MSC 1692: Terms of service API
matrix-org/matrix-spec-proposals pull request #1692
Opened 2018-10-03 19:38 UTC by turt2live

[Rendered](https://github.com/matrix-org/matrix-doc/blob/travis/msc/terms-api/proposals/1692-terms-api.md)

----

Note: This proposal is the first to try a new process where we avoid creating excess issues with locked discussions. Discussion about this proposal should happen on this PR, preferably inline where possible. 

Note 2: Riot/synapse is going ahead and trying out the registration portion of this proposal to fix a UX bug. Given UI auth has fallback support, this should not break any clients and can be easily modified in the future if this proposal were to change. Implementation is required as a proof of concept for the proposal anyways.

2018-10-03 19:53 UTC, turt2live commented
Also I just found https://github.com/matrix-org/matrix-doc/issues/1231 which doesn't appear to have a conclusion to it. This proposal also alters how https://github.com/matrix-org/matrix-doc/issues/1252 works.

2018-10-03 22:46 UTC, Half-Shot commented on proposals/1692-terms-api.md
> +            "url": "https://example.org/somewhere/terms.html",
I assume mxcs can be supported, even if it makes less sense over federation. It might be slightly nicer than uploading them to a webserver forever.

2018-10-03 22:47 UTC, Half-Shot commented on proposals/1692-terms-api.md
> +During registration it may be important to the homeserver that the user accepts a given policy.
In terms of acceptance, should the client be enforcing/suggesting scrolling to the bottom and then checking a box (like some services) or simply a :ballot_box_with_check: to say you agree.

2018-10-03 22:48 UTC, Half-Shot commented on proposals/1692-terms-api.md
> +            "version": "1.2"
It may be worth specifying the language the document is in (or for extra points, a dict of language => document) ?

2018-10-03 22:51 UTC, Half-Shot commented on proposals/1692-terms-api.md
> +            "required": true
So what's interesting is here we have documents which are required and ones which aren't, but in registration we only present documents which are required? 

I guess the only time you'd list something as non-required if the previous document being accepted is good enough, but I feel like at registration we might present documents which aren't required either.

2018-10-03 22:53 UTC, turt2live commented on proposals/1692-terms-api.md
> +            "url": "https://example.org/somewhere/terms.html",
MXCs are not supported, but there's nothing stopping someone from uploading a text document to their homeserver and dumping `https://example.org/_matrix/media/r0/download/s0mefile` into their config.

2018-10-03 22:53 UTC, Half-Shot commented on proposals/1692-terms-api.md
> +The homeserver should not prevent the use of `/sync` (and similar endpoints) but may withhold any
We might need a way to indicate that the sync has been limited in some fashion, like a key or header? I feel like filtering through sync for ``m.terms`` might be a little icky.

2018-10-03 22:53 UTC, turt2live commented on proposals/1692-terms-api.md
> +During registration it may be important to the homeserver that the user accepts a given policy.
How the client represents it is up to them. The intention is that the literal UI is a link out-of-app, so the terms aren't displayed inline.

2018-10-03 22:55 UTC, Half-Shot commented on proposals/1692-terms-api.md
> +`/_matrix/client/r0/terms` using the user-interactive authentication approach with a valid
Something feels a little wrong about adding another somewhat specific API to the already massive C-S API v.s. making the account data writable, and just having more vigorous checks in place and an acceptance key for each policy?

2018-10-03 22:55 UTC, turt2live commented on proposals/1692-terms-api.md
> +            "required": true
The documents at registration aren't exactly "required" in the same sense of the word here. The documents at registration are automatically accepted once the stage is complete, so it is entirely possible that the Code of Conduct example be included at registration.

2018-10-03 22:57 UTC, turt2live commented on proposals/1692-terms-api.md
> +The homeserver should not prevent the use of `/sync` (and similar endpoints) but may withhold any
The fact that the client is receiving a very specific error code for most other endpoints should be a good hint in my opinion. Equally, the client shouldn't be scanning the sync for anything in particular - the syncs would just appear as empty, which is not uncommon. The client really shouldn't be doing anything special with the account data event, except for making sure that it updates it's own internal stores for wherever it displays the accepted polices is.

2018-10-03 22:58 UTC, Half-Shot commented on proposals/1692-terms-api.md
> +            "url": "https://example.org/somewhere/terms.html",
Is there a reason for explicitally not allowing MXCs...

oh, is this about us eventually authenticating access to files?

2018-10-03 22:59 UTC, turt2live commented on proposals/1692-terms-api.md
> +`/_matrix/client/r0/terms` using the user-interactive authentication approach with a valid
The reason for putting UI auth on here is so that the homeserver can mandate some other checks it may need for form a digital signature. For example, the homeserver may request that the user enter their password or provide some sort of identifier that can be used to legally bind the acceptance (if needed). It's much more painful to put UI auth on PUT /account_data

2018-10-03 23:00 UTC, turt2live commented on proposals/1692-terms-api.md
> +            "url": "https://example.org/somewhere/terms.html",
No, it's about making it so clients don't have to do anything complicated with the URL because they should just be linking off of it.

2018-10-03 23:01 UTC, Half-Shot commented on proposals/1692-terms-api.md
> +The homeserver should not prevent the use of `/sync` (and similar endpoints) but may withhold any
True, true. Not really a sticking point for me if we have the error for the other endpoints.

2018-10-03 23:01 UTC, Half-Shot commented on proposals/1692-terms-api.md
> +            "required": true
Fair.

2018-10-03 23:09 UTC, turt2live commented on proposals/1692-terms-api.md
> +During registration it may be important to the homeserver that the user accepts a given policy.
![image](https://user-images.githubusercontent.com/1190097/46444386-fead6680-c72e-11e8-8c38-032a1c7adeeb.png)
^like this. The client could embed the terms if it wanted, but that's probably not recommended as iframes play badly with CSP, Access Control, and general security.

2018-10-03 23:10 UTC, turt2live commented on proposals/1692-terms-api.md
> +            "url": "https://example.org/somewhere/terms.html",
The other motivation is that people may already have their own privacy policies, etc written and may not want to link to a matrix-specific one. Therefore, they can supply a link to their regular corporate site.

2018-10-04 08:38 UTC, richvdh commented on proposals/1692-terms-api.md
> +This is described as a `m.login.terms` authentication type. The parameters for this login type
s/login type/authentication type/

2018-10-04 08:40 UTC, richvdh commented on proposals/1692-terms-api.md
> +            "url": "https://example.org/somewhere/terms.html",
obviously it's up to the HS admin, but it would presumably be sensible if these URLs were versioned (hence `.../terms-1.2.html` etc)?

2018-10-04 08:41 UTC, richvdh commented on proposals/1692-terms-api.md
> +The client is not required to supply any additional information in the auth dict to complete
it's presumably up to the HS to remember which version of the policy it supplied to the client (and hence which the user is accepting)?

2018-10-04 08:43 UTC, richvdh commented on proposals/1692-terms-api.md
> +after UI auth is started, the homeserver should present the latest version of each policy in
ehrm. Beware of the massive foot-gun that is the fact that /login doesn't currently use UI auth, because everything is awful.

2018-10-04 08:51 UTC, richvdh commented on proposals/1692-terms-api.md
> +amongst policies, the client can determine whether a policy is being updated or introduced. The
if clients have to do string-comparison on `name`s, we should specify up-front what sort of collation rules they should use (eg case-sensitivity, unicode normalisation, etc).

I'd be kinda tempted to have a separate `id` field with a limited alphabet, which also paves the way for the name to be translated depending on browser settings.

2018-10-04 08:52 UTC, erikjohnston commented on proposals/1692-terms-api.md
> +`/_matrix/client/r0/terms` using the user-interactive authentication approach with a valid
TBH, I'd rather have a separate path for something new. Even if we tried to shove this in existing APIs I would expect that a) the server would still need to implement as much stuff, b) the client would still need to implement about as much stuff and c) the spec would still need to document about as much stuff.

2018-10-04 08:53 UTC, richvdh commented on proposals/1692-terms-api.md
> +`/_matrix/client/r0/terms` using the user-interactive authentication approach with a valid
>  It's much more painful to put UI auth on PUT /account_data

how so?

(though I am inclined to agree that we're probably going to end up with a helper API to make this work...)

2018-10-04 08:55 UTC, erikjohnston commented on proposals/1692-terms-api.md
> +The homeserver should not prevent the use of `/sync` (and similar endpoints) but may withhold any
I think that we would need to be proactive in telling clients that we've shutdown their sync, as we can't really rely on clients making HTTP requests. For example, if I'm waiting for an important message that never comes through because the ToS was updated and I wasn't told, I'd be fairly annoyed.

2018-10-04 08:56 UTC, richvdh commented on proposals/1692-terms-api.md
> +but must at least include the `m.login.terms` stage in every flow. The behaviour of the stage
s/stage/authentication type/. Or "a stage using the `m.login.terms` authentication type"

2018-10-04 09:27 UTC, erikjohnston commented
This looks mostly sane I guess, though I don't really know much about registration/login.

One thing that I'm unsure of is the behaviour when we need the user to agree to an updated ToS. Locking down the APIs and returning 403s has a number of issues:

- Server side its a bit annoying to keep track of which APIs are safe to allow the user access to and which aren't. Denying everything but sync doesn't terribly worthwhile given the likelihood that clients will want to make API call when actually rendering things to client (e.g. avatars)
- Breaking people's messaging app is unlikely to make people particularly happy. I think we need to make sure that clients get proactively told that action needs to be taken, and ideally allow being notified in advance (long before the API gets blocked).

I also think it'd make more sense to return a 401 with a specific error code. That way "dumb" clients just log out and the user can log in again and accept the updated ToS. Smarter clients can interpret the 401 and show a "accept ToS" screen.

2018-10-04 13:58 UTC, turt2live commented on proposals/1692-terms-api.md
> +The homeserver should not prevent the use of `/sync` (and similar endpoints) but may withhold any
Well, there's equally nothing stopping the client from handling the terms account data update as special.

2018-10-04 14:01 UTC, turt2live commented on proposals/1692-terms-api.md
> +`/_matrix/client/r0/terms` using the user-interactive authentication approach with a valid
I just can't imagine current clients would react well to suddenly requiring ui auth on a relatively common endpoint. Even if it were sometimes used, that's a huge amount of complexity a client would have to deal with.

2018-10-04 14:02 UTC, turt2live commented on proposals/1692-terms-api.md
> +            "url": "https://example.org/somewhere/terms.html",
When I go through this for round 2 I'll do that. It is up to the admin though.

2018-10-04 14:02 UTC, turt2live commented on proposals/1692-terms-api.md
> +The client is not required to supply any additional information in the auth dict to complete
Yup

2018-10-04 14:03 UTC, turt2live commented on proposals/1692-terms-api.md
> +after UI auth is started, the homeserver should present the latest version of each policy in
... it does in the spec or I didn't read it right.

2018-10-04 14:05 UTC, turt2live commented on proposals/1692-terms-api.md
> +amongst policies, the client can determine whether a policy is being updated or introduced. The
An ID field is almost required for different language support, so I'm tempted to go that way. Without an ID, it's hard for the client to figure out which of the policies are the same.

2018-10-04 14:10 UTC, richvdh commented on proposals/1692-terms-api.md
> +after UI auth is started, the homeserver should present the latest version of each policy in
I think you didn't read it right.

It uses a similar-but-different precursor to UI auth.

2018-10-04 14:15 UTC, Half-Shot commented on proposals/1692-terms-api.md
> +`/_matrix/client/r0/terms` using the user-interactive authentication approach with a valid
> TBH, I'd rather have a separate path for something new. Even if we tried to shove this in existing APIs I would expect that a) the server would still need to implement as much stuff, b) the client would still need to implement about as much stuff and c) the spec would still need to document about as much stuff.

Sure, but if someone comes along and specs something like TOTP support which also requires UI auth to change but probably could sit well in account_data, we now have to spec this *again*. There are probably other things that orgs might also want to put behind a required auth path.

So if this is the only time ever that we want to do UI auth for an account_data value, then it make sense to have a separate endpoint.

2018-10-04 14:43 UTC, Half-Shot commented on proposals/1692-terms-api.md
> +`/_matrix/client/r0/terms` using the user-interactive authentication approach with a valid
I think that's a *bit* far fetched. This is about storing a value in a user's account data, which is far more likely to be verified manually than read receipt or a message. Also, my example was about changing a bit of auth data (in this case the key), not verifying the user's identity. Though reading it, that was probably a confusing example to use.

2018-10-04 14:54 UTC, Half-Shot commented
I agree with almost everything here, except the need for a new endpoint.

I strongly disagree with ``/terms`` unless someone can explain what makes it special enough to warrant it's own endpoint in favour of developing ``PUT /account_data`` with the *optional* ability to request auth first. It would definitely benefit future proposals, even if it doesn't save any effort for this proposal.

It seems like it's going to take the same amount of effort whichever way this goes, so why not make this endpoint generic now to save some effort for future proposals.

2018-10-04 14:58 UTC, turt2live commented
@erikjohnston 

> Breaking people's messaging app is unlikely to make people particularly happy. I think we need to make sure that clients get proactively told that action needs to be taken, and ideally allow being notified in advance (long before the API gets blocked).

There's nothing stopping the homeserver from saying a policy is not required and then later requiring it. The proposal should be fairly supportive of whatever the homeserver admin wants to do by not being overly opinionated. 

> I also think it'd make more sense to return a 401 with a specific error code. That way "dumb" clients just log out and the user can log in again and accept the updated ToS. Smarter clients can interpret the 401 and show a "accept ToS" screen.

Logging the user out sounds really bad for dumb clients. If that dumb client has e2e support (which is not impossible) then that user could lose data. This is probably another great case where a soft logout would work, although it would probably need to be carefully executed.

2018-10-04 14:59 UTC, turt2live commented
@Half-Shot 

> I strongly disagree with /terms unless someone can explain what makes it special enough to warrant it's own endpoint in favour of developing PUT /account_data with the optional ability to request auth first. It would definitely benefit future proposals, even if it doesn't save any effort for this proposal.

I'd like to see a strong use case for other cases where UI auth is helpful on the account data. As previously mentioned several times, I do not see the benefit in adding such a feature where it results in complicated client code.

2018-10-04 15:15 UTC, Half-Shot commented
Sure. I think I have failed to explain where this could also be useful, so I will write up a through explanation this evening. (This can serve as a placeholder)

2018-10-12 23:39 UTC, turt2live commented
I've made some changes to this based on the feedback above:
* Multiple languages are now supported
* An ID is introduced for each policy for clients to reference
* The login UI auth is fixed to represent the actual specification. In the future, we should consider actually cutting over to using UI auth on login and not doing half the job (which is proposed here).
* Misc wording and language changes

I have not changed the proposal regarding introduction of a new endpoint. I've spent the better part of the week thinking about whether or not it is worth it, and I'm still not convinced that having UI auth on account data makes sense for primarily backwards compatibility reasons. Older clients would likely see the 401 as the user's token suddenly not being valid and log them out, which is a lot more dangerous than having another endpoint. Although older clients would not be accessing the terms metadata as they would not understand it, I don't think the proposal to add UI auth to account data would be worth it unless it was permitted on any event type - which could cause problems when someone inevitably blanket-enables it in their homeserver. 

Ideally in a major version change of the spec we could support UI auth on most endpoints, not just account data, therefore adding an option for more security-conscious environments. For example, a homeserver may rightfully want to prevent the user from uploading content until they acknowledge that they actually own the content. Another scenario would be the homeserver requiring a user to refresh their login details after some time - previously we had a token refresh API however I don't believe it was supportive of alternative login flows, such as TOTP, being required to authenticate a user.

2018-12-11 17:33 UTC, erikjohnston commented on proposals/1692-terms-api.md
> +`/_matrix/client/r0/terms` using the user-interactive authentication approach with a valid
> Sure, but if someone comes along and specs something like TOTP support which also requires UI auth to change but probably could sit well in account_data, we now have to spec this *again*. 

You need to spec it *either way*. I really don't think that saying "This is a new POST API with this URL and has UIA" is anymore complicated than saying "this account_data type will require being behind UIA". (And note that mandating a server puts UIA on a new account data type is not-backwards compatible, and so would have to wait for a new major spec version).

OTOH completely separately, it *might* be useful to have a "secure account data" section, where writing to it (and potentially reading from it?) requires UIA. This would allow clients to store stuff " "securely" without needing a spec change.

2018-12-11 17:53 UTC, erikjohnston commented
> > I also think it'd make more sense to return a 401 with a specific error code. That way "dumb" clients just log out and the user can log in again and accept the updated ToS. Smarter clients can interpret the 401 and show a "accept ToS" screen.
> 
> Logging the user out sounds really bad for dumb clients. If that dumb client has e2e support (which is not impossible) then that user could lose data. This is probably another great case where a soft logout would work, although it would probably need to be carefully executed.

The soft logout MSC has now landed fwiw, so e2e clients should now be able to more gracefully handle getting logged out. Given that, I would really strongly prefer responding with 401 if they haven't accepted the new ToS with suitable error codes. Smart clients will do the right thing, while dumb clients will simply log out, thus forcing the user to go and accept the new terms. (Hopefully the majority of people will accept the updated ToS before it becomes required.)

My major concern with providing blank `/sync` responses is that dumb clients will just silently break rather than inform the user that action is required. This would be particularly bad on mobiles given people often won't bother opening the app (and thus start to see errors) unless they receive a push notification, but they won't receive a push notification because when the app tries to fetch the message down `/sync` it doesn't see any new messages. For a messaging app, silently dropping message is basically one of the worst things that can happen.

Having said that, we should ensure that when a client gets logged out it actually does inform the user. Otherwise logging out will be just as bad.

> I have not changed the proposal regarding introduction of a new endpoint. I've spent the better part of the week thinking about whether or not it is worth it, and I'm still not convinced that having UI auth on account data makes sense for primarily backwards compatibility reasons. Older clients would likely see the 401 as the user's token suddenly not being valid and log them out, which is a lot more dangerous than having another endpoint. Although older clients would not be accessing the terms metadata as they would not understand it, I don't think the proposal to add UI auth to account data would be worth it unless it was permitted on any event type - which could cause problems when someone inevitably blanket-enables it in their homeserver.

Agreed, as mentioned [here](https://github.com/matrix-org/matrix-doc/pull/1692#discussion_r240716004) I think it adds unnecessary complexity to both clients *and the spec*. I don't really see why people hate adding new APIs so much when they will require special casing in clients and servers anyway.

> Ideally in a major version change of the spec we could support UI auth on most endpoints, not just account data, therefore adding an option for more security-conscious environments. For example, a homeserver may rightfully want to prevent the user from uploading content until they acknowledge that they actually own the content. 

To be honest this sounds overly complicated for something that doesn't sound like it adds a huge amount of value. I'm not sure I've ever come across a site that doesn't require you to accept updated ToS upfront?

> Another scenario would be the homeserver requiring a user to refresh their login details after some time - previously we had a token refresh API however I don't believe it was supportive of alternative login flows, such as TOTP, being required to authenticate a user.

This sounds like an orthogonal concern, as its about requiring you to refresh your session rather than certain actions requiring additional authentication.

2018-12-11 17:55 UTC, erikjohnston commented
Oh, and we probably want to think a little bit about how we do the different languages, as it'll start coming up a lot more in future APIs, and it'd be sad if we added something that works just for this stuff but not others.

OTHER THAN ALL THAT, yay this is looking good, and I'm happy we're wanting to move terms of service stuff into the registration and login flows \o/

2019-06-21 19:55 UTC, turt2live commented on proposals/1692-terms-api.md
> +The homeserver should not prevent the use of `/sync` (and similar endpoints) but may withhold any
Maybe we do just add a field to `/sync` so that clients can pick up on it.

eg:
```
{
   "rooms": {...},
   "pending_terms_acceptance": true
}
```

2019-06-21 20:03 UTC, turt2live commented on proposals/1692-terms-api.md
> +`/_matrix/client/r0/terms` using the user-interactive authentication approach with a valid
For now I'm keeping the helper API in this proposal, unless people are strongly opposed to it. I have opened https://github.com/matrix-org/matrix-doc/issues/2141 to track a future protected account data API which should be used for this instead of the helper.

I don't want to block this MSC behind protected account data if at all possible.

2019-06-21 20:11 UTC, turt2live commented
I don't think soft logout was ever linked here, so here it is: https://github.com/matrix-org/matrix-doc/issues/1466

It's currently sitting in a state of needing implementation. I'm still comfortable with blocking this MSC on its inclusion in the spec, but that does mean that soft logout needs to be implemented first.

2019-06-21 20:36 UTC, turt2live commented
Right, I've updated this to close off the points raised by people. Please take another look, particularly at the last 3 commits:
* https://github.com/matrix-org/matrix-doc/pull/1692/commits/9c8100b539b5655cf8ef8b82677d76b799c8d6b7
* https://github.com/matrix-org/matrix-doc/pull/1692/commits/e963a947cf455151fff699b0bbaf826403267f43
* https://github.com/matrix-org/matrix-doc/pull/1692/commits/cfb2bc00a56391cb5bcb7ab93537daadde137641

2019-07-16 11:00 UTC, erikjohnston commented
My only query is why we both have the `required`/`soft logout` and `withheld: true` sync stuff? If ToS are required then they get logged out? So when would events get withheld?

2019-07-16 13:54 UTC, turt2live commented
Sounds like an artifact of me forgetting something. I don't think there's a reason for us to withhold events anymore because we can just soft log people out.

2021-02-17 04:20 UTC, turt2live commented
I've moved much of this proposal out to https://github.com/matrix-org/matrix-doc/pull/3012 due to those bits being unimplemented and not having much confidence in them being appropriate for use. This MSC is now just the registration bits which have had several years worth of implementation proof to them.

2021-02-17 04:20 UTC, turt2live commented
Considering this MSC has passed at least the implementation test:

@mscbot fcp merge

2021-04-01 22:36 UTC, uhoreg commented on proposals/1692-terms-at-registration.md
> +This API makes changes to the registration and login flows for UI auth, and makes use of UI
I'm guessing that the reference to the login flow and UI auth should be removed as they were part of the bit that got split off.

2021-04-01 22:36 UTC, uhoreg commented on proposals/1692-terms-at-registration.md
> +The client is not required to supply any additional information in the auth dict to complete
If the client doesn't supply any information, could this cause a race where a user registers, the server sends the terms, the user ticks the checkboxes, the terms change, the user clicks accept, and then the server thinks that the user accepted the new terms rather than the old terms?  Or is it expected that the server knows which terms the user was sent?

2021-04-01 23:31 UTC, turt2live commented on proposals/1692-terms-at-registration.md
> +The client is not required to supply any additional information in the auth dict to complete
It's expected that the server just knows - I think this came up in a previous review, so will clarify it properly.

2021-04-13 16:00 UTC, richvdh reviewed
some nitpicking about grammars

2021-04-13 16:00 UTC, richvdh commented on proposals/1692-terms-at-registration.md
> +versions. The acceptable range of characters for a version is `[a-zA-Z0-9.-]`.
Can we add `~` and `_` to this list, to match the characters which don't need url-encoding, which is a concept we've used elsewhere (eg https://github.com/matrix-org/matrix-doc/blob/rav/proposals/id_grammar/proposals/1597-id-grammar.md#opaque-ids)?

Alternatively: make it match the grammar for room versions, by removing `[A-Z]`, though I don't really think it needs to be that limited.

What is the maximum acceptable length of a policy version?

2021-04-13 16:00 UTC, richvdh commented on proposals/1692-terms-at-registration.md
> +`url` may point to any location. The implicit ID may only contain characters in `[a-zA-Z0-9_]`.
*another* random grammar?

again, what are the acceptable lengths?

2021-05-11 16:17 UTC, richvdh requested changes
^

2021-05-11 16:26 UTC, turt2live commented
@mscbot fcp cancel

2024-02-21 17:38 UTC, turt2live commented
right, another 3 years later I've addressed the latest round of feedback. Let's try to get this into the spec, finally.

@mscbot fcp merge

2024-02-21 21:42 UTC, cvwright commented on proposals/1692-terms-at-registration.md
> +            "en": {
Would it be possible to nest the localizations under another level in the JSON, to separate them from the version?

```json
{
    "policies": {
        "terms_of_service": {
            "version": "1.2",
            "localizations": {
                "en": {
```

As it stands now, parsing this thing in a language like Swift with a stricter type system is a real PITA.

2024-03-19 18:57 UTC, richvdh approved these changes

2024-03-19 18:57 UTC, richvdh commented on proposals/1692-terms-at-registration.md
> +compatibility with existing conventions around language choices in (Matrix) clients.
I'm not that familiar with this stuff, but isn't "ISO 639-1 followed by ISO 3166-1" a *subset* of BCP 47, in which case this should just be "Language codes should be BCP 47 codes".

Also, suggest linking to the authority (https://www.rfc-editor.org/info/bcp47) rather than wikipedia.

Also also I think the bit of BCP47 that actually specifies the format codes is RFC5646, so maybe refer to that.

2024-03-19 18:57 UTC, richvdh commented on proposals/1692-terms-at-registration.md
> +> not be empty.
ftr this grammar has made it into the spec in various places now ([voip](https://spec.matrix.org/v1.9/client-server-api/#grammar-for-voip-ids), [IdP IDs for SSO](https://spec.matrix.org/v1.9/client-server-api/#client-login-via-sso)).

2024-03-19 18:58 UTC, richvdh commented on proposals/1692-terms-at-registration.md
> +Regretfully, this MSC was implemented with *stable* identifiers before an unstable identifiers process
Nit: I don't think it was done regretfully; we just didn't think about it.

```suggestion
Regrettably, this MSC was implemented with *stable* identifiers before an unstable identifiers process
```

2024-03-19 19:12 UTC, turt2live commented on proposals/1692-terms-at-registration.md
> +compatibility with existing conventions around language choices in (Matrix) clients.
these are all fair points. I ended up just linking to wikipedia after having a few thousand tabs open trying to figure out where `en_US` came from - no idea which sections of the actual BCP are relevant here.

2024-03-19 19:13 UTC, turt2live commented on proposals/1692-terms-at-registration.md
> +> not be empty.
yea... we should formalize it. Can probably do so with a small MSC, or a spec clarification for "general opaque identifiers".

2024-04-03 12:54 UTC, erikjohnston commented
@turt2live is my understanding correct that Synapse already implements this (UGH)? And if so does the current MSC match the implementation?

2024-04-03 15:57 UTC, turt2live commented
> @turt2live is my understanding correct that Synapse already implements this (UGH)? And if so does the current MSC match the implementation?

Yes and yes. If you've had the unfortunate opportunity to review the original MSC here, the bits which Synapse doesn't implement were already broken out to https://github.com/matrix-org/matrix-spec-proposals/pull/3012

2024-04-15 17:21 UTC, merged

2024-04-30 17:49 UTC, richvdh commented on proposals/1692-terms-at-registration.md
> +dict. The client *should* present the user with a checkbox to accept each policy, including a link
> an empty `auth` dict

This can't be right. I'm *assuming* it means an `auth` dict which looks like:

```json
  "auth": {
      "type": "m.login.terms",
      "session": "xxxxxx"
  }
```

(ie, nothing other than the `type` and `session`).

2024-04-30 18:02 UTC, turt2live commented on proposals/1692-terms-at-registration.md
> +dict. The client *should* present the user with a checkbox to accept each policy, including a link
err, yes. UIA is complicated, and I can believe this part of the MSC was written with confusion.

It'd be the same as dummy auth: https://spec.matrix.org/v1.10/client-server-api/#dummy-auth

2024-04-30 18:03 UTC, richvdh commented
Spec PR: https://github.com/matrix-org/matrix-spec/pull/1812

2024-05-10 21:21 UTC, turt2live commented
Merged 🎉