first cut of MSC1767 for extensible events (replaces MSC1225)
matrix-org/matrix-spec-proposals pull request #1767
Opened 2019-01-01 22:59 UTC by ara4n

2019-01-02 21:51 UTC, ara4n commented on proposals/1767-extensible-events.md
> +        "m.caption": [
because arrays are for lists of fallback format representations of the same type (text caption, html caption, etc)

2019-01-02 21:52 UTC, ara4n commented on proposals/1767-extensible-events.md
> +We're skipping over defining rules for which fallback combinations to display
unconvinced, especially with the ordered lists for m.message, m.caption and m.thumbnail. grouping the contents fields into disparate types is a massive win for reuse and extensibility; having displayhints for determining when to display weird and wonderful combinations of types is the icing on the cake (and really *does* make this more complex)

2019-01-02 21:52 UTC, turt2live commented on proposals/1767-extensible-events.md
> +        "m.caption": [
ah, right. Okay. Might be worth having an example of that (unless I'm blind and there is one)

2019-01-02 22:01 UTC, turt2live commented on proposals/1767-extensible-events.md
> +We're skipping over defining rules for which fallback combinations to display
I'm not convinced that the features introduced by ordered lists are solving a real problem. I also don't see the benefit of extensible events if I can't create my own events and have them rendered. As far as I can tell, this proposal doesn't include any kind of rendering rules for when a client runs into a non-standard event type.

2019-01-02 22:17 UTC, ara4n commented on proposals/1767-extensible-events.md
> +We're skipping over defining rules for which fallback combinations to display
So if the client doesn't recognise the event type, it'd use m.message/m.text/m.html, m.thumbnail and m.file to synthesise a plausible fallback.  You're right that this needs to be explicit; something like: "if the primary type isn't recognised, show the m.message, and m.file link if present and an m.thumbnail if present".  I'd be interested if we have common use cases which wouldn't be sufficiently covered by this.

(btw i definitely think displayhints should be proposed as another MSC; just don't want this one getting stuck on it).

2019-01-02 22:35 UTC, turt2live commented on proposals/1767-extensible-events.md
> +We're skipping over defining rules for which fallback combinations to display
The proposal should definitely spell that out as it's not entirely clear what the client should be doing when it receives such an event. The common case is probably resolved with this kind of fallback, but I can think of a couple use cases which may benefit from richer parsing rules (journal and matrix-static immediately come to mind).

2019-01-02 23:01 UTC, ara4n commented on proposals/1767-extensible-events.md
> +We're skipping over defining rules for which fallback combinations to display
can you give some sample events for the journal & matrix-static use cases so i can see what you have in mind? my hunch is still that we should make display hints a separate thing

2019-01-02 23:06 UTC, turt2live commented on proposals/1767-extensible-events.md
> +We're skipping over defining rules for which fallback combinations to display
They'd be more on the rendering side of things and could potentially benefit from being told what to do. 

It's probably fine to punt display hints to its own MSC - it looked like this proposal didn't have a rendering mechanism and I really liked how display hints worked in v1.

2019-01-04 20:02 UTC, non-Jedi commented on proposals/1767-extensible-events.md
> +It's a bit arbitrary as to which fields are allowed lists of fallbacks.
To generalize this just a bit, instead of defining a `type` field which is primary display type at same level as `content`, we could have `content` itself contain a fallback list of the format:

```json
{
  "content": [
    {"m.html": "i am a <b>fish</b>"},
    {"m.text": "i am a *fish*"}
  ]
}
```

That way within the `content` structure lists would always indicate ordered fallbacks, and we could define fallback priority rather than just what the best type to display is.

2019-01-04 20:04 UTC, non-Jedi commented on proposals/1767-extensible-events.md
> +        "m.location": {
So clients are expected to compute (based on what?) which keys are for fallback representation and which are additional information?

I don't think heuristics get you far enough in figuring this out. Maybe instead have a `fallbacks` field at the same level as `content` containing a struct of keys=fallback-type, value=fallback-value; the expectation would be that the client would choose exactly one type from the `fallbacks` struct rather than being able to display multiple related types like under the `content` key.

2019-01-07 14:21 UTC, non-Jedi commented on proposals/1767-extensible-events.md
> +        "m.message": [
Better still, does `m.message` need to exist at all?

2019-01-07 14:37 UTC, Half-Shot commented on proposals/1767-extensible-events.md
> +        "m.message": [
Does `m.text` and `m.html` imply that the event is a instant message? I thought that was the point of `m.room.message` (and now `m.message`?)

2019-01-07 14:39 UTC, non-Jedi commented on proposals/1767-extensible-events.md
> +        "m.message": [
both m.text and m.html imply human readability. What additional properties are meant to be communicated by m. message?

2019-01-07 15:00 UTC, Half-Shot commented on proposals/1767-extensible-events.md
> +        "m.message": [
Not much that I can think of, honestly.

2019-01-08 12:30 UTC, ara4n commented on proposals/1767-extensible-events.md
> +It's a bit arbitrary as to which fields are allowed lists of fallbacks.
the reason I avoided doing it this way is that you can't list fallbacks of the same type - e.g. two different `m.thumbnails` (one larger and animated; the other smaller and boring).

2019-01-08 12:31 UTC, ara4n commented on proposals/1767-extensible-events.md
> +        "m.location": {
the idea is that yup, it'd be heuristics for now and might even be non-deterministic between clients. if you want more control, it'd be via display hints, which i'm going to reintroduce in another MSC to try to split them out from the core question of extensibility.

2019-01-08 12:44 UTC, ara4n commented on proposals/1767-extensible-events.md
> +        "m.message": [
so the reason to have 
```json
"type": "m.message",
"contents": {
    "m.html": "i am a <b>fish</b>",
    "m.text": "i am a *fish*"
}
```
rather than 
```json
"type": "m.message",
"contents": {
    "m.message": [
        {"m.html": "i am a <b>fish</b>"},
        {"m.text": "i am a *fish*"}
    ]
}
```
is purely to save bits and complexity for the common case. I don't see a problem with considering `m.html` and `m.text` as fully fledged first-class types, which just happen to take a string as their body.  Whether you label the event itself as an `m.message` (which happens to have empty contents for the `m.message`, but instead provides `m.text` and `m.html` fallback event representation) or an `m.html` would be up to you, although I'd suggest `m.message` for sanity.  If you called it `m.text` then you'd expect the client to prioritise the `m.text` payload over the `m.html` fallback.

Conversely, the reason to have
```json
"type": "m.message",
"contents": {
    "m.message": [
        {"m.html": "i am a <b>fish</b>"},
        {"m.text": "i am a *fish*"}
    ]
}
```
over
```json
"type": "m.message",
"contents": {
    "m.message": [
        {"mimetype": "text/html", "body": "i am a <b>fish</b>"},
        {"mimetype": "text/plain", "body": "i am a *fish*"}
    ]
}
```
is to support arbitrary mimetypes without having to somehow map them all onto `m.*` style namespaces.  This is why `m.message` is needed for the general case.

I agree this is a little arbitrary and prone to bikeshedding, but does this make more sense.

To recap:
 * The idea of `m.text` and `m.html` is to compactly describe the types of the common text fallback representations that all events can use.  They are to all intents and purposes normal types, albeit used strategically to provide fallbacks rather than used as a primary event type.  (Similarly you could have something like `m.nsfw` as an NSFW tag which would be a normal type, but very unlikely to be ever used as a primary event type).
 * The idea of `m.message` is to describe an instant message. The full contents of that message could be described by the fallback representations - or one could flesh it out in detail with an `m.message` type (and include additional stuff like the original markdown or latex representations etc).

Does that resonate any better?

2019-01-08 12:44 UTC, ara4n commented
@non-Jedi many thanks for cogitating on this and reviewing :)

2019-01-12 06:54 UTC, alphapapa commented on proposals/1767-extensible-events.md
> +We can't apply ACLs serverside to the types embedded in the event contents.
This is a tough call IMO, because it potentially adds complexity to clients.  They could render events unconditionally, but, to a certain extent, that would make them vulnerable to trolls.  Imagine a room in which only users with a certain PL could post images, and clients were responsible for enforcement: if a certain client had a bug in its conditional rendering, and all the room's mods were running clients that worked correctly, trolls could post messages that would look innocuous to mods, but users with buggy clients would see whatever the troll put in the event's other content types.  Probably not a serious concern, but something to consider.

While I am reluctant to add more complexity to clients, it probably makes sense to be consistent across all room types, to the extent practical.

2019-01-12 06:55 UTC, alphapapa commented on proposals/1767-extensible-events.md
> +    "type": "m.message",
Is that conflating content-type or MIME-type with, shall we say, event-type or event-purpose?  Or does it imply a default or base event type of `m.message`/simple-text-message?

2019-01-12 06:57 UTC, alphapapa commented
I feel like this is much clearer and simpler than the previous Google doc version.  At least, as a client dev, this doesn't scare me much.  :)  Thanks.

2019-01-13 22:30 UTC, non-Jedi commented on proposals/1767-extensible-events.md
> +        "m.location": {
I missed Travis's comments to this same effect below. Feel free to mark this one as resolved.

2019-01-13 22:32 UTC, non-Jedi commented on proposals/1767-extensible-events.md
> +It's a bit arbitrary as to which fields are allowed lists of fallbacks.
Why couldn't you?

```json
{
  "content": [
    {"m.html": "i am a <b>fish</b>"},
    {"m.html": "Why would you <b>want</b> to have two separate html messages? Who knows?"},
    {"m.text": "i am a *fish*"}
  ]
}
```

This still might not be a good proposal for other reasons, but I don't see this particular criticism.

2019-01-14 11:31 UTC, Half-Shot commented on proposals/1767-extensible-events.md
> +        "m.message": [
I wonder if we really want to limit it to just `m.text` and `m.html` for the IOT use case. That's probably one of the best examples of wanting to save bits, and if you are just wanting to send simple values into a room, you could easily end up with:

```JSON
"type": "uk.half-shot.temperature",
"contents": {
    "uk.half-shot.temperature.celsius": 46.5,
}
```

which makes me wonder about @non-Jedi 's proposal of representing these shorthand forms in state, as that would undoubtedly be useful for this use-case.

2019-01-14 17:11 UTC, alphapapa commented on proposals/1767-extensible-events.md
> +        "m.message": [
Seems to me that, for custom event types, interpretation should be up to the client.  So, in that example, why not just use:
```json
"type": "uk.half-shot.temperature",
"contents": 46.5
```
Or if it needed to send more than one value, why couldn't it just do:
```json
"type": "uk.half-shot.temperature",
"contents": {
    "temperature.celsius": 46.5,
    "something-else": 0.72
}
```
IOW, why would each key need to be fully namespaced for custom events?

2019-01-14 17:37 UTC, ara4n commented on proposals/1767-extensible-events.md
> +        "m.message": [
@non-Jedi, no i don't think i flipped them around.

@Half-Shot: long event keys are not too bad as they compress excellently. But adding in structure that otherwise wasn't there at all probably isn't great, hence trying to avoid it.

@alphapapa: yes, one could do completely custom event formats like that, but then you lose the whole ability to supply fallbacks, which is what we were trying to provide, and so we end up back at square 1...

2019-01-14 19:37 UTC, alphapapa commented on proposals/1767-extensible-events.md
> +        "m.message": [
@ara4n Maybe I'm misunderstanding the intended use-case then.  In this example of what appears to be an IOT thermometer which uses a custom event type, is a fallback type necessary?  I wouldn't expect (or necessarily want) standard clients, like Riot, to display a message for such events, at least, not by default.  If I needed to see such events, e.g. while debugging the IOT device, I would probably want Riot to simply display raw events in the event list.

From the IOT device's programmer's perspective, I imagine he would want requirements to be as minimal as possible, i.e. the most minimal event, without having to provide fallbacks for clients that aren't the intended target of the event.

I guess I'm missing something.  Sorry if there's context I haven't seen.

2019-01-14 19:55 UTC, Half-Shot commented on proposals/1767-extensible-events.md
> +        "m.message": [
@alphapapa It might be specific to your idea, but certainly I'd *like* to see fallback text for any event that my client doesn't natively understand for debugging/fun purposes. Of course, you might want to configure your device to not send fallback in really constrained environments (which is also okay, you would do something similar to what we already have).

The major advantage of this proposal is you can write thermometer events that have optional text content to display in a client in a prettier format than raw data.

The *other* advantage is you could technically have two types of non-renderable content: One could be a generic sensor type which would show up on say, a dashboard app. And then you could have a branded event type which would contain extra info about your specific sensor that might only apply to a specific app.

2019-01-14 19:56 UTC, Half-Shot commented on proposals/1767-extensible-events.md
> +        "m.message": [
Also it would be nice to finally be able to do things like have Twitter tweets under their own event type while still being render-able in $client. At the moment you have to make things into a `m.room.message` or they won't show up at all :/.

2019-01-14 20:11 UTC, Half-Shot commented on proposals/1767-extensible-events.md
> +Given the disruption of migrating clients & bridges to the new event shape, this
The migration path definitely needs to be known before this can land in spec, because I'd like for at least all the major SDKs and clients to be quick on the uptake to avoid everyone clinging to `m.room.message` as the most compatible option.
My suggestion would be for SDKs to start sending `m.message` in helper functions, and *by default* they should translate `m.message` messages into `m.room.message` where possible. Almost all the JS based bridges rely on this consistent format and it would be good to let developers gradually make changes to their code rather than suddenly expecting them to adapt.
Hopefully after 2-3 months a new breaking version could be written for the JS-SDK which makes `m.message` the default everywhere which would convert inbound `m.room.message`s into `m.message`.

2019-01-14 20:13 UTC, Half-Shot commented on proposals/1767-extensible-events.md
> +should probably land after S2S r0.
Sidenote: Does changing the format bugger up push rules at all?

2019-01-14 22:44 UTC, ara4n commented on proposals/1767-extensible-events.md
> +We can't apply ACLs serverside to the types embedded in the event contents.
So, i totally agree that a typical client developer shouldn't have to worry about E2EE.

However, I am increasingly wondering if in the longer term (like 2-3 years away) we may find ourselves E2EEing everything everywhere.  The reasons are:
 * Dogfooding E2E;
 * Mitigating legal risk for server admins if some obnoxious content from a public room ends up on their server.
 * We start to see publicness as more of a spectrum - just because a room is theoretically open to anyone from the public, it doesn't mean that everyone knows how to find it, or that its contents should be unencrypted.
 * I really hope that we will provide a matrix daemon service which can offload all the E2E lifting from a typical Matrix client.  So a typical implementor will talk CS API to the daemon listening on localhost, which dutifully sits there encrypting/decrypting and proxying through to your actual server. In future, the server may also optionally sit clientside. At which point E2E becomes much more prevalent.  Such a daemon could also offload the finicky business of enforcing event ACLs clientsid.

In practice, though, I honestly don't think that enforcing ACLs clientside is /that/ big a deal.  It's the sort of thing that you skip in the first implementation and then find yourself adding the first time someone abuses it.

As a result, I feel that designing features which only work on non-E2E feels is a bit of a bad smell.

Would be interested in what others of @matrix-org/spec-core-team think tho.

2019-01-14 22:50 UTC, ara4n commented on proposals/1767-extensible-events.md
> +    "type": "m.message",
@non-Jedi i covered this in one of the other threads, but from my perspective, it'd valid to have an m.message event with a null content (other than the fallback reps). it'd also be technically valid to have an m.html event (treating the fallback as the primary type), but a bit confusing imo - it'd be nicer if clients just looked for `m.messages` for IMs rather than having to know that some clients disguise IMs as `m.text` or `m.html` for reasons unknown.  So whilst it's valid, i'd suggest recommending against it.

@alphapapa yes, I guess it's kinda conflating content-type with event-purpose. so let's not do it.

2019-01-14 22:53 UTC, ara4n commented on proposals/1767-extensible-events.md
> +It's a bit arbitrary as to which fields are allowed lists of fallbacks.
oh, yeah, sorry - i thinkoed. so yes, i think the difference between:

```json
{
  "content": [
    {"m.html": "i am a <b>fish</b>"},
    {"m.html": "Why would you <b>want</b> to have two separate html messages? Who knows?"},
    {"m.text": "i am a *fish*"}
  ]
}
```

and

```json
{
  "content": {
    "m.html": [
        "i am a <b>fish</b>",
        "Why would you <b>want</b> to have two separate html messages? Who knows?"
    ],
    "m.text": "i am a *fish*"
  }
}
```

is fairly subjective. I personally prefer putting the lists per-key rather than muddling them all together in a backwards-incompatible way, but i guess it means you need prior knowledge (or implement displayhints) at how to order types with respect to one another.

Hum.

2020-01-14 13:57 UTC, florianjacob commented
I wonder what should happen if a custom *state* event is extended, e.g. with a text fallback? It could make sense to store the temperature example as state event, keyed by sensors / sensor location, and then the home automation system can directly query the current state and does not have to bother with syncing & filtering until the correct one is found. Still, as custom state events are invisible for normal clients, extending them with a non-state-events to associate a fallback or other one-off / change-related information could help, though that should probably not end up in the actual room state…

I guess “the whole thing is now a state event with all content as value” would also work out, though I think the semantics thould be specified in the MSC.

Example:
```
{
    "type": "net.arasphere.temperature",
    "state_key": "living_room",
    "content": {
        # one-off non-state events associated with the state change,
         # but not needed in the actual room state?
        "m.text": "The living room temperature rose by 1.5C. It is now 37C",
        "m.html": "The living room temperature rose by <font color='#f00'1.5C</font>. It is now <font color='#f00'>37C</font>",
        "net.arasphere.temperature.diff": {
            "temperature_rise": 1.5
        }
        # actual state event?
        "net.arasphere.temperature": {
            "temperature": 37.0
        }
    }
}
```

2020-09-03 15:58 UTC, bmarty commented on proposals/1767-extensible-events.md
> +        "m.html": "i am a <b>fish</b>"
Could we write
```
        "m.text": "i am a fish",
        "m.markdown": "i am a *fish*",
        "m.html": "i am a <b>fish</b>"
```
instead?

2020-09-03 16:11 UTC, bmarty commented on proposals/1767-extensible-events.md
> +        "m.html": "i am a <b>fish</b>"
Also the problem with that approach is that it duplicates the content of the message itself. For a small sentence like `i am a fish` it is ok, but for long text, it could explode the size of the Event.
Maybe we could separate the text itself and the formatting for instance:
```json
{
   "m.text": "i am a fish",
   "m.tags": [
      {
         "start":7,
         "end":10,
         "type":"b"
      }
   ]
}
```
`b` is for bold, and any other tags could be supported, with extra key (for instance `link` with extra key `href`, etc.)
It can then be rendered by the clients at runtime, using the preferred format (Html for Web clients, SpannableString for Android, etc.), and ignoring what is not supported.

2020-09-04 15:53 UTC, Dominaezzz commented on proposals/1767-extensible-events.md
> +        "m.html": "i am a <b>fish</b>"
In addition, the duplication gets worse with internationalisation.

Might as well merge them together into a rich text type, like so.

```json
{
    "type": "m.message",
    "content": {
        "m.rich_text": [
            {
                "type": "plain",
                "body": "i am a "
            },
            {
                "type": "bold",
                "body": "fish"
            }
        ]
    }
}
```

Simple clients can just concatenate all the `body`s together.

Although, nested tags complicates things. e.g. `<b><a href=".....">fish</a></b>`

2020-09-06 04:54 UTC, alphapapa commented on proposals/1767-extensible-events.md
> +        "m.html": "i am a <b>fish</b>"
IIUC, both of these ideas would mean that the event would not contain a simple string representation of the whole message.  Clients would have to assemble the pieces just to output a whole, plain-text message.

I can't exaggerate how painful this would be for client authors.  The Internet was built on simple, plain-text protocols, like HTTP, HTML, IRC, etc.  Please do not discard the wisdom inherited from those traditions.  

If you're concerned about size, plain text, Markdown, and HTML all compress well.

Speaking for myself, as the author and maintainer of a somewhat niche Matrix client: if Matrix events were like this, I would never have bothered.  The protocol is already complicated to deal with in many ways.  At some point, dealing with it stops being fun and becomes tedious work, work for which authors of free clients are not compensated.  Please, keep it simple.

2020-09-06 07:52 UTC, bmarty commented on proposals/1767-extensible-events.md
> +        "m.html": "i am a <b>fish</b>"
There is a simple text version in my idea.
Also good compression ratio will not concern encrypted events, so I maintain the idea that we should not duplicate the text itself. Another argument: the text could be different for each format!

```json
"content": {
        "m.text": "i am a *fish*",
        "m.html": "i am a <b>dog</b>"
}
```
Different clients would not display the same text in this case.

This is already the case today and I'm not comfortable with that.

2020-10-20 08:50 UTC, Sorunome commented on proposals/1767-extensible-events.md
> +### m.file
Why do we need other types than `m.message`? Why can't an m.message just contain a file / image / whatever?

2020-11-30 06:36 UTC, MurzNN commented on proposals/1767-extensible-events.md
> +    "content": {
I think that use array instead of object in `content` will give much more flexibility to current implementation and future improvements, because will allow to add several items of same type. But simple change of object to array will broke fallback, so we can select new key for it, something like `contents` or `items`, `elements`.

And for fallback - we will keep `content` object and put in it the rendered aggregated fallback display of all complex event content items, here is example:
```json
{
  "type": "m.message",
  "contents": [
    {
      "msgtype": "m.text",
      "body": "Invite to Party at Bob's House",
      "format": "org.matrix.custom.html",
      "formatted_body": "Invite to Party at <i>Bob's house</i>"
    },
    {
      "msgtype": "m.calendar.request",
      "version": "2.0",
      "summary": "Party at Bob's house",
      "vEvent": {
        "dtStart": {
          "date": "20180207T150000",
          "tzId": "Europe/London"
        },
        "dtEnd": {
          "date": "20180207T180000",
          "tzId": "Europe/London"
        }
      }
    },
    {
      "msgtype": "m.file",
      "uri": "mxc://matrix.org/auiheiuh1eqwd",
      "mimetype": "text/calendar",
      "name": "bobs-party.ics",
      "size": 1246
    },
    {
      "msgtype": "m.location",
      "uri": "geo:37.786971,-122.399677;u=35",
      "description": "123 Fake Street - first part"
    },
    {
      "msgtype": "m.location",
      "uri": "geo:38.786971,-123.399677;u=35",
      "description": "234 Real Street - second part"
    },
    {
      "msgtype": "m.image",
      "uri": "mxc://localhost/JWEIFJgwEIhweiWJE",
      "info": {      
        "width": 256,
        "height": 256,
        "mimetype": "image/jpeg",
        "size": 1024000
      }
    }
  ],
  "content": {
    "msgtype": "m.text",
    "body": "Invite to Party at Bob's house\nDate: Feb 7th, 3pm\nLocations: [37.786971,-122.399677;u=35] (123 Fake Street - first part); [geo:38.786971,-123.399677;u=35] (234 Real Street - second part)\nFile: mxc://matrix.org/auiheiuh1eqwd>bobs-party.ics\nImage: mxc://localhost/JWEIFJgwEIhweiWJE",
    "format": "org.matrix.custom.html",
    "formatted_body": "Invite to Party at <i>Bob's house</i>\nDate: Feb 7th, 3pm\nLocations: [37.786971,-122.399677;u=35] (123 Fake Street - first part); [geo:38.786971,-123.399677;u=35] (234 Real Street - second part)\nFile: <a href=mxc://matrix.org/auiheiuh1eqwd>bobs-party.ics</a>\nImage: <img src=mxc://localhost/JWEIFJgwEIhweiWJE />"
  }        
}
```
What do you think about this idea?

2020-11-30 07:26 UTC, MurzNN commented on proposals/1767-extensible-events.md
> +    "content": {
For help Matrix clients to understand which version to display (try to render each item by himself, or simply display the fallback text), we can also add the item type, that describe which features client must support for properly render all by himself, something like `features_used: ['MSC1234', 'MSC2345']` or `client_server_version_used: r0.7.2`.

2020-12-01 09:49 UTC, MurzNN commented on proposals/1767-extensible-events.md
> +    "content": {
This way also can be confused with allowing several items of same type (for example, 3 `m.text` items), but we can handle this via joining text of all `m.text` items into one `contents.body` field, and have similar solutions for other types.

2021-02-28 01:25 UTC, hummingbard commented
Are we close to reaching a general agreement on this? I'm not familiar with how the MSC process works. 

There was some [discussion on HN](https://news.ycombinator.com/item?id=26277602) yesterday about Hummingbard's custom events and I would love to get this sorted out early on. There are a lot of good comments here and being very new to Matrix, I'm not exactly sure why certain approaches might be better than others, or more idiomatic if you like. 

With regards to the top comment on the HN page by @ara4n, my initial reasoning was that Hummingbard events should probably not have a fallback at all, so that when we are able to integrate Hydrogen in the future, social posts and IM messages can stay separate. This would let Hummingbard have a popup chat in every space - with custom events rendering only on social timelines, and IM messages isolated to the popup.

I do see the value of having _some_ fallback though. Right now, Hummingbard uses a custom `com.hummingbard.post` type for posts. Perhaps it would be better to switch back to `m.room.message` so that post bodies at least render on Element, and events sent from Element render on Hummingbard.

What is likely the best way to separate events on Hummiingbard's side, while letting Element render everything? Keep in mind that Hummingbard is solely dependent on Dendrite so we're limited by it's filtering abilities.

That leaves things like multiple images/links/attachments. I quite like the array approach by @MurzNN .

@ara4n if you have the time to go through some current posts on Hummingbard, or create some through the site on our [test](https://hummingbard.com/test) space so we can work this out, I'd highly appreciate it.

2021-02-28 02:11 UTC, ara4n commented on proposals/1767-extensible-events.md
> +equivalent to the longer form `m.message` example below:
> "text and HTML are special and should be allowed on ANY event type and hence don't follow these mixin rules

this is precisely the intention.

2021-02-28 02:30 UTC, ara4n commented on proposals/1767-extensible-events.md
> +### m.file
The proposal is that the event type describes the type of the data in that event.  So an instant message would be an `m.message`; an image would be an `m.image`; a file would be an `m.file`, so the typing is more useful and descriptive and you can filter based on it.  It means you use the same mechanism for displaying a fallback for a custom event type as a normal event type.

2021-02-28 02:34 UTC, ara4n commented on proposals/1767-extensible-events.md
> +    "content": {
My concern about letting people bundle together load of different items in a single event is:
 * It encourages folks to bundle unrelated things together, making events non-atomic
 * You have no way of linking to the component parts
 * It would complicates the spec
 * It makes the events big and encourages people to hit up against the 65K limit
 * Relations *should* provide a much more flexible way of bundling together a set of related events

2021-02-28 02:40 UTC, ara4n commented on proposals/1767-extensible-events.md
> +            "url": "mxc://matrix.org/asdjkhcsd",
The reason I didn't is because the event should be processable as a plain old `m.file` by a client that doesn't know how to handle `m.image` (or `m.video` or `net.arasphere.weirdformat`).  But you're right that the field duplication is bugging me.

Perhaps the right solution is to treat `m.thumbnail` as a nested event, and embed within it its own `m.file` and `m.image`.  The only reason i didn't was to special-case for simplicity, but with a fresh pair of eyes it certainly looks a bit jarring.

2021-02-28 02:42 UTC, ara4n commented on proposals/1767-extensible-events.md
> +            "url": "mxc://matrix.org/asdjkhcsd",
actually, if we treat `m.thumbnail` as nested events then we get stuck into whether they need captions or not, etc.  having them as a special-case (rather than heading off re-creating displayhints) feels like the least evil.

2021-02-28 03:47 UTC, MurzNN commented on proposals/1767-extensible-events.md
> +    "content": {
> It encourages folks to bundle unrelated things together, making events non-atomic

Any way all clients must render each event as full single "atom" of timeline, so aggregating it from many events will be superfluous routine.

I can't present the situation, when we need to show only part of event (excluding media item content, that is already the relation to mxc). 

All items of the event is the parts of it, and must not be considered as independent events. 

> You have no way of linking to the component parts

Yes, but situations when we need link to some part of event are very rare. And, if very needed, we can link to numeric serial number of needed item in array.

Sometimes we need to quote some paragraph of event text to reply on event, but this isn't means that we must split the text paragraphs to separate items. 

> It makes the events big and encourages people to hit up against the 65K limit

Yes, but pasting long text in simple m.message event can break this limit too ;)

> Relations should provide a much more flexible way of bundling together a set of related events

Relations are not disappearing, each relation can be part of current event array, but in needed place (eg between two text items), instead of the separate array like now (that make impossible to insert one needed relation in middle of event, and others - at end of it).

2021-02-28 04:54 UTC, MurzNN commented on proposals/1767-extensible-events.md
> +### m.file
In most cases, separate images/files are not useful without context (text description), [here](https://github.com/matrix-org/matrix-doc/pull/2529#issuecomment-736373314) is more detailed description of this problem.

And when we found the event with interesting image, we must immediately find the text event, that referenced to this image (describes it). So why not to store this image directly in that event, instead of have 2 references (`m.message` > `m.image` > mxc url to image).

At wider look, current `m.image` and `m.file` events are already not actual events, but references to file via `mxc` url, so why we must use double references to simply insert image inside text? ;-)

2021-02-28 10:43 UTC, MurzNN commented
> I do see the value of having _some_ fallback though. Right now, Hummingbard uses a custom `com.hummingbard.post` type for posts. Perhaps it would be better to switch back to `m.room.message` so that post bodies at least render on Element, and events sent from Element render on Hummingbard.

I see two options to implement this:

1. Use the custom `com.hummingbard.post` type for post, and subsequent `m.room.message` event, that contains the teaser (announce, spoiler) of that event (title text and first part of body text), with link to full post.

2. Reuse the `m.room.message` event with filling the teaser into `body` event (like in option 1), and all additional info to separate `com.hummingbard.post` array, something like this:
```json
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.text",
    "body": "<h1>The awesome story</h1><p>A long time ago in a galaxy far, far away...</p><a href='...'>Read full post</a>",
    "hummingbird": [
      {
        "msgtype": "m.text",
        "body": "The first part of full text of story, located before image.",
      },
      {
        "msgtype": "m.image",
        "url": "mxc://example.com/KUAQOesGECkQTgdtedkftISg",
        "body": "Image 1.jpg",
        "info": {
          "mimetype": "image/jpg",
          "size": 1153501,
          "w": 963,
          "h": 734,
        }
      },
      {
        "msgtype": "m.text",
        "body": "The ending text of full story after image.",
      }
    ]
  }
}
```

2021-03-23 06:25 UTC, erkinalp commented on proposals/1767-extensible-events.md
> +    "content": {
> It would complicates the spec

Slack, Discord, Guilded and Facebook have similar rich embeds and they handle it just fine.
> It makes the events big and encourages people to hit up against the 65K limit

Jumbo event support may be added if required.

2021-03-26 00:06 UTC, kevincox commented on proposals/1767-extensible-events.md
> +        "m.html": "i am a <b>fish</b>"
Encrypted events can compressed before encryption (with some care).

2021-03-26 00:07 UTC, kevincox reviewed
github wants me to write something in this box.

2021-03-30 22:18 UTC, turt2live commented on proposals/1767-extensible-events.md
> + 3. Clients don’t know how to render unknown event types.
Where it does solve case 1 is by standardizing what certain data structures would look like, such as location data, which can be appended to any event to show a "this was sent [here]" sort of UX. Largely though, yes, anyone could shove a `com.example.coords` field onto an event and be fine, but that might not render correctly on all clients in that deployment.

2021-03-31 00:46 UTC, turt2live commented on proposals/1767-extensible-events.md
> +        "m.html": "i am a <b>fish</b>"
Compressible formats sounds like something that would be best covered by another MSC. The conversation this invokes ends up being long and complicated, and thus ideal for a dedicated MSC.

2021-03-31 00:49 UTC, turt2live commented on proposals/1767-extensible-events.md
> +        "m.message": [
(low bandwidth, such as IOT, is probably best handled by dedicated MSCs like https://github.com/matrix-org/matrix-doc/pull/3079)

2021-03-31 00:58 UTC, turt2live commented on proposals/1767-extensible-events.md
> +We can't apply ACLs serverside to the types embedded in the event contents.
for the record, 2-3 years later we already have use cases where entire servers are encrypting every room they create, sometimes to the detriment of usability for the sake of security (tens of thousands of devices in multitudes of rooms). Clients already have to do client-side validation for encrypted events, and typically make decisions on what to render, only to change that when something in the environment changes (as Matthew mentions). 

We also have a daemon now, making a lot of the work offloaded for typical clients and even most bots.

It's a couple years late, but my feeling as a SCT member is that we should definitely not exclude encryption. It's critical to the protocol now.

2021-03-31 00:59 UTC, turt2live commented on proposals/1767-extensible-events.md
> +should probably land after S2S r0.
it makes the default ones a bit annoying - we should open a separate MSC to handle that.

2021-03-31 01:20 UTC, turt2live commented on proposals/1767-extensible-events.md
> +### m.message
um, emotes and notices have gone missing.

2021-03-31 07:19 UTC, ShadowJonathan commented on proposals/1767-extensible-events.md
> +        "m.html": "i am a <b>fish</b>"
I would recommend making a distinction between CommonMark and GFM Markdown (or any other variant), to align converstion

2021-03-31 07:22 UTC, ShadowJonathan requested changes

2021-03-31 07:22 UTC, ShadowJonathan commented on proposals/1767-extensible-events.md
> +                "mimetype": "text/markdown",
```suggestion
                "mimetype": "text/markdown+commonmark",
```

Maybe it's useful to differentiate between the different types of markdown, to avoid conflicts in the future, were we ever to switch

2021-04-02 11:14 UTC, kevincox commented on proposals/1767-extensible-events.md
> +We can't apply ACLs serverside to the types embedded in the event contents.
I agree. E2EE should be the first priority of any design without an explicit reason why it shouldn't. This is because non-encrypted rooms are almost always automatically handled by any design that works for E2EE and we don't want to have two specs for each feature (that would put a real burden on clients).

2021-04-02 11:16 UTC, kevincox commented on proposals/1767-extensible-events.md
> +                "mimetype": "text/markdown",
I wonder if it is best for clients to convert the HTML to markdown so that it works for whatever variant they use. I don't know if we want markdown to be part of the protocol even if it is listed what type of even it uses. On the other hand when editing your own message in your own client you probably want to see the original markdown. If we are going to make it part of the protocol I would recommend we just pick one.

2021-05-10 10:33 UTC, Biep commented
I was told the following might belong here:

**Give image/file posting its own eventType**
*That way it can be assigned its own power level, allowing people to post messages but not images.  This can help fight image spamming.  It can also be useful in rooms where public resources are shared, and the files section should not get polluted.*

2021-05-10 18:33 UTC, MurzNN commented
> This can help fight image spamming. 

There are too many spam vectors, so restricting only one will give very tiny profit, comparing to user restriction of attaching multiple files to one event, like in many other messenger

2021-06-16 05:58 UTC, erkinalp commented on proposals/1767-extensible-events.md
> +Similar semantics apply to videos, audio, etc. This has a risk of potentially running up against the
#3052 defines how to include the waveform, that can be reused if wanted.

2021-06-25 19:44 UTC, turt2live commented on proposals/1767-extensible-events.md
> +### m.file
to consider: what does encryption look like?

2021-12-07 21:37 UTC, turt2live commented on proposals/1767-extensible-events.md
> + 3. Clients don’t know how to render unknown event types.
I've ultimately rewritten the description to better describe this. Please open a new thread if this feels unresolved :)

2021-12-07 21:39 UTC, turt2live commented on proposals/1767-extensible-events.md
> +equivalent to the longer form `m.message` example below:
I believe I've clarified this in a refactoring of some of the MSC. If not, please open a new thread.

2021-12-07 21:40 UTC, turt2live commented on proposals/1767-extensible-events.md
> +    "type": "m.message",
I'm not entirely convinced that we should let the primary type support an `m.html` and `m.text` - `m.message` with appropriate `content` is just as complex to render by a client.

2021-12-07 21:41 UTC, turt2live commented on proposals/1767-extensible-events.md
> +        "m.html": "i am a <b>fish</b>"
Markdown isn't really safe to include at the spec level whereas HTML can be defined very nicely. Maybe once we solve markdown in the spec more generally, but for now I'm extremely hesitant to open the can of worms that is markdown.

2021-12-07 21:42 UTC, turt2live commented on proposals/1767-extensible-events.md
> +        "m.html": "i am a <b>fish</b>"
(marking as resolved to indicate the concern has been addressed)

2021-12-07 21:45 UTC, turt2live commented on proposals/1767-extensible-events.md
> +        "m.message": [
I *think* this thread is resolved, but if not then a more concise concern in a new thread would be appreciated.

2021-12-07 21:46 UTC, turt2live commented on proposals/1767-extensible-events.md
> +### m.file
I believe Matthew's comment addresses this thread. Please open a new thread if feeling otherwise.

2021-12-07 21:47 UTC, turt2live commented on proposals/1767-extensible-events.md
> +    "content": {
At a glance this thread looks like discussion around display hints and multiplexing, which has zero interest in being included in this MSC. Other MSCs are welcome to argue for their inclusion.

2021-12-07 21:48 UTC, turt2live commented on proposals/1767-extensible-events.md
> +                "mimetype": "text/markdown",
I'm ripping out all markdown references because it doesn't work properly within the confines of the spec.

2021-12-07 21:51 UTC, turt2live commented on proposals/1767-extensible-events.md
> +It's a bit arbitrary as to which fields are allowed lists of fallbacks.
Changing `content` to be an array sounds extremely complicated from a spec perspective - we favour objects for their extensibility, and the content is already an event. Making it suddenly an array would break all sorts of details within servers and clients.

The `content` array does look cleaner, but I don't think that's enough of a justification to break the protocol at this point in time. A future MSC is welcome to figure this out.

2021-12-08 00:03 UTC, turt2live commented on proposals/1767-extensible-events.md
> +            "url": "mxc://matrix.org/asdjkhcsd",
I've tried to make the fields a bit less duplicated in https://github.com/matrix-org/matrix-doc/pull/3552

2021-12-08 00:06 UTC, turt2live commented on proposals/1767-extensible-events.md
> +should probably land after S2S r0.
punted to https://github.com/matrix-org/matrix-doc/issues/3555 as a future MSC.

2021-12-08 00:07 UTC, turt2live commented on proposals/1767-extensible-events.md
> +We can't apply ACLs serverside to the types embedded in the event contents.
I plan to move a lot of this discussion to a future MSC with placeholder https://github.com/matrix-org/matrix-doc/issues/3556 - resolving until then.

2021-12-08 00:11 UTC, turt2live commented
Just for observers: I've moved quite a bit of this out to separate MSCs in hopes of not breaking github too much further. The core schema and base types for text are still here, but everything else has been moved to different MSCs (some of which are placeholders).

To my knowledge, all feedback so far has either been responded to or considered in the design of the broken out MSCs. Please take a look, but do note there's *a lot* of reading material.

This MSC has also been updated to incorporate a lot of the feedback that has been raised both generally and from other MSCs which have already tried to use this system.

If you haven't read the MSC in a while, please give it a fresh set of eyes :)

2021-12-08 21:13 UTC, ShadowJonathan commented on proposals/1767-extensible-events.md
> +            "temperature": 37.0
```suggestion
            "temperature": 37
```

I'm fairly sure that floats are still banned

2021-12-08 21:55 UTC, turt2live commented on proposals/1767-extensible-events.md
> +            "temperature": 37.0
it's also a hypothetical

2022-01-12 23:21 UTC, turt2live commented
This has been proven in multiple clients by proxy of other MSCs (see PR description). There are explicit implementations in the PR description as well for this MSC, for good measure.

Noting that this MSC covers *only* the structure and text areas of events, I think this is ready to move forward. The other MSCs, covering images, files, etc, are expected to be reviewed on their own and should be using the schema proposed here.

General reminder that at this point bikeshed isn't appreciated: if you are extremely concerned with the name of a field, please bring it up in #matrix-spec and not here (unless it is so blocking, in which case the SCT can `@mscbot concern` it). Additionally, any comment *not* in a thread has *not* been considered - please convert your concerns to comments on the diff if you expect resolution.

@mscbot fcp merge

2022-01-13 00:04 UTC, deepbluev7 commented on proposals/1767-extensible-events.md
> +preferred.
If we are not going to map all event types into a top level key like `m.markdown`, `m.json` etc anyway, I can't see a strong reason to have `m.html`. That seems to only add complexity with marginal usefulness. You save less around 10 characters, but you need to include a text representation anyway. I can somewhat understand having a shorthand for `m.text`, because there you can actually save some data for IOT or whatever low bandwidth projects. But what is the argument for having a shorthand for `m.html`? Can we just require that to be in `m.message` with a mimetype of `text/html`?

2022-01-13 00:31 UTC, turt2live commented on proposals/1767-extensible-events.md
> +preferred.
Most clients send out text+html already, so the theory is instead of a really awkward `m.message` array in the middle of their send event code path we can just shorthand it, particularly if the client doesn't mix the generation and parsing concerns.

For clients which do mix the generation and parsing concerns, it's mostly moot to them because they won't see the event content being constructed in their code.

Eg:
```js
client.sendEvent(roomId, "m.message", {
  "m.text": userInput,
  "m.html": htmlUserInput,
});
```

2022-01-13 01:03 UTC, deepbluev7 commented on proposals/1767-extensible-events.md
> +preferred.
That sounds like a nice API, that an SDK would add and not something, that needs to be encoded in the spec. Especially since it makes the parsing quite a bit more ugly, since you always need to parse the array first, otherwise fallback to `m.html`, then fallback to `m.text` and lastly, in the transition phase, fallback to `body`. Especially since statically typed SDKs might want to add specific types for MHtml anyway and handling special cases can be quite awkward.

2022-01-13 01:20 UTC, turt2live commented on proposals/1767-extensible-events.md
> +preferred.
The original thread was https://github.com/matrix-org/matrix-doc/pull/1767#discussion_r245401460 if it helps - open to more feedback/ideas if `m.html` feels spurious (I personally don't really have a preference)

2022-01-13 01:29 UTC, deepbluev7 commented on proposals/1767-extensible-events.md
> +preferred.
Yeah, I read that one, but the primary argument seems to be compactness and that makes sense for `m.text`, but not `m.html` (since an event needs to have a certain minimum length and complexity for it to even include html formatting) and imo we should have as few special cases as possible in the already more complex extensible event. Most SDKs will probably just automatically canonicalize the event somewhat, but still, every special case is just a new opportunity for a new bug.

2022-01-25 18:45 UTC, richvdh reviewed
I'm afraid I'm finding this MSC super confusing. I'm going to stop for a bit.

2022-01-25 18:45 UTC, richvdh commented on proposals/1767-extensible-events.md
> +cannot be used to multiplex data into a single event. Relationships between events
This sentence seems important because of the MUST, but I don't really understand it what is trying to tell me. There are no event ids involved here (afaict), so how does an event type refer to different events?

2022-01-25 18:45 UTC, richvdh commented on proposals/1767-extensible-events.md
> +Because events are generally sent in the context of a room, all primary types introduced
is this a different sort of "primary type" to the "primary type" defined at line 34?

2022-01-25 18:45 UTC, richvdh commented on proposals/1767-extensible-events.md
> +### Text messaging
Is this an example of how we're applying the changes described above? or additional changes?

2022-01-25 18:45 UTC, richvdh commented on proposals/1767-extensible-events.md
> +    which might typically be just the ones listed below.
this is rendering weirdly, fyi

2022-01-25 18:45 UTC, richvdh commented on proposals/1767-extensible-events.md
> +        "m.text": "i am a *fish*", // doesn't have to be markdown, but useful as a "fallback" for HTML
so `m.text` are special cases which are only valid in the content of an `m.message`? maybe not the best example to go in with if so?

2022-01-25 18:45 UTC, richvdh commented on proposals/1767-extensible-events.md
> +9. `m.message` (implying `m.text` and `m.html` too)
I feel like having this list way earlier would have saved a whole lot of confusion on my part as I was reading this MSC.

2022-01-25 18:45 UTC, richvdh commented on proposals/1767-extensible-events.md
> +6. `m.location` (from [MSC3488](https://github.com/matrix-org/matrix-doc/pull/3488))
Am I to understand that these are defined as things that have meaning within a `content` but not within a `type`?

2022-01-25 18:47 UTC, richvdh commented on proposals/1767-extensible-events.md
> +for rich messaging as we never previously agreed a way of expressing alternate
Since I don't understand any of the technical content, some bikeshed-painting.

```suggestion
messaging, as there has never been a previously-agreed way of creating a jury-rigged solution
for rich messaging, as we never previously agreed a way of expressing alternate
```

2022-01-25 18:48 UTC, richvdh commented on proposals/1767-extensible-events.md
> +for rich messaging as we never previously agreed a way of expressing alternate
still too many "previously agreed". bah.

2022-01-25 20:45 UTC, uhoreg commented on proposals/1767-extensible-events.md
> +cannot be used to multiplex data into a single event. Relationships between events
I think that the word "event" in "... MUST refer to the same event ..." does not refer to a Matrix event, but rather some "thing", and perhaps it would be better to change that word to something else.  Some possible words are "item", "thing", "object", "data".

2022-01-25 20:53 UTC, turt2live commented on proposals/1767-extensible-events.md
> +cannot be used to multiplex data into a single event. Relationships between events
This is trying to say "these aren't mixins" in response to the original proposal - it definitely needs rewording having re-read it 😬 

tldr: adding `m.location` to the event content of `m.message` doesn't make it "text with location" as those are two logically different things - a new `m.text_with_location` event type (pending proper name) would be introduced instead.

2022-01-25 20:55 UTC, turt2live commented on proposals/1767-extensible-events.md
> +Because events are generally sent in the context of a room, all primary types introduced
yes.

2022-01-25 20:57 UTC, turt2live commented on proposals/1767-extensible-events.md
> +### Text messaging
This is part of the proposal content to actually make use of the structure outlined above. It felt a bit pointless to say "events are changing!!" without a demonstrated case for it (plus the administrative overhead of the MSC process if we were to break it out).

2022-01-25 20:57 UTC, turt2live commented on proposals/1767-extensible-events.md
> +        "m.text": "i am a *fish*", // doesn't have to be markdown, but useful as a "fallback" for HTML
`m.text` is just a shortcut for `"m.message": [{"mimetype": "text/plain", "body": "..."}]` in `content`

2022-01-25 20:58 UTC, turt2live commented on proposals/1767-extensible-events.md
> +    which might typically be just the ones listed below.
nothing I can really do about this - it's a GFM oddity.

2022-01-25 20:59 UTC, turt2live commented on proposals/1767-extensible-events.md
> +6. `m.location` (from [MSC3488](https://github.com/matrix-org/matrix-doc/pull/3488))
These are primary event types which will show up in `content`, yes.

2022-01-25 21:48 UTC, uhoreg reviewed
Some nitpicks and clarifications, but largely seems plausible

2022-01-25 21:48 UTC, uhoreg commented on proposals/1767-extensible-events.md
> +`m.text` and `m.html` are shortform types used to represent the most common scenarios. In cases
To be pedantic, I'm understanding the "shortform types" to be interpreted as:

- if both `m.text` and `m.html` are present, then treat it as if there was an `m.message` property with a `{"mimetype":"text/html", "body": ...}` and a `{"mimetype":"text/plain", "body": ...}` entry, in that order
- if only `m.html` is present, then treat it as if there was an `m.message` property with a `{"mimetype":"text/html","body":...}` entry
- if only `m.text` is present, then treat it as if there was an `m.message` property with a `{"mimetype":"text/html","body":...}` entry

the important part being the case where both of the shortforms are present, where we want the HTML version to be preferred over the text version.

2022-01-25 21:48 UTC, uhoreg commented on proposals/1767-extensible-events.md
> +```
Is the long-form version of this:

```json5
{
  "type": "m.emote",
  "content": {
    "m.emote": {
      "mimetype": "text/plain",
      "body": "is a fish"
    }
  }
}
```

(where the property in the `"content"` is `m.emote` instead of `m.message`) ?

2022-01-25 21:48 UTC, uhoreg commented on proposals/1767-extensible-events.md
> +        "m.emote": {}, // denotes that this should fall back to an emote, but worst case gets rendered as text
What if someone sends the event:

```json
{
  "type": "org.example.custom.event",
  "content": {
    "m.text": "is a fish",
    "m.emote": {},
    "m.notice": {}
  }
}
```

Should it get rendered as an emote or a notice?  Or is this a case of "if you send such a silly event, the client gets to do whatever it wants with your event".

I'm somewhat concerned that the fact that the shortforms are used for three different primary types introduces a bunch of complexity and makes it likely that a client will do something wrong.  My understanding of the rules is:
- if the primary type is `m.message` (and the event does not already have an `m.message` property), then treat `m.text`/`m.html` as a shortform for `m.message`
- if the primary type is `m.emote`/`m.notice` (and the event does not already have a property of the same name), then treat `m.text`/`m.html` as a shortform for `m.emote`/`m.notice`.
- if the primary type is something different, and
  - there is a non-empty `m.emote`/`m.notice`/`m.message`, then use that, and ignore any `m.text`/`m.html` shortforms.  (Not sure what to do if there is, say, all three.)
  - there is an empty `m.emote`/`m.notice`, then use `m.text`/`m.html`, if present, as shortform for that type
  - otherwise, use `m.text`/`m.html` as shortform for `m.message`

2022-01-25 21:48 UTC, uhoreg commented on proposals/1767-extensible-events.md
> +* Clients support the new primary event types, but continue to send `m.room.message` instead.
I think it would help to add a sub-bullet point here saying when sending the `msgtype` will be the event's primary type.  It is sort of discussed a bit later on, but I think it would help to have it more explicit at this location.

2022-01-25 22:19 UTC, turt2live commented on proposals/1767-extensible-events.md
> +preferred.
correct, yes.

2022-01-25 22:20 UTC, turt2live commented on proposals/1767-extensible-events.md
> +`m.text` and `m.html` are shortform types used to represent the most common scenarios. In cases
that's the theory, though in practice `m.html` on its own isn't all that helpful as the client would be depending on `m.text` - there's another thread out there which considers removing `m.html`, and I'm leaning towards doing that for simplicity reasons.

2022-01-25 22:21 UTC, turt2live commented on proposals/1767-extensible-events.md
> +```
negative, `m.message` in the `content` for the type.

2022-01-25 22:23 UTC, turt2live commented on proposals/1767-extensible-events.md
> +        "m.emote": {}, // denotes that this should fall back to an emote, but worst case gets rendered as text
it'd be client-defined behaviour. The rules early on say that with an unknown primary type a client should find the first representable event, which it can do in a number of ways.

Some clients might choose to grab the keys off the JSON and iterate through them until it's renderable (noting that objects in JSON are not stably ordered) while other clients might deliberately look for `m.emote` before `m.notice` and render as such.

2022-01-25 22:24 UTC, turt2live commented on proposals/1767-extensible-events.md
> +* Clients support the new primary event types, but continue to send `m.room.message` instead.
The msgtype and primary type are meant to be different things (`m.message` is the primary type for an `m.text` msgtype), but yes: clarification on the `msgtype` looks to be lacking.

2022-01-26 11:58 UTC, richvdh commented on proposals/1767-extensible-events.md
> +    which might typically be just the ones listed below.
doesn't an extra level of " " fix it?

2022-01-27 21:09 UTC, uhoreg commented on proposals/1767-extensible-events.md
> +
I think we have yet another (yay!) notifications issue here, in that AFAICT pings depend on matching text within the `body` field, which will be absent in a non-transitional extensible event.  So we'll need another MSC to fix notifications for this.

2022-01-27 21:12 UTC, turt2live commented on proposals/1767-extensible-events.md
> +
This is tracked as https://github.com/matrix-org/matrix-doc/issues/3555

2022-02-01 15:37 UTC, richvdh commented
removing this from "ready for FCP ticks" pending some clarifications.

2022-02-20 13:35 UTC, zecakeh commented on proposals/1767-extensible-events.md
> +`m.text` and `m.html` are shortform types used to represent the most common scenarios. In cases
Although it always appears in the examples, it is not mentioned that a plain text representation (`m.text` or `{"mimetype":"text/plain", "body": ...}`) is required when an `m.message` is expected. This diverges from the current spec where the `body` is required on the defined message types. It also means that a client might not be able to rely on the textual representation of a message, even if it is present.

Is this a conscious choice?

I tried to go over the previous comments and I couldn't find a reference to that so I'm sorry if this concern has already been answered.

2022-02-21 00:34 UTC, turt2live commented on proposals/1767-extensible-events.md
> +`m.text` and `m.html` are shortform types used to represent the most common scenarios. In cases
The intention is that `m.message` primary event types have at least a plain text representation of some kind, be it `m.text` or `m.message` in the body.

2022-02-21 08:35 UTC, zecakeh commented on proposals/1767-extensible-events.md
> +`m.text` and `m.html` are shortform types used to represent the most common scenarios. In cases
With the current phrasing what I understand is that *any* `m.message` is valid. So not necessarily `text/plain`.

2022-02-21 17:29 UTC, zecakeh commented on proposals/1767-extensible-events.md
> +to try and render unknown `msgtype`s.
Following this comment at https://github.com/ruma/ruma/issues/790#issuecomment-1046362311:

> fwiw, the intent of the transitional format is that you don't look at the msgtype but rather the other parts of the extensible event format to determine what kind of event it is. The msgtype is only used when the event does not have an extensible event representation (or when extensible events are not being considered).

Reading only the MSC, I actually understood the opposite. Another sentence explaining that would probably be welcome.

2022-02-27 18:14 UTC, zecakeh commented on proposals/1767-extensible-events.md
> +to try and render unknown `msgtype`s.
Another concern: if we are not supposed to look at the `msgtype` for events with fallback, how do we know whether the  message is an `m.message`, `m.notice` or `m.emote`?

Must we add an empty `m.notice` or `m.emote` to be consistent with `m.voice`?

2022-03-21 11:31 UTC, dkasak commented on proposals/1767-extensible-events.md
> +cannot be used to multiplex data into a single event. Relationships between events
I think just including what you last said would go a long way towards clarity. Something like inserting the following somewhere:

"That is, extensible events are not intended to represent mixins. For example, an event containing both a `m.location` and a `m.message` content does not represent a "text with location". Rather, it's a location with a text fallback for clients which don't understand locations."

There's already an example with an album of images so it might even make sense to make a list of several examples to build intuition.

Also, I think the point about relations which follows might be adding to the confusion since it is introduced a bit too abruptly. I suppose it's trying to say that, if you are actually trying to form a relationship between two events, you shouldn't attempt to use extensible events for this, but rather that you should send a separate event with a `m.relates_to`. But it's not terribly clear that this is indeed what is intended.

2022-03-21 11:54 UTC, dkasak commented on proposals/1767-extensible-events.md
> +cases where captions, thumbnails, etc need to be considered. This has further issues of
What role does this MSC play in captions, given that it's not meant to represent mixins?

2022-03-21 17:10 UTC, kegsay commented
This MSC doesn't seem to talk about sync filters at all. Sync filters are used by clients to filter out unrender-able events, which would be broken by this MSC due to the introduction of sub-types on `content`. Servers would realistically need to index (as in database index) all keys on `content` which isn't ideal due to the presence of keys which are not sub-types from legacy data models. This is particularly important for [Sliding Sync](https://github.com/matrix-org/matrix-spec-proposals/pull/3575) as clients will want to "Show previews of messages" in the room list but obviously only get events which they know how to render. I suggest the MSC at least calls this out and says "hey servers should probably index", and even better if we can have some way of officially namespacing sub-types e.g "all sub-types start with `_`" so we aren't indexing useless fields.

2022-03-21 17:12 UTC, turt2live commented
@kegsay I've deferred sync filters out to https://github.com/matrix-org/matrix-spec/issues/999 (likely a future MSC).

2022-03-30 02:00 UTC, alphapapa commented
Revisiting this after reading [Andy's blog post](https://www.artificialworlds.net/blog/2022/03/08/comparison-of-matrix-events-before-and-after-extensible-events/), I have some concerns again.

As a minor client developer, this feels discouraging.  Now, instead of writing code to parse messages in one structure, I have to parse messages in:

1.  The original specified structure.
2.  The new, extensible structure with multi-keyed maps in a list of maps.
3.  The new, extensible structure with single-keyed abbreviations in a map that is not in a list of maps.
4.  A potential mishmash of 3 different structure specifications shoved into a single event.

So instead of straightforward destructuring code, I have to write a long conditional trying four different ways.  And all of those will have to be kept around in perpetuity, or else someday, old events might just appear empty or, worse, cause bugs that might make my client non-functional.

As well, the wire format gets incredibly bloated.  Look at the last example given: the same message body written four different ways in a single event.  This doesn't only affect bandwidth and disk usage, but it also makes debugging harder, because it makes raw events much more difficult to visually parse.

Matrix is generally great, but stuff like this isn't.  Please rein this in before it goes into spec.  Simplify this down to the bare minimum.  You can always add another MSC later if absolutely necessary.

Matrix has so much potential, and is based upon a fundamental simplicity (lists and key-value maps), but I fear that the Matrix protocol is going to eventually become so bloated and confusing that developing clients (not to mention servers) is going to become impractical.  Interoperability between clients may suffer as well, and if that happens, it will destroy Matrix's reputation among users and probably its future.  It has plenty of competitors that will be glad to make their specs simpler and easier for developers.  If Matrix wants to be the next 30-year protocol (like HTTP, et al), it needs to keep simplicity as a paramount objective (i.e. think HTTP 1.x, not 2.x/3.x).

2022-03-30 03:13 UTC, turt2live commented on proposals/1767-extensible-events.md
> +# MSC1767: Extensible events in Matrix
@alphapapa says:

> Revisiting this after reading [Andy's blog post](https://www.artificialworlds.net/blog/2022/03/08/comparison-of-matrix-events-before-and-after-extensible-events/), I have some concerns again.
> 
> As a minor client developer, this feels discouraging.  Now, instead of writing code to parse messages in one structure, I have to parse messages in:
> 
> 1.  The original specified structure.
> 2.  The new, extensible structure with multi-keyed maps in a list of maps.
> 3.  The new, extensible structure with single-keyed abbreviations in a map that is not in a list of maps.
> 4.  A potential mishmash of 3 different structure specifications shoved into a single event.
> 
> So instead of straightforward destructuring code, I have to write a long conditional trying four different ways.  And all of those will have to be kept around in perpetuity, or else someday, old events might just appear empty or, worse, cause bugs that might make my client non-functional.
> 
> As well, the wire format gets incredibly bloated.  Look at the last example given: the same message body written four different ways in a single event.  This doesn't only affect bandwidth and disk usage, but it also makes debugging harder, because it makes raw events much more difficult to visually parse.
> 
> Matrix is generally great, but stuff like this isn't.  Please rein this in before it goes into spec.  Simplify this down to the bare minimum.  You can always add another MSC later if absolutely necessary.
> 
> Matrix has so much potential, and is based upon a fundamental simplicity (lists and key-value maps), but I fear that the Matrix protocol is going to eventually become so bloated and confusing that developing clients (not to mention servers) is going to become impractical.  Interoperability between clients may suffer as well, and if that happens, it will destroy Matrix's reputation among users and probably its future.  It has plenty of competitors that will be glad to make their specs simpler and easier for developers.  If Matrix wants to be the next 30-year protocol (like HTTP, et al), it needs to keep simplicity as a paramount objective (i.e. think HTTP 1.x, not 2.x/3.x).

2022-03-30 03:26 UTC, turt2live commented on proposals/1767-extensible-events.md
> +# MSC1767: Extensible events in Matrix
For clarity: You don't need to support this parsing structure. For clients wishing to try and render *unknown event types* though, this is how they'd do it. For example, when a new feature is being developed and gracefully falls back to text: clients which support extensible events can render it as text until they gain knowledge on the primary event type.

As an example, your client can destructure `m.message` events by reaching into the `content` and picking out the fields it needs, much like today's `m.room.message` handling. This doesn't require interpreting the extensible events schema, by design.

We are also deliberately prioritizing rendering capabilities over readability/bloat of the event here. We want to support many of the features already described by the MSC and have narrowed it down to this as the smallest possible structure to represent the information required. While bandwidth can be argued as a concern, we envision a future MSC will address the transport issues rather than trying to solve it at the event level. 

Generally speaking though, this is already at a bare minimum for acceptance. We moved all the non-text bits out to their own MSCs and have spent a couple years working out how exactly to represent the structure in the simplest and most understandable form, landing on this. We're not saying it's perfect, but it's certainly better than the early approaches - we plan to supplement gaps with blog posts similar to Andy's as we continue to push this out.

The complexity of writing implementations of Matrix is a very well-known problem, and one that we already feel today. It's off topic here, but the plan is to split the spec into logical parts (exact breakdown to be determined - currently looking like events, voip, encryption, etc) so clients and servers can more clearly see what they actually *need* to implement to fulfill a given usecase. A server targeting text-only clients will require encryption but not voip, as an example. We believe that extensible events is net-positive, all things considered.

2022-03-30 07:05 UTC, alphapapa commented on proposals/1767-extensible-events.md
> +# MSC1767: Extensible events in Matrix
@turt2live I appreciate your thoughtful response.  I do hope this proposal works out well and that Matrix succeeds in the long-term.

2022-03-30 10:21 UTC, dkasak commented on proposals/1767-extensible-events.md
> +# MSC1767: Extensible events in Matrix
FWIW, I think the above may be overcomplicating it a bit and there is a simpler way of stating this.

To support the parsing side of this MSC, do this:

- If you see a `m.message` event, just parse the new format. Don't support the old format at all.
- If you see a `m.room.message` event, first try parsing the new format. If that fails, parse the old format.

To support the sending side of this MSC, do this:

- Continue sending `m.room.message` events as normal, but also add in the keys of the new format.
- At some agreed upon point in the future (pending a new MSC), change the type to `m.message` and stop sending keys from the old format.

This doesn't seem so bad to me. If I'm interpreting the MSC correctly, perhaps something like this could be added to a "What you need to do as a client author" section? The MSC talks quite exhaustively about the rationale behind the design and the transition process, but perhaps clear instructions to client authors were a bit lost in the noise.

2022-03-30 14:25 UTC, deepbluev7 commented on proposals/1767-extensible-events.md
> +# MSC1767: Extensible events in Matrix
While the actual thread for this is here: https://github.com/matrix-org/matrix-spec-proposals/pull/1767#discussion_r783533194 , there is actually some more complication specifically for text message events, so a client needs to parse these in approximately this order to ge the text content of an event:

- search for mimetype "text/html" in "m.message"
- look at "m.html"
- look at "format" and "formatted_body"
- search for mimetype "text/plain" in "m.message"
- look at "m.text"
- look at "body"

I disagree that this is the simplest way this proposal can be represented, 4 steps should be enough, 6 is too much. But yeah, that's https://github.com/matrix-org/matrix-spec-proposals/pull/1767#discussion_r783533194 .

2022-03-30 14:47 UTC, dkasak commented on proposals/1767-extensible-events.md
> +# MSC1767: Extensible events in Matrix
(I took that thread as being more about whether shorthand keys are warranted or not, and that's why I didn't comment there. I don't really have a strong opinion on that topic and I can see benefits to either approach.)

However, I'd argue that's not the correct list of steps due intermixing of individual parsing steps from the new format and the old format. I think this is a distinctly bad idea.

I think the correct way of parsing should always be

1. Parse the new format.
2. If failing 1, parse the old format.

Which when expanded leads to

1. a. Search for mimetype `text/html` in `m.message`.
   b. Look at `m.html`.
   c. Search for mimetype `text/plain` in `m.message`.
   d. Look at `m.text`
2. a. Look at `format` and `formatted_body`.
   b. Look at `body`.

That is, only when we have exhausted all of the new format parsing steps should we even attempt to look at old-style fields. Clients should never send events without `text/html`/`m.html` but *with* `formatted_body`. Parsing it this way ensures that such events will be considered invalid.

2022-03-31 13:43 UTC, uhoreg commented on proposals/1767-extensible-events.md
> +`m.text` and `m.html` are shortform types used to represent the most common scenarios. In cases
> @uhoreg, presumably your last bullet point has a typo and it's meant to say `"mimetype":"text/plain"` instead?

Yes.  Fixed

2022-03-31 15:25 UTC, alphapapa commented on proposals/1767-extensible-events.md
> +# MSC1767: Extensible events in Matrix
I don't love everything about Python, but I think the Zen of Python is applicable here: there should be one, obvious way to construct and to parse messages--and preferably only one correct way.  

IMHO, these shorthands don't actually make it easier--they make it harder, because they are additional cases that must be programmed for.  It's much easier to write a program to do one specific thing than to write one to do A, but maybe B, or maybe some of A and some of B, and eventually falling back to C if nothing else works.

So I would suggest picking either the shorthands or the full MIME-types and sticking with it.

2022-04-02 23:48 UTC, deepbluev7 commented on proposals/1767-extensible-events.md
> +        "m.emote": {}, // denotes that this should fall back to an emote, but worst case gets rendered as text
Isn't the json always alphabetically ordered, because it needs to be canonically encoded over federation?

2022-04-03 03:47 UTC, turt2live commented on proposals/1767-extensible-events.md
> +        "m.emote": {}, // denotes that this should fall back to an emote, but worst case gets rendered as text
The order of keys in JSON have no ordering, so the client is expected to maintain a list of event types it prefers to fall back to.

2022-04-08 21:47 UTC, turt2live commented
The SCT can't make meaningful progress on this at the moment, and the MSC itself requires quite a bit of refactoring. For the time being, let's remove it from the urgent pile:

@mscbot fcp cancel

2022-07-02 01:07 UTC, turt2live commented on proposals/1767-extensible-events.md
> +cannot be used to multiplex data into a single event. Relationships between events
I think I will have clarified this with an inbound rewrite. If not, please definitely open a new thread.

2022-07-02 01:09 UTC, turt2live commented on proposals/1767-extensible-events.md
> +preferred.
Out of band discussion revealed that `m.html` is a hard blocker for this MSC going forward, but other shortcuts don't really make sense. This will be clarified in an inbound rewrite.

2022-07-02 01:30 UTC, turt2live commented on proposals/1767-extensible-events.md
> +cases where captions, thumbnails, etc need to be considered. This has further issues of
this MSC? Nothing! :D

https://github.com/matrix-org/matrix-doc/pull/3552 makes a (questionable) argument for captions.

2022-07-02 01:32 UTC, turt2live commented
to the subscribers: this has gone through another round of rewriting to hopefully be understandable. I believe all outstanding threads have been addressed, but if not then please open **new** threads for consideration.

I plan to put this forward for FCP in the next couple weeks barring major concerns.

2022-07-04 08:37 UTC, andybalaam approved these changes

2022-07-04 17:20 UTC, turt2live commented on proposals/1767-extensible-events.md
> +**Note**: We specifically support these shortcuts to ensure that funding for Matrix is not
it's not really the learning experience we're concerned with in this paragraph, though is another point we'd raise.

2022-08-01 14:38 UTC, networkException reviewed
Just a typo

2022-08-01 14:38 UTC, networkException commented on proposals/1767-extensible-events.md
> +invididuals in understanding what a message event is, two shortcuts are defined: `m.text` and
```suggestion
individuals in understanding what a message event is, two shortcuts are defined: `m.text` and
```

2022-08-02 20:07 UTC, deepbluev7 commented on proposals/1767-extensible-events.md
> +complicated event types (such as polls or RTF events).
This adds a lot of complexity for full clients. I don't agree that putting the burden of demo features in clients is reasonable. You are adding quite a bit of complexity with extensible already, why is this the make or break?

I have seen clients too often depend on events specifically sent by Element, so having one client sending `m.html` and one client `{ "mimetype": "text/html", "body": "i am a <strong>fish</strong>" }` will mean that the message won't render in some clients at some points. This is a significant burden on clients that are smaller than Element, since they need to "implement what Element does" instead of following the specification.

There should be one canonical way to send an event and making the experience worse on Matrix so that it is easier to secure funding is terrible. Especially since it just makes sending messages easier, but receiving them significantly harder.

2022-08-02 20:11 UTC, turt2live commented on proposals/1767-extensible-events.md
> +complicated event types (such as polls or RTF events).
this has been discussed at length already, and the points are covered in the MSC or by other threads here.

2022-11-10 14:40 UTC, turt2live commented
For the github subscribers, this MSC has been rewritten, again. With this rewrite there's a lot of changes but the underlying functionality is largely the same.

Critically:
* Subtypes are now called "content blocks", and are now a first-class citizen
* A room version is required for this change to go through
* The shortcut types have been removed
* Ordering limitations on the `m.markup` (btw, it's markup now) array are removed
* Content blocks can be nested (see `m.notice`)
* The other base type MSCs are pending similar rewrites to match this system (images, files, etc).

If you have comments, please put them on threads in the diff. I've resolved all outstanding threads, and please avoid the use of the thread-less comment box as it makes it difficult to follow along.

2022-11-10 15:08 UTC, benkuly commented on proposals/1767-extensible-events.md
> +To support event types which may need an emote or notice fallback, `m.emote` and `m.notice`
Can you explain, why this is needed? Is there an actual use case?

In my opinion we should should distinguish between event type (e.g. `m.message` or `m.emote`) and content schemas (e.g. `m.markup` or `org.exmaple.probe_value`) to avoid confusion. This paragraph does mix them up. I also think, that it overcomplicates de-/serializersation

2022-11-10 15:31 UTC, turt2live commented on proposals/1767-extensible-events.md
> +To support event types which may need an emote or notice fallback, `m.emote` and `m.notice`
`m.notice` is more useful of the two, as (hopefully) demonstrated by the later example. `m.emote` also gets a content block definition because, well, we're here and it's easy to do so, and costs us nothing. Theoretically, one could use `m.emote` as a fallback for `m.sticker` or similar, to communicate rich-enough integration.

As for how it affects (de)serialization, there shouldn't be much of an impact: content blocks are specifically called out in the MSC as *not* being event types, though they can have the same name. Some effort was made to avoid `m.message` and `m.message` naming (instead using `m.markup` for the content block), however for notices and emotes it's hard to avoid the terminology overlap. A parser/serializer would treat them as completely different things, even if named the same.

2022-11-10 15:51 UTC, ShadowJonathan commented on proposals/1767-extensible-events.md
> +  therefore it is the client's responsibility to validate/sanitize the content further.
This feels untrue, as there is a [section in the spec](https://spec.matrix.org/v1.4/client-server-api/#mroommessage-msgtypes) that details which html tags and attributes are allowed and which aren't. Do those get grandfathered into here, or does this effectively release those restrictions?

Personally, I would advice against releasing the restrictions, as that will introduce vagueness and uncertainty around how html will be rendered on different clients. The existing set of HTML tags and attributes help sanitise and "bound" what to expect from the html over the wire.

2022-11-10 15:51 UTC, ShadowJonathan commented on proposals/1767-extensible-events.md
> +  the preferred representations should appear first in the array.
This does not feel "unordered", it feels there are counteractive signals here;
- "this is an unordered array"
- "the preferred representation *could* be ordered first"

----

For example, if (like the above example) a text/plain markup is ordered before text/html, which one would be "preferred"? Does that mean that the client should prefer the text/plain repr over the text/html one?

----

It also seems that [this section](https://github.com/matrix-org/matrix-spec-proposals/pull/1767/files#diff-242c41793e638a8acaf2b7ea5870ca0249de76f00b36e8fb2c2e5ed4e106872aR125-R129) implies the reinforce the first note, while disregarding the second one.

----

I believe this section could be worded better in terms of fallback, or not present at all.

2022-11-10 15:51 UTC, ShadowJonathan commented on proposals/1767-extensible-events.md
> +  however are equally permitted to send an HTML representation instead.
```suggestion
  however are equally permitted to only send an HTML representation instead.
```
?

2022-11-10 15:51 UTC, ShadowJonathan commented on proposals/1767-extensible-events.md
> +  array, followed by more common HTML and text formats.
I'd like to make a note here (not a review comment) about that this would allow the likes of [`text/x-gfm`](https://www.digipres.org/formats/mime-types/#text/x-gfm) to be a proper mimetype to target, for markdown-compatibility-related purposes.

If possible, it might be interesting to include this as a sub-item, to evoke the imagination or have readers have an "ah" moment about this, as I know markdown compatibility has been somewhat of a sore point, and so this could be used to "lump" the raw markdown into the message, while keeping compatible rich representation in the markdown.

2022-11-10 15:51 UTC, ShadowJonathan commented on proposals/1767-extensible-events.md
> +To support event types which may need an emote or notice fallback, `m.emote` and `m.notice`
I believe embedded `m.notice` has a solid use-case here, but `m.emote` seems questionable as a candidate for being embeddable.

2022-11-10 15:51 UTC, ShadowJonathan commented on proposals/1767-extensible-events.md
> +an `m.room.encrypted` event:
Reusing a name for a content block and a type seems to become confusing to some, I could recommend using `m.ciphertext` as a name for the content block, but I see that `ciphertext` is also used as a field under that content block, so I'd only strongly want to note the possibility of confusion between the two places where `m.encrypted` could be used.

2022-11-10 15:51 UTC, ShadowJonathan commented on proposals/1767-extensible-events.md
> +        "org.matrix.msc1767.html": "<b>Hello</b> World"
```suggestion
        "org.matrix.msc1767.markup": [
            {"body": "Hello World"}, 
            {"body": "<b>Hello</b> World", "mimetype": "text/html"}
        ]
```

2022-11-10 15:51 UTC, ShadowJonathan commented on proposals/1767-extensible-events.md
> +use the unstable prefix mentioned above. A fallen back `m.room.message` example event becomes:
(Forgotten during the rewrite?)

2022-11-10 15:51 UTC, ShadowJonathan commented on proposals/1767-extensible-events.md
> +## Historical changes
Ditto, feels like https://github.com/matrix-org/matrix-spec-proposals/pull/1767#issuecomment-1310393397 should be included here.

2022-11-10 15:52 UTC, dkasak commented on proposals/1767-extensible-events.md
> +This allows the `m.encrypted` content block to be reused by other event types, if required.
Why would this be required? Are we already suspecting it or is this just an off-handed remark?

2022-11-10 16:28 UTC, turt2live commented on proposals/1767-extensible-events.md
> +To support event types which may need an emote or notice fallback, `m.emote` and `m.notice`
> So there is a distinction between event type and content blocks?

Yes, explicitly (see early paragraphs in the proposal).

> > m.emote and m.notice are defined as content blocks with an object containing the content of a normal m.emote or m.notice event.
> 
> Still, this sounds to me like content block types can be nested, which has a compexity impact on de-/serialization and is really confusing. I want to understand why this decision was made.
> 
> As an alternative there could be an `m.emote` and `m.notice` content block boolean without nesting the `m.markup`. Thereby a client must not support `m.emote` and `m.notice` to render a content, because `m.markup` would stay on top level.

They can be nested, but they would be nested with explicit schema (so should be possible to parse still).

2022-11-10 17:04 UTC, bleonard252 commented on proposals/1767-extensible-events.md
> +This allows the `m.encrypted` content block to be reused by other event types, if required.
This seems like it would be intended to allow or encourage non-encrypted data to be sent along with encrypted data. As far as progress on encryption goes, this seems unhelpful at best.

2022-11-10 17:29 UTC, turt2live commented on proposals/1767-extensible-events.md
> +  therefore it is the client's responsibility to validate/sanitize the content further.
Those restrictions are already a suggestion - this MSC doesn't neccessarily remove that section of the spec, but it also doesn't really feel constrained by it. Clients can (and should) still sanitize as needed, including following recommendations in the spec about how HTML can work.

For the features of our HTML that aren't allowed/expected in "normal" HTML, we should open an MSC for a MatrixHTML specification.

2022-11-10 17:30 UTC, turt2live commented on proposals/1767-extensible-events.md
> +  the preferred representations should appear first in the array.
Originally this field was ordered, but that caused problems because people naturally put stuff like plain text first, then HTML, then a lot of the more optional formats, leading to a problem where the second array element is actually "first prepared", then the first element, then the remainder. Instead, we are trying to tell clients to pick the one they want to use (which they should be able to do safely anyways), but as a *suggestion*, pick the first one if you don't have a good option.

2022-11-10 17:31 UTC, turt2live commented on proposals/1767-extensible-events.md
> +  however are equally permitted to send an HTML representation instead.
The lack of "only" is intentional: senders are asked to send plain text with their Markdown, but they can also send HTML+Markdown instead.

2022-11-10 17:32 UTC, ShadowJonathan commented on proposals/1767-extensible-events.md
> +  the preferred representations should appear first in the array.
That sounds reasonable, though I just think it's not communicated clearly in the proposal here.

2022-11-10 17:33 UTC, turt2live commented on proposals/1767-extensible-events.md
> +  array, followed by more common HTML and text formats.
I personally feel the MSC is already too long and markdown examples don't add to the vision the MSC is trying to portray - instead, it's mentioned as a "oh look, markdown too" to remind readers there are more mimetypes than text and HTML. Specifically, this is actually targeting Slack, Wire (to a degree), and other messengers which use highly custom formats.

2022-11-10 17:35 UTC, turt2live commented on proposals/1767-extensible-events.md
> +        "org.matrix.msc1767.html": "<b>Hello</b> World"
will apply manually - there's some concerns with this layout.

2022-11-10 17:36 UTC, turt2live commented on proposals/1767-extensible-events.md
> +## Historical changes
It is? The parts highlighted for advertising on github/the spec room are intentionally different than the ones recorded in the MSC's own changelog. The MSC's changelog is meant to cover drastic changes whereas the "please take another look" comment highlights the subtlties to encourage readers with opinions to re-read it.

2022-11-10 18:53 UTC, cvwright commented on proposals/1767-extensible-events.md
> +* `mimetype` is optional in a representation, and defaults to `text/plain`.
Is the intention to allow multiple bodies with the same mimetype?

If so, how should a client choose which one to display?  This smells like a vulnerability where a maliciously-crafted message could be made to display differently to different clients, e.g. Element shows "Alice is a wonderful person" while FluffyChat shows "Alice is a terrible person".

If the intent is not to allow multiple bodies with the same mimetype, then you could remove the possibility for confusion by making `content` a dictionary, with the mimetype as the key.

2022-11-10 19:01 UTC, ShadowJonathan commented on proposals/1767-extensible-events.md
> +* `mimetype` is optional in a representation, and defaults to `text/plain`.
+1 for making `m.markup` a dictionary of mimetype -> body, should make things a lot clearer and implicit, unless the intention was to expand the body-mimetype object with other fields in the future.

2022-11-10 19:15 UTC, cvwright commented on proposals/1767-extensible-events.md
> +to render a bridge state change with `m.markup` to clearly indicate a bridge was added/edited.
If you allow state events to include `m.markup`, how does a client validate that the textual description is accurate and not misleading?

For example, "Alice made Bob a moderator" vs "Alice muted Bob", or "Alice invited Bob" vs "Alice banned Bob"?

2022-11-10 19:31 UTC, cvwright commented on proposals/1767-extensible-events.md
> +To support event types which may need an emote or notice fallback, `m.emote` and `m.notice`
It is weird that `m.markup` is initially presented as the place to look for a fallback.  And now we have `m.notice` and `m.emote` also available as different fallback options.  But then they're just containers for the same structure that we had before.

I guess what I'm asking is: What is the reason for having the extra layer of `m.notice` here?  Why not just use the `m.markup` directly under `content` like you described above?

Would some event type want to have both an `m.markup` and an `m.notice`, and have them say different things?

2022-11-10 19:36 UTC, cvwright commented on proposals/1767-extensible-events.md
> +It's a bit ugly to not know whether a given key in `content` will take a string, object or array.
I can't speak for the other languages with real type systems, but all of this looks very doable in Swift using Apple's `Decodable` protocol.  Much nicer than, say, the params for `m.login.terms`.  :-)

That is, as long as there's an unambiguous spec for each message type.

2022-11-10 19:43 UTC, cvwright commented on proposals/1767-extensible-events.md
> +This allows the `m.encrypted` content block to be reused by other event types, if required.
Could this be used as an alternative to #3911 for linking media to encrypted events?

That is, the encrypted content stays the same as before, and you could add a list of MXC media URL's elsewhere under the `content`.

2022-11-10 19:49 UTC, MTRNord commented on proposals/1767-extensible-events.md
> +to render a bridge state change with `m.markup` to clearly indicate a bridge was added/edited.
Also, how would a client here deal with translation for this? And/Or when a client uses a different scheme for their context messages? (We already have clients using different product names for features.)

2022-11-10 19:59 UTC, dkasak commented on proposals/1767-extensible-events.md
> +        "org.exmaple.probe_value": {
```suggestion
        "org.example.probe_value": {
```

2022-11-10 20:36 UTC, bleonard252 commented on proposals/1767-extensible-events.md
> +* `mimetype` is optional in a representation, and defaults to `text/plain`.
Translation comes to mind. In theory this could still be handled with a subkey.

2022-11-11 08:22 UTC, benkuly commented on proposals/1767-extensible-events.md
> +To support event types which may need an emote or notice fallback, `m.emote` and `m.notice`
I want to point out my alternative again:

> As an alternative there could be an m.emote and m.notice content block boolean without nesting the m.markup. Thereby a client must not support m.emote and m.notice to render a content, because m.markup would stay on top level.

2022-11-11 08:33 UTC, dkasak commented on proposals/1767-extensible-events.md
> +To support event types which may need an emote or notice fallback, `m.emote` and `m.notice`
I think the underlying trouble is that the MSC *is* mixing up event types and content blocks semantically, to a degree. What is a `m.notice` content block even supposed to mean? I suppose it wants to say "my inner contents represent a notice, rather than some markup which *isn't* a notice".

But that sounds squarely what the purpose of the `m.notice` *event type* is supposed to be. So why are we trying to nest it as a content block inside some other type?

2022-11-11 09:36 UTC, turt2live commented on proposals/1767-extensible-events.md
> +* `mimetype` is optional in a representation, and defaults to `text/plain`.
Translations, other markup details, extensions, etc - a dictionary is not fit for purpose here, sorry. Seeing two different messages is already an issue, and this MSC doesn't make it better or worse.

2022-11-11 09:38 UTC, turt2live commented on proposals/1767-extensible-events.md
> +This allows the `m.encrypted` content block to be reused by other event types, if required.
> > For the extensible events world though, this is to make "encryption" be a single content block instead of 3, as all event types get redefined over time.
> 
> Hmm, can you expand a bit? Which (hypothetical) 3 are you referring to?

They aren't hypothetical 😇 Any top-level key in `content` is a content block, so the three fields currently required to send an encrypted message each become a content block.


> Could this be used as an alternative to #3911 for linking media to encrypted events?
> 
> That is, the encrypted content stays the same as before, and you could add a list of MXC media URL's elsewhere under the `content`.

Unlikely - that would make things more complicated.

2022-11-11 09:46 UTC, turt2live commented on proposals/1767-extensible-events.md
> +to render a bridge state change with `m.markup` to clearly indicate a bridge was added/edited.
There's several things here:

1. Clients are not required to render extensible events on state events.
2. Room admins/moderators that do this (because you need permission to send a state event) are unlikely to be well-received by the room's community.
3. The fallback is only used when the client doesn't know how to deal with a given state event, which means normal users (who can send membership events) can't actually do any damage: their membership event would be rendered as a membership event without any fallback. The same applies for the power levels event.
4. Even if the client *does* decide to render extensible events on state events, falling back to `m.markup` means it'll get rendered as a text message, not as a state event. Thus it'll be no different than literally saying "Alice made Bob a moderator" in chat.
5. On translations, please refer to the other MSC and point 4 above.

2022-11-11 09:47 UTC, turt2live commented on proposals/1767-extensible-events.md
> +        "org.exmaple.probe_value": {
will apply manually

2022-11-11 09:53 UTC, turt2live commented on proposals/1767-extensible-events.md
> +To support event types which may need an emote or notice fallback, `m.emote` and `m.notice`
@cvwright You can put `m.markup` one layer up, but then it gets rendered as a text message rather than as a notice. This is why it's nested.

@benkuly while I appreciate the suggestion, it's been dismissed before because a boolean is not extensible enough for future consideration, unfortunately. 

@dkasak The semantics are indeed being combined, deliberately. It's to say that the event gets rendered like a notice *if the client doesn't believe there's a more suitable content block*, which then means it also uses the text. This does not mean that the client renders it as a probe value (for example) that is faded because it's a notice - it would either render as a probe value or as a notice, not both.

2022-11-11 09:55 UTC, turt2live commented on proposals/1767-extensible-events.md
> +  the preferred representations should appear first in the array.
> That sounds reasonable, though I just think it's not communicated clearly in the proposal here.

will attempt to clarify - it was a last minute change (per commits).



> On that note: should events building upon ext ev suggest an order? As in: "its fine to use whatever but for best compatibility clients should prefer this order if they support it."
> 
> Meaning that if a client supports variant a and b and the event sends a b and c as possible representations _should_ the client prefer a over b or b over a for an event to make sure that clients are consistent across the ecosystem if the client supports both?
> 
> While for HTML vs unformmated messages is very clear what the best way of order is when a client supports both it may not be as clear with let's say for example having an imaginary ext ev where you have 2 image formats to choose from. (this is just an example to display the issue). As in for ext evs where there are representations that can have equal weight.

The client would know better than the sender for what representations are best for it to render, especially when considering extensions to the markup system (translations, etc). Leaving it as a deliberate implementation detail seems wise, imo.

2022-11-11 09:58 UTC, turt2live commented on proposals/1767-extensible-events.md
> +It's a bit ugly to not know whether a given key in `content` will take a string, object or array.
Good to hear! I'm going to resolve this thread though so I don't think there's something to action ;)

2022-11-11 10:01 UTC, dkasak commented on proposals/1767-extensible-events.md
> +This allows the `m.encrypted` content block to be reused by other event types, if required.
Ah, okay. To spell it out for others, I suppose you meant `algorithm`, `session_id` and `ciphertext`, and excluding `sender_key` and `session_id` because they are deprecated.

2022-11-11 10:06 UTC, dkasak commented on proposals/1767-extensible-events.md
> +To support event types which may need an emote or notice fallback, `m.emote` and `m.notice`
Then the problem is that the `m.notice` event type has unclear semantics. What does the `m.notice` type mean, other than its faded rendering? Does it mean anything at all or is it just a styling thing?

2022-11-11 10:14 UTC, turt2live commented on proposals/1767-extensible-events.md
> +This allows the `m.encrypted` content block to be reused by other event types, if required.
Special cases are really not ideal, as it causes so many more problems. I'd sooner specify that the `m.encrypted` content block should not be used to have encrypted/unencrypted fallbacks.

Note that it's already possible to send unencrypted content in an encrypted event - this MSC isn't really changing anything, but rather formally making encryption a thing you can represent more easily under this system.

2022-11-11 10:18 UTC, dkasak commented on proposals/1767-extensible-events.md
> +To support event types which may need an emote or notice fallback, `m.emote` and `m.notice`
To attempt to pinpoint what I think is wrong about this: It makes the answer to the question of "Is an event a notice?" hard and unobvious. Previously, you'd just check the event type and, if it's `m.notice`, it's a notice, and otherwise it's not a notice.

But with an `m.notice` content block, it *may* be a notice to some clients, but only if they don't know how to render the other content blocks? Or, alternatively, it's *not* a notice for anyone, it just renders like one on some clients.

This is the result of mixing semantics and presentation and not clearly delineating between them.

2022-11-11 10:22 UTC, dkasak commented on proposals/1767-extensible-events.md
> +to render a bridge state change with `m.markup` to clearly indicate a bridge was added/edited.
> Even if the client does decide to render extensible events on state events, falling back to m.markup means it'll get rendered as a text message, not as a state event. Thus it'll be no different than literally saying "Alice made Bob a moderator" in chat.

It would be *rendered* as a text message, but would it still have the *meaning* of a state event?

2022-11-11 10:38 UTC, benkuly commented on proposals/1767-extensible-events.md
> +To support event types which may need an emote or notice fallback, `m.emote` and `m.notice`
> @benkuly while I appreciate the suggestion, it's been dismissed before because a boolean is not extensible enough for future consideration, unfortunately.

Okay, then make it an object:

```json5
{
    // irrelevant fields not shown
    "type": "org.example.temperature",
    "content": {
        "m.markup": [{"body": "It is 22 degrees at Home"}],
        "m.notice": {
            "enabled": true
        },
        "m.emote": {
            "enabled": true
        },
        "org.exmaple.probe_value": {
            "label": "Home",
            "units": "org.exmaple.celsius",
            "value": 22
        }
    }
}
```

or include it in `m.markup`:

```json5
{
    // irrelevant fields not shown
    "type": "org.example.temperature",
    "content": {
        "m.markup": {
            "body": [{"body": "It is 22 degrees at Home"}],
            "m.notice": true,
            "m.emote": true
        }
        "org.exmaple.probe_value": {
            "label": "Home",
            "units": "org.exmaple.celsius",
            "value": 22
        }
    }
}
```

2022-11-11 10:42 UTC, richvdh commented on proposals/1767-extensible-events.md
> +For simplicity, the `content.body` condition now looks for an `m.markup` block's `text/plain`
> the `content.body` condition

It's unclear to me what exactly this refers to. Note that there is no `content.body` condition defined at https://spec.matrix.org/v1.4/client-server-api/#conditions-1.

Perhaps you mean  `event_match` conditions with a key of `content.body`? It feels odd to me that we would special-case some keys to give them special behaviour, and really we should define a whole new condition type here. On the other hand, `content.body` already has some special-casing for historical reasons, so I suppose adding more special cases isn't the end of the world.

Either way, clarification needed here please.

2022-11-11 10:42 UTC, turt2live commented on proposals/1767-extensible-events.md
> +  the preferred representations should appear first in the array.
actually, given all the other comments, I think we should just go back to making this ordered. This would also apply to notifications stability and such, which feels important.

2022-11-11 10:43 UTC, richvdh commented on proposals/1767-extensible-events.md
> +For simplicity, the `content.body` condition now looks for an `m.markup` block's `text/plain`
Also: does this change to the behaviour apply for all room versions, or just ones that support extensible events?

2022-11-11 10:44 UTC, turt2live commented on proposals/1767-extensible-events.md
> +To support event types which may need an emote or notice fallback, `m.emote` and `m.notice`
It has no semantic difference to `m.room.message` with `msgtype` of `m.notice` - we just aren't letting events subtype themselves with things like `msgtype` anymore.

2022-11-11 10:49 UTC, dkasak commented on proposals/1767-extensible-events.md
> +To support event types which may need an emote or notice fallback, `m.emote` and `m.notice`
But I think the problem is exactly that the event type *should* carry semantics. If as you say `m.notice` does *not* have different semantics than `m.message`, just different styling, then we should be sending notices as `m.message` and styling them differently by using an appropriate content block, such as the one suggested above:

```json
"m.markup": {
    "body": [{"body": "It is 22 degrees at Home"}],
    "m.notice": true
}
```

2022-11-11 10:50 UTC, turt2live commented on proposals/1767-extensible-events.md
> +To support event types which may need an emote or notice fallback, `m.emote` and `m.notice`
> To attempt to pinpoint what I think is wrong about this: It makes the answer to the question of "Is an event a notice?" hard and unobvious. Previously, you'd just check the event type and, if it's `m.notice`, it's a notice, and otherwise it's not a notice.
> 
> But with an `m.notice` content block, it _may_ be a notice to some clients, but only if they don't know how to render the other content blocks? Or, alternatively, it's _not_ a notice for anyone, it just renders like one on some clients.
> 
> This is the result of mixing semantics and presentation and not clearly delineating between them.

@dkasak If a client knows how to render the event type then the client renders it as such. If it *doesn't* know how to render that event type, then it starts looking at content blocks. The client picks which content blocks are looked at first, deliberately, and might in fact choose a different one from another client. The notice is effectively a text fallback if nothing else seems relevant to that client.

---

@benkuly That is closer to mixins, not independent rendering, which is what we're avoiding at the moment. Display hints and similar are explicitly out of scope.

2022-11-11 10:55 UTC, turt2live commented on proposals/1767-extensible-events.md
> +For simplicity, the `content.body` condition now looks for an `m.markup` block's `text/plain`
This feels a bit like over-specification in an already very long MSC, imo. It feels clear enough to me that this is targeting `event_match` with `content.body`, and that all other improvements (because there are obviously some) are deferred. Other MSCs are already mentioned as being needed to handle the `m.room.message` -> `m.message` event type transition anyways - I'd rather move this discussion to said future MSC.

2022-11-11 11:00 UTC, dkasak commented on proposals/1767-extensible-events.md
> +To support event types which may need an emote or notice fallback, `m.emote` and `m.notice`
@turt2live I understand the presentation side of this and how the rendering rules work. I'm rather concerned we're eroding event *meaning* (semantics) here, by mixing semantic concerns with presentational concerns. Each event type should have a clearly defined meaning without reference to the way it will be presented by clients.

2022-11-11 11:05 UTC, dkasak commented on proposals/1767-extensible-events.md
> +to render a bridge state change with `m.markup` to clearly indicate a bridge was added/edited.
> > It would be rendered as a text message, but would it still have the meaning of a state event?
>
> Yes.

Well isn't this exactly the problem pointed out above? Because state events usually have effects, and so their presentation should reflect this effect, but if they get rendered as a text message, the message can say anything at all, even wording contrary to the effect?

2022-11-11 11:15 UTC, turt2live commented on proposals/1767-extensible-events.md
> +For simplicity, the `content.body` condition now looks for an `m.markup` block's `text/plain`
have clarified anyways, I think.

2022-11-11 11:18 UTC, richvdh commented on proposals/1767-extensible-events.md
> +For simplicity, the `content.body` condition now looks for an `m.markup` block's `text/plain`
yeah that's clearer, thanks

2022-11-11 11:18 UTC, turt2live commented on proposals/1767-extensible-events.md
> +to render a bridge state change with `m.markup` to clearly indicate a bridge was added/edited.
it'd be no different than blatantly lying in a text message though? I'm not sure technology can solve this problem space, or if it should.

2022-11-11 11:48 UTC, dkasak commented on proposals/1767-extensible-events.md
> +to render a bridge state change with `m.markup` to clearly indicate a bridge was added/edited.
Surely it is different, because ordinary text messages don't make the client perform side-effects. The concern is that someone would be able to use this to perform a side-effect but then mask the fact of that happening through this mechanism.

2022-11-11 12:51 UTC, turt2live commented on proposals/1767-extensible-events.md
> +To support event types which may need an emote or notice fallback, `m.emote` and `m.notice`
From out of band, it sounds like we need to declare that mixins are specifically allowed, and likely push emotes and notices out to their own MSCs for further discussion. Specifically, around notices, it feels more desirable to have a mixin to say "this event is automated - do not reply" rather than an event type to do that.

2022-11-11 13:07 UTC, dkasak commented on proposals/1767-extensible-events.md
> +to render a bridge state change with `m.markup` to clearly indicate a bridge was added/edited.
From out of band, the case I'm most worried about is something like a client implementing a state event but continuing to let "fallback" content blocks to inform and override its rendering. For a concrete example, a client implements `org.example.door_lock`, but instead of only relying on the `door_state` content block (specified in its event schema) to inform the rendering, it allows itself to be overridden by a 1px `m.image` content block, rendering the state event invisible.

The solution is to add some wording to say that clients should not do this and to warn implementors of the vulnerability.

2022-11-11 14:12 UTC, cvwright commented on proposals/1767-extensible-events.md
> +to render a bridge state change with `m.markup` to clearly indicate a bridge was added/edited.
> > Can't we just say that standard state events (those beginning with `m.`) don't support content blocks to solve this problem?
> 
> Preferably not, because special casing causes problems. I also don't really see how this solves the problem?

Distinguishing state events vs non-state events is not really special casing though, is it?  They are two fundamentally different things in the spec.

2022-11-11 14:16 UTC, cvwright commented on proposals/1767-extensible-events.md
> +to render a bridge state change with `m.markup` to clearly indicate a bridge was added/edited.
> From out of band, the case I'm most worried about is something like a client implementing a state event but continuing to let "fallback" content blocks to inform and override its rendering. 

Yes exactly.  To put a somewhat finer point on it, suppose a compromised homeserver maliciously added a user to the room.  The story all along has been that "Users should pay attention to room membership".  But now that defense just got a lot more difficult, because now the `m.room.member` event in the timeline can be disguised with a fallback message / cover story.

2022-11-11 14:25 UTC, cvwright commented on proposals/1767-extensible-events.md
> +This allows the `m.encrypted` content block to be reused by other event types, if required.
> > Could this be used as an alternative to #3911 for linking media to encrypted events?
> > ...
> 
> Unlikely - that would make things more complicated.

Sorry, I meant that more as "Is this the kind of thing you are envisioning?" more than "Do you think this particular application is a good idea?"

Overall I don't see a serious problem here.  There are often legitimate reasons to send plaintext data alongside of some ciphertext.  Articulating such a use case here might help to justify this part of the proposal, but even without one it's not a stretch to believe that they could exist.

Clients just need to not be stupid about what they send in the clear, and as you said, this is already a requirement.

2022-11-11 14:36 UTC, cvwright commented on proposals/1767-extensible-events.md
> +This allows the `m.encrypted` content block to be reused by other event types, if required.
Actually on second thought, allowing encrypted content blocks in lots of different message types could be quite cool.

Then the server could filter messages by type, reducing the number of messages that a client must download and decrypt.

2022-11-11 14:41 UTC, turt2live commented on proposals/1767-extensible-events.md
> +to render a bridge state change with `m.markup` to clearly indicate a bridge was added/edited.
We discussed that in the room: clients should be treating member events as known, but point taken that it's possible for developers to make mistakes. The requirements @dkasak talks about are actually already in the proposal, just not obviously.

2022-11-11 17:57 UTC, bleonard252 commented on proposals/1767-extensible-events.md
> +to render a bridge state change with `m.markup` to clearly indicate a bridge was added/edited.
Recognized state events, like m.room.member events in most clients, obviously wouldn't use m.markup. However, we could recommend clients to show a warning that "An unknown change was made."

2022-11-17 06:40 UTC, turt2live commented on proposals/1767-extensible-events.md
> +### Room version
How does the client know it is speaking in a suitable room version though? Hardcoding works for the first room version, but as soon as we add a second room version we'll have a bunch of outdated clients.

Probably shove something into the capabilities API?

2022-11-17 10:59 UTC, andybalaam commented on proposals/1767-extensible-events.md
> +Unlike previous iterations of this proposal, it is not expected that content block
This paragraph is useful for people familiar with history, and very confusing for someone reading this the first time. Can we make it a sidebar, or relegate it to a footnote?

2022-11-17 13:06 UTC, clokep commented on proposals/1767-extensible-events.md
> +### Room version
MSC3244 attempted to handle this for spaces, but has since been rejected.

2022-11-17 16:22 UTC, turt2live commented on proposals/1767-extensible-events.md
> +### Room version
From memory, the issue with MSC3244 was that it was attempting to describe a server preference for room version features, not considering the client's need, and was for *creating* rooms. The difference here would be *using* rooms.

2022-12-20 09:41 UTC, wmwsagara commented
I'm trying to create a feed (eg. world events, financial charts, etc) for our users.

This requires at minimal following in the message:
1. An image
2. Textual note on top the image.
3. An url to attached to the image to go to an external website for detail.

I noted, Matrix currently doesn't have a message type (msgtype) for this.

Does this MSC1767 cover this requirement? 

If not, is it possible to introduce a new msgtype or a way to extent the "msgtype: m.image" in MSC1767 itself?

2023-01-13 05:02 UTC, turt2live commented on proposals/1767-extensible-events.md
> +To support event types which may need an emote or notice fallback, `m.emote` and `m.notice`
Emotes are now https://github.com/matrix-org/matrix-spec-proposals/pull/3954 and notices are https://github.com/matrix-org/matrix-spec-proposals/pull/3955

The proposal text here is updated in 48e058849e6d47eb79e4ec6df26d6e1f7dc900fe

2023-01-13 05:03 UTC, turt2live commented on proposals/1767-extensible-events.md
> +to render a bridge state change with `m.markup` to clearly indicate a bridge was added/edited.
As of 48e058849e6d47eb79e4ec6df26d6e1f7dc900fe this MSC no longer recommends state events to be treated as timeline events at all, instead doing the formality of promoting existing `content` bodies of state events to relevant content blocks (not that anyone is expected to deal with them - see updated proposal text).

2023-01-13 05:04 UTC, turt2live commented on proposals/1767-extensible-events.md
> +This allows the `m.encrypted` content block to be reused by other event types, if required.
Encrypted events are now their own dedicated MSC for further discussion: https://github.com/matrix-org/matrix-spec-proposals/pull/3956

This proposal is updated as of 48e058849e6d47eb79e4ec6df26d6e1f7dc900fe to reflect this.

2023-01-13 05:04 UTC, turt2live commented on proposals/1767-extensible-events.md
> +Unlike previous iterations of this proposal, it is not expected that content block
Clarified in 48e058849e6d47eb79e4ec6df26d6e1f7dc900fe

2023-01-14 00:09 UTC, turt2live commented
I have updated the implementations and believe this MSC is ready to go again. The Element Web implementation is *not* landed as of writing, however the PRs prove that it is possible to make a client respect the constraints of this MSC.

**Please note the spec process approach denoted in the MSC itself before raising concerns/questions**

@mscbot fcp merge

2023-01-14 00:14 UTC, turt2live commented on proposals/1767-extensible-events.md
> +### Room version
I'm implicitly deferring this to a future MSC to figure out. For now, hardcoding room versions which support/don't support extensible events is working well enough (but won't work in the later stages of the project: see spec process section of this MSC)

2023-01-17 13:12 UTC, dbkr commented on proposals/1767-extensible-events.md
> +prior to extensible events even existing).
Much as this section is already fairly complex, it might help to explain that content blocks are not necessarily alternative representations and there may be no single content block that fully describes the whole event - you might need to combine multiple content blocks to get the full picture, and call out to mixins.

2023-01-17 15:55 UTC, turt2live commented on proposals/1767-extensible-events.md
> +  however are equally permitted to send an HTML representation instead.
I've dropped the bit after the comma - the first part is the important part ("please always send plain text at a minimum")

2023-01-17 15:59 UTC, turt2live commented on proposals/1767-extensible-events.md
> +extensible events in a published (stable) room version.
It'll still be the regular MSC process (we'll need an MSC to make the stable room version happen anyways) - this is just clarifying that the SCT is responsible for determining which of the dozens of MSCs end up landing "first" rather than letting it evolve organically.

2023-01-17 16:03 UTC, turt2live commented on proposals/1767-extensible-events.md
> +Meanwhile, clients can send mixed support for extensible events if they prefer (such as by
I'm just going to remove this feature - it doesn't serve value.

2023-01-17 16:17 UTC, turt2live commented on proposals/1767-extensible-events.md
> +described as sent by a bot, thus reducing feedback loops.
I've added a couple paragraphs which I think might help, but might also be more noise - let me know what you think 😇

2023-01-17 16:28 UTC, turt2live commented on proposals/1767-extensible-events.md
> +prior to extensible events even existing).
ah, yes, that would be a good thing to call out. I've added some words to hopefully do so - let me know what you think.

2023-01-17 18:35 UTC, richvdh reviewed
Overall: seems generally sensible. A few questions.

2023-01-17 18:35 UTC, richvdh commented on proposals/1767-extensible-events.md
> +Though this MSC does not describe any such mixins itself, MSC3955 does by allowing any
```suggestion
Though this MSC does not describe any such mixins itself, [MSC3955](https://github.com/matrix-org/matrix-spec-proposals/pull/3955) does by allowing any
```

2023-01-17 18:35 UTC, richvdh commented on proposals/1767-extensible-events.md
> +thus all event types MUST support being rendered/processed *without* the use of mixins.
so to be clear: a mixin is a special sort of content block which exists only to be added on to other event types?

I feel like the boundary between what is, and is not, a mixin is pretty fuzzy. For example, MSC3551 defines an `m.caption`. It's optional, so the event supports being rendered/processed without it. What makes `m.automated` a mixin, but `m.caption` not?

2023-01-17 23:03 UTC, turt2live commented on proposals/1767-extensible-events.md
> +thus all event types MUST support being rendered/processed *without* the use of mixins.
it's a bit difficult to describe tbh. `m.caption` isn't a mixin because it can't universally be applied to any event type ("what does it mean to caption a poll"), which I guess might be the distinguishing factor?

2023-01-17 23:04 UTC, turt2live commented on proposals/1767-extensible-events.md
> +It is left as a deliberate implementation detail for which schemas to try, and in what
this behaviour is not necessarily client-specific, though it could be argued servers are acting as clients when consuming these events.

I'd rather leave it open if it's not affecting overall understanding of the MSC.

2023-01-17 23:07 UTC, turt2live commented on proposals/1767-extensible-events.md
> +and stable settings).
later in the MSC we mention those exceptions - will clarify up here to expect that text.

2023-01-17 23:10 UTC, turt2live commented on proposals/1767-extensible-events.md
> +not try to "cast" unknown events into that type.
have removed this paragraph - it's duplicating information.

2023-01-17 23:14 UTC, turt2live commented on proposals/1767-extensible-events.md
> +thus all event types MUST support being rendered/processed *without* the use of mixins.
I've added a note to this section to hopefully clear this specific concern up - let me know if it helps.

2023-01-18 10:28 UTC, richvdh commented on proposals/1767-extensible-events.md
> +It is left as a deliberate implementation detail for which schemas to try, and in what
I was just trying to correct the grammar here tbh. Possibly "Which schemas to try, and in what order, is left as a deliberate implementation detail."

2023-01-18 18:03 UTC, richvdh commented on proposals/1767-extensible-events.md
> +thus all event types MUST support being rendered/processed *without* the use of mixins.
It helps, but I think it would be clearer to start out with a definition:

```suggestion
A **mixin** is a specific type of content block which can be added to any type of event to
change how that event is processed. Content blocks which are
mixins will be called out as such in the spec. Mixins are meant to be purely additive,
thus all event types MUST support being rendered/processed *without* the use of mixins.

See also the [Wikipedia entry on mixins](https://en.wikipedia.org/wiki/Mixin).
```

2023-01-18 18:13 UTC, turt2live commented on proposals/1767-extensible-events.md
> +then text message, for example.
```suggestion
Which schemas to try, and in what order, is left as a deliberate implementation detail.
A client might decide to try parsing the event as a video, then image, then file, then 
text message, for example.
```

ref https://github.com/matrix-org/matrix-spec-proposals/pull/1767/files#r1073357017

2023-01-18 18:13 UTC, turt2live commented on proposals/1767-extensible-events.md
> +It is left as a deliberate implementation detail for which schemas to try, and in what
ah, that works - will adopt via https://github.com/matrix-org/matrix-spec-proposals/pull/1767/files#r1073903152

2023-01-23 13:41 UTC, dbkr commented on proposals/1767-extensible-events.md
> +  for recommended allowable HTML.
Well, before there is an explicit 'strongly suggested' list of tags, but here we're just mentioning it as one way clients might choose to do it. If we want to keep it the same, we should actually make the same suggestion. This could just be by saying, "the same set of strongly suggested tags from https://spec.matrix.org/v1.4/client-server-api/#mroommessage-msgtypes apply here too" or something.

2023-01-30 07:10 UTC, KitsuneRal commented
@mscbot concern `m.markup` is a weird name for a content block that will not have any markup 80% of the time

2023-01-30 17:32 UTC, turt2live commented on proposals/1767-extensible-events.md
> +when mixing in `m.room.message` compatibility, though mixes nicely thanks to namespacing.
err, no, it's not - will remove/reword (thought I did, honestly)

2023-01-30 17:32 UTC, turt2live commented on proposals/1767-extensible-events.md
> +`m.markup` has the following definitions associated with it:
`m.markup` rename thread

2023-01-30 17:33 UTC, turt2live commented on proposals/1767-extensible-events.md
> +`m.markup` has the following definitions associated with it:
`m.text` feels more natural, though could lead to confusion when it's non-plain text?

2023-01-30 17:33 UTC, turt2live commented on proposals/1767-extensible-events.md
> +`m.markup` has the following definitions associated with it:
`m.mime_text` is descriptive, though sounds weird. Doesn't feel like it covers future extensions like translations very well either.

2023-01-30 18:43 UTC, KitsuneRal commented on proposals/1767-extensible-events.md
> +`m.markup` has the following definitions associated with it:
`m.text_block` (it really should be a text block from the layout perspective)

2023-01-30 18:45 UTC, KitsuneRal commented on proposals/1767-extensible-events.md
> +`m.markup` has the following definitions associated with it:
`m.text_alternatives` (looong but conveys the idea that the array lists alternative content representations, not a sequence of those).

2023-01-30 20:31 UTC, bleonard252 commented
How about *m.default*? Considering it would be present in almost every message, usable on its own, and as a fallback. Otherwise I second *m.text*, as it's concise and signifies it isn't intended for use for, say, images (unless it is?)

Jan 30, 2023 14:06:40 Travis Ralston ***@***.***>:

> ***@***.**** commented on this pull request.
> 
> ----------------------------------------
> 
> In proposals/1767-extensible-events.md[https://github.com/matrix-org/matrix-spec-proposals/pull/1767#discussion_r1091034149]:
> 
>> +a minimum, a `m.markup` content block:
> +
> +```json5
> +{
> +    // irrelevant fields not shown
> +    "type": "m.message",
> +    "content": {
> +        "m.markup": [
> +            { "body": "<i>Hello world</i>", "mimetype": "text/html" },
> +            { "body": "Hello world" }
> +        ]
> +    }
> +}
> +```
> +
> +`m.markup` has the following definitions associated with it:
> 
> *m.text_block* (it really should be a text block from the layout perspective)
> 
> they're all blocks :p
> 
> —
> Reply to this email directly, view it on GitHub[https://github.com/matrix-org/matrix-spec-proposals/pull/1767#discussion_r1091034149], or unsubscribe[https://github.com/notifications/unsubscribe-auth/ADUJCOTR5DUY26QIRNRS5FDWVAGL7ANCNFSM4GMYH3LQ].
> You are receiving this because you are subscribed to this thread.[Tracking image][https://github.com/notifications/beacon/ADUJCOX3OA56OUN72VFJCEDWVAGL7A5CNFSM4GMYH3L2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOJQFQRLA.gif]
>

2023-01-30 20:38 UTC, turt2live commented on proposals/1767-extensible-events.md
> +`m.markup` has the following definitions associated with it:
from @bleonard252 via email:

> How about *m.default*? Considering it would be present in almost every message, usable on its own, and as a fallback. Otherwise I second *m.text*, as it's concise and signifies it isn't intended for use for, say, images (unless it is?)

`m.default` feels a bit too out of the area as not all events will use it, by design. Internally we're rallying behind `m.text` though because it provides enough sensible meaning and any confusion would be clarified by another client spitting out parse errors.

2023-01-31 00:59 UTC, turt2live commented on proposals/1767-extensible-events.md
> +  for recommended allowable HTML.
Fixed in 68612194069ccf6a98655dc58335931452a0e0a4

2023-01-31 01:01 UTC, turt2live commented on proposals/1767-extensible-events.md
> +when mixing in `m.room.message` compatibility, though mixes nicely thanks to namespacing.
Fixed in c5db1a059d4f62b4e8bba9abb545afa03c982f59

2023-01-31 01:02 UTC, turt2live commented on proposals/1767-extensible-events.md
> +`m.markup` has the following definitions associated with it:
`m.text` it is unless others have a better option.

2023-01-31 16:19 UTC, KitsuneRal commented on proposals/1767-extensible-events.md
> +`m.markup` has the following definitions associated with it:
@mscbot resolve `m.markup` is a weird name for a content block that will not have any markup 80% of the time

2023-01-31 19:03 UTC, anoadragon453 approved these changes

2023-01-31 19:23 UTC, turt2live commented on proposals/1767-extensible-events.md
> +blocks as needed. Other MSCs may override this decision on a per-event type basis (ie: redeclaring
98bc9addba9fc0b5fcf6d214cb6018f223e67aac

2023-01-31 19:24 UTC, turt2live commented on proposals/1767-extensible-events.md
> +described as sent by a bot, thus reducing feedback loops.
Considering resolved due to FCP checkbox being ticked.

2023-01-31 19:24 UTC, turt2live commented on proposals/1767-extensible-events.md
> +prior to extensible events even existing).
Considering resolved due to FCP checkbox being ticked.

2023-01-31 19:27 UTC, turt2live commented on proposals/1767-extensible-events.md
> +`m.markup` has the following definitions associated with it:
71611964105311da79416c1d69b1cd16dff3e9a3

2023-02-06 02:10 UTC, merged

2023-02-07 09:04 UTC, ara4n commented on proposals/1767-extensible-events.md
> +`m.markup` has the following definitions associated with it:
oh, thank god this got renamed - thank you! :)

2023-02-07 16:30 UTC, turt2live commented
(Someone ticked their box post-fcp, and the bot is confused: ignore it)

2023-07-13 13:37 UTC, anoadragon453 commented on proposals/1767-extensible-events.md
> +`m.relates_to` does actually end up being a mixin).
What about reactions those? Surely those can't function without a relation being present either.

2023-07-13 17:52 UTC, turt2live commented on proposals/1767-extensible-events.md
> +`m.relates_to` does actually end up being a mixin).
yea... reactions are awkward. The relationship should be additive (without aggregation key), but representing the aggregation key as a content block is difficult. The expectation is that a dedicated MSC would solve extev reactions.

2023-10-03 21:26 UTC, networkException commented on proposals/1767-extensible-events.md
> +In room versions supporting extensible events, clients MUST only send extensible events.
Upgrading a room creates an entirely new room, "old" events will not be present in there.

2023-10-03 22:10 UTC, julioromano commented on proposals/1767-extensible-events.md
> +In room versions supporting extensible events, clients MUST only send extensible events.
noob alert!

Oh I wasn't aware of this, where does the spec mention it?

2023-10-03 22:31 UTC, networkException commented on proposals/1767-extensible-events.md
> +In room versions supporting extensible events, clients MUST only send extensible events.
Here for example: https://spec.matrix.org/v1.8/client-server-api/#server-behaviour-16

2023-10-04 06:43 UTC, julioromano commented on proposals/1767-extensible-events.md
> +In room versions supporting extensible events, clients MUST only send extensible events.
Super thanks! I naively thought such an important thing would be mentioned in https://spec.matrix.org/v1.8/rooms/ . I still have to get used at how the spec chapters are organized.

2024-05-30 22:17 UTC, Gnuxie commented on proposals/1767-extensible-events.md
> +
Power levels provide no provision for restricting what media (via mixins) you can embed into events.

2024-06-25 16:57 UTC, anoadragon453 commented on proposals/1767-extensible-events.md
> +
@Gnuxie could you write this up as a new issue to make sure it doesn't get lost?

2024-08-16 21:35 UTC, KnowledgeGarden commented
Perhaps an extremely naive question, but here goes:
Suppose I want to do something in a Matrix client much like, say, Kialo, events for which are new text messages, but they are situated in the context of a parent node, which, itself, is situated in a Pro-Con debate graph; the view painted would be, first, the graph, then, when a node is selected, the graph shifts to place that node as the local "root" at the top.
My question, then, is this: can an extensible message type allow for a type which entails an entire JSON graph object with individual nodes?
Many thanks in advance - Jack

2024-08-16 23:09 UTC, Gnuxie commented on proposals/1767-extensible-events.md
> +
https://github.com/matrix-org/matrix-spec/issues/1932

2024-08-17 16:54 UTC, KnowledgeGarden commented
@Gnuxie Thanks for that link.  I'm at a loss.  It circularly points back to this issue.
m.room.power_levels is not mentioned in the latest api spec at
https://spec.matrix.org/latest/
but it is at
https://spec.matrix.org/legacy/client_server/r0.2.0.html
and
https://spec.matrix.org/unstable/rooms/v1/  and https://ems-docs.element.io/books/element-support/page/managing-a-room-advanced-room-management
There is a page on using that property at
https://snyk.io/advisor/npm-package/m/functions/m.room.power_levels

Power Levels is a State parameter.  I am curious why it shows up here. I'm looking for an example of how powerlevels affects media type.
I am asking about Message Type flexibility.
I got a hint about it here
https://github.com/matrix-org/matrix-events-sdk
which is buried in Element dependencies, but that repo hasn't been touched since last year and is still marked as "work in progress" and "use at your own risk".
I suspect that extensible message types is not particularly high a priority.

2024-08-17 19:14 UTC, Gnuxie commented
@KnowledgeGarden sorry the link is unrelated, you just bumped the issue and reminded me to open an issue that i forgot about.

2025-02-23 17:19 UTC, taras-bl reviewed
```
@florianjacob 
```