MSC2246: Asynchronous media uploads
matrix-org/matrix-spec-proposals pull request #2246
Opened 2019-08-24 13:51 UTC by tulir

[Rendered](https://github.com/tulir/matrix-doc/blob/asynchronous_uploads/proposals/2246-asynchronous-uploads.md)

2019-08-24 14:11 UTC, ara4n commented
sounds excellent to me; would love to unblock streaming transfers at last.
need to consider risk of DoS by creating lots of IDs, and define the json if any handed to the /create (for instance, could be useful in future for defining whether a give mxc url should be locked behind auth of some kind)

2019-08-26 15:24 UTC, turt2live submitted a review, later dismissed
also generally looking in the right direction - I've left some early comments which are hopefully helpful.

2019-08-26 20:34 UTC, tulir commented on proposals/2246-asynchronous-uploads.md
> +`content_uri` that can be used in events. Additionally, the response would
Since the new upload endpoint was changed to not require splitting the media ID out of the MXC URI, the create endpoint also only returns the MXC URI like the existing upload endpoint.

Example response content added too

2019-08-26 20:34 UTC, tulir commented on proposals/2246-asynchronous-uploads.md
> +Create a new MXC URI without content. Like `/upload`, this endpoint returns the
yes

2019-08-26 20:37 UTC, tulir commented on proposals/2246-asynchronous-uploads.md
> +method could cause a lot of open HTTP connections.
Added that to the `/create` endpoint

2019-08-27 17:04 UTC, bmarty commented
The idea is then to send a media event, after the new /create endpoint, and before sending the media itself; isn't it? We have to consider the failure of the upload: it can lead to media event with eternal not found media.
Also the client should have a way to know that the media is not yet available to the server for a better UI, by displaying a waiting message (ex: `Bob is sending an image`) for instance?

2019-08-28 12:33 UTC, manuroe commented on proposals/2246-asynchronous-uploads.md
> +content repository should stall the request until it is uploaded. Optionally,
We cannot block the request more than timeouts. If the media is not yet available (or not streamable), could we send an error with a `retry_after_ms` value providing an ETA based on upload speed for example?

2019-08-29 07:56 UTC, tulir commented on proposals/2246-asynchronous-uploads.md
> +content repository should stall the request until it is uploaded. Optionally,
Yeah, I think some query param in `/download` to return an error instead of stalling is needed so clients can do what suits them best. Stalling is probably good as the default since it's backwards-compatible for clients as long as it doesn't time out.

That error could also be used to show some kind of "Bob is sending an image" like @bmarty suggested.

2020-08-01 22:41 UTC, tulir commented on proposals/2246-asynchronous-uploads.md
> +content repository should stall the request until it is uploaded. Optionally,
Added `max_stall_ms` to specify how long the client wants to wait before it starts receiving data.

2021-05-22 23:18 UTC, JuniorJPDJ commented
bump?

2022-03-14 14:17 UTC, ShadowJonathan commented on proposals/2246-asynchronous-uploads.md
> +If the upload is successful, an empty JSON object and status code 200 is
I think that a successful upload must include "the client did upload the whole request body"

I can think of a situation where a client starts uploading media, but then the connection is disrupted, the client may want to continue (not represented here), or retry.

Seeing as this is a one-and-done endpoint, the server should be stringent on when the client is "done" uploading, and not accept a half-uploaded body, so the client should also send a `content-length` header (I'm not entirely sure if it should be mandatory or heavily recommended) to make sure the server receives the entire file before confirming it.

2022-03-14 14:17 UTC, ShadowJonathan commented on proposals/2246-asynchronous-uploads.md
> +  `true`.
See my comment above, I think this is problematic together with a cut-off upload, as a client may start uploading one file, cut it off arbitrarily, and then start uploading a different one.

Together with this option, I think the server should protect itself against "different subsequent uploads", and only accept what the client previously was sending.

Another alternative is that the server allows resuming uploads, though the same rules of "matching what you previously sent" should apply.

2022-03-14 14:17 UTC, ShadowJonathan commented on proposals/2246-asynchronous-uploads.md
> +should return a `M_NOT_YET_UPLOADED` error. The error may include an additional
Should this be together with a `504` HTTP error of sorts?

2022-03-21 19:42 UTC, turt2live commented
The author believes this MSC has all the required implementation detail and is ready for FCP.

2022-03-22 16:30 UTC, richvdh commented
looks great to me.

@mscbot fcp merge

2022-03-23 10:46 UTC, erikjohnston reviewed
Seems like a good idea to me!

2022-03-23 10:46 UTC, erikjohnston commented on proposals/2246-asynchronous-uploads.md
> +JSON. The recommended default expiration for starting the upload is 1 minute.
I'm a bit unsure about this. The resources taken up by an unused media ID is minimal (just a row in the DB), whereas failing to upload media in time means that the associated event forever links to broken data. 

The scenario I'm thinking of is dodgy/slow internet connection, where it wouldn't be unreasonable to struggle to upload the media in time. We could increase the recommended default expiry, but I'm not entirely sure what the expiry really buys in practice.

2022-03-23 10:46 UTC, erikjohnston commented on proposals/2246-asynchronous-uploads.md
> +client should try again.
How does the server know what to use for `retry_after_ms`? I don't think it has any special knowledge of when the upload is likely to complete? Or is this just a mechanism for telling clients to back off and stop re-requesting constantly?

2022-03-23 10:56 UTC, hifi commented on proposals/2246-asynchronous-uploads.md
> +JSON. The recommended default expiration for starting the upload is 1 minute.
The expiry is to prevent clients from retrying/waiting forever for files that are never uploaded. Increasing the suggested time may be reasonable if the upload fails for any reason as it would prevent retrying if you're uploading a large file making that media ID stale.

2022-03-23 11:03 UTC, hifi commented on proposals/2246-asynchronous-uploads.md
> +client should try again.
It's a back off suggestion. The server _could_ know when to expect an upload to complete as it could calculate the upload speed and expected completion based on content length header from the upload itself and give a good suggestion.

All of this is intentionally left out to leave it as implementation detail as the server could also start streaming the download as soon as the upload has started (given it known the content length).

2022-03-25 07:16 UTC, sumnerevans commented on proposals/2246-asynchronous-uploads.md
> +#### `PUT /_matrix/media/v3/upload/{serverName}/{mediaId}`
What should happen if you try to upload to a server name that isn't the user's homeserver?

It seems like @hifi responds 404 in this case? https://github.com/turt2live/matrix-media-repo/pull/364/files#diff-3ddbc505e50723b8440369eef4dc1fa055026668151b1dbecbd1725fc6765727R70-R72

2022-03-25 09:33 UTC, tulir commented on proposals/2246-asynchronous-uploads.md
> +#### `PUT /_matrix/media/v3/upload/{serverName}/{mediaId}`
> If the serverName/mediaId combination is not known or not local, an `M_NOT_FOUND` error is returned.

2022-03-29 14:02 UTC, erikjohnston commented on proposals/2246-asynchronous-uploads.md
> +JSON. The recommended default expiration for starting the upload is 1 minute.
I've been thinking about this a bit, and I agree it would be good to support both requests for the media a) initially blocking until the media starts getting uploaded, and b) after a while returning an error code immediately if the media hasn't been uploaded yet.

I guess the questions are:

1. Do we want to forbid the client from uploading the media after the server has started returning errors for the media?
2. Relatedly: what error should we return? A 5xx would indicate that it might later succeed and would allow late uploads, or a 404 if we don't.
3. Do we want or need to tell the client how long they have to upload the media? What would the client do with that information?

Allowing late uploads means that every time a client comes to display the media it will retry, whereas if we return a 404 it could potentially cache that the media will never be uploaded. My hunch though is that clients won't ever bother caching error responses, so there's not much need to disallow late uploads?

I don't think this is a huge issue either way ftr.

2022-04-15 16:24 UTC, sumnerevans commented on proposals/2246-asynchronous-uploads.md
> +the error code `M_CANNOT_OVERWRITE_MEDIA` and HTTP status code 409. The endpoint
Should this error code also be used for when the created media has expired?

2022-05-03 19:29 UTC, uhoreg commented on proposals/2246-asynchronous-uploads.md
> +the error code `M_CANNOT_OVERWRITE_MEDIA` and HTTP status code 409. The endpoint
I think for expired media IDs, it would make sense to use the same error as for unknown media IDs (M_NOT_FOUND), so that servers don't need to remember the IDs that it created but that have expired -- servers just need to remember active IDs, and when they expire, they can be dropped and forgotten.

2022-05-03 19:36 UTC, uhoreg commented on proposals/2246-asynchronous-uploads.md
> +should also reject upload requests from users other than the user who created
M_FORBIDDEN seems like a reasonable error code for this case.  Should that be added here?

2022-05-28 19:51 UTC, jplatte commented on proposals/2246-asynchronous-uploads.md
> +A new query parameter, `max_stall_ms` is added to the endpoints that can
I think "stall" is rather uncommon wording for defining a timeout. Maybe just call it that: `timeout_ms`? (could also prefix with `upload_` or sth. like that.

2022-05-30 15:33 UTC, sumnerevans commented
FWIW, https://github.com/matrix-org/synapse/pull/12484 is a working implementation of this MSC in Synapse.

2022-06-01 03:09 UTC, turt2live requested changes
I think generally this feature is something we want, however I'm concerned that it needs to go back a step into API design before going forward with spec. In particular, I think it will be far too frustrating for clients to handle connectivity issues and get their upload completed in a 20 or 60 second window: we should instead find a way to let them upload the media at their convenience. 

I've also thumbs-upped several comments from others which I think are blocking considerations for this MSC, and will try to translate them into mscbot concerns after this review.

Process-wise for this case, we first battle it out in the comments. The expectation going into this is that the MSC will change, and the question is how dramatic that change will be. With the MSC having nearly enough checkboxes ticked (sorry), the question more or less translates to whether the changes are significant enough to warrant re-review from the rest of the team. If the changes are significant enough, the FCP will be cancelled and re-proposed. Otherwise, we'll continue as normal. For the rare case of ending up on something that is unrecognizably different, we might ask for a new MSC to be opened. For the equally rare case that we end up changing nothing after the battle, we'd just unblock the MSC and continue per normal.

With my Media Guy hat o, I'm not fully comfortable with this MSC moving forward as-is: we really need to support the client taking an eternity to upload their file.

2022-06-01 03:09 UTC, turt2live commented on proposals/2246-asynchronous-uploads.md
> +A new query parameter, `max_stall_ms` is added to the endpoints that can
We should also add the words "the server can and should impose a maximum value for this parameter".

2022-06-01 03:09 UTC, turt2live commented
@mscbot concern Different spam reduction controls appear to be required (read: taking a while to upload is a feature)
@mscbot concern Edge case error codes need to be specified
@mscbot concern Empty security considerations on a user-generated content endpoint
@mscbot concern The client shouldn't be allowed to stall the server for infinite milliseconds (the server should impose a limit)

2022-06-01 05:33 UTC, ShadowJonathan commented on proposals/2246-asynchronous-uploads.md
> +JSON. The recommended default expiration for starting the upload is 1 minute.
An invisible quota system might be more a problem than a solution, as if a client expects to be able to upload 50 concurrent files, while the server internally only allows 10, then it'll result in unstable/unusable UX. (E.g. those first 40 files erroring out on others' screens, and/or erroring on the uploader's side, depending how this is implemented)

If there's a quota, the server should expose it, so clients can schedule uploads accordingly.

2022-06-01 05:38 UTC, ShadowJonathan commented on proposals/2246-asynchronous-uploads.md
> +is left for another MSC.
I think this paragraph has some hidden history, this is a change from the original requirement (include streaming) after I commented about some security concerns [here](https://github.com/matrix-org/matrix-spec-proposals/pull/2246#discussion_r825995723), TLDR: it's not as much about being able to stream, but that the file is mutable while it's streamed, and that there's an edge case where; if a client closes the upload stream, starts again, but then uploads a wholly different file, how should everything then fail/proceed gracefully to accommodate this new situation?

2022-06-01 05:45 UTC, turt2live commented on proposals/2246-asynchronous-uploads.md
> +JSON. The recommended default expiration for starting the upload is 1 minute.
we do have the media config endpoint we could use for it, though it might also be desirable to hide the number.

A problem I just realized is that a rotating quota doesn't really help if the user sends the ID in an event: it's not like we can reuse that media ID ever again, so we still have the database row. A reliable solution isn't immediately obvious, however.

Generally I'm quite concerned that trying to get clients to upload their media fast enough just won't work, particularly if there's no consequence for the client to keep requesting these things within a rate limit.

2022-06-01 05:48 UTC, turt2live commented on proposals/2246-asynchronous-uploads.md
> +is left for another MSC.
that sounds like a thing we should fix as part of this MSC regardless, to be honest. Does a partial failed upload count as uploading the media? (ie: does the server mark the media as "uploaded" at the start or the request handling or at the end?) what happens if the client tries to upload the media twice (concurrently)?

2022-06-01 06:58 UTC, ShadowJonathan commented on proposals/2246-asynchronous-uploads.md
> +is left for another MSC.
I also poked at the "partial uploads" problem [here](https://github.com/matrix-org/matrix-spec-proposals/pull/2246#discussion_r825993890), imo, there shouldn't be partial uploads, and the client should send `content-length` in the request body to have the server make sure it received everything before it commits the file.

Concurrent uploading is something I hadn't considered.

2022-06-01 07:22 UTC, hifi commented on proposals/2246-asynchronous-uploads.md
> +JSON. The recommended default expiration for starting the upload is 1 minute.
Is it much different from clients uploading small files and creating MXCs that way as that's already abusable the exact same way? The upload endpoint is authenticated so at least it's easy to determine where the abuse is coming from.

We could specify (or leave it as an implementation detail) that the expiry time is reset every time an upload is starting/performing to make retries work indefinitely as long as the client doesn't forget to start/retry the upload completely.

2022-07-08 21:45 UTC, sumnerevans commented on proposals/2246-asynchronous-uploads.md
> +JSON. The recommended default expiration for starting the upload is 1 minute.
If we go with the quota idea, it seems like we would want to have an expiration timeout still, in case a client crashes and never finishes the upload.

We don't want a dead upload to permanently cause the user's quota to be lowered.

2022-07-08 22:09 UTC, turt2live commented on proposals/2246-asynchronous-uploads.md
> +JSON. The recommended default expiration for starting the upload is 1 minute.
There's also a new potential usecase on the horizon where we'd want extremely long-lived media uploads (could take literal hours to finish uploading the media), so would be good to consider what a timeout-less system looks like I think.

2023-03-31 22:08 UTC, sumnerevans commented on proposals/2246-asynchronous-uploads.md
> +JSON. The recommended default expiration for starting the upload is 1 minute.
I believe that these concerns have been addressed in the latest version of the MSC. The main mechanisms are:

1. Implementing the "quota" system described above where the quota is on the number of "pending media uploads" (un-expired MXCs that haven't received their upload)
2. Allowing servers to return earlier than the `timeout_ms` if desired (for example, if the server is running out of available connections)

I think that exploring a timeout-less system should be done in a separate MSC.

2023-03-31 22:09 UTC, sumnerevans commented on proposals/2246-asynchronous-uploads.md
> +## Security considerations
The section has been updated in the latest version of the MSC.

2023-03-31 22:12 UTC, sumnerevans commented on proposals/2246-asynchronous-uploads.md
> +milliseconds that the client is willing to wait to start receiving data.
Added clarification that servers can ignore the timeout, and should do so if the media is immediately available or immediately unavailable (expired)

The latest version of the MSC also states that the server can ignore (or choose to only respect a shorter timeout) at any time, allowing it to adapt to the current resource constraints.

2023-04-04 18:40 UTC, dbkr commented on proposals/2246-asynchronous-uploads.md
> +status code 409.
What if the upload fails but the bridge has already sent the message containing the MXC URI? This might need some more detail on exactly how multiple calls to the endpoint work, although it's been touched on in other comments.

To throw a few ideas out:
 * Include a content length & hash in the create endpoint (although of course this would rule out the client generating the media during upload, eg. live streaming video)
 * HTTP chunking on uploads
 * Other things that have already been mentioned like requiring content-length in the upload call, but being explicit that the server would consider the upload 'finalised' once it had the advertised number of bytes.
 
For concurrent uploads, could leave it up to the HS to decide how to handle sensibly, possibly advising that later uploads kick off any started earlier?

2023-04-19 21:10 UTC, turt2live commented on proposals/2246-asynchronous-uploads.md
> +# Asynchronous media uploads
```suggestion
# MSC2246: Asynchronous media uploads
```

2023-04-19 21:17 UTC, turt2live commented on proposals/2246-asynchronous-uploads.md
> +auth and returns the `content_uri` that can be used in events.
```suggestion
Create a new MXC URI without content. Like `/upload`, this endpoint requires
auth, can be rate limited, and returns the `content_uri` that can be used in events.
```

2023-04-19 21:19 UTC, turt2live commented on proposals/2246-asynchronous-uploads.md
> +returned.
```suggestion
returned. Rate limiting additionally can apply here.
```

2023-04-19 21:28 UTC, turt2live commented on proposals/2246-asynchronous-uploads.md
> +status code 409.
fwiw, as the person currently holding this MSC up, I'm not too concerned with this case. The two most likely scenarios are:

1. The http client can't hit the server for some reason. If the call is interrupted or otherwise has a connection error then the upload can/should be cancelled/invalidated. Similarly, most http clients buffer a good portion of the request (and when they don't, http servers tend to do a lot of buffering at the application level): this buffering means that even if the client doesn't see the response the upload is still likely to be successful.

2. The server encounters an error during the processing of the upload. In this case, the server should reject the http request with a 500 or similar error and not consider any potentially-partial content as uploaded.

There's certainly an argument for improved error handling though - I'll leave that to @dbkr & others to decide if it warrants an `@mscbot concern` comment :)

2023-04-19 21:29 UTC, turt2live approved these changes
lgtm, assuming the following comments can be addressed prior to acceptance (blocks FCP completing, not starting):

https://github.com/matrix-org/matrix-spec-proposals/pull/2246/files#r1170578353
https://github.com/matrix-org/matrix-spec-proposals/pull/2246/files#r1171865645

2023-04-19 21:29 UTC, turt2live commented
@mscbot resolve Different spam reduction controls appear to be required (read: taking a while to upload is a feature)
@mscbot resolve Edge case error codes need to be specified
@mscbot resolve Empty security considerations on a user-generated content endpoint
@mscbot resolve The client shouldn't be allowed to stall the server for infinite milliseconds (the server should impose a limit)

2023-04-25 00:00 UTC, merged

2023-04-25 12:54 UTC, richvdh commented on proposals/2246-asynchronous-uploads.md
> +#### `PUT /_matrix/media/v3/upload/{serverName}/{mediaId}`
Is the intention that this endpoint support the `content-type` header and `filename` query parameter, as https://spec.matrix.org/v1.6/client-server-api/#post_matrixmediav3upload does? It looks like the sample implementation at https://github.com/turt2live/matrix-media-repo/pull/364/files#diff-3ddbc505e50723b8440369eef4dc1fa055026668151b1dbecbd1725fc6765727 does, but this isn't mentioned in the MSC.

2023-04-25 12:59 UTC, tulir commented on proposals/2246-asynchronous-uploads.md
> +#### `PUT /_matrix/media/v3/upload/{serverName}/{mediaId}`
Yes. In the future those details could be moved to the /create call request body, but that wasn't defined here

2023-04-25 14:15 UTC, richvdh commented
Spec PR: https://github.com/matrix-org/matrix-spec/pull/1499

2023-05-03 15:49 UTC, turt2live commented
Merged 🎉

2023-10-17 03:53 UTC, tezlm commented
I know I'm *very* late, but it's surprising that nobody mentioned [tus](https://tus.io/) yet, which allows for resumable file uploads. Since the core is headers + `PATCH` it can luckily be retrofitted into matrix in a future msc, if anyone wants it.

2023-11-21 17:12 UTC, sumnerevans commented
For future code sleuths:

Async uploads PR: https://github.com/matrix-org/synapse/pull/15503

Released in Synapse:
* https://github.com/matrix-org/synapse/releases/tag/v1.97.0rc1