[WIP] MSC2249: Require users to have visibility on an event when submitting reports
matrix-org/matrix-spec-proposals pull request #2249
Opened 2019-08-27 12:52 UTC by Half-Shot

This fixes #2227

2021-04-29 15:32 UTC, Half-Shot commented
This is no longer in WIP

2021-04-29 15:45 UTC, erkinalp requested changes

2021-04-29 15:45 UTC, erkinalp commented on proposals/2249-report-require-joined.md
> +```
````suggestion
The `/rooms/{roomId}/report/{eventId}` endpoint should check to see if the authenticated user
is joined to the room in any point of history that the user could retrieve the event to be reported.
the room does not exist, the server should respond with:

```json
{
    "errcode": "M_FORBIDDEN",
    "error": "The room does not exist, or you could not have seen the event in question."
}
```
````

2021-04-29 15:55 UTC, Half-Shot commented on proposals/2249-report-require-joined.md
> +```
So the reason for this requirement is that:
- I couldn't think of a valid use case to report an event of a room you've left/been banned from
- In theory most impls will be caching the latest membership, so it's a useful short circuit to avoid spelunking the history of the room to find out if you were joined 10 years ago.

There might be an argument that you want to report an event in a room you were kicked/banned from, but it feels like a useful report coming out of that situation is likely to be low. If enough people are in favor, we could make it up to the impl to decide at what level they would accept reports from.

2021-04-29 19:28 UTC, uhoreg commented on proposals/XXXX-appservice-login.md
> +# MSC0000: Provide authentication method for appservice users
This file seems to have decided to come along for the ride.

2021-04-29 19:32 UTC, uhoreg commented on proposals/2249-report-require-joined.md
> +Care should be taken not to give away information inadvertently by responding different error codes depending
```suggestion
Care should be taken not to give away information inadvertently by responding with different error codes depending
```

2021-05-03 20:37 UTC, erkinalp commented on proposals/2249-report-require-joined.md
> +```
> There might be an argument that you want to report an event in a room you were kicked/banned from, but it feels like a useful report coming out of that situation is likely to be low.

I personally experienced such an issue. Can DM you the details.

2021-05-03 20:53 UTC, Half-Shot commented on proposals/XXXX-appservice-login.md
> +# MSC0000: Provide authentication method for appservice users
E_TOO_MANY_PROPOSALs

2021-05-03 21:00 UTC, Half-Shot commented on proposals/2249-report-require-joined.md
> +```
Well, the details aren't so important but if it's a common use case that you want to report events that you can *no longer* read then perhaps the short circuit isn't worth the trouble.

2021-06-11 08:04 UTC, erkinalp commented on proposals/XXXX-appservice-login.md
> +# MSC0000: Provide authentication method for appservice users
"MSC 2249, Part 2: Provide authentication method for appservice users"

2023-03-03 19:15 UTC, turt2live commented on proposals/2249-report-require-joined.md
> +    "errcode": "M_FORBIDDEN",
Synapse has decided to use `M_NOT_FOUND`/404 for both errors, which sounds equally correct.

https://github.com/matrix-org/synapse/pull/13779

2023-03-03 19:16 UTC, turt2live commented
Given synapse has [accidentally implemented](https://github.com/matrix-org/synapse/pull/13779) this MSC, and it makes sense, we should just accept it.

@mscbot fcp merge

2023-03-12 21:28 UTC, Half-Shot commented on proposals/2249-report-require-joined.md
> +    "errcode": "M_FORBIDDEN",
works for me!

2023-03-12 21:32 UTC, Half-Shot commented
This was a blast from the past, I can't believe it's been nearly 4 years...

2023-05-07 21:40 UTC, merged

2023-08-15 06:18 UTC, turt2live commented
Merged 🎉