Hidden read receipts
matrix-org/matrix-spec-proposals pull request #2285
Opened 2019-09-06 04:08 UTC by turt2live

[Rendered](https://github.com/matrix-org/matrix-doc/blob/travis/msc/hidden-read-receipts/proposals/2285-hidden-read-receipts.md)

2019-09-06 04:16 UTC, turt2live commented
Implementations:
* https://github.com/matrix-org/matrix-js-sdk/pull/1028
* https://github.com/matrix-org/matrix-react-sdk/pull/3395
* https://github.com/matrix-org/synapse/pull/5990

2019-09-07 01:32 UTC, turt2live commented
@joepie91 in general, please use line comments so conversation isn't lost. However, I hope i can respond in one comment here:

This is already partially identified in the security considerations section (if you swap out "ignore" for "unaware", at least). The expectation is that this lands in a version of the specification, which is where the MUST takes effect - servers would be non-compliant if they ignored the flag and advertised that they supported the version.

2019-09-09 10:00 UTC, ara4n commented
@mscbot fcp merge

2019-09-10 09:32 UTC, joepie91 commented
@turt2live I was hoping that the 'review' feature would produce a thread like a line comment would (since this is a general comment, not tied to a specific line), but apparently not :)

Given that it's a MUST, I would propose explicitly adding a note to the spec that says "this flag did not exist before version X of the spec, and all read receipts are assumed to be visible there", so that clients which implement multiple spec versions can take this into account in how they design their UI.

I'm not sure whether such an "add note to the spec" point would be part of the MSC itself, or tracked separately.

2019-09-10 14:29 UTC, turt2live commented
It would be done at spec PR time - MSCs generally don't try and influence the exact wording of the spec given they are more informal documents than the formal spec.

2019-09-10 17:07 UTC, turt2live commented
@mscbot concern There should be an account data config option for this so clients can honour it always.

2019-09-10 19:01 UTC, uhoreg commented on proposals/2285-hidden-read-receipts.md
> +When sending a `m.read` receipt, a `m.hidden: true` flag can be included (optional) to tell
I always imagined that this would be implemented by having a separate receipt/marker type, say `m.read.private`, which only the user would see.  Having an `m.hidden` flag works, although the body of the `POST /rooms/.../read_markers` request looks a bit weird to me, with some keys meaning "set this marker to this event" and some flags meaning "add this flag to one of the markers".  So it's a bit non-ideal from my POV, but I won't push against it unless other people feel the same way too.

2019-09-10 19:05 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +When sending a `m.read` receipt, a `m.hidden: true` flag can be included (optional) to tell
I would tend to agree with using a different event type, or possibly a different API endpoint entirely (as originally proposed somewhere in the history of issues). However, adding a flag does make the implementation for homeservers a lot easier: this is something they can tack on during development or after they've been well-established (like Synapse). 

I definitely agree that the read marker interface is not great, so suggestions for naming there would be great. I went with consistency rather than changing the name for now though.

2019-09-24 17:56 UTC, turt2live commented
I'm cancelling FCP on this because I don't think it's ready for that yet, and I want to add a few more things to it:

@mscbot fcp cancel

2020-05-20 14:36 UTC, ludwigbald commented
I'm not sure how to add an inline comment, so here are my thoughts in comment form:
For both ease-of-use and ease-of-privacy reasons, this should be an account setting and not be configurable per room.
I think it's bad UX if the read marker jumps. If it doesn't have any purpose, we should hide it. Making "I don't send read receipts" a part of your public profile makes it easy for others to understand why you seem to never read their messages. This would depend on #489, I guess.

Also, i.m.o this should come together with #2558. If you don't want me to know whether you read my message, I at least want to know whether you have received it. (I want to know if something went wrong.)

2020-05-20 14:42 UTC, ludwigbald commented on proposals/2285-hidden-read-receipts.md
> +perceived today.
For both ease-of-use and ease-of-privacy reasons, this should be an account setting and not be configurable per room.
I think it's bad UX if the read marker jumps. If it doesn't have any purpose, we should hide it. Making "I don't send read receipts" a part of your public profile makes it easy for others to understand why you seem to never read their messages. This would depend on #489, I guess.

Also, i.m.o this should come together with #2558. If you don't want me to know whether you read my message, I at least want to know whether you have received it. (I want to know if something went wrong.)

2020-05-24 11:36 UTC, tulir commented on proposals/2285-hidden-read-receipts.md
> +perceived today.
> If you don't want me to know whether you read my message, I at least want to know whether you have received it.

The people who don't want you to know if you read a message very likely also don't want their devices to leak info of when they receive a message.

2020-05-24 11:39 UTC, tulir commented on proposals/2285-hidden-read-receipts.md
> +perceived today.
> For both ease-of-use and ease-of-privacy reasons, this should be an account setting and not be configurable per room.

While clients should primarily present it as an account setting, it should be per-room on the account level so clients that want to provide more granular privacy options could do so (it also makes more sense on the per-room level the way this proposal suggests)

2020-05-24 12:09 UTC, ludwigbald commented on proposals/2285-hidden-read-receipts.md
> +perceived today.
> > For both ease-of-use and ease-of-privacy reasons, this should be an account setting and not be configurable per room.
> 
> While clients should primarily present it as an account setting, it should be per-room on the protocol level so clients that want to provide more granular privacy options could do so (it also makes more sense on the per-room level the way this proposal suggests)

Okay, I could live with that. Maybe an account setting that specifies the default, with per-room overrides?

in general, the whole proposal seems very hacky to me. We shouldn't have to send weird hidden dummy events.

2020-05-24 12:15 UTC, tulir commented on proposals/2285-hidden-read-receipts.md
> +perceived today.
Yeah, defaults with per-room overrides is what Riot does for most settings

> in general, the whole proposal seems very hacky to me. We shouldn't have to send weird hidden dummy events.

They aren't weird hidden dummy events, they're needed to sync read status across your own devices even if you don't want other people to know what you've read

2020-06-07 17:22 UTC, dkasak commented on proposals/2285-hidden-read-receipts.md
> +When sending a `m.read` receipt, a `m.hidden: true` flag can be included (optional) to tell
I concur that the `read_markers` body looks weird to me too. I also find the conflation between "read receipts" and "read markers of type `m.read`" a bit odd, if I understood correctly that those concepts are equivalent. Primarily, this is because the endpoint is called `read_markers` instead of mentioning receipts. From my experience with the ecosystem, there is a lot of confusion around this.

It seems to me that there's a need for three different and rather unconnected features:

1. Read markers: a *private* bookmark to indicate the point up to which you've processed the discussion. Since you haven't processed anything after the read marker, you may want to go back to it later and the read marker allows you to do this.
2. Read receipts: *public* indicators of what you've seen last to inform participants that you have seen it.
3. "Hidden" read receipts: purely internal, and hence *private* mechanism to synchronize "unread messages" indicators between a user's devices (while still retaining the ability from 1 as a separate concept).

When stated like this, 3 does not have much in common with 2, except that they are both a type of receipt and that a receipt of type 2 also serves the purpose of a type 3 receipt (but not vice versa).

This makes me wonder why a separate read marker API was added for the RM instead of considering the RM as just another receipt type and using the `/rooms/.../receipt/RECEIPT_TYPE/EVENT_ID` endpoint with a different `RECEIPT_TYPE`. Is it simply to be able to set them both in a single HTTP call?

In any case, I think it would be much preferable if a new `RECEIPT_TYPE` was added for 3, such as the `m.read.private` as suggested by @uhoreg. The `read_markers` endpoint would then also get an analogous key and would continue to serve the purpose of an endpoint for setting receipt-like things in bulk.

This would also solve the issue raised in [an earlier comment](https://github.com/matrix-org/matrix-doc/pull/2285#pullrequestreview-285145506) by making it fail closed: a newer client configured not to send out read receipts would start sending `m.read.private` exclusively, but an older server would simply ignore such a receipt type (or `read_markers` key), which would prevent information leaks.

2020-07-03 12:46 UTC, Sorunome commented on proposals/2285-hidden-read-receipts.md
> +# MSC2285: Hidden read receipts
How about a way to enable them being hidden globally for your entire account? That way you don't have to specify `hidden` every time, which also means that clients who aren't aware of this option won't leak unwanted read receipts.

2021-05-21 08:16 UTC, timokoesters commented on proposals/2285-hidden-read-receipts.md
> +When sending a `m.read` receipt, a `m.hidden: true` flag can be included (optional) to tell
I can confirm that these three different types of read receipts is also how I understood the spec when implementing it in Conduit. 

1. Read markers (an event in account_data, also called fully_read). Can only be set with /read_markers
2. Public read receipts (read receipts sent to other users). Can be set with /receipt or /read_markers
3. Private read receipts (used to synchronize notification counts between devices). Can be set with /receipt or /read_markers. Currently this type is closely coupled with 2, because it uses the same receipt type.

I recommend that we add a "hidden" field to the /read_markers and /receipt requests. If it is true, the request will not touch the public read receipt (2) and only update the private read receipt (3).

This results in the intended functionality with very few required spec/server changes (at least for conduit). A new receipt_type would mean that a lot more data has to be transferred to update the private read receipt

2021-05-21 08:56 UTC, erciccione commented
Please unlock #2527. Being forced to send read receipt is one of the most privacy-invasive and annoying characteristic of matrix and the community should be allowed to ask questions and discuss possible solutions. Especially now that this PR has been converted back to draft, so things will be even slower then they used to be (and this has been an issue **for 5 years**).

2021-05-21 08:57 UTC, t3chguy commented
![image](https://user-images.githubusercontent.com/2403652/119111466-007ce300-ba1b-11eb-9fd3-d02e982e35eb.png)


That looks entirely unrelated @erciccione?

2021-05-21 09:00 UTC, erciccione commented
@t3chguy sorry. I pointed to the wrong issue, i meant #https://github.com/vector-im/element-web/issues/2527. Correcting my message now.

2021-05-21 09:03 UTC, t3chguy commented
This doesn't have a Synapse implementation, not even behind an experimental feature, so adding support for it in Element would do absolutely nothing until that is complete.

2021-05-21 09:09 UTC, erciccione commented
> adding support for it in Element would do absolutely nothing

I'm not asking to add support for Element. I'm asking to unlock the issue i pointed to. It was locked, but seems to be the only place where the problem of the read receipt being always on have been tracked and can be discussed. Maybe would make sense to have a synapse/matrix specific issue.

2021-05-21 09:10 UTC, t3chguy commented
It is best to organise comments on a spec issue, so that its not just visible to those following a single client implementation

2021-05-22 15:32 UTC, timokoesters commented on proposals/2285-hidden-read-receipts.md
> +# MSC2285: Hidden read receipts
Do you think this can be designed in a second MSC so this one can be accepted sooner?

2021-05-22 15:35 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +# MSC2285: Hidden read receipts
Also, I would personally prefer to have an option to disable the per-room. This would make it impossible

2021-05-22 16:28 UTC, NinjaTrappeur commented
As agreed on #matrix-spec, I rebased the element PR (that has now been reverted) there: https://github.com/NinjaTrappeur/matrix-react-sdk/tree/nin-add-hidden-read-receipts

The matrix-js-sdk PR has not been reverted and is still part of the codebase. We're good on that front.

For the record, @turt2live requested to add a proper backend support detection through `/version` on #matrix-spec. I'm planning to implement that this week. I need to dig a bit deeper in the codebase first.

2021-06-15 05:16 UTC, erkinalp requested changes

2021-06-15 05:16 UTC, erkinalp commented on proposals/2285-hidden-read-receipts.md
> +Servers MUST NOT send hidden receipts over federation to any server.
To prevent user from being nagged to disable this privacy related feature other users, other
users should still see a public read receipt pointing to sender's latest event when the sender
chooses to hide own read receipt:
```suggestion
Servers processing read receipts MUST NOT send hidden receipts to any other user than the sender.
Servers MUST NOT send hidden receipts over federation to any server. Instead, they MUST emulate
a public read receipt pointing to the latest room event sent by the said sender for other users and servers,
OR the event pointed by the latest public read receipt by the user, whichever points to a later event.
```

2021-06-15 06:45 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +Servers MUST NOT send hidden receipts over federation to any server.
I feel this defeats the purpose of the MSC. Do you have any information on what your suggestion actually means?

2021-06-15 07:49 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +Servers MUST NOT send hidden receipts over federation to any server.
I think I am overlooking something - how does this defeat the purpose of the MSC?

2021-06-15 08:18 UTC, erkinalp commented on proposals/2285-hidden-read-receipts.md
> +Servers MUST NOT send hidden receipts over federation to any server.
> I feel this defeats the purpose of the MSC.

This change is designed prevent from detection of whether one prefers public or hidden read receipts, without leaking any additional information from the sender. Without this change, other users and servers will easily be able to see that preference, which would cause nagging by room mods and/or server operators (including other servers in the federation that the rooms user joins federate).

2021-07-07 06:08 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +Servers MUST NOT send hidden receipts over federation to any server.
This was discussed briefly in #matrix-spec and it seems there is a misunderstanding in what this MSC does. The MSC just blocks propagation of receipts to allow notifications to work properly while not alerting other users to the user's read-up-to status. The MSC does not block implicit read receipts as currently required by the spec.

The suggestion appears to be regurgitating the spec in an awkward way, so I'm going to decline to add it. At first, it appeared as though the suggestion was to send something down with some sort of metadata to make it not work on the receiving side, which is not the case.

2021-07-15 07:47 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +for identifiers. `m.hidden` becomes `org.matrix.msc2885.hidden` for example.
```suggestion
for identifiers. `m.hidden` becomes `org.matrix.msc2285.hidden` for example.
```

2021-07-28 11:49 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +# MSC2285: Hidden read receipts
@Sorunome, this sounds like mostly the same point as https://github.com/matrix-org/matrix-doc/pull/2285#discussion_r428069098. Is there any reason that this is a separate thread/do you still think should be global?

2021-07-28 14:45 UTC, babolivier commented
Synapse implementation has been merged: https://github.com/matrix-org/synapse/pull/10413 (I'll edit the list of implems above since it's linking to the wrong PR)

2021-08-10 17:32 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +When sending a `m.read` receipt, a `m.hidden: true` flag can be included (optional) to tell
What are people's feelings on this? Judging from the reactions, it's not obviously clear if a new event type is preferred or if the MSC is fine as-is. It's somewhat worth noting that the Synapse implementation passed review, which is an indicator to me that the proposed flag-based design is at least suitable for the problem space.

2021-08-10 17:34 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +perceived today.
Have people's opinions changed on this? Judging from the reactions, it's not immediately clear if people are demanding this become an account data thing or if a client-centric approach is okay. Personally, I'd prefer to keep it client-centric so I can have a client which is extremely privacy preserving for the cases I need that, but generally have my read receipts be out there.

2021-08-10 17:43 UTC, turt2live commented
I'd like to see this enabled on matrix.org and used by humans before this enters FCP, but overall I think this is largely ready to go. If people have blocking comments on the existing threads, please raise them.

2021-08-24 16:43 UTC, anoadragon453 commented on proposals/2285-hidden-read-receipts.md
> +perceived today.
Why not both? Could we spec an account data boolean which privacy-conscious clients simply choose to ignore?

2021-08-25 02:15 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +perceived today.
Both isn't impossible, but it would imply that we can't make a decision. For simplicity's sake taking one approach over the other would be preferred, whatever that may be.

I'm not seeing a lot of opposition to the client-centric approach though.

2021-08-25 02:23 UTC, aaronraimist commented on proposals/2285-hidden-read-receipts.md
> +perceived today.
I think both would be better. I personally would like to be able to sync this setting between all my devices. If Element were to add a line in `im.vector.web.settings` to sync it then it might as well just be a specced field in account data so it applies to all clients.

2021-08-25 06:18 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +perceived today.
To be honest, if this were to be an account data field, I'd like it to be per-room/per-space/per-DMs/per-whatever and that is another problem in itself... So I think we should leave account data out for the moment and figure out something more complex and re-usable (unless there already is something that I am not aware of...)

2021-10-04 01:32 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +When sending a `m.read` receipt, a `m.hidden: true` flag can be included (optional) to tell
I'm taking silence to mean that people are okay with seeing this in a future MSC. In particular, I can see the sort of suggestion for server-side handling being a good addition to per-receipt handling which would make for a very easy MSC down the line.

2021-10-04 01:34 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +perceived today.
Per https://github.com/matrix-org/matrix-doc/pull/2285/files#r720985566 it sounds a bit like there's benefit in a server-side setting for this, though I still don't believe that this MSC should be the one to introduce it. It'd certainly be a welcome addition, however.

2021-10-04 01:35 UTC, turt2live commented
I believe the threads are resolved though have left them open because they have important context not captured in the MSC prose. 

This MSC is in desperate need of opinion from the SCT and has met all criteria for FCP (people have been using it without complaint), so:

@mscbot fcp merge

2021-10-05 16:01 UTC, richvdh commented
> I believe the threads are resolved though have left them open because they have important context not captured in the MSC prose.

shouldn't the document of the MSC capture all the necessary context? A huge github PR is not an easy place to try to gather context.

2021-10-26 16:51 UTC, richvdh submitted a review, later dismissed

2021-11-09 17:30 UTC, turt2live commented
@mscbot concern This needs reviews to be actioned

2021-11-27 19:45 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +When sending a `m.read` receipt, a `m.hidden: true` flag can be included (optional) to tell
We had a [short discussion](https://matrix.to/#/!NasysSDfxKxZBzJJoE:matrix.org/$EqIPOFfzAHSteuujF0-FqSxOKdGOHZp53igGoWNuJmg?via=matrix.org&via=libera.chat&via=envs.net) about this in #matrix-spec with @timokoesters and concluded that we don't really understand why we have `/receipt` and we think that since we have a way to do this in bulk using `/read_markers` we could deprecate `/receipt` to not duplicate functionality. (maybe I've missed something, feel free to add to this)

AFAICT, that would lead to one of three solutions:

+ Separate `receiptType`
+ A new bulk endpoint which would allow for adding `hidden` flag to a specific `receiptType` (`m.read` in this case)
+ A query param flag to `/read_markers` - I don't like this as the flag should only apply to `m.read` not to `m.fully_read`

2022-01-08 09:55 UTC, Sorunome commented on proposals/2285-hidden-read-receipts.md
> +# MSC2285: Hidden read receipts
Not sure if it has been considered here already, or if it is out-of-scope for this MSC: It might make sense to add an endpoint to change the default behaviour per-user of `m.hidden`, so that read receipts of clients who do not implement this behaviour yet can still be hidden

2022-03-02 13:58 UTC, SimonBrandner commented
> Any update on this? Looks like things got stuck more than a year ago, but this is a very needed feature.

The MSC has unresolved concerns, so it is stuck until the author (or someone else) resolves them :/

2022-03-03 11:31 UTC, dkasak commented on proposals/2285-hidden-read-receipts.md
> +When sending a `m.read` receipt, a `m.hidden: true` flag can be included (optional) to tell
After some more thought, I would strongly prefer that we encode this new kind of private receipt as a separate receipt type, that is `m.read.private`. In general I think the routing decision should be encoded in the type itself so that there is less room for mistakes and information leakage.

The problem of bulk update is a separate one. Setting only a single type and bulk setting several or all types at once should both be supported.

Read markers and receipts are increasingly sounding to me as instances of the same general concept with differing routing decisions. Even the spec [uses the word "marker"](https://spec.matrix.org/v1.2/client-server-api/#receipts) when talking about receipts. So, indeed, why do we have two different APIs for this?

So to resolve the current impasse, I propose that we:

1. Add `m.read.private` as a new receipt type to the `/receipt` API.
2. Add `m.read.private` as an optional JSON key to the `/read_markers` API, similar to `m.read`.
3. Make the `m.fully_read` JSON key in `/read_markers` optional.

This preserves the ability to bulk update all types of receipts. Then, in a future MSC:

1. Duplicate the `POST /_matrix/client/v3/rooms/{roomId}/receipt/{receiptType}/{eventId}` endpoint as `POST /_matrix/client/v3/rooms/{roomId}/read_markers/{receiptType}/{eventId}`. (Alternatively, duplicate `POST /_matrix/client/v3/rooms/{roomId}/read_markers` as `POST /_matrix/client/v3/rooms/{roomId}/receipt`.)
2. Deprecate the `/_matrix/client/v3/rooms/{roomId}/receipt.*` endpoints. (Alternatively, deprecate the `/_matrix/client/v3/rooms/{roomId}/read_markers.*` endpoints.)

If all JSON keys of the dict payload are made optional, point 1 may be unnecessary.

2022-03-03 21:08 UTC, turt2live commented
@mscbot fcp cancel

2022-03-03 21:57 UTC, turt2live commented
For the subscribers: This MSC has changed dramatically since it was originally opened. Please take another look at it and leave fresh threads if you have feedback - all existing threads have been marked resolved.

2022-03-10 05:35 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +
```suggestion
The MSC also proposes adding `m.fully_read` as a possible `receipType` for `/receipt`.

```

2022-04-29 17:22 UTC, clokep commented on proposals/2285-hidden-read-receipts.md
> +should also be moved.
From the Synapse review (matrix-org/synapse#12168) I think we tweaked this logic slightly such that both receipts can co-exist in a room, but the "latest" one is what is actually used. So if you have events `A`, `B`, and `C` with a private receipt to `B`, then send a public receipt to `C` your private receipt doesn't really matter anymore since you have a later one.

I suspect the idea behind this text is actually that `m.read.private` clears notifications in the same way as ` m.read`?

2022-04-30 17:38 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +should also be moved.
Does this sound good?

```suggestion
Both `m.read` and `m.read.private` clear notifications in the same way. If the
user sent two receipts into a room, the later one should be the one that decides
the notification count.

If the user has `m.read` and `m.read.private` receipts at the same event, the
`m.read` receipt takes precedence - an `m.read.private` receipt sent to an event
that already has `m.read`, shouldn't move the user's receipt up in the timeline
from the perspective of other users.
```

2022-05-04 12:46 UTC, clokep commented on proposals/2285-hidden-read-receipts.md
> +should also be moved.
@SimonBrandner:

> If the user sent two receipts into a room, the latter one should be the one that decides the notification count.

Is "latter" a typo (should it be "later") or does it refer to `m.read.private` taking precedence for notifications?

2022-05-04 14:33 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +should also be moved.
I meant _later_ - thank you for the catch! I've updated my comment

2022-05-24 14:29 UTC, clokep commented on proposals/2285-hidden-read-receipts.md
> +# MSC2285: Private read receipts
My understanding is that as of matrix-org/synapse#12168 and matrix-org/matrix-js-sdk#2221 the MSC matches the implementations.

2022-05-27 00:26 UTC, deepbluev7 commented on proposals/2285-hidden-read-receipts.md
> +stable) or the presence of a `org.matrix.msc2285` flag in  `unstable_features`
Could we get a new unstable flag? Otherwise notification clearing just breaks on older servers with no way to tell users why.

2022-05-27 00:27 UTC, deepbluev7 commented on proposals/2285-hidden-read-receipts.md
> +stable) or the presence of a `org.matrix.msc2285` flag in  `unstable_features`
See https://github.com/Nheko-Reborn/mtxclient/issues/76

2022-05-27 08:43 UTC, t3chguy commented on proposals/2285-hidden-read-receipts.md
> +stable) or the presence of a `org.matrix.msc2285` flag in  `unstable_features`
> Otherwise notification clearing just breaks on older servers with no way to tell users why.

Right next to the experimental flag they should have a note "If your server isn't also running experimental code then this experiment may yield bad results" - unless of course the client is using unstable MSCs to back "stable" features.

2022-05-27 09:54 UTC, deepbluev7 commented on proposals/2285-hidden-read-receipts.md
> +stable) or the presence of a `org.matrix.msc2285` flag in  `unstable_features`
Preferably a client could also show if a server supports the MSC. For that reasons MSCs usually update the unstable flag, when there is a major change it the MSC.

2022-05-27 14:34 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +stable) or the presence of a `org.matrix.msc2285` flag in  `unstable_features`
I did consider updating the unstable flag but decided against it since the MSC is rather small and experimental features are sort of expected to break... I wonder if it's still worth it - we could update it but for it to work we would have to wait for one more release cycle, while now if you're up to date everything should work

2022-05-27 16:21 UTC, deepbluev7 commented on proposals/2285-hidden-read-receipts.md
> +stable) or the presence of a `org.matrix.msc2285` flag in  `unstable_features`
I guess I'll just add a warning then, that we have no way to check for server support, so it might be broken.

2022-05-27 16:33 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +stable) or the presence of a `org.matrix.msc2285` flag in  `unstable_features`
> I guess I'll just add a warning then, that we have no way to check for server support, so it might be broken.

Sorry for not handling this better

2022-05-27 16:36 UTC, deepbluev7 commented on proposals/2285-hidden-read-receipts.md
> +stable) or the presence of a `org.matrix.msc2285` flag in  `unstable_features`
No worries, I could have noticed that earlier. And it is an MSC after all :D

2022-06-13 15:56 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +stable) or the presence of a `org.matrix.msc2285` flag in  `unstable_features`
Spec-wise we're supposed to update the unstable flag, however for this case I don't think it's needed necessarily. It's a good test to ensure clients aren't overly relying on unstable functionality.

2022-06-13 15:57 UTC, turt2live commented
This seems ready to go, barring some light clarifications.

@mscbot fcp merge

2022-06-13 21:04 UTC, deepbluev7 commented on proposals/2285-hidden-read-receipts.md
> +from the perspective of other users.
Is there a way for the client to tell, which one is higher, when they come down /sync?

2022-06-14 11:30 UTC, clokep commented on proposals/2285-hidden-read-receipts.md
> +from the perspective of other users.
Only the latest one is received down sync, not both. The latest one essentially overwrites the earlier one.

2022-06-15 18:42 UTC, deepbluev7 commented on proposals/2285-hidden-read-receipts.md
> +from the perspective of other users.
That applies to one receipt type, but if you have multiple receipt types, do you still only get one of them in /sync? Or do you get both of them and then just need to store both and check which one is later, if you have the full range of events locally?

I guess you can always account for both when evaluating notifications locally, but this added actually quite some complexity that I didn't expect, since I can't simplify it down to one marker. I basically can't go "okay, the marker points to this events, so the event after it has no read marker". I now need to find both and hope they are in the same continuous chunk.

It is not such a big issue, but slightly more annoying than the one receipt, that was hidden or not, which we had before.

2022-06-16 13:58 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +from the perspective of other users.
I am not completely sure I follow - I am pretty sure we send both `m.read` and `m.read.private` down `/sync`. The client then has two receipt types to worry about which adds a bit of complexity when looking for things such as event read-up to - an example of the handling for that is https://github.com/matrix-org/matrix-js-sdk/pull/2221

2022-06-17 02:00 UTC, deepbluev7 commented on proposals/2285-hidden-read-receipts.md
> +from the perspective of other users.
Basically if you have a timeline fragment `A->B->C->D->E`, if your latest `m.read` points at C, you can't know if the later message D is read, unless you know if `m.read.private` points to a previous or later event. I.e. if your fragment currently available to the client is `A->B->C->D`, but `m.read.private` points at `E`, you need to paginate forward until `E` to know for sure, if `D` is read or not. But `m.read.private` might point at `A`, in which case your forward pagination might never give you any knowledge about the private read receipt, since you needed to paginate backwards.

Now in a typical /sync scenario, that isn't too bad, since you have all the newest messages. And usually only then you care about the read receipt.

But some clients implement opening a room at where the user has their read receipt. Now before you could just fetch the context of your latest read receipt. Now you can't do that, since you wouldn't know which fragment comes first for either receipt. Arguably clients should be using the readmarker in this case anyway.

Nonetheless, it would probably be a good idea, if the server could annotate read receipts with some additional information if a read receipt is ordered before or after the other read receipt type. Although now that I think of it, a client can probably just use the timestamp to order read receipts in most cases. I guess it depends on if clients can trust the timestamps to be a reliable way to order read receipts.

2022-06-17 11:18 UTC, clokep commented on proposals/2285-hidden-read-receipts.md
> +from the perspective of other users.
Synapse has a couple of tests that seem to assert only one will get returned for a particular event:

https://github.com/matrix-org/synapse/blob/c52abc1cfdd9e5480cdb4a03d626fe61cacc6573/tests/rest/client/test_sync.py#L411-L457

Which doesn't really answer the question.

There is logic to handle the ordering of receipts (see `get_receipts_for_user_with_orderings`), but that doesn't seem to get used by `/sync`?

2022-06-17 11:34 UTC, MTRNord commented on proposals/2285-hidden-read-receipts.md
> +# MSC2285: Private read receipts
(this comment mostly exists as down votes without comment are frowned upon by some people of the spec core team and previously lead to discussions.)

I personally am in favor of seperating the notification counter from the read marker however I strongly am against having private read receipts.

This has both social and technical reasons.

1. Socially I strongly believe it is good etiquette to have read markers to prevent people from asking multiple times if someone doesn't reply for whatever reason. Surely another solution would be to expect them to write "sorry read but can't reply" but at that point the user is effectively doing what the system was supposed to be solving here. Also most people are too lazy to do this as they expect the system to do it for them.
Also I am aware that email and other email style systems do not do read markers. However I believe they have a different type of audience and different expectations associated with them. Matrix is primarily an _Instant_ Messaging app. Hence imho there should also be instant feedback. While email is an async medium where a reply is expected to only happen in "working hours". Is this a social issue? Maybe. But I don't believe this is a problem matrix spec should be solving which the msc seems to try.

2. On the technical side I believe that we need those read receipts as you may have federation problems which aren't uncommon which you wouldn't detect without read receipts leading to silently lost messages. They are currently they only indicator we have apart from manually running the federation tester to check if there is a broken or half broken fed. This problem could likely be solved by adding a better indicator (aka a HS self health check).

2022-06-17 15:23 UTC, deepbluev7 commented on proposals/2285-hidden-read-receipts.md
> +# MSC2285: Private read receipts
According to German (and probably EU) data protection laws, you are required to collect and send the minimal amount of data by default. This is currently not possible. While you can hide your online status, it is broadcasted to everyone everytime you open a room. While this can be nice with your friends, it is not nice when communicating with your employer, doctor or other people you don't consider your friend or who you don't want to know, when you are awake. For some people it is also very uncomfortable to read a message and knowing the other party can see that, but they might not have the energy right now to reply. As such it is important to give people the option in my opinion. Heck, clients can go as far and have different options for groups and DMs.

For context, the upcoming TI messenger specification seems to require hidden read receipts by default too: https://github.com/gematik/api-ti-messenger/tree/main/Vorabveroeffentlichungen/TIM_1.1

Matrix already gives away some metadata, giving control to the user is important imo. You shouldn't be forced to share your personal data. :3

2022-06-28 13:18 UTC, richvdh commented on proposals/2285-hidden-read-receipts.md
> +This MSC proposes adding a new `receiptType` of `m.read.private`. This
It's really helpful for people reading an MSC if you provide links to relevant existing spec, to provide context. In this case the relevant context appears to be https://spec.matrix.org/v1.3/client-server-api/#receipts.

2022-06-28 13:18 UTC, richvdh commented on proposals/2285-hidden-read-receipts.md
> +can make a POST request such as this.
```suggestion
Alternatively, the client can move the user's `m.fully_read` marker and/or 
`m.read` receipt at the same time as `m.read.private` by making a POST
request to the [`/read_markers` endpoint](https://spec.matrix.org/v1.3/client-server-api/#post_matrixclientv3roomsroomidread_markers). For example:
```

2022-06-28 13:18 UTC, richvdh commented on proposals/2285-hidden-read-receipts.md
> +    "m.read.private": "$123",
```suggestion
    "m.read.private": "$123"
```

2022-06-28 13:18 UTC, richvdh commented on proposals/2285-hidden-read-receipts.md
> +The `m.read` is now optional as sometimes we only want to send `m.read.private`.
where is it optional? I think you mean `/read_markers`, but please say so.

2022-06-28 13:18 UTC, richvdh commented on proposals/2285-hidden-read-receipts.md
> +other users.
+1; this needs more fleshing out to be reliable.

2022-06-28 13:18 UTC, richvdh commented on proposals/2285-hidden-read-receipts.md
> +on `/versions`. Clients are recommended to check for server support to ensure
Is there an intention to use `m.read.private` as a "stable" feature before it makes it into a released spec version (and that version being fully adopted by servers)? We might need to consider how clients identify support for it if so.

2022-06-28 13:34 UTC, richvdh commented on proposals/2285-hidden-read-receipts.md
> +from the perspective of other users.
Seems like there is some confusion here. It would be good to get this thread resolved.

EW's logic here (https://github.com/matrix-org/matrix-js-sdk/pull/2221/files#diff-1252c1ee1e945dedde8e3e6e96f4b29013a7fc3cd8b83fabc762f2d0add859a8R2356-R2370) seems like it might be good enough? Or do we need the server to annotate RRs with some sort of ordering (if so, what ordering should it use, given it doesn't necessarily have the full event graph, and even if it does there exists only a *partial* ordering between events)?

2022-06-28 14:36 UTC, richvdh commented on proposals/2285-hidden-read-receipts.md
> +POST /_matrix/client/r0/rooms/!a:example.org/receipt/m.read.private/$123
These should really be `/v3/` nowadays btw.

2022-06-28 17:31 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +from the perspective of other users.
Would this work for you?

```
When determining how far a user has read messages, a client should choose the
event that is located later in the client's local timeline; if the client isn't
aware of the event's location in the client's local timeline, a simple
comparison of timestamps should suffice; if timestamp comparison fails, private
read receipt should take precedence.
```

2022-06-28 17:47 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +other users.
I am not sure I completely follow - what is the exact situation here? A client sending `m.read.private` to a server that does not support it? I don't think there is much we can do other than https://github.com/matrix-org/matrix-spec-proposals/pull/2285#discussion_r908466863

2022-07-01 07:51 UTC, tulir commented on proposals/2285-hidden-read-receipts.md
> +on `/versions`. Clients are recommended to check for server support to ensure
MSC3440 (threads) used `org.matrix.msc3440.stable` as an unstable feature until the spec release, not sure if that's considered standard now

2022-07-01 07:54 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +on `/versions`. Clients are recommended to check for server support to ensure
From what T said, it sort of is, so that is what we went with

2022-07-01 08:11 UTC, deepbluev7 commented on proposals/2285-hidden-read-receipts.md
> +from the perspective of other users.
I think it is better to leave the client behaviour unspecified in this case. What you proposed sounds a bit too expensive and I'd rather store all read receipts and check that way. Tbh, I would have preferred if the server sent me what is the latest read receipt, either by bumping the read marker, having only one receipt type or by annotating them. If that is not going to happen, I am fine with just leaving it unspecified as "client needs to figure out what is latest".

2022-07-01 19:08 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +of a suitable spec version in `versions` on `/versions`.
I think this language is from a diagram I provided:
![image](https://user-images.githubusercontent.com/1190097/176955739-7be76c73-41b6-4ae6-b1fe-869078382c0c.png)

"suitable" is my 2am wording for "whatever it was released in".

2022-07-01 19:19 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +While this MSC is considered stable, to determine server support clients can
("merged" is a bit confusing when it can mean two different stages of the MSC process: do we mean to say post-FCP?)

2022-07-01 19:46 UTC, richvdh commented on proposals/2285-hidden-read-receipts.md
> +of a suitable spec version in `versions` on `/versions`.
Ok, speaking to @turt2live:

No, clients are *not* allowed to assume this will be in v1.4. They can check for `org.matrix.msc2285.stable`, but note that server implementations can/should drop that flag at the same time (or soon after) they start advertising the spec version that supports it (probably, but not necessarily, v1.4).

The corollary of that is that a client that want to adopt this feature before it becomes stable must choose between:

 * checking for `org.matrix.msc2285.stable`, and sending public read receipts if that flag is not present, risking read-receipts suddenly becoming public if the server is upgraded to spec vNext before the client.
 * sending private read receipts regardless of whether it sees server-side support for them, and risk notification hell if the server doesn't actually support them.

The first choice might be improved by (a) making sure to accept spec vNext before the server implementation is updated; (b) warning the user if it notices the flag disappearing.

@SimonBrandner: I hope that is clear, if not entirely satisfactory. It would be good to have some words in the MSC reflecting this situation.

2022-07-01 19:48 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +of a suitable spec version in `versions` on `/versions`.
For clarity, the client can also decide that it hates both options and not support private read receipts until it's in a released version of the spec: the safest, but also slowest, option.

2022-07-04 15:43 UTC, richvdh commented
@mscbot resolve what are we doing about the order of read receipts

2022-07-04 15:44 UTC, richvdh commented
@mscbot resolve what are we doing about the order of read receipts?

2022-07-04 15:50 UTC, richvdh commented on proposals/2285-hidden-read-receipts.md
> +If a client has this feature enabled, it is recommended that, in the case of the
recommended? I don't think it has a choice?

2022-07-04 15:50 UTC, richvdh commented on proposals/2285-hidden-read-receipts.md
> +support the MSC) or it should warn the user and start sending public read
this is confusing. what do you mean by "the server not supporting the MSC" vs "the server really does not
support the MSC" ?

2022-07-04 15:57 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +# MSC2285: Private read receipts
@MTRNord second ping - we'd like to resolve this.

2022-07-04 16:48 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +# MSC2285: Private read receipts
(they are possibly on holiday since they're not responding on Matrix either)

2022-07-04 17:15 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +support the MSC) or it should warn the user and start sending public read
Nothing really :sweat_smile: - it makes more sense without it

2022-07-04 17:25 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +# MSC2285: Private read receipts
Having actually read the comment, I believe this to be resolved and so am closing it. The opinion is noted, however with a "direction of Matrix" hat on, I think we need this MSC for chat and non-chat purposes alike.

2022-07-05 16:15 UTC, anoadragon453 commented on proposals/2285-hidden-read-receipts.md
> +`/receipt`.
I don't understand the justification for this change from the current state of the document?

2022-07-05 16:45 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +`/receipt`.
We are essentially making `m.fully_read` into a `receiptType` which it currently is not. This makes the APIs consistent both `/receipt` and `read_markers` now accept it

2022-07-10 17:39 UTC, timokoesters commented on proposals/2285-hidden-read-receipts.md
> +from the perspective of other users.
I think this entire paragraph can be summarized by "If the m.read.private field is not present, it defaults to the value of m.read"

- m.read is the visible read receipt that everyone can see.
- m.read.private is responsible for notification counts

2022-07-11 06:40 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +from the perspective of other users.
> I think this entire paragraph can be summarized by "If the m.read.private field is not present, it defaults to the value of m.read"

I don't think that is exactly the same thing - if there are both, `m.read` takes precedence (that seems to get lost in your version, I think). Also, I think it is preferable to be more explicit here

> * m.read is the visible read receipt that everyone can see.
> * m.read.private is responsible for notification counts

This is not exactly the case: `m.read` is also responsible for notif counts if there is no `m.read.private` event

2022-07-11 08:26 UTC, deepbluev7 commented on proposals/2285-hidden-read-receipts.md
> +from the perspective of other users.
> This is not exactly the case: m.read is also responsible for notif counts if there is no m.read.private event

Which is why the first sentence said it defaults to the value of m.read, if it is not present.

2022-07-12 08:39 UTC, richvdh commented on proposals/2285-hidden-read-receipts.md
> +read receipts.
sorry, but this still isn't accurate.

If the server doesn't support the MSC and the client keeps sending private RRs, then it is not a *risk* but a *certainty* that notifications will not be cleared.

The difficulty is that a client written today has to rely on the presence of `org.matrix.msc2285` or `org.matrix.msc2285.stable` in `unstable_features`, and that at some point servers will stop advertising that. So it is possible that a server supports the MSC without the client being able to know that. You need to call that out, and mention that,  to avoid this problem, clients need to be updated to check the spec version asap after the release of the spec.

2022-07-12 08:56 UTC, timokoesters commented on proposals/2285-hidden-read-receipts.md
> +read receipts.
If the server doesn't support m.read.private and the client sends just that fields, the server will return an error because m.read was a required field previously.

So a client can just try sending m.private and see if it returns an error

2022-07-12 14:02 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +`/receipt`.
There isn't a better reason than consistency. 

The original discussion about this centred around the fact that we have two endpoints that are doing essentially the same thing but not really... The idea was to first make them consistent to make things less confusing and then deprecate `/receipt` as it doesn't have much use (and possibly come up with a replacement for `/read_markers` that would support sending some content).

2022-07-12 14:34 UTC, anoadragon453 commented on proposals/2285-hidden-read-receipts.md
> +`/receipt`.
Ah, I was missing that context. It would be useful to put that in the MSC as a justification :)

2022-07-12 17:37 UTC, richvdh commented on proposals/2285-hidden-read-receipts.md
> +the fact that the way of detecting server support will change.**
I still don't think this really calls out the fact that a client has no reliable way to tell if a server supports private read receipts.

```suggestion
Clients should check for server support before sending private read receipts:
if the server does not support them, then a private read receipt will not clear
any notifications for the user.

The presence of `org.matrix.msc2285` or `org.matrix.msc2285.stable` in
`unstable_features` is a reliable indication that a server supports private read
receipts; however the converse is not true: their absence does not necessarily 
mean that the server does *not* support private read receipts. In particular,
the server may have been updated to a future spec version which includes
private read receipts, and hence removed the `unstable_features` entry.

Therefore, if a client has this feature enabled, but the server does not advertise
support for this MSC in `unstable_features`, 
the client should either keep sending private read receipts with the
risk that notifications will not be clearing, or it should warn the user and
start sending public read receipts instead.

To mitigate this problem, once this MSC gets merged and once it becomes a part of a spec version,
clients should update their implementations as fast as possible to accommodate
the fact that the way of detecting server support will change.

2022-07-12 17:49 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +the fact that the way of detecting server support will change.**
This doesn't seem to take into account that the `versions` field?

2022-07-12 17:56 UTC, dbkr commented on proposals/2285-hidden-read-receipts.md
> +from the perspective of other users.
I'm also a bit confused by what's trying to be said here. Why does it matter which one "takes precedence" if they both point to the same event? What would it mean to take one rather than the other? I think this is just to clarify that setting m.read.private has no effect on the m.read receipt and so can't make your read receipt go backwards or mark a message as unread - if so, I'd maybe just say that?

2022-07-12 18:06 UTC, richvdh commented on proposals/2285-hidden-read-receipts.md
> +the fact that the way of detecting server support will change.**
well, I think it's implicit, but to be explicit we could change the last paragraph to something like...

```
To mitigate this problem, once this MSC gets merged and once it becomes a part of a spec version,
clients should update their implementations to check for the new spec version in the `versions` field.
```

2022-07-12 18:12 UTC, dbkr commented
@mscbot concern wording on which event takes precedence

2022-07-12 18:13 UTC, dbkr commented
@mscbot concern feature detection as per suggested change

2022-07-12 18:18 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +`org.matrix.msc2285.stable` flag once the MSC is part of a spec version.
In an effort to adopt @richvdh's [phrasing](https://github.com/matrix-org/matrix-spec-proposals/pull/2285/files#r919239757) and some feedback internal to the SCT on this:

```suggestion
Clients should check for server support before sending private read receipts:
if the server does not support them, then a private read receipt will not clear
any notifications for the user.

The presence of `org.matrix.msc2285` or `org.matrix.msc2285.stable` in
`unstable_features` is a reliable indication that a server supports private read
receipts; however the converse is not true: their absence does not necessarily
mean that the server does *not* support private read receipts. In particular,
the server may have been updated to a future spec version which includes
private read receipts, and hence removed the `unstable_features` entry.

Therefore, if a client has this feature enabled, but the server does not advertise
support for this MSC in `unstable_features`, the client should either keep sending
private read receipts with the risk that notifications will not be clearing, or it
should warn the user and start sending public read receipts instead.

To mitigate this problem, once this MSC gets merged and once it becomes a part of a
spec version, clients should update their implementations as fast as possible to
accommodate the fact that the way of detecting server support will change: clients
will now be looking for that spec version in `/versions`.

### While the MSC is unstable

During this period, to detect server support clients should check for the
presence of the `org.matrix.msc2285` flag in `unstable_features` on `/versions`.
Clients are also required to use the unstable prefixes (see [unstable
prefix](#unstable-prefix)) during this time.

### Once the MSC is merged but not in a spec version

Once this MSC is merged, but is not yet part of the spec, clients should rely on
the presence of the `org.matrix.msc2285.stable` flag in `unstable_features` to
determine server support. If the flag is present, clients are required to use
stable prefixes (see [unstable prefix](#unstable-prefix)).

### Once the MSC is in a spec version

Once this MSC becomes a part of a spec version, clients should rely on the
presence of the spec version, that supports the MSC, in `versions` on
`/versions`, to determine support. Servers are encouraged to keep the
`org.matrix.msc2285.stable` flag around for a reasonable amount of time
to help smooth over the transition for clients. "Reasonable" is intentionally
left as an implementation detail, however the MSC process currently recommends
*at most* 2 months from the date of spec release.
```

I've essentially copy/pasted @richvdh's comment, made some small edits, skipped over the sections for unstable and stable-but-not-really, and finally edited the spec version section (the last one).

2022-07-12 18:19 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +the fact that the way of detecting server support will change.**
adopted into https://github.com/matrix-org/matrix-spec-proposals/pull/2285/files#r919275805

2022-07-12 18:30 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +`org.matrix.msc2285.stable` flag once the MSC is part of a spec version.
reviewed a bit OOB - committing.

2022-07-12 18:32 UTC, dbkr commented
@mscbot resolve feature detection as per suggested change

2022-07-12 18:55 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +from the perspective of other users.
I've tried to clarify this in 5c891d036307f91c9fdd1d701c65e4070b14c5af - please raise new comments :)

2022-07-13 14:23 UTC, KitsuneRal requested changes

2022-07-13 14:23 UTC, KitsuneRal commented on proposals/2285-hidden-read-receipts.md
> +much responsibility to an existing structure.
I can see how this can be an(other) bikeshedding effort, arriving late to top it off, so feel free to dismiss it if you consider it too much of a change, too late.

I think that one more alternative hasn't been explored - using `/read_markers` (and only `/read_markers`, see above) to send `m.read` receipt with the new value shape - instead of a string with the event id, it would take a dict with the event id and `"m.hidden": true/false`. Given that both `m.read` and `m.read.private` are (should be), in essence, a single entity (I can't imagine a reasonable UX where the two would coexist, rather than one preempting another as the user changes the respective setting in their client), reflecting it in a single thing instead of two things is considerably better. The new value shape would make a compatibility barrier: updated clients can check for the feature support as described here, and  send one of two shapes depending on the homeserver support; non-supporting homeservers would reject the private read receipt even if the client sends it, and non-supporting clients would continue to send the old stringy value, which would still be accepted by homeservers.

Again, I understand that I'm coming and trying half of the MSC now - feel free to dismiss. But I think it's something to be considered before the FCP is over.

2022-07-13 14:26 UTC, KitsuneRal commented
@mscbot concern /receipt assumes the payload to be federatable
@mscbot concern The paragraph in Alternatives about account data is confusing

2022-07-13 14:27 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +be consistent)
Read markers are deliberately not able to control notifications, hence the need for a new receipt type in this case.

2022-07-13 14:30 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +much responsibility to an existing structure.
Read markers and read receipts do coexist in the Element clients - they serve different purposes.

The `m.hidden` sort of approach is what this MSC originally did, and was rejected for doing so. It was too easy for the user's read receipts to accidentally be public.

2022-07-13 15:07 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +should be handled in a separate MSC.
Per other threads: fully read markers are *not* supposed to be used for notifications at all.

2022-07-13 15:29 UTC, timokoesters commented on proposals/2285-hidden-read-receipts.md
> +should be handled in a separate MSC.
Why not? Because clients already use it differently?

2022-07-13 17:40 UTC, KitsuneRal commented on proposals/2285-hidden-read-receipts.md
> +should be handled in a separate MSC.
The concern is that the current text literally says that you'd have to "invent a way to store _per-account settings_ in _account data_", and this is precisely what account data is made for. Maybe the best is to say exactly what you said in the comment: read receipts are _not_ account data and saving some of them in (room) account data does not seem intuitive and consistent - instead of the "would lead to us inventing the way..." part.

2022-07-13 17:45 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +should be handled in a separate MSC.
Ah, I see! I've updated the text. @KitsuneRal, does it make more sense now?

2022-07-13 17:47 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +be consistent)
You can't - the `m.fully_read` field is required (at least in the current spec - this MSC changes this). Though what @turt2live means by read markers in this case is `m.fully_read` itself, _not_ the `/read_markers` endpoint

2022-07-13 17:48 UTC, KitsuneRal commented on proposals/2285-hidden-read-receipts.md
> +much responsibility to an existing structure.
The `m.hidden` as proposed previously did not alter the value shape of the receipt itself though. It was another key-value next to `m.read` and `m.fully_read`. And, sure, it was all too easy to end up exposing private receipts in that case. Having `"m.read": { "m.hidden": true, "event_id": "$evt" }` would not allow the current homeservers to parse it as usual while updated homeservers could take notice and stop broadcasting `m.read`, while still sending the "usual" `m.read` down the line of the client. There's a small problem still that other clients of the same user would not be aware that this `m.read` is private - but given that they are on the receiving end of that very user I'm not sure about the value of this information.

I apologise again - I should have brought this line of reasoning a month ago...

2022-07-13 18:00 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +be consistent)
Should be updated

2022-07-13 18:03 UTC, KitsuneRal commented on proposals/2285-hidden-read-receipts.md
> +should be handled in a separate MSC.
Yes, good enough, thanks.

2022-07-13 18:05 UTC, KitsuneRal commented on proposals/2285-hidden-read-receipts.md
> +be consistent)
I still don't think `m.fully_read` should be added to `/receipt` - see above :)

2022-07-13 18:11 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +much responsibility to an existing structure.
right, I think I can see the advantage/desire to keep the existing `m.read` type but using an intentionally different shape, though that feels like it'd introduce complexity in the form of selective read receipts (by nature of using a dictionary), which is a bit counter to what this MSC aims to achieve.

It'd certainly be a good option for a future/different MSC though, as I can see the benefit of selective read receipts (email bridge to a room, for example).

2022-07-14 08:20 UTC, deepbluev7 commented on proposals/2285-hidden-read-receipts.md
> +much responsibility to an existing structure.
Sending m.read with a "hidden" flag however was much easier for clients as well as servers to implement. Yes, it adds an additional feature to existing read receipts and it does have some edge cases, where on older servers it wouldn't work properly, but I don't think that was a good argument for the added complexity that m.read.private brings. m.read.private was about 3 times as much code to implement in my client than the hidden flag for what basically amounts to the same feature and the ordering issue it introduces has been like half the discussion on this MSC.

2022-07-14 08:43 UTC, dkasak commented on proposals/2285-hidden-read-receipts.md
> +much responsibility to an existing structure.
For me, the potential for private read receipts to leak on an unsupporting server is a deal breaker, so I strongly disagree with not having a separate type. I also don't view `m.read.private` and `m.read` as being the same entity -- one is simply a *marker for myself* of which rooms I've opened since the latest events arrived in them, the other is something I primarily want to *tell others*.

It's unfortunate that marking for myself and informing others was initially conflated under `m.read`. In an ideal world, we'd have made `m.read` private and then had a separate, explicit `m.read.public` on top when wanting to inform other people. But since this isn't how it was initially designed, I think `m.read.private` is the best we can do now while also ensuring strong guarantees about not leaking information.

2022-07-14 13:28 UTC, deepbluev7 commented on proposals/2285-hidden-read-receipts.md
> +much responsibility to an existing structure.
Hm, yes, that sounds reasonable. But in that case I would propose a long term migration strategy to recommend clients to always send the private read receipt (with m.read being optional instead) and eventually maybe deprecate either that m.read affects notifications or that client are allowed to send m.read without m.read.private (unless for appservice usecases or something). That would sidestep having to deal with both for notifications too (in the long term).

2022-07-14 16:32 UTC, turt2live commented on proposals/2285-hidden-read-receipts.md
> +much responsibility to an existing structure.
Adding such a recommendation would be a bit too far out of scope for this MSC, at least from my perspective. It's not immediately obvious that the whole ecosystem would benefit from such a recommendation: the spec is more in the position to provide the tools people can use rather than dictate flow, for this case.

----

I'm going to close this thread as resolved: so far it's been concluded that future MSCs can do the additional work that gets brought up here, which I think is the correct decision. Rehashing `m.hidden` (or similar) is also not a productive way to use FCP - we're looking for last minute blockers that will prevent the system from working rather than exploring ideas that have already been discussed (and rejected). If folks spot something in the MSC which won't work, please raise that - it's what the FCP is for.

2022-07-16 11:59 UTC, zecakeh commented on proposals/2285-hidden-read-receipts.md
> +The `m.read` property is now optional for the [`/read_markers`
```suggestion
The `m.fully_read` property is now optional for the [`/read_markers`
```

`m.read` is already optional, and according to [this comment](https://github.com/matrix-org/matrix-spec-proposals/pull/2285#discussion_r920350727) this MSC makes `m.fully_read` optional.

2022-07-16 12:10 UTC, SimonBrandner commented on proposals/2285-hidden-read-receipts.md
> +The `m.read` property is now optional for the [`/read_markers`
Thank you!!

2022-07-17 19:06 UTC, merged

2022-08-25 20:23 UTC, turt2live commented
Spec PR: https://github.com/matrix-org/matrix-spec/pull/1216

2022-09-12 22:35 UTC, turt2live commented
Merged 🎉

2022-09-13 04:15 UTC, Bugsbane commented
Do you know if there's any issue to watch, regarding getting this MSC supported in Elerment (Android/iOS/web)?

2022-09-13 04:23 UTC, SimonBrandner commented
> Do you know if there's any issue to watch, regarding getting this MSC supported in Element (Android/iOS/web)?

It's already implemented in Element Web/Desktop, for Android and iOS: https://github.com/vector-im/element-android/issues/2436 and https://github.com/vector-im/element-ios/issues/4646 respectively

2022-09-15 01:26 UTC, Bugsbane commented
Oh, freaking sweet! This feature was the last blocker before rolling out my Synapse server. Super happy it's already in Element, too!