MSC2409: Proposal to send EDUs to appservices
matrix-org/matrix-spec-proposals pull request #2409
Opened 2020-01-14 16:16 UTC by Sorunome

[Rendered](https://github.com/Sorunome/matrix-doc/blob/soru%2Bhs/appservice-edus/proposals/2409-appservice-edus.md)

This MSC is a continuation of [MSC1888](https://github.com/matrix-org/matrix-doc/pull/1888) and thus depricates it.

Signed-off-by: Sorunome <mail@sorunome.de>

2020-02-26 23:40 UTC, ericmigi commented
bumping this up as it would help out of a ton of mx-puppet-slack users! :)

2020-03-03 11:11 UTC, MRAAGH commented
I really miss this while using mx-puppet-discord. Typing notifications add so much extra value to a chat!

2020-03-21 13:08 UTC, auscompgeek commented
It seems to me that it would be worth making appservices opt into receiving EDUs to avoid pushing EDUs to an appservice that doesn't care about them.

2020-03-21 17:25 UTC, Half-Shot commented
@auscompgeek would be even better if appservices could add a filter to their registration data to filter out anything they don't care about.

2020-04-03 16:00 UTC, Sorunome commented
@Half-Shot maybe in general add the filter object to the registration file? That way PDUs could also be filtered. That sounds like it should be a separate MSC, though

2020-04-03 16:01 UTC, Half-Shot commented
> @Half-Shot maybe in general add the filter object to the registration file? That way PDUs could also be filtered. That sounds like it should be a separate MSC, though

It was one from a while ago, but we dropped at the time as the performance gains from doing so weren't worth it.

2020-04-03 16:02 UTC, Sorunome commented
> > @Half-Shot maybe in general add the filter object to the registration file? That way PDUs could also be filtered. That sounds like it should be a separate MSC, though
> 
> It was one from a while ago, but we dropped at the time as the performance gains from doing so weren't worth it.

Does it sound worthy to bring that up again, in relation with this MSC, and then leave filtering to, well, the filters?

2020-04-03 16:05 UTC, Half-Shot commented
Yup. I think it's worth noting that we might need filters, but at this point I think that's a seperate concern. This MSC is facilitating the ability for ASes to recieve EDU traffic, another MSC can handle filtering of that traffic.

2020-08-26 20:09 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +The appservice /transaction API currently supports pushing PDU events (regular message and state events)
link to the API please

2020-08-26 20:09 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +specifiys how these can be pushed to an appservice.
```suggestion
specifies how these can be pushed to an appservice.
```

2020-08-26 20:10 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +old implementations may mistake them for PDUs and could cause undefined behaviour.
```suggestion
existing appservices may mistake them for PDUs and could cause undefined behaviour.
```

2020-08-26 20:12 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +network and the appservice more.
due to the performance issues involved, the registration should have an opt-in flag so the homeserver can skip processing the EDUs if the appservice doesn't care. A later MSC can provide more granular filtering on both PDUs and EDUs.

2020-09-01 08:38 UTC, Sorunome commented on proposals/2409-appservice-edus.md
> +The appservice /transaction API currently supports pushing PDU events (regular message and state events)
Done!

2020-09-01 08:39 UTC, Sorunome commented on proposals/2409-appservice-edus.md
> +network and the appservice more.
added `receive_edus` to the registration file!

2020-09-19 10:40 UTC, Half-Shot commented on proposals/2409-appservice-edus.md
> +# MSC2409: Proposal to send EDUs to appservices
Having thought about this a bit more, one of the difficult parts of implementation (for me) has been trying to shoe-horn EDU traffic into transactions. Transactions are logical blocks of events that should be retried if the service is down, but EDUs are categorically not (in most cases).

If you miss a presence, read receipt or typing then you typically as a service don't want that to be retained. So in some ways this feels like the wrong shape of API, since we're doing a `PUT /transaction/12345` except we don't expect 12345 to contain the same contents anymore.

So I am wondering if there should be a seperate endpoint to push this traffic down, which just pushes whenever the homeserver has data (AND the appservice is considered "up"). 

(to_device is a bit of a special case in that homeservers DO want to send those reliably, so that may need to come down a third endpoint, or shoved into a transaction where a transaction ID roughly maps to the stream ID of an inbox)

2020-09-25 17:19 UTC, Sorunome commented on proposals/2409-appservice-edus.md
> +# MSC2409: Proposal to send EDUs to appservices
how is it so much different from a `/sync`?

2020-09-25 17:20 UTC, tulir commented on proposals/2409-appservice-edus.md
> +# MSC2409: Proposal to send EDUs to appservices
`/sync` doesn't reliably deliver everything like appservice transactions do

2020-09-25 17:28 UTC, Sorunome commented on proposals/2409-appservice-edus.md
> +# MSC2409: Proposal to send EDUs to appservices
Then...soru doens't quite understand where the problem is. You try to put a transaction, it fails, you re-try later. Why does that re-trying later have to contain the same edus? what is stopping it from just...not containing them?

2020-09-26 15:44 UTC, auscompgeek commented on proposals/2409-appservice-edus.md
> +# MSC2409: Proposal to send EDUs to appservices
This problem isn't really any different to the desired unreliability of those EDUs over federation, and federation uses transactional endpoints too, right?

2020-09-28 20:43 UTC, Half-Shot commented on proposals/2409-appservice-edus.md
> +# MSC2409: Proposal to send EDUs to appservices
>You try to put a transaction, it fails, you re-try later. Why does that re-trying later have to contain the same edus?

I could be reading the spec wrong, but the txnId from the homeserver basically ensures that the content in the transaction is going to be the same for the same txnId. Ergo if you send txn 123, and it fails, and then you resend it with different EDU data, then you've violated that promise. 

>And even if it has to contain the same edus, why is that bad

I think because typically it's unhelpful for appservices to receive stale presence/typing data, and potentially read receipts too since they get bundled as one event.

On the other hand, we can choose not to care about any of this for the EDU field, but it does feel a bit wrong.

2020-09-28 20:57 UTC, tulir commented on proposals/2409-appservice-edus.md
> +# MSC2409: Proposal to send EDUs to appservices
> I could be reading the spec wrong, but the txnId from the homeserver basically ensures that the content in the transaction is going to be the same for the same txnId. Ergo if you send txn 123, and it fails, and then you resend it with different EDU data, then you've violated that promise.

This is a Matrix spec change, which means we can change the spec. That promise doesn't necessarily have to apply to EDUs.

2020-09-28 20:59 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +# MSC2409: Proposal to send EDUs to appservices
it would go against the terminology of Matrix to change the behaviour for a single transaction endpoint. EDUs should be reliably known by the server given they are repeated in federated transactions, so there's not really an excuse to drop them on the floor.

2020-09-30 12:40 UTC, Half-Shot commented on proposals/2409-appservice-edus.md
> +  "ephemeral": [
Presumably this will need a further MSC, but it would be good to be able to send device_list changes to the appservice which aren't EDUs at all?

2020-10-01 13:17 UTC, Half-Shot commented on proposals/2409-appservice-edus.md
> +## Security considerations
@Sorunome it would be good to have an unstable prefix section so I can implement this. We would need one on the transaction body `ephemeral` key, so something like `de.sorunome.msc2409.ephemeral`. We would also need one for the registration file key `receive_edus` (`de.sorunome.msc2409.receive_edus`).

2020-10-01 13:23 UTC, Half-Shot commented on proposals/2409-appservice-edus.md
> +setting `receive_edus` to true. A registration file could look like following:
Can we change this to `push_ephemeral`, my reasons are twofold:
- This is an instruction for the homeserver to push.
- The bridge won't receive raw EDUs in a technical sense, but rather the resulting C-S API edition of the event (e.g. some events are manufactured in the homeserver like read_receipts).

2020-10-01 13:23 UTC, Half-Shot commented on proposals/2409-appservice-edus.md
> +## Security considerations
As per the above, keen we use push_ephemeral

2020-10-01 13:25 UTC, Half-Shot commented
Implementing over at https://github.com/matrix-org/synapse/pull/8437

2020-10-13 09:57 UTC, Half-Shot commented on proposals/2409-appservice-edus.md
> +## Security considerations
So if we could have a `de.sorunome.msc2409.push_ephemeral` key, and a `de.sorunome.msc2409.ephemeral` for the transaction body that would be good :+1:

2020-10-16 08:22 UTC, Half-Shot commented on proposals/2409-appservice-edus.md
> +# MSC2409: Proposal to send EDUs to appservices
The synapse implementation uses /transactions to do this, so closing.

2020-10-18 11:20 UTC, tulir commented
mautrix-python impl: https://github.com/tulir/mautrix-python/commit/ee74e1706fc9d223b72c50ad5b40b949840be7c8

2020-11-10 05:24 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +specifies how these can be pushed to an appservice.
another justification is that complex bots might find this information valuable, but instead have to weigh a risk of either crushing the server with `/sync` or not having the relevant features.

2020-11-10 05:24 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +setting `push_ephemeral` to true. A registration file could look like following:
what if it is set to false?

```suggestion
To prevent accidentally flooding existing appservices with EDUs, appservices must set `push_ephemeral` to
`true` in their registration. When `false` (the default), the appservice will not receive EDUs. A registration file 
could look like following:
```

2020-11-10 05:24 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +  "ephemeral": [
that will probably need a new MSC indeed. Appservices don't *really* have real devices they can rely on in some server implementations.

2020-11-10 05:24 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +if the sender is present in a room that is shared by any of the registered appservices users.
This is slightly different from today's specification. Today's specification uses a concept of interest to determine if an event needs to be sent to the application service. Registration of a user is not required in order to be interested in an event - the user just has to be in the namespace. As such, this paragraph could be reworded as:

> An appservice is interested in an EDU if the appservice would be interested in the associated room or sender as though it were a regular room event. For example, the presence of a user (not associated with a room) would be sent to the appservice if the appservice had a namespaced user participating in a room with that user or the room ID/aliases match the appservice's namespace(s). Similarly, a typing event (which is associated with a room) would be sent if the appservice was interested in the room or sender.

2021-05-18 22:02 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +setting `push_ephemeral` to true. A registration file could look like following:
hello november travis: this is pretty obvious.

2021-05-18 22:03 UTC, turt2live approved these changes
General concept seems sane to me.

2021-05-18 22:04 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +  "ephemeral": [
Other MSCs seem to give the appservice a device reliably, so I think this MSC can now adopt EDUs properly.

2021-05-28 20:57 UTC, kevincox commented on proposals/2409-appservice-edus.md
> +existing appservices may mistake them for PDUs and could cause undefined behaviour.
```suggestion
existing appservices may mistake them for PDUs and might behave erratically.
```

Nit: "may" can be misinterpreted as "is allowed" and we are not allowing "undefined behaviour". Also I don't think Matrix has the concept of undefined behaviour.

2021-05-28 20:57 UTC, kevincox commented on proposals/2409-appservice-edus.md
> +setting `push_ephemeral` to true. A registration file could look like following:
Is this granular enough? What if an appservice wants to receive typing notifications but not presence updates? It could be a significant resource savings to avoid sending types of events that are just going to be thrown away. Something as simple of making this a list of types could save a lot of resources. Maybe for future extensibility it could be a map of type to empty object, a default can be specified with the type of `*` (or a separate key). I imaging that most appservices would have a static list of events that they support so listing the supported event types makes sense. I suspect that getting all events is a rarer case.

On the other hand the config file is kinda the wrong place for this, maybe we can let the appservice negotiate with the homeserver somehow. However in that case why do we have a flag in the config file as well? Why not just let the appservice tell the server which events it is interested in (and it can remind/update the server every time it boots up).

I see that this was discussed before (https://github.com/matrix-org/matrix-doc/pull/2409#issuecomment-602075652) but I think we should reconsider this. I would rather not have a flag in the config file as it isn't something that an admin would (normally) care about. If we are going to add filtering in the future why don't we add that as the opt-in mechanism?

2021-05-28 21:45 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +setting `push_ephemeral` to true. A registration file could look like following:
Filtering on the server side wouldn't be much more efficient given the proximity appservices have to the inner workings of the homeserver. Much like room events, the appservice can ignore whatever it doesn't need.

2021-05-29 14:52 UTC, kevincox commented on proposals/2409-appservice-edus.md
> +setting `push_ephemeral` to true. A registration file could look like following:
Then why is there an opt-in at all? Is it just a temporary measure for appservices that don't know that they should apply a filter here yet?

2021-05-29 20:08 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +setting `push_ephemeral` to true. A registration file could look like following:
Because spamming appservices with otherwise empty transactions isn't very great, and it still does have a performance impact. Filtering would likely make the performance issue even worse for the server-side, whereas the appservice can share the CPU cost of it.

2021-05-30 23:06 UTC, kevincox commented on proposals/2409-appservice-edus.md
> +setting `push_ephemeral` to true. A registration file could look like following:
Nit and mostly offtopic:

> Filtering would likely make the performance issue even worse for the server-side

I would expect filtering to cost a couple of orders of magnitude less than serializing and sending objects across the network. This is also assuming something about the colocation of the services which is usually close but depends on the user's setup.

2021-10-05 20:48 UTC, turt2live commented
This MSC gained the label because the implementation is not linked in the PR description.

From my perspective, the implementation is incomplete due to the performance issues and fact that it didn't try to send all the EDUs to the appservice, such as device list changes. I believe the latter of this is currently underway, but the former makes it very difficult to prove that this MSC works in practice if everyone is required to disable it once a small amount of traffic passes over the connection - this isn't to say it needs to be safe to enable on the likes of the Old Freenode bridge, but it should be possible for large bridges to turn it on and prove it works. It's a similar requirement that encrypted appservices will face in time.

2021-11-18 12:42 UTC, richvdh commented on proposals/2409-appservice-edus.md
> +  "ephemeral": [
Part of me is unconvinced that we should be grouping all these things together into `ephemeral`. It's different to the way `/sync` does it, which has separate `presence`, `to_device`, `device_lists` sections (though it does use `ephemeral` for typing events and read-receipts.)

That said, it is the same as the way the federation api does it.

2021-11-18 12:42 UTC, richvdh commented on proposals/2409-appservice-edus.md
> +      "type": "m.typing",
please can we use `edu_type` here, for consistency with the federation api.

2021-11-18 12:44 UTC, richvdh commented on proposals/2409-appservice-edus.md
> +field at the top level of the EDU for transport to the appservice:
surely not at the top level?

2021-11-18 12:48 UTC, Half-Shot commented on proposals/2409-appservice-edus.md
> +  "ephemeral": [
It feels okay to treat this similar to the federation API, because we're doing a similar thing in that this API pushes the events to the AS to be consumed as events rather than a client consuming state changes (user has stopped typing, user has started typing).

Ultimately with my bridge developer hat on, this shape of API is easier to work with as it means we can consume ephemeral events similar to how we consume regular timeline events, and so far that has worked out for the ~5 bridges I've done this with.

2021-11-18 12:50 UTC, Half-Shot commented on proposals/2409-appservice-edus.md
> +      "type": "m.typing",
Seems reasonable to me if we assume that https://github.com/matrix-org/matrix-doc/pull/2409#discussion_r752203766 is going to carry on with the federation API-like shape. :+1:

2021-11-18 12:51 UTC, richvdh commented on proposals/2409-appservice-edus.md
> +field at the top level of the EDU for transport to the appservice:
actually, since the to-device messages here don't have a direct correspondence to the underlying `m.direct_to_device` events, which can contain multiple to-device messages, (see https://spec.matrix.org/v1.1/server-server-api/#send-to-device-messaging), we should probably use a separate section for to-device messages, at which point, yes can do all this at the top level.

2021-11-18 12:52 UTC, richvdh commented on proposals/2409-appservice-edus.md
> +  "type": "m.new_device",
we either need to put these in a separate section of the response, or wrap them in a `type: "m.direct_to_device"` EDU-like-thing, to avoid a namespace clash. (to-device-message types and EDU types are different namespaces)

2021-11-18 12:58 UTC, richvdh commented on proposals/2409-appservice-edus.md
> +  "type": "m.new_device",
(strong vote for a separate section from me, otherwise you've got to think of a good `type` for the pseudo-EDU. `m.direct_to_device` is misleading because it makes you think that they have the same shape as the real EDUs.)

2021-11-18 13:01 UTC, tulir commented on proposals/2409-appservice-edus.md
> +      "type": "m.typing",
Do we *have* to copy the mistakes from the federation API too?

2021-11-18 13:14 UTC, tulir commented on proposals/2409-appservice-edus.md
> +  "ephemeral": [
Presence and typing/receipts can be in the same area, but it would probably make sense to separate to-device messages. Device lists and OTK counts are already separated (#3202)

2021-11-18 13:20 UTC, Half-Shot commented on proposals/2409-appservice-edus.md
> +  "type": "m.new_device",
pseudo-EDUs sound horrible, so own section feels okay to me.

2021-11-19 15:14 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +  "ephemeral": [
Appservices are more related to federation than the sync structure, so I'd be inclined to maintain a single list.

Device lists and OTK counts are separate because of how those pieces of data are thrown around Matrix.

What is the intended benefit of splitting out to-device specifically?

2021-11-19 15:22 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +  "ephemeral": [
For clarity: I do not want us to arbitrarily copy the federation structure wholesale as it leads to implementation complications. Appservices are still half clients.

2021-11-19 15:46 UTC, tulir commented on proposals/2409-appservice-edus.md
> +  "ephemeral": [
The comments are split across 3 threads and in the third thread @richvdh said

> to-device-message types and EDU types are different namespaces

so if we don't split the to-device events, they'd have to be wrapped in an EDU like `m.direct_to_device`.

2021-11-19 16:42 UTC, richvdh commented on proposals/2409-appservice-edus.md
> +  "ephemeral": [
yeah sorry, I split the threads a bit here. Let's take this to https://github.com/matrix-org/matrix-doc/pull/2409#discussion_r752211109 for now.

2021-11-19 16:43 UTC, richvdh commented on proposals/2409-appservice-edus.md
> +field at the top level of the EDU for transport to the appservice:
resolving in favour of https://github.com/matrix-org/matrix-doc/pull/2409#discussion_r752211109

2021-11-19 18:34 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +  "type": "m.new_device",
Is the format at least presentable? Noting that `m.new_device` is a bad example as that is handled in [MSC3202](https://github.com/matrix-org/matrix-doc/pull/3202) specifically. A more practical example would be establishing an Olm session.

For simplicity's sake, using the same format and sticking them under a transaction top-level `to_device` array would probably be fine?

2021-12-01 16:34 UTC, anoadragon453 commented on proposals/2409-appservice-edus.md
> +array in the transaction. If there are no messages to be sent, the array can be omitted.
Can we also omit the `ephemeral` array if there are no ephemeral events to send?

2021-12-01 16:36 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +array in the transaction. If there are no messages to be sent, the array can be omitted.
yes

2021-12-01 16:40 UTC, tulir commented on proposals/2409-appservice-edus.md
> +      "edu_type": "m.typing",
Why do we have to copy the `type` field naming mistake from the federation API? PDUs sent to appservices are client-formatted too, so it makes no sense to use `edu_type` here just because the federation API does that.

2021-12-01 16:51 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +      "edu_type": "m.typing",
Appservices attach themselves to a server rather than act as a client, which brings them closer to the federation level of how Matrix works. As such, it feels important (to me, imo) to acknowledge and reinforce the relationship an appservice has to its server.

2021-12-01 17:23 UTC, tulir commented on proposals/2409-appservice-edus.md
> +      "edu_type": "m.typing",
I'm not sure if that's true and I don't see how this is an useful way to do that even if it is true.

* Appservices get all other events in client format. If PDUs and to-device events were sent in federation format, then it'd be understandable to use the federation format for EDUs too, but they're not, and I don't think anyone wants that either (might be fun as an optional flag like the client API has, but not by default).
* Appservices are generally based on Matrix client frameworks (matrix-{js,bot}-sdk, mautrix-{go,python}). The code for handling events seems to be partially shared with the client API in both Synapse and many appservices, so in practice, Synapse would need new code to rename the field to `edu_type`, and appservices would need new code to rename it back to `type`.

2021-12-01 17:42 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +      "edu_type": "m.typing",
@richvdh I'd appreciate your thoughts on switching back to `type` - I'd rather not bounce between the two for years to come.

2021-12-01 18:26 UTC, richvdh commented on proposals/2409-appservice-edus.md
> +      "edu_type": "m.typing",
bleh. It's probably fair to say that ASes are closer to clients than servers, and as such trying to use `edu_type` for things like `m.typing` is going to require some annoying translation code on both the AS and server side.

It is annoying that it introduces an inconsistency with the federation API, and I'm not necessarily sure the "mistake" is on the federation API rather than the C-S API but :man_shrugging:.

Ultimately if those who write ASes find `type` significantly easier than `edu_type` here, then let's go with that.

Related: https://github.com/matrix-org/matrix-doc/issues/1143, https://github.com/matrix-org/matrix-doc/issues/3405.

2022-09-01 08:20 UTC, andreidiaconescu commented
hello,
what is the status of this feature: can we receive typing events in the Application Service ?

2022-09-01 20:43 UTC, turt2live commented
Status updates are best asked in [#sct-office:matrix.org](https://matrix.to/#/#sct-office:matrix.org) so we can better provide an answer.

Currently, this MSC could do with a champion to bring it through the process.

2023-10-19 23:23 UTC, Half-Shot commented
Hey, it's 2023 (well, it's nearly 2024 but don't let that get you down)!

I'm thinking of picking this one up, as it's a few years later and we're (matrix.org bridges / Element integrations) are using this MSC a lot, which is generally a good indicator that we like what it does and it works well enough.

I think there are probably two tracks here to be cleaned up, which are:

> Are we happy with the general format of the transaction body (`type` v.s. `edu_type`).

I'm generally of the opinion that since this landed in Synapse experimentally, we've managed to implement this without much pain and what is spec'd seems to work.

> Is it performant?

This is harder to answer, but we did run the libera.chat bridge for a number of years with this enabled and Element runs several servers with this feature turned on so I think in a lot of cases it can be performant. There are a few outstanding Synapse bugs, but my feeling is these are implementation problems / details and do not pertain to the described spec.

In short, I think we're in a place to start considering this as a proper spec now. We've got implementations, we've got happy usage out of it. The next steps I believe are to hear what the consensus is from the spec team and wider.

2023-10-20 11:33 UTC, tulir commented
> I'm generally of the opinion that since this landed in Synapse experimentally, we've managed to implement this without much pain and what is spec'd seems to work.

It's implemented as `type` everywhere, but the proposal text still says `edu_type` 🤔

2023-10-20 12:26 UTC, Half-Shot commented
I don't think it's worth trying to rewrite the world, let's just fix the proposal.

2023-10-20 13:50 UTC, anoadragon453 commented on proposals/2409-appservice-edus.md
> +existing appservices may mistake them for PDUs and could cause undefined behaviour.
I don't think the use of "may" here is a problem, as this sentence is just saying "old implementations of application services may not expect an entry in `events` with type `m.receipt` and thus error out. Therefore let's have a new property called `ephemeral`".

"undefined behaviour" in this sentence refers to errors in older AS implementations; not in relation to the spec itself. This phrase is obviously causing confusion though, so alternative wording seems justified.

---

If this MSC weren't already implemented everywhere I may suggest that this is a weak justification for a new field, and ask for proof in existing appservice implementations of EDUs in `events` triggering errors (which implies a broken implementation...). But since we've settled on `ephemeral` in the wild - and it does make the payload a bit easier to read - I don't have an objection to keeping `ephemeral` as a separate array.

2023-11-15 16:32 UTC, Half-Shot commented on proposals/2409-appservice-edus.md
> +array in the transaction. If there are no messages to be sent, the array can be omitted.
15f4582c9b00072851033e705881ecfea72c04fa

2024-01-09 09:39 UTC, dbkr commented on proposals/2409-appservice-edus.md
> +Note that the EDU is otherwise formatted as it would for client-server API transport.
```suggestion
Note that the EDU is otherwise formatted as it would be for client-server API transport.
```

2024-01-09 09:44 UTC, dbkr commented on proposals/2409-appservice-edus.md
> +Unlike other ephemeral events, to-device messages are included at a top level `to_device`
Could this get a mention back where the `ephemeral` key is introduced please? ie. give a summary of what's being added and then give the detail on each.

2024-01-09 09:48 UTC, dbkr commented on proposals/2409-appservice-edus.md
> +combo. These events are annotated by the server with a `to_device_id` and `to_user_id`
Would maybe make more sense to wrap the to_device events in their own object which contains the metadata for this transport layer? ie.

```json
{
  "to_user_id": "@_irc_bob:example.org",
  "to_device_id": "ABCDEF123",
  {
    "type": "org.example.to_device_event_type",
    "sender": "@alice:example.com",
    "content": {
      "hello": "world"
    }
  }
}
```

...then there's no chance of overlapping keys (although obviously this would be unlikely anyway) and the receiving server can just take the inner object out and pass it on verbatim?

2024-01-09 09:53 UTC, dbkr commented on proposals/2409-appservice-edus.md
> +setting `push_ephemeral` to true. A registration file could look like following:
nitpick, perhaps, but since this file is describing the app service, should it be, `receive_ephemeral` rather than 'push'? (indeed, the comment below is phrased in this way too).

2024-01-09 09:55 UTC, dbkr commented on proposals/2409-appservice-edus.md
> +setting `push_ephemeral` to true. A registration file could look like following:
I'm not 100% on this but it feels slightly confusing that `ephemeral` here matches the new `ephemeral` section the body, but it also controls the presence of the `to_device` section. Could it be clearer to just have a separate field to control whether the AS wants to_device messages (and maybe this could actually be useful for an AS to be able to subscribe to to_device message without getting presence, etc?)

2024-01-09 15:54 UTC, turt2live commented on proposals/2409-appservice-edus.md
> +setting `push_ephemeral` to true. A registration file could look like following:
In my opinion a filter would be best suited for a future MSC. Appservices already don't have an option to filter what events (PDUs) they receive, but it would be great if they could.

"Ephemeral" here is also inherited from the server-server API rather than client-server API: it includes to-device messages, but changes shape to be more useful as a representation. We could absolutely package it into `ephemeral`, but appservices will already be translating it to fit their crypto engine shape anyways - might as well give them something directly compatible.

Overall, appservices being closer to federation than clients makes things weird. We should improve them, but I don't think this is the MSC to fix everything.

2024-01-09 16:16 UTC, richvdh requested changes

2024-01-09 16:16 UTC, richvdh commented on proposals/2409-appservice-edus.md
> +shares a room with (or is under the appservice's namespace) would be sent to the appservice.
Strongly recommend writing explicit rules for each type of event, rather than handwaving about EDUs in general.

(Also, note again that EDUs don't exist as a concept at all outside the federation API)

2024-01-09 16:16 UTC, richvdh commented on proposals/2409-appservice-edus.md
> +The homeserver needs to accuratley determine which EDUs to send to the appservice, as to not leak
```suggestion
The homeserver needs to accurately determine which EDUs to send to the appservice, as to not leak
```

2024-01-09 16:16 UTC, richvdh commented on proposals/2409-appservice-edus.md
> +that EDU.
The same is true of to-device messages?

2024-01-09 16:16 UTC, richvdh commented on proposals/2409-appservice-edus.md
> +  message. Note that retried transactions will still need to include the message.
This seems to assume that a client somewhere is `/sync`ing with the same device ID as the appservice? And both devices want to receive the to-device message?

I'll note that this does not yet seem to be implemented (https://github.com/element-hq/synapse/issues/11423). Maybe that's ok since this is not a normative part of the MSC, but I'm a bit troubled that this is left undefined.

2024-01-09 16:16 UTC, richvdh commented on proposals/2409-appservice-edus.md
> +  message. Note that retried transactions will still need to include the message.
I don't really understand why we can only delete messages for users under an appservice's *exclusive* namespace. There's probably some explanation somewhere in the depths of https://github.com/matrix-org/synapse/issues/10653, but it needs explaining here imho

2024-01-16 09:22 UTC, Half-Shot commented
Just for explicitness: I'm happy to shepherd this MSC.

2024-04-23 02:56 UTC, turt2live commented
Canceling FCP while this remains a work in progress.

@mscbot fcp cancel

2024-09-28 21:09 UTC, tulir commented on proposals/2409-appservice-edus.md
> +setting `push_ephemeral` to true. A registration file could look like following:
The field has been renamed

2024-09-28 21:11 UTC, tulir commented on proposals/2409-appservice-edus.md
> +Note that the EDU is otherwise formatted as it would for client-server API transport.
It now explicitly says the format is C-S sync format + `room_id`

2024-09-28 21:12 UTC, tulir commented
I've deleted to-device events, clarified which EDUs are covered here and renamed `push_ephemeral` to `receive_ephemeral` (stable field only - unstable version is unaffected). I'll make a new MSC specifically for to-device events, as it's a fairly separate thing from typing/receipts/presence.

I think I addressed all the review comments that were about ephemeral events and not only about to-device, so:

@mscbot fcp merge

2024-09-30 13:02 UTC, clokep commented on proposals/2409-appservice-edus.md
> +only three event types that can currently occur: `m.presence`, `m.typing` and `m.receipt`.
I've thought a bit about it and don't see any issues, but wanted to double check that you considered both private read receipts and threaded read receipts when re-evaluating this proposal?

2024-09-30 13:12 UTC, tulir commented on proposals/2409-appservice-edus.md
> +appservice under the same rules as regular events (interest in the room means sending it).
Hmm, I guess it should only send if the appservice is interested in the user

2024-10-01 13:55 UTC, richvdh commented on proposals/2409-appservice-edus.md
> +# MSC2409: Proposal to send EDUs to appservices
Might be good to clarify that this no longer covers all EDUs

```suggestion
# MSC2409: Proposal to send typing, presence and receipts to appservices
```

2024-10-01 13:55 UTC, richvdh commented on proposals/2409-appservice-edus.md
> +only three event types that can currently occur: `m.presence`, `m.typing` and `m.receipt`.
```suggestion
only three event types that can currently occur: [`m.presence`](https://spec.matrix.org/v1.11/client-server-api/#mpresence), [`m.typing`](https://spec.matrix.org/v1.11/client-server-api/#mtyping), and [`m.receipt`](https://spec.matrix.org/v1.11/client-server-api/#mreceipt).
```

2024-10-01 18:37 UTC, anoadragon453 approved these changes
Just some small polish, but overall LGTM!

2024-10-01 18:37 UTC, anoadragon453 commented on proposals/2409-appservice-edus.md
> +*Node: This proposal is a continuation of [MSC1888](https://github.com/matrix-org/matrix-doc/pull/1888)
```suggestion
*Note: This proposal is a continuation of [MSC1888](https://github.com/matrix-org/matrix-doc/pull/1888)
```

2024-10-01 18:37 UTC, anoadragon453 commented on proposals/2409-appservice-edus.md
> +homeservers side. Additionally, more network traffic is produced, potentially straining the local
```suggestion
homeserver side. Additionally, more network traffic is produced, potentially straining the local
```

2024-10-01 18:37 UTC, anoadragon453 commented on proposals/2409-appservice-edus.md
As to-device messages are often talked about in the context of EDUs, could you explicitly say that this MSC **does not** cover to-device events and that it is left to a future MSC?

2024-10-01 18:37 UTC, anoadragon453 commented on proposals/2409-appservice-edus.md
> +any metadata about users. Particularly `m.presence` could be tricky, as no `room_id` is present in
```suggestion
any unnecessary metadata about users. Particularly `m.presence` could be tricky, as no `room_id` is present in
```

2024-10-18 00:04 UTC, uhoreg commented on proposals/2409-appservice-edus.md
> +receive_ephemeral: true
[non-blocking comment:] Might be nice to allow some way of selecting *which* EDUs to receive, but that could be something added in a future MSC.

2024-10-18 09:18 UTC, tulir commented on proposals/2409-appservice-edus.md
> +receive_ephemeral: true
There were at least two threads and one non-thread discussion about filtering, but somehow it never ended up being mentioned in the MSC. I think the general consensus is that it's better to leave to a future MSC.

2024-10-21 03:33 UTC, cloudrac3r approved these changes

2024-10-28 15:53 UTC, merged

2024-11-28 16:30 UTC, zecakeh commented
spec PR: https://github.com/matrix-org/matrix-spec/pull/2018