Proposal for Authenticated Content Repository API
matrix-org/matrix-spec-proposals pull request #2461
Opened 2020-03-15 04:00 UTC by SyrupThinker

[Rendered](https://github.com/SyrupThinker/matrix-doc/blob/authenticated_content_repository_api/proposals/2461-authenticated-content-repository-api.md)

2020-03-15 08:20 UTC, Sorunome commented on proposals/2461-authenticated-content-repository-api.md
> +| m.local | Only content with an authority the server is responsible for can be accessed unauthenticated |
What does this mean? Basically all users in the room can see it, but noone else?

2020-03-15 08:21 UTC, Sorunome commented on proposals/2461-authenticated-content-repository-api.md
> +| m.cached | Only cached content can be accessed unauthenticated |
Is this even needed? It sounds odd - someone in the room accesses the content and then suddenly everyone can as it is cached

2020-03-15 08:21 UTC, Sorunome commented on proposals/2461-authenticated-content-repository-api.md
> +the configuration field m.media.unauthenticated is added.
Added where? To which endpoint? Down there you have that as a reply and not as sending, so something is off

2020-03-15 08:22 UTC, Sorunome commented on proposals/2461-authenticated-content-repository-api.md
> +Clients can decide based on this
why not add the authentification type to `m.file` etc.? So like

```json
{
  "url": "blah",
  "info": { ... },
  "authenticated": "m.local"
}
```

2020-03-15 10:17 UTC, SyrupThinker commented on proposals/2461-authenticated-content-repository-api.md
> +the configuration field m.media.unauthenticated is added.
Added endpoint in new revision

2020-03-15 10:21 UTC, SyrupThinker commented on proposals/2461-authenticated-content-repository-api.md
> +Clients can decide based on this
I might have miscommunicated  the intent of this proposal by adding synapse#2150 considering it is only tagentally related. I've read the conversation some time ago and added it from memory. Only checking whether I cought the issues I was thinking of.

I have clarified the intent in a new revision.

2020-03-15 10:26 UTC, SyrupThinker commented on proposals/2461-authenticated-content-repository-api.md
> +| m.cached | Only cached content can be accessed unauthenticated |
Replying to the first part of the question, as the latter is unrelated as clarified elsewhere.
This is based on Mathew's comment in synapse#2133.
One possible use case for `m.cached` is that a server admin knows that all users are responsible and allows content that they accessed (and then for exampled didn't report) to be accessed by older clients and to be directly linked to for bridges or download links.

2020-03-15 10:34 UTC, SyrupThinker commented on proposals/2461-authenticated-content-repository-api.md
> +| m.local | Only content with an authority the server is responsible for can be accessed unauthenticated |
See other comment.
Does the new context clarify the meaning of this?
Because to me it is phrased very clearly.

2020-03-21 10:15 UTC, helaan commented
I've read this MSC and I think I've found a few issues related to the modes and interactions between them.

- If the mode used is `m.local`, authentication is needed for cached content. This does not restrict access, as they are still available from the origin homeserver. It only prevents others sapping bandwidth.
- If the mode used is `m.cached`, local media needs authentication. This means that everyone who can authenticate with that server can get the media. So if another server can authenticate with this server, it can cache the media and then possibly send it out unauthenticated unless it has mode `m.local` or `m.none`.
- If the mode used is `m.none`, servers are not allowed to cache the content and as I don't see a way for users to authenticate with a different homeserver (nor do I think that is desireable), media sent by users of that homeserver cannot be viewed by users on other homeservers.
- `m.unspecified` is unclear to me, `null/missing` is the status quo.

Please correct me if I'm wrong. I'm not well versed in the Matrix protocol, so I'm probably wrong.

2020-03-21 12:31 UTC, SyrupThinker commented on proposals/2461-authenticated-content-repository-api.md
> +The following behaviours are defined:
Threaded discussions are preferred @helaan
- `m.local` Correct, it also allows compliance with local regulations regarding the possession and distribution of illegal content.
- `m.cached` Not quite, if the server already fetched the content (or it originated on this server), unauthenticated users can access it. Maybe `m.stored` is less confusing?
- `m.none` and `null / missing` Exactly.
- `m.unspecified` The server could use different criteria to allow access to content, that are not covered by this document.
This is basically the fallback case of "you need to check to know whether you can access something".
One might also call it arbitrary, but I didn't want the connotation of 
it never being consistent.

An unpublished version contained "Each entry in the following table is a subset of the preceding ones, with `m.unspecified` not fitting into this hierarchy".

2020-03-21 13:18 UTC, helaan commented on proposals/2461-authenticated-content-repository-api.md
> +The following behaviours are defined:
Ah, I'll switch to threaded replies then.

> An unpublished version contained "Each entry in the following table is a subset of the preceding ones, with m.unspecified not fitting into this hierarchy".
That makes it a lot clearer, I did not pick up on `m.cached` being comparable to `m.local`.

About `m.none`: Maybe state more clearly that this is only possible on unfederated servers?

What do you think will be the mode that servers in the public federation will use when this MSC is implemented and it is worth it to have it flexible? Personally, I think federated servers will switch to `m.local` and unfederated servers will just use `m.none`. Wouldn't this be simpler and as effective to have this setting depend on whether or not you have federation enabled or am I underestimating the importance of old client support?

2020-03-21 14:39 UTC, SyrupThinker commented on proposals/2461-authenticated-content-repository-api.md
> +The following behaviours are defined:
In my opinion `m.none` is not just possible on unfederated servers. Having `m.none` as the default for unfederated servers seems sensible, but concluding that when a server federates it will always have an accessible content repo is wrong. An admin might just not want to distribute through the media endpoints regardless.

I agree `m.local` would be the most common case for federated servers.

Especially `m.cached` gives nice properties like explained in the MSC. Although that could be cut and signaled through `m.unspecified`, loosing the benefit of clients knowing they can link to the content directly.

Having `m.unspecified` forces client and server authors to think about the possibility of rejection, something that some current clients don't do. It empowers admins to have a different rule set without clients failing when they make assumptions for the other cases.
Maybe this should be replaced or amended with "When an unknown value is encountered a client should account for the possibility of rejection".

Preserving compatibility with older clients is also a choice admins should make.
Explicitly supporting the old behavior allows this.


If I were to create the simplest form of this proposal it would just state.
> All unauthenticated accesses to media endpoints may be rejected for any reason

2020-03-27 01:12 UTC, turt2live commented on proposals/2461-authenticated-content-repository-api.md
> +## Alternatives
This will need a section comparing it to [MSC701](https://github.com/matrix-org/matrix-doc/issues/701)

2020-03-27 01:13 UTC, turt2live commented on proposals/2461-authenticated-content-repository-api.md
> +the field m.media.unauthenticated is added to
generally we should be naming things in the positive:
```suggestion
the field m.media.authenticated is added to
```

2020-03-27 01:14 UTC, turt2live commented on proposals/2461-authenticated-content-repository-api.md
> +the configuration should first be retrieved and cached.
There is no federation API for this.

2020-03-27 01:15 UTC, turt2live commented on proposals/2461-authenticated-content-repository-api.md
> +value other than null, older clients will not be able to access some content.
Not only older clients, but many desktop clients will have a hard time accessing images now. Some of the toolkits people use don't allow them to add headers before the request, so they'd need to add special code for this to buffer the media ahead of time.

This isn't a problem we need to fix in the MSC though, just something to be aware of.

2020-03-27 01:17 UTC, turt2live commented on proposals/2461-authenticated-content-repository-api.md
> +The following behaviours are defined:
I'd generally just recommend we have it turned on for the client-server API regardless. There's nothing stopping a server from accepting lack of auth, and realistically the spec should fix the general case of media being locked down.

2020-03-27 01:18 UTC, turt2live commented on proposals/2461-authenticated-content-repository-api.md
> +## Potential issues
Also mentioned in MSC701 (I think, I'm going off memory) is a way to solve the authentication issue without potentially leaking your access token. Clients which have 'download this file' or 'open in new tab' buttons will need to pass along the access token via the query string. In doing so, when someone copies the link and pastes it to someone else they've exposed their account.

2020-03-28 12:56 UTC, SyrupThinker commented on proposals/2461-authenticated-content-repository-api.md
> +the configuration should first be retrieved and cached.
I figured that because the servers use the client API for media downloads they could also  it for the media config endpoint

2020-03-28 13:27 UTC, SyrupThinker commented on proposals/2461-authenticated-content-repository-api.md
> +the field m.media.unauthenticated is added to
This would lead to the inverted enum values `m.non-local` and `m.uncached`
which are in my opinion worse than having the field name in the negative.

I'm open to suggestions for better enum names

2020-03-28 14:10 UTC, SyrupThinker commented on proposals/2461-authenticated-content-repository-api.md
> +## Potential issues
I really try to stay away from crypto, so this is just a naive simplification of MSC701:

The authentication token is created through HMAC(access_token, media_id).
This way only the media download can be replayed.
I'm not sure how the HMAC would be verified, but that'd need to be solved for MSC701 too.

2020-03-28 19:49 UTC, turt2live commented on proposals/2461-authenticated-content-repository-api.md
> +the field m.media.unauthenticated is added to
tbh when I was leaving this comment I was expecting it to be a boolean, not an enum. Not sure there's a benefit for having it be an enum at all, or even really needing this flag is needed.

2020-03-28 19:50 UTC, turt2live commented on proposals/2461-authenticated-content-repository-api.md
> +the configuration should first be retrieved and cached.
They cannot. Also they aren't supposed to be using the client endpoints, they just haven't been defined correctly in the server-side endpoints.

2020-03-28 21:03 UTC, SyrupThinker commented on proposals/2461-authenticated-content-repository-api.md
> +the field m.media.unauthenticated is added to
Well, that depends on whether servers can actually make use of that value (according to you they should not) and whether its considered useful enough for clients (as noted in the MSC).

If those are not considered useful then all that stuff can be thrown out.

2020-03-28 21:03 UTC, SyrupThinker commented on proposals/2461-authenticated-content-repository-api.md
> +the configuration should first be retrieved and cached.
Then this proposal is the time to specify that I'd say. Sharing federating media will be hard.

2021-04-19 12:21 UTC, ShadowJonathan requested changes
I like this idea, but I think it has a fatal flaw and confusion with `m.none` that i'd like to see resolved first.

2021-04-19 12:21 UTC, ShadowJonathan commented on proposals/2461-authenticated-content-repository-api.md
> +| null / missing | All content can be accessed unauthenticated                                                  |
I'm seeing `m.none` mentioned below, should that one be added here? Or what's the status on that?

2021-04-19 12:21 UTC, ShadowJonathan commented on proposals/2461-authenticated-content-repository-api.md
> +When the value is m.none the server should not attempt to fetch the
Does `m.none` effectively mean "All content here is non-accessible to other servers"? that breaks quite a lot of assumptions in matrix, where f.i. someone setting a room avatar in a federated room can suddenly "not display" that avatar simply because the server does not allow federated propagation of that file, per server-wide rules.

2021-04-19 14:50 UTC, SyrupThinker commented on proposals/2461-authenticated-content-repository-api.md
> +| null / missing | All content can be accessed unauthenticated                                                  |
`null` should actually be `m.none` here, thanks for pointing that out.

2021-04-19 15:06 UTC, SyrupThinker commented on proposals/2461-authenticated-content-repository-api.md
> +When the value is m.none the server should not attempt to fetch the
I assume my other comment clears the first part up, but `m.none` actually means *no restrictions*, as in the current behaviour. `m.all` would actually be the behaviour you describe, as in *everything is restricted*.

For the latter, yes, that is an expected consequence of this proposal.
I'd expect a user to be made aware by server owners if such media restrictions are in place.

2021-04-19 15:22 UTC, SyrupThinker commented on proposals/2461-authenticated-content-repository-api.md
> +The following behaviours are defined:
Such a change should only happen after some server-server API is in place though, right?
Otherwise media couldn't be fetched from a strictly conforming server.

2021-04-19 16:49 UTC, ShadowJonathan commented on proposals/2461-authenticated-content-repository-api.md
> +When the value is m.none the server should not attempt to fetch the
"restricted" as in "can only be accessed once authenticated"? And that any server over federation can request such media in an authenticated user's stead?

2021-04-19 16:53 UTC, ShadowJonathan commented on proposals/2461-authenticated-content-repository-api.md
> +the configuration should first be retrieved and cached.
Maybe the "federation api" could be an extra query parameter on existing download/thumbnail endpoints, which can be as simple as `authed=yes/no`? Of course, servers would need to also authenticate that it is another *server* that is requesting such media, and not someone else.

2024-04-23 03:12 UTC, turt2live commented
@SyrupThinker Thanks for opening this MSC! We've been considering authentication for quite a while, and really appreciate efforts to fix this particular area of the protocol. Lately we've been working on https://github.com/matrix-org/matrix-spec-proposals/pull/3916 as a way forward to authentication, and are currently gearing up for acceptance on it. 

If there's something we haven't yet considered in MSC3916 that you think we should, let us know. It's our current proposal to close this MSC in favour of MSC3916.

2024-05-14 18:51 UTC, turt2live commented
I'm assuming that lack of response means the author has disappeared :(

With MSC3916 entering proposed-merge FCP, I'm proposing that this MSC be rejected:

@mscbot fcp reject

2024-05-14 18:51 UTC, turt2live commented
@mscbot fcp close

2024-05-14 19:56 UTC, SyrupThinker commented
> @SyrupThinker Thanks for opening this MSC! We've been considering authentication for quite a while, and really appreciate efforts to fix this particular area of the protocol. Lately we've been working on https://github.com/matrix-org/matrix-spec-proposals/pull/3916 as a way forward to authentication, and are currently gearing up for acceptance on it.

> If there's something we haven't yet considered in [MSC3916](https://github.com/matrix-org/matrix-doc/pull/3916) that you think we should, let us know. It's our current proposal to close this MSC in favour of [MSC3916](https://github.com/matrix-org/matrix-doc/pull/3916).

> I'm assuming that lack of response means the author has disappeared :(
> 
> With [MSC3916](https://github.com/matrix-org/matrix-doc/pull/3916) entering proposed-merge FCP, I'm proposing that this MSC be rejected:

Apologies for the lack of reply, I have only now been aware of activity on this PR.

Glancing at MSC3916 I believe the concerns bringing about this proposal are acknowledged and taken into account. I don't think I have further insight as I have not been following recent Matrix development.

Thank you for working out a solution to this :)

2024-05-14 20:30 UTC, turt2live commented
Great to hear we've addressed things on a cursory glance, and thanks for taking a look!

This MSC is currently set on a closure path which requires fairly heavy review from the SCT. If you prefer, we can close this MSC in favour of MSC3916, shortcutting a lot of the feedback steps.

2024-05-15 06:39 UTC, SyrupThinker commented
Yes, let's close this one in favor of MSC3916.

2024-05-15 16:12 UTC, turt2live commented
@mscbot fcp cancel

2024-05-15 16:12 UTC, closed without merging