MSCxxxx: Annotations and reactions
matrix-org/matrix-spec-proposals pull request #2677
Opened 2020-07-07 20:21 UTC by uhoreg

2020-07-07 21:26 UTC, uhoreg commented on proposals/2677-reactions.md
> +What happens when you react to an edit?
In the thread at https://github.com/matrix-org/matrix-doc/pull/1849/files#r308722176:

bwindels says:

> There is some discussion on [vector-im/riot-web#10136 (comment)](https://github.com/vector-im/riot-web/issues/10136#issuecomment-508036441) about this, with the TL;DR being the intention for:
> 
>     * sending reactions to target the edit, not the message
> 
>     * clients' checking edits for reactions to display
> 
>     * servers have to look for reactions on edits when bundling
> 
> 
> If clients don't do this in a consistent way edits might be shown in one client but not in another, so we might want to spec this, or even enforce it server-side.

ara4n says:

> this section is trying to spec it consistently: reactions are strictly per edit, and you don't bundle them together. it sounds like we're not aligned though; for me, edits should effectively delete/replace reactions.

auscompgeek says:

> On other messaging services that have both reactions and edits that I've seen, editing a message doesn't remove the reactions, so such behaviour may be surprising to those moving away from other platforms. It would be good to have consistency though.

bwindels says:

> > this section is trying to spec it consistently: reactions are strictly per edit, and you don't bundle them together. it sounds like we're not aligned though; for me, edits should effectively delete/replace reactions.
> 
> Right, I think there are 3 questions that could be further clarified below:
> 
>     * Is reacting to an original event that got edited allowed (either by spec or server)? The language below doesn't say but seems to imply so. If it is, this can give inconsistent results between clients w.r.t. which reactions are displayed for edited events.
> 
>     * Should clients ignore reactions on the original edited event?
> 
>     * How is deleting/replacing reactions achieved? By clients ignoring reactions on anything but the last edit?
> 
> 
> The linked riot ticket is proposing, for edited events, to have a client indeed _always_ react to the latest edit the client is aware of when reacting, and also only take reactions on the last edit into account for displaying. Hence, reactions to previous edits will still exist (but indeed not be bundled by the server anymore), but be ignored by clients once they receive the new edit.
> 
> If this is the way we want to go, we might want to spec it in greater detail to help clients be consistent.
> 
> One could also contemplate returning an error when trying to react to an original edited event or any of its edits but the last one.
> 
> Riot doesn't do any of this yet btw, just always reacts to the original event for now.

ara4n says:

> Okay. i agree with auscompgeek's point that other services don't reset reactions when you edit - i guess people assume that the scope for abuse (you say "matrix rocks"; get 400 likes; then replace it with "matrix sucks") is mitigated by the fact that readers can check the message history to see what reactions happened when.
> 
> In which case, I think the simpler approach might be to just go and apply the reactions to the original message and ignore those on edits, i.e. the behaviour we have today? Rather than aggregating the reactions over all the edits.
> 
> erikjohnston wdyt?

2020-07-08 06:22 UTC, auscompgeek commented on proposals/2677-reactions.md
> +  * ...but anything else may not be rendered.
It should be noted that Slack and Discord allow for reacting to member events too. Whilst at the protocol level these could be faithfully bridged, it'd suck if they didn't show up in the UI.

2020-08-17 15:11 UTC, babolivier commented on proposals/2677-reactions.md
> +  XXX: is this implemented in Synapse yet?
A quick search through the code tells me it isn't.

2021-01-17 06:20 UTC, chc4 commented
Is this the Matrix spec proposal that is currently implemented by Element (and Synapse?) for their reactions? Did they actually implement it already without reactions being standardized, or is there some other message type I'm missing?

2021-01-17 10:38 UTC, tulir commented
Yes. Proposals have to be proven to work with an implementation before they can be accepted, otherwise we'd end up with lots of fancy specs with no idea if they're going to work in the real world.

This proposal is a bit old (the original version, #1849, is from early 2019), which is why the event type is `m.reaction` instead of using an unstable prefix like `org.matrix.msc1849.reaction`. PoC implementations of newer proposals will use unstable prefixes as per #2324.

2021-01-17 22:29 UTC, chc4 commented
Huh, ok. I understand the reasoning, but having the reference client and reference server implement non-standardized parts of the Matrix spec is a pretty bad look.

2021-01-18 10:51 UTC, Cadair commented
That's why #2324 was agreed upon so there is a clear line between the spec and implementations being ahead of the released spec. All projects like this grow organically, sometimes you just need to learn from your missteps.

2021-02-22 16:51 UTC, ShadowJonathan commented
was brought up again in a matrix channel, how is it that this MSC isn't FCPd yet?

2021-03-11 10:16 UTC, erkinalp commented on proposals/2677-reactions.md
> +variation-16 when applicable.
```suggestion
The reactions are not limited to emoji and clients should be designed to also accept
non-emoji reactions. When sending emoji reactions, the `key` field should include
the colourful variation-16 when applicable.
```

2021-03-11 10:17 UTC, erkinalp commented on proposals/2677-reactions.md
> +   useful with it.
```suggestion
 * Yes, reactions to reactions should be treated similarly to replies to replies.
```

2021-03-11 10:18 UTC, erkinalp commented on proposals/2677-reactions.md
> +  * ...but anything else may not be rendered.
Discord only allows reacting to joins and boosts, not leaves, kicks or bans.

2021-03-11 10:18 UTC, erkinalp requested changes
Reactions of reactions and arbitrary text reactions

2021-03-11 10:23 UTC, tulir commented on proposals/2677-reactions.md
> +   useful with it.
That makes no sense, replies are rendered in a completely different way

2021-03-11 10:40 UTC, erkinalp commented on proposals/2677-reactions.md
> +   useful with it.
Does it make sense now?

2021-06-02 21:39 UTC, uhoreg commented on proposals/2677-reactions.md
> +variation-16 when applicable.
I think that "When sending emoji reactions" already implies that reactions aren't limited to emoji.  However, it is probably worth putting in the "Security considerations" section that clients should display very long reactions sensibly.

2021-06-02 21:44 UTC, uhoreg commented on proposals/2677-reactions.md
> +   useful with it.
It looks like the consensus is that we don't want to tell clients to render reactions to reactions.

2021-06-02 21:45 UTC, uhoreg commented on proposals/2677-reactions.md
> +  * ...but anything else may not be rendered.
what's a "boost"?

2021-06-02 21:52 UTC, deepbluev7 commented on proposals/2677-reactions.md
> +  * ...but anything else may not be rendered.
It is some kind of payment for the community to unlock extra features. https://support.discord.com/hc/en-us/articles/360028038352-Server-Boosting-#h_9dfb44db-c394-4339-863b-e6d1e3fb0469 has a picture of how this looks like. It is basically like a notification in the room timeline.

2021-06-03 08:05 UTC, erkinalp commented on proposals/2677-reactions.md
> +manner. For example, clients can elide overly-long reactions.
```suggestion
manner.
```

2021-07-01 13:59 UTC, bwindels commented on proposals/2677-reactions.md
> +events together based on their `key` and `type` and returns a `count`.  Another
we should not group by type as that would mean that server-side aggregations of annotations would need the unencrypted event type.

2021-07-01 14:01 UTC, bwindels commented on proposals/2677-reactions.md
> +## Edge Cases
mention this from MSC 2674:
>  * Replying to a reaction should be treated like a normal message and have the
   reply behaviour ignored.

2021-07-05 15:39 UTC, bwindels commented on proposals/2677-reactions.md
> +manner. For example, clients can elide overly-long reactions.
This does not prevent arbitrary text reactions, but IMO suggests a good (albeit somewhat vague) balance between abusively long text reactions taking up too much screen real estate and allowing any text as a reaction. I'd be inclined to leave it in.

2021-07-08 08:43 UTC, bwindels commented on proposals/2677-reactions.md
> +events together based on their `key` and `type` and returns a `count`.  Another
Have made changes to reflect this concern

2021-07-08 10:38 UTC, tulir commented on proposals/2677-reactions.md
> +to a message.
Is there some plan for encrypted reactions? Right now the event type is `m.reaction` even in encrypted rooms.

Using `m.annotation` as the relation type to make it generic, only to ignore event types completely and treat all annotations as reactions feels wrong.

2021-07-08 11:21 UTC, bwindels commented on proposals/2677-reactions.md
> +to a message.
> Is there some plan for encrypted reactions? Right now the event type is `m.reaction` even in encrypted rooms.

There is https://github.com/matrix-org/matrix-doc/blob/matthew/msc1849/proposals/1849-aggregations.md#thoughts-on-encrypting-the-aggregation-key, but still very much up in the air.

It's true that `m.reaction` events are sent unencrypted today by many if not all clients. The proposal linked above provides for both though.

> Using `m.annotation` as the relation type to make it generic, only to ignore event types completely and treat all annotations as reactions feels wrong.

Personally, I don't see much value in the event type of an annotation event from the relation point of view. I don't think there is any compelling use case where you wouldn't want a count per key on the target event. For end-to-end encrypted rooms, it seems to me we have 3 options:
 1. send `m.reaction` unencrypted, as is done today by many clients. It's true that this is not much of an information leak, as `rel_type: "m.annotation"` means `type: "m.reaction"` in 99.9% of the cases, and `m.reaction` events don't contain anything but their relation and their type, so encryption brings little benefit here. I'm not sure that we should assume this to be the case for all events that add an annotation though.
 For example a bot could share the result of an operation within the encrypted content, and an annotation with a checkmark to the event that started the operation. You could argue that two events would do the job just fine here, although this atomicity of sending one event for all UI updates wanted by the bot could be nice.
 1. somehow provide the event type to the server while still encrypting the rest of the event. Special-casing `type` in how encryption is performed feels wrong to me, for no apparent benefit.
 1. only group by `key` and not `type`. This is perhaps not ideal either, but feels a lot less wrong to me than option 2, and again, there is no compelling use case for this.

Also, note that `m.relates_to` is already defined to be sent unencrypted by MSC 2675.

Again, none of these options seem catastrophic, but 3 seems like the simplest and most pragmatic one to me.

2021-07-08 11:22 UTC, bwindels commented on proposals/2677-reactions.md
> +to a message.
It might make sense to suggest in this MSC that `m.reaction` can be sent unencrypted as there is no benefit, but that other annotation events with more sensitive content should be encrypted.

2021-07-08 14:28 UTC, bwindels commented on proposals/2677-reactions.md
> +to a message.
> Using `m.annotation` as the relation type to make it generic, only to ignore event types completely and treat all annotations as reactions feels wrong.

I see what you're saying here btw, `m.reaction` would have been a better `rel_type` than `m.annotation` and prevent some confusion, but I'd like to document the current state with this MSC before making any changes.

2021-07-09 19:53 UTC, kevincox commented on proposals/2677-reactions.md
> +to a message.
Are we talking about encryption the reaction character itself, or the fact that a reaction occurred? If it is the character itself I strongly disagree with the notion that "there is no benefit". You can learn a lot about a conversation based on the reactions used and they should be as secure as possible.

How much downside is there to not aggregating reactions. In almost all cases I have seen <1k reactions. This is not a trivial amount but shouldn't be a major concern. I would much rather have good security than a slightly more efficient protocol for rare events.

2021-07-30 05:19 UTC, alphapapa commented
Apologies if this is the wrong place for this:

It would be helpful if guidance were given to client developers about how to guide users in sending reactions.  For example, in Element, there's a button to click to select an emoji, and users can also input them by typing certain strings wrapped in `:`, like `:heart:`.  

But in my client, what choices should I offer users?  Is there a list of acceptable keys?  Is *any* string allowed?  Is there a standard mapping between emojis and their `:`-wrapped aliases?  Is each client developer expected to research this and reimplement the functionality?  Are there any interoperability concerns between clients?

Thanks.

2021-08-01 19:08 UTC, ShadowJonathan commented
@alphapapa I believe such questions are better answered in `#matrix-dev:matrix.org`

2021-08-01 21:08 UTC, alphapapa commented
@ShadowJonathan It would be helpful if these questions were answered by the spec for client devs to refer to, like the guidance the spec gives regarding other client issues.  That is the purpose of the spec, no?

2021-08-01 21:15 UTC, ShadowJonathan commented
@alphapapa this is off-topic to the MSC at hand, please open an issue or talk in that channel, `#matrix-spec:matrix.org` is also relevant.

2021-08-03 06:00 UTC, alphapapa commented
@ShadowJonathan I don't understand.  I'm commenting on this proposed change to the spec, to ask that it include answers to certain questions for client developers, which it currently doesn't.  How is that off-topic?

2021-08-03 11:20 UTC, ShadowJonathan commented
@alphapapa it is off-topic to this current MSC, which is only related to the technical aspect of replies, reactions, and anything else this might empower. Please file a separate issue for what you're suggesting.

2021-08-03 18:15 UTC, uhoreg commented
@alphapapa please add comments on the document (which allows threading), rather than comments here, as it's easier to follow.  But the quick answers to your questions are that any string is allowed as the `key`, and mapping human-readable names to emoji is out of scope for this MSC.

2021-09-07 04:03 UTC, turt2live commented on proposals/2677-reactions.md
> +  XXX: is the example correct?
I don't think it is, or the text above it is wrong. The example demonstrates that the original event `type` is lost, which is important to have for dual-purpose aggregations as noted by [this thread on polls](https://github.com/matrix-org/matrix-doc/pull/3381/files#r703159699).

The text above references the event `type` though, giving hope that maybe it'll be supported one day.

2021-11-23 18:14 UTC, dbkr commented on proposals/2677-reactions.md
> +is intended primarily for handling emoji reactions, these lets you define an
```suggestion
is intended primarily for handling emoji reactions, these let you define an
```

2021-11-30 10:08 UTC, bwindels commented
The CS API should not allow to send a relation targetting a `m.annotation` event, as discussed at https://github.com/matrix-org/matrix-doc/pull/2675#discussion_r757010873

2022-01-01 12:08 UTC, tulir commented on proposals/2677-reactions.md
> +variation-16 when applicable.
I think the "when applicable" should be defined a bit more precisely. It took me a while to find [emoji-variation-sequences.txt](https://www.unicode.org/Public/14.0.0/ucd/emoji/emoji-variation-sequences.txt) ([HTML version](https://unicode.org/emoji/charts/emoji-variants.html)) from the Unicode spec to match what Element web (emojibase) does.

Another potential interpretation is using the "fully-qualified" variant from https://unicode.org/Public/emoji/14.0/emoji-test.txt, but that results in a much smaller set of emoji with the variation selector (and that's not what element does)

2022-03-03 18:47 UTC, clokep commented on proposals/2677-reactions.md
> +                "limited": false,
The intention of the `limited` here I assume is to support pagination (via the `/aggregations` endpoint), but that endpoint was removed from MSC2675, so is undefined.

I'm not sure it is particularly useful, but if it is we should redefine it in this MSC (or another one).

2022-03-13 08:08 UTC, zecakeh commented on proposals/2677-reactions.md
> +                      "count": 3
Having a `current_user_participated` flag would probably be useful as clients usually provide a visual hint for that. It's also useful for the client to know if, when the user activates this reaction, it should send a new reaction or if it should query the server to get the `event_id` to send a redaction.

2022-03-24 17:28 UTC, turt2live commented on proposals/2677-reactions.md
> +# MSC2677: Annotations and Reactions
This MSC and reality have diverged quite a bit, to the point of this MSC referencing design decisions we've since reverted or outright never implemented. 

A rewrite of this MSC to reflect reality and the current implementation desirables would be good, as much of the feedback here seems to mostly be confusion with the present day not matching the description.

2022-04-09 17:45 UTC, alphapapa commented on proposals/2677-reactions.md
> +# MSC2677: Annotations and Reactions
Agreed.  As a simple client developer, I'm surprised that this still isn't officially in-spec yet.  I'm now trying to figure out how to deal with m.reactions in initial sync, which seem to be appearing in some events' unsigned data rather than as separate m.annotation or m.reaction events.  It's not easy to keep up with things that aren't in spec yet.

2022-05-23 17:12 UTC, richvdh commented on proposals/2677-reactions.md
> +```
this duplicates msc2153, and I have proposed closing MSC2153 accordingly.

2022-05-23 17:13 UTC, richvdh commented on proposals/2677-reactions.md
> +    ]
I don't think we should be propagating the errors of the past (see https://github.com/matrix-org/matrix-spec/issues/643):

```suggestion
    "actions": []
```

2022-06-03 07:49 UTC, revidee commented on proposals/2677-reactions.md
> +                      "count": 3
I second that. With that, a client could get closer to the Element-UI, without having to fetch all reactions.
Alternatively, one could add filter-by-sender-id to the `/aggregations` or `/relations` endpoint in order to query this field manually.

However, redactions still make server-side aggregations pretty useless.

The benefit of not having to query all m.reactions events due to server-side aggregations is diminished by the fact that redactions on non-received reactions cannot be related to the a) event they reply to and b) the key this event incremented and since it is redacted now needs to be decremented. This strictly enforces the client to have **all** reactions events locally saved and only doing client-side aggregation, since after a redaction happened, we cannot even know which event to re-query the relations/aggregations for.

Honestly, I don't see the benefit of even including the server-side aggregation at this current state, since this case cannot be covered currently (as far as I can see). What's the point of having this feature, if the client still has to fetch all events and aggregate everything locally in order to guarantee consistency of reaction counts?

2022-09-03 14:03 UTC, HarHarLinks commented on proposals/2677-reactions.md
> +to a message.
> In almost all cases I have seen <1k reactions. 

Realistically, rooms with more than a couple dozen participants wouldn't be encrypted, hence we can assume there are only ever small-ish amounts of reactions if encrypted?

2023-02-14 17:02 UTC, richvdh commented on proposals/2677-reactions.md
> +    ]
Removed from synapse in https://github.com/matrix-org/synapse/pull/15073

2023-02-14 17:03 UTC, richvdh commented on proposals/2677-reactions.md
> +# MSC2677: Annotations and Reactions
I'm taking over this MSC and am going to attempt to knock it into a shape where it can be merged.

2023-02-14 19:04 UTC, richvdh commented on proposals/2677-reactions.md
> + 4. XXX: does synapse do 2 & 3 yet?
for the record, it does 2, but not 3. 3 is left for the clients to do; clarified in dad2b07d.

2023-02-14 21:27 UTC, richvdh commented on proposals/2677-reactions.md
> +        "annotation_count": 1234,
I've now clarified (in dad2b07d) that redacted reactions are not counted as part of the aggregation, on either the server or client side.

2023-02-14 21:29 UTC, richvdh commented on proposals/2677-reactions.md
> +What happens when you react to an edit?
> In which case, I think the simpler approach might be to just go and apply the reactions to the original message and ignore those on edits, i.e. the behaviour we have today? Rather than aggregating the reactions over all the edits.

This seems to be what happened in the end. Clarified in dad2b07d.

2023-02-14 21:33 UTC, richvdh commented on proposals/2677-reactions.md
> +  * ...but anything else may not be rendered.
currently, Element-Web doesn't show reactions to member events, and they don't get counted on the server side because state events don't received bundled aggregations. It's less than ideal, but it's the way it currently is.

Clarified in 4031ad42.

2023-02-14 21:36 UTC, richvdh commented on proposals/2677-reactions.md
> +  XXX: is this implemented in Synapse yet?
indeed. Evidently it hasn't been needed thus far! removed.

2023-02-14 21:40 UTC, richvdh commented on proposals/2677-reactions.md
> +## Edge Cases
Hopefully this is clarified in dad2b07d.

2023-02-14 21:41 UTC, richvdh commented on proposals/2677-reactions.md
> +to a message.
This isn't a thing we're going to resolve within this MSC; punting it to https://github.com/matrix-org/matrix-spec/issues/660.

2023-02-14 21:43 UTC, richvdh commented on proposals/2677-reactions.md
> +  XXX: is the example correct?
fixed in 657a7466.

2023-02-14 23:35 UTC, richvdh commented on proposals/2677-reactions.md
> +variation-16 when applicable.
clarified in c28c3855

2023-02-14 23:36 UTC, richvdh commented on proposals/2677-reactions.md
> +                "limited": false,
yes, this is now removed.

2023-02-14 23:37 UTC, richvdh commented on proposals/2677-reactions.md
> +                      "count": 3
> Having a `current_user_participated` flag like in threads would probably be useful as clients usually provide a visual hint for that.

True, but it's not currently implemented and I'm keen to focus this MSC on what we have currently. Extensions like this can go in a separate MSC.

2023-02-14 23:39 UTC, richvdh commented
I think this MSC now matches reality and is substantially clarified. Review would be appreciated.

2023-02-21 17:01 UTC, richvdh commented on proposals/2677-reactions.md
> +                      "count": 3
You have a very good point here. It might make more sense to rip out the reaction-aggregation altogether than to spec it in its current state.

I've asked in the [client developers room](https://matrix.to/#/#matrix-client-developers:matrix.org) but my impression is that most clients aren't currently use the aggregation, and that those that are wouldn't care if it went away.

I'll wait for more opinions before making a final decision here.

2023-02-22 06:36 UTC, turt2live approved these changes
This MSC matches my understanding for how reactions (annotations) work today, and appears to be well scoped to that specific case. 

Thank you for getting this (and all the other ancient relationships MSCs...) over the line, @richvdh

2023-02-22 06:36 UTC, turt2live commented
@mscbot fcp merge

2023-02-28 18:27 UTC, richvdh commented on proposals/2677-reactions.md
> +                      "count": 3
Decision made: nobody has objected to me ripping out support for reaction-aggregation. I have therefore made a PR to do so in Synapse (https://github.com/matrix-org/synapse/pull/15172) and will update this MSC accordingly.

2023-02-28 18:49 UTC, richvdh commented on proposals/2677-reactions.md
> +                      "count": 3
Done, in 749198f. Thanks @revidee for bringing this to my attention.

@turt2live please be advised that this is a substantial change since you gave your "ready for FCP" tick - you may wish to revisit.

2023-02-28 23:30 UTC, AndrewRyanChama requested changes
commented with concerns about the ability to display the correct reactions when seeking to an older message

2023-02-28 23:30 UTC, AndrewRyanChama commented on proposals/2677-reactions.md
> +`m.annotation` relationships are *not* [aggregated](https://spec.matrix.org/v1.6/client-server-api/#aggregations)
In current implementations, if a message is deeplinked or otherwise seeked to in history, then reactions made to that message long afterwards will not be displayed.  

I'm worried about possible parity issues with competing messaging apps, for example it's common for a pinned message or something to gather a gorillion or more reactions over a long time.  This MSC should provide a way so that particularly important messages in the past that are repeatedly referenced can still accurately display their reactions.

With the current api it might be possible to call /relations for a single message, but it's not practical to call this on all messages when paginating, because it will cause too many api calls, and there is no way to know which messages have reactions on them.

Possibly aggregation isn't the right solution here, but we need a way such that clients have a way to display the correct reactions in these cases.

2023-03-01 07:05 UTC, KitsuneRal commented on proposals/2677-reactions.md
> +`m.annotation` relationships are *not* [aggregated](https://spec.matrix.org/v1.6/client-server-api/#aggregations)
My take on it is that this is a problem specifically when paginating from a deeplinked message back or forth. Paginating back from the sync edge of the timeline is going to rake all reactions even before the related events; and I would probably be fine with explicitly calling `/relations` on pinned messages because normally there are not many of them, anyway. From the API standpoint that leaves `/context` and `/search`; as long as encrypting the fact of relationship is not on the cards, I'd probably rather explore getting reactions in the same way we get state events in those endpoints now.

2023-03-01 08:39 UTC, jplatte commented on proposals/2677-reactions.md
> +`m.annotation` relationships are *not* [aggregated](https://spec.matrix.org/v1.6/client-server-api/#aggregations)
I think a good trade-off here could be to aggregate reactions into a plain 'number of reactions' server-side. Then clients will know whether they have seen all reactions and can use `/relations` to fetch them, if they care.

I'd also be strongly in favor of then encrypting the "key" of the reaction, the same way the new content is encrypted for edits but the relation to the event being edited isn't, but maybe that should be its own thread.

2023-03-01 09:07 UTC, Alcaro commented on proposals/2677-reactions.md
> +`m.annotation` relationships are *not* [aggregated](https://spec.matrix.org/v1.6/client-server-api/#aggregations)
Doesn't that give weird results if someone removes a reaction? "20 reactions now, 20 reactions last time" proves nothing - Alice could've removed her thumb up and replaced with thumb down. Though "0 reactions now", which is true for 99% of messages, is usable information.

If you mean aggregating into "13 thumbs up, 7 thumbs down", that would be useful. Though if one of them is subsequently redacted, client won't know which type to decrement. (I'm not even sure if client knows which message was affected - if I'm reading the spec correctly, redactions only contain the ID of the redacted event, not which message that event is attached to.)

"13 thumbs up, 7 thumbs down" is also insufficient for clients who care about who reacted - Alice could've retracted her thumb up, and Bob added one instead - but that's also rare enough to ignore. Clients can just fetch the relations list for messages it cares about, which is presumably only a small number.

2023-03-01 09:09 UTC, dkasak commented on proposals/2677-reactions.md
> +`m.annotation` relationships are *not* [aggregated](https://spec.matrix.org/v1.6/client-server-api/#aggregations)
I think @jplatte has the right idea, but instead of making it the number of *reactions*, I think it should be number of *relations*. Then clients should fetch all relations whenever the event has relations (and they're interested in them). This gives us the opportunity to encrypt both the `key` and the `rel_type`, as described [here](https://github.com/matrix-org/matrix-spec/issues/660#issuecomment-1055940484). (I don't think it's reasonable to encrypt the event ID, so ignore that part.)

2023-03-01 09:12 UTC, jplatte commented on proposals/2677-reactions.md
> +`m.annotation` relationships are *not* [aggregated](https://spec.matrix.org/v1.6/client-server-api/#aggregations)
> Doesn't that give weird results if someone removes a reaction? "20 reactions now, 20 reactions last time" proves nothing

Wdym with "now" and "last time"? The client would only be seeing this one time when fetching the event, then if it cares about reactions, it will fetch all the reactions via `/relations`, and receive updates as additional (reaction / redaction) events.

2023-03-01 09:13 UTC, jplatte commented on proposals/2677-reactions.md
> +`m.annotation` relationships are *not* [aggregated](https://spec.matrix.org/v1.6/client-server-api/#aggregations)
@dkasak I like it!

2023-03-01 10:04 UTC, Alcaro commented on proposals/2677-reactions.md
> +`m.annotation` relationships are *not* [aggregated](https://spec.matrix.org/v1.6/client-server-api/#aggregations)
> Wdym with "now" and "last time"?

I'm considering the case where the client sees the same message multiple times, for example fetching the pins twice, or a large segment of recent channel history, and doesn't want to waste bandwidth on refetching unchanged reaction counts.

But it sounds like that's not the usecase you're optimizing for, so I apologize for the noise.

2023-03-01 10:53 UTC, richvdh commented on proposals/2677-reactions.md
> +`m.annotation` relationships are *not* [aggregated](https://spec.matrix.org/v1.6/client-server-api/#aggregations)
It's true that current implementations are "buggy" in the case of old messages with reactions the client hasn't seen, and the discussion of potential solutions is welcome.

However, I think I should reiterate the purpose of this MSC, as set out in its introduction:

> ... this MSC therefore seeks primarily to formalise the status quo. Although there is plenty of scope for improvement, we consider that better done in future MSCs, based on a shared understanding of the current implementation.

In other words, sorry, but we absolutely won't be redesigning reaction aggregations as part of this MSC. Trivial changes *are* within scope, and it turned out that ripping out the existing implementation was easy and made more sense than leaving it in, for the reasons discussed at https://github.com/matrix-org/matrix-spec-proposals/pull/2677#discussion_r1108487789. However anything else is going to need implementing and testing on both servers and clients and is just going to end up delaying this MSC yet again.

In other other words, the options for this MSC are (a) keep the aggregation as it was before https://github.com/matrix-org/matrix-spec-proposals/pull/2677/commits/749198fd4a9efa4dc8eb0565ad05746ffa70aa7f and https://github.com/matrix-org/synapse/pull/15172 or (b) rip it out. There is no (c).

2023-03-07 19:24 UTC, anoadragon453 approved these changes

2023-03-08 11:26 UTC, gnunicorn commented on proposals/2677-reactions.md
> +`m.annotation` relationships are *not* [aggregated](https://spec.matrix.org/v1.6/client-server-api/#aggregations)
Someone brought the question up the other day, whether the concepts (and even the implementation) of [GraphQL](https://spec.graphql.org/) isn't the better suited idea for the API (rather than plain old REST) now that we have relational data and clients, who want to pro-actively decide very granular which information they want. Just wanted to leave that here as a side-note ...

2023-03-26 23:18 UTC, merged

2023-04-25 18:08 UTC, turt2live commented
Merged 🎉