MSC2781: Deprecate the (reply) fallbacks in the Matrix specification
matrix-org/matrix-spec-proposals pull request #2781
Opened 2020-09-18 21:47 UTC by deepbluev7

Since I hit another fallback bug today, I thought I should finally propose this. Let's see, how this goes.

Signed-off-by: Nicolas Werner <nicolas.werner@hotmail.de>

2020-09-18 22:06 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +Seems unnecessary, since this only removes stuff.
An alternate event type or msgtype should be used to avoid confusing clients which rely on the fallback being present under the spec.

2020-09-18 22:15 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +Seems unnecessary, since this only removes stuff.
But then all clients would fail to render those events, while if you don't use any prefix, it would just look like the fallback is missing, because it is. I believe adding an unstable prefix would actually cause more issues, than it would solve? But if it is really necessary, I will add it of course, but I think this MSC is somewhat of a weird case. Basically you are saying all message types would need to be prefixed from a client implementing this MSC?

2020-09-18 22:17 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +Seems unnecessary, since this only removes stuff.
The point is that clients have to opt into the MSC's behaviour while the MSC is not included in the spec, so they need some way of doing it. It's not safe to assume that existing clients will be happy about the fallback being missing.

2020-09-18 22:18 UTC, Cadair commented on proposals/2781-down-with-the-fallbacks.md
> +Seems unnecessary, since this only removes stuff.
Surely changing the reply type of the replies is going to be even more of a breaking change?

2020-09-18 22:19 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +Seems unnecessary, since this only removes stuff.
The ***event type*** or ***message type*** - changing the reply type is not recommended.

2020-09-18 22:31 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +Seems unnecessary, since this only removes stuff.
In my opinion changing the msgtype or event type is even more of a breaking change than changing the content of `body` and `formatted_body`. I somehow doubt even half of the clients will render messages correctly in that case. On the other hand, if you just drop the fallback, in the worst case clients should treat the event as any other event, but from my testing no client actually broke, just old Riot/Android didn't show replies anymore. Changing the reply type is at least somewhat reasonable, since then this only affects replies and normal messages should still render as before. I guess there is no other MSC with namespacing yet, that removes a key and which could be used to compare the approach with?

2020-09-18 22:31 UTC, tulir commented on proposals/2781-down-with-the-fallbacks.md
> +Seems unnecessary, since this only removes stuff.
Are there really more clients that are confused by a lack of reply fallback than clients that are confused by unknown message types?

There's no way to avoid confusion altogether, so it should be minimized instead.

2020-09-18 22:34 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +Seems unnecessary, since this only removes stuff.
> In my opinion changing the msgtype or event type is even more of a breaking change than changing the content of body and formatted_body.

Honestly, this is the point of this section. The unstable prefix stuff only applies while the MSC is not in the spec. Once in the spec, clients are expected to follow suit with the change and the unstable prefix no longer needs to be used. Until then, clients *need* a way to opt into this.

It does not matter which clients appear to be unaffected by such a change - not all of them are visible, and it's against the spirit of the spec and process to force a change upon people they did not ask for.

2020-09-18 22:39 UTC, uhoreg commented on proposals/2781-down-with-the-fallbacks.md
> +Seems unnecessary, since this only removes stuff.
An unstable prefix is only needed if the proposal is implemented before it makes it into the spec.

But this raises an interesting point in how we would handle clients that do depend on the fallback being present.  Do we create a new room version and say that prior room versions have replies that include fallbacks, and future room versions don't?  Or do we say that this change applies everywhere, and if your client is now broken, then too bad.

On the other hand, I wonder how badly a client could break due to a lack of fallback.  Clients should handle spec violations in incoming messages gracefully -- if, for example, a client crashes when it receives a reply without a fallback, that would certainly be a security issue for the client.  The worst breakage that I can imagine that wouldn't be classified as a security issue is that the client just fails to render that one message entirely which, IMHO, doesn't sound that terrible (especially as I would be very surprised if any client did break, and if any did break, it would likely be a trivial fix).

2020-09-18 23:03 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +Seems unnecessary, since this only removes stuff.
> But this raises an interesting point in how we would handle clients that do depend on the fallback being present.

Since most clients ignore room versions, those clients that break on fallbacks probably also break, when this is only changed in a new room version. In my opinion any client that actually relies on the fallback being present, has issues anyway. Especially if you consider that, while the spec requires a fallback, it doesn't require you to use a specific fallback format. To quote:

> The formatted_body should use the following template:

"Should" is not a requirement. A client is free to use an empty string as the fallback, which is equal to no fallback, if I interpret the spec maliciously.

Stripping is specified similarly:

> To strip the fallback on the formatted_body, the client should remove the entirety of the mx-reply tag.

This does not specify, what the client should do, if the fallback does not contain an mx-reply tag, but removing something, that does not exist, should not cause issues, should it? ;p

The only thing actually required and what may break clients is the html requirement. Because the required fallback is not required to look different from an empty string.

But that's just me being cheeky, I guess...

2020-09-19 06:13 UTC, Sorunome commented on proposals/2781-down-with-the-fallbacks.md
> +Seems unnecessary, since this only removes stuff.
To add on, there are already some clients which don't send a reply fallback at all and most clients fetch the original event and render it just fine

2020-10-10 21:21 UTC, KitsuneRal approved these changes
I understand the controversy but I really think that fallbacks bring more problems (especially in terms of the content getting stuck in messages not belonging to authors) than solutions to those who try to stay as simple as possible. The requirement to strip the fallbacks in replies raises the bar of implementing them to the point where half of the ecosystem chooses not to deal with that. Besides, the fallbacks are a huge HTML foot in the door where plaintext messengers have literally no chance of compliance. So yes, please, let's go with it.

2020-10-10 21:21 UTC, KitsuneRal commented on proposals/2781-down-with-the-fallbacks.md
> +prefixed with a `*`, since that has been confusing to users in the past. Since
I'd say it's rather opinionated - I myself used to recognise `*` as a signifier of an edit pretty early when they started to show in payloads (and before I got to the rich replies MSC), and I know quite a few occasions outside of Matrix where prepending `*` conventionally (if not formally) meant a correction.

2020-10-10 21:21 UTC, KitsuneRal commented on proposals/2781-down-with-the-fallbacks.md
> +- Quaternion: [Blocked because of fallbacks](https://github.com/quotient-im/libQuotient/issues/245).
It's not exactly blocked - it's just that I have a fever every time I think of implementing all those stripping things. In fact, for HTML it's getting rather easy with the recent proceedings in Quaternion; but cutting parts of the plain texts is something my users are likely to be very vocal against, next to me. Also, it's worth noting that non-compliant replies (without fallbacks, i.e., "as if" this MSC has been merged) can be sent even with the current libQuotient version.

2020-10-10 21:21 UTC, KitsuneRal commented on proposals/2781-down-with-the-fallbacks.md
> +on `<mx-reply>` tags, so you need to strip them anyway to render replies.
I'm not sure where you're getting this from but Quaternion has been carrying showing replies for quite some time without any special code, so in a way it actually benefited from having the (HTML) fallback. With that said, I agree that downsides of having the replied to text verbatim in the replies outweigh the advantages of doing nothing in more basic clients. What could at least be done is leaving just the link to the previous reply (and "In reply to @mxid" in the plaintext fallback), so that only metadata from the replied to message are reused.

2020-10-10 21:34 UTC, KitsuneRal commented on proposals/2781-down-with-the-fallbacks.md
> +Seems unnecessary, since this only removes stuff.
Right, so basically clients already get tested on resilience to missing fallbacks simply by the fact that there are quite a few clients not sending fallbacks with the replies as of right now.

I'm not quite sure which kind of unknown we're trying to protect against here by namespacing such events (even tentatively) - but for now the clause is there so this thread can be resolved, I guess?

2020-10-10 21:39 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +prefixed with a `*`, since that has been confusing to users in the past. Since
I do agree, that it is opinionated, but as a Nheko dev, I do get questions about the "duplicated messages with a * in front of it" pretty often, so it certainly is not universally understood in my experience.

2020-10-10 21:42 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +on `<mx-reply>` tags, so you need to strip them anyway to render replies.
I remember having to strip the mx-reply tags, because otherwise either Nheko or my Sailfish client did not render messages with replies at all, but now that you mention it, it may have been caused somewhere else and it may not have been Qt, that was the issue. I'll probably remove that point or at least the "breaking Qt" reference.

2020-10-10 21:54 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +on `<mx-reply>` tags, so you need to strip them anyway to render replies.
Yes, I remembered it wrong, it was an unrelated issue, that happened with every reply fallback, but was just plain buggy code. I'll remove that part.

2021-10-17 06:03 UTC, aaronraimist commented
Implementation: https://github.com/matrix-org/matrix-react-sdk/pull/6964

2022-01-14 03:41 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +## Proposal
it's a little unfortunate that the proposal is 123 lines later - can we bump the proposal content up and (re)write the arguments from above to benefit the proposal rather than combat the issues themselves?

2022-01-14 03:41 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +# MSC2781: Deprecate fallbacks in the specification
```suggestion
# MSC2781: Deprecate edit & reply fallbacks in the specification
```

2022-01-14 03:41 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +Deprecate the rich reply fallback. Clients should stop sending them and should
Any particular reason to choose deprecation over removal? Typically we do require a deprecation first, but considering clients will have access to older versions of the specification and this doesn't affect endpoints (just events), I'd be inclined to just stop sending it entirely.

In limited testing, Element Web seems perfectly okay with this change. In effect, MSC3440 is already planning to use replies such that there is no fallback proposed but still using the reply key. 

This argument also applies to edits.

2022-01-14 03:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +## Appendix A: Clients not supporting rich replies
I suspect/hope this needs updating.

2022-01-14 03:44 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +Deprecate the rich reply fallback. Clients should stop sending them and should
No, there isn't really any, I just worded it badly. Removal probably explains the content of the proposal better.

2022-01-14 03:51 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +## Appendix A: Clients not supporting rich replies
Well, I at least need to add all the new clients, which might shift the balance, but otherwise I fear not by much.

2022-01-14 06:12 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +prefixed with a `*`, since that has been confusing to users in the past. Since
I removed the proposal for edits for now.

2022-01-14 06:17 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +## Proposal
I have moved the proposal up and tried to make the language for the issues a bit nicer, but I still kept it as a list of issues, because I think that is easier to understand. I'll see if I can work in the benefits of dropping the fallback into the proposal a bit more.

2022-01-14 06:18 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +## Appendix A: Clients not supporting rich replies
I did update it, but it seems to have gotten worse imo, but I appreciate that fractal merged support for rich replies a few hours ago at least!

2022-01-18 01:42 UTC, turt2live requested changes
Overall the MSC is fine tech-wise. I largely have concerns with how it has positioned itself, so have tried to correct for that with thought-provoking comments ;) 

Apologies if any of it comes across as overly harsh - intent is to reduce a bit of the stronger language in the proposal and replace it with wording that gets a similar idea across.

2022-01-18 01:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +double down on fallbacks.
MSC2589 does fallbacks differently - not sure it's fair to say it is "doubling down".

Also, it's closed in favour of this MSC so hopefully the vote of confidence it cast is reflected by this MSC :)

2022-01-18 01:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +Remove the rich reply fallback from the specification. Clients should stop
link to current spec please

2022-01-18 01:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +Matrix across all clients in the long term.
```suggestion
As a result of this, you would be able to reply with an image.  New clients
would also be able to implement edits and replies more easily, as they can
sidestep a lot of pitfalls. 

Given clients have had enough time to implement replies completely, the
overall look & feel of replies should be unchanged or even improved by this
proposal.
```

2022-01-18 01:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +events](https://github.com/matrix-org/matrix-doc/pull/3644).
This should be a comment thread on that MSC, not a statement in here.

2022-01-18 01:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +message now, similar to a redaction, and not merge `content` and `new_content`.~~
remove this if it's crossed out?

2022-01-18 01:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +marker to at least mark replies visually.
It might also be worthwhile to lean into the pressure that not supporting replies creates. Clients which haven't supported replies up until now might need a bit of a push :)

Users complaining about lost context is one way of doing that.

2022-01-18 01:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +format for relations anyway). We could specify, that the server is supposed to
"new format for relations" needs a link. Replies are unchanged even by the relationship MSCs, which means we have two relation formats.

2022-01-18 01:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +other cases this should **reduce** security issues.
This needs backing up with words - what sorts of security issues are mitigated?

2022-01-18 01:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +reply. Otherwise replies will just infinitely nest replies. [While the spec doesn't necessarily require that](https://github.com/matrix-org/matrix-doc/issues/1541),
wrong issue? That link is talking about doing an MSC2589 approach, not nested replies.

2022-01-18 01:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +to distinguish a quote from a reply reliably.
This is false. The spec outlines exactly how the plain text parsing and stripping works - this is easily distinguished between a reply and a quote.

Even if the first line of the reply is a quote, it is easily detected and accounted for under the spec's algorithm.

2022-01-18 01:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +edit. Currently this is solved by not sending a reply fallback in edits, so
replies and edits are able to co-exist under their relation formats.

2022-01-18 01:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +basis, especially for the fallback in `body`.
This section feels overly rant-y. The more likely story is that the fallback is complicated to get right and so clients end up implementing their own thing by accident, introducing inconsistencies. The `should` is a strong recommendation from the spec and clients don't really have a reason to deviate from it - so it is effectively a `must` until a proper use-case is defined that warrants a customized format.

2022-01-18 01:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +language selection for their client, which may be personal information.
This is going back to my last comment about how clients just got it wrong and have bugs.

2022-01-18 01:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +The above issues are minor, if reply fallbacks would sufficiend value to
```suggestion
The above issues are minor, if reply fallbacks added sufficient value to
```

2022-01-18 01:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +welcome to the IRC crowd.
Bridges are not required to be 1:1 mappings of Matrix messages, nor are they ever intended to be perfect mappings. IRC is not Matrix, so I don't think this argument is valid.

2022-01-18 01:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +    also drop it](https://github.com/matrix-org/matrix-doc/pull/3644).
MSC1767 isn't going to touch fallbacks or replies at all. That's 100% MSC3644's job.

2022-01-18 01:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +localized for the receiving party to understand it. This however proves to be a
The spec explicitly does not want it translated. This is a client bug.

2022-01-18 01:42 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +## Appendix A: Clients not supporting rich replies
Instead of listing the clients which don't support it, it might be best to show which clients are okay with this change on a technical level. For example, Element Web doesn't seem to care if the fallback is present or not, which is a good sign for this MSC's acceptance.

2022-01-19 01:50 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +to distinguish a quote from a reply reliably.
The algorithm is only reliable, if there is always a fallback in the message and especially not in the current version of the spec, since the new spec layout seems to strip spaces:

![image](https://user-images.githubusercontent.com/16312324/150047161-5bea96fe-dc33-4e32-b777-7d98a83bff82.png)

(from https://spec.matrix.org/v1.1/client-server-api/#fallback-for-mtext-mnotice-and-unrecognised-message-types)

There is no way to distinguish there if "this is the second line" is from the fallback or not. The proper algorithm is to check, if a message starts with `> <@` and then strip until the next empty line and always include an empty line after the fallback after sending the message. This is not explicit in the spec and failing to do so causes ambiguities.

Similarly for the formatted body, the spec only says this: `To strip the fallback on the formatted_body, the client should remove the entirety of the mx-reply tag.`

A client should actually strip using the regex `<mx-reply>.*</mx-reply>`, because otherwise there is a way for the sender of the original event to control the content of the replies to event by inserting a second `</mx-reply>` and an unmatched comment tag.

2022-01-19 01:57 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +edit. Currently this is solved by not sending a reply fallback in edits, so
This is at least not intended by the MSC according to my interpretation of the proposal text: https://github.com/matrix-org/matrix-doc/pull/2676/files#diff-1761bdadd1caacb2503d2b2e6c572fc628c7321b0beab8d502ac249c15b2826aR113

It explicitly talks about reference relations in the proposal (which were originally intended to replace the current replies by the author, I believe?) and it says there should be no fallback and it doesn't mention sending an `m.in_reply_to` in the edit. So if they can co-exist is probably something to be solved on that proposal, but according to my current reading, they can't or it is at least not intended.

2022-01-19 02:02 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +basis, especially for the fallback in `body`.
I have seen multiple deviations from that format already, where clients didn't use the mxid in the fallback, but the userid. Some clients translated the format, some always send the body in the fallback instead of "sent a file". Those events are sent by clients and do cause issues. I'm not sure how I should word that otherwise? I'll remove the first 1.5 sentences though.

2022-01-19 02:06 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +language selection for their client, which may be personal information.
Localizing the reply fallback is not trivial, so I think it makes sense to at least mention it.

2022-01-19 02:09 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +welcome to the IRC crowd.
The IRC bridge has often be mentioned to me as a good candidate for using the reply fallback. I wanted to preempt that comment thread on the MSC, because it is wrong.

2022-01-19 02:11 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +    also drop it](https://github.com/matrix-org/matrix-doc/pull/3644).
It might have been a little confusing, but I just wanted to link to what extensible events are, I'll see if I can make that clearer.

2022-01-19 02:25 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +## Appendix A: Clients not supporting rich replies
I've added a section on this now with the different clients I tested. I would also be surprised if any client breaks, because then this would have been abused in the wild for a while already.

2022-01-19 02:26 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +    also drop it](https://github.com/matrix-org/matrix-doc/pull/3644).
Is this now clearer?

2022-01-19 02:33 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +other cases this should **reduce** security issues.
I linked one of them, a few more are in the appendix B, although one could argue if they are security issues or just glitches.

2022-01-19 02:37 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +reply. Otherwise replies will just infinitely nest replies. [While the spec doesn't necessarily require that](https://github.com/matrix-org/matrix-doc/issues/1541),
I linked to the spec, that says only to strip the fallback when displaying a message now.

2022-01-19 04:16 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +to distinguish a quote from a reply reliably.
That screenshot is clearly a rendering fail from the new structure and not normative content.

https://github.com/matrix-org/matrix-doc/blob/6c4aabd05348a7fb7ed3135e79ea7013c3ac9297/content/client-server-api/modules/instant_messaging.md?plain=1#L359-L361

^ this is the representation. There must be a blank line between the fallback and the start of the message.

As for the HTML: the wording chosen by the spec is correct. It's asking to remove the tag, not the text. This is a very subtle difference which implies HTML parsing needs to take place before removing the tag contents. HTML parsers will take care of invalid structures.

2022-01-19 04:17 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +edit. Currently this is solved by not sending a reply fallback in edits, so
`m.replace` should be removed from the edits MSC as `m.replace` is its own MSC now, and in either case it's not this MSC's role to talk about edits - leave that to the edits MSC please.

2022-01-19 04:18 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +basis, especially for the fallback in `body`.
Rewording the section to talk about how complicated it is to get the fallback correct (by example of no one being consistent) feels more appropriate.

2022-01-19 04:19 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +language selection for their client, which may be personal information.
well, you're not meant to localize it :D 

It's a client bug if it is translated/localized.

2022-01-19 04:20 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +    also drop it](https://github.com/matrix-org/matrix-doc/pull/3644).
not really, but it's not my most major concern - resolving for now as the wording is at least different.

2022-01-19 04:26 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +welcome to the IRC crowd.
The IRC bridge is implementing a different kind of reply fallback though, so isn't supporting the argument of the paragraphs here.

2022-01-19 04:41 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +to distinguish a quote from a reply reliably.
The problem with html parsers applying before removing the tag, is that invalid tags don't get removed. So any client implementing that, can be fooled by mismatched `<mx-reply>` tags. I forget the exact exploit, but it allowed you to insert text into the replied to message by inserting additional, unmatched mx-reply tags, because html would autoclose them. So you had hidden text in the original message, that suddenly became visible in the reply someone sent.

But I guess you are right, the stripping issue for the body tag only applies, if someone does not send a reply fallback in body or there is a missing empty line. (As long as the spec rendered correctly for the user implementing it of course)

2022-01-19 04:44 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +welcome to the IRC crowd.
It supports the point, that the fallback isn't very useful, since you need to replace it anyway to have an experience, that users will accept (which is what the section is about).

2022-01-19 04:48 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +welcome to the IRC crowd.
That's not really clear to me - can those words be added? 😇

2022-01-19 04:49 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +welcome to the IRC crowd.
Sure, I removed them before, because they sounded mean.

2022-01-19 04:58 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +edit. Currently this is solved by not sending a reply fallback in edits, so
I moved this to a single sentence talking about the interaction with other MSCs now. I think having some reference to that issue is still valueable.

2022-01-19 04:58 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +welcome to the IRC crowd.
Added an extra sentence now.

2022-01-19 05:00 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +to distinguish a quote from a reply reliably.
Reworded the plain body stripping now to the common mistakes now, which all get solved, if you don't need to strip it. I also didn't mention, that the current spec renders the fallback in such a way, that it makes client implement it wrong. :3

2022-01-19 05:14 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +language selection for their client, which may be personal information.
Should I just add, that the requirement for not localizing the fallback was not enough to stop clients from doing so? Also, where exactly does the spec say that? Just because the requirement only has an English text, doesn't seem to be enough for a developer to understand, that it shouldn't be translated. But at least tulir removed the translations from Element Android at some point, so clients translating the fallback are probably rare nowadays: https://github.com/vector-im/element-android/pull/1610

2022-01-19 05:17 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +language selection for their client, which may be personal information.
Changed this now to say, that historically some clients did this wrong. But I still think the spec isn't clear enough in that regard.

2022-01-19 05:18 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +basis, especially for the fallback in `body`.
I've reworded it slightly now to give more focus on common variations instead of specifically focussing on issues with stripping.

2022-01-19 20:44 UTC, turt2live approved these changes
let's send it

2022-01-19 20:45 UTC, turt2live commented
I think this is overdue for FCP, and it unblocks things like threads:

@mscbot fcp merge

2022-01-20 00:30 UTC, ara4n commented
I agree that reply fallbacks cause more problems than they solve, and we can remove the current implementation from the spec.

However, I continue to believe they are a useful feature for the protocol to support trivial clients and help bootstrap new developers. Right now I can write a trivial 5 line Matrix client in bash which can accurately reflect conversation in a Matrix room - including edits and replies, thanks to fallbacks (rather than scrabbling around with /context to piece a coherent timeline together, or caching events). This is a *really nice developer experience* and gives a massive reassuring boost to folks casually developing on Matrix. I think we would be fools to discard it outright, just because folks who have already implemented replies/edits in their clients don't value fallbacks for folks who haven't yet. For Matrix to grow we have to make it fun and easy for new developers to get up and running quickly - without sacrificing ease of development or security for more sophisticated clients.

So, while I'm happy to ditch the current problematic implementation from the spec, I'd want to replace it shortly with a fixed implementation. Luckily, extensible events literally exist to provide better fallback mechanics for richer event types, and could fix reply fallbacks in a way that solves all the complaints here in Appendix B (other than the "leaking history" concern, which I consider bogus - it's no different to manual quotes in an event, or quoting history in an email thread. Clients can train the user to expect that the msg being replied to will be quoted in the msg). The way to use extensible events for this would be to have m.text and/or m.html include the fallback, and then an m.reply mixin to store the actual reply contents. This yields some duplication, but much like MIME fallbacks and similar it's the nature of the beast.

This discussion can be split out to another MSC however.

2022-01-20 02:47 UTC, deepbluev7 commented
@ara4n I agree that providing an easier way to support rich replies for simple clients is useful. It's mostly that I just had a very bad experience with the current fallback and I think it worsens the Matrix experience, if you add up all the issues and benefits.

I think a different MSC can provide a much better help for small clients. I personally would prefer to put this simply into unsigned as a bundled relation instead of using an extensible event. It would be some additional work for clients to support replies, but having the replied to event in unsigned would make generating a rendered event, which includes the reply, a simple concatenation and also makes it fairly easy to improve the look and feel incrementally. It does increase the implementation burden somewhat, but it does sidestep the complicated issues, where you need to load a different event, potentially over the network.

2022-01-20 08:01 UTC, ara4n commented
yeah, bundling could work okay as an alternative.

2022-01-20 12:20 UTC, richvdh commented on proposals/2781-down-with-the-fallbacks.md
> +You might not get notifications anymore for replies to your messages. This was
```suggestion
You might not get notifications any more for replies to your messages. This was
```

2022-01-20 12:20 UTC, richvdh commented on proposals/2781-down-with-the-fallbacks.md
> +relations) or not.
changing the push rules is a big undertaking, so won't happen quickly. I think if we accept this MSC, we should do so on the understanding that we're prepared to lose notifications for replies for an indefinite period. If we're *not* happy with that, we should at least satisfy ourselves that changing the push rules is *possible* first.

2022-01-20 12:20 UTC, richvdh commented on proposals/2781-down-with-the-fallbacks.md
> +### Testresults without fallback
```suggestion
### Results of testing replies without fallback
```

2022-01-20 12:20 UTC, richvdh commented on proposals/2781-down-with-the-fallbacks.md
> +### Fallback increase integration work with new features
```suggestion
### Fallbacks increase integration work with new features
```

2022-01-20 12:20 UTC, richvdh commented on proposals/2781-down-with-the-fallbacks.md
> +Changes from 1.5 years ago:
please could you replace this with an actual date?

2022-01-20 12:20 UTC, richvdh commented on proposals/2781-down-with-the-fallbacks.md
> +Only one client implemented rich replies in the last 1.5 years. Other clients
what date was this written?

2022-01-20 13:22 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +relations) or not.
I'm pretty sure it is possible, here is how beeper did the same for reactions: https://gitlab.com/beeper/synapse/-/commit/44a1728b6b021f97900c89e0c00f7d1a23ce0d43

The MSC I want to write will have that, just with a way to match on the relation type and a special case for the reply relation format.

2022-01-20 15:59 UTC, richvdh commented on proposals/2781-down-with-the-fallbacks.md
> +relations) or not.
> I'm pretty sure it is possible, here is how beeper did the same for reactions: https://gitlab.com/beeper/synapse/-/commit/44a1728b6b021f97900c89e0c00f7d1a23ce0d43

it's hard for me to reverse-engineer how exactly the push rules are changing here, and how clients are expected to behave in the face of such changes. I'd want to see a more complete analysis.

2022-01-20 18:28 UTC, ara4n commented on proposals/2781-down-with-the-fallbacks.md
> +relations) or not.
relying on reply fallbacks to notify you when someone replies to your message is a hack. my hunch is that people aren't even necessarily aware that it exists as an (accidental) feature. i'm okay with removing it in order to clean up reply fallbacks as long as we add it back in on push rules - whether it's easy or hard to incorporate it in push rules.

2022-01-20 19:58 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +relations) or not.
@richvdh I'll just write the MSC on saturday and then you can form an opinion. But basically it is an extra condition, that can match on a related event, which can be useful in general to enable/disable notifications for replies, reactions, threads, edits, etc.

2022-01-20 20:22 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +Only one client implemented rich replies in the last 1.5 years. Other clients
I've added a date to the top of the status section now, when it was last updated.

2022-01-20 20:23 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +Changes from 1.5 years ago:
I've added a date instead of replacing it, because I think the time period is the interesting thing here, but it should be clear now, what time period is meant.

2022-01-20 20:40 UTC, richvdh commented on proposals/2781-down-with-the-fallbacks.md
> +Changes from 1.5 years ago:
thanks.

2022-01-20 20:43 UTC, richvdh commented on proposals/2781-down-with-the-fallbacks.md
> +relations) or not.
> relying on reply fallbacks to notify you when someone replies to your message is a hack. my hunch is that people aren't even necessarily aware that it exists as an (accidental) feature. 

I agree with both, but I'm pretty sure that people would notice it going missing as an (accidental) feature.

> i'm okay with removing it in order to clean up reply fallbacks as long as we add it back in on push rules - whether it's easy or hard to incorporate it in push rules.

... so, we're agreed we need a proposal for doing so before we accept this MSC?  I'm sorry, I've been burnt here before.

2022-01-21 01:48 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +relations) or not.
"weekend": https://github.com/matrix-org/matrix-doc/pull/3664

2022-01-21 13:23 UTC, erikjohnston commented on proposals/2781-down-with-the-fallbacks.md
> +relations) or not.
I rely heavily on getting binged when someone replies to a message, and you can see that it has become ingrained in behaviour as people generally don't start replies with a bing. I personally think we really should fix the push rules before we drop fallbacks.

2022-02-01 17:34 UTC, richvdh commented on proposals/2781-down-with-the-fallbacks.md
> +relations) or not.
resolving this thread now that we have #3664.

2022-02-01 17:35 UTC, richvdh commented
so we now have MSC3664 to fix the push rules for replies, but I still don't think we can land this MSC until that one does, so I'm going to keep my concern open for now.

2022-04-08 21:46 UTC, turt2live commented
While we wait for implementation of MSC3664, let's remove this from the SCT's "look at this now" pile. Given how easy it was to get checkmarks for the original FCP, I am not concerned for future FCPs.

@mscbot fcp cancel

2022-10-12 20:31 UTC, turt2live commented
This is formally blocked by https://github.com/matrix-org/matrix-spec-proposals/pull/3664

2023-03-10 19:28 UTC, t3chguy commented
This cannot happen soon enough.

<img width="993" alt="image" src="https://user-images.githubusercontent.com/2403652/224408669-2550816c-0969-4a9f-a528-8f5daa47d27f.png">

2023-08-02 14:01 UTC, clokep commented on proposals/2781-down-with-the-fallbacks.md
> +an explicit solution.
I think with intentional mentions this isn't an issue anymore, see https://spec.matrix.org/v1.7/client-server-api/#mentioning-the-replied-to-user

2024-05-13 20:01 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +an explicit solution.
That is partially true. Intentional mentions resolve the notification issue, however the current behaviour is also very lacking, see for example https://github.com/matrix-org/matrix-spec-proposals/pull/4142

I don't think the notification behaviour should be a blocker for this MSC and I never considered it one, considering that when I wrote this MSC, that behaviour was actually broken in Synapse. Also not all clients support intentional mentions, for those this is still a problem. That paragraph is more about mentioning that it could be solved by a different MSC.

I can update the paragraph about the current solutions, however I do expect it to grow stale quite quickly again unless the blockers mentioned above are resolved from the SCT side.

2024-05-13 22:23 UTC, turt2live approved these changes
generally this seems fine - thanks for taking another look at it.

2024-05-13 22:23 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +Remove the [rich reply fallback from the
Blocking concern for FCP finish: I don't think we can jump to removal, but we can deprecate and say "Clients SHOULD NOT send fallback", for example. A later MSC would be capable of fully removing the fallback. 

The spec would read something like:

> Clients SHOULD NOT send fallback representation, but SHOULD attempt to parse it intelligently when provided (detected by the presence of `<mx-reply />`). The fallback representation is as follows: [...]

Later, when removed and clients have had a chance to fully see the transition, an MSC to remove the fallback completely can be FCP'd. The spec after that change would likely just be a note block saying "There used to be a fallback representation, but not anymore. Click [here] to see it.".

This is all as required under the deprecation policy: https://spec.matrix.org/v1.10/#deprecation-policy

2024-05-13 22:23 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +Matrix experience overall.
I found it hard to read this paragraph in particular. Non-blocking suggested edit:
```suggestion
Clients which don't implement rich replies or edits may see messages
without context, confusing users. However, most replies and edits are
in close proximity to the original message, making context likely to be
nearby. Clients should also have enough information in the event to
render helpful indications to users while they work on full support.
```

2024-05-13 22:23 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +an explicit solution.
```suggestion
Clients which aren't using [intentional mentions](https://spec.matrix.org/v1.7/client-server-api/#mentioning-the-replied-to-user)
may cause some missed notifications on the receiving side. [MSC3664](https://github.com/matrix-org/matrix-doc/pull/3664)
and similar aim to address this issue, as [MSC4142](https://github.com/matrix-org/matrix-spec-proposals/pull/4142)
tries to improve the intentional mentions experience for replies generally.
```

2024-05-13 22:23 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +an explicit solution.
The concern blocking FCP from finishing here is text to clarify the presence of intentional mentions in the modern world. The older blockers regarding notifications/push rules are removed/negated.

2024-05-13 22:23 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +
Non-blocking, just added information from discussion with the SCT:
```suggestion

This history leak can also cause abusive or redacted messages to remain visible
to other room members, depending on the client implementation of replies.

```

2024-05-13 22:24 UTC, turt2live commented
@mscbot fcp merge

2024-05-13 22:24 UTC, turt2live commented
@mscbot concern We must deprecate before removal
@mscbot concern Mention intentional mentions

2024-05-13 23:26 UTC, ara4n commented
fwiw, the thing that swung me on this is the t&s impact of leaking contents of deleted in replies.

2024-05-14 00:42 UTC, clokep commented on proposals/2781-down-with-the-fallbacks.md
> +ultimately closed in favor of this proposal.
MSC2589 is noted in the alternative section, which seems to fit it a bit better. I simplified the text slightly, but I'm unconvinced it is clearer. Additionally I added more context into the issues that this causes to better setup why we want to remove this

```suggestion
Currently replies require clients to send and parse a [fallback representation](https://spec.matrix.org/v1.10/client-server-api/#fallbacks-for-rich-replies)
of the replied to message. Fallback representation is meant to simplify supporting
replies in a new client, but they actually create implementation issues and block features.
This MSC proposes to deprecate and eventually remove those fallbacks.

Some of the known issues include:

* The content of reply fallback is [untrusted](https://spec.matrix.org/v1.10/client-server-api/#stripping-the-fallback).
* Reply fallbacks may leak history. ([#368](https://github.com/matrix-org/matrix-spec/issues/368))
* Parsing reply fallbacks can be tricky. ([#350](https://github.com/matrix-org/matrix-spec/issues/350))
* It is unclear how to handle a reply to a reply. ([#372](https://github.com/matrix-org/matrix-spec/issues/372))
* Localization of replies is not possible when the content is embedded into the event.
* It is not possible to fully redact an event once it is replied to, this causes both trust & safety and right to be forgotten issues.
* There are a variety of implementation bugs related to reply fallback handling.
```

2024-05-14 00:43 UTC, clokep commented on proposals/2781-down-with-the-fallbacks.md
> +[specification](https://spec.matrix.org/v1.1/client-server-api/#rich-replies).
This has been allowed since Matrix v1.3: https://spec.matrix.org/v1.10/client-server-api/#rich-replies

```suggestion
as invalid HTML.
```

2024-05-14 00:44 UTC, clokep commented on proposals/2781-down-with-the-fallbacks.md
> +sidestep a lot of pitfalls.
This has been allowed since Matrix v1.3: https://spec.matrix.org/v1.10/client-server-api/#rich-replies

```suggestion
as invalid HTML.
```

2024-05-14 00:45 UTC, clokep commented on proposals/2781-down-with-the-fallbacks.md
> +time.
```suggestion
For a period of time clients will need to continue handling events with reply fallbacks,
either old events or from clients which have not yet been updated.
```

2024-05-14 00:47 UTC, clokep commented on proposals/2781-down-with-the-fallbacks.md
> +bleed into public rooms.
I don't think this needs an unstable prefix -- the spec says that rsending reply fallbacks is a "SHOULD", so it is valid to stop sending them.

2024-05-14 00:48 UTC, clokep commented
Overall I'm happy with this, but I think the text is a bit confusing. @turt2live and I left a bunch of comments which should help with that.

@mscbot concern General clarity

2024-05-14 07:51 UTC, dbkr commented
I think this is going in the right direction but already has appropriate concerns, and I agree with them. For future reference, some examples would make this a lot easier to read.

2024-06-02 22:07 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +ultimately closed in favor of this proposal.
I mostly applied this diff with a few minor wording changes. Feel free to send further suggestions about that section, but I will mark this as resolved for now for clarity!

2024-06-02 22:09 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +bleed into public rooms.
Originally the unstable prefix was added as some SCT members asked for it. However, I do agree that this seems unnecessary since 1.3 and removed it.

2024-06-02 22:09 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +
Added this.

2024-06-02 22:10 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +Matrix experience overall.
I applied this, since most of the paragraph seemed to be a bit redundant. Thanks!

2024-06-02 22:11 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +an explicit solution.
I updated the paragraph to specify, that since clients would probably implement intentional mentions first, the notification behaviour should not be a blocker anymore, but might be improved in the future.

2024-06-02 22:21 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +Remove the [rich reply fallback from the
I disagree, that a separate deprecation period is necessary. The behaviour was already made optional since version 1.3. As such clients should already be able to deal with not receiving a fallback. For that reason I think just mentioning the change in an INFO box should be sufficient.

For receiving clients there is no difference between a client, that stops sending a fallback because of a "SHOULD NOT" or the spec not mentioning that clients should or should not send a fallback at all. For the sending client this only adds confusion without any substantial benefit imo.

Also on the receiving end missing fallbacks need to be supported already today (since 1.3). As such there isn't really a change in behaviour, just the frequency of such events. Again, pointing out the change in an INFO box would be helpful, but a deprecation period would just add additional process overhead.

So to summarize, I don't think the deprecation policy applies here and to respect the time of everyone involved, I deem an additional MSC to then remove the behaviour as unnecessary. The actual implementation in the specification might be a bit more sophisticated, but I do believe sending reply fallbacks should be removed now.

2024-06-02 22:25 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +- Element Android: Relies on the reply fallback.
One of my hopes with this MSC was to encourage clients to implement proper reply support. Element Android in particular has been a problem for me, since it sends invalid fallbacks in many cases. While I do agree, that it is unlikely this will actually be fixed in Element Android, considering how problematic the reply implementation in Element Android is, I don't know if that should really be a blocker on this MSC. Stripping out its current reply handling and implement this MSC is probably easier than making Element Android actually compliant with the current specification for replies (from before this MSC).

2024-06-05 00:01 UTC, clokep commented on proposals/2781-down-with-the-fallbacks.md
> +as invalid html.
I think it probably makes more sense to just strip it? I prefer not having "either-or" sort of things in a specification and give a single clear guidance.

```suggestion
Clients should stop sending them and should treat `<mx-reply>` elements as something
to be unconditionally stripped.
```

2024-06-05 00:04 UTC, clokep commented on proposals/2781-down-with-the-fallbacks.md
> +examples).
I think this somewhat overlaps with what we say above, let's stick to security concerns in thsi section:

```suggestion
Overall this should **reduce** security issues as the handling of untrusted
HTML is simplified. For an example security issue that could be avoided, see
https://github.com/vector-im/element-web/releases/tag/v1.7.3 and the appendix.
```

Although the appendix doesn't seem to detail other security issues?

2024-06-05 00:08 UTC, clokep commented on proposals/2781-down-with-the-fallbacks.md
> +any additional deprecation period.
```suggestion
For this reason the reply fallback can be removed from the specification without
any additional deprecation period.
```

2024-06-05 00:10 UTC, clokep commented
@deepbluev7 Thanks for your effort on clarifying and improving this MSC. I think it is much easier to read now and clearer what the proposed changes are! 🎉 

@mscbot resolve General clarity

2024-06-11 08:46 UTC, dbkr commented on proposals/2781-down-with-the-fallbacks.md
> +Currently the specification suggest clients should send and strip a
```suggestion
Currently the specification suggests clients should send and strip a
```

2024-06-11 10:04 UTC, dbkr commented on proposals/2781-down-with-the-fallbacks.md
> +Remove the [rich reply fallback from the
I think you may be talking about two slightly different things here: it's a given that clients need to support them not being there. The question is whether the text of the next few versions of the spec needs to describe a thing that was previously in it but is now no longer recommended.

2024-06-18 13:44 UTC, richvdh reviewed
some very minor editorial points, and a question.

2024-06-18 13:44 UTC, richvdh commented on proposals/2781-down-with-the-fallbacks.md
> +* It is not possible to fully redact an event once it is replied to, this causes both trust & safety and right to be forgotten issues.
Grammar nit:

```suggestion
* It is not possible to fully redact an event once it is replied to. This causes both trust & safety and right to be forgotten issues.
```

2024-06-18 13:44 UTC, richvdh commented on proposals/2781-down-with-the-fallbacks.md
> +address this issue, as
```suggestion
address this issue, and
```

2024-06-18 13:44 UTC, richvdh commented on proposals/2781-down-with-the-fallbacks.md
> +Of the 23 clients listed in the [matrix client matrix](https://matrix.org/clients-matrix)
```suggestion
Of the 23 clients listed in the [Matrix client matrix](https://matrix.org/clients-matrix)
```

2024-06-18 13:44 UTC, richvdh commented on proposals/2781-down-with-the-fallbacks.md
> +- Element iOS: [Does not support rich replies](https://github.com/vector-im/element-ios/issues/3517)
... and therefore relies on the reply fallback? So is the same as Element Android? or different?

2024-06-25 17:42 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +- Element iOS: [Does not support rich replies](https://github.com/vector-im/element-ios/issues/3517)
When that was written, yes. Although I didn't investigate more since I don't own any iOS device. But it seems Element iOS might have some support now based on https://github.com/element-hq/element-ios/pull/6155 ?

2024-06-25 17:49 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +Remove the [rich reply fallback from the
@dbkr I think the spec should stop suggesting that reply fallbacks are used in replies. I think that should just be historical information as we do for historical mxids, m.room.aliases rX.Y.Z spec versions and unamespaced tags for example, since those can still appear and client authors need to be aware of that. I don't think any of those had a deprecation period either and some of those are arguably higher impact.

2024-06-25 17:53 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +as invalid html.
Hm, I think unconditionally stripping them forever is a bit dangerous, since it allows you to sneak data into events, that usually isn't rendered. The "either-or" behaviour makes the old behaviour of most clients still valid, but I think long term clients shouldn't special case that tag and render it as they do any invalid html (which in Nheko's case is dump it into the message as text). However how clients treat invalid html is again different, Nheko html escapes such tags, other clients drop such tags.

Maybe this should say, that clients should just treat it as invalid html, which implicitly allows both of these implementations? And in the future someone can describe in more detail how invalid html tags should be handled in general?

2024-06-25 17:59 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +examples).
Hm, I don't feel that strong either way. I do consider leaking history "security sensitive", but that isn't a real security issue, I guess. Similarly injecting untrusted html into messages has been abused a few times and could be a security issue, but I don't know of any open ones, that can be abused for anything more than messing with what is displayed atm.

I'll just apply the suggestion and I don't think the exact wording if the appendix contains security issues or not isn't important enough to figure out a better way to word this.

2024-06-25 23:38 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +clients and that clients may need to strip out such fallbacks.
MSCs don't really get to dictate how a spec PR is reviewed. This paragraph should be removed.

(blocking concern)

2024-06-25 23:38 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +Clients which don't implement rich replies or edits may see messages
I know I suggested this text, but I think I got confused when I wrote the comment. Is this MSC for reply fallbacks, edit fallbacks, or both? This should be clarified in the introduction and title if it's also affecting edits.

2024-06-25 23:38 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +* It is not possible to fully redact an event once it is replied to. This causes both trust & safety and right to be forgotten issues.
Let's not wade into legal arguments here, particularly when no one reviewing this advertises themselves as a GDPR lawyer. We can also spell out the T&S concern to remove the mystery.

```suggestion
* It is not possible to fully redact an event once it is replied to. This causes issues with Trust & Safety where
  spam or other removed content remains visible, and may cause issues with the GDPR Right to be Forgotten.
```

2024-06-25 23:38 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +as invalid html.
Describing it as "invalid HTML" with a "for example, by stripping the tag or rendering the escaped plain text" I think would be fine.

2024-06-25 23:38 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +Remove the [rich reply fallback from the
All of those examples are from a time before the deprecation policy was enacted in Matrix 1.1, fwiw. This MSC introduces a technically breaking change to clients, which necessitates deprecation first at a minimum. The spec instructs clients which do support rich replies on how to handle the fallback (strip it), and implies that the module is optional. By removing the fallback, we're saying that clients *must* support rich replies in order to maintain conversation context - something which is currently optional (and not even a `SHOULD` optional).

The MSC addresses the context piece a bit, but doesn't address the breaking change. As such, this needs to go through deprecation first to manage the breaking change, then removal at least 1 version later as per the policy. This does add additional overhead - feedback regarding that is best placed in a dedicated MSC which aims to change the deprecation policy.

2024-06-25 23:40 UTC, turt2live requested changes
seemingly my github tabs got confused and submitted my review without asking the status associated with it.

Apologies for the slow review here - authenticated media has been taking up all my time.

2024-06-25 23:40 UTC, turt2live commented
@mscbot resolve Mention intentional mentions

2024-09-25 14:44 UTC, anoadragon453 commented on proposals/2781-down-with-the-fallbacks.md
> +clients and that clients may need to strip out such fallbacks.
I agree that the MSC shouldn't have control over the spec PR. However, this is a useful suggestion that the spec PR author could consider, and I think it's useful to keep it around for consideration.

Perhaps this can be reworded:

```suggestion
A suggestion for the spec PR: An info box could be included to mention
the historical use of the reply fallback, suggesting that clients may encounter
such events sent by other clients and that clients may need to strip out such
fallbacks.
```

That way the spec PR remains independent, yet the idea is not lost.

2024-10-01 15:01 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +Clients which don't implement rich replies or edits may see messages
I just removed the mention of edits, since this MSC is only about rich replies. Edits already suffered of this context loss for clients not implementing them+rich replies, since edits don't include a reply fallback (nor a reply relation).

2024-10-01 15:02 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +as invalid html.
I simplified it to "client should treat it as any other invalid html tag", no need to spell out how clients currently do that.

2024-10-01 15:07 UTC, deepbluev7 commented on proposals/2781-down-with-the-fallbacks.md
> +Remove the [rich reply fallback from the
> All of those examples are from a time before the deprecation policy was enacted in Matrix 1.1, fwiw. This MSC introduces a technically breaking change to clients, which necessitates deprecation first at a minimum. The spec instructs clients which do support rich replies on how to handle the fallback (strip it), and implies that the module is optional. By removing the fallback, we're saying that clients must support rich replies in order to maintain conversation context - something which is currently optional (and not even a SHOULD optional).

No, currently it is perfectly legal for a client to never send reply fallbacks, since reply fallbacks were made optional in Matrix 1.3. This MSC just removes the case, where sometimes clients without rich replies weren't losing context, because most clients still send a fallback today. But since the reply fallback was already optional, no client was required to send a reply fallback. And other features like threads or edits never included a reply fallback apart from some clients implementing that feature incorrectly. As such this is only breaking because it increases the likelihood of encountering an event without reply fallback, but it doesn't change that such events are perfectly legal to send already.

This MSC only removes already optional behaviour.

2024-10-01 15:23 UTC, kegsay commented on proposals/2781-down-with-the-fallbacks.md
> +Remove the [rich reply fallback from the
> This MSC introduces a technically breaking change to clients

..but it doesn't. Clients have to handle the fallback not being there. It does not meet the bar for a "breaking change".

I would **strongly** advocate a nuanced approach here, on a case-by-case basis (which honestly isn't hard given the amount of attention MSCs get). In _this particular case_, because the functionality was optional, there is little benefit to dragging this process out any longer than needed, particularly given the security impacts of reply fallbacks. Having them in the ecosystem any longer than necessary is just untenable, _especially_ if it's just due to bureaucracy rather than any technical/security/social reasons.

2024-10-01 18:09 UTC, turt2live commented on proposals/2781-down-with-the-fallbacks.md
> +Remove the [rich reply fallback from the
This feels like it's become a circular argument with no conclusion. Other members of the SCT are encouraged to weigh in on this, as I'm unconvinced that this MSC can go through as-is.

2024-10-01 19:17 UTC, clokep commented on proposals/2781-down-with-the-fallbacks.md
> +Remove the [rich reply fallback from the
Since clients already need to handle the fallback not being there then I think it is fine to remove it with a historical reference to strip the content.

2024-10-16 16:30 UTC, turt2live commented
I'm still concerned about the jump to removal here, but not enough to prevent this MSC from moving forwards:

@mscbot resolve We must deprecate before removal

I have unticked my box though to get broader alignment from the remaining SCT members on this.

2024-10-29 16:33 UTC, erikjohnston commented on proposals/2781-down-with-the-fallbacks.md
> +Remove the [rich reply fallback from the
The question in my mind is: what are the benefits to the ecosystem by having a deprecation period? What would materially change if we marked these APIs as deprecated?

Naively I would have thought that the only action client authors would _need_ to take was to ensure that they handled the absence of the fallback correctly. Given its has been optional since 1.3 this *should* be a no-op for client implementers. 

However, having a deprecation policy will flag two things to client develops:
1. They really do need to make sure they correctly handle replies without fallback. There is a difference between clients theoretically supporting lack of fallback and them actually supporting it.
2. They may want to ensure that the UX without fallback is still good. This is a transition from being able to mostly be able to rely on there being a fallback most of the time, to there never being one.


Personally, I think if we're relatively confident that most clients already deal correctly with the above its OK to skip the deprecation period. I'm in no position to judge the client situation though.

Otherwise, the safest option would be to do a short deprecation period, though I would advocate for not requiring a new MSC and instead simply have this MSC say "fallback will be deprecated in the next release, and removed the release after (unless the SCT hear enough negative feedback to delay)". If push comes to shove we can always do a one-line MSC to change that.

In terms of getting this over the line, I'll try and poke internally to get a conclusion on this.


**TL;DR**: My instinct is let's skip if we're confident that the vast majority of the client ecosystem would not benefit from a deprecation period, but if not let's just do a quick deprecation period and slate the removal in this MSC.

2024-11-01 20:01 UTC, officialdakari commented
Implementation: officialdakari/Extera

2024-11-05 16:23 UTC, merged

2024-11-19 09:10 UTC, zecakeh commented
Spec PR: https://github.com/matrix-org/matrix-spec/pull/1994

2025-01-08 23:44 UTC, turt2live commented
This was merged 🎉 in Matrix 1.13