MSC2964: [WIP] Matrix profile for OAuth 2.0
matrix-org/matrix-spec-proposals pull request #2964
Opened 2021-01-14 17:10 UTC by sandhose

[Rendered](https://github.com/sandhose/matrix-doc/blob/sandhose/msc/oauth2-profile/proposals/2964-oauth2-profile.md)

2021-01-15 09:09 UTC, sandhose commented
Related issue: #2615 

Related MSCs: #2965, #2966, #2967 

---

In this MSC, there are a few areas that still need work.

First, it outlines different profiles of clients. One important client type that is not yet covered by it are CLI tools.
The natural fit for this would be the client credential grant, taking form of either a `client_secret` or a secret key for [JWT signing](https://tools.ietf.org/html/rfc7523#section-2.2).
The problem with this is that it authenticates as "the client", not a user. How users should delegate authorization to other clients is a bit unclear. Maybe [RFC 8693](https://tools.ietf.org/html/rfc8693) helps with that.

Second, there are the parts that we enforce.
For example, I chose to enforce PKCE for public clients. Since most of Matrix clients are public, I think it makes sense to enforce the current best practices here.
Another example would be credentials for confidential clients. Right now nothing is specified, but it might make sense to encourage the usage of keypairs instead of client secrets. If we encourage that, should it be enforced?
Last example, in the part about the [request to the authz endpoint](https://github.com/sandhose/matrix-doc/blob/msc/sandhose/oauth2-profile/proposals/2964-oauth2-profile.md#requests-to-the-authorization-endpoint), I mention that the `state` parameter should be unpredictable. Some profiles go further than that to enforce a minimum entropy for this parameter.

Third there is device handling in general. [MSC2967](https://github.com/matrix-org/matrix-doc/pull/2967) talks a bit about this, but there will definitely be some changes to the device API.
An example of this is that we might want to surface client metadata when querying the devices instead of just an arbitrary name.
Another open question is should a device be deleted on logout? If so, how do we handle device that are used by multiple clients (which is technically possible with the solution proposed in #2967)?

2021-01-15 15:04 UTC, Sorunome commented on proposals/2964-oauth2-profile.md
> +The current authentication mechanisms in Matrix does look like a lot like OAuth 2.0 without most of its security mechanisms.
UIA and OAuth have two different goals, though. OAuth could be e.g. a UIA stage

2021-01-15 15:05 UTC, Sorunome commented on proposals/2964-oauth2-profile.md
> +An **Authorization/Authentication Server** (AS) or **OIDC Provider** (OP) in the context of OIDC is the service that fulfills an authentication request. In the context of Matrix, it is either the hom
Can we try to find a different acronym, please? AS is already used in the matrix world for Application Service, making it a bit confusing to read ^^

2021-01-15 15:08 UTC, Sorunome commented on proposals/2964-oauth2-profile.md
> +The client might include a login hint to what MXID the user is trying to use.
So far the spec only requires a username on login and `/login` then returns the MXID. At work we actually utilize this so that the login username has nothing to do with the MXID you have in the end.

2021-01-15 15:13 UTC, Sorunome commented on proposals/2964-oauth2-profile.md
> +None relevant.
Listing expanding and adding UIA to the `/login` endpoint does sound like a relevant alternative here.

2021-01-15 15:13 UTC, sandhose commented on proposals/2964-oauth2-profile.md
> +The current authentication mechanisms in Matrix does look like a lot like OAuth 2.0 without most of its security mechanisms.
While it is still under discussion, the end goal is to completely replace the current authentication mechanism of Matrix with OAuth 2.0, not add OAuth as a UIA stage. This series of MSC are written with this in mind

2021-01-15 15:17 UTC, sandhose commented on proposals/2964-oauth2-profile.md
> +An **Authorization/Authentication Server** (AS) or **OIDC Provider** (OP) in the context of OIDC is the service that fulfills an authentication request. In the context of Matrix, it is either the hom
Fair point. Those acronyms are pretty standard in the OAuth 2.0 world, but while I did not state that the AS used should be OIDC-compliant (because there are no need for that for now) I think I'll need that in further MSCs, especially when I start to touch to widgets/integrations. I'll probably explicit that and use the "OP" acronym instead of "AS".

2021-01-16 16:43 UTC, Sorunome commented on proposals/2964-oauth2-profile.md
> +# MSC2964: Matrix profile for OAuth 2.0
Soru is not sure if these OAuth proposals in their current form work. There are a couple fundamental issues with them:

1. Bad UX: For native desktop clients and phone clients, the user is basically forced to be re-directed to the browser and complete login steps there. For web-clients the user is re-directed upon login to another website.
2. A possible mentioned work-around for the first issue was privileged clients, so that e.g. matrix.org privileges app.element.io. While that does not have to happen, if an easy solution to a bad UX issue is to introduce privileged clients, it *will* happen sooner or later, if we want or not.
3. This removes the ability for us to ever do something like #2957 or ever implement login with just one password for both authentication and SSSS:
3.1. OAuth steps are completed on the website --> we execute code to handle our password from the server. The entire point of #2957 is to *not* trust the server with this
3.2. We'd need to get the calculated SSSS key from webbrowser to client somehow
4. That only few clients implement SSO currently shows the high entry-barrier for client-dev if you want to login with SSO. Requiring OAuth for every login will significantly lift the entry barrier for new clients
5. for embedded/limited clients the idea proposed was that you need an external device w/ browser to complete the login

An idea would be to use oauth just for sso, and replace `m.login.sso` with `m.login.oauth` and introduce UIA to `/login` (#2835). While a server could chose to just always use oauth then, instead of "normal" login, this would negate all the extra stuff we would get by using OAuth scopes.

Another idea would be to *not* require a browser / browser-like environment to complete the needed OAuth steps, and (for point 3), *not* execute any code given by the server for being able to authenticate yourself.

2021-01-26 13:29 UTC, ara4n commented on proposals/2964-oauth2-profile.md
> +# MSC2964: Matrix profile for OAuth 2.0
I synced with @sandhose on this last week, as I share some of the same concerns above (and hadn't had a chance to discuss them before these MSCs were written)  Taking them point by point:

 1. Bad UX: In practice there are basically two auth flows in Matrix today - either basic username+password, or some kind of SSO which requires a web UI.  It's critical that we continue to support basic username+password for all the various Matrix clients and bots which use this, allowing them to have simple native UI (at the expense of the security dubiousness of encouraging people to hand their main account password over to some random native app).  For other flows, we already need the ability to bounce through a web UI, and in practice we've seen several major security issues due to inventing those flows ourselves rather than leveraging OAuth - so I see the appeal here in switching to an existing standard.  Am I missing a native auth flow that wouldn't be covered by this?  Meanwhile, if you're on a basic client and want to get an OAuth scope, the client can provide a URI to let the user finish the auth in a web browser - this feels like an improvement on the current situation.
 2. Given your server is the one authing your login, not your client, it doesn't seem unreasonable that if the server doesn't know if it can trust the client, the server should be the one displaying the UI (webpage) needed to auth the client.  However, if your server wants to specialcase some known trusted clients to let them iframe the server SSO flow, that doesn't seem unreasonable, and would improve common cases where a given server steers new users into using a default client without making things worse for other clients.
 3. Totally agreed that this is in conflict with MSC #2957 - i've asked @sandhose to go figure out how to fix that, as cryptographic login is super desirable.  (It's worth noting that cryptographic login is in general incompatible with SSO however, so perhaps it just ends up being a separate login flow alongside the basic auth one for non-SSO situations?)
 4. Totally agreed we should keep plain login around too.
 5. Solved by keeping plain login around too.

However, I'm not sure that the right solution is to turn `m.login.sso` into `m.login.oauth` and add UIA to `/login`.  We then end up with both the complexity of UIA *and* OAuth2 flying around.  Instead, how about we aim to have 3 separate login flows: plain login, OAuth (covering all SSO), and cryptologin?

The main flaw I see is that we'd need a place to support TOTP-style 2FA such that it works for all flows if configured (it feels suboptimal to make it SSO-only, given cryptologin + 2FA sounds very desirable, for instance)

2021-01-26 17:30 UTC, Sorunome commented on proposals/2964-oauth2-profile.md
> +# MSC2964: Matrix profile for OAuth 2.0
Generally sounds good, yes. Another issue would be that with plain login we don't have the scope management.

As for the concerns, the issue is that for TOTP (or basically any other 2fa) we need more back-and-forth communication one way or another. The cryptographic authentication might also require that (while no exact flows are layd out yet in the MSC, a login does require a few requests back-and-forth). It seems to soru that the simplest solution for that is adding UIA to `/login`, but yes, i seems like duplicate work.

2021-01-26 18:48 UTC, richvdh commented on proposals/2964-oauth2-profile.md
> +# MSC2964: Matrix profile for OAuth 2.0
>  Instead, how about we aim to have 3 separate login flows: plain login, OAuth (covering all SSO), and cryptologin?

I'm not entirely convinced by this. Some servers (of which matrix.org will soon be one) allow either username/password or SSO (via social login). If we split username/pass and OAuth into two separate flows, we effectively undo the work we did for social login in presenting the Identity Providers next to the username/password box, since we're now back to "log into matrix.org" (without knowing *anything* on the client side about what auth mechanisms matrix.org might offer).

Of course that's a problem with OAuth generally, but at least if the username/password mechanism follows the same flow as other logins, we don't get this jarring "username/password" vs "everything else".

There is another problem with Social Login, which is solved by having the server manage the choice of login flow (OAuth-stylee), which is: how to correctly brand login buttons without having to have support for every conceivable brand in every client.

I'm not sure I want to discuss this further here; the point is basically that I think we need to take a hard look at whether what we have designed for Social Login is the right solution, or whether we need to do something more OAuthy.


To pick up a couple of other points:

@Sorunome wrote:

> 4. That only few clients implement SSO currently shows the high entry-barrier for client-dev if you want to login with SSO. Requiring OAuth for every login will significantly lift the entry barrier for new clients

Disagree. I'm not convinced the entry barrier for SSO is any higher than username/pass, since it's just a couple of redirects; the server takes care of most of it. IMHO the reason few clients implement SSO is because there is no need to: few *servers* currently implement SSO.

@ara4n wrote
> [re embedded clients]
> Solved by keeping plain login around too.

except it's not, is it? It only solves it for servers which choose to offer a username/password flow, with no 2FA? That might work for specific deployments, but it doesn't sound like a general solution.

2021-01-27 23:09 UTC, MTRNord commented on proposals/2964-oauth2-profile.md
> +# MSC2964: Matrix profile for OAuth 2.0
@richvdh 
> https://github.com/matrix-org/matrix-doc/pull/2785Disagree. I'm not convinced the entry barrier for SSO is any higher than username/pass, since it's just a couple of redirects; the server takes care of most of it. IMHO the reason few clients implement SSO is because there is no need to: few servers currently implement SSO.

I think the issue here is not really the code needed to do the requests but actually that there might be a webpage to be displayed to do the actual SSO. Which usually tends to be hard for native desktop apps and TUI clients as those have a harder time communicating with a browser (and with those that do js sometimes even). Thats in my opinion the main challenge of SSO currently. Though if OAuth gives token/code based auth (as google does it for example) this would be an upgrade and make this easier. (google shows you a token a user can easily copy from their browser so the client doesnt need to spin up a local server to redirect too or similar).

Also I agree with @richvdh on the embedding part (basicly what I said above).

I overall do like having oauth in the spec as a main login thing but I have the feeling in the current proposal it either breaks many clients and servers at once or atleast clutters the login process. I personally like the feature proposed but not the way it is implemented. Though I cannot offer another solution to this.

2022-05-16 16:39 UTC, ShadowJonathan commented on proposals/2964-oauth2-profile.md
> +The scope definitions are out of scope of this MSC and are defined in [MSC2967](https://github.com/matrix-org/matrix-doc/pull/2967).
Couldn't this be the client requesting for a seperate token with *only* the required scope to perform this action, only for it to be dropped (deactivated) immidiately after?

Something about upgrading the same token doesn't sit well with me from a security perspective, it might be a deliberately locked-down token, and/or multiple actions at once could race to upgrade/downgrade the current token.

2022-05-25 10:29 UTC, hughns commented on proposals/2964-oauth2-profile.md
> +An **Authorization/Authentication Server** (AS) or **OIDC Provider** (OP) in the context of OIDC is the service that fulfills an authentication request. In the context of Matrix, it is either the hom
I've added some changes to use OP instead of AS and added a comment about the overlap. Hopefully this clarifies the situation.

2022-07-12 10:44 UTC, kate-shine commented on proposals/2964-oauth2-profile.md
> +The scope definitions are out of scope of this MSC and are defined in [MSC2967](https://github.com/matrix-org/matrix-doc/pull/2967).
Having a separate token purely for one scope / set of scopes sounds like a really good idea, especially for race condition reasons. Races could be also avoided by introducing state on AS/OP side, but that is quite out of scope of oauth2 specification (if I'm not mistaken)

At the same time, it would make specification compatible with more possible OP implementations.

Making it single use would be easily doable using [jti](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.7) claim on that token.

2022-08-11 17:05 UTC, deepbluev7 commented on proposals/2964-oauth2-profile.md
> +The client might include a login hint to what MXID the user is trying to use.
I would like to see some more info on what a "login hint to what MXID" is. Can that be the username or does it have to be the mxid? Does the client now have to do the mxid mapping, that so far was pretty much implementation defined?

2022-08-11 17:41 UTC, zecakeh commented on proposals/2964-oauth2-profile.md
> +The client might include a login hint to what MXID the user is trying to use.
If I understood correctly, like the name suggests, it's only a hint, to avoid the user having to enter their MXID/username several times.

For example, with a client you would have these steps:
1. The user enters a MXID in the client to login.
2. The client discovers the homeserver from the MXID, according to the spec. While doing that it also sees that the homeserver supports OIDC.
3. The client directs the user to the OIDC auth server, and inserts in the request the MXID that the user entered as a login hint.
4. The user opens the login page on the auth server, and the username field is pre-filled according to the MXID that was provided.

In no way it should limit the choice of username for the user, or force the auth server or homeserver to use it. That's what I understand of the intentions for that field from the OIDC spec anyway.

Although ultimately the auth server is free to do whatever it pleases and might also ignore this parameter altogether.

I would guess it's also up to the auth server and homeserver to decide if the username used for authentication matches the one in the MXID. Irc, it's already the case in Synapse's OIDC config where one can chose to map the username from the auth server to anything else.

2022-08-11 19:55 UTC, deepbluev7 commented on proposals/2964-oauth2-profile.md
> +The client might include a login hint to what MXID the user is trying to use.
Well, often clients actually use separate fields for server and username (or the server is even preconfigured). Users then just enter "FirstName LastName", so would that be an acceptible login hint or does it have to be an mxid?

2023-01-30 14:24 UTC, dhenneke commented on proposals/2964-oauth2-profile.md
> +**OAuth 2.0** is an authentication framework. Authentication systems are built on top of OAuth2. It is based on numerous RFCs by the IETF.
```suggestion
**OAuth 2.0** is an authorization framework. Authentication systems are built on top of OAuth2. It is based on numerous RFCs by the IETF.
```

Some nitpicking: OAuth 2.0 clearly states that it only specifies authorization. Even OIDC is not necessarily an authentication protocol because it mainly makes some information from the (out-of-spec) authentication process that happened on the authorization server available to the RP. Granted, JWTs are often used as access tokens that have similar information and validation processes as the ID Token from OIDC.

2023-01-30 14:26 UTC, dhenneke commented on proposals/2964-oauth2-profile.md
> +An **Authorization/Authentication Server** (AS - as this acronym is already used to refer to Application Service in Matrix we will avoid it) or **OIDC Provider** (OP) in the context of OIDC is the se
This MSC sometimes uses "Authorization Server" and "Authentication Server". Afaik, the official OAuth 2.0 name for the AS would be "Authorization Server", so I would propose to use it everywhere.

2023-02-08 20:24 UTC, hughns commented on proposals/2964-oauth2-profile.md
> +An **Authorization/Authentication Server** (AS - as this acronym is already used to refer to Application Service in Matrix we will avoid it) or **OIDC Provider** (OP) in the context of OIDC is the se
Due to the existing use of Application Service as a term in Matrix I have instead standardised on OP and OpenID Provider (which I believe is most correct compared to "OIDC Provider" or "OIDC provider")

2023-02-09 09:40 UTC, hughns commented on proposals/2964-oauth2-profile.md
> +None relevant.
👍 This has been added to https://github.com/matrix-org/matrix-spec-proposals/blob/hughns/delegated-oidc-architecture/proposals/3861-delegated-oidc-architecture.md#alternatives

2024-09-17 12:49 UTC, tonkku107 reviewed
Some nitpicky things things I noticed while reading through the updated version and suggested fixes

2024-09-17 12:49 UTC, tonkku107 commented on proposals/2964-oauth2-profile.md
> +- `response_mode_supported`: a JSON array of response modes supported by the authorization endpoint
```suggestion
- `authorization_endpoint`: the URL where the user should be sent to initiate the login flow
- `token_endpoint`: the URL where the client is able to exchange the authorization code for an access token
- `response_types_supported`: a JSON array of response types supported by the authorization endpoint
- `grant_types_supported`: a JSON array of grant types supported by the authorization endpoint defined in [RFC8414] and used in [RFC6749]
- `response_mode_supported`: a JSON array of response modes supported by the authorization endpoint
```
- `authorization_endpoint` could be phrased better
- `token_endpoint` is interacted by the client, not really the user
- "verify the signature of the ID Token" below `token_endpoint` seems like a leftover from something
- typo on `grant_types_supported` explanation

2024-09-17 12:49 UTC, tonkku107 commented on proposals/2964-oauth2-profile.md
> +All of those metadata values are well-defined in [RFC8414] and used in varioud MSCs like [RFC6749].
```suggestion
All of those metadata values are well-defined in [RFC8414] and used in various RFCs like [RFC6749].
```

2024-09-17 12:49 UTC, tonkku107 commented on proposals/2964-oauth2-profile.md
> +  &redirect_uri=https://app.example.com/oauth2-callback
```suggestion
  &redirect_uri=https%3A%2F%2Fapp.example.com%2Foauth2-callback
```
URL encoding

2024-09-17 12:49 UTC, tonkku107 commented on proposals/2964-oauth2-profile.md
> +    scope         = urn:matrix:client:api:* urn:matrix:client:device:AAABBBCCCDDD &
```suggestion
    redirect_uri  = https%3A%2F%2Fapp.example.com%2Foauth2-callback &
    scope         = urn%3Amatrix%3Aclient%3Aapi%3A*+urn%3Amatrix%3Aclient%3Adevice%3AAAABBBCCCDDD &
```
These values would be URL encoded

2024-09-17 13:02 UTC, sandhose commented on proposals/2964-oauth2-profile.md
> +    scope         = urn:matrix:client:api:* urn:matrix:client:device:AAABBBCCCDDD &
I kept this part simplified with no URL-encoding and extra spaces. It might be worth saying that, and give the actual url-encoded, with no space added URL in addition

2024-09-17 13:02 UTC, sandhose commented on proposals/2964-oauth2-profile.md
> +  &redirect_uri=https://app.example.com/oauth2-callback
Same here, this is done for readability

2024-09-17 13:11 UTC, tonkku107 commented on proposals/2964-oauth2-profile.md
> +    scope         = urn:matrix:client:api:* urn:matrix:client:device:AAABBBCCCDDD &
The values are already listed above in their non-url-encoded format. The oauth specs also include line breaks in their examples but url-encode the values

2024-12-07 09:15 UTC, tonkku107 commented on proposals/2964-oauth2-profile.md
> +This MSC in particular defines how clients can leverage the OAuth 2.0 authorization code grant to gain access to the Matrix Client-to-Server API.
Since the rework, there is nothing specifying what clients should do when logging out

2025-01-20 11:59 UTC, Johennes commented on proposals/2964-oauth2-profile.md
> +It then constructs the authorization request URL using the `authorization_endpoint` value, with the following query parameters:
OAuth also has [Pushed Authorization Requests](https://datatracker.ietf.org/doc/html/rfc9126) which attempt to alleviate some of the issues of query parameters (see e.g. the [introduction of RFC9126](https://datatracker.ietf.org/doc/html/rfc9126#name-introduction)). I wonder if it'd be worth to consider these from the outset here?

2025-01-21 15:52 UTC, richvdh commented on proposals/2964-oauth2-profile.md
> +The client might include a login hint to what MXID the user is trying to use.
looks like `login_hint` has been removed altogether, so this thread is outdated

2025-01-21 15:57 UTC, richvdh commented on proposals/2964-oauth2-profile.md
> +# MSC2964: Matrix profile for OAuth 2.0
OAuth2 in general is now dealt with by https://github.com/matrix-org/matrix-spec-proposals/pull/3861, so further discussion on this, if needed, should happen there.

2025-01-22 00:17 UTC, turt2live commented on proposals/2964-oauth2-profile.md
> +This MSC in particular defines how clients can leverage the OAuth 2.0 authorization code grant to gain access to the Matrix Client-to-Server API.
https://github.com/matrix-org/matrix-spec-proposals/pull/4254

2025-01-22 08:59 UTC, sandhose commented on proposals/2964-oauth2-profile.md
> +It then constructs the authorization request URL using the `authorization_endpoint` value, with the following query parameters:
This is a good point, although because most Matrix clients will be public clients, we wouldn't really gain from the cryptographic integrity or confidentiality advantages PAR gives us. It would help us in two other ways though:

 - validating the authorisation request earlier, to possibly show a user-friendly error within the client
 - large authorisation requests, if we start having fine-grained authorisations

This is why for now, I'd prefer leaving them out of the proposal for the sake of simplicity, and introduce them later (probably alongside [RAR](https://datatracker.ietf.org/doc/html/rfc9396)) when we actually need it

2025-01-22 11:05 UTC, Johennes commented on proposals/2964-oauth2-profile.md
> +It then constructs the authorization request URL using the `authorization_endpoint` value, with the following query parameters:
Makes sense and sounds fair to me. 👍

2025-01-27 18:49 UTC, turt2live commented on proposals/2964-oauth2-profile.md
> +It then constructs the authorization request URL using the `authorization_endpoint` value, with the following query parameters:
(it would be good to have this alternative documented in the MSC)

2025-01-27 18:50 UTC, turt2live commented on proposals/2964-oauth2-profile.md
> +The scope definitions are out of scope of this MSC and are defined in [MSC2967](https://github.com/matrix-org/matrix-doc/pull/2967).
(considering resolved - if this feels untrue, please open a new thread)

2025-01-27 18:51 UTC, turt2live commented
MSCs proposed for Final Comment Period (FCP) should meet the requirements outlined in the [checklist](https://github.com/matrix-org/matrix-spec-proposals/blob/main/MSC_CHECKLIST.md) prior to being accepted into the spec. This checklist is a bit long, but aims to reduce the number of follow-on MSCs after a feature lands. 

SCT members: please check off things you check for, and raise a concern against FCP if the checklist is incomplete. If an item doesn't apply, prefer to check it rather than remove it. Unchecking items is encouraged where applicable.

Checklist:
- [ ] Are [appropriate implementation(s)](https://spec.matrix.org/proposals/#implementing-a-proposal)
  specified in the MSC’s PR description?
- [x] Are all MSCs that this MSC depends on already accepted?
- [x] For each new endpoint that is introduced:
  - [x] Have authentication requirements been specified?
  - [x] Have rate-limiting requirements been specified?
  - [x] Have guest access requirements been specified?
  - [x] Are error responses specified?
    - [x] Does each error case have a specified `errcode` (e.g. `M_FORBIDDEN`) and HTTP status code?
      - [x] If a new `errcode` is introduced, is it clear that it is new?
- [x] Will the MSC require a new room version, and if so, has that been made clear?
  - [x] Is the reason for a new room version clearly stated? For example,
          modifying the set of redacted fields changes how event IDs are calculated,
          thus requiring a new room version.
- [x] Are backwards-compatibility concerns appropriately addressed?
- [x] Are the [endpoint conventions](https://spec.matrix.org/latest/appendices/#conventions-for-matrix-apis) honoured?
  - [x] Do HTTP endpoints `use_underscores_like_this`?
  - [x] Will the endpoint return unbounded data? If so, has pagination been considered?
  - [x] If the endpoint utilises pagination, is it consistent with
    [the appendices](https://spec.matrix.org/v1.8/appendices/#pagination)?
- [x] An introduction exists and clearly outlines the problem being solved.
      Ideally, the first paragraph should be understandable by a non-technical audience.
- [ ] All outstanding threads are resolved
  - [ ] All feedback is incorporated into the proposal text itself, either as a fix or noted as an alternative
- [x] While the exact sections do not need to be present,
  the details implied by the proposal template are covered. Namely:
  - [x] Introduction
  - [x] Proposal text
  - [x] Potential issues
  - [x] Alternatives
  - [x] Dependencies
- [x] Stable identifiers are used throughout the proposal, except for the unstable prefix section
  - [x] Unstable prefixes [consider](README.md#unstable-prefixes) the awkward accepted-but-not-merged state
  - [x] Chosen unstable prefixes do not pollute any global namespace (use “org.matrix.mscXXXX”, not “org.matrix”).
- [x] Changes have applicable [Sign Off](CONTRIBUTING.md#sign-off) from all authors/editors/contributors
- [x] There is a dedicated "Security Considerations" section which detail
  any possible attacks/vulnerabilities this proposal may introduce, even if this is "None.".
  See [RFC3552](https://datatracker.ietf.org/doc/html/rfc3552) for things to think about,
  but in particular pay attention to the [OWASP Top Ten](https://owasp.org/www-project-top-ten/).

2025-01-27 18:51 UTC, turt2live commented
@mscbot fcp merge

2025-01-27 18:52 UTC, turt2live commented
@mscbot concern FCP checklist incomplete

2025-01-27 22:03 UTC, zecakeh commented on proposals/2964-oauth2-profile.md
> +This proposal requires the client to know the following authorization server metadata about the homeserver:
Don't we also need `code_challenge_methods_supported` for the PKCE methods?

2025-01-27 22:03 UTC, zecakeh commented on proposals/2964-oauth2-profile.md
> +- support PKCE as per [RFC7636]
Since it seems that using the `S256` method is required below, maybe it should be mentioned here?

2025-02-04 16:29 UTC, richvdh approved these changes
Since I don't understand how the nuclear reactor works, have some comments about the colour of the bikeshed.

It seems generally good to me!

2025-02-04 16:29 UTC, richvdh commented on proposals/2964-oauth2-profile.md
> +- Generate a random value for the `code_verifier`
```suggestion
It needs to generate the following values:

- a random value for the `state`
- a random value for the `code_verifier`
```

2025-02-04 16:29 UTC, richvdh commented on proposals/2964-oauth2-profile.md
> +- For web-based clients, this can be done through a rediretion or by opening the URL in a new tab
```suggestion
- For web-based clients, this can be done through a redirection or by opening the URL in a new tab
```

2025-02-04 16:29 UTC, richvdh commented on proposals/2964-oauth2-profile.md
> +Public clients with an HTTPS redirect URI must use the `fragment` response mode, as the fragment is not sent to the server in the redirect.
what exactly is meant by a "public client"? I can guess, but I think we should maybe be more explicit.

2025-02-04 16:29 UTC, richvdh commented on proposals/2964-oauth2-profile.md
> +---
unfortunately, github renders this hr rather heavily, making it look like we're starting a completely new chapter in the MSC. I think it's probably clearer to get rid of it.

Likewise elsewhere.

2025-02-04 16:29 UTC, richvdh commented on proposals/2964-oauth2-profile.md
> +User can register themselves by initiating a authorization code flow with the `prompt=create` parameter as defined in [Initiating User Registration via OpenID Connect 1.0](https://openid.net/specs/op
```suggestion
Users can register themselves by initiating an authorization code flow with the `prompt=create` parameter as defined in [Initiating User Registration via OpenID Connect 1.0](https://openid.net/specs/openid-connect-prompt-create-1_0.html).
```

2025-03-05 11:50 UTC, sandhose commented on proposals/2964-oauth2-profile.md
> +This proposal requires the client to know the following authorization server metadata about the homeserver:
because it's a *requirement*, I think the client can just assume the server supports it? I don't really have a strong opinion over this

2025-03-05 12:06 UTC, sandhose commented on proposals/2964-oauth2-profile.md
> +Public clients with an HTTPS redirect URI must use the `fragment` response mode, as the fragment is not sent to the server in the redirect.
This is because OAuth distinguishes public and confidential clients. Public clients don't have any private secret authenticating with them (like a 'client secret'). I don't think this distinction is useful in the Matrix use case for now at least, as all clients are public ones. Removed that in a26e7a63addb8ad7e618dbb03cd7f5423912ae25

2025-03-05 12:30 UTC, sandhose commented on proposals/2964-oauth2-profile.md
> +It then constructs the authorization request URL using the `authorization_endpoint` value, with the following query parameters:
Added that in the alternatives in cf170e00

2025-03-05 12:42 UTC, sandhose commented on proposals/2964-oauth2-profile.md
> +---
I've replaced those with subsections in 3fc09a67

2025-03-05 13:21 UTC, zecakeh commented on proposals/2964-oauth2-profile.md
> +This proposal requires the client to know the following authorization server metadata about the homeserver:
Ah I see what you mean. I don't have a strong opinion either, I was just trying to be thorough :wink:.

2025-03-11 18:40 UTC, richvdh requested changes

2025-03-11 18:40 UTC, richvdh commented on proposals/2964-oauth2-profile.md
> +- `scope` set to `urn:matrix:client:api:* urn:matrix:client:device:AAABBBCCCDDD` (as per [MSC2967])
could you clarify where this `AAABBBCCCDDD` comes from? Is the client expected to generate it? Presumably it needs to be unique? How can a client ensure that?

This is quite a difference from how things work in practice with `/login`. I know that `/login` allows you to specify a device_id, but it's rarely used.  If we want to change this model, it could do with more discussion than this implication.

2025-03-12 16:33 UTC, sandhose commented on proposals/2964-oauth2-profile.md
> +Clients with an HTTPS redirect URI must use the `fragment` response mode, as the fragment is not sent to the server in the redirect.
This is indeed not well written. Here "HTTPS redirect URI" is to mean "not using a custom redirect scheme" e.g. native apps. This is a recommendation as most web-based clients are client-side only, so we ideally don't want to disclose the `code` sent back in the parameters to the server. If we use query parameters they are sent to the web server, if we use the URL fragment, they are not

2025-03-12 16:39 UTC, sandhose commented on proposals/2964-oauth2-profile.md
> +Clients with an HTTPS redirect URI must use the `fragment` response mode, as the fragment is not sent to the server in the redirect.
I reworded this in 91f5b76e, please reopen if it's not clear enough

2025-03-18 14:07 UTC, sandhose commented on proposals/2964-oauth2-profile.md
> +- `scope` set to `urn:matrix:client:api:* urn:matrix:client:device:AAABBBCCCDDD` (as per [MSC2967])
I've 'moved' this discussion/decision in MSC2967. I've clarified what this scope means exactly in 484cff15

2025-03-18 14:45 UTC, richvdh approved these changes

2025-03-23 21:03 UTC, anoadragon453 approved these changes
All non-blocking concerns.

2025-03-25 17:39 UTC, clokep commented on proposals/2964-oauth2-profile.md
> +# MSC2964: Usage of OAuth 2.0 authorization code grant and refresh token grant
Is there anything Matrix specific about this MSC? It seems to be standard OIDC RFCs?

2025-03-26 08:12 UTC, sandhose commented on proposals/2964-oauth2-profile.md
> +# MSC2964: Usage of OAuth 2.0 authorization code grant and refresh token grant
What is specific to Matrix is the set of requirements, like

 - using the auth code grant (and not the implicit/hybrid flows)
 - use PKCE
 - refresh token rotation
 - strict redirect URI validation

You're right that this isn't defining anything new. OpenID also has 'profiles' (like [FAPI 2.0](https://openid.net/specs/fapi-security-profile-2_0-final.html)) which don't really define anything new, but rather set some strict requirements for a specific use

2025-03-26 12:28 UTC, clokep commented on proposals/2964-oauth2-profile.md
> +# MSC2964: Usage of OAuth 2.0 authorization code grant and refresh token grant
So this is defining a "profile" (a minimum set of features which must be supported) for Matrix?

2025-03-26 12:33 UTC, sandhose commented on proposals/2964-oauth2-profile.md
> +# MSC2964: Usage of OAuth 2.0 authorization code grant and refresh token grant
Kinda, yes. We don't have to adopt that vocabulary though. Profiles defined by some OpenID specs are shorter, as it is intended for people already familiar with OAuth/OIDC, so they can just say 'use X and Y with parameter A and B'

2025-03-31 16:56 UTC, anoadragon453 commented
@mscbot resolve FCP checklist incomplete

2025-04-05 18:41 UTC, merged

2025-05-25 11:22 UTC, zecakeh commented
spec PR: https://github.com/matrix-org/matrix-spec/pull/2150

2025-06-20 09:45 UTC, richvdh commented
> spec PR: [matrix-org/matrix-spec#2150](https://github.com/matrix-org/matrix-spec/pull/2150)

merged! :tada:

2025-08-14 17:18 UTC, noelportillo reviewed
Perfect thank you