MSC2965: [WIP] OIDC Provider discovery
matrix-org/matrix-spec-proposals pull request #2965
Opened 2021-01-14 17:11 UTC by sandhose

[Rendered](https://github.com/sandhose/matrix-doc/blob/sandhose/msc/oidc-discovery/proposals/2965-oidc-discovery.md)

2022-08-09 16:45 UTC, erlend-sh commented
> Keycloak in OIDC Playground
Are any other examples planned?

I’m using Ory for several apps that I’d like to also connect together with Matrix. It also strikes me as a conveniently lightweight example for Matrix, which also aligns well with Dendrite since it’s in Go.

2022-08-14 20:55 UTC, hughns commented
@erlend-sh Good suggestion, thank you - I've added https://github.com/vector-im/oidc-playground/issues/3 to track this.

2023-05-16 12:55 UTC, clokep commented on proposals/2965-oidc-discovery.md
> +The authentication server metadata can then be discovered by the client using [OpenID Connect Discovery 1.0](https://openid.net/specs/openid-connect-discovery-1_0.html) against the `issuer` field.
How does "normal" (non-Matrix) OIDC handle getting this metadata? Is `/.well-known/openid-configuration` standard? Or is this just always left to the protocol to negotiate?

2023-05-16 12:59 UTC, clokep commented on proposals/2965-oidc-discovery.md
> +- RECOMMENDED `id_token_hint` - ID Token (as previously issued by the issuer to the client) as a hint about the current authenticated user that is requesting to be able to manage their account. This
I'm finding this hard to follow, maybe the following is clearer? (I'm not sure it is accurate.)

```suggestion
- RECOMMENDED `id_token_hint` - An ID Token that was previously issued to the client; the issuer uses it as a hint for which user is requesting to manage their account. If the requesting user is not logged in then it is used as a login hint; if a different user/identity is already logged in then warn the user that they are accessing a different account.
```

2023-05-16 13:00 UTC, clokep commented on proposals/2965-oidc-discovery.md
> +Being unable to discover the authorization server from the Matrix Client API might be an issue in some cases.
This is a pretty big issue IMO. Can we fallback to a different location?

See also MSC3922?

2023-05-16 13:01 UTC, clokep commented on proposals/2965-oidc-discovery.md
> +The authentication server metadata can then be discovered by the client using [OpenID Connect Discovery 1.0](https://openid.net/specs/openid-connect-discovery-1_0.html) against the `issuer` field.
Looks like https://github.com/sandhose/matrix-doc/blob/msc/sandhose/oidc-discovery/proposals/2965-oidc-discovery.md#discovery-via-webfinger might answer my question.

2023-05-16 13:02 UTC, clokep commented on proposals/2965-oidc-discovery.md
> +Being unable to discover the authorization server from the Matrix Client API might be an issue in some cases.
And I see the Alternatives section below seems to cover this. 😄

2023-05-16 13:04 UTC, clokep commented on proposals/2965-oidc-discovery.md
> +The benefits of this approach are that it is standard and decouples the authentication server from the Matrix server: different authentication servers could be used by accounts on the server.
```suggestion
The benefits of this approach are that it is standard and decouples the authentication server from the Matrix server: different authentication servers could be used by different accounts on the server.
```

2023-05-16 13:05 UTC, clokep commented on proposals/2965-oidc-discovery.md
> +- the `.well-known` resource is dynamic, which can be harder to host/delegate & might conflict with other services like Mastodon
An alternative viewpoint is that it might mean you only need to setup a single endpoint to handle authentication for multiple services.

It is dynamic because you need to return the `subject` back in the response?

2023-05-16 13:05 UTC, clokep commented on proposals/2965-oidc-discovery.md
> +- this does not cover discovering the authentication server for user registration
Is this left to outside the OIDC standards?

2023-05-17 15:04 UTC, andybalaam commented on proposals/2965-oidc-discovery.md
> +  "end_session_edntpoint": "https://account.example.com/oauth2/logout",
Typo: `end_session_edntpoint` -> `end_session_endpoint`

2023-12-10 16:16 UTC, zecakeh commented on proposals/2965-oidc-discovery.md
> +GET /_matrix/client/v3/auth_issuer
Why `v3`? It's a new endpoint, shouldn't it be `v1`?

2024-02-22 09:49 UTC, richvdh commented on proposals/2965-oidc-discovery.md
> +- _REQUIRED_ `issuer`: the OpenID Connect Provider that is trusted by the homeserver
what should homeservers that do not use OIDC do here? Return a 404? With a matrix error code, or not?

We should specify exactly what responses mean "I don't do OIDC", so that clients can distinguish servers that don't do OIDC from those that are unreachable or having a transient problem.

We also need to be mindful of backwards-compatibility, of course.

2024-03-19 19:06 UTC, Johennes commented on proposals/2965-oidc-discovery.md
> +- _REQUIRED_ `issuer`: the OpenID Connect Provider that is trusted by the homeserver
I think I haven't seen this addressed anywhere but why does the mapping need to be 1:1? Could a homeserver not trust and work with several OPs letting the user choose between them?

2024-06-21 12:27 UTC, oliverpool commented on proposals/2965-oidc-discovery.md
> +- _REQUIRED_ `issuer`: the OpenID Connect Provider that is trusted by the homeserver
I agree. It is not uncommon to see multiple choices:
- Log in with GitHub
- Log in with Google
- Log in with ...

2024-11-16 13:39 UTC, bjorn3 commented
This is necessary for Element X to work with accounts on mozilla's matrix instance right, right?

2024-12-11 20:22 UTC, Tachi107 commented
Looking at [MSC3861](https://github.com/matrix-org/matrix-spec-proposals/pull/3861), it seems that fully using OpenID Connect isn't a goal. Hence, wouldn't implementing something based on the OAuth Authorization Server Metadata specification ([RFC 8414](https://datatracker.ietf.org/doc/html/rfc8414)), which is a generalization of OIDC Discovery, make more sense?

2025-01-17 16:26 UTC, sandhose commented
@Tachi107 This is a really good point! Unfortunately, the RFC states that applications must not use the general `.well-known/oauth-authorization-server` endpoint but rather set their own well-known document.

I've reworked the MSC to instead expose the authorization metadata directly as a C-S API endpoint

2025-01-20 19:31 UTC, tonkku107 commented on proposals/2965-auth-metadata.md
> +GET /_matrix/client/v1/auth_metadata
Could this endpoint also redirect to the `/.well-known/oauth-authorization-server` document on the issuer?

2025-01-22 00:32 UTC, turt2live requested changes
overall looks good to me - just a few (hopefully) easily correctable concerns

2025-01-22 00:32 UTC, turt2live commented on proposals/2965-auth-metadata.md
> +To avoid confusion with the existing `.well-known/matrix/*` documents, this proposal suggests defining a new C-S API endpoint instead.
we could still use `/.well-known/matrix/auth`, though I suppose the underlying question is whether the information is coming from the *server* or *API*: `.well-known` is before any resolution on the Client-Server API URLs, while `/_matrix` is after. It feels like there's equal arguments for either:

* `.well-known` would be nice for consistency with the RFC
* ... but that puts account management in the hands of the DNS holder (which is probably(?) better when using hosted services)
* ... but then the homeserver might be contacting a completely unrelated account server to verify users/actions/etc because it's not aware of the config change
* ... so we'd use a client-server API endpoint instead
* ... but that looks a bit weird when comparing to the RFC

(adding more rationale to the MSC would be appreciated)

2025-01-22 00:32 UTC, turt2live commented on proposals/2965-auth-metadata.md
> +GET /_matrix/client/v1/auth_metadata
Redirects generally aren't supported on Matrix APIs - it would be a bit weird to specify one for here. If it's the same information though, and considering it's (probably) without authentication, a smart reverse proxy may be able to simply intercept and serve the alternative resource, provided the formats are the same.

The use of `.well-known` is otherwise covered in the alternatives section.

2025-01-22 00:32 UTC, turt2live commented on proposals/2965-auth-metadata.md
> +A request on this endpoint should return a JSON object containing the authorization server metadata as defined in [RFC8414].
For checklist requirements:

```suggestion
A request on this endpoint should return a JSON object containing the authorization server metadata as defined in [RFC8414].
This endpoint does *not* require authentication, and MAY be rate limited per usual. 
```

2025-01-22 00:32 UTC, turt2live commented on proposals/2965-auth-metadata.md
> +None relevant.
If the MSC adds context around "controller" of resources (namely `.well-known` vs off the homeserver's Client-Server API), those details would be relevant here.

2025-01-22 00:32 UTC, turt2live commented on proposals/2965-auth-metadata.md
> +See individual proposals for more details on each field.
A list of the MSCs which apply here would be appreciated, at least to reference what kind of behaviour is attached. They *should not* become dependencies here though, I think.

2025-01-22 00:34 UTC, turt2live commented
MSCs proposed for Final Comment Period (FCP) should meet the requirements outlined in the [checklist](https://github.com/matrix-org/matrix-spec-proposals/blob/main/MSC_CHECKLIST.md) prior to being accepted into the spec. This checklist is a bit long, but aims to reduce the number of follow-on MSCs after a feature lands. 

SCT members: please check off things you check for, and raise a concern against FCP if the checklist is incomplete. If an item doesn't apply, prefer to check it rather than remove it. Unchecking items is encouraged where applicable.

Checklist:
- [ ] Are [appropriate implementation(s)](https://spec.matrix.org/proposals/#implementing-a-proposal)
  specified in the MSC’s PR description?
- [x] Are all MSCs that this MSC depends on already accepted?
- [ ] For each new endpoint that is introduced:
  - [ ] Have authentication requirements been specified?
  - [ ] Have rate-limiting requirements been specified?
  - [x] Have guest access requirements been specified?
  - [x] Are error responses specified?
    - [x] Does each error case have a specified `errcode` (e.g. `M_FORBIDDEN`) and HTTP status code?
      - [x] If a new `errcode` is introduced, is it clear that it is new?
- [x] Will the MSC require a new room version, and if so, has that been made clear?
  - [x] Is the reason for a new room version clearly stated? For example,
          modifying the set of redacted fields changes how event IDs are calculated,
          thus requiring a new room version.
- [x] Are backwards-compatibility concerns appropriately addressed?
- [x] Are the [endpoint conventions](https://spec.matrix.org/latest/appendices/#conventions-for-matrix-apis) honoured?
  - [x] Do HTTP endpoints `use_underscores_like_this`?
  - [x] Will the endpoint return unbounded data? If so, has pagination been considered?
  - [x] If the endpoint utilises pagination, is it consistent with
    [the appendices](https://spec.matrix.org/v1.8/appendices/#pagination)?
- [x] An introduction exists and clearly outlines the problem being solved.
      Ideally, the first paragraph should be understandable by a non-technical audience.
- [ ] All outstanding threads are resolved
  - [ ] All feedback is incorporated into the proposal text itself, either as a fix or noted as an alternative
- [x] While the exact sections do not need to be present,
  the details implied by the proposal template are covered. Namely:
  - [x] Introduction
  - [x] Proposal text
  - [x] Potential issues
  - [x] Alternatives
  - [x] Dependencies
- [x] Stable identifiers are used throughout the proposal, except for the unstable prefix section
  - [x] Unstable prefixes [consider](README.md#unstable-prefixes) the awkward accepted-but-not-merged state
  - [x] Chosen unstable prefixes do not pollute any global namespace (use “org.matrix.mscXXXX”, not “org.matrix”).
- [x] Changes have applicable [Sign Off](CONTRIBUTING.md#sign-off) from all authors/editors/contributors
- [x] There is a dedicated "Security Considerations" section which detail
  any possible attacks/vulnerabilities this proposal may introduce, even if this is "None.".
  See [RFC3552](https://datatracker.ietf.org/doc/html/rfc3552) for things to think about,
  but in particular pay attention to the [OWASP Top Ten](https://owasp.org/www-project-top-ten/).

2025-01-22 00:35 UTC, turt2live commented on proposals/2965-oidc-discovery.md
> +- this does not cover discovering the authentication server for user registration
(I think this is resolved with the rewrite - if not, please open a new thread)

2025-01-22 00:35 UTC, turt2live commented on proposals/2965-oidc-discovery.md
> +- the `.well-known` resource is dynamic, which can be harder to host/delegate & might conflict with other services like Mastodon
(I think this is resolved with the rewrite - if not, please open a new thread)

2025-01-22 00:36 UTC, turt2live commented on proposals/2965-oidc-discovery.md
> +- _REQUIRED_ `issuer`: the OpenID Connect Provider that is trusted by the homeserver
@sandhose this should probably be addressed, at least while the spec plans to support UIA (though deprecated) in the meantime.

2025-01-22 00:36 UTC, turt2live commented on proposals/2965-oidc-discovery.md
> +- _REQUIRED_ `issuer`: the OpenID Connect Provider that is trusted by the homeserver
(I think this is resolved with the rewrite - if not, please open a new thread)

2025-01-22 00:38 UTC, turt2live commented
Implementation lgtm. Concerns are relatively minor as well:

@mscbot fcp merge

2025-01-22 00:39 UTC, turt2live commented
@mscbot concern Error codes for not using OIDC
@mscbot concern Include rationale for Client-Server API endpoint over .well-known
@mscbot concern Checklist is incomplete

2025-01-22 11:09 UTC, sandhose commented on proposals/2965-auth-metadata.md
> +To avoid confusion with the existing `.well-known/matrix/*` documents, this proposal suggests defining a new C-S API endpoint instead.
We considered this, but I agree with Erik; this is why we didn't go for that solution

2025-01-22 13:38 UTC, sandhose commented on proposals/2965-auth-metadata.md
> +See individual proposals for more details on each field.
Have done that in 2aed234c

2025-01-22 13:40 UTC, sandhose commented on proposals/2965-oidc-discovery.md
> +- _REQUIRED_ `issuer`: the OpenID Connect Provider that is trusted by the homeserver
Have clarified that in 93d1b094

2025-01-22 14:24 UTC, sandhose commented on proposals/2965-auth-metadata.md
> +None relevant.
I've talked about the .well-known alternative in another section, didn't feel right in the 'security considerations'. Should I still add something here?

2025-01-25 23:38 UTC, turt2live commented on proposals/2965-auth-metadata.md
> +None relevant.
It's implied heavily enough where I don't think it's required to update the security considerations section.

2025-01-25 23:38 UTC, turt2live approved these changes
read-up-to marker

(thanks for keeping these updated)

2025-01-25 23:39 UTC, turt2live commented
@mscbot resolve Error codes for not using OIDC
@mscbot resolve Include rationale for Client-Server API endpoint over .well-known
@mscbot resolve Checklist is incomplete

2025-01-28 11:12 UTC, erikjohnston commented on proposals/2965-auth-metadata.md
> +This introduces a new Client-Server API endpoint to discover the authorization server metadata used by the homeserver.
Can we include a rationale for why we don't hardcode the endpoint URLs to be under a `/_matrix/oauth2` scheme? We still need the metdata discovery for other fields, so to an extent there is a question as to "why not", but still.

2025-02-04 13:24 UTC, richvdh commented on proposals/2965-auth-metadata.md
> +### Discovery via the well-known client discovery
Nit: it's server discovery rather than client discovery, if anything.

maybe:

```suggestion
### Discovery via existing `.well-known` mechanism

2025-02-04 13:24 UTC, richvdh commented on proposals/2965-auth-metadata.md
> +A new `m.authentication` field is added to this document to support OpenID Connect Provider (OP) discovery.
```suggestion
A previous version of this proposal suggested using the existing [homeserver discovery mechanism](https://spec.matrix.org/v1.13/client-server-api/#server-discovery) to discover the authentication server.

A new `m.authentication` field is added to the `.well-known` document to support OpenID Connect Provider (OP) discovery.
```

2025-02-04 15:34 UTC, clokep commented on proposals/2965-auth-metadata.md
> +The second option is also impractical, as all other Matrix APIs on this domain are prefixed with `/_matrix`, and it could easily be confused with the set of well-known documents hosted on the server
I don't understand this -- I think the thread (https://github.com/matrix-org/matrix-spec-proposals/pull/2965/files#r1924524746) talks about before/after finding the client API. That rationale seems to be missing here.

Frankly to me, I'd expect this to be under well-known.

2025-02-06 18:44 UTC, tonkku107 commented on proposals/2965-auth-metadata.md
> +**Note**: The fields required for the main flow outlined by [MSC3861] and its sub-proposals are:
Here we define some required fields for the matrix proposals but I think some clarity is needed on whether requirements from RFC8414 also apply.

2025-03-05 15:15 UTC, sandhose commented on proposals/2965-auth-metadata.md
> +This introduces a new Client-Server API endpoint to discover the authorization server metadata used by the homeserver.
I've added that in the alternatives section in 8719e6fc

2025-03-05 15:16 UTC, sandhose commented on proposals/2965-auth-metadata.md
> +In this case, clients should fall back to using the User-Interactive Authentication flows instead to authenticate the user.
Isn't `/login` *the* main *User-Interactive Authentication flow*?

2025-03-05 15:22 UTC, sandhose commented on proposals/2965-auth-metadata.md
> +## Rationale for not using a `.well-known` document
Makes sense, moved that in the alternatives section in c3137914

2025-03-11 09:51 UTC, tulir commented on proposals/2965-auth-metadata.md
> +In this case, clients should fall back to using the User-Interactive Authentication flows instead to authenticate the user.
`/login` doesn't use the UIA mechanism, it's basically a separate system that doesn't support multiple stages or other interactivity 🙃

2025-03-11 09:56 UTC, sandhose commented on proposals/2965-auth-metadata.md
> +In this case, clients should fall back to using the User-Interactive Authentication flows instead to authenticate the user.
Fair enough. My point here is to point at 'the existing auth and account management APIs', which includes:

 - `/login*`
 - `/refresh`
 - `/register`
 - `/logout*`
 - `/account/deactivate`
 - `/account/password`
 - `/account/3pid/add`
 - `/delete_devices`
 - `DELETE /devices/{id}`

Any suggestion how to phrase that?

2025-03-11 17:09 UTC, richvdh commented on proposals/2965-auth-metadata.md
> +The second option is also impractical, as all other Matrix APIs on this domain are prefixed with `/_matrix`, and it could easily be confused with the set of well-known documents hosted on the server
```suggestion
The second option would be very confusing, as all other Matrix APIs on the client-server domain are prefixed with `/_matrix`, whereas the existing `.well-known` documents ([`/.well-known/matrix/client`](https://spec.matrix.org/v1.13/client-server-api/#getwell-knownmatrixclient) and [`/.well-known/matrix/server`](https://spec.matrix.org/v1.13/server-server-api/#getwell-knownmatrixserver)) are hosted on the server name domain.
```

2025-03-11 17:10 UTC, richvdh commented on proposals/2965-auth-metadata.md
> +The second option is also impractical, as all other Matrix APIs on this domain are prefixed with `/_matrix`, and it could easily be confused with the set of well-known documents hosted on the server
maybe "impractical" isn't quite the right word here. It would certainly be confusing AF: the point is that `/.well-known/matrix/client` and `/.well-known/matrix/server` are both expected to be found on the *server name* domain.

I've proposed a clarification at https://github.com/matrix-org/matrix-spec-proposals/pull/2965#discussion_r1989772999 which might help.

2025-03-18 20:50 UTC, uhoreg commented on proposals/2965-auth-metadata.md
> +- `code_challenge_methods_supported` including the value `S256` ([MSC2964])
It would help with readability if you included a short description (one sentence or so) to describe what each of these fields does, so that we don't need to flip between so many MSCs.  Also, if you could include the titles of the MSCs (and RFC), that would be helpful too.

2025-03-29 22:01 UTC, merged

2025-05-24 14:25 UTC, zecakeh commented
spec PR: https://github.com/matrix-org/matrix-spec/pull/2147

2025-06-17 16:47 UTC, richvdh commented
> spec PR: [matrix-org/matrix-spec#2147](https://github.com/matrix-org/matrix-spec/pull/2147)

Merged!

2025-08-14 17:20 UTC, noelportillo reviewed
Yes look very good