MSC2966: [WIP] Usage of OAuth 2.0 Dynamic Client Registration in Matrix
matrix-org/matrix-spec-proposals pull request #2966
Opened 2021-01-14 17:12 UTC by sandhose

[Rendered](https://github.com/sandhose/matrix-doc/blob/sandhose/msc/oauth2-dynamic-registration/proposals/2966-oauth2-dynamic-registration)

2021-02-04 10:35 UTC, richvdh commented on proposals/2966-oauth2-dynamic-registration.md
> +| `redirect_uris`  | Array of redirection URIs for use in redirect-based flows                                                   | Required with the `authorization_code` grant ype | No          |
something I don't really understand here (or about OAuth2 dynamic registration in general):

What is to stop me, as an attacker, registering a "client" with branding (name, logo, etc) that looks like a trusted client, but with a redirect_uri that points to a site I control?

I then send the user a link which will take them through the login flow, and redirect back to my site. Assuming I can persaude the user to open the link, I can then harvest the authorization code and thence gain access to their account?

2021-02-04 14:14 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +| `redirect_uris`  | Array of redirection URIs for use in redirect-based flows                                                   | Required with the `authorization_code` grant ype | No          |
In this case the auth server would at least prompt for explicit consent as it would be considered as a separate client from the legitimate one.

One thing that could be enforced would be to have the different URIs (at least `redirect_uris` and `client_uri`) to be on the same origin. Quoting from [RFC 7591 sec. 5](https://tools.ietf.org/html/rfc7591#section-5):

> In a situation where the authorization server is supporting open client registration, it must be extremely careful with any URL provided by the client that will be displayed to the user (e.g., `logo_uri`, `tos_uri`, `client_uri`, and `policy_uri`).  For instance, a rogue client could specify a registration request with a reference to a drive-by download in the `policy_uri`, enticing the user to click on it during the authorization.  The authorization server SHOULD check to see if the `logo_uri`, `tos_uri`, `client_uri`, and `policy_uri` have the same host and scheme as the those defined in the array of `redirect_uris` and that all of these URIs resolve to valid web pages.

2021-02-04 14:38 UTC, richvdh commented on proposals/2966-oauth2-dynamic-registration.md
> +| `redirect_uris`  | Array of redirection URIs for use in redirect-based flows                                                   | Required with the `authorization_code` grant ype | No          |
> In this case the auth server would at least prompt for explicit consent as it would be considered as a separate client from the legitimate one.

of course; but how is the user meant to tell that they are now being asked for consent to a phishing app?

> One thing that could be enforced would be to have the different URIs (at least redirect_uris and client_uri) to be on the same origin.

Wouldn't this preclude the use of desktop clients, which often register custom URI schemes to get the auth code back from a browser to the client?

2021-02-13 12:33 UTC, richvdh commented on proposals/2966-oauth2-dynamic-registration.md
> +| `redirect_uris`  | Array of redirection URIs for use in redirect-based flows                                                   | Required with the `authorization_code` grant ype | No          |
As discussed elsewhere: it turns out that on Windows and MacOS at least, desktop apps *can* register for parts of the `https://` namespace. So that only really leaves Linux where you can only register for an entire URI scheme (via an [`x-scheme-handler/...` mimetype](https://specifications.freedesktop.org/shared-mime-info-spec/shared-mime-info-spec-latest.html#idm45094474779648)).

So it should be possible to create a system which makes this look user-friendly for everyone except Linux users, who presumably are a bit more comfortable with obscure URIs anyway.

2021-02-13 13:29 UTC, richvdh commented on proposals/2966-oauth2-dynamic-registration.md
> +The client registration endpoint is advertised in the OIDC discovery document and can be used as per [RFC 7591 sec. 3](https://tools.ietf.org/html/rfc7591#section-3).
I'm sure this is obvious if you're familiar with OAuth2, but for context I'd find it really helpful if you could clarify *when* a client would register itself with a given server in the context of Matrix.  Presumably, whenever the user chooses a homeserver to log into? (Is the client expected to remember a list of homeservers it has registered against?)

2023-02-24 15:54 UTC, deepbluev7 commented on proposals/2966-oauth2-dynamic-registration.md
> +| `policy_uri`     | URL that points to a human-readable policy document for the client                                          | Required                                         | Yes         |
Does this mean, that for any client I develop, I now need infrastructure and domains to host these documents, as I assume these need to be web accessible? Currently you don't need any of that, since the client doesn't send any data to the client developer and doesn't provide any service, where ToS make any sense. But now to be able to sign in with my self written client, I need to host a website? That doesn't sound like "Simpler for Homeservers and clients to implement" from MSC3861 at all.

2023-02-24 15:54 UTC, deepbluev7 commented on proposals/2966-oauth2-dynamic-registration.md
> +| `redirect_uris`  | Array of redirection URIs for use in redirect-based flows                                                   | Required with the `authorization_code` grant ype | No          |
My client generates a localhost address on demand during SSO currently. This MSC makes it sound like I need to switch to a fixed schema instead, which means running multiple instances of my software in parallel will become much harder. How would I solve having 2 separate instances of my app running and I want to only sign into one of them?

2023-02-24 15:54 UTC, deepbluev7 commented on proposals/2966-oauth2-dynamic-registration.md
> +This is done by encoding the client metadata in a JWT and signing it.
How do I include such data in my open-source project? Because this would allow either everyone to make themselves look like my client or I can't distribute my software freely anymore, can I? Is there some documentation on why this is secure for desktop applications, that I could read? Or what "securely identify" means in this context as in what it is protecting against?

2023-02-24 15:54 UTC, deepbluev7 commented on proposals/2966-oauth2-dynamic-registration.md
> +If an authorization server allows unsigned clients, the number of client registration might explode exponentially.
Why is this a problem?

2023-02-24 16:10 UTC, MTRNord commented on proposals/2966-oauth2-dynamic-registration.md
> +| `policy_uri`     | URL that points to a human-readable policy document for the client                                          | Required                                         | Yes         |
Also often community clients are deliberately NOT a service provider. So why would they need a ToS if there is no Service?

For example Apache2 comes with this disclaimer in the license:

> Unless required by applicable law or agreed to in writing, software
> distributed under the License is distributed on an "AS IS" BASIS,
> WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
> See the License for the specific language governing permissions and
> limitations under the License.

So clearly there is no service provided.

2023-02-24 16:13 UTC, MTRNord commented on proposals/2966-oauth2-dynamic-registration.md
> +If an authorization server allows unsigned clients, the number of client registration might explode exponentially.
I don't think this should be problem, imho. This is the whole goal of an open ecosystem like matrix. Anyone at any time can build a client and use it. You are not vendor bound. Allowing this to be restricted imho goes against the core idea of an open ecosystem which matrix tries to be.

2023-08-04 13:06 UTC, zecakeh commented on proposals/2966-oauth2-dynamic-registration.md
> +This is done by encoding the client metadata in a JWT and signing it.
It is not said _how_ the JWT is sent during registration. Looking at RFC7591, my guess is this what is called a software statement, but it should be said clearly.

2024-09-17 14:29 UTC, tonkku107 commented on proposals/2966-oauth2-dynamic-registration.md
> +For example, if the `client_uri` is `https://example.com/`, then one of the `redirect_uris` can be `https://example.com/callback` or `https://app.example.com/callback`, but not `https://app.com/callb
For a self-hostable web client like Element web, the recommended uri would be `element.io` but if I host an instance of it on `example.com`, I wouldn't be able to set a proper `redirect_uri` with the recommended uri.
How important is this requirement really? What about informing the user about the differing host in the redirect uri during authorization?
Of course clients could also bundle in their landing pages and policies or set up a redirect to work around the issue.

2024-09-17 14:29 UTC, tonkku107 commented on proposals/2966-oauth2-dynamic-registration.md
> +To use this grant, along with refresh tokens:
This makes it sound like the items below are extra requirements to get a refresh token

2024-09-17 14:29 UTC, tonkku107 commented on proposals/2966-oauth2-dynamic-registration.md
> +**Note**: in this example, the server has not registered the locale-specific values for `client_name`, `tos_uri`, and `policy_uri`, which is why they are not present in the response.
Maybe it'd be useful to add examples which show that the server could ignore any values, not just localized ones (except required values specified in this MSC) or choose to modify values. For example a homeserver could ignore the `grant_types` sent by the client and register that it has access to any supported `grant_types` for a simpler implementation (at least according to RFC 7591)

2024-12-09 09:00 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +For example, if the `client_uri` is `https://example.com/`, then one of the `redirect_uris` can be `https://example.com/callback` or `https://app.example.com/callback`, but not `https://app.com/callb
I think this is a feature, not a bug. "element.mycompany.corp" is "Element Web hosted by MyCompany", as there are no assurance that it's an untempered Element Web hosted by Element the company

2025-01-16 11:04 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +| `redirect_uris`  | Array of redirection URIs for use in redirect-based flows                                                   | Required with the `authorization_code` grant ype | No          |
> My client generates a localhost address on demand during SSO currently. This MSC makes it sound like I need to switch to a fixed schema instead, which means running multiple instances of my software in parallel will become much harder. How would I solve having 2 separate instances of my app running and I want to only sign into one of them?

This is covered by the "Native clients" part of this spec: apps can register `localhost` without port, and the server must accept a dynamic port during the authorisation

2025-01-16 11:46 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +| `policy_uri`     | URL that points to a human-readable policy document for the client                                          | Required                                         | Yes         |
This requirement has been lifted, they are not required anymore

2025-01-16 11:46 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +This is done by encoding the client metadata in a JWT and signing it.
I've removed the signed metadata part of the MSC

2025-01-16 11:48 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +This is done by encoding the client metadata in a JWT and signing it.
Removed the metadata signature from the MSC, will be addressed in a separate one

2025-01-16 12:50 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +**Note**: in this example, the server has not registered the locale-specific values for `client_name`, `tos_uri`, and `policy_uri`, which is why they are not present in the response.
I adapted the example and stated that the server must ignore unknown metadata/values in 4deb3c85

2025-01-22 00:59 UTC, turt2live requested changes
overall this looks good, though I think it needs implementations to be able to move to FCP. I'll document those requirements in a separate review.

2025-01-22 00:59 UTC, turt2live commented on proposals/2966-oauth2-dynamic-registration.md
> +This page should be able to be accessed without requiring authentication.
I believe this is all covered by the RFC:

```suggestion
Per [RFC 7591](https://tools.ietf.org/html/rfc7591), the `client_uri` MUST be a valid URL
that SHOULD give the user more information about the client. This URL SHOULD NOT
require authentication to access.
```

2025-01-22 00:59 UTC, turt2live commented on proposals/2966-oauth2-dynamic-registration.md
> +For example, if the `client_uri` is `https://example.com/`, then one of the `redirect_uris` can be `https://example.com/callback` or `https://app.example.com/callback`, but not `https://app.com/callb
Not for the MSC text, but Element Web could add an `/about` route that it ships for this purpose.

2025-01-22 00:59 UTC, turt2live commented on proposals/2966-oauth2-dynamic-registration.md
> + - `policy_uri`: URL that points to a human-readable policy document for the client
blocking: what is the difference between policy and terms of service?

2025-01-22 00:59 UTC, turt2live commented on proposals/2966-oauth2-dynamic-registration.md
> +The homeserver must support the `none` value for the `token_endpoint_auth_method`, as most Matrix clients are client-side only, do not have a server component, and therefore are public clients.
```suggestion
The homeserver MUST support the `none` value for the `token_endpoint_auth_method`, as most Matrix clients are client-side only, do not have a server component, and therefore are public clients.
```

2025-01-22 00:59 UTC, turt2live commented on proposals/2966-oauth2-dynamic-registration.md
> + - the `grant_types` must include `authorization_code` and `refresh_token`
```suggestion
 - the `redirect_uris` MUST have at least one value
 - the `response_types` MUST include `code`
 - the `grant_types` MUST include `authorization_code` and `refresh_token`
```

2025-01-22 00:59 UTC, turt2live commented on proposals/2966-oauth2-dynamic-registration.md
> +The client must store the `client_id` for future use.
Mentioned in the umbrella MSC: does the client need to remember this over multiple browsers/sessions, or just while the single user session logs in?

2025-01-22 01:00 UTC, turt2live commented on proposals/2966-oauth2-dynamic-registration.md
Implementation requirements:
* [ ] Client using `web` flow
* [ ] Client using `native` flow
* [ ] Server supporting both flows (may be two different servers)

2025-01-22 01:02 UTC, turt2live commented on proposals/2966-oauth2-dynamic-registration.md
> +The discovery of the above metadata is out of scope for this MSC and is currently covered by [MSC2965](https://github.com/matrix-org/matrix-doc/pull/2965).
presumably if there's no `registration_endpoint`, the server doesn't support dynamic client registration. That should be documented in the MSC as a thing clients should expect.

2025-01-22 13:02 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +The discovery of the above metadata is out of scope for this MSC and is currently covered by [MSC2965](https://github.com/matrix-org/matrix-doc/pull/2965).
I'm not sure how to handle this. Basically there are two possibilities:

 - make client registration mandatory. That would be aligned with the 'openness' of Matrix, as you should be able to use any client with any compliant server. Not supporting this would then mean the server not spec-compliant?
 - make it optional and explain here what this means. This makes it clearer in the spec that its possible to use this in 'closed' ecosystems, where servers impose which client is allowed to use it

2025-01-25 23:31 UTC, turt2live commented on proposals/2966-oauth2-dynamic-registration.md
> + - `policy_uri`: URL that points to a human-readable policy document for the client
ah, alright. If they're from the RFC then let's just copy them.

2025-01-25 23:34 UTC, turt2live commented on proposals/2966-oauth2-dynamic-registration.md
> +The discovery of the above metadata is out of scope for this MSC and is currently covered by [MSC2965](https://github.com/matrix-org/matrix-doc/pull/2965).
hmm, looks like MSC2965 marks it required (and I just missed that), so would definitely lean towards openness. Something we may need to clarify in the spec PR (rather than MSC) is that "registration" is just so the client can talk to the server, not for creating new accounts. The client may still be unable to create new accounts or log in to existing accounts later in the process.

2025-01-25 23:41 UTC, turt2live commented on proposals/2966-oauth2-dynamic-registration.md
> +| `redirect_uris`  | Array of redirection URIs for use in redirect-based flows                                                   | Required with the `authorization_code` grant ype | No          |
(considering thread as resolved - if this feels untrue, please open a new thread)

2025-01-25 23:41 UTC, turt2live commented on proposals/2966-oauth2-dynamic-registration.md
> +The client registration endpoint is advertised in the OIDC discovery document and can be used as per [RFC 7591 sec. 3](https://tools.ietf.org/html/rfc7591#section-3).
(considering thread as resolved - if this feels untrue, please open a new thread)

2025-01-25 23:41 UTC, turt2live commented on proposals/2966-oauth2-dynamic-registration.md
> +If an authorization server allows unsigned clients, the number of client registration might explode exponentially.
(considering thread as resolved - if this feels untrue, please open a new thread)

2025-01-25 23:42 UTC, turt2live commented on proposals/2966-oauth2-dynamic-registration.md
> +For example, if the `client_uri` is `https://example.com/`, then one of the `redirect_uris` can be `https://example.com/callback` or `https://app.example.com/callback`, but not `https://app.com/callb
(considering thread as resolved - if this feels untrue, please open a new thread)

2025-01-25 23:54 UTC, turt2live commented on proposals/2966-oauth2-dynamic-registration.md
I haven't dug too far to find all the PRs or original implementations, but did find these points of evidence:
* https://github.com/matrix-org/matrix-js-sdk/pull/4070 (for Element Web via https://github.com/matrix-org/matrix-react-sdk/pull/12257 )
* https://github.com/element-hq/element-desktop/pull/1662
* https://github.com/matrix-org/matrix-rust-sdk/pull/2412
* The dendrite PR above

2025-01-25 23:55 UTC, turt2live commented
MSCs proposed for Final Comment Period (FCP) should meet the requirements outlined in the [checklist](https://github.com/matrix-org/matrix-spec-proposals/blob/main/MSC_CHECKLIST.md) prior to being accepted into the spec. This checklist is a bit long, but aims to reduce the number of follow-on MSCs after a feature lands. 

SCT members: please check off things you check for, and raise a concern against FCP if the checklist is incomplete. If an item doesn't apply, prefer to check it rather than remove it. Unchecking items is encouraged where applicable.

Checklist:
- [x] Are [appropriate implementation(s)](https://spec.matrix.org/proposals/#implementing-a-proposal)
  specified in the MSC’s PR description?
- [x] Are all MSCs that this MSC depends on already accepted?
- [x] For each new endpoint that is introduced:
  - [x] Have authentication requirements been specified?
  - [x] Have rate-limiting requirements been specified?
  - [x] Have guest access requirements been specified?
  - [x] Are error responses specified?
    - [x] Does each error case have a specified `errcode` (e.g. `M_FORBIDDEN`) and HTTP status code?
      - [x] If a new `errcode` is introduced, is it clear that it is new?
- [x] Will the MSC require a new room version, and if so, has that been made clear?
  - [x] Is the reason for a new room version clearly stated? For example,
          modifying the set of redacted fields changes how event IDs are calculated,
          thus requiring a new room version.
- [x] Are backwards-compatibility concerns appropriately addressed?
- [x] Are the [endpoint conventions](https://spec.matrix.org/latest/appendices/#conventions-for-matrix-apis) honoured?
  - [x] Do HTTP endpoints `use_underscores_like_this`?
  - [x] Will the endpoint return unbounded data? If so, has pagination been considered?
  - [x] If the endpoint utilises pagination, is it consistent with
    [the appendices](https://spec.matrix.org/v1.8/appendices/#pagination)?
- [x] An introduction exists and clearly outlines the problem being solved.
      Ideally, the first paragraph should be understandable by a non-technical audience.
- [x] All outstanding threads are resolved
  - [x] All feedback is incorporated into the proposal text itself, either as a fix or noted as an alternative
- [x] While the exact sections do not need to be present,
  the details implied by the proposal template are covered. Namely:
  - [x] Introduction
  - [x] Proposal text
  - [x] Potential issues
  - [x] Alternatives
  - [x] Dependencies
- [x] Stable identifiers are used throughout the proposal, except for the unstable prefix section
  - [x] Unstable prefixes [consider](README.md#unstable-prefixes) the awkward accepted-but-not-merged state
  - [x] Chosen unstable prefixes do not pollute any global namespace (use “org.matrix.mscXXXX”, not “org.matrix”).
- [x] Changes have applicable [Sign Off](CONTRIBUTING.md#sign-off) from all authors/editors/contributors
- [x] There is a dedicated "Security Considerations" section which detail
  any possible attacks/vulnerabilities this proposal may introduce, even if this is "None.".
  See [RFC3552](https://datatracker.ietf.org/doc/html/rfc3552) for things to think about,
  but in particular pay attention to the [OWASP Top Ten](https://owasp.org/www-project-top-ten/).

2025-01-25 23:56 UTC, turt2live approved these changes

2025-01-25 23:56 UTC, turt2live commented
@mscbot fcp merge

2025-01-27 22:21 UTC, zecakeh commented on proposals/2966-oauth2-dynamic-registration.md
> +It SHOULD reuse the `client_id` for all future authorization requests done against the same homeserver.
So to be clear, the client should associate the `client_id` to the server name of the homeserver? The `issuer` field from [RFC8414](https://datatracker.ietf.org/doc/html/rfc8414) is ignored, since it doesn't appear to be mentioned in any MSC?

Won't that complicate the migration of current implementations that should have associated their `client_id` to the `issuer`?

2025-01-28 17:25 UTC, richvdh commented on proposals/2966-oauth2-dynamic-registration.md
> +This URL SHOULD NOT require authentication to access.
is `client_uri` required? 

If not, some "If present" wording would be helpful, and explain how the constraints on the other URIs work when it is absent.

If it is required, call it out explicitly, and maybe say what should happen if it's not there?

2025-01-28 17:25 UTC, richvdh commented on proposals/2966-oauth2-dynamic-registration.md
> +In all cases, the redirect URI MUST not have a fragment component.
```suggestion
In all cases, the redirect URI MUST NOT have a fragment component.
```

2025-01-28 17:25 UTC, richvdh commented on proposals/2966-oauth2-dynamic-registration.md
> +    - the URI MUST not have an authority component. This means that it MUST have either a single slash or none immediately following the scheme, with no hostname, username, or port.
```suggestion
    - the URI MUST NOT have an authority component. This means that it MUST have either a single slash or none immediately following the scheme, with no hostname, username, or port.
```

2025-01-28 17:25 UTC, richvdh commented on proposals/2966-oauth2-dynamic-registration.md
> +    - it MUST have no port registered. The homeserver MUST then accept any port number during the authorization flow.
```suggestion
    - it (the registered redirect URI) MUST NOT contain a port number. The homeserver MUST then accept any port number during the authorization flow.
```

2025-01-28 17:25 UTC, richvdh commented on proposals/2966-oauth2-dynamic-registration.md
> +This is what the following [*OAuth Client ID Metadata Document* draft](https://datatracker.ietf.org/doc/html/draft-parecki-oauth-client-id-metadata-document) proposes.
```suggestion
This is what the [*OAuth Client ID Metadata Document* draft](https://datatracker.ietf.org/doc/html/draft-parecki-oauth-client-id-metadata-document) proposes.
```

2025-01-28 17:25 UTC, richvdh commented on proposals/2966-oauth2-dynamic-registration.md
> +This is what the following [*OAuth Client ID Metadata Document* draft](https://datatracker.ietf.org/doc/html/draft-parecki-oauth-client-id-metadata-document) proposes.
or:

```suggestion
This is what the following document proposes: [*OAuth Client ID Metadata Document* draft](https://datatracker.ietf.org/doc/html/draft-parecki-oauth-client-id-metadata-document).
```

2025-03-05 16:47 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +
That's a good suggestion, thanks!

2025-03-05 16:49 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +
Woops, thanks! Fixed in fae9c291

2025-03-05 16:51 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +This URL SHOULD NOT require authentication to access.
Clarified that it is required in `f3d30e96`

2025-03-05 16:57 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> + - `http://localhost:1234/callback`
Oh, those were supposed to be sub-sections of `Redirect URI validation`. Fixed in 1768d54f

2025-03-05 17:07 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +    - it MUST have no port registered. The homeserver MUST then accept any port number during the authorization flow.
a98b2ba1

2025-03-05 17:09 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +It MUST ignore fields, `grant_types` and `response_types` that are not understood by the server.
Clarified that in 6e32a716

2025-03-05 17:12 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +It SHOULD reuse the `client_id` for all future authorization requests done against the same homeserver.
Makes sense, I think the reason I did it this way is so that the fields in the request example make more sense if they are defined before?

2025-03-11 15:14 UTC, erikjohnston commented on proposals/2966-oauth2-dynamic-registration.md
> +Per [RFC 7591](https://tools.ietf.org/html/rfc7591), the `client_uri` MUST be a valid URL that SHOULD give the user more information about the client.
I'm unsure about requiring a client URI, as it means authors of all clients *must* have a website of some form. Given e.g. `client_name` is optional, what's the rationale of requiring `client_uri`?

Some homeservers may wish to try and lock down which clients can use them, but I think that is a special case.

2025-03-11 15:14 UTC, erikjohnston commented on proposals/2966-oauth2-dynamic-registration.md
> + - MUST omit the port (to use the default port for https: 443)
Why can't we use redirect URLs on different ports?

2025-03-11 15:14 UTC, erikjohnston commented on proposals/2966-oauth2-dynamic-registration.md
> +A subsequent MSC could be proposed to identify multiple instances of the same client using signed client metadata.
Presumably the server can deduplicate clients that register with the exact same JSON?

2025-03-11 15:14 UTC, erikjohnston commented on proposals/2966-oauth2-dynamic-registration.md
> +This means that the number of client registrations will grow exponentially.
Yeah, I think we should allow clearing up of registered clients that are not used by any sessions?

I think to do so we'd need some response type when the client tries and uses a deleted `client_id`?

2025-03-11 15:14 UTC, erikjohnston commented on proposals/2966-oauth2-dynamic-registration.md
> +This approach has the advantage of being able to use the same `client_id` for different instances of the same client, but it has the disadvantage of requiring the client to host a JSON file on its ow
If `client_uri` is mandatory, then hosting a JSON file isn't really a big concern no? Though personally I think we shouldn't require a `client_uri` if we don't need to.

2025-03-11 15:14 UTC, erikjohnston commented on proposals/2966-oauth2-dynamic-registration.md
> +A good example of this is if a mobile client distributed through an app store registers the `app.acme.corp:` scheme in an effort to impersonate "ACME Corp's" app, then "ACME Corp" would have a valid
This doesn't protect against clients using localhost schemes? Or against clients that have embedded browsers that can intercept any scheme? Doesn't android allow you to intercept any/all URL loads for embedded web views?

TBH, I'm wondering whether this whole section should just be "the server cannot trust that the client is who they say they are".

2025-03-11 17:48 UTC, richvdh commented on proposals/2966-oauth2-dynamic-registration.md
> +It SHOULD reuse the `client_id` for all future authorization requests done against the same homeserver.
I think it's fine, and normal, for an example to reference fields that haven't been defined yet.

Again, not insisting on a change

2025-03-13 09:18 UTC, t3chguy commented on proposals/2966-oauth2-dynamic-registration.md
> +For example, if the `client_uri` is `https://example.com/`, then one of the `redirect_uris` can be `https://example.com/callback` or `https://app.example.com/callback`, but not `https://app.com/callb
Also seems like no consideration has gone into protocol & port components of the URI, do those have to match too?

2025-03-13 09:22 UTC, t3chguy commented on proposals/2966-oauth2-dynamic-registration.md
> + - MUST omit the port (to use the default port for https: 443)
Yeah agreed, this breaks the ability to test local development builds running in vite server, webpack dev server etc, especially if user lacks root access.

Also makes it harder to do CI end to end tests where we may need to use multiple ports at once to parallelise.

2025-03-13 09:26 UTC, t3chguy commented on proposals/2966-oauth2-dynamic-registration.md
> +For example, if the `client_uri` is `https://example.com/`, then one of the `redirect_uris` can be `https://example.com/callback` or `https://app.example.com/callback`, but not `https://app.com/callb
If the URI is on a child subdomain does the path matter? Does the path matter at all? It says "common base" and that seems to imply caring about path but I don't see any examples around that

2025-03-13 15:18 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +For example, if the `client_uri` is `https://example.com/`, then one of the `redirect_uris` can be `https://example.com/callback` or `https://app.example.com/callback`, but not `https://app.com/callb
This is an attempt to mitigate as much as possible client impersonation. This is so that I cannot claim to be 'https://element.io/' if my redirect URI is 'https://evil.com/callback'

This is what the RFC says in the security considerations:

>   In a situation where the authorization server is supporting open
   client registration, it must be extremely careful with any URL
   provided by the client that will be displayed to the user (e.g.,
   "logo_uri", "tos_uri", "client_uri", and "policy_uri").  For
   instance, a rogue client could specify a registration request with a
   reference to a drive-by download in the "policy_uri", enticing the
   user to click on it during the authorization.  The authorization
   server SHOULD check to see if the "logo_uri", "tos_uri",
   "client_uri", and "policy_uri" have the same host and scheme as the
   those defined in the array of "redirect_uris" and that all of these
   URIs resolve to valid web pages.

On the scheme, I think we should clarify that all the URIs (except the redirect_uris) must be `https`, should be pointing to HTML web pages (except for the logo_uri)

On the port, I think we can relax the requirement and allow any port, and not require to match between the URIs

2025-03-13 15:21 UTC, t3chguy commented on proposals/2966-oauth2-dynamic-registration.md
> +For example, if the `client_uri` is `https://example.com/`, then one of the `redirect_uris` can be `https://example.com/callback` or `https://app.example.com/callback`, but not `https://app.com/callb
> I think we should clarify that all the URIs (except the redirect_uris) must be https, should be pointing to HTML web pages (except for the logo_uri)

So TOS & Policy can't be PDFs or other document formats? That seems like an odd restriction to state in the Matrix spec.

2025-03-13 15:22 UTC, t3chguy commented on proposals/2966-oauth2-dynamic-registration.md
> +For example, if the `client_uri` is `https://example.com/`, then one of the `redirect_uris` can be `https://example.com/callback` or `https://app.example.com/callback`, but not `https://app.com/callb
Shouldn't we also limit then the format allowed on `logo_uri` so it is something that the likes of MAS is capable of rendering? Or are CR3 files fine?

2025-03-13 15:23 UTC, t3chguy commented on proposals/2966-oauth2-dynamic-registration.md
> +For example, if the `client_uri` is `https://example.com/`, then one of the `redirect_uris` can be `https://example.com/callback` or `https://app.example.com/callback`, but not `https://app.com/callb
> On the port, I think we can relax the requirement and allow any port, and not require to match between the URIs

Note to self, the fixup I just landed in js-sdk does not forbid port but does check that they match

2025-03-13 15:32 UTC, t3chguy commented on proposals/2966-oauth2-dynamic-registration.md
> +For example, if the `client_uri` is `https://example.com/`, then one of the `redirect_uris` can be `https://example.com/callback` or `https://app.example.com/callback`, but not `https://app.com/callb
> So TOS & Policy documents can't be PDFs or other document formats? That seems like an odd restriction to state in the Matrix spec.

Seems like Element already uses PDFs as privacy docs e.g. for IS: https://static.element.io/legal/identity-server-privacy-policy.pdf

2025-03-13 15:40 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +If provided by the client, the homeserver SHOULD show or link to the `tos_uri` and `policy_uri` to the user.
Good suggestion, did that in 8b2f387b

2025-03-13 15:41 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +For example, if the `client_uri` is `https://example.com/`, then one of the `redirect_uris` can be `https://example.com/callback` or `https://app.example.com/callback`, but not `https://app.com/callb
I have relaxed the requirement on the port in 03ba6f2d

2025-03-13 15:42 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> + - MUST omit the port (to use the default port for https: 443)
Relaxed in 03ba6f2d4db81a8e79b286254365f6230eeb7817

2025-03-13 15:52 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +Per [RFC 7591](https://tools.ietf.org/html/rfc7591), the `client_uri` MUST be a valid URL that SHOULD give the user more information about the client.
The whole reason of this section is to mitigate client impersonation as much as possible.

A web client claiming to be 'Element' will not be able to use `https://element.io/` as client URI unless they can host their client in a subdomain of element.io. We display that client_uri to the end user, so that they can have some trust with it, without displaying the (potentially ugly and more technical) redirect_uri to build that same trust.

It does not mean having to have a proper dedicated domain name, free/shared hosting services will work. MAS will use the public suffix list to know whether a client can claim a domain or not, to allow for example `https://myclient.github.io/` (but not `https://github.io/`) as `client_uri`

Of course this cannot be bulletproof, as described in the 'security considerations' section

2025-03-13 15:53 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +A subsequent MSC could be proposed to identify multiple instances of the same client using signed client metadata.
This is an implementation detail but yes.

Signed client metadata would potentially allow changing this metadata over time as needed

2025-03-13 15:59 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +This means that the number of client registrations will grow exponentially.
'Exponentially' is indeed wrong here. Fixed that in 6b03a534

Problem is, with the current proposal, we don't really have a way to notice that until we redirected to the homeserver, and we usually don't want to redirect back to the client if we don't trust the redirect_uri provided…

If we wanted to implement 'garbage collection' of client IDs, we should use [RFC9126 pushed access requests](https://datatracker.ietf.org/doc/html/rfc9126), so that we can give feedback that the client_id is invalid right away, before the redirect.

I would leave that as a future improvement though, I'm not too concern about the number of registration completely exploding

2025-03-13 16:03 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +This means that the number of client registrations will grow exponentially.
I've added words on how to mitigate in b6abea5f

2025-03-13 16:09 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +This approach has the advantage of being able to use the same `client_id` for different instances of the same client, but it has the disadvantage of requiring the client to host a JSON file on its ow
I think this has the advantage of not requiring any communication from the homeserver to the 'client_uri'. This is interesting for example during development where my `https://local-dev.mycorp` might resolve to my local machine, but isn't reachable by the homeserver.

It also introduces a whole level of questions like:

 - should the HS cache the client metadata fetched?
 - what if the metadata changes?
 - how does the client manage rollout of new versions, with intentional incompatible changes in the metadata?

Those are better handled if the client is the one pushing the metadata, instead of the homeserver pulling it

2025-03-13 16:19 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +A good example of this is if a mobile client distributed through an app store registers the `app.acme.corp:` scheme in an effort to impersonate "ACME Corp's" app, then "ACME Corp" would have a valid
`localhost` schemes won't work in many cases, including mobile apps, and some environments might [require specific entitlements](https://developer.apple.com/documentation/BundleResources/Entitlements/com.apple.security.network.server).

In short,

 - web apps are protected against impersonation
 - mobile native apps have some protection against impersonation (and a strong case to take down apps from the app store if impersonation is detected)
 - desktop native apps is the area where we unfortunately can't do as much

2025-03-13 18:42 UTC, tonkku107 commented on proposals/2966-oauth2-dynamic-registration.md
> +This means that the number of client registrations will grow exponentially.
One possible way to deal with this would be to implement the client read request from RFC 7592. The suggestion in https://github.com/matrix-org/matrix-spec-proposals/commit/b6abea5f854d7d5e00bc47b93422e9ca62f71058 doesn't really clean up much.

2025-03-15 17:13 UTC, ara4n commented on proposals/2966-oauth2-dynamic-registration.md
> +It stores this `client_id` and uses it for all future authorization requests against the homeserver.
This is probably a stupid question, but given i'm thinking it, others reading this probably will too: What's the difference between the `client_id` and the `device_id` for a given session, and is there any recommendation/expectation for them to be the same or not?

I assume we assume them to be different here because:
 a) the client_id is generated by the IdP rather than the HS, and we don't want the IdP to have to get a device ID from the HS?
 b) currently clients can specify their own device IDs
 c) clients only need a device ID if they're speaking E2EE, and the client might not implement E2EE?

Is this right, and what else am i missing? It feels like it's worth spelling out here for idiots like me :)

2025-03-17 08:36 UTC, t3chguy commented on proposals/2966-oauth2-dynamic-registration.md
> +It stores this `client_id` and uses it for all future authorization requests against the homeserver.
A `client_id` isn't unique to that device, it is likely (the client could provide different registration metadata for some reason) the same for all consumers of that `client` (e.g. https://app.element.io) by means of the IdP seeing the same registration metadata and issuing the same `client_id`

2025-03-18 14:52 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +It stores this `client_id` and uses it for all future authorization requests against the homeserver.
Indeed, we shouldn't use the `client_id` as a device ID. The long-term goal is to de-duplicate client IDs, so that we can clearly state to users if they used this client in the past or not, and if other people are using this client on their homerserver.

2025-03-18 14:55 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +```
As defined in RFC7591, the client doesn't have a client_secret because the `token_endpoint_auth_method` is set to `none`. It was missing from the response here though, so I added it in 650a4498

2025-03-18 14:58 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +This means that the number of client registrations will grow exponentially.
It still means you can clean up any user <-> client relationship, and just have to retain client ID and the redirect URIs, instead of all the metadata fields.

Problem with client read request, is that it makes us implement a relatively big new mechanism (with only the read request, not the update and delete), including issuing client registration tokens, to fix a potential problem that we yet don't have (as we don't yet expire client IDs)

2025-03-18 17:53 UTC, erikjohnston commented on proposals/2966-oauth2-dynamic-registration.md
> +This means that the number of client registrations will grow exponentially.
One thing I don't really follow is: clients presumably can't assume that they are registered on a given homeserver, so what's the difference for a client between encountering a new homeserver and a homeserver that has deleted their registration (assuming the homeserver has no active sessions with the client ID)?

2025-03-21 09:32 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +This means that the number of client registrations will grow exponentially.
> clients presumably can't assume that they are registered on a given homeserver

They do that through local storage. When the client does the registration, it can save the client_id in a `hs => client_id` mapping. It does mean also that right now each instance of a client on each device is considered as a different client

2025-03-21 10:11 UTC, erikjohnston commented on proposals/2966-oauth2-dynamic-registration.md
> +This means that the number of client registrations will grow exponentially.
Yeah, but generally clients will have to go through the registration flow. At which point, can't we just pretty much always do the client registration (and deduplicate server side)? That way we can easily delete client IDs.

My concern with not addressing this now is that its going to be hard to add the ability to delete client IDs in a backwards compatible way in the future, if they're assuming they can reuse any previous registration

2025-03-23 20:25 UTC, anoadragon453 approved these changes
Just minor nits.

2025-03-23 20:25 UTC, anoadragon453 commented on proposals/2966-oauth2-dynamic-registration.md
> +As per [RFC 7591 sec. 2.2](https://tools.ietf.org/html/rfc7591#section-2.2), these metadata values MAY be localized.
```suggestion
All of these metadata values are optional.

##### Metadata localization

As per [RFC 7591 sec. 2.2](https://tools.ietf.org/html/rfc7591#section-2.2), these metadata values MAY be localized.
```

Readability nit: as this feels like it should be a separate section.

2025-03-23 20:25 UTC, anoadragon453 commented on proposals/2966-oauth2-dynamic-registration.md
> +Because each client on each user device will do its own registration, they will all have different `client_id`s.
```suggestion
Because each client on each user device will do its own registration, they may all have different `client_id`s.
```

as de-duplicating is possible in implementation.

2025-03-23 20:25 UTC, anoadragon453 commented on proposals/2966-oauth2-dynamic-registration.md
> +A subsequent MSC could be proposed to identify multiple instances of the same client using signed client metadata.
Shouldn't de-duplication also be suggested as a potential mitigation technique in this section; similar to suggesting deletion inactive client registrations?

Or are you trying to discourage implementations from going down that route?

2025-03-25 09:54 UTC, erikjohnston commented
@matrixbot concern we should be able to delete unused client registrations

c.f. https://github.com/matrix-org/matrix-spec-proposals/pull/2966#discussion_r1989089655

2025-03-25 13:26 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +A subsequent MSC could be proposed to identify multiple instances of the same client using signed client metadata.
I suggested deduplication in a0e8b376

I also implemented that dedupe in MAS: https://github.com/element-hq/matrix-authentication-service/pull/4293

2025-03-25 13:27 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +This means that the number of client registrations will grow exponentially.
I've suggested deduplication, plus a long-term suggestion to avoid the 'we cannot delete client IDs' problem: a0e8b376

2025-03-25 14:23 UTC, richvdh commented on proposals/2966-oauth2-dynamic-registration.md
> +It SHOULD reuse the `client_id` for all future authorization requests done against the same homeserver.
@zecakeh any further comments on this thread?

2025-03-25 14:43 UTC, zecakeh commented on proposals/2966-oauth2-dynamic-registration.md
> +It SHOULD reuse the `client_id` for all future authorization requests done against the same homeserver.
No, thanks.

2025-03-25 17:30 UTC, clokep commented on proposals/2966-oauth2-dynamic-registration.md
> +In brief, once a client has obtained the homeserver's OAuth 2.0 metadata per [MSC2965](https://github.com/matrix-org/matrix-spec-proposals/pull/2965), and before it can initiate an authorization requ
Probably a dumb question, but does *every* client have to do this? If I'm running a corporate server can I pre-register my-web-client.acme.com?

I'm not sure if that even makes sense.

2025-03-25 17:30 UTC, clokep commented on proposals/2966-oauth2-dynamic-registration.md
> +This MSC specifies how Matrix clients SHOULD leverage the OAuth 2.0 Dynamic Client Registration Protocol ([RFC 7591](https://tools.ietf.org/html/rfc7591)) to register themselves before initiating an
Not being familiar with the RFC I'm having a lot of trouble figuring out which parts are just "follow the MSC" and which parts are specific to Matrix.

2025-03-25 17:30 UTC, clokep commented on proposals/2966-oauth2-dynamic-registration.md
> +This increase can be mitigated by de-duplicating client registrations that have identical metadata.
This is an implementation detail/suggestion to implementors I assume?

2025-03-25 20:56 UTC, richvdh commented on proposals/2966-oauth2-dynamic-registration.md
> +This means that the number of client registrations will grow exponentially.
Unfortunately I don't think that solves the problem right now.

(Some members of) the SCT remain concerned that, without a mechanism in the MSC by which servers can safely garbage-collect old client IDs, it's going to be a real pain to fix in the future.

One suggestion was 

> can we just specify that `400 M_INVALID_CLIENT_ID` upon first use means "please re-register/I don't know where you got that from, but it's wrong"

2025-03-25 20:57 UTC, richvdh commented
@mscbot concern no way for servers to gc old client IDs

2025-03-26 09:10 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +This means that the number of client registrations will grow exponentially.
If the inability to GC old clients is a hard blocker, we need to solve that.

The core of the issue is that the client cannot poke whether their client ID is valid or not. When they start using it, it's already too late, because they have started a auth grant, which implies a browser redirect.

Whenever there is an error in the flow (like the user denied access), we usually redirect back to the client with an `error`. Problem is, to redirect back to the client, you have to know the client, which isn't the case if you garbage-collected it…

So, **if we want the client to be able to poke whether the `client_id` is still valid** we either need to:

 - implement the [client read request from RFC7592](https://datatracker.ietf.org/doc/html/rfc7592#section-2.1). This way the client has a way to get its own registered metadata. Drawback of this is one extra call, and one extra token to keep track of for the client with little value, and we would only partially implement RFC7592, as the other parts (update & delete) wouldn't make sense for us.
 - change MSC2966 to use [RFC 9126 Pushed Auth Requests](https://datatracker.ietf.org/doc/html/rfc9126), which would make the client prepare the auth request through an HTTP call instead of a redirect, which means we can give it an error properly here

Long term, I would like to have pushed auth requests. But this would add an extra step for clients to login, and significant changes in the implementations now if we want to unblock the MSC.

**Alternatively**, what if we said something among the lines of

> The homeserver may delete client registrations that had no active session and have not been used in more than a month time.
> Therefore, clients must do a new client registration if they want to authenticate against a homeserver they haven't used in a while.

To be clear, I don't like the idea of putting an arbitrary date in there, but this is the easiest way we can get out of it without changing the implementations

2025-03-26 09:22 UTC, richvdh commented on proposals/2966-oauth2-dynamic-registration.md
> +This means that the number of client registrations will grow exponentially.
> Whenever there is an error in the flow (like the user denied access), we usually redirect back to the client with an `error`. Problem is, to redirect back to the client, you have to know the client, which isn't the case if you garbage-collected it…

I think I (and maybe other members of the SCT) am slightly failing to join the dots about how an expired client_id is a problem, so to set this out more explicitly, it would be something like:

 1. Client knows it has previously registered and has a `client_id` which it believes to be valid
 2. It therefore *redirects* the user to the authorization endpoint, per [MSC2964](https://github.com/sandhose/matrix-spec-proposals/blob/msc/sandhose/oauth2-profile/proposals/2964-oauth2-profile.md#sample-authorization-request)
 3. The server doesn't recognise the `client_id` so needs to return an error

Obviously, a `400 M_INVALID_CLIENT_ID` doesn't help us here, but I'm not quite following why the server cannot return an error to the client via the normal callback mechanism? It seems like the server has everything it needs for this?

2025-03-26 09:34 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +This means that the number of client registrations will grow exponentially.
This is because OAuth 2.0 wants to prevent your server becoming an open redirector.

[RFC 6749 section 4.1.2.1](https://www.rfc-editor.org/rfc/rfc6749#section-4.1.2.1) states

>    If the request fails due to a missing, invalid, or mismatching
   redirection URI, or if the client identifier is missing or invalid,
   the authorization server SHOULD inform the resource owner of the
   error and MUST NOT automatically redirect the user-agent to the
   invalid redirection URI.

In this context, 'resource owner' is the end user, 'user-agent' is the web browser; so they tell you that you should display an error page to the user, but not go back to the client.

This is also expanded a bit in [RFC 9700 section 4.11.2](https://datatracker.ietf.org/doc/html/rfc9700#section-4.11.2)

2025-03-26 09:38 UTC, tulir commented on proposals/2966-oauth2-dynamic-registration.md
> +This means that the number of client registrations will grow exponentially.
> The homeserver may delete client registrations that had no active session and have not been used in more than a month time.
> Therefore, clients must do a new client registration if they want to authenticate against a homeserver they haven't used in a while.

This option sounds the easiest. Does it even need to be such a long time? Servers could just check for client IDs with no valid access tokens and clean them up if they're more than a day old for example. Then just define that clients must not store client IDs after logout and must re-register if the user spends more than a few hours on the pre-login screen or something like that

2025-03-26 10:15 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +This means that the number of client registrations will grow exponentially.
Did that in 1f489eee

2025-03-26 10:45 UTC, richvdh commented on proposals/2966-oauth2-dynamic-registration.md
> +This means that the number of client registrations will grow exponentially.
looks better to me now

2025-03-26 10:52 UTC, erikjohnston commented on proposals/2966-oauth2-dynamic-registration.md
> +Clients SHOULD perform a new client registration at the start of each authorization flow.
I'd probably say this is a `MUST`?

2025-03-26 10:57 UTC, erikjohnston commented
@mscbot resolve we should be able to delete unused client registrations

2025-03-26 11:05 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +Clients SHOULD perform a new client registration at the start of each authorization flow.
done in ee36393

2025-03-26 11:05 UTC, erikjohnston commented on proposals/2966-oauth2-dynamic-registration.md
> +Clients SHOULD perform a new client registration at the start of each authorization flow.
From out-of-band discussion: there may be valid reasons to not reregister, e.g. "like if the same client has multiple sessions with the same homeserver in parallel?". However, I'm paranoid that client implementers will see the SHOULD, end up caching the client ID and see that it works 90% of the time, and then things break if the server tries to delete the client ID mapping.

Suggestion is to convert to MUST, and add a caveat for that case, to make things explicit.

2025-03-26 11:15 UTC, erikjohnston commented
@mscbot resoove no way for servers to gc old client IDs

2025-03-31 15:29 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +In brief, once a client has obtained the homeserver's OAuth 2.0 metadata per [MSC2965](https://github.com/matrix-org/matrix-spec-proposals/pull/2965), and before it can initiate an authorization requ
Because this is not in the actual proposal text, I will rephrase this to make it less authoritative, as this is already covered by 'Proposal > Dynamic client registration'. Did that in 55433db4

2025-03-31 15:45 UTC, sandhose commented on proposals/2966-oauth2-dynamic-registration.md
> +This MSC specifies how Matrix clients SHOULD leverage the OAuth 2.0 Dynamic Client Registration Protocol ([RFC 7591](https://tools.ietf.org/html/rfc7591)) to register themselves before initiating an
I've added two notes about this here: dbb61639

In short, nothing is Matrix-specific other than the set of metadata values we enforce/encourage clients to use

2025-03-31 16:05 UTC, dbkr commented on proposals/2966-oauth2-dynamic-registration.md
> +This MSC specifies how Matrix clients SHOULD leverage the OAuth 2.0 Dynamic Client Registration Protocol ([RFC 7591](https://tools.ietf.org/html/rfc7591)) to register themselves before initiating an
Not to be a stickler, but I think having this 'should' in formal capitals technically implies the whole MSC is optional, which is probably not what you want.

2025-04-05 18:41 UTC, merged

2025-05-24 16:49 UTC, zecakeh commented
spec PR: https://github.com/matrix-org/matrix-spec/pull/2148

2025-06-18 09:13 UTC, richvdh commented
> spec PR: [matrix-org/matrix-spec#2148](https://github.com/matrix-org/matrix-spec/pull/2148)

Merged! :tada: