MSC2967: [WIP] API scope restriction
matrix-org/matrix-spec-proposals pull request #2967
Opened 2021-01-14 17:13 UTC by sandhose

[Rendered](https://github.com/sandhose/matrix-doc/blob/sandhose/msc/api-scopes/proposals/2967-api-scopes.md)

2021-01-15 10:08 UTC, Kegsay commented on proposals/2967-api-scopes.md
> +`write` access to a resource implies `read` access to it.
It might be nice to have the concept of either:
 - `append` (write but not delete), where `write` allows deletions.
 - `delete`, where `write` alone does not allow deletions.

I trust some logins to send messages but I don't want them to be able to edit/delete things I've already sent.

2021-01-15 11:08 UTC, sandhose commented on proposals/2967-api-scopes.md
> +`write` access to a resource implies `read` access to it.
It's hard to know what suffixes would actually make sense before the full scopes get defined. Maybe this MSC should be less precise about the scope suffixes and leave them for when exact scopes get implemented?

After this MSC, I only expect `urn:matrix:api:*`, `urn:matrix:sudo:*` and `urn:matrix:device:[ID]` to work, which are enough to mimic current behaviors.

2021-01-31 04:24 UTC, erkinalp requested changes
Don't use the word `sudo` as we do not have a concept of superusers or substitute users in Matrix.

2021-01-31 04:24 UTC, erkinalp commented on proposals/2967-api-scopes.md
> +Access to the `urn:matrix:sudo:*` can be time-restricted and require user re-authentication for sensitive operations.
```suggestion
Access to the `urn:matrix:limited:*` can be time-restricted and require user re-authentication for sensitive operations.
```

2021-03-01 23:39 UTC, aaronraimist commented
Related: https://github.com/matrix-org/matrix-doc/issues/2889

2022-08-03 15:23 UTC, hughns commented on proposals/2967-api-scopes.md
> +Access to the `urn:matrix:sudo:*` can be time-restricted and require user re-authentication for sensitive operations.
In the latest version of the proposal we explicitly call it `uia` so that the purpose is clear in relation to the C-S API.

2022-08-03 15:26 UTC, hughns commented on proposals/2967-api-scopes.md
> +`write` access to a resource implies `read` access to it.
@kegsay I've added these as notes to the proposal and attempted to clarify about what would be done now versus at some point in future.

2023-02-28 16:59 UTC, hughns commented on proposals/2967-api-scopes.md
> +Access to the `urn:matrix:sudo:*` can be time-restricted and require user re-authentication for sensitive operations.
Furthermore, the latest version of the proposal now excludes UIA entirely.

2023-05-16 14:24 UTC, clokep commented on proposals/2967-api-scopes.md
> +The Device ID handling involves a change in where device IDs are generated. This is discussed in MSC2964. On the OIDC Provider side the device ID proposal requires the use of dynamic scopes. That is,
```suggestion
The Device ID handling involves a change in where device IDs are generated. This is discussed in [MSC2964](https://github.com/matrix-org/matrix-doc/pull/2964). On the OIDC Provider side the device ID proposal requires the use of dynamic scopes. That is, the specific scope is a templated form rather than being static. This is not currently supported by some OpenID Providers (e.g. Okta and Auth0).
```

2023-05-16 14:32 UTC, clokep commented on proposals/2967-api-scopes.md
> +The addition of the `WWW-Authenticate` header could cause issue with some clients.
The header itself or attempting to parse it? We could also provider a matching `errcode` if that's useful?

2023-08-30 20:19 UTC, tonkku107 commented on proposals/2967-api-scopes.md
> +Presently a device ID is typically generated by the homeserver and is associated with a specific access token. In OAuth 2.0 there is no such thing as a session and so a mapping cannot be handled usin
> In OAuth 2.0 there is no such thing as a session and so a mapping cannot be handled using the same mechanism.

In OIDC they define a `sid` (Session ID) claim within the `id_token` in the [Front-Channel Logout spec](https://openid.net/specs/openid-connect-frontchannel-1_0.html) (also referenced in other specs)

I would also like to mention that since clients are expected to use dynamic registration, `client_id`s resemble device IDs quite a bit

2025-01-27 19:05 UTC, turt2live requested changes
Overall this MSC looks ready to go, though there's some existing comments which should be addressed/incorporated before FCP is proposed.

2025-01-27 19:06 UTC, turt2live commented
MSCs proposed for Final Comment Period (FCP) should meet the requirements outlined in the [checklist](https://github.com/matrix-org/matrix-spec-proposals/blob/main/MSC_CHECKLIST.md) prior to being accepted into the spec. This checklist is a bit long, but aims to reduce the number of follow-on MSCs after a feature lands. 

SCT members: please check off things you check for, and raise a concern against FCP if the checklist is incomplete. If an item doesn't apply, prefer to check it rather than remove it. Unchecking items is encouraged where applicable.

Checklist:
- [x] Are [appropriate implementation(s)](https://spec.matrix.org/proposals/#implementing-a-proposal)
  specified in the MSC’s PR description?
- [x] Are all MSCs that this MSC depends on already accepted?
- [x] For each new endpoint that is introduced:
  - [x] Have authentication requirements been specified?
  - [x] Have rate-limiting requirements been specified?
  - [x] Have guest access requirements been specified?
  - [x] Are error responses specified?
    - [x] Does each error case have a specified `errcode` (e.g. `M_FORBIDDEN`) and HTTP status code?
      - [x] If a new `errcode` is introduced, is it clear that it is new?
- [x] Will the MSC require a new room version, and if so, has that been made clear?
  - [x] Is the reason for a new room version clearly stated? For example,
          modifying the set of redacted fields changes how event IDs are calculated,
          thus requiring a new room version.
- [x] Are backwards-compatibility concerns appropriately addressed?
- [x] Are the [endpoint conventions](https://spec.matrix.org/latest/appendices/#conventions-for-matrix-apis) honoured?
  - [x] Do HTTP endpoints `use_underscores_like_this`?
  - [x] Will the endpoint return unbounded data? If so, has pagination been considered?
  - [x] If the endpoint utilises pagination, is it consistent with
    [the appendices](https://spec.matrix.org/v1.8/appendices/#pagination)?
- [x] An introduction exists and clearly outlines the problem being solved.
      Ideally, the first paragraph should be understandable by a non-technical audience.
- [ ] All outstanding threads are resolved
  - [ ] All feedback is incorporated into the proposal text itself, either as a fix or noted as an alternative
- [x] While the exact sections do not need to be present,
  the details implied by the proposal template are covered. Namely:
  - [x] Introduction
  - [x] Proposal text
  - [x] Potential issues
  - [x] Alternatives
  - [x] Dependencies
- [x] Stable identifiers are used throughout the proposal, except for the unstable prefix section
  - [x] Unstable prefixes [consider](README.md#unstable-prefixes) the awkward accepted-but-not-merged state
  - [x] Chosen unstable prefixes do not pollute any global namespace (use “org.matrix.mscXXXX”, not “org.matrix”).
- [x] Changes have applicable [Sign Off](CONTRIBUTING.md#sign-off) from all authors/editors/contributors
- [x] There is a dedicated "Security Considerations" section which detail
  any possible attacks/vulnerabilities this proposal may introduce, even if this is "None.".
  See [RFC3552](https://datatracker.ietf.org/doc/html/rfc3552) for things to think about,
  but in particular pay attention to the [OWASP Top Ten](https://owasp.org/www-project-top-ten/).

2025-03-05 16:42 UTC, sandhose commented on proposals/2967-api-scopes.md
> +Presently a device ID is typically generated by the homeserver and is associated with a specific access token. In OAuth 2.0 there is no such thing as a session and so a mapping cannot be handled usin
Technically yes, in practice no as MSC2918-style refresh tokens are almost not adopted by anyone. Is it worth clarifying here?

2025-03-05 16:44 UTC, sandhose commented on proposals/2967-api-scopes.md
> +Presently a device ID is typically generated by the homeserver and is associated with a specific access token. In OAuth 2.0 there is no such thing as a session and so a mapping cannot be handled usin
> In OIDC they define a sid (Session ID) claim within the id_token in the [Front-Channel Logout spec](https://openid.net/specs/openid-connect-frontchannel-1_0.html) (also referenced in other specs)

Front-channel logout is a OP -> RP logout notification mechanism, which is not what we need.

We would need OIDC RP-initiated logout, but it's not practical to use in native apps, especially on iOS, as there would be an explicit prompt to logout there.

> I would also like to mention that since clients are expected to use dynamic registration, client_ids resemble device IDs quite a bit

This is somewhat true for now, although I aspire to dedupe client registrations through client metadata signature at some point, so I don't really like 'abusing' the client_id to do that

2025-03-05 16:45 UTC, sandhose commented
@turt2live Feedback has been incorporated, I think we can go ahead with the FCP ticks

2025-03-05 19:14 UTC, tonkku107 commented on proposals/2967-api-scopes.md
> +Presently a device ID is typically generated by the homeserver and is associated with a specific access token. In OAuth 2.0 there is no such thing as a session and so a mapping cannot be handled usin
This was such an old post to which I got my answers by joining the matrix room already :D 

> Front-channel logout is a OP -> RP logout notification mechanism, which is not what we need.

The reason I mentioned that it's referenced in other specs is so that you could also refer to just that part of it, not having to implement the whole front-channel proposal. OIDC itself considers that section of the spec as where the session id concept is defined.

It's pointless now that ID tokens aren't a requirement anymore though.

2025-03-11 02:17 UTC, turt2live commented
@mscbot fcp merge

2025-03-11 14:03 UTC, dbkr commented on proposals/2967-api-scopes.md
> +Note that currently the Matrix specification doesn't specify a format for the device ID itself. If the device ID were constrained as per [MSC1597](https://github.com/matrix-org/matrix-spec-proposals/
So does this specify an encoding to be used or none?

2025-03-11 14:03 UTC, dbkr commented on proposals/2967-api-scopes.md
> +Scope format could also have an URL format, e.g. `https://matrix.org/api/*/read`.
```suggestion
Scopes could also have an URL format, e.g. `https://matrix.org/api/*/read`.
```
.. just because I'm assuming multiple uses of 'scope' wasn't intentional

2025-03-11 18:40 UTC, richvdh requested changes

2025-03-11 18:40 UTC, richvdh commented on proposals/2967-api-scopes.md
> +For future MSCs that build on this namespace unstable sub divisions should be used whilst in development:
nit 
```suggestion
For future MSCs that build on this namespace unstable subdivisions should be used whilst in development:
```

2025-03-11 18:40 UTC, richvdh commented on proposals/2967-api-scopes.md
> +e.g. `urn:matrix:com.example.mscXXXX.foo:something` or `urn:matrix:client:com.example.mscXXXX.something`
I'm also unclear about what would happen once the msc is stable: would it become `urn:matrix:client:something`?

2025-03-11 18:40 UTC, richvdh commented on proposals/2967-api-scopes.md
> +| `urn:matrix:client` | For mapping of Client Server API access levels |
Rather than this table with one row, I think it would be clearer to explain what's going on in words.

```suggestion
All scopes related to Matrix should start with `urn:matrix` and use the `:` delimiter for further sub-division.
Scopes related to mapping of Client-Server API access levels should start with `urn:matrix:client`.
```

2025-03-11 18:40 UTC, richvdh commented on proposals/2967-api-scopes.md
> +The Device ID handling involves a change in where device IDs are generated. This is discussed in [MSC2964](https://github.com/matrix-org/matrix-doc/pull/2964). On the OIDC Provider side the device ID
> This is discussed in [MSC2964](https://github.com/matrix-org/matrix-doc/pull/2964).

Is it? where?

2025-03-11 18:40 UTC, richvdh commented on proposals/2967-api-scopes.md
> +The client can then bind the device ID to the grant by requesting a scope comprising of a [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986) URN in the format:
> The client can then bind the device ID to the grant

What does this actually mean in practice? For example, does it mean that when I call `/sync` using an access token corresponding to this grant, then I will receive to-device messages sent to the given device ID? If so, can you say so explicitly?

2025-03-11 18:40 UTC, richvdh commented on proposals/2967-api-scopes.md
> +This also has a nice side-effect: if the device asked was never used by the client making the request, the authorization server will ask for explicit consent from the user.
I don't really follow this, tbh. Why does the auth server ask for consent if a device was *not* used? What is asking for consent for? When does this happen?

do you mean "not previously used", rather than "never used"?

2025-03-13 16:24 UTC, sandhose commented on proposals/2967-api-scopes.md
> +OAuth 2.0 grants have scopes associated to them and provides a framework for obtaining user consent.
Reworded in 7bad5053, wdyt?

2025-03-13 16:29 UTC, sandhose commented on proposals/2967-api-scopes.md
> +e.g. `urn:matrix:com.example.mscXXXX.foo:something` or `urn:matrix:client:com.example.mscXXXX.something`
I've reworded in 79845f53

2025-03-14 08:32 UTC, dbkr commented on proposals/2967-api-scopes.md
> +OAuth 2.0 grants have scopes associated to them and provides a framework for obtaining user consent.
Yep, that seems much clearer!

2025-03-14 08:34 UTC, dbkr commented on proposals/2967-api-scopes.md
> +If it needs to introduce multiple scope, like `urn:matrix:client:foo` and `urn:matrix:client:bar`, it could use `urn:matrix:client:com.example.mscXXXX:foo` and `urn:matrix:client:com.example.mscXXXX:
```suggestion
If it needs to introduce multiple scopes, like `urn:matrix:client:foo` and `urn:matrix:client:bar`, it could use `urn:matrix:client:com.example.mscXXXX:foo` and `urn:matrix:client:com.example.mscXXXX:bar`.
```

2025-03-14 08:34 UTC, dbkr commented on proposals/2967-api-scopes.md
> +e.g. `urn:matrix:com.example.mscXXXX.foo:something` or `urn:matrix:client:com.example.mscXXXX.something`
Thanks, added minor typo fix.

2025-03-14 08:48 UTC, sandhose commented on proposals/2967-api-scopes.md
> +Scope format could also have an URL format, e.g. `https://matrix.org/api/*/read`.
done in 58f2398

2025-03-14 08:49 UTC, sandhose commented on proposals/2967-api-scopes.md
> +| `urn:matrix:client` | For mapping of Client Server API access levels |
did that in e7531fa4

2025-03-14 08:54 UTC, sandhose commented on proposals/2967-api-scopes.md
> +The client can then bind the device ID to the grant by requesting a scope comprising of a [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986) URN in the format:
I'm unclear whether this MSC should define what being associated to a particular device means? This is binding (or creating) a 'Matrix device' as defined [by the spec](https://spec.matrix.org/v1.13/#devices); I don't think the impact it has on the rest of the C-S API should be defined in this MSC?

2025-03-14 09:00 UTC, sandhose commented on proposals/2967-api-scopes.md
> +Note that currently the Matrix specification doesn't specify a format for the device ID itself. If the device ID were constrained as per [MSC1597](https://github.com/matrix-org/matrix-spec-proposals/
I did define an explicit suggested alphabet and imposed a restricted alphabet (which is a superset of what MSC1597 suggests; see 58f2398

2025-03-14 15:43 UTC, richvdh commented on proposals/2967-api-scopes.md
> +The device ID scope MUST be present *at most* once in the scope.
this seems circular

```suggestion
The device ID scope MUST be present *at most* once in the list of requested scopes.
```

maybe?

2025-03-14 15:43 UTC, richvdh commented on proposals/2967-api-scopes.md
> +Which is equivalent to:
```suggestion
In any case it MUST only used characters allowed by the OAuth 2.0 scope definition in [RFC6749] section 3.3,
which is defined as the following ASCII ranges: `%x21 / %x23-5B / %x5D-7E`, i.e:
```

2025-03-14 15:43 UTC, richvdh commented on proposals/2967-api-scopes.md
> +Using this alphabet, a 10 character string is enough to be reasonably unique.
"reasonably unique" doesn't make much sense

```suggestion
Using this alphabet, a 10 character string is enough to stand a sufficient chance of being unique.
```

2025-03-14 15:43 UTC, richvdh commented on proposals/2967-api-scopes.md
> +The client can then bind the device ID to the grant by requesting a scope comprising of a [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986) URN in the format:
the problem is that the words "bind" and "grant" do not currently appear in the matrix spec (at least in this context), so yes, I think we do need to define this better. My question above about to-device messages is an important one, which I'm still not clear on the answer to.

If my *assumptions* are correct, then we could fix this by adding something along the lines of:

> Once the device ID is bound to the grant in this way, any access tokens corresponding to the grant are also associated with the given device ID. This means, for example, that `/sync` calls made with an access token corresponding to the grant will return to-device messages sent to the given device ID.

2025-03-14 16:20 UTC, richvdh commented on proposals/2967-api-scopes.md
> +P \approx 1 - e^{\frac{K^2}{2N}} \\
```suggestion
P \approx 1 - e^{-\frac{K^2}{2N}} \\
```

2025-03-14 16:20 UTC, richvdh commented on proposals/2967-api-scopes.md
> +$$
needs more linebreaks or something. In any case, it's all rendering on one line.

2025-03-15 17:19 UTC, ara4n commented on proposals/2967-api-scopes.md
> +Using this alphabet, a 10 character string is enough to be reasonably unique.
(i'm failing to see why 'reasonably unique' is wrong here, but whatever)

2025-03-15 17:26 UTC, ara4n commented on proposals/2967-api-scopes.md
> +#### Device ID handling
Hm. I'm surprised that the specifics of the Device ID handling scope is included in this MSC, which otherwise is the framework for defining scopes in general.  Is this because this scope is compulsory for OIDC to work?  If so, we should say so.  If not, at the least, we should say that the scope is defined here as a concrete example of how scopes would work... or failing that, split it into a separate MSC.

If it /is/ primarily intended example of the framework, it just feels a bit weird to also be speccing specific behaviour at the same time - wouldn't it be better to give a fake example, and then clearly separate the Device ID management proposal somehow?

I have a feeling i've missed something here that explains why this isn't completely out of place :D

2025-03-18 13:23 UTC, sandhose commented on proposals/2967-api-scopes.md
> +$$
I did that in 13042035 but then forgot to push 😅

2025-03-18 13:32 UTC, sandhose commented on proposals/2967-api-scopes.md
> +The device ID scope MUST be present *at most* once in the scope.
I'm always on the fence with this… The thing is, the RFC defines "scope" singular as basically the list of access a token has

>    The authorization and token endpoints allow the client to specify the
   scope of the access request using the "scope" request parameter.  In
   turn, the authorization server uses the "scope" response parameter to
   inform the client of the scope of the access token issued.
>
>   The value of the scope parameter is expressed as a list of space-
   delimited, case-sensitive strings.  The strings are defined by the
   authorization server.  If the value contains multiple space-delimited
   strings, their order does not matter, and each string adds an
   additional access range to the requested scope.

Looking at [other specs like OpenID Connect](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims), looks like a single item in the scope can be called a `scope value`?

2025-03-18 15:36 UTC, sandhose commented on proposals/2967-api-scopes.md
> +The client can then bind the device ID to the grant by requesting a scope comprising of a [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986) URN in the format:
> Once the device ID is bound to the grant

This makes it sound like 'binding' is dynamic though?

I've reworded the whole section, removing the unnecessary 1-row table as well in abbae1eb, wdyt?

2025-03-19 11:38 UTC, erikjohnston commented on proposals/2967-api-scopes.md
> +A client can adopt and rehydrate an existing device ID by asking for its associated scope on login.
I think this needs some rationale for why we need/want to make this change?

I'm a bit hesitant moving the creation of IDs to clients, as it adds all sorts of edges cases that need to be addressed (clashes, incorrect grammar, etc) and means servers can't encode any information in the device ID (which we don't currently, but you could imagine would be useful).

2025-03-25 10:07 UTC, erikjohnston requested changes

2025-03-25 10:07 UTC, erikjohnston commented on proposals/2967-api-scopes.md
> +A client can adopt and rehydrate an existing device ID by asking for its associated scope on login.
Talked out of band last Friday morning, and there sounds like there is a bunch of historical context here (that has since become mostly outdated). Conclusion was for @sandhose to comment with the background and a bit or a rationale, and then we can make a final call on whether we want device IDs to be generated on the client or server.

Something that I didn't realise is that the spec currently allows clients to generate device IDs when they log in (mostly for bots and the like).

2025-03-25 15:40 UTC, sandhose commented on proposals/2967-api-scopes.md
> +A client can adopt and rehydrate an existing device ID by asking for its associated scope on login.
I've explained why the change isn't bad in practice, and the historical context why it is like that in 082625d1

2025-03-25 17:07 UTC, anoadragon453 commented on proposals/2967-api-scopes.md
> +A client can adopt and rehydrate an existing device ID by asking for its associated scope on login.
Is it possible for the homeserver to still generate a device ID if a `urn:matrix:client:device:<device ID>` scope is omitted? Or would that be odd behaviour in the OAuth 2.0 world?

Having the ability for the homeserver to generate the device ID does make very simple matrix clients even simpler (no need to randomly generate a string). But I don't feel strongly that this behaviour must remain; it's only a nice-to-have.

Similarly, I recognise that it's useful for the client to provide a device ID upon login (for device rehydration and other use cases). So I'm happy to see that's still supported.

2025-03-25 17:49 UTC, clokep commented on proposals/2967-api-scopes.md
> +There MUST be *at most* one `urn:matrix:client:device:` token in the requested scope.
What happens if there's more than one? The login is rejected with what error?

Is this "at most" or "exactly"? (Probably the same as @anoadragon453 's comment at https://github.com/matrix-org/matrix-spec-proposals/pull/2967#discussion_r2012560048)

2025-03-25 17:49 UTC, clokep commented on proposals/2967-api-scopes.md
> +Using this alphabet, a 10 character string is enough to stand a sufficient chance of being unique.
These are still per user, correct? Can two users have the same devices ID?

2025-03-26 10:53 UTC, sandhose commented on proposals/2967-api-scopes.md
> +Using this alphabet, a 10 character string is enough to stand a sufficient chance of being unique.
Yes they are, that semantic hasn't changed

2025-03-26 10:58 UTC, sandhose commented on proposals/2967-api-scopes.md
> +There MUST be *at most* one `urn:matrix:client:device:` token in the requested scope.
The current implementation allow device-less tokens, which may not be the right thing. Let's simplify this for now, making it 'exactly one', and maybe later we introduce what not having a device ID means

2025-03-26 11:13 UTC, sandhose commented on proposals/2967-api-scopes.md
> +There MUST be *at most* one `urn:matrix:client:device:` token in the requested scope.
Change that in 858b7be9

On the error, that would be a [standard `invalid_scope` error](https://www.rfc-editor.org/rfc/rfc6749.html#section-4.1.2.1). Do we really need to specify that?

2025-03-26 11:18 UTC, erikjohnston commented on proposals/2967-api-scopes.md
> +A client can adopt and rehydrate an existing device ID by asking for its associated scope on login.
Thanks for the explanation @sandhose. SCT had a discussion and I believe the conclusion was broadly that this is fine for now, there's not much reason to change it so late in the day.

2025-04-05 18:42 UTC, merged

2025-05-25 09:50 UTC, zecakeh commented
spec PR: https://github.com/matrix-org/matrix-spec/pull/2149

2025-06-17 16:48 UTC, richvdh commented
> spec PR: [matrix-org/matrix-spec#2149](https://github.com/matrix-org/matrix-spec/pull/2149)

Merged! :tada: