MSC0000: Jump to date API endpoint
matrix-org/matrix-spec-proposals pull request #3030
Opened 2021-02-25 01:58 UTC by MadLittleMods

MSC0000: Jump to date API endpoint

Rendered (todo)

---

Related issues:

 - https://github.com/vector-im/element-web/issues/7677
 - https://github.com/matrix-org/synapse/issues/7164

2021-11-18 18:00 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +The heuristics for deciding when to ask another homeserver for a closer event if your homeserver doesn't have something close, is left up to the homeserver implementation. Although the heuristics wil
Synapse implementation: https://github.com/matrix-org/synapse/pull/9445

2021-12-02 08:13 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +The heuristics for deciding when to ask another homeserver for a closer event if your homeserver doesn't have something close, is left up to the homeserver implementation. Although the heuristics wil
Experimental Synapse implementation merged 🚀 https://github.com/matrix-org/synapse/pull/9445

2021-12-03 06:00 UTC, turt2live reviewed
overall the proposal looks great - just a few editorial comments :)

2021-12-03 06:00 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +Add new client API endpoint `GET /_matrix/client/r0/rooms/{roomId}/timestamp_to_event?ts=<timestamp>?dir=[f|b]` which fetches the closest `event_id` to the given timestamp `ts` query parameter in the
New versioning has taken place since this MSC has been opened - the endpoint would be at `v1` instead of `r0` under the new versioning.

2021-12-03 20:33 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +Add new client API endpoint `GET /_matrix/client/r0/rooms/{roomId}/timestamp_to_event?ts=<timestamp>?dir=[f|b]` which fetches the closest `event_id` to the given timestamp `ts` query parameter in the
Thank you! This is a very confusing area 😖

2021-12-03 20:46 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +Add new client API endpoint `GET /_matrix/client/r0/rooms/{roomId}/timestamp_to_event?ts=<timestamp>?dir=[f|b]` which fetches the closest `event_id` to the given timestamp `ts` query parameter in the
Added `The direction `dir` query parameter accepts `f` for forward-in-time from the timestamp and `b` for backward-in-time from the timestamp.`

Suggestions welcome as well 🙂. Probably can be similar to however we want to describe `/messages?dir=[f|b]`

2022-01-11 10:10 UTC, anoadragon453 commented
Removing the `needs-implementation` label as this MSC has both an accepted client and server implementation.

2022-01-13 08:28 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +using `GET /_matrix/client/r0/rooms/{roomId}/context/{eventId}?limi=0` for the
Typo: `limi=0`

2022-01-16 11:14 UTC, ara4n approved these changes
this lgtm; very minor comments.

@mscbot fcp merge

2022-01-16 11:14 UTC, ara4n commented on proposals/3030-jump-to-date.md
> +Use topoligical ordering, just as Element would use if you follow a permalink.
```suggestion
Use topological ordering, just as Element would use if you follow a permalink.
```

2022-01-16 11:14 UTC, ara4n commented on proposals/3030-jump-to-date.md
> +### Paginate `/messages` from timestamp
would be good to understand why this alternative (and the next one) were discarded?

2022-01-16 11:16 UTC, ara4n commented
no, really:

@mscbot fcp merge

2022-01-16 22:29 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +### Paginate `/messages` from timestamp
I think it was mainly convenience that the initial implementation from @erikjohnston went down this route, and was on our mind during the [initial discussion](https://docs.google.com/document/d/1KCEmpnGr4J-I8EeaVQ8QJZKBDu53ViI7V62y5BzfXr0/edit#bookmark=id.qu9k9wje9pxm).

2022-01-18 00:52 UTC, turt2live commented
Reported OOB:

@mscbot concern Implementation cannot be tested

2022-01-18 01:03 UTC, turt2live requested changes
I have mostly clarification concerns, and would like to play with it (but can't 😢). The proposal overall seems sane as a way forward.

2022-01-18 01:03 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +`event_id` returned by `/timestamp_to_event`.
The spec doesn't currently allow the tokens from `/context` to be supplied to `/messages`. I suspect this is a bug in the spec rather than an intentional design decision though, so would be good to see what Synapse's history on this is to help determine if the behaviour needs changing versus clarifying.

2022-01-18 01:03 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +### Paginate `/messages` from timestamp
(can we get that documented in the MSC prose please? 😇 )

In general, the rationale for why any of the alternatives were discarded appears missing.

2022-01-18 01:05 UTC, turt2live commented
@mscbot concern Authentication / rate limiting
@mscbot concern Document why alternatives were rejected
@mscbot concern Context API doesn't appear to work with backfilling (likely spec bug)
@mscbot concern The dir parameter is unclear/questionable

2022-01-18 07:13 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +`event_id` returned by `/timestamp_to_event`.
Using `/context` pagination tokens for `/messages` seems to work fine. As an example, we're doing it here, https://github.com/matrix-org/complement/blob/1b6ea4816e7291ef108569d996139047109c4d5b/tests/msc2716_test.go#L1348-L1369

2022-01-18 07:15 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +/_matrix/client/v1/rooms/{roomId}/timestamp_to_event?ts=<timestamp>?dir=[f|b]`
Just the same as any other `/messages` request probably. What are the prose around this already? (boilerplate, etc)

2022-01-18 07:16 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +backward-in-time from the timestamp. This endpoint also returns
This one "pick the closest event in X direction"

2022-01-18 07:17 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +# MSC3030: Jump to date API endpoint
> I have mostly clarification concerns, and would like to play with it (but can't 😢).

Fixes are here 🙇 https://github.com/matrix-org/matrix-react-sdk/pull/7563

2022-01-18 07:29 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +### Paginate `/messages` from timestamp
I can add that same note 👍. But for alternatives, I would just be making up reasons in retrospect.

We mainly just chose what sounded like the easiest path and had some prior art, then brought it to fruition to give it some real world experience. The alternatives haven't been thrown out for a particular reason and we could still go down those routes depending on how people like the current setup. Basically only I have actually had hands on with using it.

As a con with the current implementations using the `/timestmap_to_event` endpoint, the pagination mechanics to fetch from `/messages` at a given point in time is not the greatest since you have to get a pagination from `/context` first. But this is already documented in the MSC and doesn't seem bad outside of the extra request. I'm going to be utilizing this use case for the displaying pages of messages in the public archives soon.

2022-01-18 17:49 UTC, dbkr commented on proposals/3030-jump-to-date.md
> +`event_id` fetched is too far out of range to be useful for your use case.
What does it return if there are no events before/after the given ts?

2022-01-18 17:49 UTC, dbkr commented on proposals/3030-jump-to-date.md
> +### Paginate `/messages` from timestamp
I would say those reasons are still worth noting in the MSC: they're just as valid IMO.

It is a slight shame that it's 3 API calls rather than 1 to start paginating from a timestamp, but it has a nice consistency to in that you then always paginate with pagination tokens so consumers can't get confused and try to paginate through messages using timestamps.

Is there a reason timestamp_to_event can't return a pagination token directly?

2022-01-18 17:53 UTC, turt2live commented
@mscbot resolve Implementation cannot be tested

Thanks :)

2022-01-19 02:12 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +`event_id` fetched is too far out of range to be useful for your use case.
Will add ⏩

404
```json
{
  "errcode":"M_NOT_FOUND",
  "error":"Unable to find event from 1672531200000 in direction f"
}
```

2022-01-19 02:16 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +`event_id` returned by `/timestamp_to_event`.
> Is there a reason timestamp_to_event can't return a pagination token directly?
>
> *-- @dbkr, https://github.com/matrix-org/matrix-doc/pull/3030#discussion_r787009271*

I think it might be worth doing, https://github.com/matrix-org/synapse/pull/9445#discussion_r747943150

2022-01-19 02:30 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +### Paginate `/messages` from timestamp
> I would say those reasons are still worth noting in the MSC: they're just as valid IMO.

Current context added ⏩


> Is there a reason timestamp_to_event can't return a pagination token directly?

Split off the conversation to this thread: https://github.com/matrix-org/matrix-doc/pull/3030#discussion_r787297190

2022-01-21 22:54 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +`event_id` returned by `/timestamp_to_event`.
We can always iterate on this later and add this extra property in another MSC ⏩

2022-01-22 04:31 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +/_matrix/client/v1/rooms/{roomId}/timestamp_to_event?ts=<timestamp>?dir=[f|b]`
usually just "The endpoint is authenticated, and can be rate limited" (using the correct verbiage for the intended effect). If it requires an unexpected combination of authentication and rate limiting, a sentence or two to cover the why is appreciated (ie: if a new endpoint called `/flood` was rate limited, we'd probably ask why)

2022-01-24 23:36 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +/_matrix/federation/v1/timestamp_to_event/{roomId}?ts=<timestamp>?dir=[f|b]`
See https://github.com/matrix-org/matrix-doc/pull/3030#discussion_r786351083

2022-01-24 23:38 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +/_matrix/client/v1/rooms/{roomId}/timestamp_to_event?ts=<timestamp>?dir=[f|b]`
Thank you @turt2live! Added something similar and described the "why" as to prevent resource exhaustion (DOS'ing the server with many requests).

2022-02-09 16:25 UTC, erikjohnston commented on proposals/3030-jump-to-date.md
> +}
Is the idea then to immediately call `/context`? I'm wondering if it makes sense to return a `/context` like response?

2022-02-09 16:25 UTC, erikjohnston commented on proposals/3030-jump-to-date.md
> +}
I don't think `/context` works across federation ATM, nor is there a way of "backfilling forwards" (which would be required when paginating forwards for event the server doesn't have).

2022-02-09 23:50 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +}
Would probably be good, this point has a thread here: https://github.com/matrix-org/matrix-doc/pull/3030#discussion_r787297190

2022-02-10 00:37 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +}
Just asking this question in case there is another mechanism; If I visit a `matrix.to` link with a specific event ID in a room my homeserver hasn't been in before (or doesn't have the history), how is it able to jump up to that point in the timeline? (maybe it doesn't and just says unable to load position in timeline).

For reference, I have only been using `/context` to get the stream token to use with `/messages`. But `/context` does seem like it would fail for an event not in the local database.

---

As a workaround, say someone requests archives for `2022-01-05`, we could `/timestamp_to_event` for the day after `2022-01-06` and backfill from there.

2022-02-10 10:39 UTC, erikjohnston commented on proposals/3030-jump-to-date.md
> +}
> maybe it doesn't and just says unable to load position in timeline

It does that ^, afaik, which is not ideal

2022-04-05 16:50 UTC, richvdh commented on proposals/3030-jump-to-date.md
> +}
just to add to the general feedback here: it's really unclear how this is meant to work over federation - it's unclear what a requesting server is meant to do after it gets the event id back.

TBH, I would focus on landing the C-S API endpoint, and we can worry about making it work effectively over federation later.

2022-04-05 17:15 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +}
> just to add to the general feedback here: it's really unclear how this is meant to work over federation - it's unclear what a requesting server is meant to do after it gets the event id back.

@richvdh Isn't that up to the homeserver implementation?

Right now in Synapse, when you request C-S API `/timestamp_to_event`, and it sees a gap, the homeserver will ask the federation `/timestamp_to_event` endpoint and return that result. I do think we should [update to backfill that event](https://github.com/matrix-org/synapse/blob/develop/synapse/handlers/room.py#L1346-L1350) as well.

The federation endpoint is necessary for the [archive use case](https://github.com/matrix-org/matrix-public-archive) we're actively developing MSC3030 alongside. When someone visits the archive on a date, we want to return some results. The only way to get that info is asking the federation for the events we're missing.

We can get around the limitation of not being able to "backfill forwards" by starting to paginate from the end-of-day requested in the archive. If someone visits the archive for 2022-04-03, we can `/timestamp_to_event?ts={2020-04-04:00:00:00}&dir=b` to find the most recent event in the 2022-04-03 day. Then if that event from federation was backfilled, we can use `/context` to get a pagination token and use `/messages?dir=b` which will backfill just fine from there for however long we want to paginate back.

2022-04-05 17:34 UTC, richvdh commented on proposals/3030-jump-to-date.md
> +}
> @richvdh Isn't that up to the homeserver implementation?

maybe, but unless we can come up with a plausible use for this endpoint, there's not much point in it. I think the MSC should at least give an example of how it can be used. Right now I don't think there is anything the requesting server can do with the event id it gets back (it'll pass it back to the client, which will call `/context` on it, which will 404)

2022-04-08 19:56 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +backward-in-time from the timestamp. This endpoint also returns
can that be written into the MSC please?

2022-04-08 20:00 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +}
ftr: Pushing the MSC ahead without federation feels not great from a client perspective, so if we can figure this out in this MSC then that would be preferred.

2022-04-08 20:04 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +}
Do we anticipate that the endpoint would be called for older or newer events most often? If it's more likely to be old/ancient events then including `/context` (or pagination tokens) in the response would be good, I think. If it's more likely to be recent events then the client likely has it cached locally already and can avoid the `/context` call (and the server doesn't need to do extra work).

2022-04-08 20:05 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +`event_id` returned by `/timestamp_to_event`.
(if that^ is the decision, please mention it in the MSC)

2022-04-08 20:09 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +## Potential issues
Clients could also abuse this new API for getting the create event, so servers might want to put extra care into optimizing whatever lookups they do. 

The create event contains quite a lot of information that a client needs in order to operate, so it is frequently requested by said clients. For example, the room type and room version (for displaying warnings about stability).

2022-04-08 20:14 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +## Potential issues
Another issue is that clients could land on an event they can't/won't render, such as a reaction, then they'll be forced to desperately seek around the timeline until they find an event they can do something with.

For example, in announcement rooms where membership events are typically hidden it is more important that the client guess which direction to start paginating in to find the next-nearest event it can render. The risk would be that if the client picks the "wrong" direction then the user could be looking at the second neighbour rather than the first. 

Eg:
* Client wants to jump to January 1st, 2022
* Server says there's an event on January 2nd, 2022 that is close enough
* Client finds out there's a ton of unrenderable events like memberships, poll responses, reactions, etc at that time
* Client starts paginating forwards, finally finding an event on January 27th it can render
* Client wasn't aware that the actual nearest neighbouring event was December 31st, 2021 because it didn't paginate in that direction
* User is confused that they are a month past the target date when the message is *right there*.

2022-04-08 20:18 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +current design.
while kind, the proposal is a lot stronger if it can defend its choice to go with the design it has set out. If we're still at the exploratory mark where this isn't determined to be the best possible solution, we can pull it back to in-review rather than have it at proposed-fcp.

2022-04-08 20:20 UTC, turt2live requested changes
see previous comments

2022-04-08 20:20 UTC, turt2live commented
@mscbot resolve Authentication / rate limiting

2022-04-09 03:20 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +Add new client API endpoint `GET /_matrix/client/r0/rooms/{roomId}/timestamp_to_event?ts=<timestamp>?dir=[f|b]` which fetches the closest `event_id` to the given timestamp `ts` query parameter in the
More conversation about `dir` continued in https://github.com/matrix-org/matrix-spec-proposals/pull/3030#discussion_r786350771

2022-04-09 03:25 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +backward-in-time from the timestamp. This endpoint also returns
I feel like it already says that 🤷:

> fetches the closest `event_id` to the given timestamp `ts` query parameter
in the direction specified by the `dir` query parameter


But I think I am missing what your original confusion was as I don't understand the first sentence "it sounds like `dir` is to help the server do `date.isBefore(now)`, which surely it can do on its own without trusting the client?"

2022-04-09 03:30 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +}
> Do we anticipate that the endpoint would be called for older or newer events most often?

Both have great use cases. Jump to last week, or jump to 2 years ago.

2022-04-09 03:33 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +## Potential issues
Added 👍

2022-04-09 03:50 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +## Potential issues
Added to the potential issues 👍

Also added some notes on how the client can make the situation a bit better:

I feel like the client just needs to be smarter here. The client can see event `origin_server_ts` as they paginate and if they see they're going more than a couple days out, they can also try the other direction.

Clients can also just explain to the user what happened with a little toast: "We were unable to find an event to display on January 1st, 2022. The closest event after that date is on January 27th."

2022-04-09 05:22 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +current design.
Original alternative discussion in https://github.com/matrix-org/matrix-spec-proposals/pull/3030#discussion_r785425438

I think we're past the exploratory mark. The current design was discussed initially and then better proven with a homeserver implementation and client usages where it still fits in well. But we're in the stage of fielding better ideas if people have them.

I've added some complication thoughts to the current alternatives.

2022-04-09 05:28 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +}
I've added a note that "After the local homeserver receives a response from the federation endpoint, it should probably should try to backfill this event so that it's available to query with `/context` from a client in order to get a pagination token."

2022-04-11 08:53 UTC, erikjohnston commented on proposals/3030-jump-to-date.md
> +## Potential issues
This feels like a similar problem as with general back pagination. We should definitely not include reactions, edits and the like (i.e. anything that would get bundled together in the `/messages` response). I'm a bit less concerned about membership, as that *does* get rendered by the client and so the user can see and understand what's going on there. 

We could also potential add a filter, as we do for `/messages`?

2022-04-12 23:04 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +## Potential issues
> This feels like a similar problem as with general back pagination. We should definitely not include reactions, edits and the like (i.e. anything that would get bundled together in the /messages response). I'm a bit less concerned about membership, as that does get rendered by the client and so the user can see and understand what's going on there.

I feel like we shouldn't do this. In end-to-end encrypted (E2EE) rooms, all of the events look like `m.room.encrypted` so we can't do this sort of filtering. It's also unclear all of the event types to filter out here. What about unknown events, what about future event types, what about clients that do render some event types (for example, edit events are rendered in Hydrogen)? Has the magic already been figured out somewhere for another endpoint?

How does `/messages` work with a `RoomEventFilter` in encrypted rooms? My assumption is it doesn't because everything is a `m.room.encrypted` event type.

> We could also potential add a filter, as we do for `/messages`?

Sounds fine but I think it's not necessary for a v1 and can add this in another MSC.

2022-04-13 10:05 UTC, erikjohnston commented on proposals/3030-jump-to-date.md
> +query parameter accepts `f` for forward-in-time from the timestamp and `b` for
What's the rationale for including a `dir`? Naively i would assume that if I jump to a date then it'd give me the closest event, rather than the closest in a specified direction?

I don't think it matters that much, since clients will likely just call `/context` or whatever and so see the surround events, but I'm just a bit surprised it's something a client cares about.

2022-04-15 18:04 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +## Potential issues
> There are different levels of things going on here, the edit and reaction aggregation happens even for encrypted events. This is what happens today (I think?? At least, if not that was the intention) with /messages.

I don't think we do this. I see `m.reaction` and edit (`m.room.message` with `m.relates_to` and `m.replace`) when I query `/messages`. I'm also confused how it could ever work in encrypted rooms which have all of that information locked away in the encrypted part of `m.room.encrypted`.

For unencrypted rooms, we do aggregate the edits/reactions under the `unsigned` key of the events they're attached to.

2022-04-15 22:47 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +query parameter accepts `f` for forward-in-time from the timestamp and `b` for
For clients, it doesn't make that much of a difference because you can always compare the timestamp you made the request with to the `origin_server_ts` that was returned to see what direction you need to paginate further in. And it's a toss-up in the amount of client complexity for various use cases on the extra logic (some will require more and others won't depending on the approach we pick).

But the `dir` parameter does help us be a little more efficient on the homeserver. Without `dir`, the homeserver has to check for a gap both forwards and backwards on every request. If we include the `dir` parameter, we only have to check in one direction. And then in both cases, the client still decides which direction they want paginate further in.

---


In terms of client usage, I find it easier to reason about when it's a consistent result with `dir` vs having to figure out both directions after it's returned.

Pseudo-code with `dir`:

```js
// Get archive of messages for 2022-04-04
const { yyyy, mm, dd } = parseDateString('2022-04-04');
const fromTimestamp = Date.UTC(yyyy, mm, dd);
const toTimestamp = Date.UTC(yyyy, mm, dd + 1);

// Check for the closest event from the end of the requested day looking backwards
// to get the most recent event in the room on the given day
const timestampToEventRes= await fetch(`/timestamp_to_event?ts=${toTimestamp}?dir=b`);

// Nothing to show, if the returned event is older than the day itself
if(timestampToEventRes.origin_server_ts < fromTimestamp) {
  return `No events to display on ${yyyy}-${mm}-${dd}`;
}

// Get a pagination token
const contextRes = await fetch(`/context/${timestampToEventRes.event_id}?limit=0`);

const messagesRes = await fetch(`/messages?dir=b&from=${contextRes.end}`);
return filterEventsWithinRange(messagesRes.chunk, fromTimestamp, toTimestamp);
```

Pseudo-code without `dir` (see the "Extra logic" part of this for the difference):

```js
// Get archive of messages for 2022-04-04
const { yyyy, mm, dd } = parseDateString('2022-04-04');
const fromTimestamp = Date.UTC(yyyy, mm, dd);
const toTimestamp = Date.UTC(yyyy, mm, dd + 1);

// Check for the closest event (forwards or backwards) from the end of the requested day
const timestampToEventRes= await fetch(`/timestamp_to_event?ts=${toTimestamp}`);

// Nothing to show, if the returned event is older than the day itself
if(timestampToEventRes.origin_server_ts < fromTimestamp) {
  return `No events to display on ${yyyy}-${mm}-${dd}`;
}

// Get a pagination token
const contextRes = await fetch(`/context/${timestampToEventRes.event_id}?limit=0`);

// Extra logic here to figure out which side of found event we should paginate from.
// The alternative to this piece of code is to always use `contextRes.end` and let `filterEventsWithinRange` handle the out of bounds events on both sides.
let paginationToken = contextRes.end;
if(timestampToEventRes.origin_server_ts > toTimestamp) {
  let paginationToken = contextRes.start;
}

const messagesRes = await fetch(`/messages?dir=b&from=${paginationToken}`);
return filterEventsWithinRange(messagesRes.chunk, fromTimestamp, toTimestamp);
```

2022-04-19 07:35 UTC, erikjohnston commented on proposals/3030-jump-to-date.md
> +## Potential issues
Aggregation information happens outside the encrypted payload precisely so that the server can e.g. index them. 

> I don't think we do this. I see `m.reaction` and edit (`m.room.message` with `m.relates_to` and `m.replace`) when I query `/messages`. I'm also confused how it could ever work in encrypted rooms which have all of that information locked away in the encrypted part of `m.room.encrypted`.

Well that sucks, and probably makes pagination a pain in rooms with lots of aggregations. I thought we did do this somewhere, maybe when we do an initial sync?

2022-05-09 21:23 UTC, alphapapa commented on proposals/3030-jump-to-date.md
> +be impossible to distinguish from  a timestamp.
It seems like this problem could be solved by simply having additional `fromtime`/`totime` query parameters, which would always receive Matrix timestamps as arguments.

And if that solves the ambiguity problem, it seems like this extension of the `/messages` endpoint would be much preferable to adding the `/timestamp_to_event` endpoint, because it would reduce round-trips and simplify client-side implementation.

2022-09-10 03:26 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +backward-in-time from the timestamp. This endpoint also returns
5 months later I have no idea what I was on about - it's possible I forgot what the paragraph was about after reading the thread above 😅

2022-09-10 03:37 UTC, turt2live approved these changes
I think this is generally good to go, presuming the backfill concern is sufficiently resolved for federation

2022-09-10 03:37 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +endpoint, it should probably should try to backfill this event so that it's
backfill with which endpoint?

2022-09-10 03:37 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +events which are potentially closer.
is there also a suggestion on which servers to try? (hitting all servers is going to be slow/noisy, for example)

2022-09-10 03:37 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +## Potential issues
It looks like this concern would be solved by another MSC (which is good, imo): https://github.com/matrix-org/matrix-spec-proposals/pull/3874

While it doesn't allow filtering out *all* event types, it can at least filter out things with relationship types such as reactions and poll responses.

2022-09-10 03:37 UTC, turt2live commented
@mscbot resolve Document why alternatives were rejected
@mscbot resolve The dir parameter is unclear/questionable

2022-09-14 08:02 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +events which are potentially closer.
Added a note ✅

> A good heuristic for which servers to try first is to sort by servers that have
been in the room the longest because they're most likely to have anything we ask
about.

2022-09-14 08:06 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +endpoint, it should probably should try to backfill this event so that it's
Added a note to use the "federation `/event/<event_id>` endpoint" ✅

2022-09-14 08:24 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +be impossible to distinguish from  a timestamp.
I documented your alternative in the MSC. Sounds like a decent option but I'll leave it to others to assign their preference.

As a counter-point, it doesn't solve the round-trip/client-side implementation round-trip complexity problem if I instead wanted to use the closest `event_id` with the `/context` endpoint or some other endpoint.

2022-09-27 14:01 UTC, dav-is commented on proposals/3030-jump-to-date.md
> +`event_id` returned by `/timestamp_to_event`.
I think a pagination token would be very useful to avoid fetching the `state` events from the Context API. It seems the Context API can be somewhat slow because of that.

2022-10-11 23:26 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +For our [roadmap of feature parity with
```suggestion
Alongside the [roadmap of feature parity with
```

2022-10-11 23:26 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +`event_id` returned by `/timestamp_to_event`.
This would need a spec clarification then.

2022-10-11 23:29 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +/_matrix/client/v1/rooms/{roomId}/timestamp_to_event?ts=<timestamp>?dir=[f|b]`
```suggestion
/_matrix/client/v1/rooms/{roomId}/timestamp_to_event?ts=<timestamp>&dir=[f|b]`
```

2022-10-11 23:31 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +`event_id` returned by `/timestamp_to_event`.
Created https://github.com/matrix-org/matrix-spec/issues/1280 to track this

2022-10-11 23:35 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +query parameter accepts `f` for forward-in-time from the timestamp and `b` for
For the archive usecase it's certainly useful, however for the messaging case we'd end up doing both calls anyways: can we add `dir=c` for closest, making that the default? `f` and `b` would still be available to optimize the path for archiving cases.

2022-10-11 23:36 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +In order to solve the problem where a remote federated homeserver does not have
sorry, which server is the remote federated homeserver? At a glance this sounds like a non-local server, but I don't think that's true here?

2022-10-11 23:37 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +`/context` from a client in order to get a pagination token.
I don't think this will work: the local server will now know the target event and events prior to it, but it will not know the events which come after the target event, making the client's eventual call to `/context` a lie.

2022-10-11 23:39 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +In order to solve the problem where a remote federated homeserver does not have
Ahh ye, this is a bit weird. I think the assumption here is around how the room creator server has all of the history and everyone else is a remote federated homeserver. But that's not how Matrix works.

I think we can just simplify to:

```suggestion
In order to solve the problem where a homeserver does not have
```

2022-10-11 23:41 UTC, turt2live commented
I don't think this concern is adding any value at the moment:

@mscbot resolve Context API doesn't appear to work with backfilling (likely spec bug)

... however there is still a problem with context and backfilling:

@mscbot concern Server doesn't appear to be able to forwards-fill over federation

----

I think generally this is back to being ready for review from the wider team, barring any edits which need to be made to the MSC itself.

2022-10-11 23:43 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +In order to solve the problem where a remote federated homeserver does not have
Updated ✅

2022-10-11 23:47 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +`/context` from a client in order to get a pagination token.
`/context?limit=0` will still work to get pagination token that works just fine `/messages?dir=b`

Paginating forwards (and not being able to get backfill) is an existing problem for all endpoints, `/messages`, `/context`.

Backfilling forwards is something I am interested in creating a separate MSC for as it's also useful for the Matrix public archive, https://github.com/matrix-org/matrix-public-archive/issues/72 (MSC even mentioned in the TODO there). And for permalinks in Matrix clients like Element which uses `/context` to render the spot in the timeline.

2022-10-11 23:57 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +`/context` from a client in order to get a pagination token.
It'd definitely be a seperate MSC regardless of the conversation here, though the concern is that the proposed timestamp endpoint ends up being non-functional if the local server can't forwards-fill its gap. This would create a dependency on that to-be-written MSC, I believe.

2022-10-12 00:00 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +`/context` from a client in order to get a pagination token.
(for clarity on the dependency: I don't think it's worth canceling the proposed-FCP status of this MSC, though it also can't enter FCP without the forwards-fill problem fixed, I think. That's dependent on the forwards-fill problem being a real problem, however).

2022-10-12 00:31 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +query parameter accepts `f` for forward-in-time from the timestamp and `b` for
... except in the messaging case the endpoint could land on event which is invisible to the client anyways, making "nearest" a bit pointless.

See https://matrix.to/#/!ewdjhNcPcEmYNKzlWp:t2l.io/$kPZ2rYl8EwCRLXF51iYu6z0rpHqYSTUa6DGhFnlVNkU?via=matrix.org&via=element.io&via=vector.modular.im

----

I'm going to count this thread as resolved - if this is false, please ping or raise a new thread.

2022-10-12 00:44 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +`/context` from a client in order to get a pagination token.
Synapse `/context` doesn't backfill at all currently. Synapse should backfill at least backwards using the current API's. This way we can avoid the `Unable to find event position in timeline` type errors when visiting a permalink. And we can avoid gaps better (related https://github.com/matrix-org/matrix-spec-proposals/pull/3871).

Not being able to backfill forwards predates this MSC though. `/timestamp_to_event`, `/context`, and `/messages` are all usable without forwards backfill. See the current usages already. When backfill forward is supported, it just opens up more use cases.

It feels like more like an enhancement, more than a blocker to me.

2022-10-12 04:23 UTC, turt2live commented on proposals/3030-jump-to-date.md
> +`/context` from a client in order to get a pagination token.
Synapse not backfilling sounds like a Synapse bug indeed, though I don't imagine the spec is super clear about this (it's not clear when or how a server is supposed to  backfill). 

Forward-fill feels almost required to me for this MSC, as otherwise the feature has a higher chance of user-facing failure. I'd also argue it's a spec problem that `/messages` doesn't have a way to forward fill either. An MSC which looks probable might be acceptable enough, even if it's not a hard blocker.

2022-10-12 04:35 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +`/context` from a client in order to get a pagination token.
> though I don't imagine the spec is super clear about this (it's not clear when or how a server is supposed to backfill).

Created https://github.com/matrix-org/matrix-spec/issues/1281 to track this


> An MSC [about forward-fill] which looks probable might be acceptable enough, even if it's not a hard blocker.

Since I was interested in the topic regardless of this MSC, I don't really have a problem with drafting this MSC sometime soon.

> Forward-fill feels almost required to me for this MSC, as otherwise the feature has a higher chance of user-facing failure.

But this level of failure feels the same as what you experience with `/messages` and `/context` today. So I still lean on the not-a-blocker side.

2022-10-19 08:20 UTC, richvdh commented on proposals/3030-jump-to-date.md
> +the room type and room version (for displaying warnings about stability).
I'm not entirely grokking why this is a problem. (Also, clients can just `GET /_matrix/client/v3/rooms/{roomId}/state/m.room.create/` if they want the create event?)

2022-10-19 17:20 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +token directly in another MSC ⏩
It's just meant as a "in the future", fast-forward, moving on, etc

Handles the vibe of "No need to dwell on this point, future thing"

2022-10-19 17:23 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +the room type and room version (for displaying warnings about stability).
It's not a problem, just that people should take note and make sure this works without issue. This is spawning from https://github.com/matrix-org/matrix-spec-proposals/pull/3030#discussion_r846444317

2022-10-19 18:55 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +homeserver receives a response from the federation endpoint, it should probably should
```suggestion
homeserver receives a response from the federation endpoint, it probably should
```

2022-10-19 19:27 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +query parameter accepts `f` for forward-in-time from the timestamp and `b` for
I've added something https://github.com/matrix-org/matrix-spec-proposals/pull/3030/commits/509c1b4e51a03adafc6264caa21fe14da1f743c2. I don't think I mastered the "brief" part of brief summary there though.

Please refine and whittle it down to what matters here.

2022-10-20 10:19 UTC, dbkr commented on proposals/3030-jump-to-date.md
> +the room type and room version (for displaying warnings about stability).
I think I'd have to agree that this has brought more confusion than clarity. If we wanted to be helpful here, I'd advise clients on the correct way to do it, ie. to fetch the create event, do that, and whatever the would now be the correct way of jumping to the start of the room timeline.

2022-10-20 10:26 UTC, dbkr commented on proposals/3030-jump-to-date.md
> +slight variation on the date or something.
Hmm - If the user has a slider that they can nudge, then sure, but if the interface is presented as just a calendar, or instance, then they could end up where selecting one particular day jumps them to a random point in time because a backfilled event happened to be closest to midnight on that day, which is going to seem quite surprising and flakey.

2022-10-20 11:15 UTC, richvdh commented on proposals/3030-jump-to-date.md
> +token directly in another MSC ⏩
personally, I'd find it clearer without the mystery emoji, but maybe that's just me being old.

2022-10-20 21:47 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +the room type and room version (for displaying warnings about stability).
Updated to suggest the right way to fetch the `m.room.create` event ✅

2022-10-20 22:09 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +slight variation on the date or something.
We can only hope that an event's `origin_server_ts` is relevant enough to its `prev_events` and descendants.

The new `destination_server_ts` field mentioned in this MSC is another potential helper. Clients could compare the `origin_server_ts` to the `destination_server_ts` on the event and decide to warn the user if there is a significant gap.

Even if there is a significant gap, it more matters if the surrounding `prev_events` are sensible. Since `origin_server_ts` can be whatever and is not enforceable , I can construct an event nestled under a `prev_event` with a nice preceding timestamp and nice descendants. Or I can just construct some evil events with `origin_server_ts: 0` or in the future to screw everyone up regardless.

Perhaps some heuristic to sort/prefer events which have the smallest `destination_server_ts - origin_server_ts` gap alongside how close `origin_server_ts` is to the requested `?ts`.

But that also doesn't make sense if people are joining the room for the first time since it will always be a big gap and potentially only backfill the rest of the history years later.

All this to say, I don't know of something better and keeping it simple with `origin_server_ts` is probably best.

---

In terms of Calendar UI, I plan to also have [hour-range time picking UI](https://github.com/matrix-org/matrix-public-archive/issues/7) in the Matrix public archive. Originally to go more fine-grained when there are too many messages to display for a given day, but I could see how it could be also useful for this situation of wanting a slightly different event to get somewhere better. Maybe hour range sliders would be good.

---

Homeservers could send daily heartbeat events that they trust themselves to be from the day. And we could start at the heartbeat event and find the closest to the given timestamp.

Doesn't help with existing rooms with history though.

2022-10-25 15:36 UTC, dbkr commented on proposals/3030-jump-to-date.md
> +slight variation on the date or something.
Yep, agreed I can't really think of a better way of dealing with the problem, it was more that the paragraph seemed to be dismissing it as a non-issue. I think I'd rather we just admit that it's a know problem but not letting perfect be the enemy of good.

2022-10-25 19:24 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +
Sounds superb @richvdh 👍👍

2022-10-25 19:24 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +query parameter accepts `f` for forward-in-time from the timestamp and `b` for
@richvdh refined this in https://github.com/matrix-org/matrix-spec-proposals/pull/3030#discussion_r1000510932

2022-10-25 19:35 UTC, MadLittleMods commented on proposals/3030-jump-to-date.md
> +slight variation on the date or something.
Added some more language around this which makes the problem more obvious with no perfect solution.

2022-11-01 08:52 UTC, turt2live commented
I appear to be the only one with the concern, so in the interest of not blocking this needlessly:

@mscbot resolve Server doesn't appear to be able to forwards-fill over federation

we should, however, figure out how to fix this at some point.

2022-11-06 12:21 UTC, merged

2022-11-07 08:37 UTC, dhenneke commented
<img width="482" alt="image" src="https://user-images.githubusercontent.com/720821/200263560-9415b6bd-a957-4374-978e-468f3222e45e.png">

@turt2live shouldn't this go into `main`?

2022-11-07 08:46 UTC, turt2live commented
Older MSCs go to old_master due to branch conflicts, and will be brought over to main over time (usually when I'm at a terminal that can cherry pick)

2022-11-07 22:02 UTC, MadLittleMods commented
Thanks all for the review! 😇

Next up is stabilizing the implementations in Synapse and Element where I made the experimental implementations.

2022-11-30 00:30 UTC, turt2live commented
Spec PR (WIP as of writing): https://github.com/matrix-org/matrix-spec/pull/1366

2022-12-21 19:06 UTC, uhoreg commented
Merged! :tada: