Room version capabilities
matrix-org/matrix-spec-proposals pull request #3244
Opened 2021-06-15 14:43 UTC by BillCarsonFr

2021-06-15 15:11 UTC, tulir commented on proposals/3244-room-version-capabilities.md
> +# MSC3244: Room version capabilities
I might be missing something, but I don't see why this data needs to come from the server. Standard room version capabilities don't vary across servers, so the supported features can just be hardcoded into clients. Only the list of supported room versions will vary, but that data is already available from the endpoint.

2021-06-15 15:20 UTC, turt2live commented on proposals/3244-room-version-capabilities.md
> +# MSC3244: Room version capabilities
yea... I'm not seeing what this is trying to accomplish. Room versions are meant to be frozen sets of functionality, particularly at the spec level, and not mutated over time. If someone were to create a `com.example.my_room_version` they'd almost certainly have to figure out a nested versioning scheme because once used the room version can't change behaviour.

2021-06-15 15:42 UTC, BillCarsonFr commented on proposals/3244-room-version-capabilities.md
> +# MSC3244: Room version capabilities
Currently cients never require a specific room version, and created room are using the default version at the time of creation.

If clients start hard coding room version, they will need to be continuously updated to be up to date. E.g if the default room version is updated (for security reason), the clients will force lower room version

2021-06-15 16:55 UTC, clokep commented on proposals/3244-room-version-capabilities.md
> +# MSC3244: Room version capabilities
I think the idea isn't whether or not the client specifies the room version, but that the clients would encode the information in them for what features a room version supports.

The argument against this is that the servers have to know this already (e.g. [Synapse's implementation](https://github.com/matrix-org/synapse/blob/d09e24a52d2cdd062efd73bc28e4fe2cd9bbab5e/synapse/api/room_versions.py#L78-L195)), so instead of hard-coding it into each client the server could pass the information to the client.

Maybe that's over-designed though and the proper thing is to codify a similar list in the clients?

2021-06-15 19:47 UTC, uhoreg commented on proposals/3244-room-version-capabilities.md
> +# MSC3244: Room version capabilities
The issue with having a list in the clients is that it can get outdated.  If I'm running an old client, and the server says that the default room version is "10", but the client doesn't know what room version "10" is, then it doesn't know if a room created with the default version will support knocking, or if it should specify that it wants room version "7".

Arguably, clients shouldn't be doing anything with room versions that they don't understand, but since most of the room version changes are server-side things, clients have been mostly fine just assuming that everything is (almost) the same.

2021-06-15 19:51 UTC, uhoreg commented on proposals/3244-room-version-capabilities.md
> +- msc3083 a.k.a restricted join rule support
In general, I think that we should be using meaningful names like `knocking` and `restricted_join` rather than MSC numbers.

2021-06-15 19:51 UTC, uhoreg commented on proposals/3244-room-version-capabilities.md
> +              "best": "7",
(bikeshedding) I think `preferred` would be better than `best`

2021-06-15 19:51 UTC, uhoreg commented on proposals/3244-room-version-capabilities.md
> +versions available on a given server, to give more feedbacks to users during room creation as well as
While I'm nit-picking, I might as well add some grammar corrections too.

```suggestion
The goal of this MSC is to give the client a way to have more information on the supported features of room
versions available on a given server, to give more feedback to users during room creation as well as
```

2021-06-15 19:51 UTC, uhoreg commented on proposals/3244-room-version-capabilities.md
> +then pick one of the stable version that appears in both `support` array.
```suggestion
then pick one of the stable version that appears in both `support` arrays.
```

2021-06-16 07:11 UTC, BillCarsonFr commented on proposals/3244-room-version-capabilities.md
> +- msc3083 a.k.a restricted join rule support
thx, updated with meaningful names

2021-06-16 12:26 UTC, clokep commented on proposals/3244-room-version-capabilities.md
> +then pick one of the stable version that appears in both `support` arrays.
A downside of this is that you can end up on an older room version since there's no ordering, e.g.

* `knocking`: preferred: 7, supports: 7, 8, 9
* `restricted`: preferred 9, supports: 8, 9

From here you could choose 8 or 9, but which to use? Maybe it doesn't really matter. 🤷

2021-06-16 13:04 UTC, BillCarsonFr commented on proposals/3244-room-version-capabilities.md
> +then pick one of the stable version that appears in both `support` arrays.
can we say that support is ordered?

2021-06-16 15:04 UTC, clokep commented on proposals/3244-room-version-capabilities.md
> +then pick one of the stable version that appears in both `support` arrays.
I'm not sure where that information would come from though. The server doesn't really have an ordered list of room versions it prefers.

2021-06-18 14:38 UTC, ara4n commented on proposals/3244-room-version-capabilities.md
> +          "knocking" : {
should we not namespace these to m.knocking or whatever? if only for symmetry with all our other identifiers?

2021-06-18 14:38 UTC, ara4n commented on proposals/3244-room-version-capabilities.md
> +        "org.matrix.msc2176": "unstable",
is it deliberate that these unstable room versions are removed in the below example?

2021-06-18 14:40 UTC, ara4n commented on proposals/3244-room-version-capabilities.md
> +If multiple capabilities are needed (e.g mscXX1 and mscXX2), and they have different `preferred` versions, clients can
I think we should make it clear that for real-world usage, the client implementation or end-user should not be selecting room version, but instead the choice of default & recommended room versions should be made by the server implementor (perhaps tweaked by a knowledgeable server admin).  This is what tripped me up on understanding this MSC.

2021-06-18 16:57 UTC, BillCarsonFr commented on proposals/3244-room-version-capabilities.md
> +        "org.matrix.msc2176": "unstable",
kind of, the below example is the future compared to that one, but it was also to reduce noise

2021-06-18 16:57 UTC, BillCarsonFr commented on proposals/3244-room-version-capabilities.md
> +          "knocking" : {
will check and use same name

2021-06-18 17:18 UTC, ara4n commented on proposals/3244-room-version-capabilities.md
> +        "org.matrix.msc2176": "unstable",
okay, then need to add a line to make it clear that between the two examples, the unstable versions were stabilised.

2021-06-19 07:59 UTC, erkinalp commented on proposals/3244-room-version-capabilities.md
> +If multiple capabilities are needed (e.g mscXX1 and mscXX2), and they have different `preferred` versions, clients can
> for real-world usage, the client implementation or end-user should not be selecting room version, but instead the choice of default & recommended room versions should be made by the server implementor 

How would that work with different room versions with entirely different capabilities? For example we currently only have persistent room versions, however, if we also get ephemeral room versions in the future, the server would be unable to select on its own. What I have in mind is the client sending a list of requested capabilities (knock, persistent/ephemeral, reversible redactions) and server returning the latest iteration of the *best matching* room version for those set of capabilities.

2021-06-19 12:45 UTC, KitsuneRal commented on proposals/3244-room-version-capabilities.md
> +If multiple capabilities are needed (e.g mscXX1 and mscXX2), and they have different `preferred` versions, clients can
It doesn’t work that way. An older client won’t  know about the capabilities introduced by the newer server release, therefore won’t be able to request any of those. And the other way around, if the client knows what to do with the new capability (already codified in a given room version) it won’t be able to request it from an older server release unless it already advertises support of that room version. If a user creating a room knows they need a specific room version _and_ their client _and_ homeserver support that room version, the user can request it; if not, defaults kick in.

2021-06-21 08:01 UTC, BillCarsonFr commented on proposals/3244-room-version-capabilities.md
> +If multiple capabilities are needed (e.g mscXX1 and mscXX2), and they have different `preferred` versions, clients can
> What I have in mind is the client sending a list of requested capabilities (knock, persistent/ephemeral, reversible redactions etc.) and server returning the latest iteration of the best matching room version for those set of capabilities.
@KitsuneRal 

This was one of the options, it works for room creation use cases but client would also need to be able to show different settings per room depending on the supported feature, so a capability api would anyway also be needed

2021-06-21 08:16 UTC, BillCarsonFr commented on proposals/3244-room-version-capabilities.md
> +          "knocking" : {
updaded to `knock` as per MSC

2021-06-21 08:17 UTC, BillCarsonFr commented on proposals/3244-room-version-capabilities.md
> +        "org.matrix.msc2176": "unstable",
added some context

2021-06-22 13:25 UTC, KitsuneRal commented on proposals/3244-room-version-capabilities.md
> +If multiple capabilities are needed (e.g mscXX1 and mscXX2), and they have different `preferred` versions, clients can
To show those settings/capabilities, at least one thing I as a client author would expect is a generic framework to receive (and display) human-friendly names for those settings/capabilities (and don't forget l10n...). And then I wonder if having that framework would be less of a development+maintenance chore than simply having the room versions, along with their features, defined in my own code.

2021-06-29 14:55 UTC, clokep commented on proposals/3244-room-version-capabilities.md
> +- `restricted` for restricted join rule support (msc3083)[https://github.com/matrix-org/matrix-doc/pull/3083]
```suggestion
- `knock` for knocking join rule support [MSC2403](https://github.com/matrix-org/matrix-doc/pull/2403)
- `restricted` for restricted join rule support [MSC3083](https://github.com/matrix-org/matrix-doc/pull/3083)
```

2021-06-29 15:17 UTC, clokep commented on proposals/3244-room-version-capabilities.md
> +then request to use the preferred version (`preferred`) that supports the feature, in the create room call:
This seems to imply that unstable room versions *can* be included in the response. This isn't 100% clear from the examples.

2021-06-29 15:17 UTC, clokep commented on proposals/3244-room-version-capabilities.md
> +In the hypothetical scenario where multiple capabilities would be needed (e.g mscXX1 and mscXX2), and have different `preferred` versions, clients can then pick one of the stable version that appears
Is there a benefit to having preferred and support separate as opposed to just an ordered array for support?

2021-06-29 15:26 UTC, t3chguy commented on proposals/3244-room-version-capabilities.md
> +In the hypothetical scenario where multiple capabilities would be needed (e.g mscXX1 and mscXX2), and have different `preferred` versions, clients can then pick one of the stable version that appears
We might want to be able to say `"preferred": null` whilst only unstable room versions support this, e.g right now for restricted, but still giving the clients the list of supporting room versions to know what UI to show for an experimental room version without needing to hardcode it.

2021-06-30 09:48 UTC, t3chguy commented on proposals/3244-room-version-capabilities.md
> +then request to use the preferred version (`preferred`) that supports the feature, in the create room call:
IMO `preferred` should always be stable, `support` should include all known room versions, inc unstable, as that field is what drives the UI of whether to show a particular setting

2021-07-01 07:38 UTC, t3chguy commented on proposals/3244-room-version-capabilities.md
> +`room_capabilities` | event type | `org.matrix.msc3244.room_capabilities`
PoC implementations:

+ https://github.com/matrix-org/synapse/pull/10283

Uses `"preferred": null` for `restricted` to never have `preferred` be an unstable version

2021-07-01 09:10 UTC, babolivier commented on proposals/3244-room-version-capabilities.md
> +          "knocking" : {
I also agree that these attributes should be namespaced as `m.*`, otherwise it gets inconsistent with the rest of the spec.

2021-07-19 15:34 UTC, BillCarsonFr commented on proposals/3244-room-version-capabilities.md
> +          "knocking" : {
the top level att are name spaces (m.room_versions, m.change_password) but not the content attributes (default/available/room_capabilities)

2021-08-10 17:24 UTC, turt2live requested changes

2021-08-10 17:24 UTC, turt2live commented on proposals/3244-room-version-capabilities.md
> +If a Home Server were to switch the new version as default to early, it will lock out all other users
```suggestion
If a homeserver were to switch the new version as default to early, it will lock out all other users
```

2021-08-10 17:24 UTC, turt2live commented on proposals/3244-room-version-capabilities.md
> +If a Home Server were to switch the new version as default to early, it will lock out all other users
applies throughout

2021-08-10 17:24 UTC, turt2live commented on proposals/3244-room-version-capabilities.md
> +# MSC3244: Room version capabilities
The server can't really be sure it's suggesting the right values though? If a client is developed with v8 in mind, it's not going to really know if v10 will also serve its purpose, and the server definitely won't know how the client expects to function. 

Room versions are non-linear, so in a hypothetical (and possibly likely down the line) scenario we could have v8 for knocking, v9 for enforced encryption, v10 for newfangled knocking+restricted cooperation, and v11 which mixes it all together. In this case, the client will want a feature called "knocking" but doesn't know that v10/11 are actually some completely new approach it has never heard of. It'd be irresponsible of the server to suggest this as a preferred version, but also it's not immediately clear what we'd do given it's keyed by feature name. Further, the server suggesting v11 could impact the user experience of the client even if the client did know about v10 (but not 11): it may very well not want to have encryption baked into the room, but the server will have suggested an unknown room version for new-knocking.

Overall, I do seriously wonder if this can be solved with process rather than tech. If we sped up the room version cutting process, would it alleviate the concerns of this MSC? Can we find a non-technical answer to communicating what is in a given room version and drive uptake?

2021-11-02 17:39 UTC, richvdh reviewed
I'm going to drop this review, as I found it sitting in a half-done state on github. It looks like it's still mostly relevant.

2022-04-21 17:59 UTC, MadLittleMods commented on proposals/3244-room-version-capabilities.md
> +- `restricted` for restricted join rule support [MSC3083](https://github.com/matrix-org/matrix-doc/pull/3083)
Are we allowing unstable capabilities to be added here?

It would be good to add a note that unstable capabilities are allowed with prefixes.

2022-04-26 15:47 UTC, turt2live commented
This has failed to get positive review and doesn't appear to be on a track for acceptance. To encourage people to raise their thoughts and fix the problems:

@mscbot fcp reject

2022-07-12 15:10 UTC, closed without merging

2025-08-11 08:27 UTC, t3chguy commented
This would have been a very helpful thing to have for the Hydra rollout, so clients don't need to hardcode room version compatibility lookup tables and possibly get it wrong for all new stable/unstable room versions.

2025-08-11 11:45 UTC, richvdh commented
Indeed. A champion to pick it up and do the remaining work to get it approved would be much appreciated.

2025-08-11 13:12 UTC, KitsuneRal commented
Ftr, one thing I would do differently from this MSC is focusing on the description of room version properties and sticking with that. So no interactive stuff, no choosing features in the UI, just enabling the clients to figure out how to handle which room version.