Room summary proposal
matrix-org/matrix-spec-proposals pull request #3266
Opened 2021-07-04 19:30 UTC by deepbluev7

Somewhat related to [MSC2946](https://github.com/matrix-org/matrix-doc/pull/2946) this provides an API to get a summary for a specific room either from the local server or over federation.

Useful for a few cases, where you need to show a summary for a room like matrix.to, traveler bots, showing spaces, lightweight clients, etc.

Signed-off-by: Nicolas Werner <nicolas.werner@hotmail.de>

2021-07-05 11:23 UTC, Sorunome commented on proposals/3266-room-summary.md
> +- Nextcloud may want to list the names and avatars of your `/joined_rooms` when
What about getting the summary or *all* your joined rooms at once, then, and not just of a single room? That was actually sorus usecase, and is not covered by this MSC

2021-07-05 11:52 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +- Nextcloud may want to list the names and avatars of your `/joined_rooms` when
I mostly did this on a per room basis, since this makes the API a bit simpler. I could see a few reasons, why one would want to call this with multiple rooms though. It may have better performance and reduces amount of requests a lot. To be able to cover all the use cases this intends to address atm, you would need to be able to submit a list of roomids, so that you can also peek rooms, to which you are not joined atm. This would complicate the API quite a bit. So imo, calling this once for each room is simpler with only some downsides.

Is that okay or do you think a bulk API is still necessary? Alternatively, we could wait to see, what the performance impact is once this is implemented somewhere.

2021-07-05 12:27 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +access to the summary.
Reminder to myself to check, what additional data is needed either in the request or the response, so that the requesting server knows, if it is allowed to forward this to the requesting user according. Especially with #3083 the requesting server may not have the required information about required space membership. This could be solved by adding a query parameter like `viaSpace` or listing the spaces, where the user is required to be a member of in the response.

2021-07-05 19:06 UTC, tulir commented on proposals/3266-room-summary.md
> +GET /_matrix/client/r0/rooms/{roomidOrAlias}/summary?
`/rooms` endpoints are always room ID only in the current C-S API. This should probably be `/summary/{roomIdOrAlias}` (like the alias /join endpoint), or just `/rooms/{roomId}/summary` and require using the generic alias query endpoint

2021-07-05 19:09 UTC, tulir commented on proposals/3266-room-summary.md
> +GET /_matrix/federation/v1/summary/{roomidOrAlias}
None of the existing federation endpoints take a room ID or alias, they're all room ID only. It's not necessarily a bad idea, but there should probably be some written justification for why this is different from everything else.

2021-07-05 19:11 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +GET /_matrix/client/r0/rooms/{roomidOrAlias}/summary?
I'm open to changing this, but I'd like to see some more discussion around this, since I am not sure, what the correct way is.

2021-07-05 19:12 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +GET /_matrix/federation/v1/summary/{roomidOrAlias}
Right, we shouldn't let a different server resolve the alias anyway, so just roomid makes more sense.

2021-07-05 19:36 UTC, tulir commented on proposals/3266-room-summary.md
> +GET /_matrix/client/r0/rooms/{roomidOrAlias}/summary?
I guess it depends on whether `/join/{roomIdOrAlias}` being its own thing is considered a mistake or not. Adding new endpoints as `/rooms/{roomIdOrAlias}/...` makes sense if there's some kind of a plan or intention to merge the joins into `/rooms/{roomIdOrAlias}/join`.

2021-07-09 15:08 UTC, haslersn commented on proposals/3266-room-summary.md
> +history visibility, space membership and similar rules outlined in
In case the client is able to view the room due to space membership, then maybe the request should also include the witness, i.e., the specific space, as a parameter.

In general (now or in the future) this parameter can be extended to be a list of spaces s_1, ..., s_n where

- the user is member of s_1
- s_i is an allowed room of s_{i+1} for 0 < i < n
- s_n is an allowed room of `roomidOrAlias`

in order to **transitively** allow viewing rooms without first joining the intermediate spaces s_2, ..., s_n.

2021-07-10 10:01 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +history visibility, space membership and similar rules outlined in
I alluded to this already in a different thread. The original design had a `viaSpace` parameter, that you could add (similar to the other vias) to say which spaces you are looking through. I removed that from my draft, because I didn't like how adding that parameter client side would change, what summary you get. But there seem to be significant benefits to this (i.e. also attesting space membership over federation, so that the requesting server can be sure, the requesting user is allowed to see that room). So the benefits seem to outweigh the drawbacks in this case.

2021-07-11 12:53 UTC, KitsuneRal commented on proposals/3266-room-summary.md
> +# MSC3266: Room Summary API
Before reviewing, just a quick note: there's already a "Room Summaries" MSC (MSC688) that introduces a `summary` object in sync responses; and, coincidentally, #1679 mentions #688 in the context of some of use cases below. In other words: the spec already has an entity called "room summary" that partially overlaps in purpose with the API suggested here. I haven't really read into this MSC yet but I guess it would be great if these two "room summaries" either were representations of the same thing, or had distinct naming.

2021-07-11 19:47 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +# MSC3266: Room Summary API
This MSC is more about requesting a similar summary to the one in the sync response, but with much more information. The summary in /sync only provides you with heroes and member counts. The other state events in this MSC are sent to the client in /sync as the stripped room state. Since this endpoint should be able to be called independently, it returns the important information from the summary in /sync as well as the stripped state events a client would need to display the room. So these MSCs encapsulate the same concept, but because they are "called" in different ways, the returned data differs slightly.

Does renaming this MSC to "Room Summary API" or "Room Summary Endpoint" help resolve those concerns?

2021-07-12 06:50 UTC, KitsuneRal commented on proposals/3266-room-summary.md
> +# MSC3266: Room Summary API
"Room Summary API" would better connect to what's there, thanks. But actually it just wasn't clear that you're building or at least borrowing from the existing room summary structure, since the MSC doesn't refer to #688 or room summary in the sync response (I might have just overlooked though). Actually, the same applies to #2946, it's not really clear whether it connects to #688 summaries or not.

2021-07-12 14:56 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +# MSC3266: Room Summary API
I've added `/sync` to the alternatives section, which also mentions (and links) #688. In the end though the existing summaries in `/sync` are really specific to `/sync` as such there is very little overlap. I've tried to clarify, why that is the case. Does that make it clearer?

2021-07-14 10:12 UTC, t3chguy commented on proposals/3266-room-summary.md
> +| is_direct          | Optional. If this is a direct chat. The server should use the usual rules to figure out, if this is a direct chat, not just look in the create event. | May be used in previews
this feels super weird to me given that it isn't a property of the room

> The server should use the usual rules to figure out, if this is a direct chat, not just look in the create event.

The server's rules for is it a DM (in the context of push rules) are "does this room have exactly 2 members)

Whether a room is a DM or not depends on your own account_data (`m.direct`) and is user-specific.

The exception here is for invites which have the flag on the invite event (not on the create event as that's immutable)

This feels very edge-casey.

2021-07-14 10:14 UTC, t3chguy commented on proposals/3266-room-summary.md
> +missing.
without auth is probably overkill, though it should definitely be permitted to guests. 

Otherwise on closed servers with public rooms you'd be able to brute force room IDs/common aliases and find out what is effectively private metadata (public room on closed instance) without having an account

2021-07-14 10:18 UTC, t3chguy commented on proposals/3266-room-summary.md
> +    rooms being returned.
it does work for arbitrary rooms as it'll include the room you are asking about

```
await mxMatrixClientPeg.matrixClient.getSpaceSummary("!YTvKGNlinIzlkMTVRl:matrix.org");

{
    "rooms": [
        {
            "room_id": "!YTvKGNlinIzlkMTVRl:matrix.org",
            "name": "Element Web/Desktop",
            "topic": "https://element.io | Stable: 1.7.32 | Release status: RC planned for 14 Jul | Code & bugs at https://github.com/vector-im/element-web | Release notes in #element-web-announcements:matrix.org | Give feedback on desktop/webapp here; Mobile app feedback at #element-android:matrix.org and #element-ios:matrix.org",
            "canonical_alias": "#element-web:matrix.org",
            "num_joined_members": 8800,
            "avatar_url": "mxc://t2l.io/b27f5b7b7f91e58063a30e0ca53cbc79d242fe2b",
            "world_readable": true,
            "guest_can_join": false,
            "creation_ts": 1564523018972
        }
    ],
    "events": []
}
```

2021-07-14 10:20 UTC, t3chguy commented on proposals/3266-room-summary.md
> +    over federation (yet).
Also the `/state` API doesn't return stripped state events https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-rooms-roomid-state

The specific state API does return stripped state (because consistency, what's that) https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-rooms-roomid-state-eventtype-statekey

But would require MANY API hits and not be able to reach all the data (e.g `num_joined_members` would not be possible)

2021-07-14 10:24 UTC, tulir commented on proposals/3266-room-summary.md
> +missing.
I think it should be possible to use without auth if the homeserver wants to allow it. I definitely don't want to enable guest access, but having matrix.to fetch previews for my rooms directly from my server is fine. /publicRooms requiring auth is already up to the homeserver admin in the same way.

2021-07-14 10:24 UTC, t3chguy commented on proposals/3266-room-summary.md
> +    `/_matrix/federation/unstable/im.nheko.summary/{roomid}`
this won't work well for some implementations which keep the prefix and rest of the path separate,

e.g prefix should be `/_matrix/client/unstable/im.nheko.summary`
full path should be `/_matrix/client/unstable/im.nheko.summary/rooms/{roomidOrAlias}/summary`

Once it passes FCP just changing the prefix would correct the path (`/_matrix/client/r0`)

2021-07-14 10:26 UTC, t3chguy commented on proposals/3266-room-summary.md
> +missing.
> /publicRooms requiring auth is already up to the homeserver admin in the same way.

The spec disagrees.

> Requires auth:	No.

https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-publicrooms

2021-07-14 10:33 UTC, tulir commented on proposals/3266-room-summary.md
> +missing.
Yeah the requires auth field in the spec is a bit dumb: #2949

2021-07-14 11:59 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +| is_direct          | Optional. If this is a direct chat. The server should use the usual rules to figure out, if this is a direct chat, not just look in the create event. | May be used in previews
I was thinking of looking it up in account data. This could be useful to exclude this room, if you don't want to show DMs. But I can remove that, if that sounds useless.

2021-07-14 12:06 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +    rooms being returned.
Oh, I did not notice that when reading that MSC. From the context I just assumed it only worked for spaces and their children. It doesn't however have a mechanism to suggest space membership over federation, if you are peeking a specific space room, right? (Assuming #3083 applies to that room) So you would at least still have to peek all rooms in that space to peek a specific space room only?

2021-07-14 12:11 UTC, t3chguy commented on proposals/3266-room-summary.md
> +    rooms being returned.
Not sure I follow

> It doesn't however have a mechanism to suggest space membership over federation, if you are peeking a specific space room, right?

it has the `allowed_rooms` field which tells you which room IDs grant you access into the room

2021-07-14 13:21 UTC, t3chguy commented on proposals/3266-room-summary.md
> +missing.
I take it back, I thought m.to registered guest accounts but it doesn't.

Would be nice if this was unauth as specified

2021-07-14 13:35 UTC, t3chguy commented on proposals/3266-room-summary.md
> +
I have a pair of PoC implementations

matrix.to: https://github.com/matrix-org/matrix.to/pull/219
Doesn't do anything with the extra fields yet (extra beyond PublicRoomsChunk)

Synapse: https://github.com/matrix-org/synapse/pull/10394
Doesn't do s2s API
Doesn't have `is_direct`
No tests
Includes the `allowed_spaces` field from MSC2946

2021-07-14 13:43 UTC, t3chguy commented on proposals/3266-room-summary.md
> +
![image](https://user-images.githubusercontent.com/2403652/125632469-39651b22-cabe-4085-88f2-1d3ce4e82f58.png)

```
GET http://localhost:8008/_matrix/client/unstable/im.nheko.summary/rooms/!GjGVltztZkxAfxCQHb:localhost/summary

HTTP/1.1 200 OK
Transfer-Encoding: chunked
Server: Synapse/1.38.0
Date: Wed, 14 Jul 2021 13:28:03 GMT
Content-Type: application/json
Cache-Control: no-cache, no-store, must-revalidate
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: X-Requested-With, Content-Type, Authorization, Date

{
  "room_id": "!GjGVltztZkxAfxCQHb:localhost",
  "name": "Testing",
  "topic": "TOPIC",
  "canonical_alias": "#test-space1:localhost",
  "num_joined_members": 2,
  "avatar_url": "mxc://localhost/WOLlkMstLJfySAqBnFGUIcGx",
  "join_rules": "public",
  "world_readable": false,
  "guest_can_join": true,
  "creation_ts": 1625494118811,
  "room_type": "m.space",
  "is_encrypted": false,
  "membership": "join"
}

2021-07-14 13:46 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +    rooms being returned.
You need some way to tell the other server over federation, what user wants to see the room preview. This works for the spaces summary API, since it implicitly knows, which space the user is peeking via, so it doesn't need to know the actual user, that is peeking. If you only want to get the summary for a single room, the spaces summary API has no way to provide information on which space the user is peeking via. So you need to fetch the summary for all the rooms in the space to peek a specific space room.

(The `allowed_rooms` field is only in the response, but you need to tell how you are peeking the room in the request, I think.)

2021-07-14 13:50 UTC, t3chguy commented on proposals/3266-room-summary.md
> +    rooms being returned.
> You need some way to tell the other server over federation, what user wants to see the room preview.

No? You could filter that locally and use the response to build your local cache.

That's how the space summary APIs appear to work anyhow. The response is granted if any user on the requesting HS is allowed access to the data

> This works for the spaces summary API, since it implicitly knows, which space the user is peeking via

Except the same issue applies to the root space which isn't being peeked by anything yet could still have the same visibility restrictions e.g private/invite-only/restricted join rule

2021-07-14 17:55 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +    rooms being returned.
Hm, someone raised a concern that checking all the spaces would be too expensive and that you should send a hint for which spaces you are in in the request. So that's what I was thinking of.

2021-07-14 18:23 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +    `/_matrix/federation/unstable/im.nheko.summary/{roomid}`
I changed the paths now, do they look good now?

2021-07-14 18:25 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +| is_direct          | Optional. If this is a direct chat. The server should use the usual rules to figure out, if this is a direct chat, not just look in the create event. | May be used in previews
I removed this field now. A different MSC can add that back, if someone has a use case.

2021-07-14 18:26 UTC, t3chguy commented on proposals/3266-room-summary.md
> +additions: `room_type`, `membership` and `is_encrypted`.
in the future it might be easier referencing MSC2946 as I'll likely "convince" it to also adopt the `is_encrypted` flag so then the only new field will be `membership`

2021-07-14 18:26 UTC, t3chguy commented on proposals/3266-room-summary.md
> +exception of `membership`.
but this is an easily derived field, `|| "leave"`

2021-07-14 18:28 UTC, t3chguy commented on proposals/3266-room-summary.md
> +    `/_matrix/federation/unstable/im.nheko.summary/{roomid}`
Yup!

2021-07-14 18:37 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +history visibility, space membership and similar rules outlined in
I have now added the `allowed_room_ids` as in the other MSC.

2021-07-14 18:40 UTC, t3chguy commented on proposals/3266-room-summary.md
> +    rooms being returned.
I think its `allowed_rooms` in the s2s implementation of the space summary anyway. I'll be experimenting (ab)using the space summary s2s API instead of a dedicated S2S API for this MSC

2021-07-14 18:45 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +access to the summary.
Done this now with the allowed_room_ids field.

2021-07-14 18:53 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +    rooms being returned.
Is there any good reason to not just use the spaces summary API with a limit of 1 room instead of this?

2021-07-14 18:58 UTC, t3chguy commented on proposals/3266-room-summary.md
> +    rooms being returned.
a more expected API shape, I think they should be 2 CS APIs, but share a lot of internals and 1 SS API

2021-07-14 19:05 UTC, t3chguy commented on proposals/3266-room-summary.md
> +    `m.space.child` events in a space.
not only by default, I don't think there's any way currently to skip all the depth=1 stuff

2021-07-14 19:08 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +    provided by the server (that looks like this proposal).
I'm thinking of changing this proposal to match this alternative. That way this could be used also for bulk use cases like loading summaries for all joined rooms in a thin client or other clients, that just show a room list but no messages (and don't update it). Anyone has any thoughts on that (@t3chguy maybe?)

Basically the current CS GET would stay, but another POST would be added with a format like this:

```
POST /_matrix/client/r0/summary

{
    "rooms": [
        {
            "room": "idOrAlias",
            "via": ["list","of","servers","to","try"]
        },
        {
            "room": "otherIdOrAlias",
            "via": ["other","list","of","servers","to","try"]
        }
    ]
}
```

And the federation API would use that same POST, without the via's (Or maybe simplified to just a list of room ids).

2021-07-15 07:39 UTC, t3chguy commented on proposals/3266-room-summary.md
> +    provided by the server (that looks like this proposal).
that would fit the space summary response type too, ` { rooms: [...] }` just without the events field which would allow for even greater code re-use

I have no usecases of a bulk variant personally, Element for the Spaces project (space previews in matrix.to) will need the room summary API so would prefer to minimise the scope where possible.

2021-08-10 18:16 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +    provided by the server (that looks like this proposal).
I would appreciate some SCT input on this. Basically I would like input on the following questions before I decide to make changes on to this MSC:

- Should this MSC focus on summaries for a single room or should it also add a `POST` bulk API like above?
- Should it try to reuse the spaces summary federation API or is having a similar federation API fine?
- Since this is API is similar to calling the spaces summary API on a single room, is there value in adding a separate API?

2021-08-10 18:18 UTC, turt2live commented
idea reviewer: feedback on https://github.com/matrix-org/matrix-doc/pull/3266#discussion_r686213648 is specifically appreciated.

2021-08-10 18:19 UTC, clokep commented on proposals/3266-room-summary.md
> +    provided by the server (that looks like this proposal).
Also note that MSC2946 has gone through a pretty dramatic re-design since MSC3266 was proposed. I think the functionality here can be match by using that API with `max_depth=0`. This might still give a "better" result though. 🤷

2021-08-10 18:24 UTC, t3chguy commented on proposals/3266-room-summary.md
> +    provided by the server (that looks like this proposal).
> Since this is API is similar to calling the spaces summary API on a single room, is there value in adding a separate API?

For use-cases like matrix.to MSC2946 /hierarchy API doesn't work due to it requiring auth, whereas this MSC proposes an API which does not require auth.

2021-08-13 12:00 UTC, clokep commented on proposals/3266-room-summary.md
> +    provided by the server (that looks like this proposal).
> > Since this is API is similar to calling the spaces summary API on a single room, is there value in adding a separate API?
> 
> For use-cases like matrix.to MSC2946 /hierarchy API doesn't work due to it requiring auth, whereas this MSC proposes an API which does not require auth.

We could change MSC2946 to not require auth if there's a use-case. No one has commented saying that it is useful to have it not require auth. I usually just default to only allowing authenticated users.

2021-08-20 10:22 UTC, kegsay commented on proposals/3266-room-summary.md
> +GET /_matrix/client/r0/rooms/{roomidOrAlias}/summary?
Aliases shouldn't go under `/rooms/` - this is what `/join/{roomIdOrAlias}` exists in the first place.

2021-08-20 10:27 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +GET /_matrix/client/r0/rooms/{roomidOrAlias}/summary?
So it should be `/summary/{roomIdOrAlias}`?

2021-09-07 16:24 UTC, richvdh commented on proposals/3266-room-summary.md
> +    provided by the server (that looks like this proposal).
wearing an SCT hat: if there is a way to do this without introducing a brand new API endpoint, I would be very much in favour of that. If the only reason that #2946 doesn't work for this usecase is that it requires auth, then let's explore changing that. I think #2946 is about to go into FCP, so at this point it might be better done as a separate MSC rather than trying to tack it onto #2946.

2021-09-14 18:24 UTC, bmarty commented on proposals/3266-room-summary.md
> +- `roomidOrAlias` can be the roomid or an alias to a room.
Generally the case for "roomid" id "roomId", with a capital I.

2021-09-14 18:29 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +- `roomidOrAlias` can be the roomid or an alias to a room.
Right, makes sense to fix that for the stable version, if this gets merged!

2021-09-14 18:38 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +    provided by the server (that looks like this proposal).
Okay, I think my conclusion from this is, that at least for a few client being able to generate a summary for one room is useful. #2946 is too focused on returning a summary of rooms in a space and having a more focused CS endpoint would be valuable. But over federation we should reuse the federation API of #2946 instead. I'm going to clean up this MSC with that goal in mind. If someone thinks just removing the auth requirements on the hierarchy endpoint is a better idea, I would suggest making a competing MSC, because in my opinion this MSC is more in the realm of providing a convenient API, similar to how we have APIs to manipulate push_rules (instead of allowing writes to account data) and changing the display_name (instead of sending state events in every room) or the 9 endpoints to update key backup data. Implementation overhead should be fairly minimal for servers, but should make the client implementation easier, which I think is a big enough benefit, considering how many clients there are and some users of this API might be especially thin clients.

2021-10-06 16:44 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +GET /_matrix/client/r0/rooms/{roomidOrAlias}/summary?
Moved it there now.

2021-10-06 16:45 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +    rooms being returned.
Made this MSC now reuse the SS API.

2021-12-03 23:51 UTC, turt2live commented
The author believes this MSC has all applicable implementations and is ready enough for FCP. It's not entirely clear what the next steps are for this one given the lack of SCT review, however the expectation is that someone will argue for it to be in a different status :)

2021-12-06 17:20 UTC, KitsuneRal requested changes
A few smaller things, overall LGTM from the client-server perspective.

2021-12-06 17:36 UTC, ShadowJonathan commented on proposals/3266-room-summary.md
> +    complex.
I can fill in some of this rationale here; peeking requires the server to effectively "pre-join" the room, processing it as if it was joining, which would require substantially more computation and resources than simply querying a preview from another server. Of course, this has security implications, but while this is proxied preview data, the other is a full-blown soft-join.

2021-12-06 17:40 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +    complex.
Also the client API is much lighter weight then peeking a room (in many cases about as much data as a single room event). Peeking could be used for the federation side in the future, but having an API to preview a room easily client side is still useful on top of that. But I'll fix that in the proposal.

2022-03-08 16:11 UTC, erikjohnston commented on proposals/3266-room-summary.md
> +    `m.space.child` events in a space. (We do reuse the federation API now.)
I think that this is the only thing left open in my mind: do we want to add this new API when we have an existing one that mostly is the same, but with different defaults? Personally, I don't mind that too much if its made explicit in the spec.

Otherwise, I think this is ready for FCP?

2022-03-08 16:26 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +    `m.space.child` events in a space. (We do reuse the federation API now.)
I need to check some stuff with the encryption property still. I'm not sure if that is in the hierarchy API, even though it should be. But I have been swamped a bit with my thesis, which is why I didn't have time to finish this at the moment. I also need to fix some issues with the implementation PR. So I don't think it is ready for FCP atm, but that is mostly my lack of time atm, sorry!

2022-03-08 16:28 UTC, t3chguy commented on proposals/3266-room-summary.md
> +    `m.space.child` events in a space. (We do reuse the federation API now.)
This new API doesn't require auth (for usage like matrix.to) vs /hierarchy (previously known as Space Summary) which does require auth

2022-03-08 16:35 UTC, anoadragon453 commented on proposals/3266-room-summary.md
> +#### Rationale and description of reponse fields
```suggestion
#### Rationale and description of response fields
```

2022-03-08 16:35 UTC, anoadragon453 commented on proposals/3266-room-summary.md
> +    `m.space.child` events in a space. (We do reuse the federation API now.)
The semantics of this API are nicer than the spaces summary API for the single-room, non-space hierarchy exploration usecase; this endpoint accepts room aliases, and has a clearer path.

Despite this API not really having any functional advantages over spaces summary, it feels odd to suggest the spaces summary API to clients when they would like a summary of a room that's not a space.

While the endpoints are similar now, I think including them both allows each to grow in different directions for different usecases.

So +1 to FCP.

2022-03-22 16:32 UTC, richvdh commented on proposals/3266-room-summary.md
> +    `m.space.child` events in a space. (We do reuse the federation API now.)
> So I don't think it is ready for FCP atm, but that is mostly my lack of time atm, sorry!
 
No worries - will put this back in draft for now!

2022-05-02 18:07 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +    `m.space.child` events in a space. (We do reuse the federation API now.)
Since I had several instances where I could have really used this MSC now, I finally got back to it, updated the federation implementation (which was much easier now that that code in Synapse has matured and the old MSCs got removed from it) and finally updated the MSC. I am happy with it now, let's see what everyone else thinks! <3

2022-05-02 18:36 UTC, turt2live commented
The author believes this is ready for FCP.

2022-05-04 11:58 UTC, clokep commented on proposals/3266-room-summary.md
> +| version            | Optional (for historical reasons). Version of the room.                                                                                               | Can be used by clients t
I think this is the room version? I'd recommend the field be called `room_version` to match other APIs in the C-S API.

The value also needs to be a string, not an int, as shown in the example.

2022-05-04 18:24 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +| version            | Optional (for historical reasons). Version of the room.                                                                                               | Can be used by clients t
Right, makes sense. Especially next to room_type.

2022-05-04 18:26 UTC, clokep commented on proposals/3266-room-summary.md
> +| version            | Optional (for historical reasons). Version of the room.                                                                                               | Can be used by clients t
Yep! I mostly just think it is *always* referred to be `room_version`, so best to be consistent! 🎉 Thanks for updating it!

2022-07-04 18:21 UTC, turt2live requested changes
I think this needs a stronger implementation proof than matrix.to on the client side. While matrix.to is an obvious consumer of this API, I'm hesitant to put spec in place which supports only matrix.to and not other clients. At the moment, it appears as though other clients *don't* need this due to lack of implementation, which I'm sure is false.

2022-07-05 07:47 UTC, deepbluev7 commented
@t3chguy Thanks, I added that one to the PR summary! I tried to find it yesterday, but missed it :D

2022-07-05 07:50 UTC, t3chguy commented
@deepbluev7 looks like Element Web is using it too. https://github.com/matrix-org/matrix-js-sdk/blob/9bf8b936d4b1312b5f24819c1cd3621d58ee4451/src/client.ts#L8925-L8937 https://github.com/matrix-org/matrix-react-sdk/blob/658ff4dfe6c93ca602060133054e45e859c6f32d/src/components/views/rooms/RoomInfoLine.tsx#L38

2022-07-05 08:00 UTC, deepbluev7 commented
Added, thanks. Is only used for member counts on space invites it seems though, but I guess that's where this endpoint is useful. And easy way to get misc info on a random room in a uniform manner.

2022-07-19 14:17 UTC, richvdh commented on proposals/3266-room-summary.md
> +    provided by the server (that looks like this proposal).
> Since I got the feedback I wanted and adapted the MSC, I'm resolving this.

have updated the PR description accordingly

2022-07-19 14:18 UTC, richvdh commented on proposals/3266-room-summary.md
> +
Can we resolve this thread?

2022-07-19 14:53 UTC, richvdh reviewed
I think this is generally good, but I have a lot of requests for clarification

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +([MSC2946](https://github.com/matrix-org/matrix-doc/pull/2946)) only provides
Now that this is in the spec, it would be great to update the link:

```suggestion
the use cases. The [spaces hierarchy API](https://spec.matrix.org/v1.3/client-server-api/#get_matrixclientv1roomsroomidhierarchy) only provides
```

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +alias and a corresponding server-server API, to fetch a summary over federation.
```suggestion
A new client-server API, which allows you to fetch a summary of a room by id or
alias, and a corresponding server-server API to fetch a summary over federation.
```

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +(This is not under `/rooms`, because it can be used with an alias.
ok, but can we call it `room_summary` ?

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +- `via` are servers, that should be tried to request a summary from, if it can't
```suggestion
- `via` are servers that should be tried to request a summary from, if it can't
```

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +| room_version       | Optional (for historical reasons). Version of the room.                                                                                               | Can be used by clients t
what historical reasons? Isn't this a new api?

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +| room_id            | Id of the room                                                                                                                                        | Useful, when the API is
```suggestion
| room_id            | Id of the room                                                                                                                                        | Useful when the API is called with an alias or to disambiguate multiple responses clientside.                                        |
```

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +| room_id            | Id of the room                                                                                                                                        | Useful, when the API is
erm why is it necessary to disambiguate multiple responses? HTTP has a 1:1 request:response relationship.

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +- Nextcloud may want to list the names and avatars of your `/joined_rooms` when
a bulk endpoint seems like a different MSC. Can we resolve this thread?

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +user is already a member of that room.
long sentence is very long, and ambiguous. "It returns the summary of the specified room ... if the user is already a member of the room" ? Or "It returns a summary ... as well as if the user is already a member of the room"?

Also MSC3173 is now part of the spec, so please update the link.

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +All those fields are already accessible as the stripped state according to
this is unclear - I don't think you mean *all* the fields?

```suggestion
`room_type`, `room_version` and `encryption` are already accessible as part of the stripped state according to
```

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +[MSC3173](https://github.com/matrix-org/matrix-doc/pull/3173), with the
please update link: https://spec.matrix.org/v1.3/client-server-api/#stripped-state

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +  join_rules: "public",
`/publicRooms` and `/hierarchy` use `join_rule` here, not `join_rules`. Please let's follow the existing convention.

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +exception of `membership`. These are the same fields as in
> These are the same fields

Are we referring to `room_type`, `membership`, `room_version` and `encryption`, or *all* of the fields? Please be clear. In either case it doesn't appear to be accurate as `/hierarchy` does not spec an `encryption` or `room_version` field.

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +adition of the membership field. The membership can already be accessed by a
addition

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +[MSC2946](https://github.com/matrix-org/matrix-doc/pull/2946) apart from the
again, please update link

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +| membership         | The current membership of this user in the room. Usually `leave` if the room is fetched over federation.                                              | Useful to distinguish in
Is this a required field? Is it omitted or set to `leave` if the user has never been a member of the room? (presumably `leave`, but please be explicit)

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +| join_rules         | Join rules of the room                                                                                                                                | Copied from `publicRooms
It would be good to be explicit which of these are required and which optional.

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +missing.
Please add the fact that `membership` is omitted when unauthenticated to the table above.

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +[MSC2946](https://github.com/matrix-org/matrix-doc/pull/2946) is reused. This
update link please

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +degrading gracefully.
this is a bit of an implementation detail, no?

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +author.)
```suggestion
(Originally there was a separate federation API for this, but it was decided
by the author that lowering the duplication on the federation side is the way to go.)
```

2022-07-19 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +summary API (MSC2946) for spaces or caching the state received via `/sync`.
update link please. It's no longer called the "batched summary api"

2022-07-19 14:58 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +
Yeah, it is mostly here as a comment about an implementation, it is not really a concern.

2022-07-19 15:04 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +| room_version       | Optional (for historical reasons). Version of the room.                                                                                               | Can be used by clients t
This reuses the /hierarchy API for the federation bits. That used to not have a room_version field. Also some rooms don't have a version in the create event. To make the introduction of this endpoint easier, it doesn't require a new revision of the /hierarchy API, but can work with older versions as well, but in those cases you might be missing some fields. I think that is the most reasonable migration path. The alternative is to have this endpoint return nothing when talking to older servers and introduce an additional federation endpoint.

2022-07-19 15:05 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +degrading gracefully.
Yes, I just left it there as a note before people ask about it, so that I don't need to answer it.

2022-07-19 15:31 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +(This is not under `/rooms`, because it can be used with an alias.
I don't really care about the name, but all the other endpoints are called /join/ and such as well, so I thought /summary/ would be more consistent with that, since it is followed by a room id/alias.

2022-07-19 16:03 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +user is already a member of that room.
I tried to refer to /hierarchy as much as possible now and gave a small summary of the rules, but it is basically what falls under "potential joiner" there.

2022-07-19 16:04 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +  join_rules: "public",
Updated, but originally the /hierarchy endpoint mistakenly used join_rules and this example was copied from there, which copied the mistake.

2022-07-19 16:05 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +| join_rules         | Join rules of the room                                                                                                                                | Copied from `publicRooms
Added explicit annotations to all of them

2022-07-19 16:06 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +missing.
Since it didn't fit the table, I added a footnote. Otherwise the table blows up too much.

2022-07-19 16:07 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +exception of `membership`. These are the same fields as in
No, the encryption and room_version fields are explicitly added, the text was inaccurate since I originally didn't notice that (since they are part of the stripped state) and I forgot to update this sentence. Done that now.

2022-07-26 15:29 UTC, richvdh commented on proposals/3266-room-summary.md
> +(This is not under `/rooms`, because it can be used with an alias.
I think that for `/join` and `/knock`, it's a bit more obvious that we're talking about a room. `/summary` could be anything, really.

I'd be interested what other people think.

2022-07-26 17:02 UTC, richvdh requested changes

2022-07-26 17:06 UTC, richvdh commented on proposals/3266-room-summary.md
> +- The
I'm afraid that, as currently formatted, this section is a bit of an impenetrable wall of text. It would be nice to format it in sections with a separate heading for each alternative (see https://github.com/matrix-org/matrix-spec-proposals/blob/old_master/proposals/1772-groups-as-rooms.md#rejected-alternatives for an example). But I won't insist, this isn't really a normative section of the MSC.

2022-07-26 21:37 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +(This is not under `/rooms`, because it can be used with an alias.
I don't have a strong opinion on it, so we can change to to whatever, but I would appreciate some more opinions since otherwise I might need to flip flop between names again.

2022-07-26 21:46 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +public or you already being a member. For unauthenticated requests a response
Ref: https://github.com/matrix-org/matrix-spec/issues/1184
Ref: https://github.com/matrix-org/matrix-spec/issues/1186

I really just wanted to reuse whatever the spaces summary API MSC did and I want to apply the same rules. That this didn't make it into the spec properly is not ideal, but can I just handwavy refer to using the same rules to that? It's not like this intends to use any different rules and it should also not be on this MSC to clarify it. Currently `knock`able rooms are previewable using the /hierarchy API. So however I describe it here would be wrong. I honestly liked my original wording of "potentially joinable rooms" best, since that is how the spaces summary API MSC described it and I feel like any explicit explanations will just need to be updated time and time again as people figure out the gaps in the original spaces summary MSC. The intent is to have a preview of rooms you are interested in joining or are joined to. So all rooms that I am allowed to get information on, I should get information on and this should just follow the already existing rules for that from the spec.

2022-07-26 21:53 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +| room_version       | Optional (for historical reasons). Version of the room.                                                                                               | Can be used by clients t
> Has it been added since?

No, this MSC adds it, since it is a very useful field and it also can then be used to resolve a "FIXME" in the synapse code for that endpoint, where there is an open question about some joinrules being supported in a room, since we currently don't know the version in the /hierarchy handler.

2022-07-26 22:14 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +- The
I split it up with headings. Some of the titles are a bit random, but... it is hard to think of better ones and I don't think they matter as much.

2022-07-26 22:18 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +`encryption` fields. The membership can already be accessed by a client anyway,
Yeah, merging that into the previous paragraph made it a lot clearer.

2022-07-26 22:20 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +exception of `membership`. These are the same fields as in the response to
It made sense before I reshuffled the sentence. Fixed.

2022-07-26 22:20 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +to the local server).
That was mostly me being unsure about if that would be possible. But it clearly should not be possible, so I just state that now.

2022-07-26 22:21 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +| room_version       | Optional (for historical reasons). Version of the room.                                                                                               | Can be used by clients t
(Added a footnote as well, that explains that this isn't present over federation rn and can only reasonably be required at a later point.)

2022-07-26 22:27 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +public or you already being a member. For unauthenticated requests a response
I guess your proposal is a lot more handwavy and not explicit anymore, so that might be the best option actually.

2022-07-26 22:32 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +public or you already being a member. For unauthenticated requests a response
I applied your suggestion now, but I am not sure how understandable it is now without any references to existing APIs.

2022-07-28 11:59 UTC, richvdh commented on proposals/3266-room-summary.md
> +returned if the room is publicly accessible.
right, so this means being `knockable` is not sufficient to make the contents visible ( since a user who has not yet received an invite to a knockable room lacks the necessary permissions to join it).

So this seems to be in conflict with the current Synapse implementation.

We may need to reach a decision on https://github.com/matrix-org/matrix-spec/issues/1186 if we are to avoid the two endpoints having subtly different behaviour.

2022-07-28 11:59 UTC, richvdh commented on proposals/3266-room-summary.md
> +period this field could be made a required field.
Ok, I don't think the validation in `_is_remote_room_accessible` is relevant here, since this table is about `/_matrix/client/v1/summary/` rather than ` /_matrix/federation/v1/hierarchy/{roomId}`. All we need to say is:

```suggestion
(2) Prior to this MSC, `/_matrix/federation/v1/hierarchy/{roomId}` doesn't
return the room version, so `room_version` may be unavailable for remote
rooms.
```

2022-07-28 11:59 UTC, richvdh commented on proposals/3266-room-summary.md
> +- The
This is much more accessible now, thanks!

2022-08-01 11:16 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +returned if the room is publicly accessible.
The intention was always to allow access to the same rooms the hierarchy API allows access to. I don't think we need to wait for a decision on those spec issues, since the behaviour should be the same in any case. I added the explicit mention of that intention back.

2022-08-05 20:07 UTC, deepbluev7 commented
Nheko now uses this in the join room dialog: https://github.com/Nheko-Reborn/nheko/commit/9d8d6b4bcaec0994776bf91a556a7e27cb862c30

![grafik](https://user-images.githubusercontent.com/16312324/183154255-a201ce00-d019-4423-9e72-fad0de882ddc.png)

2022-08-09 20:28 UTC, turt2live requested changes
overall I'm more convinced on this MSC now, particularly for the need of seeing if a room is joinable or knockable in a client, though still have a few concerns before this can go into FCP (imo).

I don't think they're unsurmountable, but some are not as easy as others (potentially).

2022-08-09 20:28 UTC, turt2live commented on proposals/3266-room-summary.md
> +  `m.space.child` event for example.
The vias feel insufficiently specified, despite I think everyone "knowing" what you mean:

* Are they required? (no)
* Are they the same as https://spec.matrix.org/v1.3/appendices/#routing ? (yes - please add the link)
* Where is "locally"? (the server, but could be argued to be on the client side with the current language)
* How does the client pick servers for an arbitrary room? (it is most often told what they are, but in the case of the room directory or bare room ID it might have to guess/hope for the best, just like with regular joins)

2022-08-09 20:28 UTC, turt2live commented on proposals/3266-room-summary.md
> +`encryption`.
Instead of taking this approach, why not just do what `/hierarchy` did and use a `PublicRoomsChunk` explicitly, extending the schema of that? (the benefit being that all 3 related endpoints get a `room_type`, `membership`, `room_version`, and `encryption` instead of having to subschema the nightmare a second time)

Maintaining several similar objects is not ideal from a spec perspective.

2022-08-09 20:28 UTC, turt2live commented on proposals/3266-room-summary.md
> +`membership` is not, but a client could access that in various different ways
How is the client meant to use the `membership` field? Even with the table below, the client should already have several other ways of knowing its current membership - is this really the best endpoint to reveal such information?

2022-08-09 20:28 UTC, turt2live commented on proposals/3266-room-summary.md
> +user is unauthenticated.
To be clear: does this mean the endpoint can be rate limited regardless of authentication? It might be safer to just list it like the spec does:

> **Rate limited**: Yes
> **Requires authentication**: No, because ...

though I'm also not entirely convinced this should be allowed to be unauthenticated - the MSC needs to describe the usecase so it can be rationalized.

2022-08-09 20:28 UTC, turt2live commented on proposals/3266-room-summary.md
> +`/hierarchy` API.
please just use `PublicRoomsChunk` 😭

2022-08-09 20:28 UTC, turt2live commented on proposals/3266-room-summary.md
> +room as well as the alias directly.
I think this is all made invalid by the summary endpoint having to reduce itself down to a room ID before going out over federation? How is it any more routable if the server does the resolution instead of the client?

2022-08-09 20:28 UTC, turt2live commented on proposals/3266-room-summary.md
> +field.
this hardly seems like an unsurmountable problem... The argument for it dealing mostly with spaces is quite strong, but saying it's missing fields is just asking for an MSC to add the fields :p

The key with the alternatives section is it needs to describe *why* a solution isn't valid, so, why is writing an MSC for adding the fields a bad idea? (answer: it's because of the focus on spaces - it would be confusing to client developers to call a Spaces endpoint to get a non-Space summary, though there is an unargued point about shifting the complexity onto the server instead, as this MSC does).

2022-08-09 20:28 UTC, turt2live commented on proposals/3266-room-summary.md
> +return wrong results for a summary.
This is true with any endpoint - the leak for this endpoint would more be that people could be surprised by the amount of metadata returned, such as in the case of https://github.com/matrix-org/matrix-spec/issues/1186

2022-08-09 20:28 UTC, turt2live commented on proposals/3266-room-summary.md
> +## Proposal
We appear to be missing error conditions from the MSC: what if the room doesn't exist? is invalid? unroutable?

2022-08-13 19:40 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +room as well as the alias directly.
If the client resolves the alias, only the client knows the server that resolved the alias.

If the server resolves the alias, it receives a list of servers that it can join via, which it can then use to query for the summary. This is the same behavior as with every other endpoint that takes an alias (apart from the room directory endpoints themselves, I guess). Usually asking the server about the room the alias is hosted on is entirely sufficient though. Apart from the directory, there is no endpoint which passes an alias over federation, so I don't see how that would be an issue in this case now?

2022-08-13 19:43 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +field.
This MSC actually adds most of those fields to the /hierarchy endpoint as well. But the EXISTING endpoint is not an alternative to this MSC, since it lacks those fields. Of course those could be added, but it is not the only reason why it currently can't be used for this. This sentence is just an additional complication that people would notice, when they try to use the /hierarchy endpoint as is without extending it.

2022-10-24 09:40 UTC, t3chguy commented
An interesting future consumer of this work could be shields.io - https://github.com/badges/shields/blob/master/services/matrix/matrix.service.js currently registers a bunch of guests and uses the `/state/` API so a dedicated API which doesn't require auth would be ideal.

2022-12-13 16:01 UTC, richvdh commented on proposals/3266-room-summary.md
> +federation API is reused. This provides (with a few changes) all the information
> For the `/hierarchy` federation API is reused.

I don't think I understand this sentence.

2022-12-13 16:03 UTC, richvdh commented
Still lots of outstanding questions from previous reviews here. @deepbluev7 are you still interested in pursuing this?

2022-12-14 01:37 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +federation API is reused. This provides (with a few changes) all the information
```suggestion
For the server side the federation API of the 
[`/hierarchy`](https://spec.matrix.org/v1.3/server-server-api/#get_matrixfederationv1hierarchyroomid)
endpoint is reused. This provides (with a few changes) all the information
```

2022-12-14 01:39 UTC, deepbluev7 commented
Yeah, I am still pursuing this, but I need to update it to work with the new room join rule, since there knocking and restricted joins are not distinguishable, so the allowed roomids need to be exposed, possibly prefiltered. But since my clients now need the unstable endpoint anyway in a few released versions, I am not as much in a hurry anymore.

2022-12-14 01:47 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +  `m.space.child` event for example.
The spec text for this same parameter (but with a different name) on the /join/ endpoint is this:

> The servers to attempt to join the room through. One of the servers must be participating in the room.

Why does an MSC need to be more specific then the spec? It is needed when otherwise the room can't be routed to. If that is the case, depends on what room you are previewing. If you know you are joined already, you don't need it. If you pass an alias, you don't need it. If you got a random room and you know some vias, there is no harm in just passing them. Some examples where those vias can be from is already listed in the line you are commenting on, but if a client provides more ways to preview a room it might have client side fields for that, like a text field a user can enter servers in, and I don't think that needs to be specified?

2022-12-14 01:54 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +`encryption`.
Well, this implicitly specifies to reuse the "PublicRoomsChunk", but most people probably would not know what that means. I think it is clearer to name the endpoint, that already returns this value than using the name of the value, that most people probably don't remember what it is. At least I mostly ignore those names unless I work with the OpenAPI JSON directly.

I also copied this wording originally from the space summary MSCs. It only uses the PublicRoomsChunk name in one example, it generally talks about the return value of `publicRooms` otherwise.

2022-12-14 01:58 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +`membership` is not, but a client could access that in various different ways
Some clients don't call /sync. Having to use an extra endpoint to fetch this endpoint is opposite to the goals of this endpoint. In general the reason to call a summary endpoint is to do less calls than generating all that info yourself.

For example, if you want to join a room, you might want to generate a preview first. Then you want to name the button differently depending on if you are joined to the room or not. If you have all joined rooms cached locally, you can fetch that info from there, but some clients do not have that info without doing another request. And the server needs to check the join state anyway to generate some of the results, so it should not have an additional cost to just put that in the summary.

2022-12-14 01:59 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +user is unauthenticated.
there is already an implementation of this, that can't use authentication, is that not enough? It is also the second example in the introduction...

> matrix.to may want to show avatar and name of a room.

2022-12-14 02:01 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +`/hierarchy` API.
You mean `ChildRoomsChunk`. And again, I think those names are confusing.

2022-12-14 02:02 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +return wrong results for a summary.
So should I just delete that line? I do think it is a genuine concern.

2022-12-14 18:34 UTC, turt2live commented
I'm going to take this off the SCT's priority list in that case. There is a bit of a problem if clients are relying on the unstable endpoint existing (as we're seeing happen outside of just your clients) - ideally, the MSC moves forward at a more hurried pace to avoid problems related to defacto spec. 

For reference, how we'd likely avoid defacto spec being an issue here is recommend the feature for removal from Synapse, forcing clients to treat the functionality as unstable.

2022-12-14 18:50 UTC, deepbluev7 commented
Well, the spec team told me to prioritize #3664, so that's what I did. Now that is stuck again. Before that, this MSC was stuck because there weren't enough implementations and half of the comments are nitpicking about wording or names, instead of actually being helpful to the content of the MSC, so it simply takes a bit of time to work on things. I changed some sentences 3 or more times. It simply takes a bit of time to please everyone with the wording, since if you react quickly, you end up just changing it back again on the next comment.

I think the 2 open points, that are actually important for the functionality of the MSC are:
- error codes
- No information about if you can join a restricted_knock room

The rest, in my opinion, is arguing about how specific things are worded or if a specific sentence "is important".

2022-12-16 06:58 UTC, KitsuneRal commented on proposals/3266-room-summary.md
> +  `m.space.child` event for example.
AIUI, `appendices/#routing` effectively answers the questions regarding "locally" and the choice of servers?

2022-12-16 07:02 UTC, KitsuneRal commented on proposals/3266-room-summary.md
> +`encryption`.
Given that we tend to change sub-structure names in OpenAPI occasionally (that doesn't alter the shape of the OpenAPI, generated code notwithstanding), I agree with @deepbluev7 that the current text is good enough.

2022-12-16 08:04 UTC, KitsuneRal commented on proposals/3266-room-summary.md
> +`/hierarchy` API.
(FWIW - the name `ChildRoomsChunk` was introduced (by me) in a clarification PR (not MSC) solely for the purpose of describing, well, child rooms in `/hierarchy`. Refactoring those sub-schema names is certainly not something for this MSC (we rarely, if ever, did it in the previous MSC practice). `PublicRoomsChunk` is used in a couple of places across the API; I agree the name could be better but it actually reflects the current usage of this group of fields.)

I think it's a good question for SCT on the status of those names, how much we have to preserve them etc.; in the meantime, I would suggest keeping the text as it is to avoid accidental confusion.

2022-12-16 08:25 UTC, KitsuneRal commented on proposals/3266-room-summary.md
> +security implications with that may better be left to a separate MSC.
```suggestion
security implications with that may better be left to a separate MSC.)
```

2023-06-25 19:50 UTC, melroy89 commented
Also still not merged? We have a lot of users now complaining they can't see the rooms in the Matrix space. Most likely people are using Dendrite. Please consider making it out of beta this year...

2023-06-25 19:52 UTC, deepbluev7 commented
@melroy89 Previewing rooms in a space is already part of the spec. This is for rooms outside the space hierarchy.

2023-06-25 20:04 UTC, melroy89 commented
> @melroy89 Previewing rooms in a space is already part of the spec. This is for rooms outside the space hierarchy.

Ah I see, since that still needs to be enabled manually in Dendrite? 
https://github.com/matrix-org/dendrite/blob/main/docs/FAQ.md#does-dendrite-support-space-summaries

2023-06-25 20:06 UTC, deepbluev7 commented
That's because the devs didn't get around to stabilizing it and has little to do with the spec.

2024-05-30 21:35 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +| join_rule          | Optional. Join rules of the room                                                                                                                      | Copied from `publicRooms
With the introduction of `knock_restricted`, knowing the join rule isn't sufficient to know which method the room can be joined via. As such the response should also include the allowedRoomIds, that the user is joined to or so.

2024-05-30 21:36 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +be a member of a room mentioned in an `allow` condition in the join rules of a
It's not clear if this includes invites. It probably should, but that should be explicitly mentioned in the MSC.

2024-10-01 12:53 UTC, AndrewFerr commented on proposals/3266-room-summary.md
> +## Unstable prefix
This should also define a new `unstable_features` flag for `GET /_matrix/client/versions`.

For example, adapting from [MSC3026](https://github.com/matrix-org/matrix-spec-proposals/blob/babolivier/msc_presence_busy/proposals/3026-presence-busy.md#proposal):
> servers implementing this MSC must expose a flag in `GET /_matrix/client/versions` responses, under `unstable_features`, named `im.nheko.msc3266`, which is set to `true`.

Other MSCs that define an `unstable_features` are MSC2432, MSC2666, MSC2285, MSC3827, and MSC3440.

2024-11-28 19:03 UTC, turt2live commented on proposals/3266-room-summary.md
> +user is unauthenticated.
Which implementation can't use authentication? 2 years later, I'm less convinced of my 2022 opinion here, but curious if there's workarounds that could be explored.

2024-11-28 19:18 UTC, turt2live commented
The SCT is aiming to ensure MSCs actually pass [the checklist](https://github.com/matrix-org/matrix-spec-proposals/blob/main/MSC_CHECKLIST.md) before FCP is proposed. This comment is that checklist tracking.

- [ ] Are [appropriate implementation(s)](https://spec.matrix.org/proposals/#implementing-a-proposal) specified in the MSC’s PR description?
- [x] Are all MSCs that this MSC depends on already accepted?
- [ ] For each new endpoint that is introduced:
  - [x] Have authentication requirements been specified?
  - [x] Have rate-limiting requirements been specified?
  - [ ] Have guest access requirements been specified?
  - [ ] Are error responses specified?
    - [ ] Does each error case have a specified `errcode` (e.g. `M_FORBIDDEN`) and HTTP status code?
      - [ ] If a new `errcode` is introduced, is it clear that it is new?
- [x] Will the MSC require a new room version, and if so, has that been made clear?
  - [x] Is the reason for a new room version clearly stated? For example, modifying the set of redacted fields changes how event IDs are calculated, thus requiring a new room version.
- [x] Are backwards-compatibility concerns appropriately addressed?
- [ ] Are the [endpoint conventions](https://spec.matrix.org/latest/appendices/#conventions-for-matrix-apis) honoured?
  - [ ] Do HTTP endpoints `use_underscores_like_this`?
  - [x] Will the endpoint return unbounded data? If so, has pagination been considered?
  - [x] If the endpoint utilises pagination, is it consistent with [the appendices](https://spec.matrix.org/v1.8/appendices/#pagination)?
- [x] An introduction exists and clearly outlines the problem being solved. Ideally, the first paragraph should be understandable by a non-technical audience.
- [ ] All outstanding threads are resolved
  - [ ] All feedback is incorporated into the proposal text itself, either as a fix or noted as an alternative
- [ ] While the exact sections do not need to be present, the details implied by the proposal template are covered. Namely:
  - [x] Introduction
  - [x] Proposal text
  - [x] Potential issues
  - [x] Alternatives
  - [x] Dependencies
- [x] Stable identifiers are used throughout the proposal, except for the unstable prefix section
  - [x] Unstable prefixes [consider](README.md#unstable-prefixes) the awkward accepted-but-not-merged state
  - [x] Chosen unstable prefixes do not pollute any global namespace (use “org.matrix.mscXXXX”, not “org.matrix”).
- [x] Changes have applicable [Sign Off](CONTRIBUTING.md#sign-off) from all authors/editors/contributors
- [x] There is a dedicated "Security Considerations" section which detail any possible attacks/vulnerabilities this proposal may introduce, even if this is "None.". See [RFC3552](https://datatracker.ietf.org/doc/html/rfc3552) for things to think about, but in particular pay attention to the [OWASP Top Ten](https://owasp.org/www-project-top-ten/).

2024-11-28 19:47 UTC, tulir commented on proposals/3266-room-summary.md
> +user is unauthenticated.
matrix.to can't use authentication. On the other hand, we already broke room avatars in matrix.to, so maybe workarounds have to be explored anyway.

2024-11-29 02:55 UTC, turt2live commented on proposals/3266-room-summary.md
> +user is unauthenticated.
yea, I'd suggest trying guest access and if that fails, well, sorry - add context around the link rather than rely on the link :)

2024-11-29 11:14 UTC, richvdh commented on proposals/3266-room-summary.md
> +user is unauthenticated.
I'm concerned that if we block this MSC behind requiring changes to `matrix.to`  then it's going to get stuck for another 3.5 years while someone finds some tuits to do that work.

Prove me wrong ;)

2024-12-10 14:44 UTC, t3chguy commented on proposals/3266-room-summary.md
> +user is unauthenticated.
Also guest access is unavailable on servers with "Next Gen Auth" https://github.com/matrix-org/matrix-spec-proposals/pull/3861 which is rolling out to major homeservers near you soon. (e.g. matrix.org)

2025-01-07 20:21 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +## Unstable prefix
I don't think this needs an unstable prefix. It either can be called and returns a value or it does not work.

2025-01-07 20:22 UTC, deepbluev7 commented
Okay, I updated the MSC with most of the experiences I had with it from the last 2 years. Also shields.io now uses it, so does that remove your concerns regarding the unauthenticated usage, @turt2live? It apparently is a lot better than their previous approach of registering a new guest user per request.

2025-01-07 20:27 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +user is unauthenticated.
Shields.io also switched to this API because their guest users caused performance issues on matrix.org and this API seems to not suffer from this problem, so I think the unauthenticated mode should stay.

2025-01-07 20:44 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +user is unauthenticated.
Resolving this as the consensus seems to be that restricting this to guest users provides no benefit and optional authentication, as described by the MSC, provides a convenient functionality for the current users of this MSC. Authentication does allow querying the room membership as well as preview some additional rooms, but would just add additional guest users for no benefit for public rooms.

2025-01-07 20:45 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +## Proposal
I added some of them. I didn't bother enumerating all of them, as they mostly are the same as for room joins and the spec doesn't bother to spell out the error codes for unroutable rooms and I would prefer there to be one error code for that.

2025-01-07 20:46 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +`/hierarchy` API.
I'm not switching to openapi names, as it seems to provide little benefit and most people aren't familiar with them. Instead I refer to the APIs, that return them.

2025-01-07 20:47 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +room as well as the alias directly.
I think this is already sufficiently explained by the MSC.

2025-01-08 08:56 UTC, t3chguy commented on proposals/3266-room-summary.md
> +user is unauthenticated.
> Shields.io also switched to this API because their guest users caused performance issues on matrix.org and this API seems to not suffer from this problem, so I think the unauthenticated mode should stay.

And matrix.org is about to turn guests off https://matrix.org/blog/2025/01/06/authentication-changes/

2025-01-09 05:58 UTC, turt2live approved these changes
I haven't perfectly verified the implementation matches, especially on the server side, but this has been sitting for far too long anyways. Let's ship it.

2025-01-09 05:58 UTC, turt2live commented
@mscbot fcp merge

2025-01-09 23:50 UTC, richvdh commented on proposals/3266-room-summary.md
> +Quite a few clients and tools have a need preview a room:
Nit:

```suggestion
Quite a few clients and tools have a need to preview a room:
```

2025-01-09 23:50 UTC, richvdh commented on proposals/3266-room-summary.md
> +(This is not under `/rooms`, because it can be used with an alias.
Nit:

```suggestion
(This is not under `/rooms`, because it can be used with an alias.)
```

2025-01-09 23:50 UTC, richvdh commented on proposals/3266-room-summary.md
> +returned if the room is publicly accessible.
What exactly does publicly accessible mean here? `join_rule: public`, presumably?

(obligatory mention of https://github.com/matrix-org/matrix-spec/issues/633)

2025-01-09 23:50 UTC, richvdh commented on proposals/3266-room-summary.md
> +Invites and rooms the user has knocked at might return outdated or partial
nit:

```suggestion
Rooms that the user has been invited to or knocked at might result in outdated or partial
```

2025-01-09 23:51 UTC, richvdh commented on proposals/3266-room-summary.md
> +| allowed_room_ids   | Room ids allows in restricted joins.                                                                                                                  | Copied from `hierarchy`.
all the other rows have an explicit "Required" or "Optional". Which is this?

2025-01-10 00:01 UTC, richvdh commented on proposals/3266-room-summary.md
> +| allowed_room_ids   | Room ids allows in restricted joins.                                                                                                                  | Copied from `hierarchy`.
Does synapse actually implement this for `im.nheko.summary` right now? The PR linked in the MSC description (https://github.com/matrix-org/synapse/pull/10394) doesn't include it. If it does, could you link to the implementation?

2025-01-10 12:15 UTC, clokep commented on proposals/3266-room-summary.md
> +`encryption` and `allowed_room_ids`.
```suggestion
These are the same fields as those returned by [`/publicRooms`](https://spec.matrix.org/v1.13/client-server-api/#get_matrixclientv3publicrooms) or
[`/hierarchy`](https://spec.matrix.org/v1.3/client-server-api/#get_matrixclientv1roomsroomidhierarchy)
, with a few additions: `membership`, `room_version`,
`encryption` and `allowed_room_ids`.
```

`/publicRooms` and `/hierarchy` return the `room_type` as of v1.4 and v1.2, respectively.

2025-01-10 12:15 UTC, clokep commented on proposals/3266-room-summary.md
> +the stripped state according to
```suggestion
`room_version` and `encryption` are already accessible as part of
the stripped state according to
```

2025-01-10 12:18 UTC, clokep commented on proposals/3266-room-summary.md
> +returned. If the room can't be found, `M_NOT_FOUND` should be returned. A
Below you say not to return `M_UNAUTHORIZED`, when is `M_FORBIDDEN` meant to be returned then? Wouldn't that divulge the room existing?

2025-01-10 12:20 UTC, clokep commented on proposals/3266-room-summary.md
> +#### Modifications to `/_matrix/client/v1/rooms/{roomId}/hierarchy`
Should this also be made to `/publicRooms`?

2025-01-10 12:21 UTC, clokep commented on proposals/3266-room-summary.md
> +For the server side the federation API of the
```suggestion
For fetching room summaries of a room a server is not joined to, the federation API of the 
```

2025-01-10 12:24 UTC, clokep commented on proposals/3266-room-summary.md
> +apply rate limiting if necessary.
Is it recommended that clients cache it for a period at least?

2025-01-10 12:26 UTC, clokep commented on proposals/3266-room-summary.md
> +to work for unjoined rooms and it excludes `m.heroes` as well as membership
This MSC doesn't use [stripped sate](https://spec.matrix.org/v1.13/client-server-api/#stripped-state) -- it uses a bunch of information derived from the room state.

2025-01-10 20:26 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +- A client may want to show the room in the roomlist, when showing a space.
That is explained in the paragraph after this list. Some of these things can be achieved using the `/hierarchy` API. But this specific case for example works well if you want to show the whole space. It doesn't work if you want to show a single room in a space. The hierarchy API requires you to load possibly the whole hierarchy to show a specific room in the space. This falls under "heavier than necessary".

2025-01-10 20:50 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +returned if the room is publicly accessible.
It means if the content can be accessed by anyone. This can be either `join_rule` of `public`, history visibility of `world_readable` and also rooms you can knock on: https://github.com/matrix-org/matrix-spec/issues/1184

This might change in the future, but as you can currently preview such rooms via the `/hierarchy` API, this MSC doesn't change it. Whatever the conclusion ends up being for the hierarchy API long term should also apply to this MSC.

An argument could be made, that world_readable should be required for unauthenticated users, but that doesn't match what is currently implemented. Another alternative could be to have a separate setting for if the room info is publicly readable instead of only having a toggle for messages and the room info. But in general this room info is already readable without joining the room, so it isn't clear why authentication would be required.

The wording of this MSC was changed multiple times already during the discussion on the issue I linked and in the end I reverted it to "publicly accessible" as I really don't want to split the discussion. I would prefer it someone wrote an MSC to clarify https://github.com/matrix-org/matrix-spec/issues/1184, https://github.com/matrix-org/matrix-spec/issues/633, etc, instead of me having to do that on the side on this MSC. I was also told to have the MSC match the current implementation and not do additional changes to it.

2025-01-10 21:03 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +#### Modifications to `/_matrix/client/v1/rooms/{roomId}/hierarchy`
Probably, but I don't want to do additional changes to this MSC to include that. It is necessary to add this to the hierarchy API on the federation side already, so it makes sense to carry it through to the client side as well (it simplifies the implementation). But `/publicRooms` is actually quite separate and when I wrote this MSC also was lacking the `room_type` field (see https://github.com/matrix-org/matrix-spec-proposals/pull/3827, I think?). So I am not sure if that should be part of this MSC.

I also didn't have a need to query the room version or the encryption algorithm of public rooms very often yet. And if I ever have the need for that, I probably want to be able to filter for it similar to MSC3827 as well. So maybe best left for a different MSC?

2025-01-10 21:06 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +apply rate limiting if necessary.
Does this need to be spelled out explicitly? Yes, clients should usually cache this, but it isn't always obvious for how long a client should cache the summary and some users of this API might also be mostly stateless. I think it is obvious that clients shouldn't fetch data more often than they need to, but should I spell that out specifically or was this a question?

2025-01-10 21:18 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +to work for unjoined rooms and it excludes `m.heroes` as well as membership
That sounds like a technicality to me? This MSC uses information, that is available event for rooms where only the events in the stripped state you linked to is available. Yes, this information is also available in the room state. But the stripped state of a room is also derived from the room state. The big difference between normal room state and the stripped state is:

- only the sender, type, state_key and content properties of an event
- it isn't verified via the normal event signatures
- it usually only includes a few specific events: create, name, avatar, topic, join_rules, canonical_alias and encryption

This MSC specifically derives from this sentence of the spec:

> Stripped state typically appears in invites, knocks, and in other places where a user could join the room under the conditions available (such as a [restricted room](https://spec.matrix.org/v1.13/client-server-api/#restricted-rooms)).

The sentence you commented on points out that relationship: These previews also work for unjoined rooms, where the full room state might be unavailable.

So could you clarify what your comment is supposed to mean? Am I supposed to change something in the text? Is it a question? Or is it just about the technicality, that this MSC doesn't directly return stripped state events, even though it uses the definition of stripped state events to define what information is available and what rooms should be previewable, without anything for me to act on? I'm a bit at a loss here, how I am supposed to resolve or reply to comments like these.

2025-01-10 21:26 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +returned. If the room can't be found, `M_NOT_FOUND` should be returned. A
Ah, good point. I confused myself there when checking if the error code comment is resolved...

2025-01-10 21:26 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +| allowed_room_ids   | Room ids allows in restricted joins.                                                                                                                  | Copied from `hierarchy`.
Forgot that when merging, fixed!

2025-01-10 23:02 UTC, richvdh commented on proposals/3266-room-summary.md
> +returned if the room is publicly accessible.
To be explicit, I am concerned about this sentence:

> For unauthenticated requests a response should only be returned if the room is publicly accessible.

I'm not sure it's true that this wording has changed multiple times, and I don't see anywhere it has been discussed. But anyway, it seems like you have a clear idea of what is meant; I'm just asking that we make it explicit.

```suggestion
returned if the room is publicly accessible; specifically, that means either:
 * the room has `join_rule: public` or `join_rule: knock`, or
 * the room has `history_visibility: world_readable`.
```

It probably also needs more paragraph breaks, for the bullet list to make sense.

2025-01-11 00:28 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +| allowed_room_ids   | Room ids allows in restricted joins.                                                                                                                  | Copied from `hierarchy`.
Here is an implementation for the missing parts:

```diff
diff --git a/synapse/handlers/room_summary.py b/synapse/handlers/room_summary.py
index 720459f1e7..5bec1235e6 100644
--- a/synapse/handlers/room_summary.py
+++ b/synapse/handlers/room_summary.py
@@ -308,7 +308,7 @@ class RoomSummaryHandler:
             # inaccessible to the requesting user.
             if room_entry:
                 # Add the room (including the stripped m.space.child events).
-                rooms_result.append(room_entry.as_json(for_client=True))
+                rooms_result.append(room_entry.as_json())

                 # If this room is not at the max-depth, check if there are any
                 # children to process.
@@ -445,7 +445,7 @@ class RoomSummaryHandler:
         if not await self._is_local_room_accessible(room_id, requester, origin):
             return None

-        room_entry = await self._build_room_entry(room_id, for_federation=bool(origin))
+        room_entry = await self._build_room_entry(room_id)

         # If the room is not a space return just the room information.
         if room_entry.get("room_type") != RoomTypes.SPACE or not include_children:
@@ -701,14 +701,12 @@ class RoomSummaryHandler:
         # pending invite, etc.
         return await self._is_local_room_accessible(room_id, requester)

-    async def _build_room_entry(self, room_id: str, for_federation: bool) -> JsonDict:
+    async def _build_room_entry(self, room_id: str) -> JsonDict:
         """
         Generate en entry summarising a single room.

         Args:
             room_id: The room ID to summarize.
-            for_federation: True if this is a summary requested over federation
-                (which includes additional fields).

         Returns:
             The JSON dictionary for the room.
@@ -739,9 +737,6 @@ class RoomSummaryHandler:
             entry["im.nheko.summary.version"] = stats.version
             entry["im.nheko.summary.encryption"] = stats.encryption

-        # Federation requests need to provide additional information so the
-        # requested server is able to filter the response appropriately.
-        if for_federation:
             current_state_ids = (
                 await self._storage_controllers.state.get_current_state_ids(room_id)
             )
@@ -866,7 +861,6 @@ class RoomSummaryHandler:
                 raise NotFoundError("Room not found or is not accessible")

             room = dict(room_entry.room)
-            room.pop("allowed_room_ids", None)

             # If there was a requester, add their membership.
             # We keep the membership in the local membership table unless the
@@ -909,25 +903,16 @@ class _RoomEntry:
     # This may not include all children.
     children_state_events: Sequence[JsonDict] = ()

-    def as_json(self, for_client: bool = False) -> JsonDict:
+    def as_json(self) -> JsonDict:
         """
         Returns a JSON dictionary suitable for the room hierarchy endpoint.

         It returns the room summary including the stripped m.space.child events
         as a sub-key.

-        Args:
-            for_client: If true, any server-server only fields are stripped from
-                the result.
-
         """
         result = dict(self.room)

-        # Before returning to the client, remove the allowed_room_ids key, if it
-        # exists.
-        if for_client:
-            result.pop("allowed_room_ids", False)
-
         result["children_state"] = self.children_state_events
         return result
```

You can also find it here: https://github.com/deepbluev7/synapse/commit/37f4253bda4942adc6356e9ed73dc40582764c9b

The feature flags aren't quite correct, but I would say that doesn't matter, as it does the right thing when enabled :)

2025-01-13 16:42 UTC, clokep commented on proposals/3266-room-summary.md
> +- A client may want to show the room in the roomlist, when showing a space.
But if you're showing the space don't you already have the info to show the room in the room list? I just be misunderstanding something.

2025-01-13 16:43 UTC, clokep commented on proposals/3266-room-summary.md
> +apply rate limiting if necessary.
I guess I found it odd that it specifically recommends servers should cache it.

2025-01-13 16:46 UTC, clokep commented on proposals/3266-room-summary.md
> +to work for unjoined rooms and it excludes `m.heroes` as well as membership
I found this sentence to imply that the stripped state was returned, which it is not. (Maybe it is a technicality, but this is a technical document -- details are important.) perhaps saying the information is derived from the stripped state would be enough. (I'm not even really sure the stripped aspect of it is needed here?)

2025-01-15 00:28 UTC, ara4n commented
I've given this a green tick in order not to block its progress, given the MSC as a whole is definitely useful and very proven at this point.  @deepbluev7 can you please deal with the remaining open PR comments though (e.g. spelling out what 'public' means; etc)?

2025-01-17 18:19 UTC, clokep commented on proposals/3266-room-summary.md
> +to work for unjoined rooms and it excludes `m.heroes` as well as membership
```suggestion
the client is using lazy loading.  This MSC provides similar information as
calling `/sync`, but to allow it to work for unjoined rooms it only uses information
 from the stripped state. Additionally, it excludes `m.heroes` as well as membership
```

Maybe that's clearer?

2025-01-20 17:56 UTC, cyb3rko commented
Mautrix has also implemented it now: https://github.com/mautrix/go/releases/tag/v0.23.0

2025-02-06 20:15 UTC, MadLittleMods commented on proposals/3266-room-summary.md
> +NOT return `M_UNAUTHORIZED` or otherwise divulge existance of a room, that
```suggestion
NOT return `M_UNAUTHORIZED` or otherwise divulge existence of a room, that
```

2025-02-06 20:15 UTC, MadLittleMods commented on proposals/3266-room-summary.md
> +If the room can't be found, `M_NOT_FOUND` should be returned. The server should
We should be explicit about the HTTP status codes

```suggestion
If the room cannot be found, the server should return a `404`
HTTP status code along with an `M_NOT_FOUND` error code. The server should
```

2025-02-06 20:15 UTC, MadLittleMods commented on proposals/3266-room-summary.md
> +A response includes the stripped state in the following format:
```suggestion
A successful `200` response includes the stripped state in the following format:
```

2025-02-06 20:24 UTC, MadLittleMods commented on proposals/3266-room-summary.md
> +(1) The field `membership` will not be present when called unauthenticated, but
```suggestion
(1) The `membership` field will not be present when called unauthenticated, but
```

2025-02-11 16:36 UTC, richvdh commented on proposals/3266-room-summary.md
> +| allowed_room_ids   | Room ids allows in restricted joins.                                                                                                                  | Copied from `hierarchy`.
Ok I take your point :)

2025-02-11 16:42 UTC, richvdh commented on proposals/3266-room-summary.md
> +to work for unjoined rooms and it excludes `m.heroes` as well as membership
That said: whilst some clarification would be appreciated here, it doesn't block FCP as far as I'm concerned.

2025-02-18 14:31 UTC, richvdh commented
This has got stuck waiting for updates once more, so in the interests of pushing it over the line, the Spec Core Team are going to make the final few updates.

2025-02-18 14:41 UTC, richvdh commented on proposals/3266-room-summary.md
> +- A client may want to show the room in the roomlist, when showing a space.
Let's just remove this reason, since we don't understand it.

```suggestion
```

2025-02-18 14:43 UTC, richvdh commented on proposals/3266-room-summary.md
> +returned if the room is publicly accessible.
Clarified in 491b77ef

2025-02-18 21:57 UTC, richvdh approved these changes

2025-02-25 07:24 UTC, Johennes commented on proposals/3266-room-summary.md
> +  topic: "Tasty tasty cheese",
Given that this is an entirely new API, could it make sense to use the rich topic format from https://github.com/matrix-org/matrix-spec-proposals/pull/3765 here?

2025-02-25 07:31 UTC, Johennes commented on proposals/3266-room-summary.md
> +calls. Restricting this API to guests only would provide no security benefit.
Should server admins be allowed to disable returning results on this API similar to how profile look-ups can be disabled?

2025-02-25 08:01 UTC, KitsuneRal commented on proposals/3266-room-summary.md
> +calls. Restricting this API to guests only would provide no security benefit.
This would be an implementation detail for servers, no? Nothing would change in the API whether a server has such an internal control or not.

2025-02-25 08:05 UTC, KitsuneRal commented on proposals/3266-room-summary.md
> +  topic: "Tasty tasty cheese",
I'm not sure about the value of having rich text in the room summary. The way this API is utilised implies brief representation. As a client author, I would prefer the topic reduced to plain text. Maybe it's just me though.

2025-02-25 08:20 UTC, Johennes commented on proposals/3266-room-summary.md
> +calls. Restricting this API to guests only would provide no security benefit.
It wouldn't change the API (beyond error codes maybe). But we do explicitly call out other cases where admins can deny look-up such as: https://spec.matrix.org/unstable/client-server-api/#server-behaviour

2025-02-25 08:23 UTC, Johennes commented on proposals/3266-room-summary.md
> +  topic: "Tasty tasty cheese",
https://github.com/matrix-org/matrix-spec-proposals/pull/3765 argued along the same lines though that was partially motivated by not wanting to touch the existing endpoints. 🙈

I think it's probably fine to keep this as plain text. Just wanted to raise it because changing it now would still be easy due to this being a new API.

2025-02-25 14:39 UTC, erikjohnston commented on proposals/3266-room-summary.md
> +calls. Restricting this API to guests only would provide no security benefit.
I think we should call it out, and indeed I am very hesitant to recommend unauthenticated access by default. We probably *do* want to allow this to be unauthenticated for e.g. matrix.org as a service to the community, but in general I don't think homeservers should not be supporting third-party services out-of-the-box. Allowing unauthenticated access opens up the server to abuse, which not all server admins can or want to deal with.

I think there are two benefits from having this unauthenticated:
1. Third-party services that want to piggy-back of a well known public home server
2. A client wants to show a preview of a room before the user logs in.

Either way, these depend on using a pre-configured default server, which can then be specifically configured to allow unauthenticated access.

2025-02-25 14:39 UTC, erikjohnston commented on proposals/3266-room-summary.md
> +would know about the room already.
If the server doesn't know about the room, don't we return 04 as per the previous paragraph?

2025-02-25 14:50 UTC, t3chguy commented on proposals/3266-room-summary.md
> +calls. Restricting this API to guests only would provide no security benefit.
3. a sane invite experience not exclusive to publicly federating homeservers via a landing page like matrix.to - otherwise the experience will be very normie unfriendly with just a room ID visible.

2025-02-25 15:13 UTC, dbkr commented on proposals/3266-room-summary.md
> +`encryption` and `allowed_room_ids`.
`allowed_room_ids` isn't mentioned in the format.

2025-02-25 15:16 UTC, dbkr commented on proposals/3266-room-summary.md
> +alias, and a corresponding server-server API to fetch a summary over federation.
This bit just needs updating to reflect the fact the SS API was removed.

2025-02-25 15:25 UTC, dbkr commented on proposals/3266-room-summary.md
> +to the current state of the room.
Why? Wouldn't the server just go & get the latest data the same as it would if they weren't invited?

2025-02-25 15:32 UTC, dbkr commented on proposals/3266-room-summary.md
> +server (that looks like this proposal).
This feels like the conclusion is that we should do this instead? Why wouldn't we?

2025-02-25 16:12 UTC, richvdh commented
@mscbot concern should unauthenticated access be enabled by default?

2025-02-25 17:17 UTC, richvdh commented on proposals/3266-room-summary.md
> +  topic: "Tasty tasty cheese",
I think basically, we need to keep `/room_summary` in sync with `GET /_matrix/federation/v1/hierarchy/{roomId}`, so that the information available for remote rooms matches that for local rooms.

Given we haven't yet changed the spec for  `GET /_matrix/federation/v1/hierarchy/{roomId}` to use rich topics (beyond preferring the plain-text representation of `m.topic` over `topic`), I don't think we should do so for `/room_summary` either. In future, we can update both together.

That said, this MSC probably *does* need clarifying that it should prefer `m.topic` over `topic`.

2025-02-25 17:17 UTC, richvdh commented on proposals/3266-room-summary.md
> +calls. Restricting this API to guests only would provide no security benefit.
In a conversation among the SCT, concern was raised about allowing unauthenticated access by default. Specifically, as the manager of a homeserver which I believe is single-user, I don't want randoms from the internet using my homeserver to access previews. Even with rate-limiting in place, the resource usage can be non-trivial.

There is also a potential information leak here: if there is an unfederated, knockable room on my server, and I do not share access to my room directory, I do not expect the name/topic of that room to suddenly be available to the whole internet.

Instead, it is proposed to recommend that homeservers make the endpoint require authentication by default. Homeservers would remain free to allow anonymous access if they wish, and anonymous access would remain enabled on `matrix.org`.

As far as `matrix.to` is concerned: there are a few potential ways forward:
 * Do nothing, and just fail gracefully, as today. The current experience, when using a server that doesn't support the endpoint, isn't *that* bad. By way of example, try opening `https://matrix.to/#/#foo:sw1v.org` in a private browsing window.
 * It could default to using `matrix.org` instead of the server name in the room alias/id. This might require some sort of gdpr style warning like "you're about to use `matrix.org`, continue?".
 * It could maintain a list of alternative list of "default" servers and pick one (randomly? at the user's choice?)
 * It could use guest accounts (maybe? unlikely, given matrix.org is turning off guest accounts)
 * There could be a separate `matrix.to` homeserver which does nothing except proxy requests to `GET /_matrix/federation/v1/hierarchy/{roomId}`.

2025-02-25 17:21 UTC, t3chguy commented on proposals/3266-room-summary.md
> +calls. Restricting this API to guests only would provide no security benefit.
> isn't that bad. By way of example, try opening https://matrix.to/#/#foo:sw1v.org in a private browsing window.

Hard disagree for message permalinks

![image](https://github.com/user-attachments/assets/a70437f2-55c6-4dba-9f29-f33844aaceb9)

> There could be a separate matrix.to homeserver which does nothing except proxy requests to GET /_matrix/federation/v1/hierarchy/{roomId}.

Sounds like a central point of data collection which goes against the point of matrix.to

2025-02-25 17:25 UTC, erikjohnston commented on proposals/3266-room-summary.md
> +calls. Restricting this API to guests only would provide no security benefit.
For transparency, here are some of the reasons that I think we should be careful about adding APIs that are unauthenticated by default. Note that all of these are solvable issues (and there is some disagreement about how much each actually matters), but I think the larger point stands that we should only consider adding unauthenticated APIs if there is a need to do so.

1. Information leaking: fundamentally you're giving information out to potential attackers. You can absolutely argue that some bits of information can and should be public, but generally the default assumption of private server operators (whether that is one person servers, or company servers) will be that only their users will be able to access any information. As we've seen, its easy for us to say "this info is public" but still get people angry at us when they discover its actually public (as per "[Avoiding unwelcome visitors on private Matrix servers](https://matrix.org/blog/2019/11/09/avoiding-unwelcome-visitors-on-private-matrix-servers/)") blog post. These information leaks can also be subtle, e.g. by revealing whether a server is in a room or not depending on the response. Matrix in general heavily leans into the idea that you own and store your own data and that is great for privacy, making information leaks Not Great.
2. It makes it easy to rack up costs. Yes, a bunch of these things can be cached or rate limited, but it is quite hard to make that fool proof and requires a bunch of extra work. If we e.g. add ratelimits, then we need to choose a value that isn't too small that we keep hitting them in normal operation (thus reducing the utility of the endpoint being open), nor too large that it can rack up costs.
3. This endpoint can trigger federation requests, which is a) not that cheap to do, and b) allows arbitrary people to hit arbitrary other servers (though not arbitrary URLs) to make it harder to fight DoS. They're not amplification attacks, so its not _that_ bad, but still.
4. Any API that allows upload of data (this applies more to MSC4108) needs to be handled _very_ carefully. Even with low timeouts and things they can be used to briefly store / handover illicit data. Even this API still lets you do that if you create a public room with illicit content on e.g. matrix.org. Then any server with unauthenticated summary endpoint enabled would return (and potentially cache) that data.
5. From a server admin PoV, in most deployments you mostly trust your own users so you don't need to worry too much about abuse. If you see abuse its easy enough to lock out a particular user and move on with your life. Admining a server that can be used by unauthenticated third-party services can be more tedious if you have to deal with IP-locking out things, or abuse requests from your server provider, etc. We to an extent see these problems already with the federation APIs.

All of those issues are solvable with enough care and thought, but there's no point doing so (and risking missing something!) if there isn't a good need for it. For example, in MSC3266 we have the issue that some users of Synapse don't federate but have public rooms, if we enabled /summary by default then information about those (potentially sensitive) rooms could leak to the public. I think this would be surprising (and potentially considered a security issue) for those users. Now, you could make Synapse only enable /summary if federation is enabled, though then you need to deal with private federations, etc. Its likely solvable, but to me the benefit of making matrix.to not have to go through matrix.org doesn't outweigh the risks and costs.

2025-02-25 17:31 UTC, richvdh commented on proposals/3266-room-summary.md
> +calls. Restricting this API to guests only would provide no security benefit.
> Hard disagree for message permalinks

I don't think the experience is any different for message permalinks than it is for room permalinks?

Sure, the preview is *nice*, but just having the room id isn't the end of the world. (It would be nice if matrix.to made it a bit clearer what that magic string was, but that could be fixed.)

2025-02-25 17:35 UTC, richvdh commented on proposals/3266-room-summary.md
> +would know about the room already.
Good question. It looks like the 404 paragraph was added in ed79007a0737668acf421cc2d1e3c8ab12177933 (and later clarified in 424189c82c5921e91ffbd28030517fc2e9c04514), but this `leave` requirement was forgotten.

Looking at the Synapse implementation, it looks like it indeed returns a 404 if the server doesn't know about the room. I propose to remove this bit about `leave`.

@deepbluev7: any objections?

2025-02-25 17:36 UTC, t3chguy commented on proposals/3266-room-summary.md
> +calls. Restricting this API to guests only would provide no security benefit.
room links using aliases such as the one in your example are at least somewhat self-documenting. Your room is about `foo`. Mine is about... gibberish?

2025-02-25 17:37 UTC, richvdh commented on proposals/3266-room-summary.md
> +`encryption` and `allowed_room_ids`.
sorry, which format?

2025-02-25 18:14 UTC, richvdh commented on proposals/3266-room-summary.md
> +calls. Restricting this API to guests only would provide no security benefit.
> Note that all of these are solvable issues (and there is some disagreement about how much each actually matters), but I think the larger point stands that we should only consider adding unauthenticated APIs if there is a need to do so.

The need to do so is demonstrated by @t3chguy's point about wanting to offer a good experience in matrix.to. We've established that there are alternatives, but none of them are great. So we're not just adding unauthenticated APIs for a laugh: we have a usecase. The question is, do the downsides outweigh the upsides? It's not as black and white as this sentence implies.

> 1. Information leaking: fundamentally you're giving information out to potential attackers. 

Yeah, this is compelling. As things currently stand: suppose I run a homeserver where I have disabled federation. On that homeserver I have a few rooms where any of my users can join (`join_rules: public`). I trust my users, but I don't want randoms on the internet to see my room names. This MSC makes that room metadata available to anyone on the internet, which I think would be a surprise to most admins in that situation.

For me, this is an absolute blocker to landing the MSC as it currently stands.

> 2. It makes it easy to rack up costs.

I think the actual cost is debatable, and caching/ratelimiting could be improved iteratively later. This is not a compelling argument for me.

> 3. This endpoint can trigger federation requests, 

This feels like a specific case of point 2.

> 4.  ... create a public room with illicit content on e.g. matrix.org. Then any server with unauthenticated summary endpoint enabled would return (and potentially cache) that data.

I don't think MSC4108 is particularly relevant to this discussion, but the second half of your point is important. This feels a lot like one of the problems we tried to fix in authenticated media: I don't want randoms in the internet pulling evil room topics onto my server.

> 5. From a server admin PoV, in most deployments you mostly trust your own users so you don't need to worry too much about abuse. If you see abuse its easy enough to lock out a particular user and move on with your life. Admining a server that can be used by unauthenticated third-party services can be more tedious if you have to deal with IP-locking out things, or abuse requests from your server provider, etc. We to an extent see these problems already with the federation APIs.

Given we already have these problems with federation APIs, maybe we don't need to worry about it too much? Or is your point that it will even affect admins who have disabled federation (and thus hope to be exempt from such abuse?)

2025-02-25 18:15 UTC, richvdh commented on proposals/3266-room-summary.md
> +calls. Restricting this API to guests only would provide no security benefit.
Speaking on behalf of the SCT: we don't have significant time to spend on this MSC, either in terms of changing the Synapse implementation, or in terms of changing `matrix.to`. Nevertheless, the current situation, of `matrix.org` supporting an unstable endpoint is, IMHO, untenable: we need to find a way forward, and in a way that does not block this MSC for another 3.5 years.

I can see for and against allowing unauthenticated access, but I think there are some real blockers to it, and right now, I am minded to proceed as suggested earlier.

> Instead, it is proposed to recommend that homeservers make the endpoint require authentication by default. Homeservers would remain free to allow anonymous access if they wish, and anonymous access would remain enabled on `matrix.org`.

I appreciate that this may not be the ideal outcome for some , especially `matrix.to`, but I think it's acceptable, and critically, it is *no worse, by any measure, than where we are today*.

2025-02-25 23:27 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +  topic: "Tasty tasty cheese",
I see no reason why this MSC should add support for rich text topics, when they are not supported by the hierarchy API and public rooms API. It would make more sense to me to add that to all of those APIs in a targeted MSC, if there is a use case for it. I don't really see one right now.

I also don't see why this MSC needs to clarify if it is using m.topic over topic now. That stuff didn't exist when this MSC was written and this MSC already clarifies where it is taking the fields from (the hierarchy API and related to the public rooms API). At some point we need to stop clarifying every little detail, it causes needless churn on the MSC and most of those things are already obvious enough. This MSC doesn't care about those changes and the rich text topic MSC explicitly mentions that servers should switch to m.topic. The MSC was merged yesterday and is not part of the spec yet. This MSC references the spec. If I now update it to reference some MSC, I will get to update it in a few months again to reference the spec and so on. At some point people will just have to consider some context.

2025-02-25 23:45 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +calls. Restricting this API to guests only would provide no security benefit.
I fundamentally disagree, that this endpoint should be available only with authentication by default. There are several users of the API already, that are using it unauthenticated (shields.io, matrix.to). So there clearly is a use case. Those users also all allow you to overwrite which server you want to use for the preview, because even if those services are centralized, Matrix is not. Having every preview go through matrix.org violates the design principles behind Matrix and matrix.to. matrix.to goes through a lot of effort to not leak the room addresses or other data to the server hosting matrix.to. As such people should generally have the choice to use their own servers for previews.

The load generated by this API is a LOT lower than what we had before with guest users for previews. This API was already mentioned as a replacement for those use cases, where people were using guest users before. Requiring authentication for this API now would violate that announcement (although yes, matrix.org could make an exception).

If servers want to disable unauthenticated access for this in a private federation, that is fine. But in an open federation we generally consider public rooms public. You aren't providing any additional security by requiring authentication for this API. All of that data is already available to anyone, who can set up a homeserver. While that is a minuscule amount of work and as such harder than calling an unauthenticated API directly, it won't prevent anyone from getting access to this data.

And the same issue exists in the other direction. Yes, unauthenticated access might cache unwelcome data for a certain amount of time. But to access that data someone would need to call the same API. And that data is deleted automatically, since it is just a cache, not persisted forever like media used to be for most people. Additionally that data can be pushed to a server also by simply sending an invite.

So my opinion is, that if servers want to disable unauthenticated access because they have special federation needs, that is absolutely fine. But they will have to do more work to actually prevent any of the abuse mentioned so far (like only allowing certain domains to federate like in the TI-Messenger federation). Otherwise requiring authentication doesn't technically provide any additional security, doesn't make less data available, but does make Matrix more centralized and this API less useful for use cases already relying on this API. If you want to provide more security, you need to lock down the federation API more and provide restrictions for invites and similar APIs. Requiring authentication for this endpoint makes only a superficial difference.

The authentication requirement of this API should be decided upon by whoever hosts the server and I don't think the spec can make a recommendation either way. It depends too much on what group you are running the server for.

2025-02-25 23:49 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +would know about the room already.
This comment is specifically about when the room info is fetched over federation. In those cases no membership information is available on the local server, but it can reasonably assume none of its local users are joined or invited. While that is obvious, I thought it deserved spelling this out explicitly, since servers shouldn't just omit the membership key in that case. It probably makes more sense to change `doesn't know about the room` to `is not participating in the room` or `does not have any local users in the room` or something about having had to fetch the summary over federation.

2025-02-25 23:51 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +`encryption` and `allowed_room_ids`.
You mean in the example above? Yes, because the `join_rule` is public. It is explained in the table below though, which also says that the field is optional. Does this need an example specifically with the `room_ids`, if the /hierarchy API already uses that field?

2025-02-25 23:53 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +to the current state of the room.
There is no way to fetch a room summary over federation, that isn't publicly joinable and a user has been invited to. How would it fetch a more up to date state? That is not how invites currently work on Matrix.

2025-02-25 23:54 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +security implications with that may better be left to a separate MSC.)
It is mentioned as an alternative, because people brought up "just call sync" when I initially discussed this MSC with people. This section is an argument in that discussion. It obviously isn't a good alternative, but people needed that spelled out at the time and I didn't want to have this argument multiple times.

2025-02-25 23:57 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +server (that looks like this proposal).
So far nobody said they would benefit from a batch API apart from one use cases, that wanted an easy way to show a room list for the /joined_rooms response. The vast majority of use cases I have seen only query one room. Batching is simply more complicated since you also might not be able to pass vias as query parameters, etc. Unless someone provides a use case, I don't see why a batched API is a better design.

2025-02-25 23:59 UTC, deepbluev7 commented on proposals/3266-room-summary.md
> +alias, and a corresponding server-server API to fetch a summary over federation.
Strictly speaking we could mention that the federation API for the hierarchy API is adapted as well, but tbh, who cares about that detail in the opening paragraph.

2025-02-26 07:54 UTC, Johennes commented on proposals/3266-room-summary.md
> +server (that looks like this proposal).
I think it's fair not to specify a batch API on the premise of lacking use cases and increased complexity. The alternative, as written, doesn't include this reasoning, however. In my understanding the main reason for writing down alternatives is to prove that the proposed solution is the best solution by way of showing that all known alternatives are inferior.

2025-02-26 08:16 UTC, Johennes commented on proposals/3266-room-summary.md
> +calls. Restricting this API to guests only would provide no security benefit.
> If servers want to disable unauthenticated access for this in a private federation, that is fine. But in an open federation we generally consider public rooms public. You aren't providing any additional security by requiring authentication for this API. All of that data is already available to anyone, who can set up a homeserver. While that is a minuscule amount of work and as such harder than calling an unauthenticated API directly, it won't prevent anyone from getting access to this data.

This is true but I think allowing unauthenticated access via the client-server API lowers the bar substantially. Everyone with a browser can query this endpoint. Critically, in a private federation those are users you don't control and may not want to share data with. I don't have a strong opinion on whether we default to authenticated access with the option to allow unauthenticated access or the other way around. But I think as an admin I should be able to lock down this API on my own server.

2025-02-26 09:15 UTC, richvdh commented on proposals/3266-room-summary.md
> +  topic: "Tasty tasty cheese",
> I also don't see why this MSC needs to clarify if it is using m.topic over topic now ... this MSC already clarifies where it is taking the fields from (the hierarchy API and related to the public rooms API)

Yup, this is fair, on closer inspection: this MSC just says "These are the same fields as those returned by `/publicRooms` ..." which seems clear enough.

2025-02-26 09:18 UTC, richvdh commented on proposals/3266-room-summary.md
> +would know about the room already.
Ok well, let's change it to "It should be `leave` if the server does not have any local users in the room" if you think it's important to have something here, though IMHO it's clearer with nothing.

2025-02-26 11:13 UTC, dbkr commented on proposals/3266-room-summary.md
> +server (that looks like this proposal).
I guessed this was probably the answer, I was more pointing out that your "alternative" sections should probably end with why you didn't choose this option (even if that reason is something like, "it doesn't matter at all but we had to pick one so we picked this one").

2025-03-04 08:58 UTC, Johennes commented on proposals/3266-room-summary.md
> +server (that looks like this proposal).
How about something like this?

```suggestion
server (that looks like this proposal). At the same time, a batched API is inherently
more complex to implement for both clients and servers. Additionally, there are no
known use cases yet that would benefit from batched access.
```

2025-03-04 09:08 UTC, dbkr commented on proposals/3266-room-summary.md
> +server (that looks like this proposal).
Looks good to me!

2025-03-04 09:38 UTC, dbkr commented on proposals/3266-room-summary.md
> +to the current state of the room.
Oh, because it's using the `/hierarchy` API over federation which doesn't allow fetching state of rooms you're not joined to? I hate to say it knowing you've already switched away from adding a federation part to the API, but possibly this would be a good reason to have one, then it could allow servers to view the summary if they had a user that had been invited. Potentially it could be left to a separate MSC but I'd certainly like if it were explained a lot better in the meantime.

2025-03-04 10:06 UTC, richvdh commented on proposals/3266-room-summary.md
> +calls. Restricting this API to guests only would provide no security benefit.
> It seems like we can accommodate both points of view by simply making it clear that allowing unauthenticated access is left up to the server implementer and admin, as @Johennes stated at the start of this thread.

Since nobody has objected to this, I'll update the text of the MSC to clarify this.

2025-03-04 14:43 UTC, dbkr commented on proposals/3266-room-summary.md
> +`encryption` and `allowed_room_ids`.
In the JSON object above, yep, but the text says, "in the following format" rather than, "for example" so I was reading that as a canonical definition rather than an example. This might just be a case of misunderstanding and it just needs to be relabelled as an example.

2025-03-04 14:43 UTC, richvdh commented on proposals/3266-room-summary.md
> +| room_type          | Optional. Type of the room, if any, i.e. `m.space`                                                                                                    | Used to distinguish room
this is also copied from `publicRooms`, I think

2025-03-04 14:53 UTC, richvdh commented on proposals/3266-room-summary.md
> +| encryption         | Optional. If the room is encrypted this specified the algorithm used for this room. This is already accessible as stripped state. | Some users may only want to join encrypted r
I see `canonical_alias` is not listed here: should it be?

2025-03-04 15:51 UTC, richvdh commented on proposals/3266-room-summary.md
> +calls. Restricting this API to guests only would provide no security benefit.
Clarified in 2f48c41e

2025-03-04 15:51 UTC, richvdh commented on proposals/3266-room-summary.md
> +to the current state of the room.
Clarified in 7299a8bf

2025-03-04 15:52 UTC, richvdh commented on proposals/3266-room-summary.md
> +`encryption` and `allowed_room_ids`.
Clarified in 45fbfab3.

2025-03-04 15:52 UTC, richvdh commented on proposals/3266-room-summary.md
> +| room_type          | Optional. Type of the room, if any, i.e. `m.space`                                                                                                    | Used to distinguish room
Clarified in 45fbfab3

2025-03-04 15:52 UTC, richvdh commented on proposals/3266-room-summary.md
> +| encryption         | Optional. If the room is encrypted this specified the algorithm used for this room. This is already accessible as stripped state. | Some users may only want to join encrypted r
Added in 6aacb773

2025-03-04 16:01 UTC, richvdh commented
I have given this another round of updates. SCT members who had previously ticked their boxes may wish to give this another round of review; however I *hope* there is nothing that will be controversial here. @deepbluev7 likewise: I hope you don't object to any of my changes here.

I think there are only two material changes:

 * Most notably: whether to expose the endpoint to unauthenticated access is now left as a decision for admins and server implementations (2f48c41e).
 * I took the executive decision to add `canonical_alias` to the response: it looked like its omission was an accident rather than deliberate.

There have been a number of other changes, but I believe they are all clarifications, rather than material changes.

2025-03-04 16:02 UTC, richvdh commented
@mscbot resolve should unauthenticated access be enabled by default?

2025-03-04 16:24 UTC, Johennes commented on proposals/3266-room-summary.md
> +   information about rooms that would otherwise be registered users (particularly
I think there's something missing here?

```suggestion
   information about rooms that would otherwise be restricted to registered users (particularly
```

2025-03-04 16:25 UTC, richvdh commented on proposals/3266-room-summary.md
> +   information about rooms that would otherwise be registered users (particularly
thank you :facepalm:

2025-03-26 09:05 UTC, richvdh commented
@KitsuneRal you have an outstanding request for changes (https://github.com/matrix-org/matrix-spec-proposals/pull/3266#pullrequestreview-824153665, I think). Could you dismiss your review, unless you still want to see changes here?

2025-03-26 09:05 UTC, richvdh commented
> 🔔 This is now entering its final comment period, as per [the review](https://github.com/matrix-org/matrix-spec-proposals/pull/3266#issuecomment-2579239313) above. 🔔

As far as I can tell, this should have completed FCP weeks ago, but the bot seems to be stuck.

2025-03-26 09:13 UTC, KitsuneRal approved these changes

2025-03-26 18:58 UTC, turt2live commented
considering FCP completed as-is. If there's edits to be made to the MSC, please put those up as a PR urgently.

2025-03-26 18:58 UTC, merged

2025-03-28 12:39 UTC, Johennes commented on proposals/3266-room-summary.md
> + * the room has `join_rule: public` or `join_rule: knock`, or:
I suspect this is meant to include `knock_restricted`?

2025-03-28 13:14 UTC, Johennes commented on proposals/3266-room-summary.md
> +- `via` are servers that should be tried to request a summary from, if it can't
Sorry, I confused myself. We went from `server_name` _to_ `via` on the other endpoints. So there's no issue after all.

2025-03-28 17:22 UTC, turt2live commented on proposals/3266-room-summary.md
> + * the room has `join_rule: public` or `join_rule: knock`, or:
If the current implementation does so, yes. Otherwise it'll need a new MSC.

2025-03-28 20:22 UTC, Johennes commented on proposals/3266-room-summary.md
> + * the room has `join_rule: public` or `join_rule: knock`, or:
Luckily it does: https://github.com/element-hq/synapse/blob/develop/synapse/handlers/room_summary.py#L611