MSCXXXX: Hiding messages
matrix-org/matrix-spec-proposals pull request #3391
Opened 2021-09-09 14:16 UTC by ShadowJonathan

Fixes https://github.com/matrix-org/matrix-doc/issues/692

`Signed-off-by: Jonathan de Jong <jonathan@automatia.nl>`

2021-09-09 14:22 UTC, deepbluev7 commented on proposals/3391-account-data-delete.md
> +  "account_data_removed": ["m.direct", "m.push_rules"], // <- NEW
Why not:

```
"account_data": {
  "events": [],
  "removed": []
}
```

Then the same schema would be extensible to state events (because of state res) too.

2021-09-09 14:25 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +  "account_data_removed": ["m.direct", "m.push_rules"], // <- NEW
ah heck, didnt see that, one second

2021-09-09 14:32 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +in `events` as replacing what existed previously.
I'm not 100% sure what the spec says about this on full sync, but this'd be a replace action on full sync hereafter, instead of a additive action to whatever internal state the client's cache would have.

2021-09-14 20:03 UTC, uhoreg commented on proposals/3391-account-data-delete.md
> +
One issue is that a client that doesn't understand the `removed_events` property will still think that the data is still set.  One possible way to mitigate that would be to have the server also include it in `events`, but with `content` being an empty object, which is the closest to "deleting" that we currently have.  e.g.

```json5
{
  "account_data": {
    "events": [
      {
        "content": {},
        "type": "m.direct"
      }
    ],
    "removed_events": ["m.direct"]
  }
}

2021-09-15 09:27 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +
I think that's a wart, but maybe it's a good approach while this is still unstable.

Should i add a mention of this to the unstable section? The intention is to remove this hack upon stabilisation, though.

2021-12-01 09:20 UTC, Dominaezzz commented on proposals/3391-account-data-delete.md
> +
If this is added, then there should also be a clarification saying that clients should remove `events` that are also in `removed_events`.

2022-04-08 17:47 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +# MSC3391: Deleting account data
At the moment I’m unsure if this MSC should move forward, considering some “account data as rooms” ideas I’ve seen floating around (disregarding the various problems that exist around that for the moment).

Would this MSC still be a good idea to move forward, considering it might interfere with future developments? Or could that be decided at review time?

2022-04-15 19:57 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +
I've added a note about this in [`88f7f7c` (#3391)](https://github.com/matrix-org/matrix-spec-proposals/pull/3391/commits/88f7f7cf824e6f6e39eed0359b7808dba875284b), would that resolve this thread?

2022-05-17 17:48 UTC, anoadragon453 approved these changes
lgtm, have left a few clarifications below.

2022-05-17 17:48 UTC, anoadragon453 commented on proposals/3391-account-data-delete.md
> +as clients adapt, but the SCT can - of course - have differing opinions.*
This should work, as long as no account data relies on a difference between a key being absent, and `key: {}`. Though given that account data could not be deleted before, I'd be skeptical of any implementation doing so.

Leaving in this optional backwards-compatibility hack, and then having another MSC to eventually remove the ability in a future spec version seems reasonable.

2022-05-17 17:48 UTC, anoadragon453 commented on proposals/3391-account-data-delete.md
> +
I'd say so!

2022-05-17 17:48 UTC, anoadragon453 commented on proposals/3391-account-data-delete.md
> +cache invalidation problems could occur as clients could aggressively cache account data.
The cache should be updated for a top-level account data key with the backwards-compatibility step mentioned above?

2022-05-17 18:06 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +cache invalidation problems could occur as clients could aggressively cache account data.
Yeah, it seems that would purge old clients' caches, with new clients using the new method.

2022-05-22 14:55 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +supporting only matrix versions it does not understand, and fail-fast if this is the case.*
@anoadragon453 / SCT, i'd like your opinion on this.

From my perspective, it seems reasonable to assume that a client will be tentative to interact with a server that only supports versions it does not "understand".

Especially in the context of this MSC, it'd be reasonable automatic deprecation of the backwards-compatible hack, if a client is expected to "know" at least one version the server announces, and all versions would include that MSC's behavior.

However, this is not a rule, and only an assumption, so I'm asking if this is a reasonable approach.

2022-08-10 10:47 UTC, Johennes commented on proposals/3391-account-data-delete.md
> +# MSC3391: Deleting account data
> Synapse (#WIP)

@ShadowJonathan did you already have an implementation for this somewhere? I couldn't see anything in the Synapse PRs.

2022-08-22 17:16 UTC, anoadragon453 commented on proposals/3391-account-data-delete.md
> +supporting only matrix versions it does not understand, and fail-fast if this is the case.*
While reasonable indeed and a perfectly valid approach, it would come with the downside that even clients that support this MSC would still receive old entries in their account data. I don't expect homeservers to drop spec versions older than the one this MSC makes it into for... years most likely. Without that, I think this MSC loses its main beneficial property; the ability to remove keys from a user's account data.

Perhaps another approach could be to have clients signal to the homeserver that they support this feature. Something like adding an `exclude_deleted_account_data` boolean to `RoomEventFilter`? Alongside a query parameter to [`GET /_matrix/client/v3/user/{userId}/account_data/{type} `](https://spec.matrix.org/v1.3/client-server-api/#get_matrixclientv3useruseridaccount_datatype) and [`GET /_matrix/client/v3/user/{userId}/rooms/{roomId}/account_data/{type}`](https://spec.matrix.org/v1.3/client-server-api/#get_matrixclientv3useruseridroomsroomidaccount_datatype). It's not the cleanest solution and one we'd be stuck with for a long time... but perhaps arguably better than the alternative.

Open to thoughts from others on a better approach.

2022-08-23 10:16 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +supporting only matrix versions it does not understand, and fail-fast if this is the case.*
First thoughts: I feel like a kickback mechanism like that would fall far beyond the scope of just this MSC, and feels superfluous to Matrix Versioning.

I'll have to see what I can do, I think it's better to look at the long term rather than short-term solutions for this.

2022-09-21 15:10 UTC, anoadragon453 commented on proposals/3391-account-data-delete.md
> +supporting only matrix versions it does not understand, and fail-fast if this is the case.*
Do any clients currently rely on account data entries with an empty object as a value? If not, could we just forgo the `removed_events` field entirely and just spec that an account data event with a content of `{}` means that the entry was deleted? I believe there's already some form of "`{}` means delete the account data entry is no longer in use" culture in clients today.

It would also mean that setting an entry with an empty content would no longer be valid.

2022-09-21 15:32 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +supporting only matrix versions it does not understand, and fail-fast if this is the case.*
I don't know, then it wouldn't be a change that would require a spec change, but then it's more a semantic one regarding which apis do what (based on their names), and the fact that there's a guardrail on preventing setting `{}` on a key.

I don't know if that is worth the effort to spec and process, if a note declaring that "this is the intended way to delete a key" (without changing any functional behaviour) could be enough.

2022-10-11 14:11 UTC, richvdh commented on proposals/3391-account-data-delete.md
> +Account data and room data currently have the following endpoints;
please could you add a link to the relevant part of the existing spec.

2022-10-11 14:53 UTC, richvdh commented on proposals/3391-account-data-delete.md
> +the entry in `removed_events`.
what exactly would such an "empty" entry look like? you mean literally an empty object? but how would a client know what to do with that?

2022-10-11 15:00 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +the entry in `removed_events`.
Yes, I meant an empty object, `{}`, here.

Current behaviour is that a client would replace their cached entry under that key with `{}` if they see that, effectively removing all data.

2022-10-11 15:04 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +data than the server, it should query the account data wherever possible.
This was written when i was afraid that i'd miss to name some endpoints that are relevant for account data.

If not all endpoints are included into considering a new behaviour, the client could possibly get in a state where it uses removed account information as if it were live.

2022-10-11 15:12 UTC, richvdh commented on proposals/3391-account-data-delete.md
> +the entry in `removed_events`.
> Current behaviour is that a client would replace their cached entry under that key with {} if they see that, effectively removing all data.

What is the "key" of an empty object?

(I think you might be assuming that account_data arrives over /sync as key/value pairs. That is not what the spec says, at least.)

2022-10-11 16:11 UTC, richvdh commented on proposals/3391-account-data-delete.md
> +data than the server, it should query the account data wherever possible.
ok, I don't find this section very clear. Perhaps you could update it with clarifications.

2022-10-11 16:24 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +the entry in `removed_events`.
I'm talking about both `/sync` and `/account_data`, and any other endpoint that might return account data.

> Why would it return {} rather than reverting to the same behaviour as before the account data was set in the first place (a 404, presumably)?

Because older clients might not know how to deal with a `404` when previously it'd return data, as that might be an assumption client/library authors make with how matrix is today; when account data is set, it is never un-set.

This MSC seeks to make it possible to un-set it, but older clients might crash and burn if presented with 404s here, and might not get the hint that data is removed with `removed_events`, and so continue on invalid assumptions.

(For example, if a `m.secret_storage.key` was present in one moment, and un-set in the next from a new client, the old client might perform undefined behaviour with the key(s) because it thinks that one key is still present.)

Thus, to gracefully introduce this new incompatible behaviour, the server should act as if `{}` is the new value for these deleted keys for compatibility reasons, until that's no longer necessary (when all versions that do not have account data removal are not supported anymore by that server software).

2022-10-11 17:18 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +supporting only matrix versions it does not understand, and fail-fast if this is the case.*
Thank you for taking the time to discuss this, I agree with this approach, and will rewrite the MSC to take advantage of it.

However, I'd like to not leave the issue of "what is returned to devices who have seen the set account data key before" up to ambiguity.

So, I will write the above behaviour ("track which devices have seen it, and return `{}` to those that have") into the new prose, so that approach or a better one can be discussed.

2022-10-11 17:42 UTC, anoadragon453 commented on proposals/3391-account-data-delete.md
> +supporting only matrix versions it does not understand, and fail-fast if this is the case.*
@ShadowJonathan I think you may have misunderstood my last paragraph? Tracking which devices have seen the deletion go through (either via `/sync` or one of the `GET .../account_data/` endpoints) is only for the purpose of the homesever knowing when it can actually purge the account data from its database (to free up space). It's just a recommendation for space-saving in homeserver implementations; it doesn't change what is returned to clients.

* Clients that provide a `since` token before an account data entry deletion happened, should *always* receive `{}` content for the deleted event type in the `/sync` response.
* Clients that query a deleted account data entry via `GET /_matrix/client/v3/user/{userId}/account_data/{type}` or ` GET /_matrix/client/v3/user/{userId}/rooms/{roomId}/account_data/{type}` should *always* receive a `HTTP 404` / `M_NOT_FOUND` response.

2022-10-11 18:35 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +supporting only matrix versions it does not understand, and fail-fast if this is the case.*
Thanks for clarifying, yes, I indeed didn't fully understand what you were going for, but now I think i do.

2022-10-11 18:36 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +the entry in `removed_events`.
Sorry, yes, in my head I have been confusing this as a KV store, considering in all ways but mapping as representation, it acts like it.

Yes, I did mean `{}` for the `"content"` key for entries in `events`.

2022-10-11 18:40 UTC, richvdh commented on proposals/3391-account-data-delete.md
> +the entry in `removed_events`.
Returning `{}` to `GET /_matrix/client/v3/user/{userId}/account_data/{type}` after it has been deleted seems... extreme.

Anyway, it's clear that this section needs clarifying before we can do any more useful review.

2022-10-11 18:45 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +the entry in `removed_events`.
I don't think I will continue this MSC with that behaviour, as in [another thread](https://github.com/matrix-org/matrix-spec-proposals/pull/3391#discussion_r992616958) I have come to an agreement on how to proceed, which includes removing this exact `/account_data/` compatibility behaviour.

2022-10-12 11:06 UTC, anoadragon453 commented on proposals/3391-account-data-delete.md
> +When implementing this proposal, servers should use the `org.matrix.msc3391` unstable prefix;
Currently this MSC does not define any way for a client to know if it has been implemented (no `unstable_features` flag). That means that when a client tries to remove account data, there are 3 possible scenarios:

- The homeserver does not support this feature.
- The homesever supports an unstable version of this feature.
- (once the MSC is accepted) the homeserver supports a stable version of this feature.

It’d probably be a good idea to define `org.matrix.msc3391.unstable` and `org.matrix.msc3391.stable` `unstable_features` flags to help clients differentiate between all 3. (Also open to feedback on other solutions, as two unstable feature flags feels a bit messy.)

2022-10-20 11:41 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +When implementing this proposal, servers should use the `org.matrix.msc3391` unstable prefix;
I went with `org.matrix.msc3391` as an unstable key, i believe that clients can assume support for the unstable prefix if they see that key, and assume stable support if they observe the server `/versions` including a matrix version that contains this MSC.

2022-10-20 11:41 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +data than the server, it should query the account data wherever possible.
I updated the document, this section no longer exists due to the changes.

2022-10-20 11:42 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +the entry in `removed_events`.
I updated the document, this section no longer exists due to the changes.

2022-10-20 11:42 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +`account_data.removed_events`, the reference in `.removed_events` must be ignored.
I updated the document, this section no longer exists due to the changes.

2022-10-20 11:55 UTC, ShadowJonathan commented
Heads up that with [`333264f` (#3391)](https://github.com/matrix-org/matrix-spec-proposals/pull/3391/commits/333264fbe1d2ec8044d6c89ffe71cd1319d55a34) I have changed the semantics of the MSC, the most important one is the removal of "`removed_events`" from sync, and redefining `{}` account data as "deleted" across the board. This simplifies the MSC and related changes going forward.

2022-10-20 14:51 UTC, anoadragon453 commented on proposals/3391-account-data-delete.md
> +These, respectively, remove account-wide account data, and room-scoped account data.
Could you clarify what happens if you try to call either of these `DELETE` endpoints with a [room] account data type that doesn't exist?

I propose that `200 OK` / `{}` be returned, to ensure idempotent responses if called multiple times.

2022-11-25 15:42 UTC, anoadragon453 commented on proposals/3391-account-data-delete.md
> +Furthermore, when a client deletes account data, it must expect `/account_data/` to return a 404 on
```suggestion
Furthermore, when a client deletes account data, it must expect the `GET` methods above to return a 404 on
```

for clarity

2022-12-30 15:03 UTC, anoadragon453 commented on proposals/3391-account-data-delete.md
> +the next request.
We ran into a Potential Issue:tm: when implementing this MSC in Synapse which I think would be good to document somewhere.

After an account data entry has been deleted, that change must be broadcast to all devices. Once that's been done, it would be ideal if we could remove the record of that account data type ever being set in the homeserver (for reduction of user data and (slight) storage benefits).

This gets a little complicated when you try to quantify at what point all devices have a user have seen the delete. One way to do this (what is [currently planned](https://github.com/matrix-org/synapse/issues/14244) for Synapse) is to track the devices that *haven't* yet seen the delete, and then tick them off the list once they have.

But what does it mean for a device to have *seen* an account data change? If they have `/sync`'d the change, we can likely say they've seen the change. We should be careful though, as the device may have error'd in processing the `/sync` response, and if it retries the request after we've deleted the row, then the response will not include the delete(!). Instead, we should only assume the client has successfully seen the delete when they make a *subsequent* `/sync` request with a `since` token that implies they've processed the delete (Synapse's `since`/`next_batch` tokens allow for this as they encode points in streams; other homeserver implementations may not have this property).

And what if a device requests `GET /_matrix/client/v3/user/{userId}/account_data/{type}` after a delete has occurred? Should we assume that the device has seen the delete? Initially I thought 'yes', but @reivilibre pointed out that this means a request to `GET /_matrix/client/v3/user/{userId}/account_data/{type}` could mean (if the device was the last to see the delete) that the delete would then not come down `/sync` - which feels like a massive footgun. As a result, we've decided not to assume a call to `GET /_matrix/client/v3/user/{userId}/account_data/{type}` means a device has seen a delete, and instead of use `/sync` requests.

---

All of this falls squarely into the area of implementation - but it may be useful to other homeserver implementations. None of this is an issue if the implementation chooses to keep "deleted" account data entries in their database forever.

2022-12-30 15:09 UTC, babolivier commented on proposals/3391-account-data-delete.md
> +the next request.
> But what does it mean for a device to have _seen_ an account data change?

Presumably servers can implement the same logic as for when they need to figure out whether a device has seen a to-device message (so that the server can delete it)? Especially as to-device messages have a better case for robustness than account data.

2022-12-30 15:23 UTC, anoadragon453 commented on proposals/3391-account-data-delete.md
> +the next request.
Good point - it is indeed very similar. The only difference is that account data has this extra way of being accessed (via `GET /_matrix/client/v3/user/{userId}/account_data/{type}`). So whether you also count that as seeing the change is the only decision you need to make if you've already settled on a design for deleting old to-device messages.

2023-01-19 15:38 UTC, anoadragon453 commented
This MSC has been implemented in Synapse: https://github.com/matrix-org/synapse/pull/14714.

I've updated the MSC's description to reflect this :slightly_smiling_face: cc @ShadowJonathan

2023-01-19 15:44 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +This proposal aims to add the following two endpoints (with no request body):
Note: Synapse is now also considering `PUT {}` as equivalent as `DELETE`, this is maybe worth considering to formalise.

2023-03-22 10:45 UTC, anoadragon453 commented
This MSC is still missing a **client implementation** before it can progress further through the Spec Process.

(I don't believe [the linked Element iOS PR](https://github.com/vector-im/element-ios/pull/7164) yet counts as it doesn't make use of the new endpoints.)

2023-03-22 10:45 UTC, anoadragon453 commented on proposals/3391-account-data-delete.md
> +The `unstable_features` key for this MSC is `org.matrix.msc3391`.
Could you clarify this to say that, presumably, a boolean value of `true` means that MSC3391 is supported by the homeserver, and any other value or the key not being present means that support is not there?

2023-03-22 13:25 UTC, Johennes commented
> This MSC is still missing a **client implementation** before it can progress further through the Spec Process.
> 
> (I don't believe [the linked Element iOS PR](https://github.com/vector-im/element-ios/pull/7164) yet counts as it doesn't make use of the new endpoints.)

It was implemented in the JS SDK with https://github.com/matrix-org/matrix-js-sdk/commit/b2a10e6 actually.

2023-03-22 15:22 UTC, anoadragon453 commented
@Johennes Oh I see! Thank you for updating the PR description as well to reflect that.

> It was implemented in the JS SDK with https://github.com/matrix-org/matrix-js-sdk/commit/b2a10e6 actually.

Has this been tested against the Synapse implementation yet? As far as I know the Synapse implementation [does not actually include](https://github.com/matrix-org/synapse/blob/25006acc1766ca51fba0d898b4613d2588cfffb8/synapse/rest/client/versions.py#L83-L127) a `org.matrix.msc3391` field, which it appears the JS implementation requires to use the new endpoints (as it should). Otherwise it will fall back to using `{}` to override the account data object.

Of course `PUT`ing `{}` will under this MSC still delete the account data entry, but it'd be good to test out the new endpoints as well.

2023-03-22 15:23 UTC, anoadragon453 commented on proposals/3391-account-data-delete.md
> +The `unstable_features` key for this MSC is `org.matrix.msc3391`.
@Johennes will Element clients (being as far as I'm aware the only clients that have implemented this MSC) want to eventually have a `org.matrix.msc3391.stable` key as well, to know that the feature is supported and that clients should make use of stabilised endpoints?

If so, we should add that to the MSC as well.

2023-03-22 15:59 UTC, Johennes commented
> Has this been tested against the Synapse implementation yet? As far as I know the Synapse implementation [does not actually include](https://github.com/matrix-org/synapse/blob/25006acc1766ca51fba0d898b4613d2588cfffb8/synapse/rest/client/versions.py#L83-L127) a org.matrix.msc3391 field, which it appears the JS implementation requires to use the new endpoints (as it should). Otherwise it will fall back to using {} to override the account data object.

Hm, you're right. We seem to use the endpoints without checking the feature flag on [Element Android](https://github.com/vector-im/element-android/commit/d244f7324c40c59b82c315491ad459591f006d81). I think we're falling back to doing the `PUT` override when that request fails there. @kerryarchibald could you comment on how this was tested during implementation?

2023-05-07 20:35 UTC, kerryarchibald commented
This was tested against the ROSA deployment with the msc3391  flag enabled, and then against matrix.org to test the fallback.

2023-05-08 13:34 UTC, clokep commented on proposals/3391-account-data-delete.md
> +### Endpoints
I assume these endpoints would reject deleting `m.fully_read` like the current [setter endpoints](https://spec.matrix.org/v1.6/client-server-api/#server-behaviour-10)?

2023-05-09 10:24 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +The `unstable_features` key for this MSC is `org.matrix.msc3391`.
> and any other value or the key not being present means that support is not there?

Ah, I thought this was implied, but i will clarify this 👍

2023-05-10 11:58 UTC, anoadragon453 commented on proposals/3391-account-data-delete.md
> +The `unstable_features` key for this MSC is `org.matrix.msc3391`.
> I _think_ so. @kerryarchibald is that correct?

Note that @kerryarchibald replied here: https://github.com/matrix-org/matrix-spec-proposals/pull/3391#issuecomment-1537535008

2023-05-10 13:18 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +### Endpoints
Yes;

`For any account data key that cannot be set, the delete API will have a likewise error response.`

Would adding this satisfy this case?

2023-05-10 15:25 UTC, anoadragon453 reviewed
Barring a couple open threads that the author have signaled that they'll get to soon, I think this MSC is sound. Let's get it over the line.

@mscbot fcp merge

2023-05-10 15:25 UTC, anoadragon453 commented on proposals/3391-account-data-delete.md
@kerryarchibald, moving this to a thread.

> Does this mean there was never a working feature flag? I do seem to remember testing and seeing `DELETE` calls in the console, so possibly I tested it without the flag check, then added that later for completeness. I don't think the support check should be removed in js-sdk, will the flag be added to synapse?

There was not, no. it was missed in the original implementation. I've now added one in https://github.com/matrix-org/synapse/pull/15562.

Looking through the matrix-js-sdk client implementation, it looks like https://github.com/matrix-org/matrix-js-sdk/commit/b2a10e6 covers deleting _user_ account data, but [not room account data](https://github.com/matrix-org/matrix-js-sdk/blob/73ca9c9ed28847454e13da358c581769e695ff42/src/client.ts#L4217-L4224). Though I'm guessing there may not be a driving feature for for deleting room account data yet?

The mechanisms for deleting user vs room account data are exactly the same though, so I think it's safe to consider an implementation for only one of them sufficient.

2023-05-10 15:27 UTC, anoadragon453 commented
(I've yet to deploy a new version of the bot that supports commands in PR review bodies.)

@mscbot fcp merge

2023-05-10 15:37 UTC, turt2live commented
SCT context: this is primarily maintenance work we shouldn't let languish, but don't have a strong driving force to bump it to the top of the priorities list. The SCT will take a look whenever they have a chance (which may mean it'll be sitting in proposed-FCP for a while, sorry).

If folks have a use case which might affect the SCT's priority on this, please let us know in the [SCT Office](https://matrix.to/#/#sct-office:matrix.org).

2023-06-06 13:38 UTC, richvdh requested changes

2023-06-06 13:38 UTC, richvdh commented on proposals/3391-account-data-delete.md
> +Account Data changes are announced through sync, this proposal also aims to change this response slightly after account data deletion.
```suggestion
Account Data changes are announced through sync; this proposal also aims to change this response slightly after account data deletion.
```

2023-06-06 13:38 UTC, richvdh commented on proposals/3391-account-data-delete.md
> +This must happen only on syncs with a `since` token.
So to be clear: on syncs *without* a `since` token, clients must interpret `{}` as regular account data? Is that absolutely necessary? It seems like it's fiddly for a client to implement and it's not clear to me why it is so important.

2023-06-06 13:38 UTC, richvdh commented on proposals/3391-account-data-delete.md
> +- Allow `DELETE` HTTP methods on account data endpoints to perform the deletion.
It's not entirely clear to me that we should have both of these mechanisms. My experience is that, where the protocol allows two ways of doing a thing, they will end up being subtly different somehow and it leads to compatibility problems (eg, one server implementation will forget to implement DELETE because the client they test with only uses PUT).

Given that we don't have any special server-side semantics for `PUT {}`, can we stick with that situation, and only do the special "deletion" behaviour for an actual `DELETE`?

2023-06-06 13:38 UTC, richvdh commented on proposals/3391-account-data-delete.md
> +the next request.
> All of this falls squarely into the area of implementation

I'm not convinced it does, entirely. It seems important to me that we specify when exactly a client can expect the 'deleted' account data to be served.

2023-06-06 13:38 UTC, richvdh commented on proposals/3391-account-data-delete.md
> +This must happen only on syncs with a `since` token.
I notice an earlier version of this MSC suggested a separate key for deleted account data (possibly to be used alongside returning `{}` in `events` for backwards compat). But I've not found where that idea was removed. Maybe you could discuss the reason not to use `deleted_events` in an "Alternatives" section?

2023-06-06 19:28 UTC, turt2live commented on proposals/3391-account-data-delete.md
> +This proposal aims to add the following two endpoints (with no request body):
```suggestion
This proposal adds the following two endpoints (with no request body):
```

MSCs are authoritative, generally.

2023-06-06 19:28 UTC, turt2live commented on proposals/3391-account-data-delete.md
> +```
it's implied, but not stated:
* Do these endpoints require authentication?
* Can these endpoints be rate limited?

2023-06-06 19:28 UTC, turt2live commented on proposals/3391-account-data-delete.md
> +`{}` for an event content as it being deleted.
Why the specific client behaviour? Clients are generally left to decide for themselves how they want to deal with this stuff. Some might choose to store it verbatim, others might not care. Some might even polyfill deleted/missing account data to ensure their code doesn't explode.

2023-06-06 19:29 UTC, turt2live commented
@mscbot concern Unclear semantics for sync
@mscbot concern Unspecified behaviour for when a client can expected deleted account data to be served
@mscbot concern New endpoints may require auth and rate limiting

2023-06-10 10:10 UTC, KitsuneRal commented on proposals/3391-account-data-delete.md
> +the next request.
I might be missing something obvious but how much is this problem different from any other change in account data? What if it's a good ol' PUT and some other device crashes at processing the /sync batch that has this change?

2023-06-10 10:26 UTC, KitsuneRal commented on proposals/3391-account-data-delete.md
> +`{}` for an event content as it being deleted.
I guess the emphasis here should be on `{}` as the way to tell a client that the piece of account data is deleted, not on the client behaviour ("you shall delete this piece not store `{}`").

2023-06-10 10:29 UTC, KitsuneRal commented on proposals/3391-account-data-delete.md
> +This must happen only on syncs with a `since` token.
I read this as an instruction to _server_ authors not to include deleted data (with `{}`) if `/sync` is called without `since`, even if the deletion has just occurred.

2023-06-12 13:49 UTC, richvdh commented on proposals/3391-account-data-delete.md
> +This must happen only on syncs with a `since` token.
*much* clearer ;)

2023-06-15 11:13 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +`{}` for an event content as it being deleted.
This is also for backwards compatibility, to make sure this sudden approach does not break a lot of clients.

2023-06-15 11:13 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +```
Yes and Yes, i'll add 👍

2023-06-15 11:14 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +This must happen only on syncs with a `since` token.
Will add 👍

2023-06-15 11:17 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +This must happen only on syncs with a `since` token.
Will improve the wording around thus 👍

2023-07-04 03:27 UTC, turt2live commented
It appears as though the author(s) aren't currently able to take this on - cancelling FCP pending the MSC being [re-raised to the SCT](https://matrix.to/#/#sct-office:matrix.org)

@mscbot fcp cancel

2023-07-13 09:42 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +- Allow `DELETE` HTTP methods on account data endpoints to perform the deletion.
As an alternative, should we define `PUT {}` to return http 400, at the minuscule risk of breaking existing clients?

2023-07-13 09:45 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +`{}` for an event content as it being deleted.
This note also changes the *semantic* of `{}` to mean "deleted", partly for backwards compatibility, but also to harmonise other aspects of this proposal.

2023-07-13 09:45 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +This must happen only on syncs with a `since` token.
Addressed in [`0653f34` (#3391)](https://github.com/matrix-org/matrix-spec-proposals/pull/3391/commits/0653f3468242c0fe18d90a16794c1488d30f54f2)

2023-07-13 09:45 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +This must happen only on syncs with a `since` token.
Addressed in [`0653f34` (#3391)](https://github.com/matrix-org/matrix-spec-proposals/pull/3391/commits/0653f3468242c0fe18d90a16794c1488d30f54f2)

2023-07-13 09:45 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +```
Addressed in [`0653f34` (#3391)](https://github.com/matrix-org/matrix-spec-proposals/pull/3391/commits/0653f3468242c0fe18d90a16794c1488d30f54f2)

2023-08-21 23:36 UTC, turt2live commented on proposals/3391-account-data-delete.md
> +the next request.
@ShadowJonathan this thread appears to be unresolved, and I think it's blocking FCP from starting.

2023-08-22 10:06 UTC, ShadowJonathan commented on proposals/3391-account-data-delete.md
> +the next request.
> As a result, we've decided not to assume a call to GET /_matrix/client/v3/user/{userId}/account_data/{type} means a device has seen a delete, and instead of use /sync requests.

Can we even tie access tokens to device IDs like this, or do we assume this per access token?

That brings up a whole can of worms for me too, and so i wish to assume that deletion of account data be a best-effort case only.

I think that enumerating and deleting account data only if all access tokens have seen it is not ideal from a performance perspective, since stale access tokens can "block" deletion of data like this, and it'd require a whole tracking system for what-access-token-has-seen-what in implementations, which i'm not aware exists right now.

---

Ultimately i'd wish to lean on @anoadragon453 for opinion on this; I think that `/account_data/` should reflect the current state at any time, and that it does not interact or touch "if the device has seen it or not", since any access token would already be syncing if it sends `account_data` requests like this, since a client is expected to sync continuously when its online.

However, what about clients that are *offline*? Do we expect implementations to internally store tombstones to their stream tokens, to notify remaining access tokens of such a delete? Won't that go against the storage savings, or will it increase performance as it only queries a "small" table every time such a sync happens, to search for such tombstones?

What if a client re-uses an old sync token, after it has restarted sync, or used an additional sync? This behaviour is undefined, and with the case of deleting data, even the reference of itself that it *has* been deleted, it might become problematic.

And i concur with @richvdh, this is not implementation-specific, as then different implementations will have different ways of specifying how and when data is deleted.

Imo, it should be tied to `/sync`, and `/account_data/` should always serve the current state, even if that results in a race condition between the two calls, as to which one returns the "this data has been deleted" state to the client first.

2023-11-27 21:14 UTC, turt2live commented
This is currently in need of a shepherd to get the MSC to the next steps. It's been proposed for FCP at least once already and got quite a bit of feedback: working through that feedback and sending it back to the SCT to send through FCP is what's required.

As the branch is on a contributor's fork, the shepherd would either need to be a member of the matrix-org github to push to the PR branch, ask the original author for access, or failing all of that open a new MSC so we can mark this one obsolete. 

Unfortunately there is no bandwidth within the SCT to do the shepherding required here.

If folks are interested in taking this on, please speak up and do so :)

2025-02-05 16:41 UTC, richvdh commented
This seems to be bitrotting, with no real interest from a maintainer. I also think it's overreaching somewhat: we have basically the same semantics in the ecosystem today, with clients explicitly setting account data to `{}` to effectively mean "deleted".

I'd like to propose this for closure.

@mscbot fcp close

2025-02-05 17:41 UTC, Johennes commented
Nullifying account data events by setting the content to `{}` definitely works. It does feel like a bit of a band-aid though. For instance, you technically cannot nullify [`m.marked_unread`](https://spec.matrix.org/v1.13/client-server-api/#mmarked_unread) because it contains a required field. While the lack of a proper deletion API does not annoy me terribly, it does feel a bit annoying that we're going from fcp merge to fcp close. 🫤

2025-02-05 17:46 UTC, clokep commented
> This seems to be bitrotting, with no real interest from a maintainer. I also think it's overreaching somewhat: we have basically the same semantics in the ecosystem today, with clients explicitly setting account data to `{}` to effectively mean "deleted".

This seems to conflict with just having merged MSC4133, which explicitly included a `DELETE` for profile fields. I see profile fields and account data as analogous, the first being public and the second private. It would be nice if these APIs would match.

I'm against on closing this on the merit it isn't useful. I can't speak to the bitrot or not though.

2025-02-06 12:13 UTC, richvdh commented
Honestly, the main reason for wanting to close it is that it seems to have been abandoned by its author, and apparently wasn't ready to merge. As such, it feels like distracting noise. I'm not in favour of a pattern where MSCs get started, implemented in some places, then abandoned, and we have to carry the mental load forever.

If anybody would like to take on pushing this forward, that would certainly be a better outcome than closing it, but given github's permissions model, it's likely to require a new MSC in any case.

2025-02-07 17:06 UTC, clokep commented
@richvdh and I discussed more out of band and I think we're fairly close in our thoughts. Having proposals open with no one driving them is not super useful. If someone does want to drive this in the future they can open a new MSC or reopen this one: i.e. the closure is due to abandonment and not due to an unwanted feature.

2025-04-06 09:40 UTC, closed without merging