MSC: Individual room preview API
matrix-org/matrix-spec-proposals pull request #3429
Opened 2021-10-05 21:16 UTC by turt2live

2021-10-05 21:26 UTC, tulir commented on proposals/3429-individual-room-preview-api.md
> +# MSC3429: Individual room preview API
This seems very similar to [MSC3266](https://github.com/matrix-org/matrix-doc/pull/3266)

2021-10-05 21:32 UTC, turt2live commented on proposals/3429-individual-room-preview-api.md
> +# MSC3429: Individual room preview API
Gah, that never came up in research for people who have tried to do this exact thing.

2021-10-05 21:45 UTC, turt2live commented on proposals/3429-individual-room-preview-api.md
> +# MSC3429: Individual room preview API
have mentioned it as an alternative

2021-10-06 13:56 UTC, clokep commented
> I say this, because i think stripped-state (which is used in multiple places), compared to the summary mechanism (which is only used in MSC3266, and is its own mechanism), would allow for code re-use and a more standard way to approach this.

MSC3266 is based on MSC2946, which attempts to re-use the response [format of `/publicRooms`](https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-publicrooms).

Stripped state is only used for invites/knocking IIRC.

Please use threads. :)

2021-10-06 15:29 UTC, turt2live commented on proposals/3429-individual-room-preview-api.md
> +## Alternatives
What if we just use the spaces summary? https://github.com/matrix-org/matrix-doc/pull/3266#discussion_r686213648

2021-12-06 17:07 UTC, KitsuneRal requested changes
As a client author, I like #3266 shape more - as its author states, it is easier to extract data specifically for the room preview case, even if at the expense of having to add fields to yet another endpoint whenever the stripped state definition gets extended. Compared to that MSC, the current MSC looks like half-way to room peeking. I'd rather use peeking to get a richer/live preview if that provided by #3266 (or hereby) is not enough; but I don't see a lot of value in full-blown stripped state events to address a simpler preview case. The wider interface calls for unneeded questions like whether it's the same stripped state returned by `/sync` for invited rooms and if yes, should `unsigned/prev_content` also be returned - all those rather answered by the peeking MSC.

Update: copied to the relevant thread.

2021-12-06 17:21 UTC, KitsuneRal commented on proposals/3429-individual-room-preview-api.md
> +## Alternatives
As a client author, I like #3266 shape more - as its author states, it is easier to extract data specifically for the room preview case, even if at the expense of having to add fields to yet another endpoint whenever the stripped state definition gets extended. Compared to that MSC, the current MSC looks like half-way to room peeking. I'd rather use peeking to get a richer/live preview if that provided by #3266 (or hereby) is not enough; but I don't see a lot of value in full-blown stripped state events to address a simpler preview case. The wider interface calls for unneeded questions like whether it's the same stripped state returned by `/sync` for invited rooms and if yes, should `unsigned/prev_content` also be returned - all those rather answered by the peeking MSC.

2022-07-19 15:03 UTC, closed without merging