MSC3510: Let users kick/ban/demote each other
matrix-org/matrix-spec-proposals pull request #3510
Opened 2021-11-20 22:50 UTC by ara4n

2021-11-22 09:39 UTC, anoadragon453 commented on proposals/3510-let-users-kick-each-other.md
> +spec?) to allow users to kick, ban or demote other users with the same power
Event auth rules are specified per room version: https://spec.matrix.org/v1.1/rooms/v7/#authorization-rules

2021-11-22 11:23 UTC, Mikaela reviewed
> Clients must clearly educate users about the change in behaviour to avoid nasty surprises.

I totally agree on that part, but still have concerns on this being quite drastic change and I think education on what changes between room versions is lacking to users in general as the room version tends to be hidden.

I imagine discovering there are 10 different kinds of rooms in the wild can come as a confusing surprise especially to less technical users who simply wish to have their community on Matrix.

2021-11-22 11:23 UTC, Mikaela commented on proposals/3510-let-users-kick-each-other.md
> +granular PLs (e.g. setting lesser trusted admins to PL 99, if needed).  This
Should this also bring a recommendation for clients to allow creating a room with arbitary maximum power level which some people are doing during room creation with the API?

2021-11-22 11:23 UTC, Mikaela commented on proposals/3510-let-users-kick-each-other.md
> +this proposal and should be considered in a separate MSC.
Whenever I see words similar to this, I fear that a partial solution gets implemented and the rest of the solution is somewhere in the future to be someone else's problem and should something bad happen between partial and full solution, I fear the one suffering from it gets blamed by upstream.

2021-11-22 11:29 UTC, Mikaela commented
On this requiring a lot of education should this pass, there is documentation around such as GNOME's [Sovereignty on a Federated System: problems we faced on GNOME’s Matrix instance: Losing ownership](https://blog.ergaster.org/post/20210610-sovereignty-federated-system-gnome/#losing-ownership) which has prompted https://github.com/vector-im/element-web/issues/17634 and possibly a couple of other issues, which may lead into further confusion.

2021-11-22 12:02 UTC, Mikaela commented
> I imagine discovering there are 10 different kinds of rooms in the wild can come as a confusing surprise especially to less technical users who simply wish to have their community on Matrix.

The solution to this could be https://github.com/matrix-org/matrix-doc/issues/2564 and similar changes to deprecate the older room versions *first before this change* and having a proper flow for upgrading rooms instead of the current `/upgraderoom` which says it's an advanced operation that shouldn't be needed?

2021-11-22 15:12 UTC, dkasak commented on proposals/3510-let-users-kick-each-other.md
> +This lets users enact coups on each other, in exchange for empowering admins
There may be a further state resolution problem here which would prevent kicks/bans/demotion between two users of the same power level from ever becoming permanent.

The reverse topological power ordering (https://spec.matrix.org/unstable/rooms/v2/#definitions, 6th paragraph) specifies that such events are sorted according to power level of the sender. But if the power levels of the senders are equal, then `origin_server_ts` is used to resolve the tie. But `origin_server_ts` is spoofable by the homeserver.

So I think that if we have two admins A and M with equal power levels in a room, and M has their own homeserver, then we might not be able to have a hard guarantee that A is able to e.g. ban M. This is because when M sees the ban event, they can create another event with a lower `origin_server_ts` to e.g. ban A in return.

2021-11-22 15:20 UTC, ShadowJonathan commented on proposals/3510-let-users-kick-each-other.md
> +This lets users enact coups on each other, in exchange for empowering admins
What about event ID? Those are semi-random, right?

Though, I could imagine that is also spoof-able, given some more intensive iteration.

2021-11-22 16:18 UTC, aaronraimist commented on proposals/3510-let-users-kick-each-other.md
> +   of trust, compromise of their account)
A betrayal of trust or compromise of an account is exactly why it works like it currently does. After this proposal is implemented, if one admin has their account compromised or goes rogue they can permanently take over the entire room by kicking all the other admins out.

2021-11-22 16:21 UTC, aaronraimist commented on proposals/3510-let-users-kick-each-other.md
> +room).
I don't think this proposal is a good idea. It seems like even after this proposal is implemented, it still remains a human decision to make, but now you are adding on the additional burden on clients and users where some rooms will work very differently than other rooms.

Room creators already have the choice to set additional admins at lower power levels so they can kick them out if they go rouge. If you want to change the spec, I think a better change would be to just have clients recommend that new admins get set at PL90 or PL99. It doesn't seem worth it to entirely change how power levels work technically just to fix one human problem and cause another.

Like @Mikaela said
> still have concerns on this being quite drastic change and I think education on what changes between room versions is lacking to users in general as the room version tends to be hidden.
> I imagine discovering there are 10 different kinds of rooms in the wild can come as a confusing surprise especially to less technical users who simply wish to have their community on Matrix.

The only way I can see this working is if you fix room upgrades so they are completely transparent to the user and essentially every room automatically gets upgraded to every new version so they all appear to work the same way.

2021-11-22 17:22 UTC, ShadowJonathan commented on proposals/3510-let-users-kick-each-other.md
> +room).
> If you want to change the spec, I think a better change would be to just have clients recommend that new admins get set at PL90 or PL99.

Agreed, i think adding an extra "owner" "role" would help, while admins become PL 99 or such, and some major roles are also added at PL 99 (but not room upgrades, i think)

2021-11-22 17:28 UTC, zkat commented on proposals/3510-let-users-kick-each-other.md
> +room).
I like this better than the proposal, too.

2021-11-23 09:55 UTC, ara4n commented on proposals/3510-let-users-kick-each-other.md
> +This lets users enact coups on each other, in exchange for empowering admins
> This is because when M sees the ban event, they can create another event with a lower origin_server_ts to e.g. ban A in return.

I was assuming that we would need a change to state res to handle this.  Perhaps it would be sufficient to tiebreak in favour of the admin who created the room, if any?

2021-11-26 20:41 UTC, MTRNord commented on proposals/3510-let-users-kick-each-other.md
> +This lets users enact coups on each other, in exchange for empowering admins
What about adding a limitation that the room creator can't be demoted by any others? This would ensure that foreign admins cant takeover a room when getting hostile. I think that may be a reasonable limitation.

2021-11-27 00:24 UTC, Ai-rin commented
Back in Jabber days this behavior caused many troubles. One wrongly chosen admin could easily take over the entire chatroom.
The idea of separate owner field in m.room.power_levels sounds much better for me.

2021-11-27 00:27 UTC, MTRNord commented on proposals/3510-let-users-kick-each-other.md
> +This lets users enact coups on each other, in exchange for empowering admins
Also as @deepbluev7 mentioned this to me it might make sense to have this somewhere in a state event defined as there may at some point be a voted owner change of a room. So that would allow to protect some users if wanted.

2021-11-27 02:29 UTC, 274below commented
I am coming from this perspective: matrix-org/synapse#11433

Broadly speaking, there needs to be a way to kick (or demote) maximum-level accounts. My driver is technical: there's an admin (priv 100) account in a room that is associated with a server that doesn't really exist anymore. As a result of the current setup, it literally cannot be removed from the room. This is a technical problem that needs to be fixed through technical means (in the form of either this or some other MSC).

Fundamentally, there always needs to be an "owner" role that has complete access to the room, and that needs to include the ability to manage who is/is not in that "owner" role.  Anything short of this introduces long-term technical gaps, which are a problem today (which is something that I'm trying to solve for my setup).

There's a lot of discussion here about the social dynamics of allowing room owners the ability to kick other room owners as well as the potential for abuse. Every time I try to address that point here I wind up writing something of a novel that I eventually wind up deleting. So, instead of trying to address every little point that has been brought up in the above comments, I will simply say that I personally view the potential for abuse in the form of room takeovers to be approximately equal to scenarios where an abusive individual _cannot_ be removed. What's worse: a scenario where a hostile individual takes a room over and makes whatever seemingly malicious changes they wanted to make, or a scenario where a hostile individual who cannot be kicked opts to just delete everything?

I don't think there's necessarily a right answer to which scenario is worse, and I don't see a lot of value in trying to figure it out because the end result is exactly the same with or without this MSC. Without this (or a similar) MSC, priv 100 accounts can just delete the content, rendering the room unusable. With this MSC, priv 100 accounts can evict anyone/everyone that they don't like. Trying to weigh "unusable room due to admin abuse variant A" against "unusable room due to admin abuse variant B" is meaningless when the end result is still "unusable room due to admin abuse."

With all of that said, maybe a middle ground would be only allowing accounts with priv 100 access to either kick or demote (thus allowing a kick) each other; any other level of access below 100 should not be allowed to kick (or demote) accounts with the same (or higher) levels of access. This would minimize the potential for down-level abuse, and provide room owners with a technical means of solving technical problems.

2021-11-27 04:04 UTC, kfiven commented on proposals/3510-let-users-kick-each-other.md
> +room).
> 

Second that, we also added something like that in Cinny when room creator can assign themselves "Founder (PL 101)". We added this to solve problem with appservice because it was kicking matrix users for idling but IMO it would also work in cases like this.

2021-11-29 08:17 UTC, MayeulC commented on proposals/3510-let-users-kick-each-other.md
> +This lets users enact coups on each other, in exchange for empowering admins
Wouldn't that be vulnerable to a Sybil attack? I think that would be very easy to abuse.

2021-11-29 08:23 UTC, MayeulC commented on proposals/3510-let-users-kick-each-other.md
> +room).
I agree that having a "super-admin"/"owner"/"creator" role sounds like a better alternative. Many other chat systems work like this without obvious downsides. If other admins need to migrate (owner unresponsive), they can @room and ask room members to move, while changing topic and room alias.

Maybe that would be a good occasion to revisit one of the many role-based membership systems like  #3073?

2021-11-29 13:21 UTC, richvdh commented
@Mikaela, @Ai-rin, @274below: please remember to make any comments on the "files changed" tab (https://github.com/matrix-org/matrix-doc/pull/3510/files), otherwise it becomes impossible to track which comments are still relevant.

I'll go through and hide the unthreaded comments so if you still feel your comments are valuable, please re-make them on the "files changed" tab.

2021-11-29 13:39 UTC, Mikaela requested changes
Merging two still relevant comments after https://github.com/matrix-org/matrix-doc/pull/3510#issuecomment-981629284.

2021-11-29 13:39 UTC, Mikaela commented on proposals/3510-let-users-kick-each-other.md
> +about the change in behaviour to avoid nasty surprises.
On this requiring a lot of education should this pass, there is documentation around such as GNOME's [Sovereignty on a Federated System: problems we faced on GNOME’s Matrix instance: Losing ownership](https://blog.ergaster.org/post/20210610-sovereignty-federated-system-gnome/#losing-ownership) which has prompted https://github.com/vector-im/element-web/issues/17634 and possibly a couple of other issues, which may lead into further confusion.

* * * * *

> I imagine discovering there are 10 different kinds of rooms in the wild can come as a confusing surprise especially to less technical users who simply wish to have their community on Matrix.

The solution to this could be https://github.com/matrix-org/matrix-doc/issues/2564 and similar changes to deprecate the older room versions *first before this change* and having a proper flow for upgrading rooms instead of the current `/upgraderoom` which says it's an advanced operation that shouldn't be needed?

2021-12-03 01:40 UTC, Ai-rin commented on proposals/3510-let-users-kick-each-other.md
> +This lets users enact coups on each other, in exchange for empowering admins
>What about adding a limitation that the room creator can't be demoted by any others? This would ensure that foreign admins cant takeover a room when getting hostile. I think that may be a reasonable limitation.

The room creator might want to transfer ownership or define backup owners, otherwise it will create a single point of failure.

2021-12-03 02:23 UTC, turt2live requested changes
sorry, it took me far too long to circle around to a composer to type this out.

I believe others have covered sentiments of the comments here, but just in case I've started a new thread.

2021-12-03 02:23 UTC, turt2live commented on proposals/3510-let-users-kick-each-other.md
> +# MSC3510: Let users with the same power level kick/ban/demote each other.
I'm very concerned with the principle of this proposal and how it affects DMs specifically. Element, one of the larger clients operating on top of the protocol, has a banner which says "Own your conversations" - I don't think this proposal would uphold that, and believe the banner is a sentiment we should maintain in Matrix.

Allowing admins to demote or remove other admins from a conversation means that DMs can have their opponent forced out, effectively losing control of the conversation history. While demoting other admins in public and semi-public rooms is justifiable, DMs, semi-private, and private rooms are semantically different to casual users. Professional and similar settings are likely to be able to work out their differences offline, however in small communities and groups power struggles are likely to be more common if supported. In particular, I'm worried about a user's ability to retain a copy of DMs for potential legal or personal record keeping - if they don't operate the homeserver (ie: reside on matrix.org), then they'll most likely have to go routes of subpoenas or GDPR subject access requests. 

I would be comfortable if this proposal scoped itself to public and semi-public (knockable, restricted) rooms, but deliberately did not operate in invite-only private rooms and DMs.

2021-12-03 07:34 UTC, su-ex commented on proposals/3510-let-users-kick-each-other.md
> +# MSC3510: Let users with the same power level kick/ban/demote each other.
Basically I agree, I wanted to raise this issue with DMs as well, but:
> I would be comfortable if this proposal scoped itself to public and semi-public (knockable, restricted) rooms, but did not operate in invite-only private rooms and DMs.

What does prevent somebody from making a private room public and then apply the mechanics of this MSC?

There's also the valid usecase that something starts as DM and then you invite more and more people. If you want at some point be able to make the room public, it's possible to make it public as well. This flexibility is great and anything that hinders the conversion of DMs into public rooms, which will make the protection of DMs possible at all, will restrict this flexibility or the protection of DMs is a toothless tiger if this MSC applies.

2021-12-03 07:41 UTC, turt2live commented on proposals/3510-let-users-kick-each-other.md
> +# MSC3510: Let users with the same power level kick/ban/demote each other.
More complicated DMs that start to involve more people are probably best covered by one of the DM-specific MSCs. As far as this MSC is concerned, a DM is just a private room that happens to be tagged as such.

There's also a point where the protocol can't really help or protect the users from themselves, such as deliberately making a room public just to demote others. Power levels can be configured ahead of time to prevent that in DMs, and the mechanism could try to distinguish between maliciously public and public (possibly some sort of dedicated state event which controls how the power level behaviour operates?). This quickly turns into having too many options, though.

2021-12-03 12:20 UTC, dkasak commented on proposals/3510-let-users-kick-each-other.md
> +complaints.
FWIW, I agree with the above reasoning regarding ownership and I think this may be the best way to move forward.

2021-12-03 12:22 UTC, dkasak commented on proposals/3510-let-users-kick-each-other.md
> +This lets users enact coups on each other, in exchange for empowering admins
> What about event ID? Those are semi-random, right?

Yes, probably spoofable if someone was intent on doing it. Apart from that, resolving into a random but deterministic direction doesn't feel very satisfying.

> I was assuming that we would need a change to state res to handle this. Perhaps it would be sufficient to tiebreak in favour of the admin who created the room, if any?

I guess that would be one way of solving it but I think [this](https://github.com/matrix-org/matrix-doc/pull/3510#discussion_r761836336) may be a better solution in this vein.

2021-12-03 12:27 UTC, dkasak commented on proposals/3510-let-users-kick-each-other.md
> +other (given the default thresholds for kick/ban/demote are 50, which by
Are you talking about something different than [what I raised here](https://github.com/matrix-org/matrix-doc/pull/3510/files#r754371247)? It feels like we're talking about the same issue.

2021-12-03 14:12 UTC, aaronraimist commented on proposals/3510-let-users-kick-each-other.md
> +complaints.
Sounds perfectly reasonable to me. The only reason I suggested 90 (or 99) is that it is backwards compatible with existing rooms. >100 would only work in new rooms since you can't promote above the highest existing power level.

2021-12-03 15:08 UTC, ShadowJonathan commented on proposals/3510-let-users-kick-each-other.md
> +other (given the default thresholds for kick/ban/demote are 50, which by
Ah, yes, sorry then :sweat_smile:

Then this thread can be resolved.

2021-12-04 00:26 UTC, deepbluev7 commented on proposals/3510-let-users-kick-each-other.md
> +complaints.
You need a new room version anyway, so it doesn't really matter if you are compatible with existing rooms. Also, rooms can arbitrarily redefine power_levels. I have a few with admins at 2^52. So this probably just needs an extra permission in power_levels and redefinition of the default PL event in new room versions.

2021-12-04 10:33 UTC, Cadair commented on proposals/3510-let-users-kick-each-other.md
> +complaints.
> You need a new room version

Why do you need a new room version to change the default PLs for new rooms?

2021-12-04 13:17 UTC, deepbluev7 commented on proposals/3510-let-users-kick-each-other.md
> +complaints.
> Why do you need a new room version to change the default PLs for new rooms?

Ah, right, this thread is about none ever being able to kick anyone else with the same PL. I thought that was still pursued, my bad.

2021-12-18 23:38 UTC, kevincox commented on proposals/3510-let-users-kick-each-other.md
> +This lets users enact coups on each other, in exchange for empowering admins
Personally in general I think it is fine that the kicked admin can react by spoofing an event to ban the banner first. However I think this is only ok if it is time-limited. The reason for this is that I don't see much difference between the reactionary ban and the proactive ban. I don't see why we should be committed to ruling in favour of quick-draw. However it say after 24h we could guarantee that the current resolution stuck then it seems that it would be fine for "peaceful" step-downs as the state is now stable.

Unfortunately I don't think we have any mechanism for this in the protocol. The only thing I can think of is allowing other users to "vouch" for the time that they saw the message. However backdating various sorts of events results in this breaking in all sorts of horrible and confusing ways into the future.

I think the only option left is majority vote. If you want to demote someone at the same power-level as you you must get more than half of the users at the same level to agree. But even that is vulnerable to backdating a promotion or invite.

2022-01-08 09:00 UTC, timokoesters commented on proposals/3510-let-users-kick-each-other.md
> +This lets users enact coups on each other, in exchange for empowering admins
> This is because when M sees the ban event, they can create another event with a lower origin_server_ts to e.g. ban A in return.

There are multiple other ways they could exploit this. E.g. In the fork they invite a new user and give them admin rights. The new user will make it into the resolved room state.
Then the new user can just unban the other user again.

2022-01-31 17:06 UTC, joshqou commented on proposals/3510-let-users-kick-each-other.md
> +complaints.
This MSC creates significantly bigger problems than it solves.

### Current Problems

#### Dead Admins
While it is annoying to have admins of dead homeservers clogging up your power level state, it's something that is easily solved by upgrading or tombstoning the room. This is a solution that many room admins already implement, and are fine with.

#### Compromised Admin Users
With the current power level behaviour, other room admins would retain their permissions until the original admin either regains control of his account, or the account is deactivated. From that point a room admin can tombstone the room to redirect users to a new room, or clean up the timeline and continue using the existing room if no destructive states were set.

#### "Admins quite reasonably expect to have full control over their room - much as root has full control on UNIX"
Even as `root`, there are some things you can't do. User misunderstandings lie on the client to resolve, not the spec.

### Introduced Problems

#### Hostile Takeovers
Compromised admin accounts being able to enact hostile takeovers on rooms, giving their actual account admin, then de-opping the compromised admin account.

#### "Moderators" being able to ban other Moderators
This is behaviour that room admins are not going to expect, and aren't going to want.

#### Breaking Convension
Room admins are already familiar with the current "greater than" power level behaviour. If new users do not understand that giving a user PL 100 makes them the co-owner of the room, then the fault lies on the client for not properly signalling to them that's what that does.

#### Breaking Convension from all previous room versions
This MSC makes breaking changes to `m.room.power_levels`, and would prevent rooms from being cleanly upgraded.

#### Forcing changes for direct rooms
Direct rooms are currently created with co-ownership, a solution to retain current behaviour in direct rooms would need to be created.

#### Giving Admin becomes a Liability
Op'ing other users would become a liability given they act in malice or have their account compromised, as such an event could lead to a hostile takeover of the room. This could dissuade room admins from giving other users admin, and would make the current "dead admin" problem worse in the long run for smaller rooms.

#### Giving Moderator becomes a Liability
As moderators would be able to ban other moderators, one compromised or malicious moderator could ban all other moderators to allow a raid or spam attack to go unopposed. This could dissuade room admins from giving multiple users moderator permissions.

---

This is frankly not a good idea. The problems mentioned to justify this change already have existing solutions, such as tombstoning.

2022-04-12 08:27 UTC, Mikaela commented on proposals/3510-let-users-kick-each-other.md
> +complaints.
> Dead Admins
> While it is annoying to have admins of dead homeservers clogging up your power level state, it's something that is easily solved by upgrading or tombstoning the room. This is a solution that many room admins already implement, and are fine with.

This has been discussed a bit in Feneas room recently. The room upgrade or tombstone in case of `/upgraderoom` copies the current event and to not carry the legacy event over, one has to perform a manual room upgrade, which I don't think is supported by any client directly, and which I worry would bring even more elitism ignoring non-technical users.

The threat model is that should a domain with administrator powers fall to wrong hands, they can take over rooms by creating accounts that have power as apparently federation key isn't required alongside controlling domain. This may however tie in with https://github.com/matrix-org/synapse/issues/3765 which probably should have a mechanism for invalidating the power levels from intentionally dying homeserver. Then again that issue doesn't cover cases like where `privacytools.io` homeserver administrators lost control over the domain instead of a graceful shutdown.

2022-10-23 10:33 UTC, ara4n commented
@mscbot fcp close

In retrospect I hadn't thought this through properly at all - thanks all for the constructive review.  I've opened #3915 as a replacement, which looks to almost entirely match @su-ex's comment at https://github.com/matrix-org/matrix-spec-proposals/pull/3510#discussion_r761836336.

2022-10-24 09:54 UTC, richvdh commented
The "fcp close" process is normally used when we decide to close someone else's proposal. Since @ara4n is the author, we don't need an FCP on closing this.

2022-10-24 09:54 UTC, closed without merging

2022-10-24 19:14 UTC, turt2live commented
@mscbot fcp cancel

just to clean up the state machine