"Mention" Pushrule
matrix-org/matrix-spec-proposals pull request #3517
Opened 2021-11-21 19:04 UTC by ShadowJonathan

2021-11-21 23:17 UTC, uhoreg commented
I've marked this as `kind:maintenance` because it feels to me like just an update to push rules, rather than a new feature.  But someone who's more familiar with push rules can feel free to disagree with me and change it to `kind:feature`.

2021-11-21 23:40 UTC, deepbluev7 commented on proposals/3517-mention-pushrule.md
> +or `content.formatted_body`.
This should probably clarify, how the mxid is found.

- Is a percent encoded mxid in a matrix.to link a match?
- What about matrix URIs?
- What about trailing `:` or `.`?

2021-11-22 01:10 UTC, ShadowJonathan commented
> I've marked this as kind:maintenance

It was completely intended like that, thanks enough though.

2021-11-22 12:06 UTC, richvdh commented
related: #1549, #2463

2021-11-22 12:18 UTC, richvdh requested changes
maybe. Updating the default push rules is a lot harder than just adding a new rule - you've only thought about the easy bits ;)

2021-11-22 12:18 UTC, richvdh commented on proposals/3517-mention-pushrule.md
> +This proposal aims to change that, adding the following push rule;
```suggestion
This proposal aims to change that, adding the following default push rule:
```

2021-11-22 12:18 UTC, richvdh commented on proposals/3517-mention-pushrule.md
> +This proposal aims to change that, adding the following push rule;
I think we can guess, but where in the list of [predefined push rules](https://spec.matrix.org/v1.1/client-server-api/#predefined-rules) should this be inserted?

2021-11-22 12:18 UTC, richvdh commented on proposals/3517-mention-pushrule.md
> +This proposal aims to change that, adding the following push rule;
... and do we keep or get rid of the existing mention rules?

2021-11-22 12:18 UTC, richvdh commented on proposals/3517-mention-pushrule.md
> +This proposal aims to change that, adding the following push rule;
we need to specify a whole lot of detail about migrations:
 * what should servers do for existing users? should they add the new rule in, or not? if so, should they consider whether the user has changed the default settings for other rules?
 * How should a client behave when it encounters a user without the new rule? It may depend on whether the server supports the new rule or not.
 * How should the server behave when a client tries to modify the existing displayname/localpart mention rules? should it magically update the new rule?

2021-11-22 12:51 UTC, ShadowJonathan commented on proposals/3517-mention-pushrule.md
> +This proposal aims to change that, adding the following push rule;
Imo, keep the existing mention rules (displayname, username), as i know they're quite useful for some other users, this is just about adding additional options. We can bikeshed about un-defaulting them or disabling them later.

2021-11-22 12:55 UTC, ShadowJonathan commented on proposals/3517-mention-pushrule.md
> +This proposal aims to change that, adding the following push rule;
Good point, the conservative approach would be to disable this, and let clients detect and auto-enable this.

However, that would just shove the problem to clients, and it doesn't tell anything about what if client A doesnt "know" this push rule, and B does, and enables it.

The alternative (just enabling this) would exacerbate the above problem.

---

I think, this being default-on (atm), that the server should just enable this once it encounters a user without this push-rule installed, be it that it lazily detects this upon push-rule changes, or as a background job when booting into the new version.

I *do* think that, if this was enabled while unstable, the server should first try to migrate over the unstable prefix, instead of defaulting and auto-enabling (as it could be quite annoying for some users)

Or, while the rule is unstable, the rule should be non-default, this could give a grace period in which clients and servers learn of this rule, before it switches to stable and becomes default-on.

2021-11-22 13:04 UTC, ShadowJonathan commented on proposals/3517-mention-pushrule.md
> +or `content.formatted_body`.
Extremely good points, i think that this kinda touches onto the "hackiness" of this approach, as indeed a user with the following MXID could be still pinged by the other following one;

`@user:example.com`

could be pinged by

`@user:example.com.loldomain.top`

if this is a simple substring match.

---

Also, `@user:example.com` could be pinged by `@user:example.com:21398`.

---

Some clients, yes, may even be "dumb" and percent-encode the above into `%40user%3Aexample.com`, which wouldn't match the direct MXID.

---

The problem, however, is that for any alternative, the server may have to do a bit more effort and HTML-parse the `formatted_body` part to extract `<a>`, which i don't think is a viable alternative (pinging @richvdh and @clokep for SCT opinion here).

---

Matrix URIs would be `matrix:u/user:example.com`, which'd miss the `@user:example.com` match.

---

A "good" solution to this would be to change the behaviour to be;
- Match MXID on `content.body`
- If `content.format == "org.matrix.custom.html"`;
  - parse `content.formatted_body` as HTML, extract `<a>` tags, and see if `href` matches a `matrix.to` user link, or a user ref via the `matrix:` URI scheme
  - if so, extract MXID, compare in full to the user.
  
However, this is considerably more overhead, and i'm not sure if that is completely acceptable. In return, you'll get a reliable explicit-user-mention condition though.

2021-11-29 08:27 UTC, MayeulC commented on proposals/3517-mention-pushrule.md
> +or `content.formatted_body`.
I note that as @example:example.com, clients often ping me when @someoneelse:example.com talks are replied to or mentioned in the room.

2021-11-29 09:32 UTC, ShadowJonathan commented on proposals/3517-mention-pushrule.md
> +or `content.formatted_body`.
@MayeulC Yeah, that would be the "username" notification pushrule matching on the domain, that false-positive situation is what this MSC is trying to resolve.

2022-01-26 11:12 UTC, ShadowJonathan commented on proposals/3517-mention-pushrule.md
> +or `content.formatted_body`.
Note; I should also incorporate and mention extensible events as a part of this, as they add `m.html` andsoforth

2022-01-29 18:57 UTC, ShadowJonathan commented on proposals/3517-mention-pushrule.md
> +or `content.formatted_body`.
I've addressed these concerns in the newest version of the document

2023-01-08 14:38 UTC, ShadowJonathan commented
I want to deprecate this MSC in favour of MSC3952.

This MSC wasn't ever meant to fully solve the problem, but to wedge a solution in that would alleviate a large annoyance today, but I see MSC3952 solving this problem completely. Secondly, MSC3952 also templates exactly what I saw in a "follow up" or "more serious" MSC after this one, so having this superseded in favour of it is logical.

2023-01-08 14:38 UTC, closed without merging