WIP: MSC3575 Sync v3
matrix-org/matrix-spec-proposals pull request #3575
Opened 2021-12-20 10:47 UTC by kegsay

2021-12-21 00:49 UTC, ara4n commented on proposals/3575-sync.md
> + - Core API: The minimumal API to be sync v3 compatible.
```suggestion
 - Core API: The minimal API to be sync v3 compatible.
```

2021-12-21 00:50 UTC, ara4n commented on proposals/3575-sync.md
> +operation can take minutes to perform. This significantly delays the initial login to Matrix clients.
```suggestion
operation can take minutes to perform. This significantly delays the initial login to Matrix clients,
and also makes incremental sync very heavy when resuming after any significant pause in usage.
```

2021-12-21 00:51 UTC, ara4n commented on proposals/3575-sync.md
> + - Ability to filter by space.
we should probably retcon that we were aiming also to support filtering by room name....

2021-12-21 00:54 UTC, ara4n commented on proposals/3575-sync.md
> +token cannot be used with other APIs such as `/messages` or `/keys/changes`.
"how do we sync /messages to the current timeline then?", asked the naive reader...

2021-12-21 01:08 UTC, ara4n commented on proposals/3575-sync.md
> +For complex nested data, APIs which include sticky parameters MUST indicate every sticky field to
but how do you indicate that a parameter is sticky?

2021-12-21 01:13 UTC, ara4n commented on proposals/3575-sync.md
> +        // Request the join rules event. Note that the empty string is required here.
```suggestion
        // Request the join rules event. Note that the empty string is required here to match the event's blank state_key.
```

2021-12-21 01:20 UTC, ara4n commented on proposals/3575-sync.md
> +of the timeline". The rationale for this was event duplication and the fact that clients would have
i think the rationale for sync v2's behaviour was actually that clients render timelines from old to new (given that's the direction time flows, and new events need to be appended).  Therefore when you get a new batch of messages, you need to know what the state is at the beginning of that batch in order to render the subsequent messages correctly.  Forcing the client developer to 'rewind' state every time it gets a batch of messages in order to then play it forward again (or apply it in reverse) is a needlessly awkward contortion for them to jump through, and it's avoidable.

I don't remember or follow the rationale about event duplication?

2021-12-21 01:22 UTC, ara4n commented on proposals/3575-sync.md
> +need to do) or worse, do an expensive database access to request the state before an event._
I'm not sure I follow why it's harder for a server to cache the state at the beginning of a batch than at the end of a batch?

2021-12-21 01:25 UTC, ara4n commented on proposals/3575-sync.md
> +#### Extensions
might make sense to split this and the subsequent extensions into separate MSCs for digestibility

2021-12-21 01:26 UTC, ara4n commented on proposals/3575-sync.md
> +## Security considerations
- incompatibility with encrypted room names, topics and user displaynames - given we need to be able to sort lexicographically and filter based on room name.

2021-12-21 12:36 UTC, kegsay commented on proposals/3575-sync.md
> +token cannot be used with other APIs such as `/messages` or `/keys/changes`.
No, it wasn't. /sync v1 included the start/end tokens for use with `/messages` - https://spec.matrix.org/latest/client-server-api/#get_matrixclientv3initialsync

2021-12-21 12:41 UTC, kegsay commented on proposals/3575-sync.md
> +need to do) or worse, do an expensive database access to request the state before an event._
Because the state at the beginning of a batch is variable. Alice, Bob and Charlie may all be at different points in the stream for the same room. To "cache" this then you either need to cache every possible state or track every single position for each client for each room, both of which are impractical.

2021-12-21 13:21 UTC, ara4n commented on proposals/3575-sync.md
> +cache every single possible earlier state for each room._
surely servers need to constantly cache and retrieve earlier states for each room as part of authing events, every time you get an event with a parent that isn't an extremity?

2021-12-21 14:07 UTC, t3chguy commented on proposals/3575-sync.md
> +The lifetime of sticky request parameters are tied to a sync connection. When the connection is lost,
For the long-polling use case the `pos` token is ephemeral and can be invalidated by the server at any time, thus ending the sync connection and beginning a new one. This sounds like it'd lose any sticky request parameters and thus return an initial sync which does not have the data the client may be expecting due to lost sticky request parameters.

Also given that most HTTP2 sockets/sessions will be terminated at a load balancer, how will servers even know when the connection is closed?

2021-12-21 14:09 UTC, t3chguy commented on proposals/3575-sync.md
> +   total number of unread notifications for this room. This value is also present in sync v2.
How will this work with E2E rooms where you don't know whether something is a notification before decrypting it, in /sync v2 the notification count had a much lower importance and would be decreased by the client when it confirmed that an encrypted message didn't contain a payload which wants a notification. But now with its importance increasing it may cause bigger impacts.

2021-12-21 14:13 UTC, t3chguy commented on proposals/3575-sync.md
> +        "spaces": ["!foo:bar", "!bar:baz"],
How would this work for DMs in Spaces? The behaviour for DMs in Spaces today is as follows:

Show DMs you have with members of the space (membership = join/invite)
IFF you did not opt-out of this at the space level

![image](https://user-images.githubusercontent.com/2403652/146944163-cfeebacd-c76b-4eaf-96d7-fbebb254f3c9.png)

2021-12-21 14:14 UTC, t3chguy commented on proposals/3575-sync.md
> +        // returned.
So clients would still need to sync all spaces, which would grow linearly with number of spaces they are in, which seems to go against one of the core goals of this MSC

> Sync time should be independent of the number of rooms you are in.

2021-12-21 14:15 UTC, t3chguy commented on proposals/3575-sync.md
> +        // user, ensure that there is a parent space event which is in this list. If unset, all
Element clients show invited rooms as belonging to the space too

2021-12-21 14:16 UTC, t3chguy commented on proposals/3575-sync.md
> +      "filters": {
how would things like Element's Home, Favourites, Orphans "meta spaces" work with the given filters?

2021-12-21 14:59 UTC, kegsay commented on proposals/3575-sync.md
> +   total number of unread notifications for this room. This value is also present in sync v2.
This is explained in the E2EE section.

2021-12-21 15:01 UTC, t3chguy commented on proposals/3575-sync.md
> + - `by_name`: Sort by room name lexicographically. This requires servers to implement the
This might block any future efforts to encrypt room state e.g name

2021-12-21 15:05 UTC, kegsay commented on proposals/3575-sync.md
> +cache every single possible earlier state for each room._
Yes, and this is expensive. Servers can offload this to sharded room server components, and this works well because the work is per-room. Servers become very difficult to optimise if synchotrons/sync servers need to do the same operation (expensive per room operations on a per-user sharded process).

2021-12-21 15:08 UTC, kegsay commented on proposals/3575-sync.md
> +The lifetime of sticky request parameters are tied to a sync connection. When the connection is lost,
> This sounds like it'd lose any sticky request parameters and thus return an initial sync which does not have the data the client may be expecting due to lost sticky request parameters.

This is a good point. We might need to force a RTT to ensure clients send up their request parameters in full again.

> Also given that most HTTP2 sockets/sessions will be terminated at a load balancer, how will servers even know when the connection is closed?

Connection != TCP connection here, so load balancers aren't a concern. The concept of a sync connection is just the presence of `pos` for a specific access token. `pos`'s absence indicates a new connection and the closure of any currently active connection for that access token.

2021-12-21 15:11 UTC, kegsay commented on proposals/3575-sync.md
> +        "spaces": ["!foo:bar", "!bar:baz"],
No idea to be honest. The sync API isn't going to match perfectly whatever Element wants to do. It sounds like you could emulate this by having `is_dm: true` to pull all DMs then client-side filter based on the `m.room.member` state event of the spaces you're interested in showing DMs from.

2021-12-21 15:16 UTC, kegsay commented on proposals/3575-sync.md
> + - `by_name`: Sort by room name lexicographically. This requires servers to implement the
Indeed, and there is mention of this currently in the security considerations which I will flesh out when the MSC is ready for review. When this was brought up during the design process for Sync v3, the basic conclusion was to punt it for later and hope that some sort of homomorphic encryption might allow us to sort the ciphertext in the future.

2021-12-21 15:27 UTC, kegsay commented on proposals/3575-sync.md
> +      "filters": {
In short, I don't know. I'm reluctant to include specific filters and functionality for whatever the current Element UI/UX is because:
 - Element isn't the only client.
 - The UI/UX is in flux, so what is here today may be gone tomorrow which would suck if sync v3 has explicit filters/options for esoteric options which no longer exist.

These points apply to many other Matrix clients as well. An earlier design for Sync v3 for example did include support for Favourites (room tags) but that was explicitly shut down as they really should be personal spaces or some such. I expect Element/Dittochat/Fluffychat/Hydrogen folks to push back on bits they care about, and then we can thrash out what needs to be added to make that UI/UX possible in sync v3. However, when that is taken to the extreme we will inevitably end up with freeform sorting and filtering so it's unfortunately my position to try to maintain some semblance of consistency and simplicity with the resulting API. It would be a major own goal to end up with a slow API because of freeform sorting/filtering which was added to appease everyone.

2021-12-21 15:33 UTC, kegsay commented on proposals/3575-sync.md
> +        // returned.
I don't follow your logic here. If a user is present in 5 spaces for example, you surely wouldn't want to be viewing the room list for each and every space at once? Even more complex space hierarchies often hide rooms behind drop-down chevrons and the like, so the act of clicking on that would change the filters. I expect clients to be viewing 1 top-level space at any one time (which then may have N subspaces which may be collapsed or expanded) which fits this API design reasonably well.

2021-12-21 15:33 UTC, t3chguy commented on proposals/3575-sync.md
> +      "filters": {
Sure but then how would a client like EW make use of sync v3, it'd need to load all rooms to be able to populate the `Home` space given it has to resolve orphans, so first paint useful paint for logins of huge accounts would still be slow as heck

2021-12-21 15:34 UTC, kegsay commented on proposals/3575-sync.md
> +        // user, ensure that there is a parent space event which is in this list. If unset, all
Thanks, I'll update this to include invited|joined, and clients can then set `is_invite: false` if they don't want to see these rooms.

2021-12-21 15:38 UTC, t3chguy commented on proposals/3575-sync.md
> +        // returned.
No but then lets say I want to show the room list for Element Corp, I'd need to know all spaces I'm in to know which spaces make up Element Corp so that then I can pass them to this filter to get the rooms from those spaces, but I don't see an `is_space` filter to even just grab the spaces. 

Unless this wants me to walk the space breadth-first, having to build up this filter as I find more sub-spaces therein.

Filtering on a Space in Element clients includes `(?:grand-)*children`

2021-12-21 15:42 UTC, t3chguy commented on proposals/3575-sync.md
> +        // returned.
Also even regardless of the room list, to calculate the Notification Badges to show on the Space Panel in Element I'd need to have all the rooms there-in synced up so I can calculate accurate (E2EE included) badge counts

2021-12-21 16:49 UTC, kegsay commented on proposals/3575-sync.md
> +        // returned.
Yes at present you'd need to hit another API to know which spaces a client is part of. I can add in a `is_space` filter pretty easily, but this feels like it's stepping on the toes of the spaces hierarchy endpoint?

Badge counts for spaces was explicitly punted by @ara4n on the basis that the UI/UX was in flux - if they actually are summing all the rooms notif/highlight counts and are tracked in real-time that will add a huge amount of traffic to `/sync` for very little gain (badges changing from 78 to 79 unread messages for example). It's a huge amount of traffic because  literally _any_ event in those rooms will cause traffic to come down `/sync` which simply won't fly for low bandwidth clients even without the event content itself. Having a grey/red dot depending on the presence of unread notifs/mentions respectively seems like a decent trade-off bandwidth wise.

As for accurate E2EE badge counts, you almost certainly _don't_ want to do this as per this MSC mentioning:
 > Grab all the missed messages and see if any of them are highlights. Denial of service risk if there are thousands of messages.

2021-12-21 16:55 UTC, kegsay commented on proposals/3575-sync.md
> +      "filters": {
EW is a set of constantly moving goalposts, so realistically sync v3 would probably be used in more simple/stable (UI/UX wise) clients like Hydrogen first, as well as a long tail of smaller clients which don't have complex UIs but want the speed/bandwidth savings of sync v3.  When EW's UI/UX stops churning then that would be a good time to see what additions are necessary for it to work with sync v3. Obviously it isn't acceptable to make EW pull in all rooms just to populate orphans (so some sort of filter would work here, but it's less clear to know exactly what this filter should be until EW settles on a final UI/UX for spaces).

2021-12-21 21:44 UTC, t3chguy commented on proposals/3575-sync.md
> +        // returned.
> Badge counts for spaces was explicitly punted by @ara4n on the basis that the UI/UX was in flux

From the Spaces team I have certainly not heard any flux in that area whatsoever ftr

2021-12-22 13:12 UTC, ShadowJonathan commented on proposals/3575-sync.md
> +```js
suggestion: `json5` could work better with comment-annotated JSON than `js`, for all the usages in this document

2021-12-22 13:12 UTC, ShadowJonathan commented on proposals/3575-sync.md
> +- Annoyingly probably `/v4/sync`
Why not prefixed with `org.matrix.msc3575`? Rationale is missing.

2021-12-25 02:43 UTC, ara4n commented on proposals/3575-sync.md
> +token cannot be used with other APIs such as `/messages` or `/keys/changes`.
okay, but still, how do you correlate with /messages in v3?

2021-12-25 06:29 UTC, turt2live commented on proposals/3575-sync.md
> +  "pos": "5",
`pos` is a number in the proxy - should it be treated as a string?

2021-12-25 06:56 UTC, turt2live commented on proposals/3575-sync.md
> +        ["m.room.member", "*"]
as a lazy shortcut, it might be useful to have a character/symbol to denote "current user", or just have the API always assume the client wants to know the user's current membership. Eg: add `["m.room.member", "$current"]` by default

2021-12-28 00:50 UTC, ara4n commented on proposals/3575-sync.md
> +        {"sender":"@alice:example.com","type":"m.room.create", "state_key":"", "content":{"creator":"@alice:example.com"}},
Is the indenting deliberately wrong/inconsistent on these? i find myself getting distracted - should we just stick to 2-space-indents in the examples?

2021-12-28 00:52 UTC, ara4n commented on proposals/3575-sync.md
> +  "counts": [1337],
I wonder if 'counts' is the best term here - isn't it more a `length`?

2021-12-28 02:48 UTC, turt2live commented on proposals/3575-sync.md
> +  "counts": [1337],
or `total` to preserve the meaning of the number.

2021-12-28 16:47 UTC, ara4n commented on proposals/3575-sync.md
> +### Bandwidth optimisations for persistent clients
I think we should clarify how this interacts with lazy-loading members (#1227). The current wording seems to imply that required_state will include all members, which could be super wasteful and kill all the benefits of LL members?

2021-12-28 16:59 UTC, ara4n commented on proposals/3575-sync.md
> +`POST /v3/sync?pos=4`:
where has the timeout param gone?

2021-12-28 17:21 UTC, ara4n commented on proposals/3575-sync.md
> +side because they are required for sort operations on lists. The `required_state` is controversially
"required" state, past tense, makes it sound like this is the state required to process the response - i.e. the state at the beginning of the response, not the end.  What is the word 'required' up to here?  Wouldn't it be better to call it 'current state' or something?

2021-12-28 17:21 UTC, ara4n commented on proposals/3575-sync.md
> +  "room_subscriptions": {
shouldn't this be `subscribe_rooms` for symmetry with `unsubscribe_rooms`, and to make it clear that it's an action, rather than being a sticky list?

2021-12-28 17:54 UTC, ara4n commented on proposals/3575-sync.md
> +      "rooms": [ [0,99] ],
It feels weird that this describes a set of ranges, but is called `rooms` (which would imply it contained room IDs or room objects of some kind).  Shouldn't it be called `ranges`?

2021-12-28 18:04 UTC, ara4n commented on proposals/3575-sync.md
> +  "room_subscriptions": {
it's also weird that this is a hash of id->objects, but unsubscribe is a list of ids. might be cleaner to have them both be a list of objects?

2021-12-29 15:43 UTC, ShadowJonathan commented on proposals/3575-sync.md
> +  "room_subscriptions": {
> ...might be cleaner to have them both be a list of objects?

I'm not sure, `room_subscriptions`/`subscribe_rooms` semantically relates to `PUT` for me, while `unsubscribe_rooms` relates to `DELETE`, where convention is with `PUT` to push all data you'd want to "store", and with `DELETE` you only reference where you've put the data, and that you want to delete it.

2021-12-29 15:44 UTC, ShadowJonathan commented on proposals/3575-sync.md
> +side because they are required for sort operations on lists. The `required_state` is controversially
I'm proposing `state_view`/`state_subset`, as essentially sync is only returning a subset of state of the room, and this parameter is restricting it to that.

"Required" state threw me off the first time as well, but only because it qualified as a filter in my head, as then the room would be "required" to have X state before its synced, but that wasn't so.

2021-12-29 15:46 UTC, ShadowJonathan commented on proposals/3575-sync.md
> +  "counts": [1337],
Related: we should probably have a document somewhere in the spec repo that standardises these for these kinds of ambiguous identifiers, i.e. "between `len`, `length`, `total`, `num`, `count`, etc., which one should the matrix spec use?"

2021-12-29 15:48 UTC, ShadowJonathan commented on proposals/3575-sync.md
> +        ["m.room.member", "*"]
I think that has a potential to clash, why not a different value type? iirc anything other than a `string` is illegal as a state_key, so this shouldn't conflict.

2021-12-30 12:24 UTC, ara4n commented on proposals/3575-sync.md
> +  "pos": "5",
sounds like a proxy bug. the spec here is quite unambiguous that it should be an opaque string.

2021-12-30 12:24 UTC, ara4n commented on proposals/3575-sync.md
> +  "initial": true,
the `initial` field is undocumented, as far as i can see?

2021-12-30 12:40 UTC, ara4n commented on proposals/3575-sync.md
> +        ],
Do we not need the concept of a limited sync still still?

2021-12-30 12:45 UTC, ara4n commented on proposals/3575-sync.md
> +    "!sub1:bar": {
It feels a bit clunky and inconsistent that the room subs returns rooms as key-values keyed by room ID, but the sliding window list has them as a list of room objects.  If they were the same, then the implementation could use the same datastructure for both, i think?

2021-12-30 13:10 UTC, ara4n commented on proposals/3575-sync.md
> +      }
Are we missing a filter for showing historical rooms?

2021-12-30 14:30 UTC, ara4n commented on proposals/3575-sync.md
> +      }
...and showing knocked rooms?

2021-12-30 14:41 UTC, ara4n commented on proposals/3575-sync.md
> +token cannot be used with other APIs such as `/messages` or `/keys/changes`.
v2 sync has a `prev_batch` token; how does the same work in v3?

2021-12-30 14:51 UTC, ara4n commented on proposals/3575-sync.md
> +  "counts": [1337],
trying to implement this, i'm unclear on what the total actually is of - doesn't it make more sense if it's scoped to a given `list`? currently it's a global, which implies that it's just telling you the total number of rooms that are on the user's radar, which doesn't seem like a very useful thing to know.

2021-12-30 15:14 UTC, Dominaezzz commented on proposals/3575-sync.md
> +_not possible_ to invert the sort order (ASC vs DESC). This may be added to this MSC if there is a
Ah this somewhat answers my earlier question. I still don't know what the existing order is though; for the inversion that is.

2021-12-30 15:14 UTC, Dominaezzz commented on proposals/3575-sync.md
> +   The server MUST perform the following steps:
This somewhat answers my earlier question. I see below that clients that have more bespoke calculations will just not use this.

2021-12-30 15:14 UTC, Dominaezzz commented on proposals/3575-sync.md
> +        ["m.room.member", "*"]
Another literal here could be something like `"LAZY"`, which means, Only give me state events if the `state_key` matches the userId of any events returned in the room timeline.

2021-12-30 15:33 UTC, ShadowJonathan commented on proposals/3575-sync.md
> +        ["m.room.join_rules", ""],
It's technically a tuple of 2, but JSON doesn't know about tuples.

2021-12-30 15:58 UTC, Dominaezzz commented on proposals/3575-sync.md
> +        ["m.room.join_rules", ""],
Sure but I think using a JSON object is more correct.

2021-12-30 16:09 UTC, turt2live commented on proposals/3575-sync.md
> +        ["m.room.member", "*"]
Not all architectures allow for such an easy check. In my test implementation, it was so difficult that a symbol was used anyways: https://github.com/turt2live/matrix-bot-sdk/pull/189

Adding a second symbol to the spec is probably the wrong answer, but assuming the client wants to know about the membership event *always* isn't too much of a stretch I think.

2021-12-30 16:12 UTC, turt2live commented on proposals/3575-sync.md
> +  "counts": [1337],
it's the number of rooms which could be in the list. In the bot-sdk's test impl I use it to figure out how many ranges (windows) to ask for: https://github.com/turt2live/matrix-bot-sdk/blob/b04dcecfa99c183f51d3777ff00d0fc6b47ab4d4/src/syncv3/V3List.ts#L100

(though it's questionable that the bot-sdk asks for ranges - haven't quite figured out if there's performance/network gains to be had here)

2021-12-31 09:14 UTC, timokoesters commented on proposals/3575-sync.md
> +seems rather wasteful. Perhaps make it configurable?
Maybe we send an approximate count, like only two digits of precision (21 -> 21, but 1234 -> 1200)

2021-12-31 09:14 UTC, timokoesters commented on proposals/3575-sync.md
> +- Unsure how much data to expose (probably index position + notif/highlight counts?). If we do _counts_
Is the idea that we only send a little data and if the client wants to know more they can subscribe to the room?

2021-12-31 12:19 UTC, timokoesters commented on proposals/3575-sync.md
> +MUST be omitted (sending `initial: false` is wasteful).
MUST is extreme for no reason. Isn't SHOULD okay?

2021-12-31 12:27 UTC, timokoesters commented on proposals/3575-sync.md
> +A response for a given `pos` must be idempotent to account for packet loss. For example:
Why? If the client tried again that means it did not receive the previous update. Then it should be okay to send a 'better' update instead (e.g. if a user stopped typing, we can leave out that EDU)

2021-12-31 16:27 UTC, timokoesters commented on proposals/3575-sync.md
> + [H,A,B,C,D]  | <- DELETE[4], INSERT[0]=H--- |
What happens if you don't delete? If we say the list has a fixed size, then the client can figure out it must drop off the end.

2021-12-31 16:27 UTC, timokoesters commented on proposals/3575-sync.md
> + - `DELETE`: Remove a *single* entry. Often comes before an `INSERT` to allow entries to swap places.
How about a MOVE that does DELETE+INSERT in one operation? Also 'swap' is the wrong word here, because it will move all entries inbetween

2021-12-31 16:27 UTC, timokoesters commented on proposals/3575-sync.md
> +possible operations are:
I think the set of actions can be improved if we require that the list has a fixed maximum size and empty slots must be at the end.

2021-12-31 16:27 UTC, timokoesters commented on proposals/3575-sync.md
> +      "rooms": [
Why are the list ordering and the room updates coupled so much? This will lead to duplication if multiple lists contain the same rooms. Can we separate ordering and actual updates?

2022-01-03 13:41 UTC, timokoesters commented on proposals/3575-sync.md
> +      "rooms": [ [0,9], [20,29] ],
The only reason multiple windows are allowed is for some clients that display multiple windows at once. But those could just use multiple "lists".
This means the "rooms" field can describe just a single window (or it can be split into two fields like "start" and "amount").

2022-01-03 13:41 UTC, timokoesters commented on proposals/3575-sync.md
> +      "rooms": [ [0,9], [20,29] ],
This might lead to duplicate data for when the windows overlap. To fix this, we can separate list metadata and actual content. See https://github.com/matrix-org/matrix-doc/pull/3575/files#r777030851

2022-01-04 10:59 UTC, kegsay commented on proposals/3575-sync.md
> +        ["m.room.member", "*"]
What's the use case for wanting the m.room.member for the current user? I would have expected people to typically split `is_invite: true` and `is_invite: false` into different lists so you would know the membership based on context (which list the room is present in)?

2022-01-04 11:38 UTC, kegsay commented on proposals/3575-sync.md
> +  "counts": [1337],
Having the total room count is useful for clients to know how many rooms there are for figuring out how to size list views. It's also useful for bots/other clients if they just want to grab all rooms.

The total room count exists at the top level because there is no list scope - only ops (and each op is then scoped to a list).

Happy to rename this to `totals`.

2022-01-04 11:40 UTC, kegsay commented on proposals/3575-sync.md
> +### Bandwidth optimisations for persistent clients
Correct, there is no special lazy room member handling in this MSC yet. I suspect I would add this in as an extension as it's a custom filter effectively.

2022-01-04 11:40 UTC, kegsay commented on proposals/3575-sync.md
> +`POST /v3/sync?pos=4`:
It's there in the proxy, will add.

2022-01-04 11:42 UTC, kegsay commented on proposals/3575-sync.md
> +side because they are required for sort operations on lists. The `required_state` is controversially
`required_state` in the response matches the same field option in the request where "required state" means the state required by the client. I'm happy to rename this to something clearer, especially given @ShadowJonathan remarks about "the room would be "required" to have X state before its synced" which is a good point.

2022-01-04 11:49 UTC, kegsay commented on proposals/3575-sync.md
> +    "!sub1:bar": {
Not sure I follow you. We need to use a list of room objects for the sliding window as ordering is important. Ordering is irrelevant for room subscriptions, so whilst yes we could put this as an array of room objects it doesn't really help beyond being able to reuse a very small portion of the response struct, at the cost of having to answer questions like:
 - is the ordering in `room_subscriptions` important?
 - is it deterministic? If so, what's the sort order?
 - what do you do if the same room appears in the list twice?
 - why do I have to loop through the entire list containing all my subscriptions just to find a very specific room I asked for?

These questions disappear if it's a key-value map.

2022-01-04 11:49 UTC, kegsay commented on proposals/3575-sync.md
> +      }
We're missing a lot of filters, but these can likely be punted to extension MSCs.

2022-01-04 11:52 UTC, kegsay commented on proposals/3575-sync.md
> +      "rooms": [ [0,99] ],
It's slightly more bandwidth efficient to use an array whilst still preserving readability in that the start index will always be before the end index. If we did it the way you suggest, it's entirely valid to see `"rooms": [ {"end": 99, "start": 0} ]` which just becomes confusing.

2022-01-04 11:55 UTC, kegsay commented on proposals/3575-sync.md
> +      "sort": [ "by_notification_count", "by_recency", "by_name" ],
I don't think they will all necessarily have the `by_` prefix e.g `alphabetically_by_name`. I'd like to see different sort extension MSCs get proposed first before we assume the `by_` prefix is sensible.

2022-01-04 11:57 UTC, kegsay commented on proposals/3575-sync.md
> +      "sort": [ "by_notification_count", "by_recency", "by_name" ],
As the MSC states, it isn't possible to do ASC/DESC on the sort orders. It's something we could add if there is a need for it though.

2022-01-04 11:59 UTC, kegsay commented on proposals/3575-sync.md
> +        ["m.room.join_rules", ""],
The same reasons that ranges are arrays and not objects. It's generally more common to see the event type prior to the state key hence why the event type is first, but as @ShadowJonathan points out, they are technically tuples.

2022-01-04 12:01 UTC, timokoesters commented on proposals/3575-sync.md
> +    "!sub1:bar": {
Maybe both can be key value maps if we separate list order metadata from content, see https://github.com/matrix-org/matrix-doc/pull/3575#discussion_r777030851

2022-01-04 12:04 UTC, kegsay commented on proposals/3575-sync.md
> +          "name": "The calculated room name",
The server isn't forcing the room name on the client in that the client is free to use whatever name it wants for a given room. The server is however forcing a sort order on the rooms based on the canonicalised room name. Sync v3 doesn't return heroes/member counts/etc because the calculation is done server-side (it needs to for the sort order) so we just conveniently return the calculated room name in this `name` field.

2022-01-04 12:05 UTC, kegsay commented on proposals/3575-sync.md
> +At a high level, the syncing mechanism creates a "connection" to the server to allow the
This should really be treated as a connection though in that if WebScokets support is sprouted from this MSC (the design allows it) then the "connection" would actually be a real WS connection. It only isn't at present because Matrix uses long-polling.

2022-01-04 12:07 UTC, kegsay commented on proposals/3575-sync.md
> +        // The * is a special sentinel value meaning 'all keys'.
Skipping the second element makes it harder for statically typed languages to represent the API shape accurately. For example, in the proxy (in Go) this field is literally a list of 2-element string arrays:
```go
RequiredState [][2]string     `json:"required_state"`
```
This becomes impossible to represent if we allow 1 _or_ 2 values, pushing more validation work onto the developer.

2022-01-04 12:10 UTC, kegsay commented on proposals/3575-sync.md
> +returning the current state is that servers can cache the latest state to return the response more
You're right that idempotency means servers need to remember responses, but this is critically just the _last_ response, not the response for every single `pos` ever sent to the client. Idempotency guarantess are there purely to account for packet loss.

2022-01-04 12:12 UTC, kegsay commented on proposals/3575-sync.md
> +- Unsure how much data to expose (probably index position + notif/highlight counts?). If we do _counts_
Exactly.

2022-01-04 12:14 UTC, kegsay commented on proposals/3575-sync.md
> +MUST be omitted (sending `initial: false` is wasteful).
It's easy for server developers to do this, it's just often forgotten about. A compliance test suite can easily test this, so I feel MUST is acceptable given how noisy/bandwidth consuming sending `initial: false` over and over would be. It's also partly because it's horrible seeing an "empty" sync v2 response contain tons of fields just like this for no real reason.

2022-01-04 13:00 UTC, kegsay commented on proposals/3575-sync.md
> +A response for a given `pos` must be idempotent to account for packet loss. For example:
This is a good point, in that if the client doesn't update `pos` then it should be safe to assume they didn't get the original response. Come to think of it, sync v2 does exactly this in that syncing with a `since` token can produce different responses depending on when you sync. I'll remove these bits then.

2022-01-04 13:04 UTC, kegsay commented on proposals/3575-sync.md
> + - `DELETE`: Remove a *single* entry. Often comes before an `INSERT` to allow entries to swap places.
It's not really a move operation though, in that `DELETE 4, INSERT 0 != MOVE 4,0`. You really are deleting an entry and inserting a new entry which you previously had no knowledge about. We could absolutely mux these into an additional operation, but does that really help things? You still need a `DELETE` for actual deletions (leaving rooms) and `INSERT` for actual insertions (joining new rooms) so why not just reuse the core machinery we already need? This reminds me a bit of CISC vs RISC debate.

2022-01-04 13:10 UTC, kegsay commented on proposals/3575-sync.md
> +      "rooms": [
We already do separate things a bit in that if a room is present in the subscription and the list, only the subscription gets the update and the list just gets the room ID in question. We could go the whole hog here and put all room updates in a map and just keep list ordering bare bones, but I don't see the value here.

> This will lead to duplication if multiple lists contain the same rooms.

This is by design as the lists may have different `required_state` and `timeline_limit`. Event duplication is a concern which can be alleviated via event maps of event_id -> Event JSON, but I'm wary about doing that at this point whilst the API is still in flux, for precisely these sorts of reasons (maybe there's better ways to de-dupe naturally in the API).

2022-01-04 13:16 UTC, kegsay commented on proposals/3575-sync.md
> +      "rooms": [ [0,9], [20,29] ],
We could do this and in fact early designs did have this. However, those multiple "lists" _are intrinsically coupled_, resulting in synchronised churn on the list metadata when rooms change positions, as well as having to specify the request params (required state, timeline limit, etc) N times for each tracked range. It just made more sense to allow multiple windows.

For usage context, the majority of clients will use multiple sliding windows (at present at least): one window tracking the top N rooms and another tracking the scroll position of the list UI. Clients currently have to track the top N rooms to get notifications (assuming a most recent sort order) as the `notifications` API isn't fully fleshed out yet.

I'm open to ideas to allow lists to compose together better than at present, if it provides a more simplistic API shape whilst still being easy to follow.

2022-01-04 13:42 UTC, Dominaezzz commented on proposals/3575-sync.md
> +      "sort": [ "by_notification_count", "by_recency", "by_name" ],
If this land, there would be no nice way to do so. Best to just leave it encoded into the string as it is now and explicitly state it as such.

2022-01-04 13:46 UTC, Dominaezzz commented on proposals/3575-sync.md
> +returning the current state is that servers can cache the latest state to return the response more
It looks like you're about to drop the idempotent requirement anyway, so my comment here won't matter anyway.

2022-01-04 13:53 UTC, Dominaezzz commented on proposals/3575-sync.md
> +At a high level, the syncing mechanism creates a "connection" to the server to allow the
Well the WebSockets MSC doesn't exist yet and may look very different from what you envision.
I don't think making decisions based on a design that no one has seen or reviewed is a good idea. It makes the future rigid and the present awkward.

That aside, the websocket MSC can say something like, a sync session is only valid for the duration of the websocket connection. At least then, when I speak to people I can say "sync session" and abstract away long polling vs websocket vs future alternatives.

Basically what I'm saying is, a Matrix specific name for this connection concept won't hurt.

2022-01-04 13:59 UTC, Dominaezzz commented on proposals/3575-sync.md
> +        // The * is a special sentinel value meaning 'all keys'.
It's good you bring up statically typed languages, so I know it's safe to use as an argument now.

This concept of a list of 2-element string arrays doesn't exist in many popular languages. Or tuples for that matter.
This extra validation work you describe, I am going to have to do it for Kotlin, since Kotlin doesn't have tuples or statically sized lists. It also cannot automatically parse an array into a class, since it well formed JSON shouldn't look like that, I'm going to have to do extra work for it.

This should really just be an object (and not an array), as every statically typed language will understand that.

2022-01-04 14:01 UTC, Dominaezzz commented on proposals/3575-sync.md
> +      "rooms": [ [0,99] ],
Also regarding bandwidth efficiency, this is sticky no? You won't have to send this up to the server very often anyway.

2022-01-04 15:08 UTC, kegsay commented on proposals/3575-sync.md
> +              |      SYNC[0,4]=J,K,L,M,N     |
Yes and no. It's useful to have ways to delete ranges of rooms (say if the list filters change then we want to invalidate large chunks of the list) which is why INVALIDATE exists in the first place. We could implicitly say "if you get a SYNC for a range which you already think you have data for, replace that data", so that way we can remove the INVALIDATE call. I would need to think through the implications of making this implicit. This might be okay so long as we never have cases where invalidate ranges != sync ranges.

2022-01-04 21:53 UTC, ara4n commented on proposals/3575-sync.md
> +  "counts": [1337],
oh, so you get a total count of rooms per list, one item in the array per list? i think i missed that the value is an array. (and eitherway, its behaviour needs to be spelt out in the MSC)

2022-01-04 21:54 UTC, ara4n commented on proposals/3575-sync.md
> +### Bandwidth optimisations for persistent clients
okay, it could be factored out to aid review, but we need to flag loud and clear that this deliberately doesn't implement LL members yet - as in that respect it's very much a regression.

2022-01-04 21:57 UTC, ara4n commented on proposals/3575-sync.md
> +      }
okay, but i think you should spell out the ones which are being punted, to stop everyone reviewing this MSC tripping over the same question.

2022-01-04 22:02 UTC, ara4n commented on proposals/3575-sync.md
> +        ["m.room.member", "*"]
i quite like this as a way to indicate LL member semantics (more so than having it as a filter), but you must remember that the semantics are more than just "only give me members for events in the room timeline" - it also has to cover the behaviour during gappy syncs.

2022-01-04 22:05 UTC, ara4n commented on proposals/3575-sync.md
> +MUST be omitted (sending `initial: false` is wasteful).
+1 to mandating that servers shouldn't include redundant data in sync responses, to avoid all the problems we've had with v2 sync responses containing loads of blank redundant data which then break clients when removed.

2022-01-05 08:42 UTC, timokoesters commented on proposals/3575-sync.md
> +      "rooms": [
> This is by design as the lists may have different required_state and timeline_limit

It's easy to merge the requirements: union over required_states, max over timeline_limits (although "limit" is not the right word then, maybe timeline_limit can be renamed to timeline_request?)

2022-01-05 08:45 UTC, timokoesters commented on proposals/3575-sync.md
> +          "required_state": [
Currently there is no way to tell clients about removal of state events. How about a second field with "dropped_state" that lists all the state event ids that have been dropped and not replaced since the last update

2022-01-05 08:49 UTC, timokoesters commented on proposals/3575-sync.md
> +      "range": [0,9],
Are these indexes of the sliding window or of the entire list?

2022-01-05 08:53 UTC, timokoesters commented on proposals/3575-sync.md
> + [H,A,B,C,D]  | <- DELETE[4], INSERT[0]=H--- |
Hmm do you mean this?: The client sends a sliding window update. Before that is handled by the server, the server already sends a sync. The client assumes the sync is received already uses the updated sliding window, but this is wrong.

2022-01-06 10:21 UTC, benkuly commented on proposals/3575-sync.md
> +   rooms like Matrix HQ will be `SYNC`ed from fresh rather than sending 100s of events.
Do I understand it right, that the client would get the complete state of the room again because auf `SYNC`? If yes: I don't see how that would consist to "bandwidth-efficient way". I have fully offline cabable clients in mind, which do not really use the windows API features, because they want to retrieve nearyl everything. The windows API may be good for a fast first login or always online clients, but for syncing just the difference to the previous sync it feels like a downgrade compared to sync v2. But maybe I just misunderstood, how sync v3 works :D

2022-01-06 23:05 UTC, Dominaezzz commented on proposals/3575-sync.md
> +MUST be omitted (sending `initial: false` is wasteful).
What should clients do then -- reject the sync response if the redundant field is sent? In reality, if a server does return this (intentionally or not) clients will simply let it work anyway. Using MUST here would be a guideline disguised as important spec.

2022-01-07 13:39 UTC, kegsay commented on proposals/3575-sync.md
> +      "rooms": [ [0,99] ],
This field is not sticky and changes whenever you scroll the room list.

> CBOR or protobuf should be used instead an call it a day.

This isn't a valid suggestion. Protobuffers aren't suitable for extensible keys that Matrix support. CBOR encodes key names as strings unless you enumify them like MSC3079 does (which I also wrote). The difference overall is small however.

2022-01-07 13:41 UTC, kegsay commented on proposals/3575-sync.md
> +        ["m.room.member", "*"]
What behaviour are you alluding to exactly @ara4n ?

2022-01-07 13:44 UTC, kegsay commented on proposals/3575-sync.md
> +          "required_state": [
I'd rather we expressed removal of state events as either:
 - The previous state event is returned, or
 - An empty `content: {}` is sent if the state is deleted entirely.

I prefer this because it means clients will handle deletions automatically as soon as they can handle setting state, without having to add in extra code.

2022-01-07 13:46 UTC, kegsay commented on proposals/3575-sync.md
> +   rooms like Matrix HQ will be `SYNC`ed from fresh rather than sending 100s of events.
It depends on the filters the client has applied. If the client is asking for all state events in the room (so for Matrix HQ this is something like 25k events) then the idea is that we will only start from fresh if you have missed >25k events in that room, else you will just get the delta.

2022-01-07 14:19 UTC, kegsay commented on proposals/3575-sync.md
> +      "range": [0,9],
Index positions and ranges always refer to the entire list.

2022-01-07 14:55 UTC, deepbluev7 commented on proposals/3575-sync.md
> +  The highest `notification_count` comes first in the list.
Nheko sorts by `["by_has_highlights", "by_notification_count",  "by_recent_message", "by_room_id"]`

Sorting by highlight count is very confusing, because there is not really a way for users to understand that sorting. They only see a red or blue bubble and that bubble always has the notification count, not the highlight count.

And sorting by most recently received event is annoying, because it makes membership changes bump the room list (and other state events you don't care about). As such Nheko only uses the timestamp of events, that it actually shows in the room list.

Lastly it uses the room id as the last effort tie breaker. That is so unlikely to happen, that it probably does not need to be spelled out in the sync sorting, I just included it for completeness sake. I'm guessing many servers will do that anyway.

2022-01-07 14:57 UTC, deepbluev7 commented on proposals/3575-sync.md
> +   The highest `origin_server_ts` value comes first in the list.
Does this always match what the client is sent as the most recent event in the room? In the traditional sync, a clean, new sync would reorder recently received events to the back, when their ts is older. Would that affect this sorting or would it always stick to he most recently received event on the server side?

2022-01-07 22:40 UTC, JuniorJPDJ commented on proposals/3575-sync.md
> + - Sort E2EE rooms in their own dedicated list: `{"filters": { "is_encrypted": true }}`
I think it's the best idea. Considering the fact not every client supports E2EE anyway it may have other benefits.

2022-01-07 23:11 UTC, JuniorJPDJ commented on proposals/3575-sync.md
> +    "!sub1:bar": {
^ This seems to be actually pretty good idea.

Why not just have one merged cumulative object of rooms for every "query type" and then have ids in each list/map.

2022-01-07 23:17 UTC, JuniorJPDJ commented
Maybe changing the `pos` to `sess` or something like that would make it less confusing as `pos` seems to be related to position.

2022-01-07 23:34 UTC, JuniorJPDJ commented on proposals/3575-sync.md
> +      "filters": {
1. Having filter for rooms not in any space would be cool idea.
2. Favourites could be handled by element using subscribes.
3. Orphans? Is this archive thing? Are those even updated in sync?

2022-01-08 02:39 UTC, turt2live commented on proposals/3575-sync.md
> +        ["m.room.member", "*"]
From the [`/sync` endpoint](https://spec.matrix.org/v1.1/client-server-api/#get_matrixclientv3sync):

> When a sync is `limited`, the server MUST return membership events for events in the gap (between `since` and the start of the returned timeline), regardless as to whether or not they are redundant. This ensures that joins/leaves and profile changes which occur during the gap are not lost.

2022-01-11 14:10 UTC, kegsay commented on proposals/3575-sync.md
> + - Sort E2EE rooms in their own dedicated list: `{"filters": { "is_encrypted": true }}`
The API lets clients choose what they want to do here. For a lot of clients I suspect including them in the same list is probably okay, but certain clients may want that extra flexibility that a different list can support. Indeed, having the `is_encrypted` filter is particularly useful when I've been testing, as the test jig I wrote in the proxy didn't handle E2EE so it was nice to be able to filter them all out and thus save on bandwidth.

2022-01-20 18:25 UTC, timokoesters commented on proposals/3575-sync.md
> +`POST /_matrix/client/unstable/org.matrix.msc3575/sync?pos=4&timeout=30000`:
We should use this opportunity and remove the query parameters and move them into the json request so that clients don't have to send an OPTIONS request every time.

2022-02-10 05:45 UTC, timokoesters commented on proposals/3575-sync.md
> +`POST /_matrix/client/unstable/org.matrix.msc3575/sync?pos=4&timeout=30000`:
See https://github.com/matrix-org/synapse/issues/9669

2022-02-24 17:24 UTC, kegsay commented on proposals/3575-sync.md
> +`POST /_matrix/client/unstable/org.matrix.msc3575/sync?pos=4&timeout=30000`:
Right, so this is only when the server sends back `Access-Control-Max-Age` header.

**I love it.** Will implement this now in the proxy.

2022-02-25 11:31 UTC, kegsay commented on proposals/3575-sync.md
> +`POST /_matrix/client/unstable/org.matrix.msc3575/sync?pos=4&timeout=30000`:
Hmm, I'm not seeing OPTIONS requests with every /sync in the proxy. These requests are POST requests. Will need to investigate this more before moving the pos to the HTTP body.

2022-05-23 14:52 UTC, kegsay commented on proposals/3575-sync.md
> +token cannot be used with other APIs such as `/messages` or `/keys/changes`.
There is a `prev_batch` for each room timeline, but they are explicitly for use with `/messages`, and are separate to the sliding sync `?pos=`.

2022-05-23 14:59 UTC, kegsay commented on proposals/3575-sync.md
> +  The highest `notification_count` comes first in the list.
Extension MSCs can include these custom sort orders.

2022-05-24 09:28 UTC, kegsay commented on proposals/3575-sync.md
> +      "rooms": [
We now do this. :)

2022-06-01 13:11 UTC, ShadowJonathan commented on proposals/3575-sync.md
> +        // The term 'like' is inspired by SQL 'LIKE', and the text here is similar to '%foo%'.
As I noticed in [the ruma impl PR](https://github.com/ruma/ruma/pull/999#discussion_r886774323), this is unclear, and potentially misleading;

> This also implies that use of `%` must be in the string, or else it'll not match suffixed or prefixed room names.
> 
> From what i'm reading, this is a simple substring server search.

---

Suggestions; name it `partial_room_name`, drop the mention of SQL, and note its a case-insensitive substring search.

Also, specifying behaviour around character normalization (e.g. `U` matching `Ü`) would be helpful.

2022-06-09 18:16 UTC, ShadowJonathan commented on proposals/3575-sync.md
> +`slow_get_all_rooms: true`. If this is set, the `ranges` and `sort` keys are ignored and all rooms which match the list
Why does this have to be prepended with `slow_`?

2022-06-13 21:12 UTC, kegsay commented on proposals/3575-sync.md
> +`slow_get_all_rooms: true`. If this is set, the `ranges` and `sort` keys are ignored and all rooms which match the list
This was a conscious choice so developers know that setting this flag introduces a performance penalty. This is the least obnoxious way to do it, with the inspiration coming from React-style `__dangerouslySetInnerHtml`.

2022-06-13 21:13 UTC, kegsay commented on proposals/3575-sync.md
> +        // The term 'like' is inspired by SQL 'LIKE', and the text here is similar to '%foo%'.
I mean, the example is pretty clear I think? Character normalization is a good point though, we probably _should_ do this.

2022-08-03 15:12 UTC, ara4n requested changes

2022-08-03 15:12 UTC, ara4n commented on proposals/3575-sync.md
> +If the request parameters have not been modified, then the `txn_id` does not need to be sent.
s/sent/changed/ presumably? @kegsay

2022-08-05 12:08 UTC, kegsay commented on proposals/3575-sync.md
> +If the request parameters have not been modified, then the `txn_id` does not need to be sent.
Well if you don't care about knowing when your params have been applied, sending a txn_id is not really _required_ and you can save a few bytes per request. Saying "changed" implies that you need to send it as-is without modification, and when you change request params you then bump the txn_id to a new value, which isn't what I'm aiming for.

2022-09-16 09:13 UTC, johannescpk commented on proposals/3575-sync.md
> +possible operations are:
I wonder if it would make sense to use the JSON Patch RFC (https://www.rfc-editor.org/rfc/rfc6902) as base for the operations? Out of the box at least `INSERT` and `DELETE` should work, I guess.

2022-09-16 09:17 UTC, johannescpk commented on proposals/3575-sync.md
> +possible operations are:
As an real life example of someone using the RFC: FHIR is using it for their PATCH endpoint (https://www.hl7.org/fhir/http.html#patch).

2022-09-16 10:35 UTC, kegsay commented on proposals/3575-sync.md
> +possible operations are:
Relevant snippet:
```
[A.7](https://www.rfc-editor.org/rfc/rfc6902#appendix-A.7).  Moving an Array Element

   An example target JSON document:

   { "foo": [ "all", "grass", "cows", "eat" ] }

   A JSON Patch document:

   [
     { "op": "move", "from": "/foo/1", "path": "/foo/3" }
   ]

   The resulting JSON document:

   { "foo": [ "all", "cows", "eat", "grass" ] }
```

This naturally has more boilerplate, and it's unclear how it would handle sliding windows. This MSC uses absolute index positions when issuing move operations, which wouldn't work here as you would actually need an array of that size. You could add an `offset` integer to indicate where the array begins in the room list then use relative indexing, but now you need to maintain and think about 2 kinds of index: absolute and relative. It ends up feeling more complicated, and the value in RFC6902 is only there if there are a variety of good libraries in different languages so people don't need to implement this logic themselves.

2022-10-17 11:02 UTC, gnunicorn commented on proposals/3575-sync.md
> +   `notification_count` > 0, followed by all other rooms. Rooms are not sorted within each level:
If no other sorting giving, I'd expect them to sort by the _number_ within each ... so a room with `highlight_count = 4` comes before `highlight_count = 3`, etc ...

2022-10-21 10:24 UTC, kegsay commented on proposals/3575-sync.md
> +   `notification_count` > 0, followed by all other rooms. Rooms are not sorted within each level:
This is semantically not useful, and would then break the ability to do 2nd order sort options (you couldn't then say `by_recency` as there would be no ties, or no ties at a sensible point rather as you'd get ties when the counts are the same).

2022-10-28 12:58 UTC, Dominaezzz commented on proposals/3575-sync.md
> +        ["m.space.child", "*"],
```suggestion
        ["m.space.child", "$ANY"],
```
or
```suggestion
        ["m.space.child", "$ALL"],
```

Seems more consistent?

2022-11-09 12:16 UTC, gnunicorn commented on proposals/3575-sync.md
> +        "room_types": [ "m.space", null ],
I was thinking about the `filters` again, in particular that someone might want to filter for certain subtypes (as [per spec MSC-3088](https://github.com/matrix-org/matrix-spec-proposals/pull/3088)) or other custom state, like having [`m.room.pinned_events`](https://spec.matrix.org/v1.4/client-server-api/#mroompinned_events) set, and notice this isn't possible at the moment.

We have support for some of these markers, like space, dm or encrypted, but not for others (even those that are in the spec, like pinned_events), which kinda feels odd. I am wondering if we can unify them to a general `has_state` and `not_has_state` with a similar matching systems as `required_states`. We could still keep the existing filters as we have them now, but allow for more generic (unknown to us and to the future of the spec) state-matching. What do you think?

2022-11-28 18:42 UTC, gnunicorn commented on proposals/3575-sync.md
> +
Should this there mandate that _clients must use_ this as the target if they find it?

2022-12-20 14:11 UTC, kegsay commented on proposals/3575-sync.md
> +        "room_types": [ "m.space", null ],
Arbitrary state filtering isn't great because it is hard to do this efficiently. Currently, the proxy pre-calculates values like DM-ness, encrypted-ness, spaces (child and parent) so it's very quick to then filter in-memory. Allowing arbitrary state filtering means we either need to do a DB hit (slow) or pre-cache all state in-memory (expensive and basically unscalable).

I can see the value in the flexibility, but not at the cost of performance imo which is the entire point of this MSC after all.

2022-12-20 14:59 UTC, t3chguy commented on proposals/3575-sync.md
> +
Why does a server need advertise a proxy in this way? Why not just make it offer it as if the server natively supported the feature, i.e. via a reverse proxy? Given some implementations may internalise the proxy by wrapping it in a worker (e.g. Dendrite) why not make the access consistent

2022-12-26 22:24 UTC, ara4n commented on proposals/3575-sync.md
> +The `timeout` query parameter exists for the same purposes of sync v2: to tell the server how many
we should specify a default value, no?

2022-12-27 22:01 UTC, ara4n commented on proposals/3575-sync.md
> + - Account Data - `account_data` in sync v2:  [impl](https://github.com/matrix-org/sliding-sync/blob/main/sync3/extensions/account_data.go)
the current account data extension is distinctly problematic, in that without a `since` token, you're guaranteed to receive all your entire account data every time your session expires (i.e. on pretty much every app launch, after 30m of downtime). For me, that's 150KB of dense JSON that has to be calculated, transferred and decoded before the app can launch.  Of this, 22KB is push rules and 116KB is tracking which rooms are tagged as DMs.  Empirically this seems to delay launch very noticeably relative to before we had the account_data extension.

```

2023-01-30 19:55 UTC, jplatte commented on proposals/3575-sync.md
> +stored client list, such as INSERT, DELETE and SYNC. Each operation has an index position OR a
Why are the ops all-uppercase? The only other thing that's all-uppercase in the protocol are error codes.

2023-02-10 15:42 UTC, benkuly commented on proposals/3575-sync.md
> + - `SYNC`: Sets a *range* of entries. Clients SHOULD discard what they previous knew about entries in
I want to understand, why we need such bloatet API. This makes the implementation more complicated. Why not just send a list of room ids, when the list changes? _At this point I would like to apologize if this discussion has already taken place and I have overlooked it._

2023-02-22 06:39 UTC, turt2live commented
Proxy implementation is suitable for this, given timelines and practicality (discussed oob many months ago: sorry for not writing it down)

2023-02-22 08:03 UTC, turt2live reviewed
This is quite a large MSC, and I haven't finished reading it yet. The comments here are representative of everything up to "Sliding Window API", and should be annotated as explicitly non-blocking if it doesn't affect feelings of being ready for FCP (in my opinion). 

I'll aim to finish the review later in the week, though this should also be plenty to think about for now :D (also sorry)

Other things to consider for getting the MSC "FCP ready" would be:
* Ensuring all resolved conversations/threads are marked as resolved, including ones not on the current diff. (I've added comments to the ones which felt like they were lacking resolution to try and give them a resolution)
* Early in the proposal, such as in the very first paragraph, clarify if this MSC is bypassing the [existing deprecation strategy](https://spec.matrix.org/v1.6/#deprecation-policy) for the spec or if the strategy is intended to be followed. The MSC already says "replace", which will invoke the deprecation policy linked, not an actual replacement.
* Double check that all the listed goals are actually achieved in the MSC. Given I'm about halfway through, I can't be sure that they *haven't* been met, but is something that will come up in a later review if not achieved - saves everyone a little time if double checked up front.

2023-02-24 19:53 UTC, deepbluev7 commented on proposals/3575-sync.md
> +stored client list, such as INSERT, DELETE and SYNC. Each operation has an index position OR a
I at lest appreciate that they are upper case on the MSC, since that makes it much easier to search for them. The final values might want to be shortened to single characters though.

2023-02-24 19:54 UTC, deepbluev7 commented on proposals/3575-sync.md
> +possible operations are:
That doesn't work for alphabetic ordering, I would say.

2023-02-24 20:09 UTC, jplatte commented on proposals/3575-sync.md
> +stored client list, such as INSERT, DELETE and SYNC. Each operation has an index position OR a
I'd much prefer lowercase but not single character, like basically everywhere else.

2023-02-24 20:11 UTC, deepbluev7 commented on proposals/3575-sync.md
> +windows as well as which rooms are explicitly subscribed to.
Can they also add data to the core API in the **response** or will the response from the extension be in a separate field? I.e. when adding room account data, is that returned in the existing rooms or under something like `{"extensions": { "account_data": ... } }`

2023-02-24 20:23 UTC, deepbluev7 commented on proposals/3575-sync.md
> +   tokens valid for at least 7 days.
This means any persisting client needs to actively scan all timeline events for duplicates, since it can never know, if the server forgot that it already sent those?

2023-02-24 20:37 UTC, deepbluev7 commented on proposals/3575-sync.md
> + - the session expires and a new session is created.
So I am assuming a client should just ignore all SYNC, INVALIDATE and DELETE commands in respect to deleting the state here? Does that mean in case of a state reset, I can rely on the server sending me an "initial": true in the room object to tell me to reset my local state?

2023-02-24 20:39 UTC, deepbluev7 commented on proposals/3575-sync.md
> +   tokens valid for at least 7 days.
Ah, I guess a client can tell, that is the case, because the room will have "initial": true?

2023-02-24 20:49 UTC, deepbluev7 commented on proposals/3575-sync.md
> +      "ranges": [ [0,99] ],
Is this sticky? Possibly exclusive with the `slow_get_all_rooms`, so that I only specify the range once, sync 3 times, then when I want all rooms, I clobber it with `slow_get_all_rooms`?

2023-02-24 20:50 UTC, deepbluev7 commented on proposals/3575-sync.md
> +      "invite_state": [ { type: "m.room.member" } ], // stripped state events, same as rooms.invite.$room_id.invite_state in sync v2, absent on joined/left rooms
Maybe rename this to `stripped_state` and share it with kocked rooms?

2023-02-24 20:50 UTC, deepbluev7 commented on proposals/3575-sync.md
> +      "invited_count": 1,           // same as sync v2 m.invited_member_count
What about the knocked member count?

2023-02-24 21:06 UTC, deepbluev7 commented on proposals/3575-sync.md
> +    }
Attaching to a random position, since I don't know where to put it:

What I can't figure out at all is: How do I know what rooms I am a member of, what rooms I am invited to, what rooms I have knocked on and what rooms I have left? Is my own member event always guaranteed to be included the first time I get a room? If not, putting it in a "membership" key or so might be more convenient (current sync has it on the top level, so it isn't an issue).

2023-02-24 21:08 UTC, deepbluev7 commented on proposals/3575-sync.md
> +        "is_invite": true,
Slightly related, do I get an update for a room I am kicked from or have left? As in, can I show the kick reason locally? Do I get a DELETE for that room (even if I have the list expanded to show all rooms) or how does that work? Does that also need an "is_leave" filter, which then is ORed together?

2023-02-24 21:55 UTC, deepbluev7 commented on proposals/3575-sync.md
> +SHOULD send a transaction ID when they need to know when the response has been calculated.
Why can't a client just tell something has been responded to by looking if the response is to their particular request? What http library does not tie a response to a request handle?

2023-02-24 22:19 UTC, deepbluev7 commented on proposals/3575-sync.md
> +to agree on what that stored state is. _This introduces additional rules on client implementations._
Does this mean that sync requests actually are tracked by HTTP connection? And I can't have multiple sync streams without figuring out how to not make my library multiplex those streams onto the same connection? That doesn't sound that desirable. Ideally I would be able to handle presence and to_device messages at a different pace than room updates. The obvious implementation for that would be to open multiple streams. With the current sync that can't be done, since it deletes your to_device messages, even when you tried to filter them out (at least on some servers). However that is already solved for sliding sync.

So passing along some stream id, possibly a single character, would allow for multiple parallel streams at different frequencies as well as fast reconnect to old streams after a connection interruption (which can happen quite a lot on lossy networks or when switching networks without http/3). You kinda need a stream id, since you don't have a since token here to distinguish streams.

2023-02-24 22:22 UTC, deepbluev7 commented on proposals/3575-sync.md
> +to agree on what that stored state is. _This introduces additional rules on client implementations._
(For reference, presence accounts for about 80% of the CPU usage on Nheko, since most of the time it is presence events, that wake up the sync loop.)

2023-02-24 22:30 UTC, deepbluev7 commented on proposals/3575-sync.md
> +standard error response as a HTTP 400 containing:
What happens if a client tries to use an older `pos` token? Will the connection rewind to that state or will it return an error? Does this include when the client asks for the same `pos` twice, because it lost the response?

2023-02-25 17:58 UTC, ara4n commented on proposals/3575-sync.md
> + - Account Data - `account_data` in sync v2:  [impl](https://github.com/matrix-org/sliding-sync/blob/main/sync3/extensions/account_data.go)
(delta tokens are the proposed solution to this)

2023-02-25 18:37 UTC, turt2live commented on proposals/3575-sync.md
> +The possible `sort` operations are:
Bots and other roomlist-less clients probably won't care about the position of rooms, so to save bandwidth we could define a `none` sort option, which suppresses operations from being sent server->client. If the client needs to know which rooms to expect (ie: what `SYNC` would normally provide), it can call `/joined_rooms` or another similar API.

Or possibly we don't exclude `SYNC` from the sort, but do suppress everything else.

2023-02-27 09:55 UTC, gnunicorn commented on proposals/3575-sync.md
> +The possible `sort` operations are:
for bots and other roomlist-less clients, the `slow_get_all_rooms` was added with ignores any `sort` and `range`-parameters. Filter still apply though, so you can take the subset you care about (e.g. only DM's). Is there a use case that this doesn't cover yet?

2023-02-27 10:48 UTC, deepbluev7 commented on proposals/3575-sync.md
> +        // A list of spaces which target rooms must be a part of, as m.space.child state events.
What about hidden space children? I.e. when a space admin only sets the m.space.parent event in a room, so that space members can only know about the room, when they are joined to the child room? Those should be listed in the /hierarchy call, so I am suprised, that those seem to be excluded here.

2023-02-27 15:59 UTC, turt2live commented on proposals/3575-sync.md
> +The possible `sort` operations are:
I hadn't read that far in the MSC yet, and it didn't come up in discussion when this comment was written :p 

Will take a look at the other field.

2023-02-28 11:17 UTC, gnunicorn commented on proposals/3575-sync.md
> +This allows servers to declare an "official" trusted proxy, rather than using other URLs which may be
While implementing this for the [ansible docker builder](https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/2515#discussion_r1119910354), the question came up whether this mean to define the entire URL, where to find he sliding-sync-endpoint or just a proxy that provides the `/_matrix/client/unstable/org.matrix.msc3575/sync` endpoint. Is this URL meant to include the path or not?

2023-02-28 12:30 UTC, kegsay commented on proposals/3575-sync.md
> + - `SYNC`: Sets a *range* of entries. Clients SHOULD discard what they previous knew about entries in
Sending list deltas is inherently complicated, which is why it's more complex than sync v2 which just sent everything. If you want a similar behaviour to that, just use `slow_get_all_rooms: true` on your list and then you won't see any ops at all.

You can't just send a list of room IDs because you need to communicate at which index they start at. If you sent the entire list and were in 10,000 rooms, that's 10,000 strings every time a room changed position, which wastes bandwidth.

2023-02-28 12:38 UTC, kegsay commented on proposals/3575-sync.md
> +to agree on what that stored state is. _This introduces additional rules on client implementations._
Currently, the proxy will track connections by the access token used in the request, forcing 1 connection per 1 access token.

This is absolutely something we're considering, because it also has a negative impact on Web, whereby if you open a SS-enabled client in two browser tabs they step on each other and expire each other's connnections. Any potential stream ID needs to be client-driven, as I don't want 5x `/sync` requests without a `?pos=` to cause 5 connections to be made, i.e the stream ID needs to be explicitly in the client request, not generated server-side.

2023-02-28 12:39 UTC, kegsay commented on proposals/3575-sync.md
> +**Long-polling Rule 1:** do not send multiple concurrent sliding sync requests to the server. If a request is lost in
The server can't distinguish this failure mode from a genuine 2nd concurrent request to change request params. This rule is focusing on the case where the request may or may not make it to the server.

2023-02-28 12:40 UTC, kegsay commented on proposals/3575-sync.md
> +SHOULD send a transaction ID when they need to know when the response has been calculated.
Because of rule #3 - the HTTP response may not be for the HTTP request you made (if, for example, the response is live data).

2023-02-28 12:42 UTC, kegsay commented on proposals/3575-sync.md
> +standard error response as a HTTP 400 containing:
It will return an error. It does not happen when the client asks for the same pos twice because it lost the response.

The proxy implements this by holding onto 2 position values:
 - the position just sent back to the client i.e in `{ pos: ... }` <- Unacknowledged latest position
 - the position last received in a client request i.e in `?pos=` <- Acknowledged position

2023-02-28 12:44 UTC, kegsay commented on proposals/3575-sync.md
> +      "ranges": [ [0,99] ],
It's not sticky in the MSC, but I'd need to check if the proxy treats this as sticky. It used to not, but this was before we swapped to lists-as-keys.

2023-02-28 12:46 UTC, kegsay commented on proposals/3575-sync.md
> +        // like `food` and `foobar`. In this case, the * is treated as a literal *.
I think there is value to state what `*` means in this scenario. The previous sentences merely state that:
 - it isn't a globbing function.
 - it won't pull in keys like...

Okay, so what _will_ it do? It's treated as a literal *.

2023-02-28 12:48 UTC, kegsay commented on proposals/3575-sync.md
> +        ["m.room.member", "$ME"],
It's very convenient to have this in Element-Web, as I can define the lists as `const`s by using `$ME`, whereas without it I have to keep the variable in sync with whatever `MatrixClient` is hanging around (and remake it when it changes).

2023-02-28 12:49 UTC, kegsay commented on proposals/3575-sync.md
> +      "timeline_limit": 10,
The server should be able to not honour that i.e a newly joined room over federation isn't going to cause tons of backfilling because you want many timeline events. I suspect the semantics are going to be the same as sync v2 filters.

2023-02-28 12:53 UTC, kegsay commented on proposals/3575-sync.md
> +      "include_old_rooms": { //sticky
Yes, it's a shallow replace. If this object is provided, it replaces the object that came before it.

The "ambiguous api" section describes the behaviour when this is shown, which states:

> What is the value of `baz`? Both unset and `2` are valid answers. For this reason, `baz` MUST
be marked as sticky if the desired result is `2`, else it will be unset.

"else it will be unset" i.e everything in this object will be unset if it isn't marked as sticky.

2023-02-28 12:55 UTC, kegsay commented on proposals/3575-sync.md
> +        // will be ignored.
Yes and Yes.

Assuming the client is joined to spaces `["!a:example.org", "!b:example.org"]` then a room can pass the filter if the room belongs to ANY one of the spaces given.

2023-02-28 12:57 UTC, kegsay commented on proposals/3575-sync.md
> +        // are returned. If true, only encrypted rooms are returned.
Simply present, else we're baking in too much in case the event sprouts a new algorithm/structure.

2023-02-28 12:59 UTC, kegsay commented on proposals/3575-sync.md
> +        "is_invite": true,
There is no knocking support yet, so we'd probably add `is_knock`.

Please make a separate comment re rooms being present after kick. The proxy will keep the room in the list _if the kick happens whilst connected_, but will be omitted on the next connection. It's not specced currently, and I don't know if that is desirable behaviour.

2023-02-28 13:02 UTC, kegsay commented on proposals/3575-sync.md
> +      "name": "The calculated room name",
AFAIK, yes.

We may add in the ability to specify a `locale` key (maybe in account data?) which would be read by the SS proxy which could convert `Alice and Bob` to `Alice et Bob`. Seems doable anyway.

2023-02-28 13:03 UTC, kegsay commented on proposals/3575-sync.md
> +      // absence of this flag means 'false'.
@ara4n and myself both feel it's a huge mistake to allow servers to optionally include redundant fields. It ends up with brittle client implementations - see the many cases where Dendrite/Conduit omit fields that Synapse does not and it breaks one of Web/iOS/Android.

2023-02-28 13:04 UTC, kegsay commented on proposals/3575-sync.md
> +      "is_dm": true, // field is absent on non-DM rooms
I don't agree with this re https://github.com/matrix-org/matrix-spec-proposals/pull/3575/files#r1120029360

2023-02-28 13:07 UTC, kegsay commented on proposals/3575-sync.md
> +    }
It depends on your filters. You're only going to be sent rooms you've joined, been invited to, or have knocked on (when it gets specced). If you specify no filter, then all of them will be returned in the list. If you are getting all of the rooms in the list and need to care about the membership, then ask for that state event `["m.room.member", "$ME"]`.

2023-03-01 21:15 UTC, deepbluev7 commented on proposals/3575-sync.md
> +    }
In the past the member event hasn't been resent based on state resets, so the only thing one could trust used to be what section the room comes down on /sync. I am assuming clients can rely on getting the right member event even after state resets then? As in a state reset causes the current state event to be pushed? That should probably be spelled out explicitly on the MSC then.

2023-03-06 15:48 UTC, MTRNord commented on proposals/3575-sync.md
> +[Proxy server](https://github.com/matrix-org/sliding-sync) (v0.99.0):
Since the proxy seemingly will stay around for a while before we have this in synapse and others, we currently have a hard requirement for well-known which seems not optimal.

Element Android (see: https://github.com/vector-im/element-x-android/issues/137 ) therefor requires a well-known file now, which not everyone might be able to add in some edge cases. 

Maybe it would make sense as part of the unstable handling of this MSC to define a standard location for the sync proxy as long as it is required for sliding sync to work to be able to not require well-known for sliding sync usage.

For example, requiring `sliding.<server_name>` as the standard location of the proxy to check if no well-known was found and using the well-known mainly when the proxy is deployed elsewhere. This would allow to not hardcode the well-known requirement and make it easier to set up while the sync proxy is around.

2023-03-06 15:56 UTC, anoadragon453 commented on proposals/3575-sync.md
> +[Proxy server](https://github.com/matrix-org/sliding-sync) (v0.99.0):
I'd be concerned about requiring a standard subdomain - what if someone's infrastructure is already using that domain for something else?

I'd rather just ask clients to fall back to `<c-s url>/_matrix/client/unstable/org.matrix.msc3575/sync` if they can't find a valid `org.matrix.msc3575.proxy` field in a client .well-known file.

2023-03-06 16:05 UTC, MTRNord commented on proposals/3575-sync.md
> +[Proxy server](https://github.com/matrix-org/sliding-sync) (v0.99.0):
Ah, yes, that makes sense. :) I wasn't sure if the proxy works on a subpath or not since I only saw it used on a subdomain so far.

2023-03-09 20:32 UTC, turt2live commented
There's 8 people on the spec core team, 4 of which have been asked to review this specifically, excluding me. When I submitted my review the MSC was believed to be in a different state than it actually is, which makes the Part 2 of the review relatively pointless at this stage.

It's currently with me to ensure this MSC works through the process at the correct stages, which is happening. Further questions about the status of this MSC, or any MSC, can be asked in [#sct-office:matrix.org](https://matrix.to/#/#sct-office:matrix.org) on Matrix.

2023-03-14 16:47 UTC, richvdh reviewed
This is a very well-written proposal - thank you for your efforts in setting it out so clearly.

I've asked a bunch of stupid questions, but generally it seems entirely plausible to me.

2023-03-14 16:47 UTC, richvdh commented on proposals/3575-sync.md
> +     * Lower-case the result by unicode. This ensures `Matrix` and `matrix` sort in the same locations.
I know you mention i18n below, but just to call out: "Lower-case the result by unicode" is wildly insufficient here. Different languages have completely different sorting preferences and it's basically only in English that sorting individual characters by their unicode codepoints will give anything approaching a sensible ordering.

Admittedly we're terrible at this today, so probably not a thing we need to fix in the first implementation.

2023-03-14 16:47 UTC, richvdh commented on proposals/3575-sync.md
> +i18n and l10n are done.
to be explicit: this is proposed for a future MSC, rather than being part of this one?

2023-03-14 16:47 UTC, richvdh commented on proposals/3575-sync.md
> +This would return the following response:
It slightly feels like it will be easy for client authors to leak subscriptions and basically forget that they've subscribed to rooms.

I also think that, in the case of a bug which causes clients and servers to get out of sync as to which rooms are subscribed, it's going to be quite tricky to track down what's going on.

To mitigate both issues: should we return a list of the subscribed rooms?

2023-04-04 09:49 UTC, zecakeh commented on proposals/3575-sync.md
> + - Account Data - `account_data` in sync v2:  [MSC3959](https://github.com/matrix-org/matrix-spec-proposals/pull/3950)
Wrong PR number in the URL :)
```suggestion
 - Account Data - `account_data` in sync v2:  [MSC3959](https://github.com/matrix-org/matrix-spec-proposals/pull/3959)
```

2023-04-04 09:50 UTC, DMRobertson commented on proposals/3575-sync.md
> + - Account Data - `account_data` in sync v2:  [MSC3959](https://github.com/matrix-org/matrix-spec-proposals/pull/3950)
Thanks, I have sausage fingers.

2023-04-17 12:31 UTC, DMRobertson commented on proposals/3575-sync.md
> +  "bump_event_types": [ "m.room.message", "m.room.encrypted" ],
From talking to clients:

- it would be useful to have this field configurable per-list
- it would be useful to  bump_event_types set to an empty list. @kegsay described a use case: clients want a room list that never bumps rooms on activity _unless_ you were directly pinged---in which case, the most recent notification bubbled to the top of the list).

2023-04-25 09:09 UTC, erikjohnston commented on proposals/3575-sync.md
> +**Long-polling Rule 1:** do not send multiple concurrent sliding sync requests to the server. If a request is lost in
I don't quite follow how this works in practice? If sending a request times out, what does the client do? Considering the timed out request might still have reached the server

2023-04-25 09:44 UTC, gnunicorn commented on proposals/3575-sync.md
> +**Long-polling Rule 1:** do not send multiple concurrent sliding sync requests to the server. If a request is lost in
Times out client-side or server-side? Server-side it means the server responds with an kinda-empty response, so the client is meant to process it and go ahead with the next request. On client side, it works the same as any other network error: restart the connection - or do that after some back-off interval depending on what your client timeout handler strategy is.

2023-04-27 15:26 UTC, DMRobertson commented on proposals/3575-sync.md
> + - For each timeline entry, ensure the `m.room.member` event for the `sender` of the timeline event is included exactly once per user ID.
As well as timeline entries, should this be triggered by typing notifications? (So that clients have a displayname to display and not just an MXID.) This seems to be what the test in https://github.com/matrix-org/sliding-sync/issues/55 is doing.

Probably best done with a sentence or two to say that
- extensions can also trigger a lazy loading member entry in `required_state`,
- extensions should not send down a duplicate event during live streaming (i.e. incremental syncs?)

and spell out explicitly in https://github.com/matrix-org/matrix-spec-proposals/pull/3961 that typing extensions should support lazy loading members in particular.

2023-05-03 09:35 UTC, bnjbvr commented on proposals/3575-sync.md
> +When this object is combined with an the additional object:
```suggestion
When this object is combined with the additional object:
```

2023-05-03 09:36 UTC, bnjbvr commented on proposals/3575-sync.md
> +      "include_old_rooms": { //sticky
Would it be worth eliminating the ambiguity here and stating the whole object is sticky, then?

2023-05-04 13:45 UTC, erikjohnston commented on proposals/3575-sync.md
> +          "required_state": [
Setting `content: {}` is more of a redaction than a deletion, which is a subtly different thing. I'm not 100% sure that we absolutely need the distinction, but I'm wary of designing out the ability to express it.

I don't know whether these sort of changes would be shown in the timeline UI at all.

2023-05-04 13:58 UTC, erikjohnston commented on proposals/3575-sync.md
> +      "name": "The calculated room name",
I'm wary of regressing our ability to have native language names given we have many users in non-English speaking countries. Is this something we have buy in from the relevant teams (including customer facing teams)?

While we *could* fix this by introducing locale concept... that is quite a big change I don't foresee us doing any time soon (unless its done as part of SS work).

2023-05-04 15:21 UTC, erikjohnston reviewed
Looks good, mostly I'm concerned about ensuring that the server is given enough flexibility that it can implement these APIs efficiently.

2023-05-04 15:21 UTC, erikjohnston commented on proposals/3575-sync.md
> +`/.well-known/matrix/client` config:
This probably should have been done as part of `/_matrix/client/versions` or `/capabilities` maybe?

2023-05-05 09:51 UTC, kegsay commented on proposals/3575-sync.md
> +  "bump_event_types": [ "m.room.message", "m.room.encrypted" ],
Unfortunately the client UX is rather particular around this, and I do have to agree with the points they make. Here's some examples:
 - You have a muted, low priority room like Matrix HQ. You don't want it to bump to the top of your room list at all, unless you get directly @mentioned. 
 - You have a normal public room like #dendrite - you don't want membership changes or reactions to bump this room to the top of the list.
 - You have a DM - you _do_ want membership changes, reactions, etc to bump this room to the top of the list.

I share your concerns around efficiency however. Currently the proxy only really handles the `m.room.message` type correctly, because of precisely the problem you outline. This is further complicated by extensible events which could easily be multiple of these things (a message and a reaction for example). Perhaps we can restrict this to message events (which would correctly ignore member changes but would include reactions) but there are UX tradeoffs then.

2023-05-05 09:55 UTC, erikjohnston commented on proposals/3575-sync.md
> +  "bump_event_types": [ "m.room.message", "m.room.encrypted" ],
Hmm, interesting. Do you know if these are hypothetical examples or something we're actually planning to implement? Some of those we just can't implement for E2E rooms.

How bad is it if the client gets told about Matrix HQ style stuff and then don't bump it up the room list? I guess it takes up a slot, though that is less bad in the persistent case?

2023-05-05 09:57 UTC, kegsay commented on proposals/3575-sync.md
> +**Long-polling Rule 1:** do not send multiple concurrent sliding sync requests to the server. If a request is lost in
This doesn't involve creating new TCP connections. This is specifically around application level sliding sync requests. You don't need to send all the keys again for a simple timeout, only if the connection is explicitly expired with the error code mentioned in this MSC. In practice this means, when you send a request:
 - if it times out, retry.
 - if the request params change e.g the client scrolls a list, interrupt the request and send a new one. If your client cannot interrupt requests you can just send a new one, but then you _should_ ignore the response to the earlier request if you get one back.

The main thing you're trying to avoid here is if you send two distinct requests (i.e different req params) with the same `?pos=` then it can become impossible to know what the server-side state will be, and you risk getting out of sync.

2023-05-05 09:58 UTC, kegsay commented on proposals/3575-sync.md
> +to a stream-orientated protocol like WebSockets in the future.
Yes.

2023-05-05 09:59 UTC, kegsay commented on proposals/3575-sync.md
> +endpoint in Matrix.
We can probably have a grace period on it yeah, similar to connections today.

2023-05-05 10:00 UTC, kegsay commented on proposals/3575-sync.md
> +value and not introspect it.
Potentially, yes it does. I would rather not add an extra piece of data (session ID) to client book keeping, which implies it probably will have to live in `pos`. The proxy currently won't allow >1 session per access token.

2023-05-05 10:02 UTC, kegsay commented on proposals/3575-sync.md
> +      // are changed. Elements in this array are ORd together to produce the final set of state events
Yes, as explained in https://github.com/matrix-org/matrix-spec-proposals/blob/kegan/sync-v3/proposals/3575-sync.md#commonalities-between-the-room-subscription-api-and-sliding-window-api

2023-05-05 10:03 UTC, erikjohnston commented on proposals/3575-sync.md
> +**Long-polling Rule 1:** do not send multiple concurrent sliding sync requests to the server. If a request is lost in
> * if the request params change e.g the client scrolls a list, interrupt the request and send a new one. If your client cannot interrupt requests you can just send a new one, but then you _should_ ignore the response to the earlier request if you get one back.

Doesn't that contradict:

> The main thing you're trying to avoid here is if you send two distinct requests (i.e different req params) with the same `?pos=` then it can become impossible to know what the server-side state will be, and you risk getting out of sync.

In that, if the client "cancels" the outbound request the server may already have processed it and sent the response down. The client will then send out another request with different req params with the same `pos`, as it is ignoring the response from the cancelled request?

2023-05-05 10:04 UTC, kegsay commented on proposals/3575-sync.md
> +      "ranges": [ [0,99] ],
Potentially, though we'd need to make sure clients see that the high index isn't the end of the room list (i.e it is `< count`) and so know to page in more data if they need it. I feel this will complicate client impls.

2023-05-05 10:05 UTC, kegsay commented on proposals/3575-sync.md
> +      "initial": true,
Agreed, that sounds like a better name imo.

2023-05-05 10:05 UTC, erikjohnston commented on proposals/3575-sync.md
> +      "ranges": [ [0,99] ],
This is a bit less of a concern if we allow clients to request all rooms, but its a potential nasty DoS vector server side.

2023-05-05 10:10 UTC, kegsay commented on proposals/3575-sync.md
> +#### Requesting all rooms
This mode of operation is specifically targeting bot use cases, so it's funny you mention this. There are other use cases for this as well though, notably for clients to pre-cache some data about all rooms e.g the room name and avatar, for fast local room searches (which is what EX does).

I feel an outright ban is impractical here, however I do think we can probably add a clause here to say:

> Servers are allowed to return all rooms over a series of responses rather than as a single response.

This addresses the concern about making no forward progress, and bounds the response size, without complicating clients. The pagination is effectively then the `?pos=` value and can only go in one direction. It would probably look something like (for 500 rooms):

 - Response 1: `SYNC 0,99` -> 100 `rooms` in top level map
 -  Response 2: `SYNC 100,199` -> 100 `rooms` in top level map
 -  Response 3: `SYNC 200,299` -> 100 `rooms` in top level map
 -  Response 4: `SYNC 300,399` -> 100 `rooms` in top level map
 -  Response 5: `SYNC 400,499` -> 100 `rooms` in top level map

2023-05-05 10:15 UTC, kegsay commented on proposals/3575-sync.md
> +### Bandwidth optimisations for persistent clients
> without a delta token we assume that when a room falls of the end of the list the client will delete the data, but if there is a delta token then clients will keep the copy of all rooms?

Your understanding is correct.

My concern with allowing dangling rooms (not in the subscribed window, but still remembered position wise) is that it can quickly get out of sync. If you get a new event in a room, in practice it doesn't always bump it to the top of the list. This means you could be getting events for rooms off the end of the list which you aren't aware of. The server then has to either:
 - resend all the data for that room when it reappears in your list
 - remember where it got up to and then send the deltas to you when it reappears in the list. <- this could be a huge delta.

2023-05-05 14:46 UTC, erikjohnston commented on proposals/3575-sync.md
> +### Bandwidth optimisations for persistent clients
I was more suggesting that we *stay* subscribed to the room rather than leaving it dangling, e.g. instead of `[A,B,C,D] -> [E,A,B,C]` we'd do `[A,B,C,D] -> [E,A,B,C,D]` until either the client or server specifically reduced the range again. The client would do it whenever it decided it wanted to reclaim some space, and the server could do it... whenever it wanted.

2023-07-13 11:13 UTC, DMRobertson commented on proposals/3575-sync.md
> +      // The MXC URL of the room's avatar, or the string "none" if this room has no prescribed avatar.
Because 
- the general design (correct me if I'm wrong @kegsay ) is that `null` is treated exactly the same as an unspecified field
- an omitted avatar field means "no change to the avatar".

2023-07-14 10:32 UTC, DMRobertson commented on proposals/3575-sync.md
> +      // The MXC URL of the room's avatar, or the string "none" if this room has no prescribed avatar.
Wording changed in 912621b4.

2023-07-14 10:53 UTC, gnunicorn commented on proposals/3575-sync.md
> +      "name": "The calculated room name",
I agree that trying to keep i10n out of the protocol seems like the better approach. In the [rust SDK we made it more explicit](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/enum.DisplayName.html#variant.Calculated) whether the name was calculated or set. We could take a similar approach here by having a smarter type handing down the actual information for the calculation. Something like (don't take that format to literal, it's from top of my head):

```
"calculated_name": "Kate Jackson, Farrah Fawcett and Jaclyn Smith"
"name_source": { "format": "dm", "heroes_names": ["Kate Jackson", "Farrah Fawcett", "Jaclyn Smith" }
```

2023-07-16 10:40 UTC, erikjohnston commented on proposals/3575-sync.md
> +}
I'm a bit concerned that this API will make it easy for clients to "forget" to unsubscribe from rooms, and you'd end up with clients slowly racking up lots of room subscriptions. Personally, I'd be tempted to change this such that every request you need to specify which rooms the client wants to remain subscribed to :shrug:

2023-07-31 13:47 UTC, TheJonny commented on proposals/3575-sync.md
> +   to the left or the right depending on where the closest empty space is.
- we just could forbid this? like "the server MUST ensure that this is unique."
- An alternative to keeping track of empty space would be to always have it in the end, that is moving to the front on DELETE and to the back on INSERT.

2023-07-31 13:55 UTC, TheJonny commented on proposals/3575-sync.md
> +   the range arrive from the server.
> slightly confused about why we need both `DELETE` and `INVALIDATE`.

if i understand it correctly, DELETE(i) is not INVALIDATE(i,i), as `DELETE(i); INSERT(r,j)` with `window[i] =r`  does not need to send the information about room `r` in the `rooms` section of the response.

but is there any difference between invalidated entries and entries, that are deleted and not inserted again in the same response? is the client required to remember them?

2023-08-02 15:59 UTC, gnunicorn commented on proposals/3575-sync.md
> +   the range arrive from the server.
I think the idea of invalidated is for performance reasons... assume the user scrolls is rather large list, then all these above can be kept around as invalidated in particular if you have an bouncer that only updates them once the scrolling is clear where to land. Rather than showing _no_ information, you show _stale_ information...

2023-08-16 14:43 UTC, Hywan commented
`timestamp` has been added onto `SlidingSyncResponse`'s `room.$room_id`, https://github.com/matrix-org/sliding-sync/pull/247.

2023-09-19 08:44 UTC, benkuly commented on proposals/3575-sync.md
> +There are two main alternatives to this proposal:
Wouldn't be one alternative to use a more generic and common protocol like GraphQL? This would allow to subscribe to different room lists or timelines, to filter data and more, too. There are also many libraries implementing GraphQL, so there is no need to force all SDKs, clients and servers to implement a completely new and very complex sync protocol.

I think it should at least be discussed instead of reinventing the wheel.

2023-10-17 02:48 UTC, tezlm commented on proposals/3575-sync.md
> +      "filters": {
perhaps `null` in the spaces filter could mean "rooms that aren't in any space"

2023-10-18 16:48 UTC, DMRobertson commented
Is the returned `required_state` that at the end or the start of the timeline? (GH is refusing to render the pull request changes, so I can't leave a nice review comment, sorry.)

2023-11-09 17:00 UTC, kegsay commented on proposals/3575-sync.md
> +There are two main alternatives to this proposal:
Added https://github.com/matrix-org/matrix-spec-proposals/blob/kegan/sync-v3/proposals/3575-sync.md#graphql

2023-11-17 16:25 UTC, kegsay commented
The end. It is the current state.

2024-05-02 20:18 UTC, MadLittleMods commented on proposals/3575-sync.md
> + - The client wants to do a **one-shot request** for some data, without incurring latency/bandwidth penalties with all the activity on the user's account. Without concurrent connections, it isn't pos
> The number of concurrent connections is N+1, where N is the number of active concurrent connections.

What is this trying to convey (can someone re-word)? I'm reading this as "a dog is a dog"

2024-05-02 20:49 UTC, MadLittleMods commented on proposals/3575-sync.md
> +        // room ID in the m.space.child event.
Why do we want to recursively find the latest room? What benefit for this extra work?

It seems like the new room would also be part of the space so it will be included anyway.

And tombstoned rooms would be filtered out depending on `include_old_rooms` (see *Tombstones* section as well).

2024-05-03 07:56 UTC, t3chguy commented on proposals/3575-sync.md
> +        // room ID in the m.space.child event.
> It seems like the new room would also be part of the space.

Only if the user upgrading had permissions to manage the space (and was on a client e.g. EW/ED which had this logic) - quite a lot of spaces are soft-broken where they only know about old versions of rooms.

2024-05-03 08:02 UTC, t3chguy commented on proposals/3575-sync.md
> +brand new endpoint, no other keys or fields need prefixing.
Currently there is no good way for a client to detect presence of a server's support for this MSC unless they are supporting it via proxy (detected via well-known).

If a client tries to make a request via `POST` to the above sync endpoint and the environment is actually running a proxy on the same subdomain then you end up losing `to_device` messages as the proxy starts a new legacy sync stream against the same access token.

Can we please add an entry to https://spec.matrix.org/v1.10/client-server-api/#get_matrixclientversions `unstable_features` to enable the server to express that it has native support.

Workarounds I tried:

OPTIONS request: 200 from the proxy, 204 from Synapse itself
HEAD request: 405 from the proxy, 404 from Synapse itself

2024-05-03 17:50 UTC, turt2live commented on proposals/3575-sync.md
> +brand new endpoint, no other keys or fields need prefixing.
In lieu of the MSC suggesting something itself, I am assuming `org.matrix.msc3575` will be used.

2024-05-06 17:48 UTC, MadLittleMods commented on proposals/3575-sync.md
> +        // room ID in the m.space.child event.
Seems like if the spaces still know about the old rooms, people will visit the old room, be pointed to the new one and can ask the admin to fix space/room relationship.

2024-05-07 07:31 UTC, t3chguy commented on proposals/3575-sync.md
> +        // room ID in the m.space.child event.
@MadLittleMods sure, except the space admin might not even be in the room for them to as ask. So they'll likely end up asking the wrong admin.

2024-05-24 07:59 UTC, sidewinder94 commented on proposals/3575-sync.md
> +        "url": "https://slidingsync.proxy.url.here"
Can this URL include a path, or should it be a base domain only?

Related issue : https://github.com/element-hq/element-web/issues/27496

2024-05-25 05:38 UTC, spantaleev commented on proposals/3575-sync.md
> +        "url": "https://slidingsync.proxy.url.here"
The original definition of "URL" probably goes back to some RFC from decades ago. I have not looked into it and cannot quote it.

That said, I believe a URL, by definition, contains a path component. The fact that the path component of this `url` field is ignored is quite strange. Ignoring an `#anchor`, etc., - sure, but.. ignoring the path is surprising.

2024-05-25 09:40 UTC, networkException commented on proposals/3575-sync.md
> +        "url": "https://slidingsync.proxy.url.here"
I'd say this MSC would have to clarify if `"org.matrix.msc3575.proxy".url` acts like `"m.homeserver".base_url`, for example (as far as I can see the spec doesn't include a formal definition for what a "base url" is either and in the [web url spec](https://url.spec.whatwg.org/#concept-base-url) it's more of an implementation detail as well, although its meaning could be derived form one of the algorithms defined there).

That being said, from what I can see `org.matrix.msc3575.proxy` is only relevant until sync v3 is stable. At that point homeservers are expected to have native implementations of sync v3 (or a proxy would have to hook into the `/_matrix/client/v4/sync` endpoint directly)

2024-05-26 13:46 UTC, EdGeraghty commented on proposals/3575-sync.md
> +        "url": "https://slidingsync.proxy.url.here"
FWIW, the ElementX implementation honours the paths in the URL

2024-05-28 08:15 UTC, t3chguy commented on proposals/3575-sync.md
> +        "url": "https://slidingsync.proxy.url.here"
The section right above that which is highlighted explains an absolute URL path rather than a relative one

2024-05-30 19:39 UTC, MadLittleMods commented on proposals/3575-sync.md
> +        // The server will inspect the m.space.child state events for the JOINED space room IDs given,
Should this also include public spaces that you haven't joined?

2024-05-30 19:40 UTC, MadLittleMods commented on proposals/3575-sync.md
> +        // A list of spaces which target rooms must be a part of, as m.space.child state events.
Does this act like the `tags` filter below where a room can belong to any one of the spaces listed (OR'd)?

2024-05-30 19:56 UTC, MadLittleMods commented on proposals/3575-sync.md
> +        // and filter the room list based on the INVITED/JOINED children room IDs.
The phrasing in this comment is a bit weird. This is in the context of a filter for the rooms in the sync response we already have, whereas it sounds like we're trying to discover rooms in the space.

Maybe this sounds more clear:

```suggestion
        // The server will inspect the `m.space.child` state events for the JOINED space room IDs given,
        // and filter the sync room list based on the space children room IDs listed.
```

2024-05-30 20:10 UTC, MadLittleMods commented on proposals/3575-sync.md
> +        // room ID in the m.space.child event.
Same reasoning as the [other comment](https://github.com/matrix-org/matrix-spec-proposals/pull/3575#discussion_r1621361512).

> The phrasing in this comment is a bit weird. This is in the context of a filter for the rooms in the sync response we already have, whereas it sounds like we're trying to discover rooms in the space.
> 
> Maybe this sounds more clear:

```suggestion
        // If the child room has a `m.room.tombstone` event, then the search should recursively navigate
        // until we find the the latest room and consider those room IDs as part of the space.
```

2024-05-30 20:18 UTC, MadLittleMods commented on proposals/3575-sync.md
> +        // room ID in the m.space.child event.
Kinda feels like the same situation as a song playlist on Spotify/YouTube, etc. I'm not blaming the new song for not being in the playlist yet, I'm going to the playlist author to fix it.

Do we try to resolve room upgrades anywhere else?

2024-05-30 20:21 UTC, MadLittleMods commented on proposals/3575-sync.md
> +        // A list of spaces which target rooms must be a part of, as m.space.child state events.
Answered at https://github.com/matrix-org/matrix-spec-proposals/pull/3575#discussion_r1113928699,

> Assuming the client is joined to spaces `["!a:example.org", "!b:example.org"]` then a room can pass the filter if the room belongs to ANY one of the spaces given.

2024-06-13 21:52 UTC, MadLittleMods commented on proposals/3575-sync.md
> +      "!sub1:bar": { // sticky
What should happen if you try to subscribe to a room you are not part of (or not allowed)?

The easy option would be to ignore it but then clients have no feedback about what they did wrong.

Perhaps entries in the `rooms` map could also have an `errcode`/`error` field.

2024-06-25 15:28 UTC, MadLittleMods commented on proposals/3575-sync.md
> +      ],
What should happen for `invite` rooms?

If we copy Sync v2, then the invite room will only have `invite_state` (no `timeline` events, `limited`, `prev_batch` token, or `required_state`).

Perhaps we could make the `rooms` more uniform regardless of membership though. The hard case is how these fields should be set in cases where the user's room membership is `invite` with `shared`/`joined` history visibility where they can't see any timeline events until they join.

**Where should the `prev_batch` token be pointing to?** If we do it just like other rooms, we paginate up to the `timeline_limit`, then all of those events are filtered out (because we're not joined yet) and the `prev_batch` token points to a place before those events that we never saw. And then potentially when we `join`, we will miss those events depending on what the client does.

If we change the scenario to a room with `world_readable` or `invited` history visibility where timeline events would be returned when you are invited; The answer is timeline events are returned, `limited` is set respectively, and `prev_batch` points to the first event to continue paginating (no problems there).

For `ban`/`leave`, we can just query for timeline events up to the point where they were banned/left (no problem here either).


---

*First discussed in https://github.com/element-hq/synapse/pull/17320#discussion_r1646581077*

2024-07-08 23:33 UTC, MadLittleMods commented on proposals/3575-sync.md
> +      ],
Instead of returning stripped state for `heroes`, we could simply return the User ID's of the heroes like Sync v2 and return the full membership event in `required_state` like we're already doing for `$LAZY`-loading room memberships.

2024-07-08 23:47 UTC, MadLittleMods commented on proposals/3575-sync.md
> +      "include_heroes": true,
What use case is `include_heroes` useful for?

`heroes` will already be populated when the room doesn't have a `m.room.name` set. And you can specify `$LAZY`-loading room members to get relevant members in the room.

2024-07-09 16:45 UTC, MadLittleMods commented on proposals/3575-sync.md
> +      "include_heroes": true,
`heroes` are used to [calculate the room name](https://spec.matrix.org/v1.10/client-server-api/#calculating-the-display-name-for-a-room) so being deterministic is useful so the room name doesn't change that much. `heroes` are already automatically returned when the room doesn't have `m.room.name` set. Since this behavior is already built-in and automatic, this `include_heroes` option isn't necessary for room name calculation.

Are `heroes` used for anything else? If not, then this option isn't necessary

---

Displaying a few avatar bubbles to preview some of the room members could be useful:

![](https://github.com/matrix-org/matrix-spec-proposals/assets/558581/e1971e6a-cd3a-4192-b909-3ccf4112f248)

A similar effect could be achieved by `$LAZY`-loading room members and fetching enough timeline events. `heroes` could also work but it will always only be up-to 5 members and won't reflect who's currently chatting if it's a big room. You could also fetch all members in the room by using `required_state: [["m.room.member", "*"]]` but can be a bit burdensome to parse in very large rooms. This use case might be better served by a specific extension to be able to specify the number of members you want to fetch and how you want them sorted.

2024-07-09 20:47 UTC, MadLittleMods commented on proposals/3575-sync.md
> +      ],
I think I found the distinction for why we don't do this: local vs remote room

For a room where another local user is in the room, this kind of thing makes sense to me. Being `invited` to a room probably means you should have access to the room (access to the full state of the room and events based on history visibility) (no security concern). Stripped state makes more sense for `knock` rooms where you don't have access yet.

But the problem comes when you're the first one on your server to be invited to the room over federation to a remote room. When you [receive a federated invite](https://spec.matrix.org/v1.10/server-server-api/#inviting-to-a-room), you only have access to `event.unsigned.invite_room_state` so that's all that you can return to the client. You would have to go through the [`make_join`/`send_join` process](https://spec.matrix.org/v1.10/server-server-api/#joining-rooms) to start participating in the room and query more info.

So it makes sense just to do the same thing for all `invite` rooms, just return stripped state.

2024-07-09 20:57 UTC, MadLittleMods commented on proposals/3575-sync.md
> +      ],
Related to https://github.com/matrix-org/matrix-spec/issues/380. As an example, when someone is invited to a room, we don't even have the `heroes` necessary to calculate the room name if the room doesn't have `m.room.name` set.

2024-07-09 21:27 UTC, MadLittleMods commented on proposals/3575-sync.md
> +      "name": "The calculated room name",
To preface this: I'm on the side of not trying to calculate room names. Just leave it to clients to use the explicitly set room name or calculate it themselves via the `heroes`.

One thing, I'm not sure about is if the `name` field should strictly be the value from the `m.room.name` state event or whether we should also fallback to the `m.room.canonical_alias`. The existing spec currently says that `heroes` should be returned ["if the room’s `m.room.name` or `m.room.canonical_alias` state events are unset or empty."](https://spec.matrix.org/v1.10/client-server-api/#_matrixclientv3sync_roomsummary) so it might make sense to fallback.

2024-07-09 21:38 UTC, MadLittleMods commented on proposals/3575-sync.md
> +        {"user_id":"@alice:example.com","displayname":"Alice","avatar_url":"mxc://..."},
Should we just use the existing definition of [stripped state](https://spec.matrix.org/v1.10/client-server-api/#stripped-state)?

> Stripped state events can only have the `sender`, `type`, `state_key` and `content` properties present.

2024-07-10 08:16 UTC, bnjbvr commented on proposals/3575-sync.md
> +      "name": "The calculated room name",
Agreed; calculing room names server-side is doomed to cause incorrect i10n (as a room name computed from heroes would look, for all languages, like "person A **and** person B"), and closes the door to customization options (even though that argument is feeble; the user value in being able to choose how many heroes are used for a fallback calculated room name would likely be quite low).

2024-07-10 08:47 UTC, bnjbvr commented on proposals/3575-sync.md
> +      "include_heroes": true,
heroes are already automatically returned when the room doesn't have m.room.name set.

> Are heroes used for anything else? If not, then this option isn't necessary

They're exposed to the EX apps at least, which use those to compute a hash that serves to determine a unique color for a room's visual entry in the room list. I think that color will also match what EW displays, since it's based on the same algorithm. That computation (be it done by the SDK or the EX apps themselves) requires the heroes to *always* be present.

2024-07-10 16:56 UTC, MadLittleMods commented on proposals/3575-sync.md
> +      "include_heroes": true,
Thanks for sharing another reference @bnjbvr :slightly_smiling_face:  

> use those to compute a hash that serves to determine a unique color for a room's visual entry in the room list

Why not just hash against the room ID?

Feels like the room color would change over time as the `heroes` will shift around until 5 people are in the room and will shift as people leave the room.

As far as I can tell, Element Web just bases it off the Matrix ID (for users) and room ID (for rooms):

 - [`useIdColorHash(...)`](https://github.com/element-hq/compound-web/blob/main/src/components/Avatar/useIdColorHash.ts#L17-L31)
 - [`compound-web` -> `src/components/Avatar/Avatar.tsx`](https://github.com/element-hq/compound-web/blob/15eefea5f821d546e6ea687c6da4b10af53b6f81/src/components/Avatar/Avatar.tsx#L107)
 - [`matrix-react-sdk` -> `src/Avatar.ts`](https://github.com/matrix-org/matrix-react-sdk/blob/19f9f9856451a8e4cce6d313d19ca8aed4b5d6b4/src/Avatar.ts#L107C17-L127)

> That computation (be it done by the SDK or the EX apps themselves) requires the heroes to always be present.

For Sync v2, `heroes` is only present for [`join` rooms](https://spec.matrix.org/v1.10/client-server-api/#_matrixclientv3sync_joined-room). And [in Synapse](https://github.com/element-hq/synapse/blob/3232bc29826d030e62c034ec582c73532bc7e465/synapse/handlers/sync.py#L2920-L2957), they are only returned when lazy-loading and (there are membership changes or initial sync).

So the color will change yet again based on membership if `heroes` was taken into account.

Can you share a link to the code in ElementX for this?

2024-07-10 16:57 UTC, bnjbvr commented on proposals/3575-sync.md
> +      "include_heroes": true,
cc @jmartinesp @pixlwave ^

2024-07-10 17:28 UTC, pixlwave commented on proposals/3575-sync.md
> +      "include_heroes": true,
> Why not just hash against the room ID?

We do this most of the time, but when the room is a 1:1 DM then we use the other member's user ID so that the room's placeholder avatar matches the user's placeholder avatar. Web does this too I believe.

> Displaying a few avatar bubbles to preview some of the room members could be useful:

This is the future plan, there designs for avatar clusters of max 4 people so the hero limit of 5 isn't an issue for us.

<img width="262" alt="Screenshot 2024-07-10 at 6 28 08 PM" src="https://github.com/matrix-org/matrix-spec-proposals/assets/6060466/b7a2911f-121b-4bd4-8f31-4a8573ce873f">

2024-07-10 17:38 UTC, pixlwave commented on proposals/3575-sync.md
> +      "include_heroes": true,
Not sure if you need code too, but the check is [here](https://github.com/element-hq/element-x-ios/blob/84e785367b942b601016ee539b14ce84d63d9fd3/ElementX/Sources/Services/Room/RoomSummary/RoomSummary.swift#L87-L93) and rendering [here](https://github.com/element-hq/element-x-ios/blob/develop/ElementX/Sources/Other/SwiftUI/Views/RoomAvatarImage.swift)

2024-07-10 18:42 UTC, MadLittleMods commented on proposals/3575-sync.md
> +      "include_heroes": true,
Thanks for the extra clarification!

It appears that `heroes` are only necessary for DMs (or group chats), aligning perfectly with the server's automatic behavior of providing `heroes` when a room name is not specified.

This further supports the argument that a separate `include_heroes` option is unnecessary.

2024-07-10 19:23 UTC, pixlwave commented on proposals/3575-sync.md
> +      "include_heroes": true,
Does that mean we wouldn't get the heroes for the "Soccer Club" example in the screenshot above?

2024-07-11 09:02 UTC, bnjbvr commented on proposals/3575-sync.md
> +      "include_heroes": true,
(A small note: there are other clients than Element in the world, and we should also keep it flexible for these.)

2024-07-11 14:33 UTC, pixlwave commented on proposals/3575-sync.md
> +      "include_heroes": true,
Let me see if I can find out actual product requirements for this on our side.

2024-07-24 17:59 UTC, MadLittleMods commented on proposals/3575-sync.md
> +  // to use sliding list semantics. This map is an aggregation of all rooms which can be returned
> If there are no`ops` (because there are no `ranges`) then all rooms which match the list filters will be present in this list, unordered. This functionality is useful for clients which do not want to use sliding list semantics.

This seems leftover before `slow_get_all_rooms` was added

2024-09-05 18:14 UTC, MadLittleMods commented on proposals/3575-sync.md
> +      ],
Conversation continued in https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1745962353

2024-09-19 20:56 UTC, MadLittleMods commented on proposals/3575-sync.md
> +      "!sub1:bar": { // sticky
Conversation continued in https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1767582765

2024-11-20 19:54 UTC, melroy89 commented
I'm using sliding sync, how this PR not be merged yet?

2024-11-21 11:19 UTC, richvdh commented
Shouldn't this be closed in favour of MSC4186?

2025-01-15 10:17 UTC, kegsay commented
Superceded by https://github.com/matrix-org/matrix-spec-proposals/pull/4186

2025-01-15 10:17 UTC, closed without merging

2025-01-15 11:24 UTC, ara4n commented
for the record, i think the bits of MSC3575 which make bandwidth O(1) with number of rooms (as opposed to MSC4186, which is O(N) bandwidth) are still a hard prerequisite for low-bandwidth Matrix situations like MSC3079: it makes no sense to ship a low bandwidth transport like MSC3079 which takes a handful of bytes to send or receive new messages... but spends hours chewing tens of megabytes syncing stuff in the background before the app is fully usable (as MSC4186 behaves).

If we're closing MSC3575, then in future we'll need to open a MSC to extend MSC4186 to add the sliding windows back in to support LB. (Or, more likely, i'd make a case to reopen this one to avoid making the MSC tree even more confusing...)

2025-09-13 04:29 UTC, sahilverma64815495-svg commented on proposals/3575-sync.md
> + - Core API: The minimumal API to be sync v3 compatible.
Hii