Mark `from` parameter as optional for `/messages`
matrix-org/matrix-spec-proposals pull request #3638
Opened 2022-01-12 09:54 UTC by gsouquet

To merge when https://github.com/matrix-org/matrix-doc/pull/3567 lands

Preview: https://pr3638--matrix-org-previews.netlify.app

2022-01-12 16:20 UTC, turt2live requested changes
also a changelog entry please :) 

Something like: 

```
Make `from` optional on `GET /_matrix/client/v3/messages` as per [MSC3567](https://github.com/matrix-org/matrix-doc/pull/3567).
```

2022-01-12 16:20 UTC, turt2live commented on data/api/client-server/message_pagination.yaml
> -          required: true
above the `description`, can we get `x-changedInMatrixVersion: "1.2"` please? It might also need to be made to work with query parameters as I'm not sure that's been considered.

2022-01-17 09:18 UTC, gsouquet commented
> also a changelog entry please :)

@turt2live where does that changelog should exist? I've looked at recent merged PRs and it's unclear to me where that should go?

2022-01-17 14:56 UTC, uhoreg commented
The changelog goes in `changelogs/client_server/newsfragments` for changes to the client-server spec.  In general, you create a file named <pr_number>.<type>, where <type> is one of the types listed in `changelogs/pyproject.toml`.  For example, for this PR, this would probably count as type "feature" ("Backwards compatible changes"), so you would put the changelog line in `changelogs/client_server/newsfragments/3638.feature`.

2022-01-17 20:51 UTC, turt2live commented on data/api/client-server/message_pagination.yaml
>                  "start": "t47429-4392820_219380_26003_2265",
looks like the formatting here and on `chunk` got changed unexpectedly.

2022-02-17 09:07 UTC, richvdh commented
@gsouquet are you able to update this?

2022-02-17 13:43 UTC, clokep commented on data/api/client-server/message_pagination.yaml
> +          x-changedInMatrixVersion: "1.2"
This probably needs to be 1.3 now?

2022-03-07 12:01 UTC, richvdh commented
We'll need to reopen this against https://github.com/matrix-org/matrix-spec.

2022-03-25 09:27 UTC, jplatte commented
> We'll need to reopen this against [matrix-org/matrix-spec](https://github.com/matrix-org/matrix-spec).

Done: https://github.com/matrix-org/matrix-spec/pull/1002

2022-03-25 09:27 UTC, closed without merging