MSCXXXX: Bundled aggregations for server side search
matrix-org/matrix-spec-proposals pull request #3666
Opened 2022-01-21 17:27 UTC by clokep

2022-01-21 17:30 UTC, clokep commented on proposals/3666-bundled-aggregations-for-search.md
> +N/A
Or maybe it should be under an unstable key in `unsigned`? 🤷

2022-01-26 19:00 UTC, clokep commented
This now has an implementation which I've linked in the description: matrix-org/synapse#11837.

2022-02-08 17:50 UTC, turt2live requested changes

2022-02-08 17:50 UTC, turt2live commented on proposals/3666-bundled-aggregations-for-search.md
> +# MSC3666: Bundled aggregations for server side search
This needs a listed client-side implementation for me to feel comfortable having this go ahead.

2022-02-17 14:22 UTC, clokep commented on proposals/3666-bundled-aggregations-for-search.md
> +# MSC3666: Bundled aggregations for server side search
I've added a client side implementation to the description (vector-im/element-ios#5565).

2022-02-23 22:46 UTC, turt2live commented
@matrix-org/spec-core-team the author has mentioned that this is now re-ready for review (it was already on the board, but in an awkward state. That state is now fixed)

2022-03-08 16:01 UTC, erikjohnston commented
@mscbot fcp merge

2022-03-22 15:31 UTC, richvdh reviewed
lgtm modulo a couple of minor wording tweaks

2022-03-22 15:31 UTC, richvdh commented on proposals/3666-bundled-aggregations-for-search.md
> +The server side search API (`POST /search`) for the `room_events` category will
a link to the spec is helpful for readers:

```suggestion
The server side search API ([`POST /search`](https://spec.matrix.org/v1.2/client-server-api/#post_matrixclientv3search))
for the `room_events` category will
```

2022-03-22 15:31 UTC, richvdh commented on proposals/3666-bundled-aggregations-for-search.md
> +Per MSC2675 the `unsigned` field of the results would include `m.relations` where
minor clarification to emphasise this is a change, rather than a statement of the status quo:

```suggestion
As in MSC2675, the `unsigned` field of the results would include `m.relations` where
```

2022-03-22 15:31 UTC, richvdh commented on proposals/3666-bundled-aggregations-for-search.md
> +returned, these appear as the following fields:
grammatical nit: [comma splice](https://en.wikipedia.org/wiki/Comma_splice)

```suggestion
returned; these appear as the following fields:
```

2022-03-22 15:31 UTC, richvdh commented on proposals/3666-bundled-aggregations-for-search.md
> +N/A
I don't think that's required.

2022-03-29 16:03 UTC, anoadragon453 approved these changes

2022-04-10 22:23 UTC, merged

2022-05-27 03:30 UTC, turt2live commented
Spec PR: https://github.com/matrix-org/matrix-spec/pull/1062

2022-06-08 21:33 UTC, turt2live commented
Merged 🎉