MSCXXXX: Enforce integer power levels
matrix-org/matrix-spec-proposals pull request #3667
Opened 2022-01-21 22:29 UTC by neilalexander

2022-01-24 21:07 UTC, turt2live reviewed
Generally seems fine to me - just a bit of clarity before I think this is ready for FCP.

2022-01-24 21:07 UTC, turt2live commented on proposals/msc3667-enforce-integer-power-levels.md
> +associated headaches with string parsing.
For clarity, which system are we hoping to enforce this within? If it's the auth rules then they might be complicated to represent, but if it's just evaluation-time parsing (ie: non-int is default power level) then that might be a bit easier to write.

2022-01-24 21:07 UTC, turt2live commented on proposals/msc3667-enforce-integer-power-levels.md
> +experimental room version is based on room version 7, with the additional requirement that power
why room version 7? is there something in v8 or v9 which makes this more complicated to implement?

(concerned as v10 would be based on v9 currently, and this MSC seems to have deliberately chosen a different room version)

2022-01-24 21:07 UTC, turt2live commented on proposals/msc3667-enforce-integer-power-levels.md
> +# MSC3667: Enforce integer power levels
just to pre-empt some potential discussion: other event types, like join rules, aren't really subject to the same nuances that integer-based power levels are. As a power event itself in state res v2, the power levels are critical for determining whether or not a user can do something - the same issue can theoretically arise from incorrect membership or join rule, however the handling of those two events is targeted at the specific enum values whereas power levels are a range.

2022-01-25 00:18 UTC, neilalexander commented on proposals/msc3667-enforce-integer-power-levels.md
> +experimental room version is based on room version 7, with the additional requirement that power
I just based it off the most recent version I know to be stable in Dendrite, no other reason. I could easily update it to follow v8 or v9 rules with just a couple lines changed.

2022-01-25 00:21 UTC, neilalexander commented on proposals/msc3667-enforce-integer-power-levels.md
> +associated headaches with string parsing.
I don't think we need to modify the auth rules themselves here. I think an acceptable outcome is that parsing the power level content at the beginning of event auth altogether fails, therefore auth fails with it. This is what the Dendrite implementation does currently. We don't attempt to fall back to a default level, although if anyone has feelings on whether that approach would be better, I'd welcome opinions.

2022-01-31 20:10 UTC, ShadowJonathan commented on proposals/msc3667-enforce-integer-power-levels.md
> +accurately, so we should not try to do so.
It is not specifically, i've drawn an algorithm to come close; ([original comment](https://github.com/matrix-org/matrix-doc/issues/3264#issuecomment-1026052546))

1. trim all whitespace
2. remove leading `+`
3. if leading character is `-`, remove and remember
4. remove leading zeroes (except the last one, if remaining string is all-zeroes)
5. interpret string as an integer
6. if `-` was encountered, negate the integer

I'm *plenty* sure this is how python does it, and i think at least a mention/help for the spec on how to start to parse the old values would help a ton.

2022-02-01 18:28 UTC, anoadragon453 commented on proposals/msc3667-enforce-integer-power-levels.md
> +behaviour in Synapse, string power levels are also accepted and parsed. The string parsing itself
This first sentence is a little confusing. String power levels are not accepted by the spec - but in practice are often accepted by homeserver implementations as not doing so would break existing rooms.

2022-02-01 18:28 UTC, anoadragon453 commented on proposals/msc3667-enforce-integer-power-levels.md
> +a power level but Dendrite will outright fail to parse it.
It would be good to have a line here explicitly stating that: as a result, homeserver implementations may need to update their existing room version implementations to remain compatible with the spec.

2022-02-01 23:38 UTC, neilalexander commented on proposals/msc3667-enforce-integer-power-levels.md
> +behaviour in Synapse, string power levels are also accepted and parsed. The string parsing itself
Spec PR #3688 will formally allow today's behaviour into the spec for all room versions up to and including version 9, since this issue was still not yet fixed in Synapse. That will allow us and future implementations to preserve compatibility with existing rooms.

This MSC, on the other hand, will fix the problem in future room versions (hopefully from room version 10).

2022-02-01 23:43 UTC, neilalexander commented on proposals/msc3667-enforce-integer-power-levels.md
> +a power level but Dendrite will outright fail to parse it.
It is my hope that the wording in #3688 will be sufficient to cover what implementations should do today and then this MSC can focus on what we do to plug the hole going forward.

2022-02-02 02:04 UTC, turt2live commented on proposals/msc3667-enforce-integer-power-levels.md
> +associated headaches with string parsing.
Failing event auth sounds ideal - can we get words to that effect in the MSC? 😇

2022-02-02 02:06 UTC, turt2live commented on proposals/msc3667-enforce-integer-power-levels.md
> +a power level but Dendrite will outright fail to parse it.
(directionally, I think it's best to work on this MSC and that spec PR almost concurrently: the MSC can make reference to what the spec intended to say, as we know we'd accept a clarification about how stringy power levels work, and the spec PR can either continue working on inclusion or wait for this MSC to land and be assigned a room version)

2022-02-02 17:30 UTC, Sorunome commented on proposals/msc3667-enforce-integer-power-levels.md
> +# MSC3667: Enforce integer power levels
This MSC has some rather big issues: It implicitly changes the way rooms v1-v9 work, *requiring* implementations to add both string parsers for general stuff and bigints to their implementation for them to be able to claim support for those room versions. Bigints especially are a rather big hurdle to implement in quite some languages. Instead, synapse could fix its behaviour and people could side-upgrade to the same existing room version to fix the rooms properly. Synapse has to follow the spec, not the other way round.

2022-02-02 18:01 UTC, Sorunome commented on proposals/msc3667-enforce-integer-power-levels.md
> +# MSC3667: Enforce integer power levels
Ruma, for example, [has already stated](https://matrix.to/#/!bKOoBjzgyxiMyHIyLp:matrix.org/$dfBXs6oj3FA5YGtZDFQLVbVRcOoYjmrrxdrYygyyIT8?via=matrix.org&via=tedomum.net) that they [do not plan on implementing](https://matrix.to/#/!bKOoBjzgyxiMyHIyLp:matrix.org/$31OVhAm7GlOke2OEPSABzPgIVQpopKZ5cc3hie8hAos?via=matrix.org&via=tedomum.net) bigints, making ruma, and all projects that build ontop of it (e.g. conduit) impossible to support all currently existing room versions.

2022-02-02 18:03 UTC, turt2live commented on proposals/msc3667-enforce-integer-power-levels.md
> +# MSC3667: Enforce integer power levels
This MSC does not change the behaviour of v1 through v9 - it's considered a spec bug that those room versions did not previously document it.

2022-02-02 18:03 UTC, Sorunome commented on proposals/msc3667-enforce-integer-power-levels.md
> +# MSC3667: Enforce integer power levels
So then the spec is following synapse, and not the other way round?

2022-02-02 20:04 UTC, turt2live commented on proposals/msc3667-enforce-integer-power-levels.md
> +# MSC3667: Enforce integer power levels
We'll be publishing a document which explains how we reach these decisions soon (see https://github.com/matrix-org/matrix-doc/issues/3434 - just waiting on internal review), but the short version is that we have to balance a working federation against historically referenced implementations, and further consider that against the foundation's own values/rules and practicality of any decision.

In this case, Synapse formed the basis for the protocol in the early room versions and the issue has existed well beyond all reasonable expectation for it to be considered a Synapse bug. While unfortunate, it's considered exclusively a spec bug due to the timeline.

----

As an aside, please tone down the accusational language. We're not doing this because we feel like it or because it's fun - we're trying to correct an ancient issue as best we can in the most pragmatic way possible. Not everyone will be happy with the decisions, but that does not excuse bad behaviour.

The github repo is bound by the same code of conduct the community rooms are, and is enforced to the same degree. Everyone is trying to work off the same document and it really sucks when that document fails them - in these cases we aspire to work together to work on a solution and not let frustration of any kind get the better of us.

----

I'm resolving this thread as overly pointed discussion. Further discussion on why/how we reached the point of needing to specify stringy power levels is to be done in #matrix-spec:matrix.org on Matrix, not spread out over a dozen different places.

2022-02-02 20:12 UTC, Sorunome commented on proposals/msc3667-enforce-integer-power-levels.md
> +# MSC3667: Enforce integer power levels
requiring bigints effectively barricated most languages from being able to implement it, having such a spec makes no sense if people can't actually follow it. The spec loses its meaning. Broken rooms will have to upgrade one way or another, be it a /upgraderoom to a new version or the same version, doesn't matter from a UX perspective.

Soru made a comment on the MSC as the issue wasn't raised on the MSC itself yet.

2022-02-02 20:21 UTC, ShadowJonathan commented on proposals/msc3667-enforce-integer-power-levels.md
> +# MSC3667: Enforce integer power levels
I think this discussion is unrelated to this specific MSC, as it only paints the path forward.

#3688 details how to handle the historical aspect, so please comment there; 
https://github.com/matrix-org/matrix-doc/pull/3688#discussion_r796632174

2022-02-10 10:23 UTC, turt2live commented
This seems possible to implement in at least two implementations (Synapse and Dendrite), and overall this MSC seems ready to go. 

I'm not an expert on where the validation should be applied, but hopefully one of these folks is:

@mscbot fcp merge

2022-02-19 16:59 UTC, KitsuneRal requested changes

2022-02-19 17:30 UTC, ShadowJonathan commented on proposals/msc3667-enforce-integer-power-levels.md
> +as integers and reject events which try to define them as any other type. This removes all of the
My guess would be that it'd fall to canonical JSON integers, as that's the most loose bound in this context.

2022-02-19 22:02 UTC, kevincox approved these changes

2022-02-20 16:01 UTC, uhoreg commented on proposals/msc3667-enforce-integer-power-levels.md
> +as integers and reject events which try to define them as any other type. This removes all of the
> My guess would be that it'd fall to canonical JSON integers, as that's the most loose bound in this context.

That would be my interpretation as well, but it doesn't hurt to clarify.

```suggestion
as integers within the range defined by canonical JSON and reject events which try to define them as any other type. This removes all of the
```

2022-03-01 14:58 UTC, erikjohnston commented on proposals/msc3667-enforce-integer-power-levels.md
> +accurately, so we should not try to do so.
> so we should not try to do so

I think this is a little confusing to add here, as I read it as "current implementations shouldn't do this", rather than "we should avoid doing this in the future".

```suggestion
accurately. 
```

2022-03-01 15:21 UTC, richvdh commented on proposals/msc3667-enforce-integer-power-levels.md
> +> well as int('010', 8).
most of this isn't relevant as it requires an explicit base.

```suggestion
> If x is not a number ... then x must be a string, bytes, or bytearray instance
> representing an integer literal. Optionally, the literal can be preceded by + or -
> (with no space in between) and surrounded by whitespace. A base-10 literal consists of the digits 0
> to 9.
```

(notably, all the prefixes here are not valid)

2022-03-27 18:19 UTC, merged

2022-05-04 20:38 UTC, turt2live commented
This MSC is assigned to v10: https://github.com/matrix-org/matrix-spec-proposals/pull/3604

2022-05-30 21:10 UTC, turt2live commented
Spec PR: https://github.com/matrix-org/matrix-spec/pull/1099