get a msc number
matrix-org/matrix-spec-proposals pull request #3746
Opened 2022-02-25 22:28 UTC by AndrewRyanChama

2022-02-25 23:01 UTC, turt2live commented
@AndrewRyanChama when you get the chance, please sign off on the changes so we can include them down the line :)

2022-05-05 20:23 UTC, Sorunome commented on proposals/3746-image-reactions.md
> +      "key": "😀"
Just wanting to point out that the name identifier of emotes, the `:emote:` thing, could be the same for different emotes. As you put this into the `key` attribute here, synapse will think that it was the same reaction and "deduplicate" it, even if a different image. More appropriately would be to put the mxc url into the `key` attribute, as that is guaranteed to be unique.

2022-05-22 01:09 UTC, sumnerevans requested changes

2022-05-22 01:09 UTC, sumnerevans commented on proposals/3746-image-reactions.md
> +      "key": "😀"
I agree with this. I think that the fallback should be in a `shortcode` key in the content:

```jsonc
"content": {
  "m.relates_to": {
    "rel_type": "m.annotation",
    "event_id": "$abcdefg",
    "key": "mxc://matrix.org/VOczFYqjdGaUKNwkKsTjDwUa"
  },
  "shortcode": ":partyparrot:",
  "info": {
    // same
  }
}
```

For the record, Beeper has been doing this with our Slack and Discord bridges for a while now, and it works well.

The downside is that the fallback is annoying for clients that don't support it, but that's better than having reactions incorrectly grouped.

2022-08-05 13:57 UTC, ajbura commented on proposals/3746-image-reactions.md
> +      "key": "😀"
We’ve also implemented this approach in Cinny [[1]](https://github.com/cinnyapp/cinny/pull/686/commits/519f620cb7660b665602e3799bd63dff7e4382a6).

2022-09-05 12:39 UTC, HarHarLinks requested changes
I think this is generally a good idea which with some small tweaks has proven successful in the wild already.

2022-09-05 12:39 UTC, HarHarLinks commented on proposals/3746-image-reactions.md
> +In order to describe a reaction with an image, we simply include an mxc url and optionally [ImageInfo](https://github.com/matrix-org/matrix-doc/blob/f8b83b7fb1194ab48ee3461185c4764ebbfecc68/data/even
```suggestion
In order to describe a reaction with an image, we simply include an mxc url and optionally [ImageInfo](https://github.com/matrix-org/matrix-spec/blob/main/data/event-schemas/schema/core-event-schema/msgtype_infos/image_info.yaml) in the event content.
```

Perhaps this should state that the m.image spec is to be mirrored here. As commented elsewhere, optionally(?) including `body` as fallback, again the same as m.image, can be a good choice.

In what regard is ImageInfo useful to have here? Does any client implement it at this point? Maybe file type.
I think thumbnail won't be used anyway (unless your client uses it instead to reduce file size downloaded over cell when mobile? not sure that's realistic - rather display fallback shortcode) and dimensions don't matter as it will be scaled to fit into the reaction display area.

2022-09-05 12:39 UTC, HarHarLinks commented on proposals/3746-image-reactions.md
> +```
Perhaps the following process should be stated in order to define how to interpret these extended reaction events:
1. check presence of `url` field. If found we have a custom image reaction.
    1. read image info if present and apply any special logic(?)
2. read fallback from `body` (or `shortcode`, see [discussion above](https://github.com/matrix-org/matrix-spec-proposals/pull/3746/files#r878778175)), which can be used as fallback in case the image does not load/is otherwise invalid
4. use `m.relates_to.key` as MSC2677 literal reaction as usual, which is also the fallback for clients not implementing MSC3746.

2022-09-05 12:39 UTC, HarHarLinks commented on proposals/3746-image-reactions.md
> +    "info": {
I'm wondering if any considerations in hindsight to [MSC2545: Image Packs](https://github.com/matrix-org/matrix-spec-proposals/pull/2545) make sense, I suppose it could easily get tacked on in hindsight.

E.g. `"image_pack_source"` could point to the [source](https://github.com/Sorunome/matrix-doc/blob/soru/emotes/proposals/2545-emotes.md#image-sources) of the image pack used when the sender chooses to include it (e.g. it is a public image pack room), allowing others to discover image packs and start using them.

2022-09-05 13:53 UTC, uhoreg commented on proposals/3746-image-reactions.md
> +Many messaging services such as Slack and Discord allow for custom images for reacts, rather than only standard emoji. Currently Element will only show the plain text of the reaction key.  In order t
Please wrap your lines to ~80 to ~120 characters.

2022-09-05 14:00 UTC, uhoreg commented on proposals/3746-image-reactions.md
> +It's possible that different users will send reactions with different images under the same reaction key, either due to malicious action or collisions.  Reaction senders must take this into account a
I think it would be difficult for clients to ensure that they use a key that does not collide with other reactions.

Would it be sufficient to tell clients to send reactions using a key that conveys a similar meaning to the image?  In that way, clients that use the server-side aggregations will (as mentioned above) fall back to displaying only the key, so they won't be affected by collisions since they won't display the images.  And clients that don't use server-side aggregations will see the full events, and be able to distinguish the reactions based on the `url` field.

2023-06-30 22:49 UTC, sumnerevans commented on proposals/3746-image-reactions.md
> +      "key": "😀"
I have created https://github.com/matrix-org/matrix-spec-proposals/pull/4027 which intends to document what the implementations that already exist do.

2023-07-06 17:03 UTC, closed without merging