Add a default push rule to ignore `m.room.server_acl` events
matrix-org/matrix-spec-proposals pull request #3786
Opened 2022-04-30 15:04 UTC by SimonBrandner

For https://github.com/vector-im/element-web/issues/20788

<hr>

[`matrix-js-sdk` PR](https://github.com/matrix-org/matrix-js-sdk/pull/2333)

2022-05-04 09:10 UTC, richvdh commented on proposals/3786-acl-notifs.md
> +    ]
`dont_notify` is a no-op, so this should just be:

```suggestion
    "actions": []
```

2022-05-04 09:20 UTC, richvdh commented on proposals/3786-acl-notifs.md
> +    "rule_id": ".m.rule.room.server_acl",
this should probably be `.m.rule.suppress_server_acl`, for consistency with `.m.rule.suppress_notices`

2022-05-04 09:20 UTC, richvdh commented on proposals/3786-acl-notifs.md
> +events:
since the list of rules is ordered, please could you specify where in the list the new rule is to be added?

2022-05-04 09:20 UTC, richvdh commented on proposals/3786-acl-notifs.md
> +unideal, this MSC proposes a new push rule to avoid this.
I'm very confused as to why this is needed. as far as I can tell there is no current push rule which matches `m.room.server_acl` events - why do we need another one to make that behaviour explicit? Or rather, please can you explain more clearly what the problem is and why this solves it?

2022-05-04 09:20 UTC, richvdh commented on proposals/3786-acl-notifs.md
> +A new default override rule is to be added that ignores `m.room.server_acl`
it's really helpful for readers if you can link to the existing spec. For example:

```suggestion
A new [default override rule](https://spec.matrix.org/v1.2/client-server-api/#default-override-rules) is to be added that ignores `m.room.server_acl`
```

2022-05-04 17:55 UTC, SimonBrandner commented on proposals/3786-acl-notifs.md
> +    ]
This is intended to be a no-op, similarly to `.m.rule.member_event` and `.m.rule.reaction`

2022-05-04 20:47 UTC, richvdh commented on proposals/3786-acl-notifs.md
> +to [MSC2153](https://github.com/matrix-org/matrix-spec-proposals/pull/2153).
MSC2153 hasn't been accepted, so please could you have this MSC explain why it is needed in its own right ?

2022-05-04 20:50 UTC, richvdh commented on proposals/3786-acl-notifs.md
> +This new push rule is inserted immediately after `.m.rule.reaction`.
`m.rule.reaction` doesn't exist (yet).

2022-05-04 20:54 UTC, richvdh commented on proposals/3786-acl-notifs.md
> +    "rule_id": ".m.rule.room.server_acl",
mmm, probably you're right.

2022-05-05 07:23 UTC, SimonBrandner commented on proposals/3786-acl-notifs.md
> +to [MSC2153](https://github.com/matrix-org/matrix-spec-proposals/pull/2153).
Sorry, I think I am having a bit of trouble expressing why this is needed - is it more understandable now?

2022-05-05 09:38 UTC, richvdh commented on proposals/3786-acl-notifs.md
> +to [MSC2153](https://github.com/matrix-org/matrix-spec-proposals/pull/2153).
honestly no, sorry :)

I'm uncomfortable that the only justification for this change is "because these other unaccepted MSCs say so". Apart from anything else, it effectively means that there is no chance of this MSC being accepted until those are.

I think you just need [this sentence](https://github.com/matrix-org/matrix-spec-proposals/pull/2153/files#diff-667fcbac442602724446f86af8774e828e8a7cce33e06a07043922cacf652524R8) from MSC2153.

2022-05-05 09:43 UTC, SimonBrandner commented on proposals/3786-acl-notifs.md
> +to [MSC2153](https://github.com/matrix-org/matrix-spec-proposals/pull/2153).
> I'm uncomfortable that the only justification for this change is "because these other unaccepted MSCs say so". Apart from anything else, it effectively means that there is no chance of this MSC being accepted until those are.

Yes, that makes sense... :sweat_smile: 

> I think you just need [this sentence](https://github.com/matrix-org/matrix-spec-proposals/pull/2153/files#diff-667fcbac442602724446f86af8774e828e8a7cce33e06a07043922cacf652524R8) from [MSC2153](https://github.com/matrix-org/matrix-doc/pull/2153).

The MSC now has [a similar sentence](https://github.com/matrix-org/matrix-spec-proposals/blob/01704756cc09f071358be9b595b254719da4ecc9/proposals/3786-acl-notifs.md?plain=1#L6) - it it clear?

2022-05-05 09:49 UTC, richvdh commented on proposals/3786-acl-notifs.md
> +to [MSC2153](https://github.com/matrix-org/matrix-spec-proposals/pull/2153).
yeah it's better, thanks.

Sorry, I'm not sure I'm going to have any time to review this or the implementation for the next week.

2022-05-05 09:54 UTC, SimonBrandner commented on proposals/3786-acl-notifs.md
> +to [MSC2153](https://github.com/matrix-org/matrix-spec-proposals/pull/2153).
> yeah it's better, thanks.

Great! Sorry for the chaos before...

> Sorry, I'm not sure I'm going to have any time to review this or the implementation for the next week.

No worries

2022-05-23 17:18 UTC, richvdh reviewed
looks generally good to me - just a few suggestions for clarity!

2022-05-23 17:18 UTC, richvdh commented on proposals/3786-acl-notifs.md
> +so these events should not trigger notifications, though right now they DO
```suggestion
so these events should not trigger notifications; however right now they *do*
```

2022-05-23 17:18 UTC, richvdh commented on proposals/3786-acl-notifs.md
> +trigger notifications, if they have the room rule set to `notify` (`All
```suggestion
trigger notifications, if the user has the room rule set to `notify` (`All
```

2022-05-23 17:18 UTC, richvdh commented on proposals/3786-acl-notifs.md
> +are sent quite frequently, which causes the users to be overwhelmed by
```suggestion
messages` in Element). 

Additionally, these events are often sent quite frequently during spam attacks, 
which causes the users to be overwhelmed by
```

2022-05-23 17:18 UTC, richvdh commented on proposals/3786-acl-notifs.md
> +notifications. (See <https://github.com/vector-im/element-web/issues/20788>)
```suggestion
notifications. (See <https://github.com/vector-im/element-web/issues/20788>.)
```

2022-05-23 17:18 UTC, richvdh commented on proposals/3786-acl-notifs.md
> +The new push rule is analogues to `.m.rule.member_event` or `.m.rule.reaction`
```suggestion
The new push rule is analogous to `.m.rule.member_event` (see https://spec.matrix.org/v1.2/client-server-api/#default-override-rules), or `.m.rule.reaction`
```

2022-05-23 17:18 UTC, richvdh commented on proposals/3786-acl-notifs.md
> +when merged.
```suggestion
or [MSC2677](https://github.com/matrix-org/matrix-spec-proposals/pull/2677)).
```

2022-05-23 17:18 UTC, richvdh commented on proposals/3786-acl-notifs.md
> +    ]
well, I've said the same thing over on MSC2677 and MSC2153 for `.m.rule.reaction`, and I believe its presence on `.m.rule.member_event` is a bug too (https://github.com/matrix-org/matrix-spec/issues/643). There's no need to propagate that bug here.

It's not that important though.

2022-05-23 20:46 UTC, richvdh approved these changes
lgtm

2022-05-24 16:50 UTC, richvdh commented
@mscbot fcp merge

2022-06-01 02:18 UTC, turt2live requested changes
Generally this looks good - I don't have nearly enough expertise to know what the implications of the different override levels are, but do have concerns about the `state_key` not being checked.

2022-06-01 02:18 UTC, turt2live commented on proposals/3786-acl-notifs.md
> +        }
we made a mistake in the `m.room.tombstone` implementation where we forgot to also filter by state_key - let's not make that same mistake again please, particularly as this time the mistake will be in the spec.

2022-06-01 02:18 UTC, turt2live commented
@mscbot concern We should be checking the state_key too

2022-06-01 15:34 UTC, turt2live approved these changes

2022-07-17 18:48 UTC, merged

2022-08-02 22:53 UTC, turt2live commented
spec PR: https://github.com/matrix-org/matrix-spec/pull/1190

2022-08-02 22:53 UTC, turt2live commented
Merged 🎉