MSC3788: Register Clients
matrix-org/matrix-spec-proposals pull request #3790
Opened 2022-05-09 19:47 UTC by xarvic

[Rendered](https://github.com/xarvic/matrix-spec-proposals/blob/main/proposals/3788-register-clients.md)

2022-05-09 19:54 UTC, turt2live reviewed
Please also sign off on your changes when you get a chance.

2022-05-09 19:54 UTC, turt2live commented on proposals/3788-register-clients.md
> +It should be possible to delegate specific tasks to other clients which are able to handle them. To make this possible the spec should define a special private room for the user, which is used by cli
Please wrap your lines to roughly 120 characters.

2022-05-09 20:03 UTC, xarvic commented
Wow that was quick, thanks for the reply :)

> Please also sign off on your changes when you get a chance.

Just by editing the comment?

2022-05-09 20:04 UTC, turt2live commented on proposals/3788-register-clients.md
> +# MSC3788: Register Clients
Your MSC number is actually 3790 ftr - please update the file name and such :)

2022-05-09 20:05 UTC, turt2live commented
Sign off can also be a comment in the PR description using the template:

```
Signed-off-by: Your Name <email@example.com>
```

2022-05-09 20:08 UTC, xarvic commented on proposals/3788-register-clients.md
> +# MSC3788: Register Clients
ok

2022-05-09 20:22 UTC, xarvic commented
After reading the MSC again i noticed one problem, that it is not that easy to detect whether two clients are one the same device, since the `device_id` is actually a `client_id`. Maybe querying the device name could help?

2022-05-09 20:25 UTC, uhoreg commented on proposals/3790-register-clients.md
> +`launch_command` is the command to run when the user wants to inspect one of the associated_event_types.
This will only work if the command exists on the computer that your current client is running on.  Similarly, if you try to use `launch_url` on a different computer/browser, then it will create a new session instead of using the existing session, which is presumably what you would want it to do.

2022-05-09 20:25 UTC, uhoreg commented on proposals/3790-register-clients.md
> +To highlight certain events a client can use "m.event_description" event.
It's not clear why a client would want to "highlight" an event, what it's supposed to do, and how it's related to the rest of this proposal.

2022-05-09 20:25 UTC, uhoreg commented on proposals/3790-register-clients.md
> +The spec should reserve the special room "client_registrations".
That's not a room ID or alias.  How does the client find that room?

2022-05-09 20:28 UTC, xarvic commented on proposals/3790-register-clients.md
> +`launch_command` is the command to run when the user wants to inspect one of the associated_event_types.
You are right. Is there a way to detect if two clients are on the same device? If so the chat client should probably filter out the rest.

2022-05-09 20:54 UTC, xarvic commented on proposals/3790-register-clients.md
> +To highlight certain events a client can use "m.event_description" event.
The idea was that by default events just get a small infotext combined with a link to click on like this:
![image](https://user-images.githubusercontent.com/62311633/167494094-e2acaa92-c195-4fc8-b04f-3bb054335c19.png)

Where as events which have a highlight get a bigger area with icon, header, description and a button. Something like this:
![image](https://user-images.githubusercontent.com/62311633/167495570-a089eff0-11e8-4877-aee2-84d044985523.png)

The aim is to distinguish between important and unimportant events so that the user doesn't get spammed.

Do thinks this could be useful?

2022-05-09 20:59 UTC, xarvic commented on proposals/3790-register-clients.md
> +The spec should reserve the special room "client_registrations".
Having a fixed room id is probably best, should i change it to `#client_registration:yourhomeserver.com`?

2022-05-10 06:18 UTC, Johennes commented on proposals/3790-register-clients.md
> +# MSC3790: Register Clients
The "Rendered" link in the pull request description appears to be a 404.

2022-05-10 11:20 UTC, xarvic commented on proposals/3790-register-clients.md
> +# MSC3790: Register Clients
That is strange, for me it works.

2022-05-10 11:31 UTC, Johennes commented on proposals/3790-register-clients.md
> +# MSC3790: Register Clients
Hm, looks like it works for me, too, now. 🤷‍♂️

2022-05-10 16:25 UTC, KitsuneRal commented on proposals/3790-register-clients.md
> +`launch_command` is the command to run when the user wants to inspect one of the associated_event_types.
Strictly speaking, no. Browser sandboxes are actually supposed to prevent web applications from doing that, and application confinement mechanisms  like Flatpak normally deny most of insight into the local environment to the application as well.

2022-05-10 17:06 UTC, uhoreg commented on proposals/3790-register-clients.md
> +The spec should reserve the special room "client_registrations".
That's not an ID, that's an alias.  Also, that would mean that any homeservers that already have a room with such an alias would get confused clients.

2022-05-10 17:11 UTC, uhoreg commented on proposals/3790-register-clients.md
> +To highlight certain events a client can use "m.event_description" event.
I don't see why something like that needs to be sent as a separate event.

2022-05-10 17:11 UTC, KitsuneRal requested changes
So far the MSC is very sketchy and has quite a few gaps. The note in "Potential issues" is not completely accurate (the room is private to the user after all) but still provides ample opportunity for lateral propagation of an attack once one device has been compromised, making the suggestion a non-starter without proper security mitigations.

What you're trying to devise is a mechahism for experience hand-over really. Whether the client is running on the same device or not doesn't really matter - I might want to open some event on a desktop while running through the feed on a mobile phone, e.g. You really shouldn't deal with application invocation - it's a big security can of worms (have you heard of Windows OLE? You're half-way reinventing it for Matrix) and there are plenty of things in operating systems - think XDG specifications on Linux, e.g. - that are aimed at doing exactly that, with proper safeguards and local context.

That said, I think that advertising support of certain event types across devices of a user has some promise. I'd be interested to see an MSC focusing specifically on this - e.g., with a client at a certain device id claiming support of certain event types and other clients of the user unhiding these events even if they are unknown locally and hinting at the user's device(s) that can show them. This is a more compact and less controversial function.

2022-05-11 14:45 UTC, xarvic commented
> So far the MSC is very sketchy and has quite a few gaps. The note in "Potential issues" is not completely accurate (the room is private to the user after all) but still provides ample opportunity for lateral propagation of an attack once one device has been compromised, making the suggestion a non-starter without proper security mitigations.
> 
> What you're trying to devise is a mechahism for experience hand-over really. Whether the client is running on the same device or not doesn't really matter - I might want to open some event on a desktop while running through the feed on a mobile phone, e.g. You really shouldn't deal with application invocation - it's a big security can of worms (have you heard of Windows OLE? You're half-way reinventing it for Matrix) and there are plenty of things in operating systems - think XDG specifications on Linux, e.g. - that are aimed at doing exactly that, with proper safeguards and local context.

Thanks, for your input. I took a look at OLE and XDG. You are right. This is what I wanted to have. But yes, i see the problem.

> That said, I think that advertising support of certain event types across devices of a user has some promise. I'd be interested to see an MSC focusing specifically on this - e.g., with a client at a certain device id claiming support of certain event types and other clients of the user unhiding these events even if they are unknown locally and hinting at the user's device(s) that can show them. This is a more compact and less controversial function.

Maybe i will try that.

2022-05-11 14:45 UTC, closed without merging