MSC3855: Threads List API
matrix-org/matrix-spec-proposals pull request #3856
Opened 2022-07-26 16:56 UTC by clokep

[Rendered](https://github.com/matrix-org/matrix-spec-proposals/blob/clokep/threads-list-api/proposals/3855-threads-list-api.md)

2022-07-27 17:13 UTC, clokep commented on proposals/3856-threads-list-api.md
> +2. If the ignored user sent the latest thread event.
Since this is replacing existing functionality, I believe the behavior of the `/messages` API as exists now would be:

1. If the ignored user sent the root thread event then the thread would be completely filtered out.
2. If the ignored user sent the latest thread event, a replacement is attempted to be found.

----

1) feels pretty weird, but I don't know what other behavior to give?

2) seems OK, but there's weird edge-cases -- what happens if all events in the thread are from ignored users; is this no longer a thread?

2022-08-09 16:19 UTC, richvdh reviewed
A few comments, but generally looks sensible to me. If you could clarify a couple of things we can probably put this up for FCP.

2022-08-09 16:19 UTC, richvdh commented on proposals/3856-threads-list-api.md
> +For the second problem, it is currently not possible for a client to query for
I'm not quite sure what "second problem" we are referring to here?

2022-08-09 16:19 UTC, richvdh commented on proposals/3856-threads-list-api.md
> +responded to. Clients use the `/messages` API with a filter of
```suggestion
responded to. Clients can use the [`/messages`](https://spec.matrix.org/v1.3/client-server-api/#get_matrixclientv3roomsroomidmessages) API with a filter of
```

2022-08-09 16:19 UTC, richvdh commented on proposals/3856-threads-list-api.md
> +`"related_by_rel_types": ["m.thread"]` to fetch the list of threads in a room. This
`related_by_rel_types` doesn't seem to be in the spec yet. Can you link to the relevant MSC?

2022-08-09 16:19 UTC, richvdh commented on proposals/3856-threads-list-api.md
> +  number of rooms to return per page. Must be an integer greater than zero.
```suggestion
  number of threads to return per page. Must be an integer greater than zero.
```

2022-08-09 16:19 UTC, richvdh commented on proposals/3856-threads-list-api.md
> +  last visible event in the room history for the requesting user.
this doesn't quite read like what you mean, I think... it sounds like it will only return threads whose root is that one event?

2022-08-09 16:19 UTC, richvdh commented on proposals/3856-threads-list-api.md
> +* **`from`**: `string`
loath as I am to broach the pagination subject again, do we need a `dir` param?

2022-08-09 16:19 UTC, richvdh commented on proposals/3856-threads-list-api.md
> +2. If the ignored user sent the latest thread event.
on 1: I *think* that if I ignore a user, but the rest of the room starts a thread based on an event the bad user sent, I still want to see the thread (ideally without the root event). After all, the thread might go on a long time without the involvement of the bad user.

We might need to think of some way of flagging to the client that a given event came from an ignored user, so should be ignored?

2022-08-09 19:35 UTC, clokep commented on proposals/3856-threads-list-api.md
> +2. If the ignored user sent the latest thread event.
> on 1: I _think_ that if I ignore a user, but the rest of the room starts a thread based on an event the bad user sent, I still want to see the thread (ideally without the root event). After all, the thread might go on a long time without the involvement of the bad user.

I think this makes sense -- it matches what the client would see if they aggregated the thread locally (or for some other reason couldn't see the initial event).

2022-08-09 19:36 UTC, clokep commented on proposals/3856-threads-list-api.md
> +For the second problem, it is currently not possible for a client to query for
The two problem statements at the top of the MSC, the second of which is:

> Clients wish to display a list of threads the user is interested in.

The bits above this all refer to the first problem. Do you have suggestions of how to make this clearer?

2022-08-09 19:37 UTC, clokep commented on proposals/3856-threads-list-api.md
> +`"related_by_rel_types": ["m.thread"]` to fetch the list of threads in a room. This
Will do, it is in MSC3440.

2022-08-09 19:38 UTC, clokep commented on proposals/3856-threads-list-api.md
> +`"related_by_rel_types": ["m.thread"]` to fetch the list of threads in a room. This
(Note this is linked below where we go into more detail about it.)

2022-08-09 19:42 UTC, clokep commented on proposals/3856-threads-list-api.md
> +  last visible event in the room history for the requesting user.
> it sounds like it will only return threads whose root is that one event?

That doesn't make sense -- a event can only be the root of a single thread.

Would it be clearer if this entire section talked about "events", which is what is actually returned?

2022-08-09 19:42 UTC, clokep commented on proposals/3856-threads-list-api.md
> +* **`from`**: `string`
A `dir=f` would be equivalent to "get me the oldest threads in the room". I don't think there's a use-case for that at the moment?

@gsouquet can you confirm this is accurate?

2022-08-09 19:43 UTC, clokep commented on proposals/3856-threads-list-api.md
> +* **`from`**: `string`
(Note that "oldest threads" means "threads which have had replies the longest time ago".)

2022-08-16 16:50 UTC, clokep commented on proposals/3856-threads-list-api.md
> +* **`from`**: `string`
There's currently no plan to need a `dir` parameter on here (there doesn't seem to be any valid use-cases).

2022-08-17 08:32 UTC, gsouquet commented on proposals/3856-threads-list-api.md
> +2. If the ignored user sent the latest thread event.
Totally agree with @clokep , this sounds like a scenario where we should act similarly to what clients do when the initial event is unreachable (for example the initial event was posted before I was joined a room and the history visibility setting does not allow me to grab that event). That behaviour seems sane

> We might need to think of some way of flagging to the client that a given event came from an ignored user, so should be ignored?

That is an interesting thought for sure, but as of today clients receive absolutely 0 infomations from ignored users. All events are erased from sync and scrollback. That would mean potentially creating a new event type with redacted content... which could be useful to extend to all events from ignored users so that client can decide to show a trail of events from an ignored individual?

2022-08-18 12:56 UTC, clokep commented on proposals/3856-threads-list-api.md
> +For the second problem, it is currently not possible for a client to query for
Hopefully 8ef8232fc4c07ab03e38b9e98c2ab07a0b368159 clarifies this.

2022-08-18 12:56 UTC, clokep commented on proposals/3856-threads-list-api.md
> +  last visible event in the room history for the requesting user.
I tried to clarify that the returned values are the thread roots -- 75afe347d23c2358187a1966103516d29d5afa20

2022-08-18 13:29 UTC, clokep commented on proposals/3856-threads-list-api.md
> +2. If the ignored user sent the latest thread event.
I added some info at dd11005295a82acf80ca69081e8e61142c5062ff that I think is the conclusion from above!

I did not include anything about communicating and ignored event to the client -- this sounds like an MSC by itself!

2022-08-18 13:29 UTC, clokep commented on proposals/3856-threads-list-api.md
> +* **`from`**: `string`
I added this as a "future extension".

2022-08-22 14:27 UTC, kegsay commented on proposals/3856-threads-list-api.md
> +# MSC3856: Threads List API
How does this work over federation as the local server may not have all the thread roots?

2022-08-22 14:27 UTC, kegsay commented on proposals/3856-threads-list-api.md
> +The returned events are ordered by the latest event of each thread.
Latest by what metric? `origin_server_ts`? Arrival time on the server? Topological ordering?

2022-08-22 14:27 UTC, kegsay commented on proposals/3856-threads-list-api.md
> +  from the last visible event in the room history for the requesting user.
I don't think I understand why `from` is a thing. If I want _all_ thread roots for a room, and I don't specify `from` then it defaults to "a list of thread roots starting from the last visible event in the room history for the requesting user" which feels like the opposite of what I want. Assuming I have say the last 50 events in the room, I can slap on `from=prev_batch_from_sync` but that also will presumably just return the thread roots _from_ that position _to_ the latest current position?

2022-08-22 14:27 UTC, kegsay commented on proposals/3856-threads-list-api.md
> +  an `end` token returned by a previous request to this endpoint.
Why would you ever want this?

2022-08-24 15:27 UTC, clokep commented on proposals/3856-threads-list-api.md
> +# MSC3856: Threads List API
It does not change any behavior there -- a server could backfill to fetch additional thread roots if it wanted to, but that seems rather implementation specific.

2022-08-24 15:30 UTC, clokep commented on proposals/3856-threads-list-api.md
> +The returned events are ordered by the latest event of each thread.
This is meant to be rather vague and it is further defined below under `chunk`, although that doesn't fully answer the question either:

> The order is chronological by the latest event in that thread.

Note that this is mostly copied from the `chunk` definition of `/messages`, which includes the following text:

> (The exact definition of `chronological` is dependent on the server implementation.)

2022-08-24 15:32 UTC, clokep commented on proposals/3856-threads-list-api.md
> +  an `end` token returned by a previous request to this endpoint.
This is here mostly for consistency with `/messages` (and it generally seems to be how pagination of all the APIs in Matrix are done).

2022-09-05 17:39 UTC, gsouquet commented
Proof of client side implementation for this proposal, https://github.com/matrix-org/matrix-js-sdk/pull/2602

2022-09-05 17:54 UTC, turt2live commented
The people involved here believe this is ready for FCP. Implementations have not been checked yet though: if suitable, the label will be removed and review continue. If not suitable, comments will be left.

2022-09-06 19:14 UTC, turt2live approved these changes
Generally seems fine to me, though I'm not looking forward to specifying another pagination API 🙃 

That's a future problem, though.

2022-09-06 19:14 UTC, turt2live commented on proposals/3856-threads-list-api.md
> +  from the last visible event in the room history for the requesting user.
because "last" is confusing with pagination:
```suggestion
  from the most recent visible event in the room history for the requesting user.
```

2022-09-06 19:14 UTC, turt2live commented on proposals/3856-threads-list-api.md
> +2. If the ignored user send the latest thread event: the server should treat the
```suggestion
2. If the ignored user sent the latest thread event: the server should treat the
```

2022-09-06 19:14 UTC, turt2live commented on proposals/3856-threads-list-api.md
> +more efficiently solved by this MSC.
We can also outright remove it, if preferred. 
```suggestion
This MSC replaces the [event filters added in MSC3440](https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/3440-threading-via-relations.md#fetch-all-threads-in-a-room)
(`related_by_rel_types` and `related_by_senders`) as the only known use-case is
more efficiently solved by this MSC.
```

as a "stable but not written" thing, it's entirely valid to rip out the functionality without having to go through a whole process of MSCs.

2022-09-06 19:14 UTC, turt2live commented
@mscbot fcp merge

2022-09-06 19:24 UTC, clokep commented on proposals/3856-threads-list-api.md
> +more efficiently solved by this MSC.
That would be desired, I think. 👍

2022-09-09 20:54 UTC, ara4n commented on proposals/3856-threads-list-api.md
> +## Alternatives
It might be useful to list https://github.com/matrix-org/matrix-spec-proposals/pull/2836 as an alternative to this, in terms of having all the thread navigation/listing activity on a single /relations endpoint outside of /messages or /threads.

2022-09-09 20:54 UTC, ara4n commented
lgtm modulo wanting to list #2836 as an alt.

2022-09-12 17:55 UTC, clokep commented on proposals/3856-threads-list-api.md
> +## Alternatives
I added something about 6002d81ce86922f8f219ff8f7bba19d8cd14de6d, hopefully I hit the highlights, but the tl;dr was "that API is much more complicated than threads needs".

2022-09-13 13:06 UTC, erikjohnston commented on proposals/3856-threads-list-api.md
> +  One of `[all participated]`. Defaults to `all`.
```suggestion
  One of `[all, participated]`. Defaults to `all`.
```

2022-09-13 13:09 UTC, clokep commented on proposals/3856-threads-list-api.md
> +  One of `[all participated]`. Defaults to `all`.
I don't have a strong opinion here, but we seem to usually not include commas in the spec:

https://spec.matrix.org/v1.2/client-server-api/#mroomhistory_visibility

2022-09-13 13:15 UTC, erikjohnston commented on proposals/3856-threads-list-api.md
> +  an `end` token returned by a previous request to this endpoint.
Is this actually something useful? We do it in `/messages` as we need to stitch the timelines together, but I don't think we ever really want to do that? Or are we expecting clients to keep the list of threads updated as things come down sync?

2022-09-13 13:18 UTC, erikjohnston commented on proposals/3856-threads-list-api.md
> +  One of `[all participated]`. Defaults to `all`.
well that just makes me sad, but I'll live

2022-09-13 14:47 UTC, justjanne commented on proposals/3856-threads-list-api.md
> +  an `end` token returned by a previous request to this endpoint.
We need to at least have the ability to paginate the threads list if it is more than one page long. That means we need to be able to specify a token to only return threads that are older than that.

This token doesn't necessarily have to be the same type of token as the ones used by other APIs, and for our current client implementation so far we only need to paginate in one direction, though.

I haven't looked into updating the threads list based on what we get through /sync yet, so I can't tell if that's planned or not. I believe we've done that before already, though, and it would be unlikely that we'd want to remove that functionality.

2022-09-13 14:51 UTC, erikjohnston commented on proposals/3856-threads-list-api.md
> +  an `end` token returned by a previous request to this endpoint.
Yup, agreed we need pagination tokens. Just wandering if they need to be specced to be compatible with the sync tokens or not

2022-09-13 16:01 UTC, turt2live commented on proposals/3856-threads-list-api.md
> +  One of `[all participated]`. Defaults to `all`.
I'd count that a spec bug tbh

2022-09-14 07:37 UTC, gsouquet commented on proposals/3856-threads-list-api.md
> +  an `end` token returned by a previous request to this endpoint.
I can't think of a use case where we would need this to have compatibility with the sync tokens at this time

2022-09-14 11:53 UTC, clokep commented on proposals/3856-threads-list-api.md
> +  One of `[all participated]`. Defaults to `all`.
I can file something (or fix it) -- which way do we prefer?

2022-09-16 13:03 UTC, clokep commented on proposals/3856-threads-list-api.md
> +  One of `[all participated]`. Defaults to `all`.
matrix-org/matrix-spec#1240 attempts to fix this.

2022-09-16 13:28 UTC, clokep commented on proposals/3856-threads-list-api.md
> +  an `end` token returned by a previous request to this endpoint.
I simplified this quite a bit in 78ee0e0d297d1ed6d30568aa5ae90a036dcc8628

@gsouquet  / @justjanne I think this would still be reasonably usable by a client, but wanted to double check.

2022-09-16 13:28 UTC, clokep commented on proposals/3856-threads-list-api.md
> +  from the last visible event in the room history for the requesting user.
See https://github.com/matrix-org/matrix-spec-proposals/pull/3856#discussion_r969612505

2022-09-16 13:28 UTC, clokep commented on proposals/3856-threads-list-api.md
> +  an `end` token returned by a previous request to this endpoint.
See https://github.com/matrix-org/matrix-spec-proposals/pull/3856#discussion_r969612505

2022-09-19 15:37 UTC, KitsuneRal requested changes
Mostly LGTM but I have a concern on the way messages from ignored users are handled.

2022-09-19 15:39 UTC, KitsuneRal commented
@mscbot concern should we care about further updates to the threads list on the client side? Notably wrt messages from ignored users

2022-09-19 17:01 UTC, clokep commented on proposals/3856-threads-list-api.md
> +the thread which was least recently updated. If there becomes a future need of this
That's a good point, perhaps on mobile this would be quite useful.

2022-09-19 17:02 UTC, clokep commented on proposals/3856-threads-list-api.md
> +   re-arranged due to this replacement.
I don't think it would be easy for clients to match.

Unfortunately having the threads appear in the proper spot in pagination was quite difficult (unless you're constantly re-evaluating ignored users). It *might* be more doable now that we're not using `/sync` tokens though. I'll take another look and see if it is doable.

2022-09-20 19:48 UTC, KitsuneRal commented
@mscbot resolve should we care about further updates to the threads list on the client side? Notably wrt messages from ignored users

2022-09-20 19:58 UTC, KitsuneRal commented
The concern is formally resolved in order to let the FCP start and the threads get into the spec within this cycle, with a caveat that we will either fix the logic for ignored events or document the discrepancy I described in the comment as a known issue (that will be addressed in a separate MSC).

2022-09-21 07:19 UTC, gsouquet commented on proposals/3856-threads-list-api.md
> +  an `end` token returned by a previous request to this endpoint.
@clokep that looks reasonable to me yes! I don't foresee problems with the changes you've made 👍

2022-09-25 23:15 UTC, merged

2022-09-27 04:37 UTC, turt2live commented
Spec PR: https://github.com/matrix-org/matrix-spec/pull/1254

2022-09-27 19:51 UTC, turt2live commented
Merged 🎉