Simple rendezvous capability
matrix-org/matrix-spec-proposals pull request #3886
Opened 2022-09-07 08:21 UTC by hughns

2022-09-11 20:59 UTC, ara4n requested changes

2022-09-11 20:59 UTC, ara4n commented on proposals/3886-simple-rendezvous-capability.md
> +# MSC3886: Simple client rendezvous capability
On one hand, this is a really simple and elegant standalone function. On the other hand, I'm a bit worried that it duplicates the semantics of to-device API (i.e. basic store & forward between devices), albeit with short-polling rather than long-polling.

I wonder how bad it would be if we opened up to-device messages to guests, and used the existing APIs for rendezvous?  So a new device would go and /login as a guest to get a temporary access token, and then publish its device ID & HS url in its QR code to let another device rendezvous with it.

My only reason for proposing this is to avoid having two store-and-forward APIs which look suspiciously similar, but have different semantics (short/long poll), and so require more code for client implementors.

2022-09-12 08:30 UTC, hughns commented on proposals/3886-simple-rendezvous-capability.md
> +# MSC3886: Simple client rendezvous capability
Understood. I'll work up an alternative based on to-device messages and see how that feels.

2022-10-04 18:20 UTC, hughns commented on proposals/3886-simple-rendezvous-capability.md
> +# MSC3886: Simple client rendezvous capability
I have started some discussion on the to-device based alternative as part of https://github.com/matrix-org/matrix-spec-proposals/pull/3903

2023-03-07 04:31 UTC, turt2live commented
This was proposed as ready for FCP by the author, however it appears to have some conflicts with to-device messaging. For now, I'm going to put it into "needs technical design review". This doesn't mean it's not ready for FCP, just that the review's tone should take a slightly different shape.

@matrix-org/spec-core-team please review this for technical design.

2023-03-14 18:12 UTC, richvdh commented on proposals/3886-simple-rendezvous-capability.md
> +### Protocol
As I understand it, none of the endpoints have any requirements for an Authentication header. I think that's fine, but could you make it explicit?

2023-03-14 18:12 UTC, richvdh commented on proposals/3886-simple-rendezvous-capability.md
> +# MSC3886: Simple client rendezvous capability
> I wonder how bad it would be if we opened up to-device messages to guests, and used the existing APIs for rendezvous? So a new device would go and /login as a guest to get a temporary access token, and then publish its device ID & HS url in its QR code to let another device rendezvous with it.

ugh, the complexity of this feels *horrible* to me.

> My only reason for proposing this is to avoid having two store-and-forward APIs which look suspiciously similar, but have different semantics (short/long poll), and so require more code for client implementors.

Sure, having two store-and-forward APIs is rather less than ideal, but this one is so simple and easy to use that I don't really buy that it's a meaningful amount of extra code for clients comparing to have to grab a temporary access token and then start /syncing.

For me, the simplicity of this proposal outweighs the fact it looks a bit like to-device messaging. (Or even matrix rooms, if you squint hard enough and invent "ephemeral rooms".)

The only thing I'd say here is that it would be good if the "Alternatives" section in this MSC said something about this idea (even if it's just a link to MSC3903's alternatives section).

2023-03-14 18:15 UTC, richvdh approved these changes
I love this. Clear, simple and effective.

Happy to put this forward for FCP, though we should avoid doing so unless we think MSC3906 is going to be ready in short order, otherwise we end up with a feature in the spec without any particular use.

2023-03-14 18:42 UTC, turt2live commented
@hughns fyi that this has also entered "not active SCT focus" as it has a soft dependency on https://github.com/matrix-org/matrix-spec-proposals/pull/3906, which is also currently back with you.

When you get a chance to update the MSCs, we'll push 3906 forward at the same time as this one - just let us know in the SCT office.

2023-03-15 20:56 UTC, hughns commented on proposals/3886-simple-rendezvous-capability.md
> +  R->A: 201 Created Location: /abc-def-123-456
It appears I never added them in the first place. Now fixed. 😇

2023-03-15 21:11 UTC, hughns commented on proposals/3886-simple-rendezvous-capability.md
> +These headers are different from the ones currently specified in the [spec](https://spec.matrix.org/v1.4/client-server-api/#web-browser-clients).
I don't recall intending to change them globally, so I have clarified that they just apply to the new API endpoint.

2023-03-15 21:36 UTC, hughns commented on proposals/3886-simple-rendezvous-capability.md
> +HTTP response headers for `201 Created`:
As per notes inline they are required.

2023-03-15 21:51 UTC, hughns commented on proposals/3886-simple-rendezvous-capability.md
> +### Protocol
I've added a section on this.

2023-03-15 21:51 UTC, hughns commented on proposals/3886-simple-rendezvous-capability.md
> +- `307 Temporary Redirect` - if the request should be served from somewhere else specified in the `Location` response header
Correct. I've added a note on why 307 is specifically used.

2023-03-15 21:55 UTC, hughns commented on proposals/3886-simple-rendezvous-capability.md
> +#### Create a new rendezvous point: `POST /rendezvous`
I have been assuming that it will be part of the Client-Server API and so end up somewhere under `/_matrix/client`.

I supposed it could also be specced as a whole new top-level Matrix API. This might make the spec implementation simpler (where the CORS and some other aspects vary) in which case it could be `/_matrix/rendezvous`.

Or, this thought might be opening a can of worms.

2023-03-15 21:57 UTC, hughns commented on proposals/3886-simple-rendezvous-capability.md
> +# MSC3886: Simple client rendezvous capability
I've move the section from [MSC3903](https://github.com/matrix-org/matrix-spec-proposals/pull/3903) alternatives section into this proposal as there is much feedback here than on MSC3903 itself.

2023-04-25 22:35 UTC, uhoreg commented on proposals/3886-simple-rendezvous-capability.md
> +```
My understanding of this is that A and B take turns writing to the same rendezvous URI until they're done.  So when it's B's turn to write, A keeps polling (using the ETag) until the server says the data has changed, and vice versa.

What happens if B tries to write, but gets some sort of network error, or an error from a proxy?  If the server got B's data, but B received a network error, then it seems to me what could happen is:
- A receives B's data, thinks it's now their turn to send data, so sends their data and gets a new ETag
- B retries the request, overwriting A's data (and never receiving it)
- A polls for new data, using the new ETag
- since B overwrote A's data, the data doesn't match the ETag, so A gets the data B sent, again

So B will miss a message from A, and A will get a duplicate message.

2023-04-25 22:35 UTC, uhoreg commented on proposals/3886-simple-rendezvous-capability.md
> +only return data if given ETag does not match
Might be nice for servers to have the option to delay responding until it gets content that doesn't match the ETag, so we can do long-polling.

2023-04-25 22:35 UTC, uhoreg commented on proposals/3886-simple-rendezvous-capability.md
> +
One potential issue here is that if A sends a message to B, then waits for a message from B using the ETag, but the message that B sends to A happens to be exactly the same as the message that A sent, then A will get the `304 Not Modified` response, and never realize that B sent a message.  So anything built on top of this needs to ensure that a message is never identical to the preceding message.

2023-06-20 01:06 UTC, turt2live reviewed
overall this MSC seems like a good approach for the problem. I've left some comments about things that should be clarified before the MSC can go up for FCP.

2023-06-20 01:06 UTC, turt2live commented on proposals/3886-simple-rendezvous-capability.md
> +- `X-Max-Bytes` - required, the maximum allowed bytes for the payload
why are these headers and not response body parameters?

2023-06-20 01:06 UTC, turt2live commented on proposals/3886-simple-rendezvous-capability.md
> +HTTP response codes:
Matrix error codes here too please, and probably a `400` definition to cover missing headers and such

2023-06-20 01:06 UTC, turt2live commented on proposals/3886-simple-rendezvous-capability.md
> +HTTP response codes:
(comment applies throughout remainder of proposal)

2023-11-13 12:08 UTC, hughns commented on proposals/3886-simple-rendezvous-capability.md
> +```
Perhaps we could mitigate against this by using a RFC7232 `If-Match` on the PUT requests?

2023-11-13 12:10 UTC, hughns commented on proposals/3886-simple-rendezvous-capability.md
> +- `X-Max-Bytes` - required, the maximum allowed bytes for the payload
On reflection I would agree that if [it is](https://github.com/matrix-org/matrix-spec-proposals/pull/3886#discussion_r1135982763) going to be part of the C-S API then it would make sense to consider consistency with the rest of the C-S API where headers are not used.

2023-11-13 13:34 UTC, DMRobertson commented on proposals/3886-simple-rendezvous-capability.md
> +#### Create a new rendezvous point: `POST /rendezvous`
Done in 931cf073.

2023-11-13 13:50 UTC, DMRobertson commented on proposals/3886-simple-rendezvous-capability.md
> +HTTP response codes:
See aee7d81c. I have proposed `M_DIRTY_WRITE` for the `HTTP 412 Precondition Failed` case where Alice attempts to write but hasn't seen Bob's latest write.

2023-11-13 14:01 UTC, DMRobertson commented on proposals/3886-simple-rendezvous-capability.md
> +HTTP response codes:
90a8b495 defines a 400 response.

2023-11-13 14:14 UTC, DMRobertson commented on proposals/3886-simple-rendezvous-capability.md
> +- `Location` - required, the allocated rendezvous URI which can be on a different server
Presumably this needs URI needs to be not guessable, to prevent attackers from guessing this and impersonating the intended recipient?

2023-11-13 14:34 UTC, DMRobertson commented on proposals/3886-simple-rendezvous-capability.md
> +- `X-Max-Bytes` - required, the maximum allowed bytes for the payload
Are we concerned with just these two headers? Or do we want _all_ of the response and request headers to be expressed via HTTP bodies?

2023-11-13 14:51 UTC, DMRobertson commented on proposals/3886-simple-rendezvous-capability.md
> +```
ISTM that every PUT should be required to cite a previous ETag so that the rendezvous server can enforce a linear ordering. (The initial ETag is included in the POST and GET response, so both A and B should be fully aware of it.)

2023-11-13 15:08 UTC, DMRobertson commented on proposals/3886-simple-rendezvous-capability.md
> +- `Expires` - required, the expiry time of the rendezvous as per [RFC7233](https://httpwg.org/specs/rfc7234.html#header.expires)
Is the intention that the expiry time is incremented every time the rendezvous payload is updated?

2023-11-13 15:21 UTC, DMRobertson commented on proposals/3886-simple-rendezvous-capability.md
> +- device keys for end-to-end encryption
dcbbcb0f and 74d90948 clarify that this is an untrusted communications channel.

2023-11-13 15:58 UTC, DMRobertson commented on proposals/3886-simple-rendezvous-capability.md
> +- `X-Max-Bytes` - required, the maximum allowed bytes for the payload
The response body for GET ought to be just the payload itself. Since the payload data is an arbitrary byte sequence, it would be painful to embed this in JSON. Therefore I would encourage the current GET response headers (Content-Type, ETag, Expires, Last-Modified) to continue to be expressed via headers. For consistency it makes sense to do so in all other resposnes.

For POST this leaves the two highlighted headers: Location and X-Max-Bytes. We could present them as a JSON-encoded body, but it would seem odd to spread the POST response metadata in two places without any meaningful distinction to justify it. My vote would be to leave things as they are. But I neither have a vote, nor any strong opinions.

2023-11-13 16:37 UTC, DMRobertson commented on proposals/3886-simple-rendezvous-capability.md
> +```
58f1e86f does this.

2023-11-13 16:46 UTC, DMRobertson commented on proposals/3886-simple-rendezvous-capability.md
> +- `Expires` - required, the expiry time of the rendezvous as per [RFC7233](https://httpwg.org/specs/rfc7234.html#header.expires)
I have assumed so in 65d697c2

2023-11-13 17:04 UTC, DMRobertson commented on proposals/3886-simple-rendezvous-capability.md
> +HTTP response codes:
Although I self-bikeshedded a different name in 3fecfcd5.

2023-11-29 11:31 UTC, dkasak commented on proposals/3886-simple-rendezvous-capability.md
> +
Is this still a problem? From the current text, it sounds like `304 Not Modified` will only be returned when a matching ETag is supplied in a `If-None-Match`. Given the resolution of [this thread](https://github.com/matrix-org/matrix-spec-proposals/pull/3886#discussion_r1177126767), clients will have to supply a previous ETag when doing a PUT, which means we no longer have to rely on the sameness of the content to decide whether the content has been modified. That is, a PUT request that specifies the previous ETag `A` should be regarded as altering the payload at `A`, even if the payload is unchanged, and therefore, it should be assigned a new ETag.

2023-11-29 11:34 UTC, dkasak commented on proposals/3886-simple-rendezvous-capability.md
> +by both devices, and SHOULD NOT be used to transmit sensitive data in plaintext.
```suggestion
by both devices, and SHOULD NOT be used to transmit sensitive data in cleartext.
```

Technical nit: Cleartext is stuff that gets sent without encryption. Plaintext is stuff you get once you decrypt ciphertext.

2023-11-29 11:38 UTC, dkasak commented on proposals/3886-simple-rendezvous-capability.md
> +- `X-Max-Bytes` - required, the maximum allowed bytes for the payload
> The response body for GET ought to be just the payload itself. Since the payload data is an arbitrary byte sequence, it would be painful to embed this in JSON.

We could base64 encode the payload, but I tend to agree. Not all things need to be shoehorned through JSON.

2024-04-09 11:56 UTC, hughns commented
It is proposed that [MSC4108](https://github.com/matrix-org/matrix-spec-proposals/pull/4108) supersedes this MSC.

2024-04-30 18:16 UTC, hughns commented
Closing this PR as https://github.com/matrix-org/matrix-spec-proposals/pull/4108 is now ready for review.

2024-04-30 18:16 UTC, closed without merging