X25519 Elliptic-curve Diffie-Hellman ephemeral for establishing secur…
matrix-org/matrix-spec-proposals pull request #3903
Opened 2022-10-04 17:20 UTC by hughns

…e channel between two Matrix clients

2022-10-04 17:34 UTC, turt2live commented on proposals/3903-x25519-ecdhe.md
> +## Alternatives
it sounds like this is duplicating Olm sessions over to-device? Early on in this proposal there should be something to address that.

2022-10-04 17:35 UTC, turt2live commented on proposals/3903-x25519-ecdhe.md
> +None.
MSC3886 and to-be-released MSC?

2022-10-04 17:48 UTC, hughns commented on proposals/3903-x25519-ecdhe.md
> +## Alternatives
Yes, acknowledged.

2022-10-04 18:19 UTC, hughns commented on proposals/3903-x25519-ecdhe.md
> +## Alternatives
Well, no. It's actually that you could achieve this with to-device messaging instead.

2022-10-17 16:19 UTC, uhoreg commented on proposals/3903-x25519-ecdhe.md
> +For the above example keys the info would be: `m.rendezvous.v1.curve25519-aes-sha256|gRr3uZSpm2qz37CkqnrhZTW3H0JQvc6l4HYOtBULNSU=|E03zK4t29xyiXlt54kOVpIzNtGytjQSvaHXF8n8tTBs=`.
I'd suggest using unpadded base64 encoding everywhere, for consistency with other things in the Matrix spec.  (Here in particular, it's important to specify exactly which variant of base64 to use, otherwise different implementations will fail to generate the same shared key)

2022-10-19 10:58 UTC, notramo requested changes
This is horrible UX.

2022-10-19 10:58 UTC, notramo commented on proposals/3903-x25519-ecdhe.md
> +**7.** The user should confirm that the established channel is secure by means of a checksum derived from the shared key.
This is **CRAPPY, HORRIBLE** UX! WHY? Why another visual comparison, another “I don't get what should I do now.” moment for users? Matrix already has too much visual comparison in its UX.

You already have a secure channel by means of QR code. Utilize it well, so users don't have to compare checksums.

2022-10-19 10:58 UTC, notramo commented on proposals/3903-x25519-ecdhe.md
> +Unlike `publicA` the recipient public key `publicB` does not need to be transmitted via a trusted medium.
If it was signed, and encrypted with the (trusted) `publicA`, could it prevent the horrible UX in step 7?

2022-10-19 10:58 UTC, notramo commented on proposals/3903-x25519-ecdhe.md
> +It's critical that the initiator public key `publicA` is transmitted via a trusted medium such as a QR code or some other
It can be MITM attacked if it's transmitted over insecure channel. However, securing `publicA` is pointless unless `publicB` is secured also, or a horrible visual comparison is used (step 7).

2023-02-13 10:47 UTC, hughns commented on proposals/3903-x25519-ecdhe.md
> +For the above example keys the info would be: `m.rendezvous.v1.curve25519-aes-sha256|gRr3uZSpm2qz37CkqnrhZTW3H0JQvc6l4HYOtBULNSU=|E03zK4t29xyiXlt54kOVpIzNtGytjQSvaHXF8n8tTBs=`.
👍 I've updated the spec to use unpadded base64 everywhere.

2023-02-20 10:22 UTC, AlexanderLindhard commented
Who needs to hire a bitcoin recovery expert? Anyone who has lost cryptocurrency funds in any form of a hack, shut down and/or hacked exchange, ransomware, ransoms, fake ICOs or who simply has lost funds by sending them to the wrong address. Did you lose access to your account by losing your bitcoin private key or, did you lose money to fake bitcoin miners? You can get all your lost funds back by hiring one of the best bitcoin recovery experts out there. After a lot of thorough examination and scrutiny, I present to you the best bitcoin recovery experts: kevinmitnickcyber @gmail com

2023-02-20 10:22 UTC, AlexanderLindhard commented
I wrote a fund recovery firm at ( kevinmitnickcyber @ GMAIL COM ) when I got scammed by some crypto investment scheme this was sad but I’m glad I got a topnotch service at my first recovery trial. It’s indeed 100% possible to recover your stolen funds. This team got it done with ease and perfectly

2023-03-01 14:23 UTC, hughns commented on proposals/3903-x25519-ecdhe.md
> +Although this proposal can be used over any other insecure channel, the anticipated use case is over
I've attempted to make the intention of the statement clearer.

2023-03-07 04:34 UTC, turt2live commented
Like in https://github.com/matrix-org/matrix-spec-proposals/pull/3886#issuecomment-1457512474 , the author believes this is ready for FCP. The MSC appears to have conflicts with toDevice messaging though, so to get a slightly different review tone I'm putting this in technical review needed.

This doesn't mean the MSC isn't ready for FCP, just that the review given should be more useful to handle.

@matrix-org/spec-core-team please review this for technical design.

2023-03-15 21:50 UTC, hughns commented
There has been more engagement in the topic of to-device messaging in https://github.com/matrix-org/matrix-spec-proposals/pull/3886 so I have consolidated the notes and discussion onto that proposal so that they can be worked through more easily.

2023-04-25 22:40 UTC, uhoreg commented on proposals/3903-x25519-ecdhe.md
> +
I don't think that this protects against replay attacks.  That might be OK if the thing built on top of it can detect if a message is replayed (e.g. if messages have a definite order, so a replayed message would be flagged as being out of place), but I think it should be mentioned.

2023-06-20 01:08 UTC, turt2live commented on proposals/3903-x25519-ecdhe.md
> +## Alternatives
this^

2023-06-20 01:08 UTC, turt2live commented on proposals/3903-x25519-ecdhe.md
> +**1a.** The initiator generates a ephemeral Curve25519 private key `privateA`.
nit: please use markdown's built-in numbering/bullet system

2023-10-18 11:29 UTC, hughns commented on proposals/3903-x25519-ecdhe.md
> +## Alternatives
I concur that the feasibility of Olm over MSC38856 should be assessed.

2023-11-29 11:50 UTC, dkasak commented on proposals/3903-x25519-ecdhe.md
> +out-of-bands communication between two Matrix clients.
The reference to MSC3906 should be clarified by stating what kind of relationship it has with this MSC.

```suggestion
In [MSC3906](https://github.com/matrix-org/matrix-spec-proposals/pull/3906) a
proposal is made to allow a user to login on a new device using an existing
device by means of scanning a QR code, followed by exchanging some messages over
a secure channel.

[MSC3886](https://github.com/matrix-org/matrix-spec-proposals/pull/3886) already
proposes a simple unsecured rendezvous protocol.

In this proposal we build a secure layer on top of MSC3886 to allow for trusted
out-of-bands communication between two Matrix clients, which satisfies the
requirements of MSC3906.
```

2023-11-29 11:51 UTC, dkasak commented on proposals/3903-x25519-ecdhe.md
> +perform AES.
```suggestion
The proposal is to use X25519 to agree on a shared secret that is then used to
perform AES.
```

2023-11-29 11:53 UTC, dkasak commented on proposals/3903-x25519-ecdhe.md
> +**1a.** The initiator generates a ephemeral Curve25519 private key `privateA`.
```suggestion
**1a.** The initiator generates an ephemeral Curve25519 private key `privateA`.
```

2023-11-29 11:58 UTC, dkasak commented on proposals/3903-x25519-ecdhe.md
> +public key `publicB` and shares is using the same structure of payload:
```suggestion
public key `publicB` and shares it using the same structure of payload:
```

2023-12-04 11:03 UTC, dkasak requested changes

2024-04-09 11:55 UTC, hughns commented
It is proposed that [MSC4108](https://github.com/matrix-org/matrix-spec-proposals/pull/4108) supersedes this MSC.

2024-04-30 18:16 UTC, closed without merging

2024-04-30 18:16 UTC, hughns commented
Closing this PR as https://github.com/matrix-org/matrix-spec-proposals/pull/4108 is now ready for review.