m.replace aggregation with full event
matrix-org/matrix-spec-proposals pull request #3925
Opened 2022-11-03 16:47 UTC by benkuly

2022-11-03 19:20 UTC, turt2live commented
@benkuly don't forget to sign off on the changes for if this eventually gets accepted please :)

2022-11-04 07:55 UTC, benkuly commented
> @benkuly don't forget to sign off on the changes for if this eventually gets accepted please :)

Thank you, is done now.

2022-11-04 08:07 UTC, jplatte commented on proposals/3925-replace-aggregation-with-full-event.md
> +While this events also have been immutable until v1.3, since v1.4 they aren't.
```suggestion
While these events also have been immutable until v1.3, since v1.4 they aren't.
```

2022-11-04 08:07 UTC, jplatte commented on proposals/3925-replace-aggregation-with-full-event.md
> +I'm not sure, if we need an unsable prefix, because the aggregation would just be extended by additional fields.
```suggestion
I'm not sure, if we need an unstable prefix, because the aggregation would just be extended by additional fields.
```

2022-11-08 15:33 UTC, richvdh requested changes
Thanks! I agree with the proposal, but I'm not sure I agree with all the reasons, and the proposal could do with some clarifications.

2022-11-08 15:33 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +* It is not as easy for clients like as in the current spec to get the current content of an event by just looking into `content.body`. While this true, it is also a relatively inconsistent behavior.
please wrap your text at 80 characters.

2022-11-08 15:33 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +The Matrix DAG has immutable PDUs forming an auth chain. The client representation of this PDUs are simply called events.
they are called events in the DAG as well. "PDU" isn't used much, but when it is, it's specific to transmitting individual events over the federation API.

The refererence to "auth chains" is irrelevant here too.

Generally I don't think this line is adding much, and I suggest you get rid of it.

```suggestion
```

2022-11-08 15:33 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +While these events also have been immutable until v1.3, since v1.4 they aren't.
I think this is overstating the case. For one thing, it's always been possible to mutate events via redaction. Second, they are still immutable: it's just the server's representation of them which is mutating. (That representation is defined at https://spec.matrix.org/v1.4/client-server-api/#room-event-format, and isn't quite the same as the "raw event": note the presence of `event_id` for example)

2022-11-08 15:33 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +* If an event with `m.replace` relation is deleted, the client would need to detect, if the original content was replaced and possibly needs to fetch the original content.
events can't be deleted. Do you mean `redacted`?

2022-11-08 15:33 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +* There is an additional server call needed, when the replacing event is encrypted, because the server cannot replace the original event content.
I don't see how you can claim that an "additional server call" is needed, when it's unclear how a server can implement the spec as it is currently written anyway.

```suggestion
* Server cannot replace the original event content for encrypted events (because the 
  replacement content is inside the encrypted body).
  See [matrix-spec#1299](https://github.com/matrix-org/matrix-spec/issues/1299).
```

2022-11-08 15:33 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +* There are also some other issues with this spec paragraph, which are discussed [here](https://github.com/matrix-org/matrix-spec/issues/1299)
Spell them out for us, please? I'm not sure what other issues you are referring to.

2022-11-08 15:33 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +* There could be clients, which rely on the current behavior.
```suggestion
* There could be clients which rely on the current behavior.
```

2022-11-08 15:33 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +The additional server call is already needed for encrypted events and would be saved by this proposal too.
the additional server call is needed because Synapse isn't implementing the spec, and it's not specific to encrypted events: https://github.com/matrix-org/synapse/issues/12793.

2022-11-08 15:33 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +
we should probably mention @kegsay's alternative suggestion at https://github.com/matrix-org/matrix-spec/issues/1299#issuecomment-1290332433.

2022-11-08 15:35 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +I'm not sure, if we need an unstable prefix, because the aggregation would just be extended by additional fields.
the fact that we're just adding extra fields is no reason that we would not need an unstable prefix.

Still, it's hard to see how an unstable prefix could be used here.

2022-11-08 15:37 UTC, benkuly commented on proposals/3925-replace-aggregation-with-full-event.md
> +* If an event with `m.replace` relation is deleted, the client would need to detect, if the original content was replaced and possibly needs to fetch the original content.
yep

2022-11-08 15:51 UTC, benkuly commented on proposals/3925-replace-aggregation-with-full-event.md
> +While these events also have been immutable until v1.3, since v1.4 they aren't.
While I still think immutablilty is relevant, I understand what you mean. In fact, in Trixnity, I circumvented all the cases, where some fields are removed by just adding them to the json before the deserialization. I've always disliked this, because it breaks good typing in most languages.
I removed the sentence.

2022-11-08 16:17 UTC, benkuly commented on proposals/3925-replace-aggregation-with-full-event.md
> +* There are also some other issues with this spec paragraph, which are discussed [here](https://github.com/matrix-org/matrix-spec/issues/1299)
There are actually no more, thank you.

2022-11-11 15:22 UTC, richvdh requested changes

2022-11-11 15:22 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +  original content.
```suggestion
* If an event with `m.replace` relation is redacted, clients need to
  detect if the original content was replaced, and possibly need to fetch the
  original content.
```

2022-11-11 15:22 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +relation, [the server should replace the content of the original event](https://spec.matrix.org/v1.4/client-server-api/#server-side-replacement-of-content).
```suggestion
As [currently specified](https://spec.matrix.org/v1.4/client-server-api/#server-side-replacement-of-content),
servers should replace the content of events that have been replaced via an `m.replace`
relation.
```

2022-11-11 15:22 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +There is a discussion about this spec paragraph [here](https://github.com/matrix-org/matrix-spec/issues/1299).
this is mentioned just above
```suggestion
```

2022-11-11 15:22 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +  content of an event by just looking into `content.body`. While this is true, it
```suggestion
* It will be harder for clients to get the current content of an event: currently
  they can just looking at `content.body`. While this is true, it
```

2022-11-11 15:22 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +  does look different (without "*") despite the fact, that it is also replaced.
I'm afraid I'm not following this. When you say "Future replacements", do you mean events that arrive (over `/sync`) *after* the client receives the original event?

The term "rendered" refers the way a client takes the json and turns it into user-visible text. Is that really what you mean, or are you talking about the way a server returns the event?

> So the event with the replaced event does look different (without "*") 

I would certainly expect events *without* a replacement not to have a `*`, so this makes it sound as though events with replacements will look the same as those without? I don't think that's what you mean though?

Basically: please could you rewrite these two sentences.

2022-11-11 15:22 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +be extended by additional fields.
```suggestion
No unstable prefix is currently proposed.
```

2022-11-11 15:22 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +
```suggestion

None currently foreseen.

```

2022-11-11 15:48 UTC, benkuly commented on proposals/3925-replace-aggregation-with-full-event.md
> +  does look different (without "*") despite the fact, that it is also replaced.
see https://github.com/matrix-org/matrix-spec-proposals/pull/3925/commits/5bfffb4ddf7c4da863ca71bdd1eaab26dd272239

2022-11-11 15:50 UTC, benkuly commented on proposals/3925-replace-aggregation-with-full-event.md
> +can just inspect unsigned to present the "edits" dialog.
You are right. Thank you :)

2022-11-15 15:56 UTC, richvdh requested changes

2022-11-15 15:56 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +  the current content of an event: currently they can just look at `content.body`.
Ok, point of English grammar: in English we don't use a comma here. If you include a comma, then "which" refers to the *whole* of the previous phrase ("It will be harder for clients") instead of just "clients". 

So, this is grammatically correct, though not what you mean here:

> "[Some action] will be harder for clients, which will [have some consequence]", eg "Displaying events will be harder for clients, which will be annoying for client developers"

In general, I think we use fewer commas in English than you think we do :)

```suggestion
* It will be harder for clients which do not support replacing events to get
  the current content of an event: currently they can just look at `content.body`.
```

2022-11-15 15:56 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +  Assuming that we have an event A with the body `1`, which is first replaced by
```suggestion
  Assume that we have an event A with the body `1`, which is first replaced by
```

2022-11-15 15:56 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +  `3`. The sync has been done right after A' und A''. Then the timeline
```suggestion
  `3`. A `/sync` is done right after A' and A''. Then the timeline
```

2022-11-15 15:56 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +  not been replaced.
Sorry, still not following. Please can you break it down a bit more.  What do you mean by "the timeline would look like this: `2` -> `*3`" ? What does `->` represent here?

After A', the client receives a /sync like this:

```yaml
timeline:
  - { event_id: "A", content: {body: "1"} }
  - { event_id: "A'", content: {body: "* 2"} }
```

Right?

----

If I spent a long time staring at your proposal and thinking about what you are trying to say, I could probably figure it out.  But for a proposal to be accepted, everybody else needs to understand it, and you can't expect everyone to spend hours trying to reverse-engineer your proposal.

In other words, please remember your audience, and explain yourself clearly.

2022-11-15 16:32 UTC, benkuly commented on proposals/3925-replace-aggregation-with-full-event.md
> +  not been replaced.
Sorry for the effort and all the commas.

Is this better? I think I would put that into the introduction, because it is also an issue of the current spec.

* Replacing the content can lead to inconsistent behavior on clients which don't
  support replacing events.
  Assume that we have this timeline on the server:
    - `{"event_id": "E1", "content": {"body": "1"}}`
    - `{"event_id": "E2", "content": {"body": "* 2", "m.new_content": {"body": "2"}}` // replaces `E1`

  A `/sync` is done after `E2`. We will have this timeline on a client:
    - `{"event_id": "E1", "content": {"body": "2"}}`
    - `{"event_id": "E2", "content": {"body": "* 2"}`

  Although `2` is a replaced body it does not have a `*`. This looks to the
  user as if it is the original content of the event.

2022-11-15 17:01 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +  not been replaced.
Yes, that's much clearer, thanks. Good idea to put it in the introduction.

2022-11-16 11:37 UTC, richvdh approved these changes
looks good!

The next step is to get it implemented so that we can see it working.

2023-01-12 10:54 UTC, richvdh commented
This now has server-side (https://github.com/matrix-org/synapse/pull/14811) and client-side (https://github.com/matrix-org/matrix-js-sdk/pull/3045) implementations. I believe it is ready for FCP.

@mscbot fcp merge

2023-01-16 21:56 UTC, turt2live commented on proposals/3925-replace-aggregation-with-full-event.md
> +   fetch it from the server.
Sorry, I don't understand what is being described here: are we saying the replacement event applies to itself? (in which case, why bother with specifying new and old content separately?)

2023-01-16 21:56 UTC, turt2live commented
@mscbot concern Unclear what is being proposed

2023-01-17 11:31 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +   fetch it from the server.
@turt2live the current wording seems pretty clear to me (though I had a hand in writing it, so maybe I'm biased).

The current spec, as linked, says:

> The aggregation format of `m.replace` relationships gives the `event_id`, `origin_server_ts`, and` sender` of the most recent replacement event.

We're changing it so that it is the *whole* of that replacement event, rather than just three fields.

2023-01-17 16:54 UTC, turt2live commented
@mscbot resolve Unclear what is being proposed

2023-02-07 17:44 UTC, dbkr commented on proposals/3925-replace-aggregation-with-full-event.md
> +      "com.example.extension_property": "chocolate"
Is this here to demonstrate that newly added properties appear on the related event and not on the original? It would b e good to clarify as it's not super obvious why it's here.

2023-02-07 17:44 UTC, dbkr commented on proposals/3925-replace-aggregation-with-full-event.md
> +* There could be clients which rely on the current behavior.
Do we know of any in particular? What will the failure mode be in such clients and is it tolerable?

2023-02-07 22:16 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +      "com.example.extension_property": "chocolate"
> Is this here to demonstrate that newly added properties appear on the related event and not on the original?

I think it's just an example, yes. Maybe it would be clearer just to remove it?

2023-02-07 22:26 UTC, richvdh commented on proposals/3925-replace-aggregation-with-full-event.md
> +* There could be clients which rely on the current behavior.
Well, element-web relied on it until https://github.com/matrix-org/matrix-js-sdk/pull/3045, and I suspect most other clients still do.

The failure mode is: suppose that some time ago, you have an event E, which was subsequently replaced by an event E'. Now, if you jump back to a bit of timeline that contains E but *not* E', then clients unaware of this change will show the original event E rather than the edited content E'.

My feelings are: (1) that is an edge-case; (2) it already happens for events other than `m.room.message` (including encrypted events) due to https://github.com/matrix-org/synapse/issues/12503.

All of this information should probably be in the MSC itself: @benkuly do you fancy updating it?

2023-02-21 07:27 UTC, merged

2023-02-21 18:03 UTC, richvdh commented
Spec PR: https://github.com/matrix-org/matrix-spec/pull/1440

2023-03-21 15:59 UTC, richvdh commented
merged!