MSC3951: Intentional Mentions
matrix-org/matrix-spec-proposals pull request #3952
Opened 2023-01-06 18:23 UTC by clokep

[Rendered](https://github.com/matrix-org/matrix-spec-proposals/blob/clokep/intentional-mentions/proposals/3951-intentional-mentions.md)

2023-01-06 18:40 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +### Backwards compatibility
Somewhere this should mention that users should feel free to use keywords if they would still like their display name (or localpart of their Matrix ID) to generate highlight notifications.

2023-01-06 18:41 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +behavior specific to those push rules with those IDs.
I couldn't come up with another option unless there was a condition to check if a field was missing (but that seems a bit odd).

Also `.m.rule.contains_user_name` is a content rule, which can't have conditions.

2023-01-06 18:42 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +will also match. It is postulated that this will not cause issues in most cases.
I'm not fully convinced this won't be an issue, will need to do some testing.

2023-01-06 18:43 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +in order to receive notifications of replies.
Maybe this MSC should recommend that clients add the user to the `mentions` array when replying? Otherwise we would lose the ability of replies to cause notifications.

2023-01-06 18:48 UTC, bradtgmurray commented on proposals/3952-intentional-mentions.md
> +### Prior proposals
Also https://github.com/matrix-org/matrix-spec-proposals/pull/1796 ?

This is my preferred proposal, as it allows server-side push rules to handle mentions, with the trade-off of leaking a bit more metadata

2023-01-06 18:52 UTC, sumnerevans commented on proposals/3952-intentional-mentions.md
> +### Prior proposals
#1796 only suggests adding the `m.mentions` field to `m.room.encrypted` events so it would need to be expanded to unencrypted events as well to bring it to feature-parity with this proposal.

2023-01-06 19:01 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +### Prior proposals
I somehow did not come across that one in my research. It sounds awfully similar to this though. Will take a closer look.

2023-01-08 14:32 UTC, ShadowJonathan commented on proposals/3952-intentional-mentions.md
> +### Abuse potential
To add: it may also be turned into a feature, where a client displays "implicit mentions" / "CCs" on top or at the bottom of the message, de-emphasised, to show users who read that message the additional mentions that were added to it outside of the message body itself.

2023-01-09 13:47 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +* Each time a message is edited the new version will be re-evaluated for mentions.
Spurious notifications from message edits isn't fixed by this MSC.

2023-01-09 18:08 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +### Prior proposals
I read through this again and I think there's a few main changes (shout if I'm missing something):

1. Keeps the list of users unencrypted so servers can help out here.
2. Allow `@room` as a special value to also avoid issues with room notifications.
3. `m.room.encrypted` events vs. all events.

2 I think is fairly non-controversial and would make sense (I didn't find issues about edge-cases involving it, but I think you can extrapolate potential ones from the issues with user mentions).

For 1, as you highlight above, the tradeoff is mostly a bit more metadata leaking. I think this is probably worthwhile, although clients still need to decrypt if they want keyword notifications. Any chance you could write a quick blurb on what you think this tradeoff is useful? I'm not fully sure what clients win from this if they still need to decrypt for keywords.

And finally, I think expanding to all events is reasonable, especially with things like extensible events coming out.

2023-01-09 18:09 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +### Prior proposals
> Any chance you could write a quick blurb on what you think this tradeoff is useful? I'm not fully sure what clients win from this if they still need to decrypt for keywords.

What I'm trying to say here -- is the rationale given in MSC1796 still valid today or do most clients decrypt all events anyway?

2023-01-09 18:58 UTC, bradtgmurray commented on proposals/3952-intentional-mentions.md
> +### Prior proposals
The biggest use case for leaving mentions unencrypted is for allowing "muted-except-for-mentions" push rules for large rooms. I want a push when I get mentioned in a large encrypted room that we use for team communication but I don't want pushes for every message. With a platform like iOS that doesn't get to sync regularly in the background, the server needs enough information to decide whether to send a push to my mobile app or not, and today it doesn't.

Without this, yes the iOS app can sync events and decrypt them and run push rules against them when the app is foregrounded, but at that point you probably just want to update notifcation/highlight counts as opposed to notifying the user of a specific message from some time ago.

2023-01-09 20:54 UTC, sumnerevans commented on proposals/3952-intentional-mentions.md
> +* Each time a message is edited the new version will be re-evaluated for mentions.
I don't think that this should be in scope for this MSC as this can already be handled using existing push rules to skip notifying if it's an `m.replace`ment.

https://github.com/beeper/synapse/blame/beeper/rust/src/push/base_rules.rs#L98-L114

2023-01-10 08:37 UTC, ShadowJonathan commented on proposals/3952-intentional-mentions.md
> +### Prior proposals
I'd ask to make it configurable between unencrypted and encrypted mentions, as it sounds like it could be a bit too much of a data leak.

2023-01-10 13:00 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +* Each time a message is edited the new version will be re-evaluated for mentions.
Yep, I don't think this is in-scope for this MSC, this is mostly a note to myself that it is a bit odd to include it in the list here, but then not fix it.

2023-01-10 15:05 UTC, bradtgmurray commented on proposals/3952-intentional-mentions.md
> +### Prior proposals
Configurable makes sense to me, the user generating the event can make the choice where to put the mention data. This does add some complexity to everything else as now things like push rules would need to check two spots.

Hrm, maybe this is more complicated. Do clients run push rules on both encrypted and decrypted payloads? Is the resulting action the superset of both runs? Or do you take the higher priority rule? What if both runs result in different push rules in the same priority group being matched, one to supress and one to notify?

Or do you just special case the mention rule type as the only one that looks at both encrypted and decrypted content, and you evaluate both payloads at the same time as part of the same push rule "pass". This probably makes more sense.

2023-01-10 15:17 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +### Prior proposals
> Do clients run push rules on both encrypted and decrypted payloads? Is the resulting action the superset of both runs?

I think they run it only on the decrypted payload, although the decrypted payload includes the cleartext keys, I think? Clients processing push rules is poorly specced.

> Or do you just special case the mention rule type as the only one that looks at both encrypted and decrypted content, and you evaluate both payloads at the same time as part of the same push rule "pass". This probably makes more sense.

Not saying we cannot do this, but this would [be different behavior than `m.relates_to`](https://spec.matrix.org/v1.5/client-server-api/#forming-relationships-between-events) where the server and client behavior are purposefully required to be the same. My gut feeling is that we should follow something similar here.

2023-01-10 15:54 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +* Each time a message is edited the new version will be re-evaluated for mentions.
> I don't think that this should be in scope for this MSC as this can already be handled using existing push rules to skip notifying if it's an `m.replace`ment.
> 
> [beeper/synapse@`beeper`/rust/src/push/base_rules.rs#L98-L114 (blame)](https://github.com/beeper/synapse/blame/beeper/rust/src/push/base_rules.rs#L98-L114)

Although... would you mind if I wrote an MSC for this behavior? 😄

2023-01-10 16:11 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +### Abuse potential
Thanks! I added some bits about this at 99ab781f03bdea04cea34a418162d6968309cc13.

2023-01-10 16:12 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +* Each time a message is edited the new version will be re-evaluated for mentions.
> Yep, I don't think this is in-scope for this MSC, this is mostly a note to myself that it is a bit odd to include it in the list here, but then not fix it.

I added a note in a2896b2318812257971c854b306e3c870edc03e0.

2023-01-10 17:32 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +* Each time a message is edited the new version will be re-evaluated for mentions.
I think I might have originally included this since we would want to somehow define what happens if an edit modifies the `mentions` list. I suspect we should just not allow that.

2023-01-10 19:01 UTC, bradtgmurray commented on proposals/3952-intentional-mentions.md
> +* Each time a message is edited the new version will be re-evaluated for mentions.
> Although... would you mind if I wrote an MSC for this behavior? 😄

Do not mind at all, just thinking of making this a base push rule for everyone in the spec?

2023-01-10 19:03 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +* Each time a message is edited the new version will be re-evaluated for mentions.
> > Although... would you mind if I wrote an MSC for this behavior? 😄
> 
> Do not mind at all, just thinking of making this a base push rule for everyone in the spec?

Yes, pretty much. I'll re-use your unstable ID so you won't need to touch anything. 👍

2023-01-10 19:16 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +A new push rule condition and a new default push rule will be added:
We need to mention where this push rule is in the list of push rules.

2023-01-11 14:14 UTC, daniellekirkwood commented on proposals/3952-intentional-mentions.md
> +in order to receive notifications of replies.
Ensuring that users get a notification when their message has been replied to would be ideal (just like when a thread was started off your message in the main timeline).

2023-01-11 15:49 UTC, sumnerevans commented on proposals/3952-intentional-mentions.md
> +in order to receive notifications of replies.
I disagree with adding the replied-to-user in `mentions`.

Notifications for replies can already be handled by existing push rules once https://github.com/matrix-org/matrix-spec-proposals/pull/3664 is merged.

https://github.com/matrix-org/synapse/pull/11804 already has an implementation of the MSC: https://github.com/beeper/synapse/blob/beeper/rust/src/push/base_rules.rs#L181-L196

2023-01-11 18:20 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +in order to receive notifications of replies.
> Notifications for replies can already be handled by existing push rules once #3664

I think this is pretty much what the paragraph I quoted says?

2023-01-11 19:51 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +### Prior proposals
I added some info on this in 4de784893e53995991b18f44329ca074b54547ae and 5dfc0bce5793f761073ec1da12eb66fa0f4508ba, but it likely needs a few more pieces of info.

2023-01-11 19:57 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +> any array entries which are not strings are ignored, but count against the limit.
I debated making this a `is_mention` condition with a value of some sort, which would be the user's MXID or `@room`. Similar to some other conditions e.g. from `.m.rule.invite_for_me`:

```json
{
    "key": "state_key",
    "kind": "event_match",
    "pattern": "[the user's Matrix ID]"
}
```

Or even more generic, making it a `field_contains` which would take a `key` and `value` (or `pattern`).

2023-01-11 20:08 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +in order to receive notifications of replies.
The benefit of using the `mentions` array here is that it signals *sender* intention of whether they want to notify the other user about replying to their message, kind of a reply vs. quote tweet.

MSC3664 gives the *receiver* control over whether to know if a user replies to their message or not.

I'm not sure if that really matters here and I think could be handled in a follow-up. *Not* doing this would add a dependency on MSC3664, however, to avoid regressing behavior.

2023-01-11 20:11 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +and battery savings.
Can this field be edited or shall we declare that it cannot be? What happens if the wrong person is mentioned? Should you be able to fix that?

2023-01-11 23:41 UTC, sumnerevans commented on proposals/3952-intentional-mentions.md
> +in order to receive notifications of replies.
Sorry, I did misread the context, but my point still stands: I think we should add a dependency on #3664.

It feels wrong to depend on the sending user's client determine whether or not the receiver's client should notify on a particular reply, and it feels like it would just be a stopgap measure that could be solved by an existing server-side change that gives more control to the user who is actually receiving the notification.

2023-01-12 15:38 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +* Each time a message is edited the new version will be re-evaluated for mentions.
I started writing this and then realized edits interact weirdly with this MSC, so will probably define that first: https://github.com/matrix-org/matrix-spec-proposals/pull/3952#discussion_r1067414439

2023-01-13 13:22 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +and battery savings.
If we allow this to be edited it:

* Avoids special casing this field.
* Allows people to correct who is mentioned in a message.
  * But this might interact weirdly with MSC3664, which says that edits should not notify? Maybe we shouldn't worry about that at the moment.
* How would you edit this if this is an encrypted event?

2023-01-13 14:32 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +in order to receive notifications of replies.
> Sorry, I did misread the context, but my point still stands: I think we should add a dependency on #3664.

I'd like to avoid adding a dependency on an MSC that seems stuck.

> It feels wrong to depend on the sending user's client determine whether or not the receiver's client should notify on a particular reply, and it feels like it would just be a stopgap measure that could be solved by an existing server-side change that gives more control to the user who is actually receiving the notification.

I'm pondering if it makes sense to have *both*, as a thought experiment, if we have clients add to the `mentions` array when replying it could:

* Allow MSC2781 to land without MSC3664. (I'm not arguing this is desirable, just that it is possible.)
* Allow mentioning both `alice` & `bob` when `charlie` replies to `bob`'s reply to `alice`. (Currently this is done via reply-fallbacks IIRC, but that wouldn't be possible after MSC2781, even with MSC3664.)
* Reply *without* mentioning the original sender: "quote-tweet"-ing.

The last two points give control to the *sender*, but for the *receiver* to also have control then MSC3664 could be used:

* Allow a user to be notified of *all* replies to their messages, regardless of if the sender included the user in the `mentions` array.

----

I don't know if this over-complicates things, but I think it is worth at least considering as an alternative or augmentation to MSC3664.

2023-01-13 20:41 UTC, turt2live commented
The author of this MSC is seeking initial review before implementation begins.

2023-01-13 21:29 UTC, turt2live commented on proposals/3952-intentional-mentions.md
> +### Room version for backwards compatibility
mentioned over DM, but an option might be to throw all the eggs into one basket here and phrase this MSC as an MSC1767-compatible mixin (similar to MSC3955), which then can be considered "core" for extensible events itself. This would mean that old, non-extensible, room versions don't get a mentions array, but new events and their shiny new format would.

It's unclear to me at this stage if this would be a good idea, but it may be a practical idea to encourage adoption while not having to worry about backwards compatibility.

2023-01-13 22:42 UTC, pacien commented
This proposal would also
- solve: https://github.com/matrix-org/matrix-spec/issues/550
- make obsolete: https://github.com/matrix-org/matrix-spec-proposals/pull/2463

2023-01-14 00:17 UTC, 0x1a8510f2 commented on proposals/3952-intentional-mentions.md
> +and battery savings.
Though I can't answer the questions you listed, I want to put my vote in to allow edits, for parity with the current way mentions are done.

2023-01-14 00:28 UTC, 0x1a8510f2 commented on proposals/3952-intentional-mentions.md
> +To limit the potential for abuse, only the first 10 items in the array should be
I would argue that this should be increased and pretty significantly too (maybe up to 100 or even 255 entries?). My reasoning is that spammers can be dealt with by means of banning or server ACLs, and between `@room` and just sending multiple events, they also have plenty of ways to sidestep this altogether. Meanwhile, legitimate uses such as mentioning a specific team in one message would be more affected by this, since Matrix has no concept of role mentions or the likes.

In general I can imagine legitimate users hitting this ceiling while I think such protocol-level limits should at least be at a level where we shouldn't expect to find legitimate users.

As you mention further down, making this configurable would address this issue, but too much configurability isn't always a good thing either, though I would prefer that over a limit of 10 people.

2023-01-14 00:40 UTC, 0x1a8510f2 commented on proposals/3952-intentional-mentions.md
> +# MSC3952: Intentional Mentions
Though this would be a pretty significant addition to the MSC, it might be worth considering specifying a Matrix HTML tag also to go with this in the body. For instance:

```
<mx-mention target=0>hello</mx-mention>
```

Where the target is the index of the mxid in the mentions array. This could help deal with spam because mentions not referenced in the body could be ignored (the mentions key would be used as a hint to save battery and the message contents would be checked to confirm whether to send a notification). Furthermore, the tags could be used to indicate which part of the message one wants to being to the attention of the mentioned user. A pill could then also be inserted where the tag starts to allow for direct access to the mentioned user's profile by clicking it, as many chat clients do.

This hybrid approach effectively retains advantages of putting mentions in the body:
- Less opportunity for mention spam
- Easy placement of pills
- Directing attention to parts of messages

And of putting them in a separate key:
- Easier to search hence less resource-hungry
- Less ambiguous

With none of the disadvantages, except maybe a very slightly larger event size.

2023-01-17 13:12 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +### Room version for backwards compatibility
> it may be a practical idea to encourage adoption while not having to worry about backwards compatibility.

It does solve the backwards compatibility issue nicely, the main downside would be pushing out the timeline for adoption.

2023-01-17 13:14 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +To limit the potential for abuse, only the first 10 items in the array should be
10 was a mostly arbitrary number -- it seemed reasonable for most cases. I wouldn't be opposed to increasing this a bit, but I don't think I've seen a message that wanted to mention 100 people or so though -- that seems like quite a lot?

2023-01-17 13:17 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +# MSC3952: Intentional Mentions
I spent quite a bit of time considering similar formats, but it was unclear how to handle this for plaintext messages (or other message formats, e.g. if a `format` of `com.example.rff` was used -- what do we do in those cases?

There are additional downside:

* It doesn't allow for hidden mentions, which *can* be useful in some situations.
* It isn't as extensible to event types except `m.room.message`.

I should document this in the alternatives though. 👍 Thank you for the reminder!

2023-01-17 18:22 UTC, 0x1a8510f2 commented on proposals/3952-intentional-mentions.md
> +To limit the potential for abuse, only the first 10 items in the array should be
I also would not expect regular messages to have anywhere near 100 mentions, but given that this is a hard limit which would take a long time to increase should it prove to be too restrictive (as the whole client/server ecosystem would need to adopt the new limit) I think too much is better than too little here.

We should also keep in mind bridging and automation when setting the limit. Some platforms we may want to bridge with might allow more/unlimited mentions so this limit might make bridging difficult. Bots might also want to mention a large amount of users (but not all users), say in the case of announcements one can subscribe to, as way more than 10 or even 100 users could subscribe to a particular announcement.

2023-01-17 18:29 UTC, 0x1a8510f2 commented on proposals/3952-intentional-mentions.md
> +# MSC3952: Intentional Mentions
Fair points, though I find it hard to let go of the ability to place pills in specific places.

What if we make the tag optional?

That would nullify my point about "less opportunity for mention spam" but otherwise has the same advantages and should address your concerns as it would optionally apply to any event which supports matrix HTML tags.

2023-01-17 20:27 UTC, Half-Shot commented on proposals/3952-intentional-mentions.md
> +To limit the potential for abuse, only the first 10 items in the array should be
I'm actually in agreement here that this limit is probably going to cause lots of problems, an example being a calendar bot for a large team which would easily exceed the 10 user ping. Arguably you could ping the room at that point...but presently in Matrix we've been pinging more than 10 folks legitimately.

Playing devils advocate: I'm not *actually* sure putting a maximum on the ping count is all that useful in the same way we don't limit the number of  `<p>` you can put into a message to fill up a room's timeline. This feels like a thing where if someone tries to spam by pinging lots of users, you just kick the user. (Possibly ending up as a Mjolnir moderation rule, for automatic-ness)

I think hardcoding a maximum ping count in the spec will ultimately break *someones* valid use case, and to me the spec shouldn't be policing user content. It should just facilitate the ability of other services/humans to handle it.

2023-01-17 20:32 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +# MSC3952: Intentional Mentions
> What if we make the tag optional?

This is essentially how the MSC is currently written, [it recommends](https://github.com/matrix-org/matrix-spec-proposals/blob/clokep/intentional-mentions/proposals/3952-intentional-mentions.md#new-event-field):

> Clients should add a Matrix ID to this array whenever composing a message which includes an intentional [user mention](https://spec.matrix.org/v1.5/client-server-api/#user-and-room-mentions) (often called a "pill").

A pill is HTML of the form of `<a href='https://matrix.to/#/@alice:example.org'>Alice</a>`, i.e. a matrix.to link to the user.

2023-01-17 21:14 UTC, 0x1a8510f2 commented on proposals/3952-intentional-mentions.md
> +# MSC3952: Intentional Mentions
I guess it's not exactly the same thing, since it allows for non-mention pills, but that's actually probably a good thing so I can agree with that. Cool!

2023-01-17 21:19 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +# MSC3952: Intentional Mentions
> I guess it's not exactly the same thing, since it allows for non-mention pills, but that's actually probably a good thing so I can agree with that. Cool!

Yep, I think it makes sense if you're talking *about* someone but don't want to mention them? A common example I've had is that I'm DMing someone and say "Oh hey you should talk to my pal `@phil:example.com` about this!", it would be nice to pillify that into a nice matrix.to link, but they're obviously not in the conversation (so you can't "mention" them).

2023-01-21 14:24 UTC, anoadragon453 reviewed
So far this looks quite reasonable and elegant on its own. A few thoughts below.

2023-01-21 14:24 UTC, anoadragon453 commented on proposals/3952-intentional-mentions.md
> +in order to receive notifications of replies.
As a lay of the chat landscape; Discord has the ability to enable/disable notifying a user when you reply to their message. I personally find this feature quite helpful. For instance, I'll turn off the notification if I'm referencing something someone mentioned earlier, but am directing my message to the immediate conversation (which the person I'm replying to may not be part of).

2023-01-21 14:31 UTC, anoadragon453 commented on proposals/3952-intentional-mentions.md
> +consistent of Matrix IDs or the special value: `"@room"`.
heh, these were meant to be turned into suggestions before submitting my review.

```suggestion
consisting of Matrix IDs or the special value: `"@room"`.
```

2023-01-21 14:31 UTC, anoadragon453 commented on proposals/3952-intentional-mentions.md
> +encrypted into the ciphertext for encrypted events. This expoes slightly more
```suggestion
encrypted into the ciphertext for encrypted events. This exposes slightly more
```

2023-01-23 13:32 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +`"@room"` value.
This isn't called out, but yes the implication is that it would only ever generate a single notification per message.

2023-01-24 08:00 UTC, Johennes commented on proposals/3952-intentional-mentions.md
> +To limit the potential for abuse, only the first 10 items in the array should be
As a concrete example, for the Element web weekly we have 120 users in the room and the calendar reminder pings the 17 required attendees.

2023-01-24 08:03 UTC, Johennes commented on proposals/3952-intentional-mentions.md
> +metadata to homeservers, but allows mentions to work properly via push notifications
Do clients not already have to decrypt events when receiving push notifications, e.g. in order to display the event text in the system notification area?

2023-01-24 08:16 UTC, Johennes commented on proposals/3952-intentional-mentions.md
> +user-specific keywords, the process for doing this is costly (either receiving
Clients will also have to decrypt events for rules that filter on the event type, such as the polls-specific push rules in MSC3930. I suspect that live location sharing as defined in MSC3489 will require similar event-specific rules.

2023-01-24 13:46 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +> any array entries which are not strings are ignored, but count against the limit.
Yep, role mentions are a thing I was considering as a nice extension. I wonder if the field would make more sense to use an object and not do magic string matching on `@room`:

```json5
{
    ...,
    "mentions": {
        "user_ids": [...],  // optional
        "room": true,  // optional
        "roles": [...]  // defined in a future MSC
    }
}
```

2023-01-24 13:50 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +user-specific keywords, the process for doing this is costly (either receiving
Only if they're being pushed every event; in the case where a room is set to mentions-only we could stop pushing those events, see our [above conversation](https://github.com/matrix-org/matrix-spec-proposals/pull/3952#discussion_r1084916055).

I'm not trying to imply that clients no longer need to decrypt events to process notifications, just that this fixes a class of needing to *push* events.

2023-01-24 14:03 UTC, ShadowJonathan commented on proposals/3952-intentional-mentions.md
> +> any array entries which are not strings are ignored, but count against the limit.
This could maybe be achieved by making it `mention`, and in the same MSC telling that `mentions` is optional and deprecated.

It already is "optional" here due to historic behaviour, but in the future that could be used as a stepping stone for transition to an object?

2023-01-24 14:53 UTC, kegsay commented on proposals/3952-intentional-mentions.md
> +To limit the potential for abuse, only the first 10 items in the array should be
> I think hardcoding a maximum ping count in the spec will ultimately break someones valid use case, and to me the spec shouldn't be policing user content. 

I fundamentally disagree with this because we _do_ need limits to ensure servers can remain quick and responsive. 

That being said, there is an inherent limit anyway due to event size limits. The main question revolves around how expensive the `mentions` field is computationally/memory wise from a server perspective. If it's dead cheap then sure let's have no limit, but if this is expensive / can be abused then not having a limit is just asking for trouble imo.

2023-01-24 14:56 UTC, kegsay commented on proposals/3952-intentional-mentions.md
> +mentioned Matrix IDs to be part of the displayed text. Depending on the use this
This is only "hidden" in the sense that client UIs don't currently display this information. Nothing stops clients from making these visible e.g as a decorator like we have `(edited)` we can easily say `(notified X people)` with a click-through to the list.

2023-01-24 14:59 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +> any array entries which are not strings are ignored, but count against the limit.
I don't see why we would define it one way just to immediately deprecate it? If we think we might add to it in the future, then we should just make it an object now.

2023-01-24 14:59 UTC, ptman commented on proposals/3952-intentional-mentions.md
> +To limit the potential for abuse, only the first 10 items in the array should be
how may can be mentioned in 64k of JSON?

2023-01-24 15:14 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +To limit the potential for abuse, only the first 10 items in the array should be
> If it's dead cheap then sure let's have no limit, but if this is expensive / can be abused then not having a limit is just asking for trouble imo.

It is likely fairly cheap; the server (and client) would traverse the list (ignoring non-string entries), and search for the current user's Matrix ID. You could certainly make a pretty long list if this is the only bit of your message size.

----

As I mentioned above, but maybe not strongly enough. **10 was chosen arbitrarily** and I am definitely not opposed to increasing it. I'll look into this further.

2023-01-24 15:16 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +mentioned Matrix IDs to be part of the displayed text. Depending on the use this
Definitely! I think this is even mentioned below (or maybe it was just discussed as part of the team). By "hidden" I meant "not part of the message" content -- I'll try to spell that out a bit more that this is a current UI limitation.

2023-01-24 15:41 UTC, Johennes commented on proposals/3952-intentional-mentions.md
> +user-specific keywords, the process for doing this is costly (either receiving
Oh, I see. I hadn't previously understood that you were mainly thinking about rooms that are set to mentions-only. That might be a nice improvement.

2023-01-24 16:02 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +mentioned Matrix IDs to be part of the displayed text. Depending on the use this
I reworked this section a bit to combine the UI ideas together up-front, then discuss abuse a bit more. I think that flows better. Thanks!

2023-01-24 16:21 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +in order to receive notifications of replies.
I'm going to park this conversation -- it feels like a future MSC should work out exactly how replies should work; perhaps I will write an alternative to MSC3664 that depends on this.

2023-01-24 16:22 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +* Each time a message is edited the new version will be re-evaluated for mentions.
(I still plan to do this, but it isn't blocking this MSC so I'm going to resolve the thread. I'll try to remember to cross-link when I write it.)

2023-01-24 16:23 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +and battery savings.
Right now edits cause notifications to be processed; it doesn't seem to be part of this MSC to change that behavior or define special rules there. I'm going to park this for a future MSC.

2023-01-24 16:34 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +metadata to homeservers, but allows mentions to work properly via push notifications
I tried to make this a bit clearer by pointing to another section of the MSC.

2023-01-24 16:45 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +To limit the potential for abuse, only the first 10 items in the array should be
I've moved this to a recommendation for moderation tooling for now.

2023-01-24 18:03 UTC, Johennes commented on proposals/3952-intentional-mentions.md
> +user-specific keywords, the process for doing this is costly (either receiving
For location sharing we haven't yet detailed the push rules but for polls MSC3930 proposes underride rules for controlling notifications on poll start / end events but also an _override_ rule for silencing poll votes in general. Do you think that would conflict with your proposal?

2023-01-24 18:44 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +user-specific keywords, the process for doing this is costly (either receiving
No, that should work fine!

2023-01-24 19:22 UTC, bradtgmurray commented on proposals/3952-intentional-mentions.md
> +[^2]: Note that this MSC does not attempt to solve the problem of issues generating
```suggestion
[^2]: Note that this MSC does not attempt to solve the problem of edits generating
```

2023-01-24 19:24 UTC, bradtgmurray commented
Just want to say from the peanut gallery that this looks great!

2023-01-24 22:53 UTC, turt2live commented
Now that implementation has happened, the author is seeking more thorough review from the SCT, possibly FCP if ready.

2023-01-26 21:07 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +> or contains a non-boolean `room` field then the rule does not match.
I failed to call out in here that the user sending the `@room` must still abide by the power-levels event. There's no intention to change that in this MSC.

2023-01-26 21:12 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +> or contains a non-boolean `room` field then the rule does not match.
Oh, never mind -- I did include the check against `sender_notification_permission`, it is just a different condition! 👍

2023-01-30 17:33 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +behavior specific to those push rules with those IDs.
Another option would be to have clients start setting `m.mentions` field ASAP and leave these push rules in place for now (as-is). This wouldn't fix all the unintentional pings problems until these push rules are removed at a later date, however.

2023-01-31 17:34 UTC, richvdh reviewed
looks eminently sensible to me. I have a few comments but I think we should start the FCP process.

2023-01-31 17:34 UTC, richvdh commented on proposals/3952-intentional-mentions.md
> +        },
I note that the existing `.m.rule.roomnotif` rule is silent by default (it lacks a `set_tweak: sound` action). Is this a deliberate change?

2023-01-31 17:34 UTC, richvdh commented on proposals/3952-intentional-mentions.md
> +will not help with???.
looks like this needs finishing up

2023-01-31 17:34 UTC, richvdh commented on proposals/3952-intentional-mentions.md
> +A new `m.mentions` field is added to the event content, it is an object with two
comma splice 
```suggestion
A new `m.mentions` field is added to the event content; it is an object with two
```

2023-01-31 17:34 UTC, richvdh commented on proposals/3952-intentional-mentions.md
> +There is also some other related bugs:
```suggestion
There are also some other related bugs:
```

2023-01-31 17:34 UTC, richvdh commented on proposals/3952-intentional-mentions.md
> +of a gappy sync) in terms of bandwidth, CPU, and battery.
I'm struggling to grok this run-on sentence. Rephrase, with fewer commas?

2023-01-31 17:34 UTC, richvdh commented on proposals/3952-intentional-mentions.md
> +There's a few prior proposals which tackle subsets of the above problem:
```suggestion
There are a few prior proposals which tackle subsets of the above problem:
```

2023-01-31 17:34 UTC, richvdh commented on proposals/3952-intentional-mentions.md
> +  "key": "m.mentions.room",
```suggestion
  "key": "content.m.mentions.room",
```

2023-01-31 17:34 UTC, richvdh commented on proposals/3952-intentional-mentions.md
> +```
I'd be quite in favour of this, to reduce the number of push conditions we end up with, and because I think MSC3758 deserves more love than it's had so far.

I realise it means you end up blocked behind MSC3758 (and possibly MSC3873), though, so I'll forgive you if you need to forge ahead.

2023-01-31 17:34 UTC, richvdh commented on proposals/3952-intentional-mentions.md
> +of mentions working properly and the savings in bandwidth and battery makes it worthwhile.
debatable.

```suggestion
Including the mentioned users in cleartext is a small metadata leak, but we consider that the tradeoff
of mentions working properly and the savings in bandwidth and battery makes it worthwhile.
```

2023-01-31 17:34 UTC, richvdh commented on proposals/3952-intentional-mentions.md
> +> This matches messages where the `m.mentions` field of the `content` contains a
s/field/property/, please, per https://github.com/matrix-org/matrix-spec/blob/main/meta/documentation_style.rst#general.

2023-01-31 17:34 UTC, richvdh commented on proposals/3952-intentional-mentions.md
> +logic and start creating events with the `m.mentions` field.
stable identifiers for the push rules?

It feels a little bit magical to me that *sending* of `m.mentions` properties depends on which push rules are seen. Why do we need to gate the transmission of `m.mentions` at all - can't we start immediately?

Why do we need to gate the `m.mentions`

2023-01-31 17:56 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +```
I agree that MSC3758 is a better solution here, it had not received much interest AFAICS. I'll take another look at it.

2023-01-31 18:03 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +(e.g. `event_match`) can process arrays.
I had the same thought at https://github.com/matrix-org/matrix-spec-proposals/pull/3952#discussion_r1067403177; it sounds like @anoadragon453 also slightly favors a generic rule.

2023-01-31 18:05 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +of a gappy sync) in terms of bandwidth, CPU, and battery.
Hopefully 425d1d61a8c494ee2bb9e9f47336f497ba9ee8a2 clarifies this by splitting it into two sentences.

2023-01-31 18:06 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +logic and start creating events with the `m.mentions` field.
I don't think it was my intention to necessarily gate adding these to events, will reword.

2023-02-01 20:21 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +(e.g. `event_match`) can process arrays.
This seems to be MSC3887.

2023-02-09 17:51 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +```
This was done in ced04e19730283b6c56a8ef903d20634cde63363.

2023-02-10 14:08 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +(e.g. `event_match`) can process arrays.
I wrote MSC3966 for this, will update this MSC with the requirement soon.

2023-02-17 17:43 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +will also match. It is postulated that this will not cause issues in most cases.
@andybalaam Suggested that we just fully disable these rules when extensible events gets its own room version and (at that point) no longer require sending an empty `m.mentions` on each event.

2023-02-20 17:27 UTC, dkasak requested changes

2023-02-20 17:27 UTC, dkasak commented on proposals/3952-intentional-mentions.md
> +significantly increase metadata leakage.
That said, I also believe this *not* to be an appropriate design trade-off for several reasons.

First, Matrix already leaks far too much (meta)data which should be encrypted and this is a move in the wrong direction. It's well known that a lot meaning can be gleaned contextually from even simple things like timestamps and message senders, let alone the more juicy stuff like message types, reactions and who the message mentions. If Matrix is to be taken seriously in circles requiring strong security, we should be working on reducing this surface area rather than increasing it.

Second, there is clearly a fundamental tension between encryption and server-side processing. Every time a feature is implemented on the server, it necessarily means we must be leaking some data to it. But there are already existing important Matrix features which require complete client-side timeline access in order to work at all -- notable examples include encrypted room search and keywords (as mentioned by the MSC too). Unless we plan on dropping support for these features, we will already have all required information to implement properly encrypted mentions. This should at least give us some pause.

Finally, there is a game theoretical problem here. Some people will want to encrypt mentions, and there is nothing preventing them from implementing this. I am predicting this will happen anyway, so it would be nice if this MSC was deliberately crafted in such a way to allow for and encompass this usage too.

Ultimately, I believe encrypted room search is a core feature that most users will want and so support for it will grow with time, at which point cleartext mentions in encrypted rooms will be an unnecessary sore thumb. At a minimum, I think this MSC shouldn't be making the call to place explicit mentions in cleartext but allow for both cleartext and plaintext placement.

2023-02-21 20:15 UTC, ara4n commented on proposals/3952-intentional-mentions.md
> +significantly increase metadata leakage.
on reflection, I agree with @dkasak completely on this - @clokep, i'm really sorry for not having bandwidth to properly review this and feed back sooner.

The thing that clinches it for me is that we already are committed to downloading all contents in E2EE rooms in order to calculate unread state (given the server doesn't know if a msg is visible until it's decrypted), notifying for keyword mentions, updating full-text indexes for E2EE content, etc.  For instance, Sliding Sync is designed with this assumption in mind: https://github.com/matrix-org/matrix-spec-proposals/blob/kegan/sync-v3/proposals/3575-sync.md#e2ee-handling.

2023-02-21 20:27 UTC, uhoreg commented on proposals/3952-intentional-mentions.md
> +To avoid unintentional mentions these rules are modified to only apply when the
There seems to be a contradiction here, where you say earlier that those rules "are to be removed", but then you say here that the rules "are modified".  How do we both modify and remove the rules?  Or are you saying that the rules will be removed at a later time (i.e. deprecated)?

2023-02-21 20:27 UTC, uhoreg commented on proposals/3952-intentional-mentions.md
> +(often called a "pill"). Clients should set the `room` value to `true` when making a
Also add the Matrix ID when replying to a message by that user?

2023-02-21 20:27 UTC, uhoreg commented on proposals/3952-intentional-mentions.md
> +significantly increase metadata leakage.
I agree with @dkasak here.  Making the mentions unencrypted makes me uneasy.  It's not clear that the benefits outweigh the data leak risk, and I'd prefer to err on the side of security here.

@mscbot concern Security of unencrypted mentions

2023-02-21 20:27 UTC, uhoreg commented on proposals/3952-intentional-mentions.md
> +
I'm not sure if this is worth mentioning, or where it should be mentioned, but bridges may need to parse messages and add a `m.mentions` when it thinks the sender is mentioning someone.  The bridge may guess incorrectly and ping someone who wasn't supposed to be mentioned (intentionally), but I don't think the situation is any worse than what we currently have.

2023-02-21 20:34 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +* `room`: a boolean, true indicates an "@room" mention. Any other value or the
I see this as potentially a property under this, see https://github.com/matrix-org/matrix-spec-proposals/blob/clokep/intentional-mentions/proposals/3952-intentional-mentions.md#role-mentions

2023-02-21 20:36 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +To avoid unintentional mentions these rules are modified to only apply when the
> Or are you saying that the rules will be removed at a later time (i.e. deprecated)?

Yes, they're essentially deprecated by this MSC and modified to shut-off if the event content has a `m.mentions` property. I'm hoping this is backwards-compatible enough that once the ecosystem upgrades we can just remove them completely (or do it when we do the extensible events room upgrade?)

2023-02-21 20:39 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +(often called a "pill"). Clients should set the `room` value to `true` when making a
There's another thread about this: https://github.com/matrix-org/matrix-spec-proposals/pull/3952#discussion_r1063689061

I think I'm inclined to say "yes", but others feel that MSC3664 is a better solution. I'd like to see a hybrid approach where the sending client includes it (to signal the the intention that the user should be notified) and then the receiver decides whether it wants to be notified or not via a combination of this MSC + MSC3664. This would allow users to quote-reply, essentially. (I.e. without pinging the initial sender.)

2023-02-21 20:41 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +
I thought I included this info in here, but...I didn't. 😄 According to @Half-Shot this MSC has the potential to make things better (as bridges can run into all the same issues discussed in the pre-amble) without really making things worse -- i.e. bridges for protocols without explicit mention information (IRC?) still need to do the mapping between IRC and Matrix ID, now they just have the explicit mapping to put that information into, instead of trying to modify the original message text.

(@Half-Shot or @tulir does that sound accurate?)

2023-02-21 20:44 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +obvious the user intends to explicitly mention a user.
An earlier version of the MSC (or maybe the design doc?) discussed that clients could prompt when trying to send a message that will notify X people to double check you really do mean to send that message. I think it would not be a requirement, but does seem like a good idea. I can add a brief note about it.

2023-02-21 20:54 UTC, uhoreg commented on proposals/3952-intentional-mentions.md
> +* `room`: a boolean, true indicates an "@room" mention. Any other value or the
Yeah, my suggestion was more as a means of avoiding having to add a new property in the future, but I think it's more a matter of taste.  While I have a slight preference for my suggestion, either way is fine.

2023-02-21 20:59 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +in order to receive notifications of replies.
Actually -- I'm going to unresolve this thread, I think if we're asking clients to include the `m.mentions` field on all messages we need to deal with how users get notified of replies (otherwise users will not be notified of replies once this MSC lands).

2023-02-21 20:59 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +(often called a "pill"). Clients should set the `room` value to `true` when making a
I've unresolved the other thread that has more context (I'm going to resolve this one to not have duplicates!)

2023-02-22 12:55 UTC, richvdh commented on proposals/3952-intentional-mentions.md
> +or backpaginate every room fully, in case of a gappy sync.
According to @ara4n, we *do* expect clients to decrypt all messages nowadays (and for all encrypted messages to cause pushes so that they can do so).  So it seems like the argument against encryption largely goes away?

2023-02-22 13:52 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +
I dug up my previous conversation with @Half-Shot about this, it mostly echos [previous thoughts](https://github.com/matrix-org/matrix-spec/issues/353#issuecomment-1055809364) of his:

> Yes, we had the problem where IRC users would ping users on Matrix by their IRC nick, which meant we had to search and replace all messages coming from IRC ->Matrix with your Matrix nick in an effort to make it ping.
>
> Which was a bit fraught and rubbish, because:
>
> 1. You might, if your nickname was something like `will`, turn off keyword matching.
> 2. It broke the contract of sorts we have with bridges not to mutate the content of messages.
> 3. It also meant we had to build Regex's to run over every message, and try to figure out if a message contained all possible nicknames that we had cached in memory.
>
> I don't think this MSC fixes 3, but it does fix 1 and 2.

I'll try to include some of this in the MSC!

2023-02-22 14:11 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +significantly increase metadata leakage.
Thanks for leaving your thoughts, I had originally written this MSC without any special encryption behavior for this property (i.e. it would be encrypted), but
updated it [based on a conversation](https://github.com/matrix-org/matrix-spec-proposals/pull/3952#discussion_r1063691992) which unearthed MSC1796. From my reading of that it seemed the logic in MSC1796 was still sound, *and* it would allow for additional features (namely "muted-except-for-mentions" push rules). The previous thread did discuss a bit about making it configurable whether to encrypt or not, but that seemed overly complicated.

I suppose MSC1796 should have been closed when matrix-org/synapse#1131 was merged into Synapse, i.e. once we started pushing all messages to mobile devices. (Note that this was before the MSC process so I couldn't really figure out how much we wanted this was vs. it being a hack to make things work.)

> The thing that clinches it for me is that we already are committed to downloading all contents in E2EE rooms in order to calculate unread state (given the server doesn't know if a msg is visible until it's decrypted), notifying for keyword mentions, updating full-text indexes for E2EE content, etc.

I will *softly* push back on this though: mobile clients do get all encrypted messages pushed to them so they do properly calculate unread state; although they do not always do proper keyword matching *or* full-text indexing of this content it seems they *could*.

Most[^1] web clients, however, *do not* get all encrypted messages and only do a partial backfill on gappy syncs (https://github.com/matrix-org/matrix-spec-proposals/blob/kegan/sync-v3/proposals/3575-sync.md#e2ee-handling describes this briefly); thus the unread state (and keyword notifications) are an estimate.

The full-text index on Element Desktop (I'm unsure if any other clients have this feature) *does* fully backfill, but does not share this information with the notification processing (and likely has different assumptions, e.g. it backfills slowly in the background).

----

tl;dr: I'll revert the changes to this MSC which discuss keeping the `m.mentions` field in cleartext. I think the rest of the implementation is still sound, but pushes a bit more work onto clients.

[^1]: The only web client I know of which gets push notifications is [Hydrogen](https://github.com/vector-im/hydrogen-web/blob/master/doc/implementation%20planning/PUSH.md), but it [doesn't seem to support decrypting pushed messages](https://github.com/vector-im/hydrogen-web/blob/13428bd03c7ec3821352ab13eb631fb0bbe23e94/src/platform/web/sw.js#L297-L303).

2023-02-22 14:24 UTC, bradtgmurray commented on proposals/3952-intentional-mentions.md
> +significantly increase metadata leakage.
Agreed on reverting the controversial parts to get the MSC through, but I still do want to advocate for servers being able to discern when to push notifications, especially in the iOS case.

In iOS, in order to display an encrypted notification to the user, we need to use a UNNotificationServiceExtension (https://developer.apple.com/documentation/usernotifications/unnotificationserviceextension), which allows us to run some code to decrypt a notification to display the cleartext content to a user. A drawback to this approach is that iOS insists that every notification that is pushed is shown to the user, and the UNNotificationServiceExtension (aka NSE) is only allowed to transform content, not supress. This means that unless I want a push notification on my home screen for every encrypted message in a group chat I'm in, I need to mute the room using a push rule to mute all notifications to that room. This would override https://github.com/matrix-org/synapse/pull/1131, which brings us to the situation where we're at today, where mentions in muted rooms get missed.

Having the the mention information in the cleartext would allow us to implement on the server an APNS push for mentions but not for other encrypted messages.

This is probably a discussion for a future MSC, and again, I think it makes sense to remove putting the mention information in the cleartext to get this through, but in the future I'd like to allow the clients that our users use to specify which metadata they're ok leaking to opt into better UX, depending on their usecase.

2023-02-22 15:20 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +logic and start creating events with the `m.mentions` field.
Honestly I have no idea what this sentence is trying to say -- it seems like this was already covered in the backwards compatibility section above about when to apply these push rules.

2023-02-22 15:22 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +To avoid unintentional mentions these rules are modified to only apply when the
Fixed in e346fbb27bf1374f0d58b38ea2d1b1694397c305.

2023-02-22 15:22 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +logic and start creating events with the `m.mentions` field.
(I removed it in e346fbb27bf1374f0d58b38ea2d1b1694397c305.)

2023-02-22 15:22 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +will also match. It is postulated that this will not cause issues in most cases.
I added @andybalaam's suggestion in e346fbb27bf1374f0d58b38ea2d1b1694397c305.

2023-02-22 15:24 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +significantly increase metadata leakage.
Thanks for more of the technical information.

I've updated the text in f0a1f6ad184788814c45d58370248b8052142171 to give no special handling of this field. A future MSC may wish to do so.

2023-02-22 15:31 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +* `room`: a boolean, true indicates an "@room" mention. Any other value or the
Oh, I've just realized your comment applies *specifically to the `room`* field! That clears it up a bit, to visualize this a bit I think you're saying this would be:

```json
{
  "m.mentions": {
    "user_ids": ["@alice:example.com"],
    "groups": ["m.room"]
  }
}
```

The original text of this MSC (and MSC1796) proposed using a constant (`"@room"`) inside the same array as the user IDs, I liked separating it out for clarity / less magic (and less potential for parser errors). Having an array of other "groups" of people might make sense, but I think it still is clearer to separate them out, e.g.:

```json
{
  "m.mentions": {
    "user_ids": ["@alice:example.com"],
    "room": True,
    "roles": ["m.moderator"],
    "room_ids": ["#parent-space:example.com"]
  }
}
```

I'm struggling a bit without trying to define the behavior there.

2023-02-22 15:42 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +obvious the user intends to explicitly mention a user.
FTR I don't think this is really *changing* anything, just making the behavior explicit? I think users already expected pilled usernames to be mentioned.

2023-02-22 15:49 UTC, dkasak commented on proposals/3952-intentional-mentions.md
> +significantly increase metadata leakage.
Provided it's configurable, I am considerably less closed to it. But that would also make it significantly less reliable, since unless the user enables it for their mentions, push notifications would still not work on iOS under the described implementation.

The real problem seems to be that iOS is such a user and encryption hostile platform.

2023-02-22 16:35 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +
Added in 8f2805defcc25865f37e9ddfd94b08553b2bbbe4.

2023-02-22 16:45 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +* `room`: a boolean, true indicates an "@room" mention. Any other value or the
@uhoreg I think I would prefer to leave this as-is; do you want me to note this in the alternatives?

2023-02-22 19:36 UTC, deepbluev7 commented on proposals/3952-intentional-mentions.md
> +via a background process but *cannot* be suppressed. This means it is not possible
I am pretty sure this is possible nowadays: https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_usernotifications_filtering

2023-02-22 19:37 UTC, mrredcon commented
I agreed with keeping the mentions in cleartext as it would solve that "Muted except for mentions push rules" problem the proposal identifies.  How would the iOS problem be solved without keeping mentions in cleartext?  Perhaps the spec could be modified to allow for server admins to toggle encrypted mentions on or off.

2023-02-22 19:38 UTC, deepbluev7 commented on proposals/3952-intentional-mentions.md
> +significantly increase metadata leakage.
I am pretty sure you can hide notifications on iOS nowadays: https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_usernotifications_filtering

Does anyone have other information?

2023-02-22 19:43 UTC, turt2live commented on proposals/3952-intentional-mentions.md
> +significantly increase metadata leakage.
(marking as unresolved given this area is a *very* active discussion)

2023-02-22 20:39 UTC, bradtgmurray commented on proposals/3952-intentional-mentions.md
> +significantly increase metadata leakage.
> I am pretty sure you can hide notifications on iOS nowadays: https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_usernotifications_filtering

Fair point! Looks like the request is specifically for end-to-end encrypted apps, and should be fairly straightforward for iOS Matrix clients to request and receive.

This means that room mutes should be applied with push rules at a lower priority than https://github.com/matrix-org/synapse/pull/1131, and then it would be the NSE's responsibility to decrypt and filter out any notifications that are for muted rooms but don't have mentions once the cleartext is known.

2023-02-23 20:17 UTC, sumnerevans commented on proposals/3952-intentional-mentions.md
> +significantly increase metadata leakage.
Even if it's possible, evaluating mentions client-side is still quite expensive, as most encrypted events will not be mentions. We would be expending a lot of energy to decrypt many messages which won't ever notify which would drain battery.

2023-02-24 17:00 UTC, mrredcon commented on proposals/3952-intentional-mentions.md
> +significantly increase metadata leakage.
I can see the wisdom in leaking the least amount of information possible in encrypted rooms, after all, that is the reason there is encryption enabled in the first place.  There should be [warnings in the clients stating that additional bandwidth/energy will be consumed as MSC 1796 recommends under the custom keywords section](https://github.com/matrix-org/matrix-spec-proposals/blob/matthew/msc1796/proposals/1796-e2e-notifications.md#better-handling-of-custom-keyword-notifications), although this should be amended to include Mention notifications as well if they do end up encrypted.  Unfortunately at this time it looks like there will have to be UX and usability sacrifices to keep E2EE actually secure (leaking less message contents/metadata), so there should be an effort to state the consequences of enabling encryption on a group room before letting the user flick the switch (especially since it is irreversible.)

2023-02-28 20:18 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +in order to receive notifications of replies.
7de34e42eb0abce53aec842ff7ed11322d406e02 adds a bunch of information about this.

2023-02-28 20:19 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +(often called a "pill"). Clients should set the `room` value to `true` when making a
Note that 7de34e42eb0abce53aec842ff7ed11322d406e02 adds some info about replies.

2023-02-28 20:29 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +significantly increase metadata leakage.
My overall take on this is that: MSC3952 as it is written today fixes *several* issues with how users get mentioned on Matrix. It should hopefully:

* Reduce noise from unwanted notifications (mostly due to technical gremlins, but also by making it possible for clients to surface *exactly* who will be mentioned by a user).
* Simplifies parsing of messages to see whether it should be a mention.
* Make it easier for less technical users to understand how mentions work (i.e. we won't need to use leetspeak or weird display names to get around bugs).

----

It does *not* (and never attempted **as a primary goal**) to solve any of the following (which this thread seems to have taken a turn towards):

* Attempt to dramatically reduce battery or data usage of mobile devices.
* Attempt to help fill notification holes in gappy-sync situations for non-push clients (i.e. web clients).
* Enable mute-except-for-mentions push rules.

These are all left as "status quo" although I think [some of the ideas in this MSC](https://github.com/matrix-org/matrix-spec-proposals/blob/clokep/intentional-mentions/proposals/3952-intentional-mentions.md#future-extensions) could be leveraged to improve these items I think it is best left to a future MSC which directly targets those problems.

2023-02-28 20:31 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +significantly increase metadata leakage.
Note that I consider this thread resolved, but I'm going to leave it open for now in case folks want to chime in.

2023-02-28 23:29 UTC, turt2live reviewed
I have reviewed this with an intent of figuring out what the next step is for the MSC and how to get there: it does seem fair that the next step is for this to move towards FCP, though there's a couple wider questions I'll be running by the SCT specifically from this review to ensure we have alignment before making major steps towards that stage (there are several small edits/improvements to the proposal's text that can be made in the meantime anyhow). 

I haven't reviewed the competing MSCs personally yet, but will aim to do so later today (particularly to help resolve the p1 conflict I've thrown onto the pile). 

To hopefully make things a bit clear, I've explicitly annotated the comments which I think need further SCT-wide review before this should go for proposed-FCP - please let me know if it's still unclear.

2023-02-28 23:29 UTC, turt2live commented on proposals/3952-intentional-mentions.md
> +  users.
For tracking: these two MSCs have been added to the SCT workflow as a P1 conflict resolution - members should consider the merits of these two approaches in contrast to this MSC when doing a complete review.

MSC3517 is *not* part of the conflict resolution process because it was closed as obsolete, implying it was adopted/melded into this MSC or similar, thus does not need explicit consideration. Members are welcome to take a look in any case though.

Similarly, https://o.librepush.net/aux/matrix_reitools/pill_mention_rules.html has *not* joined the conflict resolution process as it's not currently recorded as an MSC or proto-MSC. If this is unexpected/untrue, please raise it here.

2023-02-28 23:29 UTC, turt2live commented on proposals/3952-intentional-mentions.md
> +room version before use, which would unnecessarily delay usage.
```suggestion
room version before use, which would unnecessarily delay usage. Another MSC
can address this concern, such as in the extensible events series, if
desirable to be gated by a room version for a "clean slate" approach.
```

2023-02-28 23:29 UTC, turt2live commented on proposals/3952-intentional-mentions.md
> +None foreseen.
```suggestion
None not already described.
```

(abuse is a security concern)

2023-02-28 23:29 UTC, turt2live commented on proposals/3952-intentional-mentions.md
> +This depends on two MSCs which, at the time of writing, have not yet been accepted
```suggestion
This depends on the following MSCs which, at the time of writing, have not yet been accepted
```

2023-02-28 23:29 UTC, turt2live commented on proposals/3952-intentional-mentions.md
> +[^1]: It is [defined as](https://spec.matrix.org/v1.5/client-server-api/#mroommessage-msgtypes)
```suggestion
----

[^1]: It is [defined as](https://spec.matrix.org/v1.5/client-server-api/#mroommessage-msgtypes)
```

Just to separate footnotes from dependencies a bit

2023-02-28 23:29 UTC, turt2live commented on proposals/3952-intentional-mentions.md
> +## Potential issues
@matrix-org/spec-core-team - please review this thread.

2023-02-28 23:29 UTC, turt2live commented on proposals/3952-intentional-mentions.md
> +  users.
@matrix-org/spec-core-team - please review this thread.

2023-02-28 23:30 UTC, turt2live commented on proposals/3952-intentional-mentions.md
> +significantly increase metadata leakage.
Having been involved in the discussion around the SCT and an attempt to summarize it out of band, I would agree that @clokep's description of the scope is ideal for this MSC. The review process for an MSC is meant to ensure we aren't making things *worse* rather than try to fix everything in one shot - it's deliberately an iterative process, and this MSC's existing scope fits nicely into such an iteration.

Obviously, other SCT members are welcome to disagree on this conclusion, however in re-reading the SCT's internal discussion on this MSC I don't get the sense that the drawbacks listed (having to spider, battery usage, etc) are categorically worse with this change in the eyes of the SCT. 

Plus, this has product team approval from the folks over at Element, indicating that the overall usability of the feature with known technical defects is sufficiently good enough to ship in a product. Element doesn't get to make the total vote, though: there is an open question around whether the current implementation is suitable for this MSC to make forward progress - please take concerns relating to this to [this thread](https://github.com/matrix-org/matrix-spec-proposals/pull/3952#discussion_r1120888906) on the MSC.

2023-03-01 14:51 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +  users.
Just wanted to confirm that all sounds true. MSC3517 was closed by the author (deferring to this MSC). the `pill_mention_rules` was never written up as an MSC (and the author has no intention of it, I believe). It is discussed in the alternatives section a bit though.

2023-03-01 14:53 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +[^1]: It is [defined as](https://spec.matrix.org/v1.5/client-server-api/#mroommessage-msgtypes)
GitHub automatically adds a horizontal rule when rendering. Will double check this doesn't add 2.

2023-03-01 15:18 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +  (TODO I think there's an issue about this?)
https://github.com/matrix-org/matrix-spec/issues/353#issuecomment-1055809372 -- I'll update the reference to it.

2023-03-01 15:31 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +The full list of mentioned users should be included in the `m.new_content` property.
Yes, although note that there's no way to "cancel" the notification from the initial message. Not sure if that's worth calling out?

2023-03-01 15:40 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +Instead of searching a message's `body` for the user's display name or the localpart
Done in 3461ef8f83ac3a5baa433d3e2c954633c06e47b2.

2023-03-01 15:46 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +### Combating abuse
I think a previous version of this text including information about notifying when mentioning many people. Seems to have gotten removed. Note that this is likely something we *could do today*, this MSC might make it a bit easier though.

2023-03-01 15:55 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +The full list of mentioned users should be included in the `m.new_content` property.
f5dee4986f9760e098ded131390fc9bf5df42504 adds this, it does make me wonder a bit if you add and remove and add and remove the same person. Maybe this is such an edge-case we shouldn't matter though.

2023-03-01 16:00 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +## Potential issues
Twitter provides [an `entities` field](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/tweet) which contains the location into the text content of the Tweet for various things (e.g. links, but also mentions). This model doesn't fit well into Matrix which can have multiple markups, however.

If thi sis just about highlighting *your own* mentions it should be possible to find the corresponding pill (or keyword) and highlight it somehow, but there might not be one. I don't know what you do in this case.

Overall, I suspect this doesn't make it much more difficult to display the mentioning text in a special way since the current mentioning system generally uses a different field than what is displayed to the user (`body` vs. `formatted_body`). Could definitely use some verification, however!

2023-03-01 16:08 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +[^1]: It is [defined as](https://spec.matrix.org/v1.5/client-server-api/#mroommessage-msgtypes)
It adds a second horizontal rule when you do that, I'll add a comment just to separate them a bit.

```suggestion
<!-- Footnotes below: -->

[^1]: It is [defined as](https://spec.matrix.org/v1.5/client-server-api/#mroommessage-msgtypes)
```

2023-03-01 20:19 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +## Potential issues
I think with a little tweaking I can get an Element Web preview up that will work for testing this (it should work completely fine in encrypted rooms, even without server support). I *have* updated the matrix-js-sdk & matrix-react-sdk PRs to match the MSC though, so it seems quite doable implementation wise.

Will get back when there's a thing to test.

2023-03-01 20:41 UTC, turt2live commented on proposals/3952-intentional-mentions.md
> +## Potential issues
It would be around highlighting your own mentions, with the concern being that other clients will slowly (over years) start to be less and less specific in the details they include in the markup for mentions, thus making it more difficult for receiving clients to find the mention. Currently the approach is to look for the pill, but pills are optional and clients could just as easily rely on localpart. For example, in "travis: have you tried Travis CI?" it's easy for humans to see the mention but the parsing code suddenly becomes more complex to handle natural language.

2023-03-10 19:29 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +  [fallback replies](https://spec.matrix.org/v1.5/client-server-api/#fallbacks-for-rich-replies).
This is particular bad if a user without the power to issue `@room` is replied to by someone who *can*, which will cause an `@room` mention.

2023-03-13 18:08 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +## Potential issues
> Note that I am actively working on that PR so I'll try not to break it, but it might explode. 😄

I think I've gotten most of the bugs out of this PR now (and wrote some tests for it), so it should now be reasonable to test against.

2023-03-21 05:07 UTC, turt2live approved these changes
let's do it

2023-03-21 05:07 UTC, turt2live commented on proposals/3952-intentional-mentions.md
> +## Potential issues
We can probably course correct this as needed - resolving for now.

2023-03-21 05:07 UTC, turt2live commented on proposals/3952-intentional-mentions.md
> +## Potential issues
(leaving this thread open, but moving ahead with FCP anyways - SCT members who prefer to have more implementation first should `@mscbot concern More implementation`)

2023-03-21 05:07 UTC, turt2live commented on proposals/3952-intentional-mentions.md
> +  users.
Due to lack of comment, I'm assuming we intend to go ahead with this MSC over the alternatives. SCT members should raise concerns if they disagree.

(leaving this thread open for the moment)

2023-03-21 05:07 UTC, turt2live commented on proposals/3952-intentional-mentions.md
> +into the specification:
```suggestion
This depends on the following MSCs:
```

2023-03-21 05:07 UTC, turt2live commented
@mscbot fcp merge

2023-03-21 11:17 UTC, dbkr commented on proposals/3952-intentional-mentions.md
> +  * A user without the power level to send `@room` can abuse this by includin
```suggestion
  * A user without the power level to send `@room` can abuse this by including
```

2023-03-21 11:31 UTC, dbkr commented on proposals/3952-intentional-mentions.md
> +the edit is significant or if additional users are mentioned.
Non blocking, but you could clarify between the `m.mentions` in the event itself and the one in the `m.new_content` block as it took me a couple of reads to realise they were two different things.

2023-03-21 11:45 UTC, dbkr commented on proposals/3952-intentional-mentions.md
> +to give users more control over who can generate notifications.
A bit of discussion on norm-setting would be interesting. That is, do we still expect clients to highlight the user's pill in a message red? What about in a message that includes their pill but doesn't mention them? Would we still expect user pills to be part of mention messages or do we see them being phased out in favour of just having the out-of-line intentional mentions ("x mentioned you in this event") that you discuss?

2023-03-21 12:19 UTC, ShadowJonathan commented on proposals/3952-intentional-mentions.md
> +to give users more control over who can generate notifications.
For the first part, to borrow the paradigm from discord; The @-pills would still be there, but they just wouldn't be highlighted, meaning they only exist to refer readers to the mentioned, but not to refer the mentioned to the message.

For the second, especially about "do we see them being phased out in favour of just having the out-of-line intentional mentions", I personally don't see this happening, as its still useful to refer users in messages, similar to "mentioning by name" works. Ultimately, I think that'll be up to social conventions, which means that changing between no pill-mentions (i.e. the "CC-like list" that the Potential for Abuse section mentions) or only-pill mentions is up to individual/group/cultural preference, meaning clients would have to deal with a mix of pill-mentions and non-pill-mentions in any message, it can be seen as a feature.

2023-03-21 13:16 UTC, dkasak commented on proposals/3952-intentional-mentions.md
> +to give users more control over who can generate notifications.
IMO, the out-of-line intentional ("no-pill") mentions still need to be rendered client-side somehow, otherwise the whole thing is going to become really confusing.

> That is, do we still expect clients to highlight the user's pill in a message red?

I would expect clients to do this *if and only if* the message contains an out-of-line intentional mention for the same user. Essentially, the presence of an out-of-line mention for a given user should activate special rendering of pills for that user. In cases where there is no out-of-line mention, IMO you shouldn't even be able to pillify, that is the pill would become ordinary text. Conversely, when there *is* an out-of-line mention but no pill, the client should decorate the entire message with something like "x thought you'd be interested in this message" or something along those lines.

Clients might want to simplify and not expose this last case to the user, requiring the user to produce a pill in order to even send out an out-of-line intentional mention. (Of course, you'd still be able to produce such events manually).

2023-03-21 13:21 UTC, ShadowJonathan commented on proposals/3952-intentional-mentions.md
> +to give users more control over who can generate notifications.
> IMO you shouldn't even be able to pillify, that is the pill would become ordinary text.

there might be a reason why the original poster would have chosen to turn a person's mention into a pill, instead of "just plain text", maybe to point the other user(s) in the chat to "this specific user" instead of "this person we know by this name", which'd they have to lookup and search (in the room's member list), or simply know someone by that alias beforehand, to know who the OP is talking about.

> Clients might want to simplify and not expose this last case to the user, requiring the user to produce a pill in order to even send out an out-of-line intentional mention.

Agreed, I see this as falling in line with matrix's client simplicity preference/option, selectively pruning some advanced options to simplify the interface for their users.

2023-03-21 13:35 UTC, dkasak commented on proposals/3952-intentional-mentions.md
> +to give users more control over who can generate notifications.
> there might be a reason why the original poster would have chosen to turn a person's mention into a pill, instead of "just plain text", maybe to point the other user(s) in the chat to "this specific user" instead of "this person we know by this name", which'd they have to lookup and search (in the room's member list), or simply know someone by that alias beforehand, to know who the OP is talking about.

That's a fair (and convincing) point which I didn't think of.

Though one related thing that I would personally find annoying is if someone mentioned me in this way but my client provided no ability to notify me about it.

2023-03-21 16:11 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +The existing push rules for mentions are deprecated and replaced with rules
The end goal is that the deprecated ones will no longer exist.

There's an intermediate state (describe in more detail lower in ths MSC) where both exist, but the deprecated ones are disabled if the `m.mentions` property exists.

Any suggestion of how to reword this?

2023-03-21 16:12 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +  [they might not be mentioned unless the historical display name](https://github.com/matrix-org/matrix-spec/issues/353#issuecomment-1055809372)
Maybe it was just a bug, I'm not sure. I think there's enough evidence regardless that this MSC is a change! We can remove it -- but I think the point still stands that evaluating these rules is a bit complicated due to historical state.

2023-03-21 17:59 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +to give users more control over who can generate notifications.
Hopefully b9756431eecd2edebe3d4b71da3b0d703a115c7d clarifies this a bit.

2023-03-21 18:10 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +the edit is significant or if additional users are mentioned.
I called it out in 4147590646cfd217f9d318a79c2cf85dd2b4afee that there are two copies. I think this is much clearer now!

2023-03-21 20:33 UTC, uhoreg approved these changes

2023-03-21 20:33 UTC, uhoreg commented on proposals/3952-intentional-mentions.md
> +```
If I'm understanding this correctly, it may be worth calling out that:

- If a client highlight a message visually (e.g. by colouring it red), then it should look at the `m.mentions` under `m.new_content` for edited messages.  Otherwise, in the example above, Alice would not see the message as red, even though the intent was for her to be mentioned.
- If a client uses some sort of notification sound, it should look at the `m.mentions` directly under `content` and not ding for Alice (if it already dinged for the original message).

2023-03-21 20:33 UTC, uhoreg commented on proposals/3952-intentional-mentions.md
> +be quite difficult as it is unclear if the mentioned user has already receive
```suggestion
user's mention is removed while [editing events](#impact-on-edits). This could
be quite difficult as it is unclear if the mentioned user has already received
```

2023-03-21 20:33 UTC, uhoreg commented on proposals/3952-intentional-mentions.md
> +* [MSC3966](https://github.com/matrix-org/matrix-spec-proposals/pull/3966): `event_property_contains` push rule condition
For reference, these three MSCs have already been accepted.

2023-03-21 21:08 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +
You mean going from Matrix -> Bridge? Correct. I can reword this a bit to be clearer. (Although from Bridge -> Matrix we shouldn't need to do that anymore.)

2023-03-21 21:09 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +* [MSC3966](https://github.com/matrix-org/matrix-spec-proposals/pull/3966): `event_property_contains` push rule condition
Is it clearer if I just remove them now as they've all been accepted?

2023-03-22 12:58 UTC, uhoreg commented on proposals/3952-intentional-mentions.md
> +* [MSC3966](https://github.com/matrix-org/matrix-spec-proposals/pull/3966): `event_property_contains` push rule condition
No, I think it's better to keep it around for historical documentation.  I was just leaving a note for the sake of other reviewers to indicate that these MSCs aren't blocking this one.

2023-03-22 14:54 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +```
It is probably worth calling out that your second bullet point is really just "process push rules on the event as normal".

2023-03-22 15:02 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +```
1d1c8f3159134248cc62e111ad9be9b09a403560 clarifies this a bit.

This does give an odd experience if you were mentioned on a previous edit and then removed. The message wouldn't be highlighted, but the user may be confused at why they got a notification. I think this is a separate problem to solve honestly.

2023-03-27 16:33 UTC, giomfo commented on proposals/3952-intentional-mentions.md
> +significantly increase metadata leakage.
@dkasak @uhoreg @turt2live  In order to reduce the bandwidth/CPU/time/battery consumption client side, don't you think acceptable to add a unencrypted boolean value to the encrypted event to let the server know there are some mentions inside or not? 
The server will then be able to notify the client only for the events with mentions (without knowing who are actually mentioned). This will help us to restore on mobile the support of the "mention only" notification mode, by limiting the number of notifications received on mobile.

If the end user enabled notifications on some keywords, the server will have to send all events in encrypted rooms, but custom keywords are fairly rare.

2023-03-27 17:18 UTC, turt2live commented on proposals/3952-intentional-mentions.md
> +significantly increase metadata leakage.
The battery life considerations appear to have already been resolved? As far as the SCT is concerned though, battery life is not a strong enough reason to support this information being unencrypted (unless of course there's no workaround and it ends up using a significant amount of battery, in which case we can reconsider).

2023-03-28 17:18 UTC, richvdh commented on proposals/3952-intentional-mentions.md
> +Edited events end up with two `m.mentions` properties:
the *edited* event doesn't get a second `m.mention` property? That's in the replacement, not the original event (either before or after [applying `m.new_content`](https://spec.matrix.org/v1.6/client-server-api/#applying-mnew_content)). I think you mean:

```suggestion
Replacement events may have `m.mentions` properties in two locations:
```

2023-03-28 17:38 UTC, giomfo commented on proposals/3952-intentional-mentions.md
> +significantly increase metadata leakage.
FYI I discussed with @clokep, you may ignore my remark for this MSC. We should handle it in another MSC

2023-04-04 17:49 UTC, dbkr commented on proposals/3952-intentional-mentions.md
> +to give users more control over who can generate notifications.
Thanks, I think that does help.

On the discussion, I'm afraid I'm really only interested in the text that goes into the MSC rather than what people think about it. I would prefer to keep discussion to what we want the MSC to say.

2023-04-18 14:10 UTC, giomfo commented on proposals/3952-intentional-mentions.md
> +### Muted except for mentions push rules
@erikjohnston FYI clokep prepared https://github.com/matrix-org/matrix-spec-proposals/pull/3996

2023-04-19 21:05 UTC, turt2live commented
@dkasak please take a second look at this (with an aim of hopefully changing your review from Requested Changes to Approved).

2023-04-20 16:40 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +### Muted except for mentions push rules
147ff7803ca927e8ff132a34125ac18c3766a1e7 attempts to clarify.

2023-04-20 17:53 UTC, anoadragon453 approved these changes
Mostly just clarification comments, whereas the logic seems sound.

I'd like to resolve X before sending this for FCP however.

2023-04-20 17:53 UTC, anoadragon453 commented on proposals/3952-intentional-mentions.md
> +  mentioned users in any version of the event.
I wrote a comment about what would happen if a user mention was removed in the edit... before reading on :)

```suggestion
* One inside the `m.new_content` property, which should contain the full list of
  mentioned users in any version of the event, unless a mention is removed
  (see below).
```

2023-04-20 17:53 UTC, anoadragon453 commented on proposals/3952-intentional-mentions.md
> +Mentions can also be removed as part of an edit. In this case top-level `m.mentions`
```suggestion
Mentions can also be removed as part of an edit. In this case, the top-level `m.mentions`
```

2023-04-20 17:53 UTC, anoadragon453 commented on proposals/3952-intentional-mentions.md
> +could setup a push rule for the `content.m\\.new_content.m\\.mentions` property
likewise here.

```suggestion
could setup a push rule for the `content.m\.new_content.m\.mentions` property
```

2023-04-20 17:53 UTC, anoadragon453 commented on proposals/3952-intentional-mentions.md
> +For bridged protocols that do not have this mechanism than the bridge will only
```suggestion
For bridged protocols that do not have this mechanism, the bridge will only
```

2023-04-20 17:53 UTC, anoadragon453 commented on proposals/3952-intentional-mentions.md
> +Previous version of this proposal (and the alternative [MSC1796](https://github.com/matrix-org/matrix-spec-proposals/pull/1796))
```suggestion
A previous version of this proposal (and the alternative [MSC1796](https://github.com/matrix-org/matrix-spec-proposals/pull/1796))
```

2023-04-20 17:53 UTC, anoadragon453 commented on proposals/3952-intentional-mentions.md
> +  users.
IMO, this proposal solves the most edge cases, and introduces more beneficial primitives (`m.mentions)`, over the solutions proposed in MSC3517 and https://o.librepush.net/aux/matrix_reitools/pill_mention_rules.html.

2023-04-20 18:17 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +    "body": "Helo Alice!",
This is the typo being fixed below. 😄

2023-04-20 18:17 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +    "body": "Helo Alice!",
Or maybe it used to be and I changed the example?

2023-04-20 18:36 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +        "@bob:example.org",
> I'd expect the same behaviour from Matrix clients, so it may be worth having the example reflect that behaviour (unless you disagree?).

I'm attempting to *not* change today's behavior (compared to the reply-fallbacks we have now) when sending replies.

> Otherwise, I see that the point of this section is to communicate that clients *could* include whichever users they would like. I still worry that clients will just copy the example in the spec.

Yes clients can choose to do different things here, that might appear flakey if clients do different things though! I think ideally it would be consistent across clients?

2023-04-20 18:53 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +            "key": "content.m\\.mentions.user_ids",
We [talked about this in #matrix-spec](https://matrix.to/#/!NasysSDfxKxZBzJJoE:matrix.org/$WJgu_9SclbeiRCc8QKVU9PABZqwQ9YXWxSZzL7JJwRo?via=matrix.org&via=libera.chat&via=element.io), see 811c0df5ecbc65333ae99ec3f825ce1175d9c885 for the result.

tl;dr this is JSON, so the double backslash is correct (but actually represents a single character -- a backslash).

2023-04-20 19:11 UTC, anoadragon453 commented on proposals/3952-intentional-mentions.md
> +        "@bob:example.org",
> that might appear flakey if clients do different things though

Do you mean during the transition period? Clients are already going to be doing different things during that period anyways (some sending unintended mentions, whereas others are not).

> I think ideally it would be consistent across clients?

Indeed! Though I fear some clients may copy the example and mention other users during a reply, whereas other clients would choose not to do so.

I only raise this point as I've seen past cases of clients blindly using fields from examples in the spec *which aren't actually specced*. Those fields originally being c/p'd from a client implementation in the wild without being properly vetted.

> I'm attempting to not change today's behavior (compared to the reply-fallbacks we have now) when sending replies.

I see that - but why not? We're fixing so many other behaviour around mentions in this MSC already.

2023-04-21 15:48 UTC, anoadragon453 commented on proposals/3952-intentional-mentions.md
> +        "@bob:example.org",
@clokep and I talked this over in DMs, which has resulted in https://github.com/matrix-org/matrix-spec-proposals/pull/3952/commits/63592e7f63a2f007af91bf6739463a40a3c9c791. Which I'm happy with as it clarifies that different use cases ought to consider desired semantics for this behaviour.

2023-04-26 12:48 UTC, KitsuneRal reviewed
One consideration below, next to a suggestion of stronger language - not serious enough for an FCP-breaking concern though.

2023-04-26 15:09 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +user *why* they were mentioned). This behavior is unchanged.
> I wonder if we should explicitly discourage receiving clients from pillifying display names of mentioned users. I admit it's a somewhat corner case because well-behaved sending clients are supposed to use MXIDs and not display names in the message body; it's more to protect overzealous client authors from a pitfall.

I thought the [current spec](https://spec.matrix.org/v1.6/client-server-api/#user-and-room-mentions) was a bit clearer on this then it is, but yeah the intention is that only matrix.to links should be pillified on receiving. (I don't think this MSC is really changing that though FTR.)

2023-04-26 16:42 UTC, MTRNord commented on proposals/3952-intentional-mentions.md
> +user *why* they were mentioned). This behavior is unchanged.
I admit I didn't read the msc much but I assume you also mean pills for matrix: URLs and not just matrix.to? Feels like a step back if only matrix.to would be pillified (apart from it being a centralised service still)

2023-04-26 17:12 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +user *why* they were mentioned). This behavior is unchanged.
> I admit I didn't read the msc much but I assume you also mean pills for matrix: URLs and not just matrix.to? Feels like a step back if only matrix.to would be pillified (apart from it being a centralised service still)

The spec currently only defines them for matrix.to IIRC, I suspect this was an oversight when matrix: URIs were accept though?

This MSC makes *no changes about how/when pillifying is done*. It does say that if you pillify than the user should be mentioned explicitly in the event metadata.

2023-04-26 18:29 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +in the new event's `m.mentions` property. The `room` property should not be copied over.
I don't know the procedure of whether to commit this or not now that this has completed FCP. I'm fine with the change to the text though.

@turt2live do you have any thoughts?

2023-04-26 22:15 UTC, uhoreg commented on proposals/3952-intentional-mentions.md
> +in the new event's `m.mentions` property. The `room` property should not be copied over.
The comment was made before FCP was over, and seems like a minor enough change.  So if you agree with it, I'd say that it's fine to commit it.

2023-04-26 23:22 UTC, dkasak commented on proposals/3952-intentional-mentions.md
> +user *why* they were mentioned). This behavior is unchanged.
> The spec currently only defines them for matrix.to IIRC, I suspect this was an oversight when matrix: URIs were accept though?

It seems to me that this is not even the case. The spec [talks about including `Matrix URIs`](https://spec.matrix.org/v1.5/client-server-api/#user-and-room-mentions) in the event to make a mention, which it defines as either a matrix.to link or a `matrix:` URI. The example given uses a matrix.to anchor, but it is just an example.

2023-04-26 23:30 UTC, dkasak approved these changes

2023-04-27 12:27 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +user *why* they were mentioned). This behavior is unchanged.
Ah, good-catch. The [Matrix URI](https://spec.matrix.org/v1.5/appendices/#uris) section seems to talk about both!

2023-04-27 12:27 UTC, clokep commented on proposals/3952-intentional-mentions.md
> +user *why* they were mentioned). This behavior is unchanged.
Anyway -- I don't think we're making any particular change here, so I'm going to resolve this.

2023-04-27 13:25 UTC, merged

2023-04-27 13:36 UTC, uhoreg commented
clokep has said that he is planning on writing the spec PR for this

2023-05-09 13:26 UTC, clokep commented
Spec PR: matrix-org/matrix-spec#1508

2023-05-17 15:19 UTC, turt2live commented
Merged 🎉