Clarify how to make use of unstable prefixes in your MSC
matrix-org/matrix-spec-proposals pull request #4024
Opened 2023-06-01 15:00 UTC by anoadragon453

This PR adds a section to the simple spec guide that gives some background to MSC authors on how to effectively make use of unstable and stable prefixes.

2023-06-01 15:04 UTC, ShadowJonathan approved these changes

2023-06-01 17:02 UTC, clokep commented on README.md
> +stable prefixes for an MSC with yet another `unstable_features` flag:
Isn't it really just about how quickly you want it rolled out though? I think *any* MSC *could* use it for clients to know earlier than new spec release time to use it.

2023-06-01 17:05 UTC, clokep commented on README.md
> +also implemented support. Typically, this is handled by the MSC defining an
I found this too abstract: I was left wondering what an "implementation types" is?

```suggestion
It is common when implementing support for an MSC that a client may wish to check
if the homeserver it is communicating with supports an MSC.
Typically, this is handled by the MSC defining an
```

I guess theroetically the same thing could be done for homeserver to {homeserver, identity servers, push servers}, but those (mostly) don't define a way to check this.

2023-06-06 02:25 UTC, turt2live reviewed
generally lgtm with the verbiage changes noted already

2023-06-06 02:25 UTC, turt2live commented on README.md
> +an MSC is not yet accepted. For instance, an MSC can propose an a `m.space`
> propose an a

should be "propose to add a" or something?

2023-06-06 02:25 UTC, turt2live commented on README.md
> +respectively.
might be good to mention here that you can invent your own, but that we also don't mind people littering the `org.matrix.msc*` namespace.

2023-06-06 02:25 UTC, turt2live commented on README.md
> +According to the spec process, once an MSC has been accepted, implementations
```suggestion
According to the spec process, once an MSC has been accepted (passed a `merge` FCP), implementations
```

... or we should mention this somewhere in the doc if we don't already

2023-06-06 02:25 UTC, turt2live commented on README.md
> +where this poses a problem is when an MSC proposes new event types or fields.
are event types the common case? I thought it was endpoints, generally speaking. Clients prefer to just know rather than rely on 404-style semantics.

There is a case where the event types mean something to the server, but aren't affected by the room version, though this is theoretically rare - an example being threads (which was nothing to do with event types...).

2023-06-06 17:51 UTC, anoadragon453 commented on README.md
> +respectively.
Well, we don't want them to start encroaching on `org.matrix.msc<not their MSC number>` ideally, right?

2023-06-06 18:49 UTC, turt2live commented on README.md
> +respectively.
it's more than people can use `com.example.feature` instead of `org.matrix.*` if they want to.

2023-06-06 19:42 UTC, clokep commented on README.md
> +where this poses a problem is when an MSC proposes new event types or fields.
I suspect it should be event properties, not types? Anything that gets persisted into the DAG. I've seen this be an annoying issue for event types (polls, etc.); relation types (threads is the only example I know of since the others always used stable); or event properties (intentional mentions, etc).

2023-06-16 17:37 UTC, anoadragon453 commented on README.md
> +where this poses a problem is when an MSC proposes new event types or fields.
I've rewritten this in 681173c4, let me know how it looks!

2023-06-16 17:37 UTC, anoadragon453 commented on README.md
> +respectively.
Changed in 3eba07f420a5cae1c6ea331ffaac9eda0813b792.

2023-06-16 19:24 UTC, clokep commented on README.md
> +stable prefixes for an MSC with yet another `unstable_features` flag:
Seems reasonable to me!

2023-06-20 14:28 UTC, richvdh requested changes

2023-06-20 14:28 UTC, richvdh commented on README.md
> +implementations of your MSC to exist in the wild before your MSC is accepted.
```suggestion
Note: not all MSCs need to make use of unstable prefixes. They are only needed if
implementations of your MSC need to exist in the wild before your MSC is accepted,
*and* the MSC defines new endpoints, field names, etc.
```

2023-06-20 14:28 UTC, richvdh commented on README.md
> +#### Stable and unstable prefixes
```suggestion
####  Unstable prefixes
```

2023-06-20 14:28 UTC, richvdh commented on README.md
> +meaning, usually udner an "Unstable prefixes" header in your MSC.
```suggestion
meaning, usually under an "Unstable prefixes" header in your MSC.
```

2023-06-20 14:28 UTC, richvdh commented on README.md
> +prefixes, such as `com.example.*` (e.g. `com.example.space`).
This stuff applies to *all* identifiers, not just those with an identifiable "prefix". (Consider, in particular, properties within event bodies or other JSON structures).

So, I don't really think we should be talking about "stable prefixes" at all.  Instead, we can talk about "stable identifiers":

```suggestion
"Unstable prefixes" are the namespaces which are used by implementations while
an MSC is not yet accepted.

For instance, an MSC might propose that a `m.space`
event type or an `/_matrix/client/v1/account/whoami` endpoint should exist.
However, implementations cannot use these *stable* identifiers until the MSC
has been accepted, as the underlying design may change at any time; the design is
*unstable*.

Instead, an MSC can define a namespace such as `org.matrix.msc1234` (using the real
MSC number once known) which is added to the stable identifier, allowing for
breaking changes between edits of the MSC itself, and preventing clashes with other
MSCs that might attempt to add the same stable identifiers. 

For the above examples, this would mean using `org.matrix.msc1234.space` and
`/_matrix/client/unstable/org.matrix.msc1234/account/whoami`. It is also fine to
use more traditional forms of namespace prefixes, such as `com.example.*` (e.g. `com.example.space`).
```

Likewise, the other references to "stable prefixes" below need rephrasing.

2023-06-20 14:28 UTC, richvdh commented on README.md
> +It is common when implementing support for an MSC that a client may wish to check
```suggestion
#### Unstable feature flags

It is common when implementing support for an MSC that a client may wish to check
```

2023-07-04 12:49 UTC, richvdh approved these changes
looks great!

2023-07-04 12:49 UTC, richvdh commented on README.md
> +With a value of `true` indicating that the feature is supported, and `false`
```suggestion
... with a value of `true` indicating that the feature is supported, and `false`
```

2023-07-07 10:11 UTC, merged