MSC4037: Thread root is not in the thread
matrix-org/matrix-spec-proposals pull request #4037
Opened 2023-07-13 15:43 UTC by andybalaam

[Rendered](https://github.com/matrix-org/matrix-spec-proposals/blob/andybalaam/thread-root-is-not-in-thread/proposals/4037-thread-root-is-not-in-thread.md)

Implementations:

* [Synapse](https://github.com/matrix-org/synapse/blob/v1.87.0/synapse/rest/client/receipts.py#L116-L154) has the behaviour specified in this proposal [^1]

[^1]: although it is slightly inconsistent in that it rejects receipts for thread roots that claim to be in the thread, but it accepts receipts for reactions/edits to thread roots that claim to be in the thread, although they do not affect the notification count in the thread.

* [matrix-js-sdk](https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/client.ts#L5004) was recently fixed to match the behaviour required by this proposal, as a bug fix for stuck notifications bugs resulting from inconsistency between Synapse and Element Web.

2023-07-14 08:55 UTC, jplatte commented on proposals/4037-thread-root-is-not-in-thread.md
> +[adoptingthe behaviour recommended by this proposal](https://github.com/matrix-org/matrix-js-sdk/pull/3600).
```suggestion
[adopting the behaviour recommended by this proposal](https://github.com/matrix-org/matrix-js-sdk/pull/3600).
```

2023-07-17 11:31 UTC, clokep commented on proposals/4037-thread-root-is-not-in-thread.md
> +the thread, and accepts requests to mark it as read in the main timeline.
Looking at the code I *think* it was intended to accept either, but I would need to do more testing to be sure about that. (And being not ambiguous is good. 😄 )

2023-07-17 11:32 UTC, clokep commented on proposals/4037-thread-root-is-not-in-thread.md
> +implicitly _excludes_ those messages from being in the `main` thread.
I don't think it was meant to exclude this from being in the main *timeline* as the main *timeline* is not a *thread*.

2023-07-17 11:33 UTC, clokep commented on proposals/4037-thread-root-is-not-in-thread.md
> +## Proposal
It is implied but the changes, but just to call it out -- this also means events related to the thread root are no longer part of the thread.

2023-07-17 12:34 UTC, andybalaam commented on proposals/4037-thread-root-is-not-in-thread.md
> +implicitly _excludes_ those messages from being in the `main` thread.
But in terms of receipts, the spec talks about the main timeline as a thread. So I think it accidentally does exclude them. Which is clearly not intended in my opinion.

2023-07-17 12:35 UTC, andybalaam commented on proposals/4037-thread-root-is-not-in-thread.md
> +## Proposal
I thought I said this somewhere, but will add it here, thanks.

2023-07-17 12:38 UTC, andybalaam commented on proposals/4037-thread-root-is-not-in-thread.md
> +## Proposal
Note add here: 651824f5

2023-07-17 12:41 UTC, clokep commented on proposals/4037-thread-root-is-not-in-thread.md
> +implicitly _excludes_ those messages from being in the `main` thread.
I don't think it was intentional from the design. 👍

2023-07-17 15:20 UTC, turt2live requested changes

2023-07-17 15:20 UTC, turt2live commented on proposals/4037-thread-root-is-not-in-thread.md
> +[11.6.2.2 Threaded read receipts](https://spec.matrix.org/unstable/client-server-api/#threaded-read-receipts)
Please link to a versioned edition of the spec, not unstable. Ie: v1.7

2023-07-17 15:20 UTC, turt2live commented on proposals/4037-thread-root-is-not-in-thread.md
> +branching from it.
The proposal later goes into detail about how the implementation differs from the specification slightly, which has me concerned the spec is just wrong compared to the MSCs which lead to it. Normally the SCT aims to figure out whether the implementation or spec is wrong before opening an MSC, but we're already here, so: can we get words relating to the research of the threads MSCs to (dis)prove the spec being wrong? 

If it turns out that the spec is just outright wrong due to clear wording in the MSCs, we can bypass the FCP process and go to spec clarification, but will depend on the MSC research.

2023-07-17 15:20 UTC, turt2live commented on proposals/4037-thread-root-is-not-in-thread.md
> +In practice, Synapse ignores any request to mark the thread root as read within
permalink to code please :)

2023-07-17 15:20 UTC, turt2live commented on proposals/4037-thread-root-is-not-in-thread.md
> +related events such as edits) to be outside the main timeline.
This needs a why - there's an argument for root messages to be in the main timeline, but from an API clarity perspective it does make sense to consider a reaction "in" the thread. The arguments made above don't appear to hold for reactions, etc.

2023-07-18 09:10 UTC, andybalaam commented on proposals/4037-thread-root-is-not-in-thread.md
> +In practice, Synapse ignores any request to mark the thread root as read within
Thanks, fixed in 62d4f51c

2023-07-18 09:21 UTC, andybalaam commented on proposals/4037-thread-root-is-not-in-thread.md
> +related events such as edits) to be outside the main timeline.
I added an argument in cb06a85c - let me know whether it's convincing. If it's not, please DM me to help me understand: I find it almost conclusively convincing ;-)

2023-07-18 09:44 UTC, andybalaam commented on proposals/4037-thread-root-is-not-in-thread.md
> +branching from it.
The relevant MSC is [MSC3771: Read receipts for threads](https://github.com/matrix-org/matrix-spec-proposals/pull/3771)

Here is some wording:

> notifications generated from events with a thread relation matching the receipt’s thread ID prior to and including that event which are MUST be marked as read

Notably it only mentions things "**with a thread relation**", so it appears to match the wording of this proposal.

On the other hand, further experimentation with Synapse shows that it does allow and process receipts for edits to thread roots on BOTH the main timeline AND the thread, so Synapse does not fully align with the behaviour we propose.

2023-07-18 09:45 UTC, andybalaam commented on proposals/4037-thread-root-is-not-in-thread.md
> +branching from it.
Should I add this research to the MSC itself, or is reporting it here the right thing to do?

2023-07-18 10:54 UTC, jplatte commented on proposals/4037-thread-root-is-not-in-thread.md
> +> in the main timline.
```suggestion
> in the main timeline.
```

2023-07-18 17:41 UTC, turt2live commented on proposals/4037-thread-root-is-not-in-thread.md
> +branching from it.
It should be in the MSC for now as we're in the information gathering stage - next step is to take all that information and figure out how we got here, and what the next steps are to fix it.

2023-07-19 14:21 UTC, andybalaam commented on proposals/4037-thread-root-is-not-in-thread.md
> +branching from it.
Added in 61765169.

> On the other hand, further experimentation with Synapse shows that it does allow and process receipts for edits to thread roots on BOTH the main timeline AND the thread, so Synapse does not fully align with the behaviour we propose

Note: the above was wrong, and the correct situation is now reflected in the MSC text. Synapse's behaviour basically matches this proposal.

2023-08-08 20:37 UTC, turt2live reviewed
see contained comment thread

2023-08-08 20:37 UTC, turt2live commented on proposals/4037-thread-root-is-not-in-thread.md
> +> * It has a `rel_type` of `m.thread`, or it has an ancestor event with this
Spec PR author: do not bring "ancestor" into the spec, please. We already have terminology to describe parent relationships.

2023-08-08 20:37 UTC, turt2live commented on proposals/4037-thread-root-is-not-in-thread.md
> +[adopting the behaviour recommended by this proposal](https://github.com/matrix-org/matrix-js-sdk/pull/3600).
[MSC3771](https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/3771-read-receipts-for-threads.md) (merged) originally introduced the threaded receipts behaviour into the spec in v1.4, but did not describe what actually constitutes what is "in a thread". Though, the implied wording of MSC3771 does *not* include the thread root in the thread for purposes of notifications. This is further backed up by Synapse being the primary cited implementation proof for MSC3771, which is backed up by this proposal's text in the above paragraph.

As mentioned elsewhere, usually when disagreements between implementation and specification happen we (the SCT) prefer to handle it via another medium, however since an MSC was already created we are using it as the coordination point. 

Given the above, and the references this MSC provides (including a bug fix for Element Web via the js-sdk), I'm confident that this would be best handled as a regular specification bug/clarification issue rather than as an MSC, given the spec is incorrect for not matching the original MSC3771 text/intent. 

I believe it's still valuable for the spec to reference the root being "in a thread" for representation purposes, however for notifications and specifically read receipts I strongly agree that it doesn't make sense to count the thread root as needing a dedicated read receipt. This is ratified by MSC3771 and clarified in depth within this MSC.

@andybalaam as author for this MSC, I'd ask that you take on the spec clarification work via a regular spec PR and close this MSC. @matrix-org/spec-core-team dissenting opinions to mine are welcome, up to and including the point where a spec PR is up for review on this. 

I don't think sending this through FCP would uncover much else in terms of opinions, and sending it through FCP to close it feels like excessive process burden.

2023-08-14 08:54 UTC, andybalaam commented on proposals/4037-thread-root-is-not-in-thread.md
> +[adopting the behaviour recommended by this proposal](https://github.com/matrix-org/matrix-js-sdk/pull/3600).
Great, thank you. I will work on this.

2023-11-22 11:45 UTC, andybalaam commented
Replaced by spec PR https://github.com/matrix-org/matrix-spec/pull/1677

2023-11-22 11:45 UTC, closed without merging

2023-11-22 11:45 UTC, andybalaam commented on proposals/4037-thread-root-is-not-in-thread.md
> +[adopting the behaviour recommended by this proposal](https://github.com/matrix-org/matrix-js-sdk/pull/3600).
The spec PR is at https://github.com/matrix-org/matrix-spec/pull/1677