Tweaks to the QR code login crypto
matrix-org/matrix-spec-proposals pull request #4129
Opened 2024-04-11 13:34 UTC by dkasak

- Derive separate encryption keys and nonces for the two sides of the secure channel
- Mandate that the new device commits to a particular identity key (by setting the device ID to the public part) and proves ownership of it
- Spell out HKDF parameters in text too
- Misc style fixes

2024-04-11 14:36 UTC, poljar commented on proposals/4108-oidc-qr-login.md
> +- `MATRIX_QR_CODE_LOGIN_ENCKEY_S|Gp|Sp` as the info the info, where Gp and Sp stand for the generating
```suggestion
- `MATRIX_QR_CODE_LOGIN_ENCKEY_S|Gp|Sp` as the info, where Gp and Sp stand for the generating
```

2024-04-11 14:45 UTC, poljar requested changes
Left some nits.

2024-04-11 14:45 UTC, poljar commented on proposals/4108-oidc-qr-login.md
> +- `MATRIX_QR_CODE_LOGIN_ENCKEY_G|Gp|Sp` as the info the info, where Gp and Sp stand for the generating
```suggestion
- `MATRIX_QR_CODE_LOGIN_ENCKEY_G|Gp|Sp` as the info, where Gp and Sp stand for the generating
```

2024-04-11 14:45 UTC, poljar commented on proposals/4108-oidc-qr-login.md
> +EncKey_G := HKDF_SHA256(SH, "MATRIX_QR_CODE_LOGIN_ENCKEY_S|" || Gp || "|" || Sp, salt=0, size=32)
I think that this will  produce the same thing as `EncKey_S`.

```suggestion
EncKey_G := HKDF_SHA256(SH, "MATRIX_QR_CODE_LOGIN_ENCKEY_G|" || Gp || "|" || Sp, salt=0, size=32)
```

2024-04-11 14:45 UTC, poljar commented on proposals/4108-oidc-qr-login.md
> +The new device then proves it controls the public key to which it previously committed. It does this by doing an ECDH
Not sure if that's an error, but I would expect that it proves that it controls the private key.

```suggestion
The new device then proves it controls the private key to which it previously committed. It does this by doing an ECDH
```

2024-04-11 14:45 UTC, poljar commented on proposals/4108-oidc-qr-login.md
> +Proof := ChaCha20Poly1305_Encrypt(EncKey_Proof, NonceBytes, "MATRIX_QR_CODE_PROOF_OF_POSSESSION")
Hmm, I would have expected that a MAC would be used for this. Any reasoning on why it wasn't?

2024-04-11 14:56 UTC, dkasak commented on proposals/4108-oidc-qr-login.md
> +- `MATRIX_QR_CODE_LOGIN_ENCKEY_S|Gp|Sp` as the info the info, where Gp and Sp stand for the generating
Thanks, already committed.

2024-04-11 14:56 UTC, dkasak commented on proposals/4108-oidc-qr-login.md
> +- `MATRIX_QR_CODE_LOGIN_ENCKEY_G|Gp|Sp` as the info the info, where Gp and Sp stand for the generating
As above, thanks again.

2024-04-11 14:58 UTC, dkasak commented on proposals/4108-oidc-qr-login.md
> +Proof := ChaCha20Poly1305_Encrypt(EncKey_Proof, NonceBytes, "MATRIX_QR_CODE_PROOF_OF_POSSESSION")
I started out thinking I'd use HMAC for the purpose, but then forgot about it and chose this out of a desire not to mix primitives, even though we don't need encryption. But since we're already using HMAC in other places in the spec, I agree it's the better idea.

Will change.

2024-04-12 11:00 UTC, dkasak commented on proposals/4108-oidc-qr-login.md
> +Proof := ChaCha20Poly1305_Encrypt(EncKey_Proof, NonceBytes, "MATRIX_QR_CODE_PROOF_OF_POSSESSION")
This is now done.

2024-04-16 12:23 UTC, merged

2024-04-16 12:24 UTC, hughns reviewed
👍