MSC4140: Cancellable delayed events
matrix-org/matrix-spec-proposals pull request #4140
Opened 2024-05-07 16:52 UTC by toger5

[Rendered](https://github.com/matrix-org/matrix-spec-proposals/blob/toger5/expiring-events-keep-alive/proposals/4140-delayed-events-futures.md)

This could also supersede [MSC2228](https://github.com/matrix-org/matrix-spec-proposals/pull/2228) (by making it possible to send a redaction with the `/send` endpoint. This is the case as mentioned [here](https://matrix.to/#/!ewdjhNcPcEmYNKzlWp:t2l.io/$r_PveZzw9TqvN3qKjCmxnIavR2CCKRWvTPJoLW6BA8k?via=t2l.io&via=matrix.org&via=element.io))

Implementations:

- [x] Synapse
  - https://github.com/element-hq/synapse/pull/17326
- [x] Element Call running in SPA mode
  - https://github.com/matrix-org/matrix-js-sdk/pull/4294
  - https://github.com/element-hq/element-call/pull/2529
- [x] Element Web running Element Call in embedded mode
  - https://github.com/matrix-org/matrix-js-sdk/pull/4294
  - https://github.com/matrix-org/matrix-widget-api/pull/90
  - https://github.com/element-hq/element-call/pull/2529
- [x] Element X running Element Call in embedded mode
  - https://github.com/ruma/ruma/pull/1845
  - https://github.com/matrix-org/matrix-rust-sdk/pull/3600
  - https://github.com/element-hq/element-call/pull/2529

Known implementation gaps:
 - [ ] 3ef314f861f3e54a9a474e624eba3684ee6ea978
 - [ ] 95045cf00eeb2af0976b31d2262875ef7eefaeec
 - [ ] 49b200dcc11de286974925177b1e184cd905e6fa
----

SCT stuff:

[checklist](https://github.com/matrix-org/matrix-spec-proposals/pull/4140#issuecomment-2806245590)

FCP not yet started

~~Blocked: https://github.com/matrix-org/matrix-spec-proposals/pull/4140#issuecomment-3276054888~~

2024-05-08 18:27 UTC, AndrewFerr commented on proposals/4140-expiring-events-with-keep-alive-endpoint.md
> +If the homeserver detects a `m.expired` field it will store and distribute the
Is this supposed to be:
```suggestion
If the homeserver detects a `m.will_expire` field it will store and distribute the
```
?

2024-05-08 18:27 UTC, AndrewFerr commented on proposals/4140-expiring-events-with-keep-alive-endpoint.md
> +timeout duration in seconds.
Is this saying that the only time the field may be a numeric value instead of an enum is when the event is the payload of a `PUT` request?

Also, is it ever valid to send a `PUT` request with the field set to an enum value?  I presume it is not.

2024-05-08 18:27 UTC, AndrewFerr commented on proposals/4140-expiring-events-with-keep-alive-endpoint.md
> +where the `refresh_method` is either: `refresh`, `end`
Nitpick to match the formatting style of the spec (which IMO improves readability):
```suggestion
where the `refresh_method` is one of: `[refresh, end]`
```

2024-05-08 18:27 UTC, AndrewFerr commented on proposals/4140-expiring-events-with-keep-alive-endpoint.md
> +no metadata is leaked when. This allows to share a refresh link to a different
```suggestion
no metadata is leaked. This allows to share a refresh link to a different
```
or was something else meant to be said here?

2024-05-08 18:27 UTC, AndrewFerr commented on proposals/4140-expiring-events-with-keep-alive-endpoint.md
> +  the homeserver receives a new state event without `m.expires` but with the same
ditto
```suggestion
  the homeserver receives a new state event without `m.will_expire` but with the same
```

2024-05-08 18:27 UTC, AndrewFerr commented on proposals/4140-expiring-events-with-keep-alive-endpoint.md
> +The homeserver does the following when receiving an event with `m.expired`
```suggestion
The homeserver does the following when receiving an event with `m.will_expire`
```
Right?

2024-05-08 18:27 UTC, AndrewFerr commented on proposals/4140-expiring-events-with-keep-alive-endpoint.md
> +- Starts a counter for the stored expiation token.
```suggestion
- Starts a timer for the stored expiration token.
```

2024-05-08 18:27 UTC, AndrewFerr commented on proposals/4140-expiring-events-with-keep-alive-endpoint.md
> +```
Should refresh requests also send the `eventId` of the target event, to prevent collisions between multiple expiring events?  OTOH, if the refresh tokens are UUIDs, collisions would be unlikely.

...oh, and requiring the event ID would also leak it to whoever is doing the refreshing.

2024-05-08 18:27 UTC, AndrewFerr commented on proposals/4140-expiring-events-with-keep-alive-endpoint.md
> +  timer is restarted with the stored expire duration.
Should refresh requests allow for changing the expire duration (specified in the request body, for instance)?

2024-05-08 18:43 UTC, toger5 commented on proposals/4140-expiring-events-with-keep-alive-endpoint.md
> +timeout duration in seconds.
Enum in terms of: only a defined set of strings are valid.

2024-05-08 18:43 UTC, toger5 commented on proposals/4140-expiring-events-with-keep-alive-endpoint.md
> +```
Exactly I think it would be easier to just allow: roomid+eventid but as evaluated later on, this would allow guessing (or if you are part of the room; computing) the refresh url -> allowing others to end the call membership.

2024-05-08 18:43 UTC, toger5 commented on proposals/4140-expiring-events-with-keep-alive-endpoint.md
> +If the homeserver detects a `m.expired` field it will store and distribute the
thx

2024-05-08 18:43 UTC, toger5 commented on proposals/4140-expiring-events-with-keep-alive-endpoint.md
> +- Starts a counter for the stored expiation token.
that makes more sense, yes.

2024-05-08 18:43 UTC, toger5 commented on proposals/4140-expiring-events-with-keep-alive-endpoint.md
> +  timer is restarted with the stored expire duration.
I think it shouldn't. The reason is:
The refresh endpoint should be shareable with other parties without concerns.
Those parties (the SFU) should not be able to change the refresh time the client/user decides to configure.

In a real world scenario the client will check if the SFU supports the `will_expire` `refresh` and if that is the case it will use a long expiration duration (like 1hour). this reduces the load and since an SFU is exprected to not get disconnected from the network a liberal value is acceptable. The SFU will send the `/end` request once the user disconnects.

The SFU however should not be able to change the expiration to 2 years for instance.

2024-05-08 18:43 UTC, toger5 commented on proposals/4140-expiring-events-with-keep-alive-endpoint.md
> +  the homeserver receives a new state event without `m.expires` but with the same
Oh again...

2024-05-09 08:40 UTC, AndrewFerr commented on proposals/4140-expiring-events-with-keep-alive-endpoint.md
> +  timer is restarted with the stored expire duration.
The other parties being disallowed from changing the timeout is a great point, thanks.

And besides, the original sender of the expiring event could always just send a brand new state event with a different timeout to replace the original state event & its timeout.

2024-05-09 08:53 UTC, AndrewFerr commented on proposals/4140-expiring-events-with-keep-alive-endpoint.md
> +timeout duration in seconds.
This should specify whether the `PUT` request for setting the event is allowed to set `m.will_expire` to one of the enum values or not.

From my understanding, the initial request to set the event _must_ provide a numeric `m.will_expire`, and the enum values are used exclusively by the homeserver when it actually puts the event into the room's event graph.

2024-05-20 11:44 UTC, MatMaul commented on proposals/4140-delayed-events-futures.md
> +This MSC also allows to implement self destructing messages:
It seems possible to use that also to schedule messages for later I believe? I am unsure if a timeout is enough or if a timestamp would be useful. I think timeout seems enough since the computation would be simple enough to do client side from a timestamp to a timeout.

A way to retrieve futures would be useful however, so we can list them in a client if needed.

2024-05-20 11:48 UTC, MatMaul commented on proposals/4140-delayed-events-futures.md
> +This MSC also allows to implement self destructing messages:
Regarding timeout vs timestamp it would probably incur some small delay however, because between the computation client side and the request being registered server side, it may take some seconds. Not sure if it is really important however.
Replacing timeout by timestamp (instead of allowing both) may be the way to go for simplicity and accuracy.

2024-05-20 13:26 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +This MSC also allows to implement self destructing messages:
Per room? so you want others room members to see the messages that are going to be sent?
I was thinking more about a per user api where I can see a list of events i have scheduled.

2024-05-20 14:15 UTC, MatMaul commented on proposals/4140-delayed-events-futures.md
> +This MSC also allows to implement self destructing messages:
I was thinking about per room for the current user. But then it's tedious to get it for all rooms if needed so a global one is probably better, and the client can filter. Perhaps we want to be able to specify a message `type`.

This leads me to think... Do we want this in sync in the end ? We could have a `futures` section there.

2024-05-20 17:42 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +This MSC also allows to implement self destructing messages:
That makes sense. I really dont like the idea of sharing this information with other users however. I really think the concept of: "Everything that is shown/shared by other room members should be in the DAG" is super important. To continue with this model a future that is not yet sent into the room should also only be known  by the sender. Otherwise it would make much more sense to just put the data into the room state. If that is desired no-one is stopping the sender to also mention in the room state what futures they have scheduled.

2024-05-20 17:44 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +This MSC also allows to implement self destructing messages:
> It seems possible to use that also to schedule messages for later I believe

I noticed I have not yet commented on this. But yes this is totally possible and could be another section in the use cases!

2024-05-20 17:46 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +For this usecase an optional `m.send_now` field can be added to the body.
If we have a generlized way to batch sent matrix events this could be leverged on this and a future itself is JUST the future. And the batch send event would define the semantics for sending the future and guaranteeing that the send_now event is also sent

2024-05-21 12:03 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +For this usecase an optional `m.send_now` field can be added to the body.
[MSC2716](https://github.com/matrix-org/matrix-spec-proposals/pull/2716) allows bulk sending events.

2024-05-22 18:00 UTC, AndrewFerr commented on proposals/4140-expiring-events-with-keep-alive-endpoint.md
> +timeout duration in seconds.
This is no longer relevant now that the concept of expiry types has been dropped.

2024-05-22 19:30 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +since the sender can choose what event will be sent once expired.
Is it entire events that need to be signed, or just their content?  If it's the former, then `/send/future` should behave more like #4080's [`/send_pdus`](https://github.com/devonh/matrix-spec-proposals/blob/cryptoIDs/proposals/4080-cryptographic-identities.md#post-_matrixclientv1send_pdustxnid).  This could be done by having `/send/future`'s `send_*` fields accept fully-signed events instead of signed content + other fields.

For this to work, there'd also need to be the [modified PUT `/send` & PUT `/state` endpoints](https://github.com/devonh/matrix-spec-proposals/blob/cryptoIDs/proposals/4080-cryptographic-identities.md#put-_matrixclientv4roomsroomidsendeventtypetxnid--put-_matrixclientv4roomsroomidstateeventtypestatekey) for retrieving the PDUs that need signing.

That would make the client flow of sending a Future as follows:
- call PUT `/send` / PUT `/state` for each event that's to be sent in a Future (ideally, this could be batched)
- sign each retrieved PDU
- put each signed PDU in a request to `/send/future`, placing them in `"send_*"` fields as desired

2024-05-23 17:50 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +to send a list of event contents. The body looks as following:
How do power levels interact with Futures?  Should PLs be enforced on the events sent in `/send/future`, or on the event that the homeserver adds to the DAG on timeout / action time?

At least the `send_now` event should be subject to PLs.

2024-05-23 17:50 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +`PUT /_matrix/client/v3/futures/refresh` and `PUT /_matrix/client/v3/futures/action/${actionName}`.
Should there be a `/futures/cancel` endpoint as well?  Without it, the only way to cancel a Future is to send a state event with the same state key & content as the Future's `send_on_timeout` event (which, of course, is applicable only when the `send_on_timeout` event is a state event).  That also prevents external services from being able to cancel, as they can only hit the `future_token`-accepting endpoints & can't send events.

2024-05-23 17:50 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +    "m.send_now": finalEvent_0,
Is there a point in returning the `send_now` event if it would have been sent already?

2024-05-23 17:50 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +In some situations the client just looses connection or fails to sent the expired
```suggestion
In some situations the client just loses connection or fails to sent the expired
```

2024-05-23 17:50 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +## EventId template variable
If pre-signing events requires them to have event IDs to be included in the signature, then all event IDs will be known by the time `/send/future` is called & it won't be necessary to have this template variable.

I asked about signing with event IDs here: https://github.com/matrix-org/matrix-spec-proposals/pull/4080/files#r1610545596

2024-05-24 15:16 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +## EventId template variable
Oh this is really great actually.
It will force us to have multiple request but what is really good is, that it is really easy to send the current state and the timout state at the same time!

2024-05-24 15:25 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +## EventId template variable
Added a note so that it is clear that this is only a stop gap and that there are more elegant solutions.
I still would like to keep that section since its part of the explantion why we would like to send events at the same time and
why its better to solve it in a different way.

2024-05-24 15:32 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +to send a list of event contents. The body looks as following:
(As discussed)
Power levels should always be applied right before the event is distributed (added into the DAG)
The homeserver treats the event as if it was sent at the point in time where it is resolved (either by the timeout or an action)
The homeserver runs all the normal checks (power level, room memberhsip...) at the time of resolving the event. It is possible for a future to be rejected on timeout and not be send into the room in case the permissions have changed.

2024-05-24 15:32 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +```
I removed them.

2024-05-24 15:35 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +There can be an arbitrary amount of `actionName`s.
I like this.

2024-05-24 15:49 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +since the sender can choose what event will be sent once expired.
> call PUT /send / PUT /state for each event that's to be sent in a Future (ideally, this could be batched)
> sign each retrieved PDU
> put each signed PDU in a request to /send/future, placing them in "send_*" fields as desired

What should be batched is mostly the put PDU's right. Since creating the signed PDU's is okay to not be batched. The client then just needs to be sure that they have created all the events before sending the signed PDU's. if creating the PDU's fails the client just retires until it has the full list of events that need to sent (because they rely on each other)

So what really would need to be batched is the last step. Sending the signed PDU's.

2024-05-24 16:34 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +since the sender can choose what event will be sent once expired.
If there are multiple futures in one send_pdus call multiple future tokens need to be issued. In the response a dictionary with future_id-> token would use the id to map all the tokens.

2024-05-30 17:41 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +`PUT /_matrix/client/v3/futures/refresh` and `PUT /_matrix/client/v3/futures/action/${actionName}`.
```suggestion
`POST /_matrix/client/v3/futures/refresh` and `POST /_matrix/client/v3/futures/action/${actionName}`.
```
because these don't accept transaction IDs and aren't idempotent.  For example, multiple `POST /refresh`s for the same token should repeatedly refresh the timeout, and any `POST /action/${actionName}` after the first should fail (as the action event would have been posted already).

2024-06-03 15:16 UTC, hughns requested changes
Some suggestions for clarity.

2024-06-03 15:16 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +This guarantees that all tokens will expire eventually.
```suggestion
This guarantees that all tokens will eventually expire.
```

2024-06-03 15:16 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +For self destructing messages it is recommanded to include
```suggestion
For self-destructing messages it is recommended to include
```

2024-06-03 15:16 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +### Self destructing messages
```suggestion
### Self-destructing messages
```

2024-06-03 15:16 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +The **Self destructing messages** example would simplify to:
```suggestion
The **Self-destructing messages** example would simplify to:
```

2024-06-03 15:32 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +`PUT /_matrix/client/v3/rooms/{roomId}/send/future/{txnId}`
```suggestion
`PUT /_matrix/client/v3/futures/send/{txnId}`
```
because:
1) `/send/future` has the same path prefix as the regular `/send/{eventType}`, and would conflict with it unless servers treat `future` as a special-case value that can never be an event type
1) The other future endpoints all start with `/futures`, and it would be consistent if this one did too
1) Removing `roomId` from the path opens up the possibility for each event in the future to refer to a different room

2024-06-03 18:27 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +Allowing to schdule/delay events would solve numerous issues in
```suggestion
Allowing to schedule/delay events would solve numerous issues in
```

2024-06-03 18:27 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +The server will first send the finilized event to the client.
```suggestion
The server will first send the finalized event to the client.
```

2024-06-03 18:27 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- RetardedEvents
Let's not consider this one.

How about `PostponedEvents`?

2024-06-05 22:07 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +`PUT /_matrix/client/v3/rooms/{roomId}/send/future/{txnId}`
changed it to `/_matrix/client/v3/rooms/{roomId}/send_future/{txnId}` now since this mimics the current `send` endpoint. In the alternatives there is a section to consider using the `send` endpoint directly as discussed.

2024-06-05 22:09 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +There can be an arbitrary amount of `actionName`s.
and added it now

2024-06-06 07:48 UTC, fkwp commented on proposals/4140-delayed-events-futures.md
> +the client tries to send an action future without there being a timeout future with the same `group_id`
```suggestion
the client tries to send an action future without there being a timeout future with the same `future_group_id`
```

2024-06-06 07:49 UTC, fkwp commented on proposals/4140-delayed-events-futures.md
> +MatrixRTC makes it necessary to have real time information about the current matrixRTC session.
```suggestion
MatrixRTC makes it necessary to have real time information about the current MatrixRTC session.
```

2024-06-06 07:50 UTC, fkwp commented on proposals/4140-delayed-events-futures.md
> +  "send_token": "token",
What about adding the `future_group_id` as well?

2024-06-06 07:54 UTC, fkwp commented on proposals/4140-delayed-events-futures.md
> +For displaying the room list timeout based approaches are much more reasonable because this allows computing matrixRTC metadata for a room to be synchronous.
```suggestion
For displaying the room list timeout based approaches are much more reasonable because this allows computing MatrixRTC metadata for a room to be synchronous.
```

2024-06-06 08:03 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +the client tries to send an action future without there being a timeout future with the same `group_id`
I called the value `{group_id}` but here it makes more sense to refer to the parameter name.

2024-06-06 10:25 UTC, fkwp commented on proposals/4140-delayed-events-futures.md
> +  - If set to a `number` we call the future **timeout future**
What is the time unit here? seconds?

2024-06-06 10:40 UTC, fkwp commented on proposals/4140-delayed-events-futures.md
> +  the event into the room. Since the timeout can be refreshed and sending the future can be triggered via an endpoint (see: [Proposal/Delegating futures](#delegating-futures)) this value is not enoug
```suggestion
  the event into the room. **Note** Since the timeout can be refreshed and sending the future can be triggered via an endpoint (see: [Proposal/Delegating futures](#delegating-futures)) this value is not enough to predict the time this event will arrive in the room.
```

2024-06-06 15:36 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +```json
Maybe we can specify different response types for timeout & action futures, to make it easier to describe/refer to their exclusive fields.

On that note, do only timeout futures need a `cancel_token`?  And could action futures use a `send_token` instead of a specially-named `action_token`?  (The example JSON below suggests that is the case)

2024-06-06 15:36 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +    **restarts the timer** with the stored `timeout_duration` for the associated timeout future.
Should this respond with a 4xx for action futures, or respond successfully to not leak whether the future is a timeout or action future?

2024-06-06 15:36 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +    },
Could this instead return the path & query parameters (excluding `txnId`) as fields of the returned JSON items?

Also, since the payload of `send_future` and `state_future` is event _content_, we could return the `"content"` that was set in the original request instead of the entire event "body"` (which won't be a complete body anyhow).

2024-06-06 15:36 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +A particular delicat situation is that clients are not able to inform others if they loose connection.
```suggestion
- Who and how many people are currently participating.

A particular delicate situation is that clients are not able to inform others if they lose connection.
```

2024-06-06 15:36 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +  - Use Future events with a 10s timeout to send the disconnected from call in less then 10s after the user is not anymore pingin the `/refresh` endpoint. (or delegate the disconnect action to a serv
```suggestion
  - Update the room state every x seconds. This allows clients to check how long an event has not been updated and ignore it if it's expired.
  - Use Future events with a 10s timeout to send the disconnected from call in less then 10s after the user is not anymore pinging the `/refresh` endpoint. (or delegate the disconnect action to a service attached to the SFU)
```

2024-06-06 15:36 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +be controversion if their return value is altered.
```suggestion
This would be elegant but since those two endpoint are core to Matrix, changes to them might
be controversial if their return value is altered.
```

2024-06-06 15:36 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +dependent on the query parameters.
It would be nice if we could express the response type as a union between the "just an event ID" response type & the response to future requests.  But since all the fields are top-level, I don't think there's a good way to do that.

2024-06-06 15:36 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +The proposed solution does not allow to send multiple events/futures that belong to each other with one
```suggestion
The proposed solution does not allow to send events together with futures that reference them with one
```

2024-06-06 15:36 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +event and the future which results in never expiring call memberhsip or never destructing self-destructing messages.
```suggestion
with one request. Otherwise there is a risk for the client to lose connection or crash between sending the
event and the future which results in never expiring call membership or never destructing self-destructing messages.
```

2024-06-06 15:36 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +before
```suggestion
This would be the preferred solution since we currently don't have any other batch sending mechanism.
```

2024-06-06 15:36 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +  "group_id": group_id,
Since the timeout & action events are already batched, could the group ID be removed from the batch request?

2024-06-06 15:36 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +Use `io.element.` instead of `m.` as long as the MSC is not stable.
I think there's also a policy of prepending all endpoint paths with `/org.matrix.msc###/` (and setting the path's version string to `unstable`, instead of `v#`)

2024-06-06 16:32 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +    **restarts the timer** with the stored `timeout_duration` for the associated timeout future.
I think this would not happen because the refresh token is different to the send token. So a refresh token for a action future (that did not send a refresh token in its response) is equivalent to an arbitrary token unknown to the homeserver.
I think responding with a `410` (Gone) in case the homeserver does not know the token (or does not know it anymore since it got invalidated) would make sense to let the service know this token is invalidated.

2024-06-06 16:46 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +    },
The advantage here is that this is similar to what the homeserver has saved. The homeserver is basically delaying the event so it might just cache the request until one of the futures is triggered.
So this is very lightwait for the homeserver to compose. (Its just the cached http request + response basically.)

How exactly do you think the json should look like?
maybe it makes sense to compose the properties in a simpler manner.

2024-06-06 16:49 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +    },
```
"path":"/rooms/{roomId}/send_future/{eventType}",
"content": eventContent,
// always present
"send_token": "token",
"cancel_token": "token",
"refresh_token": "token"|undefined,
"future_group_id": "group_id",
"future_timeout": number | undefined,
```
?

2024-06-06 16:56 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +  "group_id": group_id,
Yes this is how it was intended. Good find!

2024-06-06 17:31 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +    is still the current state:
`send_now` is out of the main proposal, so resolving this.

2024-06-06 17:43 UTC, fkwp commented on proposals/4140-delayed-events-futures.md
> +- `future_group_id: string` is optional if a `future_timeout` is a `number`. The purpose of this identifier is to group
```suggestion
- `future_group_id: string` is optional if a `future_timeout` parameter is set. The purpose of this identifier is to group
```

2024-06-07 11:43 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +This MSC also allows to implement self destructing messages:
Since there now is a proposed enpoint for the list of futures I mark this as resolved.

2024-06-12 12:38 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +  **multiple futures in one mutually exclusive group**.
These aren't currently scoped per user, so it'd be possible to share the group ID to another user who could then add their own futures to that group.  Is that something we want to allow?  Given that the group ID must be explicitly shared, this shouldn't be a security issue, and might even allow for interesting use-cases; but maybe it's an overreach of what future groups are meant to be.

2024-06-12 12:40 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +dependent on the query parameters.
True, the language of the spec has more flexibility in how to describe response types & optional fields.

2024-06-12 12:55 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +  **multiple futures in one mutually exclusive group**.
Since the HS is issuing the group ids it s the homeservers job to make then unique.

I think that is mentioned somewhere. That the homeserver needs to issue unique ids

2024-06-12 15:46 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +  **multiple futures in one mutually exclusive group**.
As we discussed out-of-band, we do want to scope the `group_id`s to users, at least for these reasons:
- Not scoping `group_id`s raises the question of whether they should be available to all federated users or only local users, which adds complexity either way.  Without scoping, future management can avoid needing federation.
- Having a `group_id` effectively grants full control over the future group (as one could hijack the group by adding a short timeout future to it), so allowing users to share them would give each user full control over them, which would subvert the spirit of the guarantees we want futures & future groups to have.

2024-06-12 15:46 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- Otherwise one of the timeout or action futures will be send.
Do we want to associate futures with the device that created them?  Namely, if a future was created by a particular device, and that device later logs out / is invalidated, should the future be cancelled?

2024-06-12 16:08 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- Otherwise one of the timeout or action futures will be send.
FTR, my intuition is that device invalidation should _not_ cancel a future, as tying future lifetime to device lifetime makes it much more important for users not to lose their device sessions.  It would also lessen the utility of futures if all it takes to render them ineffective is to log out, which would heavily impact some use-cases of futures (like scheduled messages).

2024-06-13 14:44 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +- Otherwise one of the timeout or action futures will be send.
FTR: we as described by @AndrewFerr we do not want futures to expire if a device logs out.

2024-06-13 15:05 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- The future is using a group_id that belongs to a future group from another user. In this case the homeserver sends a [`405`] (`Not Allowed`).
Even better (and what I've been implementing) is for each user to get their own namespace of group IDs, i.e. for the effective group ID to be the tuple of (user ID, group ID).  Benefits include:
- Users cannot guess at other users' group IDs by spamming future requests and waiting to receive an error response.
- More group IDs are available for each user, which is especially useful if we want to allow user-defined group IDs that could otherwise clash.

2024-06-13 19:22 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +    token that is invalidated by now.
```suggestion
  - If a `POST /_matrix/client/v3/futures/{refresh_token}` is received, it
    **restarts the timer** with the stored `timeout_duration` for the associated timeout future.
  - If a `POST /_matrix/client/v3/futures/{send_token}` is received, it **sends the associated action or timeout future**
    and deletes any stored futures with the `group_id` associated with that token.
  - If a `POST /_matrix/client/v3/futures/{cancel_token}` is received, it **does NOT send any future**
    and deletes/invalidates the associated stored future. This can mean that a whole future group gets deleted (see below).
  - If a `POST /_matrix/client/v3/futures/{unknown_token}` is received the server responds with a `410` (Gone).
    An `unknown_token` either means that the service is making something up or that the service is using a
    token that is invalidated by now.
```
to match the change from `PUT` to `POST` due to non-idempotency.

2024-06-19 13:00 UTC, zecakeh commented on proposals/4140-delayed-events-futures.md
> +`PUT /_matrix/client/v3/rooms/{roomId}/state_future/{eventType}/{stateKey}?future_timeout={timeout_duration}&future_group_id={group_id}`
Is there a reason that they use `v3` instead of `v1`? Those being new endpoints I would assume they use the latter.

2024-06-22 05:38 UTC, turt2live requested changes
For logging purposes: this MSC crossed the SCT's desk as potentially scary, so we've given it an early review here. 

The idea of a generic mechanism to address call participant counts, scheduled messages, and self-destructing events is very much appealing. The fewer moving pieces we have to worry about in the spec, the better. This MSC appears to have 3 major concerns which could be classified as 'scary', which all have their own dedicated threads - please ensure discussion happens in those threads. The highlights are:

1. Self-destructing events has a metadata component which likely means it will need a dedicated MSC, despite the preference being fewer moving pieces. The user privacy concerns leading to wanting self-destructing events outweigh the idealistic genericism.
2. A comparison to MSC3277 is missing from this proposal. MSC3277 uses a DAG-based approach to ensure events are authorized and servers don't have to implement complicated subsystems for the scheduled messages feature.
3. Keep alives are unreliable and can have unexpected consequences for users and clients, particularly when a network partition causes a failed ping. For the call participant count use case in particular, the SFU(s) should already know how many connections it has and can reveal that information back to other users. Where network partitions fail the connection to the SFU, the user is dropped from the call regardless. Otherwise, temporary connection issues can ensure the user is reflected as connected with lost audio/video. This system may very well use a keep alive internally (possibly at the TCP layer), but here it would be appropriate compared to event sending.

I've also left several editorial comments to aide understanding of the MSC. I've not done a complete pass on this - these are just the more notable ones. 

As always, if any of my comments require clarification or more information, let me know in the threads :)

2024-06-22 05:38 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +be controversial if their return value is altered.
I think this would be fine. Clients would only get a different response if they use the parameters, meaning they should be expecting a different format. It would be different if *lack of* the future parameters meant a different response body.

2024-06-22 05:38 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +- RetardedEvents
```suggestion
```

We do not use this word.

2024-06-22 05:38 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +## Alternatives
This proposal's main competition appears to be [MSC3277](https://github.com/matrix-org/matrix-spec-proposals/pull/3277), where events are scheduled by placing them in the DAG. The homeserver then forwards the previously-created event at a set time, but it is part of the room until that point.

The DAG approach has a few advantages which I think make it more appealing:
* Message delivery is not subject to a third party being online. Specifically, an appservice, SFU, or similar does not need to be looped in to ensure a message gets sent - it's the homeserver's own responsibility to stay online. We may even be able to federate the event outwards with a `soft_fail_until` timestamp for maximum reliability (at the cost of eager delivery and harder cancellation).
* Events are known to be authorized and able to be sent because they've been given an event ID (and thus run through the auth rules).
* The tracking overhead is extremely minimal: servers at most need to remember to un-soft-fail an event after a set time, but it can do that with rough precision. They do not need to track different tokens for different actions - if a user redacts a scheduled event while it's still soft failed, the send is cancelled. It knows this intrinsically.

2024-06-22 05:38 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +## Potential issues
The keep alive approach appears to reverse the expectation of scheduled messages a bit, which I think may be one of the core concerns with this proposal. With [MSC3277](https://github.com/matrix-org/matrix-spec-proposals/pull/3277), senders expect that their event will go out at the time they schedule it. This proposal moves the expectation to much later in the send process, and creates an assumption that any event can be cancelled or "undone" at any point. This behaviour leads to "unexpected" consequences, because the sender was expecting to be an opportunity for their event to never send.

It's a bit subtle, but that expectation changing I think makes MSC3277 more favourable. MSC3277 doesn't really help with the call participant count problem though. For that, I think the SFU can likely count its connections more reliably than a keep alive (a single network partition leads to a false count). This is discussed in more detail in the 'MatrixRTC use case' thread I've started.

2024-06-24 07:39 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +- The future is using a group_id that belongs to a future group from another user. In this case the homeserver sends a [`405`] (`Not Allowed`).
If we make all the error codes 400 we would need a body to differenciate the different kind of errors right?
Bad Request definitly also feels appropriate.

2024-06-24 08:14 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +- Creating self-destructing events (by sending a delayed redact).
Thread for highlight 1:
I wasn't aware that it is on the table that self-destructing events would use an entirely different concept to redactions.
I was coming from: https://github.com/matrix-org/matrix-spec-proposals/blob/matthew/msc2228/proposals/2228-self-destructing-events.md
Which basically does the same thing. It redacts the event based on conditions.

What I like about this proposal, is that instead of making a custom event and add logic to create synthetic redaction we generalize the concept of event delays and everything else is a completely normal redaction.

Also
> erase the event from the DAG entirely

Sounds like an anti-pattern for a distributed system. Can you guide me on where I can find information about erasing whole events from the DAG including all there metadata without federation conflicts?

2024-06-24 08:30 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +> they are still online. Just to display the room tile properly.
Thread for highlight 3:

This is the most important reason for why we need a heardbeat like expiration system to make matrixRTC performant an realibale!

The main problem we solve here is that we DONT want the client to connect to each SFU all the time and we dont talk about calls this client is connected to. This might sound like a possbile thing todo but is more overhead that one would think (polling or connecting to a socket is not really making a difference here.)

Maybe a more detailed description of the current situation is required here:
Without MatrixRTC your client has no idea about any ongoing call when it starts up.
We introduced `call.member` state events so now we can easily read who is connected in a session in each room.
But due to the nature of state events there is no guarantee that the client will not forget to remove (set them to `{}`) after they disconnect. Each event a client misses to remove results in a room that looks like there is an ongoing call. So for each of these rooms the client has to:
 - Authenticate with the sfu (jwt service token)
 - Connect to the sfu wbsocket.
 - Check the current participants.
 - Invalidate all the member event locally. (Since they cannot write to those member events because its owned by another member they have to do this on every client.)
 It is very easy to have such a invalid event: a user pressing ctrl + w while in call in EW is enough.
 The commented section of the MSC gives an exmaple. If you have multiple rooms where there are left over member state events you need do the 3 steps for each of them individually.
 
 Workarounds we tried:
 Storing a timestamp in the state event and updating the event every 30min. This allows to compute an invalidate event without connecting to an sfu. (but only after a 30min time where you see a call that is not happening)

2024-06-24 08:32 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +be controversial if their return value is altered.
That is really nice!
It would be as you describe:
Without future parameters the response would be the same as it is now.
With the parameters the response would be different.

2024-06-24 09:00 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +- The future is using a group_id that belongs to a future group from another user. In this case the homeserver sends a [`405`] (`Not Allowed`).
You need a body in any case unless there's a strong justification for non-standard errors. The MSC should say errors produce [standard error responses](https://spec.matrix.org/v1.11/client-server-api/#standard-error-response) and define the `errcode` in addition to the HTTP status code. Old errors are not properly defined, but any new MSCs should not make the same mistakes as the spec did in the past and should define a separate code for each error.

2024-06-24 10:18 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +- The future is using a group_id that belongs to a future group from another user. In this case the homeserver sends a [`405`] (`Not Allowed`).
Working on that right now.

2024-06-24 10:25 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +## Alternatives
We are very open to insert the events into the DAG when sent. This was discussed and even has a bunch of advantages (mostly that the event_id is available immediately)

The biggest reason against it was the assumption that this might be too big of a change: It adds the complexity of a state where an event is in the dag but not yet (and maybe never) is distributed to clients.

> Message delivery is not subject to a third party being online. Specifically, an appservice, SFU, or similar does not need to be looped in to ensure a message gets sent - it's the homeserver's own responsibility to stay online. We may even be able to federate the event outwards with a soft_fail_until timestamp for maximum reliability (at the cost of eager delivery and harder cancellation).

The delivery does not rely on a third party. It relies on the homeservers timeout computation. (that is enforced by the future group! The example with the client that pings every 10s describes this well. The client getting disconnected and not sending the ping anymore lets the homerserver know it can deliver the event now.

To me, it seems that the least intrusive change is to not add events to the DAG and instaed just queu them on the homeserver/pretend the http request was received later. But I really like it if it's possible to add it to the DAG right after receiving the event and immediately computing an `event_id`.
Because Future events can also be canceled, it needs to be valid to have non sent events in the dag forever. As described in the MSC, in most cases you want to schedule multiple events in one future group and only send one of them. Adding them all to the DAG seems unnecassary.
But other than that, this sounds like a very compatible and nice solution. Do I understand it correctly that the homeserver will not send the event to federating homeservers until the timeout condition is met?

2024-06-24 10:39 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +## Potential issues
The core assumption of the voip writing this MSC is that it is of essence that syncing room state is enough to compute all ongoing MatrixRTC sessions. With the reasons described here: https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r1650573427

So It seems we have the following two scenarios:
 - We go with a SFU based state event validation approach (each client logs requests a token and logs into each SFU mentioned in any RTC member event it encounters and verifies its validity (if the user is still connected to the session))
  - We want the memberships/sessions to be reliably represented in the room state.
  
 If we decide for 1. we really don't need any of the MSC's and I can see how a static timeout as described in [MSC3277](https://github.com/matrix-org/matrix-doc/pull/3277) could be a solution. Even though no interaction to the scheduling definitively limits its use-cases.
 
 But the experience we made during a whole year concluded that we should make the state events reliable.
 (Other logic: historic session computation, changes in call realted UX, building matrixRTC sdk's all are super hard to implement and involve a a lot of duct tape if we cannot trust member state events but have to check the SFU all the time. It also means we can only validate state events in real time but never tell if a state event was invalid in the past.)

2024-06-24 12:05 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +    **futures get invalidated and the associated timers are stopped**.
> to jump ahead and send it early

This is done by using the `future_send_token`. It can be sent to immediately send the future.

> Why is this limited to state events?

This additional rule for state events makes sure, that if a users want to update state A with C that they dont overwrite it if the state changed to B before the future resolves.

For room events there is no concept of a (type, key) pair that could be overwritten.

2024-06-24 12:26 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +  - Group id's can only be used by one user. Reasons for this are, that this would basically allow full control over a future group once another matrix user knows the group id. It would also require
The `group_id`'s are server generated UUID's, so I am not sure how this could be phrased like transaction ID's.

2024-06-24 12:31 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +  of retrieval and the `timeout_duration`.
Added the format/security of those tokens.

We might not want them to be part of the url.
What do you think about moving those tokens into the body?

2024-06-25 15:43 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +## Alternatives
The VoIP team had a dedicated meeting to thoroughly investigate the option to use MSC3277's approach of adding the event to the DAG on retrieval.

We have created a summary document here: https://hackmd.io/h0z82KvKSaiW-jYlOnU69w?edit
(this will be posted below as well for visibility)

2024-06-25 15:43 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +## Alternatives
# Reliable State events (Future MSC)

The Future MSC is not sending 

### Soft fail (DAG) vs Homeserver queuing (not in DAG)
MSC4140 and MSC3277

https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r1649563962
> Message delivery is not subject to a third party being online. Specifically, an appservice, SFU, or similar does not need to be looped in to ensure a message gets sent - it's the homeserver's own responsibility to stay online. We may even be able to federate the event outwards with a soft_fail_until timestamp for maximum reliability (at the cost of eager delivery and harder cancellation).

This is the case for both proposals. The delivery itself is in full control of the homeserver.

For both proposals the homserver is given additional information to the event and will make it real eventually based on those parameters.

The main differentiator is that with MSC4140 external interaction is optionally possible.
The `/future/{futureToken}` endpoint allows interacting with event scheduling.

**This is the main feature we require to get Reliable VoIP to work.**

It is not important if we add the event to the DAG immediately, but we need the scheduling interaction of `/future/{futureToken}`.

> Events are known to be authorized and able to be sent because they've been given an event ID (and thus run through the auth rules).

We explicitly only have one auth period: at send time. While scheduled, the auth conditions can change, so the proper time to do auth computation is at send time.

With MSC3277 we would need to rerun the auth rules when sending the event.

> The tracking overhead is extremely minimal: servers at most need to remember to un-soft-fail an event after a set time, but it can do that with rough precision. They do not need to track different tokens for different actions - if a user redacts a scheduled event while it's still soft failed, the send is cancelled. It knows this intrinsically.

Using this with the required interaction tokens would result in the following:
 - Send a scheduled event with 10s
 - On each refresh/reset token retrival the homserver would redact the event and send a new one (with the send_at updated by 10s)
     - This would become quite complicated with cryptographic identities, since the user would need sign all of them. Each reset/refresh needs a client server roundtrip for signing.
 - Whenever there is no reset/refresh for 10 seconds (e.g. the device has crashed) the homeserver would un-soft-fail (send) the event.
     - Automatically
The main issue we have with this is the large trafic that generates on the homeserver. For clients this would be equivalent (at least without cryptographic identities) but the homeserver needs to insert a new event (and send it over federation) for each refresh.


Comment:
 - If we delegate leaves to the SFU we would configure the timeout to a duration in the hour range. This would make the above much more bearable.
 - We still need to decide if we want to federate the delegation tokens. Otherwise we dont get any benefit from federating the scheduled event if we can only interact with it through the sending homeserver.

Comparison
||MSC3277|MSC4140|
|-|--|--|
Traffic|Lots of traffic (one evet per refresh) between federating homeservers. For the client it is the same|Since we do not add the event to the DAG until we know it will be sent, there is no traffic because of the scheduling.|
resilience (only scheduling)|Scheduled events are even sent if the sender's homeserver goes down.|The sender's homeserver is required at send time to send the event. If it is down at sent time the event will not be sent until it comes back up.|
resilience (with interaction)|This is just not possible because sending an event (based on an interaction) before the `at` time requires redacting the scheduled one and creating a new one, which cannot be done by a different homeserver then the one hosting the sending user.| Cannot be done. It would also require federting all the interaction tokens and the unsent events but we end up in the same scenario where a homeserver would need to send an event for a user on a different homerserver.
Federation (without interaction) | Works|Doesn't work
Federation (with interaction)|We need interaction tokens (`futureTokens`) and they cannot be federated. Otherwise federating homeserver admins could interact with the Futures/scheduled messages. **With interaction there is no way we can make federation work and we lose all the benefit of inserting the event into the DAG.**|The same, we cannot ever send `futureTokens` to other homeservers since they would be able to interact with the futures. 
Auth | Here interaction could work by redacting the scheduled event and sending a new scheduled event. This is authenticaed but only the client can send the events. If we want interaction that can be delegated to the SFU (which is the best source of truth) we would need to introduce tokens similar to `futureTokens`.| With the `futureToken` based authentication (that is different to the client auth token) we have an extremely scoped auth mechanism that can be send to third parties like the SFU. The SFU can notify the homeserver about a user disconnect. The SFU is the best source of truth for that.
Tracking overhead|All the schedule tracking information is stored in the DAG and a timer needs to run through all potential expired scheduled messages periadically. This has to happen on ALL homeservers.|Very similar logic to the scheduled events except that the tracking information is stored in a seperate Future database only on the sender's homeserver (less overhead).

## TLDR:
If we don't need interaction, there is a benefit in federating the scheduled message (adding it to the DAG immediately). It increases resiliance: the sender's homeserver can disconnect and the scheduled message still will enter non-soft-failed state (will be sent).

With delegatable interaction (which is the one property we need for reliable state events), we lose the possiblity to federate scheduled messages* and the two solutions would converge to one where we lose the property of the sender's homeserver being able to lose connection but the scheduled message still is sent on other homeservers.

_\* reason being that this would also require to federate (and hence leak) the interaction tokens and allowing other homeservers to interact with the future without the user explicitly giving consent by sending the tokens.)_

#### Conclusion
We are faced with the decision between:
 - Do not assume that the senders homeserver stays online:
    - Federate the scheduled message (reslience) but loose the interaction we need for MatrixRTC reliable call member events.
 - Assume that the senders homeserver stays online:
    - If the senders homeserver is expected to stay online there is no reason to federate the scheduled/future event and we can safely add interaction which allows us to implement reliable call member events

2024-07-15 16:16 UTC, turt2live commented
(please avoid force pushing after review has been given - it makes it harder to review. We squash commits upon merge, so hundreds of 'fix typos' is fine)

2024-07-24 09:36 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +a room on behalf of a user at a later time.
Since the user is still the one creating and in the future signing the event I am not sure "behalf of the user" is the right wording?
It is publishing an event sent by a user itself at a later point in time?

2024-07-24 10:26 UTC, toger5 reviewed
Thank you so much @hughns.

2024-07-24 10:26 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +]
Removing this or changing the formatting of the `GET` response is a good idea.
(As we discussed in chat)

2024-07-24 10:26 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +
If we mention it here this should also provide some of the context information we have evaluated.
 - heartbeats need to federate to.
 - other homeservers missing heartbeats would result in the event reaching the dag (fragile if there are lots of homeservers involved and all of them could cancel the session)
 
This comment: https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/fa461e21a39adcbbc676adf265fc74a20bf8488a#r1653083566, should be linked or summarized here.

2024-07-24 10:26 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +
I think this should mention the main differentiator that this uses the sync loop as the "heartbeat" equivalent.
 - No network traffic overhead
 - Homeserver/client dependent timeouts
 - As syncing is a per client concept the rtc app has to either run in the same process so that a rtc app failure triggers the client last will or the client has to observe the rtc app and simulate the last will if the rtc app fails.

2024-07-24 10:27 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +]
read through this commit by commit. This is already solved!

2024-07-24 10:29 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +We propose adding a new authenticated endpoint `GET /_matrix/client/v1/futures` to the client-server API to allow clients to get a list of all the events that have been scheduled to send in the futur
is v1 what we are supposed to use? Do we not start at 0?

2024-07-24 11:22 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +POST /_matrix/client/v1/futures/1234567890
I am wondering if this is a too generic endpoint name?
`update_future_event` might be better?
Otherwise this really could be anything

2024-07-24 12:53 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +- When the SFU is capable of taking care of managing our connection state, and we trust the SFU to
I think since this is not proposing any change to the spec (leaving it out would not change the msc) and the delegation itself probably will not be an msc (there will be an msc for the scoping by endpoints but the usage for matrix rtc will just be on the implementation level) we can keep it in here for context. Except if someone suspects this makes the msc harder to understand and to review. I have the opinion that this is giving interesting context and answers all concerns how and if a sfu driven disconnect can be possible.

2024-07-24 13:23 UTC, fkwp commented on proposals/4140-delayed-events-futures.md
> +- When the SFU is capable of taking care of managing our connection state, and we trust the SFU to
sorry I was ref to 

> When the SFU is capable of taking care of managing our connection state, and we trust the SFU to not disconnect, a really long value can be chosen (approx. 2-10hours). The SFU will then only send an action once the user disconnects or loses connection (it could even be a different action for both cases handling them differently on the client) This significantly reduces the amount of calls for the /update_future endpoint since the SFU only needs to ping once per session (per user) and every 2-5hours (instead of every X seconds.)

2024-07-24 13:29 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +- When the SFU is capable of taking care of managing our connection state, and we trust the SFU to
That is the context I was commenting on.
With scoped tokens this is no additional MSC.  When a client can request a token the SFU can get this token and use it as any other client to send the request as specified in this MSC here.
Hence there might not even be an MSC for it. The MatrixRTC MSC will just make it clear that the state has to be updated once the user disconnects and to have a "guarantee" that the user will disconnect eventually a future has to be used. If a third party get scoped access to the the future sending this is just a more efficient client implemantation to fullfill the requirement that the state is updated on dicsonnect.
So mentioning it here might be good to give context that this is a possible usecase.

2024-07-24 14:37 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +We propose adding a new authenticated endpoint `GET /_matrix/client/v1/futures` to the client-server API to allow clients to get a list of all the events that have been scheduled to send in the futur
As far as I know, we start at v1.

2024-07-24 14:39 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +POST /_matrix/client/v1/futures/1234567890
For consistency with how this MSC is now named and "positioned" I would suggest `delayed_events` so that you have:

`GET /_matrix/client/v1/delayed_events` and `POST /_matrix/client/v1/delayed_events/{future_id}`

2024-07-24 14:54 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +We propose adding a new authenticated endpoint `GET /_matrix/client/v0/futures` to the client-server API to allow clients to get a list of all the events that have been scheduled to send in the futur
Hopefully [`b79e4e2`](https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/b79e4e2762648dd4fb8f4b4839f350cb27c12302) achieves this.

2024-07-24 14:57 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +- The future is using a group_id that belongs to a future group from another user. In this case the homeserver sends a [`405`] (`Not Allowed`).
This has been incorporated into the latest draft.

2024-07-24 14:58 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +  of retrieval and the `timeout_duration`.
"Delegation" is no longer part of this proposal so marking this conversation as resolved.

2024-07-24 15:05 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +to be managed.
How about putting the `future_id` in the request body (to avoid it appearing in web request logs)?

It also feels awkward to use both a path parameter & a body parameter (for the action).

2024-07-24 15:07 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +a room on behalf of a user at a later time.
I'm not sure it really matters in this context... I've taken it out anyhow. 🤷

2024-07-24 16:06 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +to be managed.
I rescind this request: as we discussed, there's precedent in using the response of a `GET` endpoint as a path parameter in a `POST` method for the same endpoint path (which is already done for event/room IDs).

2024-07-24 16:38 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +      "event_type": "m.call.member",
I've incorporated this in to [`93c932a`](https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/93c932aa01faed18b81048fb30c2fb781b78a50e)

2024-07-24 16:39 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +endpoints by adding an optional `future_timeout` query parameter.
As per discussion just now, we are going to stick with adding the query parameter to the existing API endpoints rather than having new API endpoints.

2024-07-24 16:40 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +POST /_matrix/client/v1/futures/1234567890
This has been incorporated into the latest proposal.

2024-07-24 16:42 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +can respond with a [`400`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400) and a Matrix error code `M_FUTURE_MAX_TIMEOUT_EXCEEDED` and the maximum allowed timeout (`timeout_duration` in
The field is now called `max_delay`. I think `M_INVALID_PARAM` could work as an alternative. I don't think it makes a difference at this stage to the proposal. It could be resolved during FCP if required.

2024-07-24 17:29 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +can respond with a [`400`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400) and a Matrix error code `M_FUTURE_MAX_TIMEOUT_EXCEEDED` and the maximum allowed timeout (`timeout_duration` in
Actually, I've added this to the alternatives section.

2024-07-24 17:30 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +be controversial if their return value is altered.
Resolving this conversation as it matches the latest proposal.

2024-07-24 17:31 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +  - Group id's can only be used by one user. Reasons for this are, that this would basically allow full control over a future group once another matrix user knows the group id. It would also require
Groups do not exist in the latest proposal, so marking this conversation as resolved.

2024-07-24 17:32 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +gets closed or looses connection and without knowing anything about the Matrix call.
The ability to delegate "heartbeats" to an SFU is no longer in the latest proposal, so marking this conversation as resolved.

2024-07-24 17:35 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +- The future is using a group_id that belongs to a future group from another user. In this case the homeserver sends a [`405`] (`Not Allowed`).
Group IDs are not in the latest proposal.

2024-07-25 06:15 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> -      "event_type": "m.room.message",
This is sth we cannot change in this MSC.

2024-07-25 09:24 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +that uses room messages to communicate the call state. However, it only allows for calls with two participants.
@hughns those are marked as outdated but i think parts of it is still open?

2024-07-25 11:36 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +- When the SFU is capable of taking care of managing our connection state, and we trust the SFU to
This reference to delegation has been removed in [`9098fea`](https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/9098fea5e5bc31d900c5ad4db92c604f6293df86).

2024-07-25 11:47 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +able to communicate with the homeserver (e.g. the user closes the app or loses connection) the call state is not updated to
I've incorporated this in [`a1b8121`](https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/a1b81213e2781758ca8097eb294ab663f6a2ea39).

2024-07-25 11:51 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +can then periodically reset/restart the timer whilst it is running. If the client is no longer running or able to communicate then the timer would expire and the homeserver would send the "hangup" ev
In [`9098fea`](https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/9098fea5e5bc31d900c5ad4db92c604f6293df86) I have rewritten the MatrixRTC use case of this MSC using a concrete example and the heartbeat terminology.

I've also added [`3a3a5b5`](https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/3a3a5b5fea265269068ccc423230fe817aea32ee).

2024-07-25 12:20 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +So, unless the delayed event is updated beforehand, the event will be sent after `running_since` + `delay`.
I first understood `running_since` as the time it was initially sent.
`last_restart: timestamp` is what we could use.

2024-07-25 13:47 UTC, zecakeh commented on proposals/4140-delayed-events-futures.md
> +in the `delay_id` field (omitting the `event_id` as it is not available):
It does not seem like a good idea to use the same version of the endpoints for this feature because the `event_id` in the response is currently required. Making it optional is not backwards-compatible.

2024-07-25 13:51 UTC, zecakeh commented on proposals/4140-delayed-events-futures.md
> +in the `delay_id` field (omitting the `event_id` as it is not available):
Actually, there will always be an `event_id` for clients that don't support this feature, so it should be fine. Sorry for the noise.

2024-07-25 14:42 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +So, unless the delayed event is updated beforehand, the event will be sent after `running_since` + `delay`.
The problem with `last_restart` as a name is that it doesn't work in the case that the delayed events is never restarted and is sent after the initial delay.

Does `delaying_from` feel any better?

2024-07-25 14:43 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +in the `delay_id` field (omitting the `event_id` as it is not available):
Exactly. It is backwards compatible by virtue of the client having to opt-in.

2024-07-25 17:07 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +For this usecase an optional `m.send_now` field can be added to the body.
Marking as resolved because batch sending is outside of the scope of the proposal and is discussed in the alternatives section.

2024-07-25 17:11 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +For this usecase an optional `m.send_now` field can be added to the body.
It is explicitly mentioned in [`84b8dc0`](https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/84b8dc05ca89f0fd52c58afade2071caca068c46)

2024-07-25 17:14 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +since the sender can choose what event will be sent once expired.
I've added an explicit section on https://github.com/matrix-org/matrix-spec-proposals/blob/toger5/expiring-events-keep-alive/proposals/4140-delayed-events-futures.md#compatibility-with-cryptographic-identities

Furthermore, the proposal has changed a lot since these comments.

If there are any clarifications needed in relation to cryptographic identities I suggest adding them to https://github.com/matrix-org/matrix-spec-proposals/blob/toger5/expiring-events-keep-alive/proposals/4140-delayed-events-futures.md#compatibility-with-cryptographic-identities directly.

2024-07-25 17:30 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +    **futures get invalidated and the associated timers are stopped**.
I've incorporated the suggestion of not having a `send` action and instead doing a `cancel` followed by new send in [`e7d0986`](https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/e7d09863e92538b891f5152ab02cc955f8f419e8).

I've added a clarification on why this only applies to state events in [`e1b460a`](https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/e1b460a2663ed14c8efbedca26b297c48cbf0030).

2024-07-25 17:36 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +    },
I've clarified what the body/content field contains in [`114da1e`](https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/114da1e31e753722a7a0643b478b9f63dbdd5389).

The `GET` response format has also evolved significantly and I believe incorporates all the feedback here.

n.b. it no longer exposes the full `path` and instead does the constituent fields.

2024-07-25 17:54 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +## Alternatives
I've captured what I think is the essence of this thread in [`4a2ca48`](https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/4a2ca4800d6e1f0debad654a8812d2e7ffc1bbd8).

2024-07-25 17:55 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +
I've added all of these to the alternatives section in [`4a2ca48`](https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/4a2ca4800d6e1f0debad654a8812d2e7ffc1bbd8).

2024-07-25 18:05 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +
I've incorporated this in to [`37979cd`](https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/37979cd47c3a3e919c35cf4b22477478b9169290).

2024-07-25 18:13 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +that uses room messages to communicate the call state. However, it only allows for calls with two participants.
> Do we need this context?

I think it is helpful so I'm going to leave it in.

> @hughns those are marked as outdated but i think parts of it is still open?

I have incorporated most unresolved conversations into the MSC including the outdated ones. There are still a few more to go.

2024-08-02 13:53 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +So, unless the delayed event is updated beforehand, the event will be sent after `running_since` + `delay`.
Alternative names are noted in [`8523ed4`](https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/8523ed416fbe3db09cf3031cacf4feb3f1be2ee1)

2024-08-02 14:06 UTC, hughns commented on proposals/4140-delayed-events-futures.md
> +## Potential issues
I believe this thread can be resolved because:

1. MSC3277 is now included in the alternatives section
2. The MSC has been renamed and wording clarified that delayed events can be cancelled

2024-08-05 20:19 UTC, ara4n commented on proposals/4140-delayed-events-futures.md
> +The client can then periodically restarts the timer whilst it is running. If the client is no longer running or able
```suggestion
The client can then periodically restart the timer whilst it is running. If the client is no longer running or able
```

2024-08-05 20:27 UTC, ara4n commented on proposals/4140-delayed-events-futures.md
> +  - Use Future events with a 10s timeout to send the disconnected from call
references to futures & /update_future are presumably stale now?

2024-08-09 16:14 UTC, anoadragon453 commented on proposals/4140-delayed-events-futures.md
> +## Use case specific considerations
This feature could also be useful for temporary mutes/bans/kicks, temporary invites, etc.

2024-09-06 19:13 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +  - `transaction_id` - Optional. The transaction ID of the delayed event if it is a regular (non-state) event.
What's the value in returning the transaction ID?  (Pinging @hughns who wrote [the commit that added it](https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/772590f6bac61bd026e8a60dc055b76637cce8f7))

If it's to help clients distinguish between multiple delayed events for the same room + event type + content + send time, delay IDs are already unique and can be used for that purpose instead.

If it's to help clients remember which transaction IDs they already used for delayed event requests, AIUI clients are already supposed to keep track of the transaction IDs they used for each CS-API endpoint, making it redundant to return here.

So unless there's some other purpose for it, I propose removing the transaction ID from this response.

2024-09-11 15:15 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +  - `transaction_id` - Optional. The transaction ID of the delayed event if it is a regular (non-state) event.
Thanks! Reverted by 883e6b5d

2024-09-11 16:18 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +have been scheduled to send.
We should be more explicit here that its only the delayed events that have been scheduled by this user.
Currently this is only mentioned implicitly here:
> For use cases where the existence of a delayed event is also of interest for other room members,
(e.g. self-destructing messages) it is recommended to include this information in the original/affected event itself.

2024-09-11 16:56 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +pair that could be overwritten.
This might not be the best way to treat this. Here are my reasons why:
 - It is very easy to emulate this behavior by just cancelling the delayed event before sending a new state event.
 - In the matrixRTC spec I would like to argue that the order should be: send the delayed leave event FIRST and afterwards the active membership event. This guarantees that only expiring call memberships will be sent.
 - I would like to replace this section with:

 ```suggestion
#### State which is effected by delayed events will be marked in the unsigned field

If a state event is sent for a state key where there is already a delayed event scheduled the homeserver will add a:
`has_delayed_overwrite: true` property to the unsigned section of the state event.

This is not required if the delayed event is received after a normal state event.

This allows client to check if a state event is temporal: `has_delayed_overwrite: true`.
`m.call.member` events for instance will only be valid if they are temporal (It allows the receiving clients to evaluate if the sending client did not forget to schedule the delayed leave event.)
```

2024-09-11 17:25 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +pair that could be overwritten.
> * It is very easy to emulate this behavior by just cancelling the delayed event before sending a new state event.

This isn't true for state that can be set by other users, who don't have the option to cancel (or even know about) delayed state from someone else.

> * In the matrixRTC spec I would like to argue that the order should be: send the delayed leave event FIRST and afterwards the active membership event. This guarantees that only expiring call memberships will be sent.

This is a good idea, but I believe it will work regardless of what the behaviour is for overwritten delayed state.

2024-09-11 17:42 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +have been scheduled to send.
Good point.  caece4d6

2024-09-18 18:05 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +page size.
This should also define how the response should order the returned delayed events, lest the paginated results are jumbled & difficult to navigate through.

I propose sorting in order of increasing send time, i.e. `running_since` + `delay`.

2024-09-19 13:03 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +DAG. This implies a delayed event can fail if it violates power levels at the time the delay passes.
Should users be notified of delayed events that hit power level failures (or any 400-class error) upon being sent?

If so, perhaps delayed event send failures can be included in `/sync` responses, for clients to handle however they like.

If not, then this spec should make it explicit that delayed event send failures are effectively unhandled.

2024-10-01 12:03 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +DAG. This implies a delayed event can fail if it violates power levels at the time the delay passes.
That is a really good comment.
Adding it to the sync response Sounds as if we would need to introduce a place for error messages there. Which  be a very new concept I think.

What about adding it to the get delayed events endpoint.
We don't known if the client will be online if the failiour occurs so it is a very async check for errors anyways so making it part of a request does not sound too bad.
I don't know how to remove errors from the get delayed events list. Maybe as soon as they are fetched once they get removed?

Is that an issue if there are more clients getting futures?

2024-10-01 13:53 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +DAG. This implies a delayed event can fail if it violates power levels at the time the delay passes.
I added this into the GET endpoint.

2024-10-01 17:48 UTC, TheArcaneBrony commented on proposals/4140-delayed-events-futures.md
> +the event is sent immediately as normal.
Would it be possible to support setting the absolute target time rather than relative?
I was thinking of possibly using this as a "hack" to make sure a bunch of state event changes are batched in a single federation transaction by scheduling them at a single point in time ~5-10 seconds in the future. (eg. a moderation bot doing wildcard kicks/bans, or redacting tens if not hundreds of spam messages, this would allow for far higher event throughput and reduce federation overhead, where the bot may already be exempted from rate limits)

Just a thought, no intent to block this MSC.

2024-10-01 19:45 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +pair that could be overwritten.
We concluded that it is fine as it is:
 - There are examples where this behavior is confusing:
     - Pinned messages: I want to pin message a in a week. Now it would override all pins done until that point in time.
 - its hard to come up with good example why we don't want the delay to get canceled if the state (with same key/type) changes
 - The main reaosn this was brought up is to make it more similar to what we do with room events.
      - Once can think of state sending of "applying a diff" since the diff depends on the previous state scheduling a diff is not possible once the initial value of the diff changes.

2024-10-01 19:50 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +the event is sent immediately as normal.
The federation overhead should be the same, because the same amount of content (in your case, the moderation actions) will be sent in the request whether they're delayed or immediate events.

Unless you meant something else?

2024-10-04 11:00 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +## Use case specific considerations
Added this to the "Use case specific considerations" section.

2024-12-28 14:04 UTC, anoadragon453 commented on proposals/4140-delayed-events-futures.md
> +DAG. This implies a delayed event can fail if it violates power levels at the time the delay passes.
Would an event failure be something that a client needs to act upon? If so, the client would need to continuously poll this endpoint, which is starting to feel a lot like `/sync`...

2025-02-25 14:15 UTC, spaetz commented
Given element-call is the default VOIP solution in EX clients, and I CONSTANTLY have to help people to get calls unstuck (so often that I had to write up instructions on how toresolve them at https://sspaeth.de/2025/02/how-to-resolve-stuck-matrixrtc-calls/ :-).
So it would be a blast to get this one moving again. Thanks for considering.

2025-04-15 15:28 UTC, turt2live commented
MSCs proposed for Final Comment Period (FCP) should meet the requirements outlined in the [checklist](https://github.com/matrix-org/matrix-spec-proposals/blob/main/MSC_CHECKLIST.md) prior to being accepted into the spec. This checklist is a bit long, but aims to reduce the number of follow-on MSCs after a feature lands. 

SCT members: please check off things you check for, and raise a concern against FCP if the checklist is incomplete. If an item doesn't apply, prefer to check it rather than remove it. Unchecking items is encouraged where applicable.

Checklist:
- [ ] Are [appropriate implementation(s)](https://spec.matrix.org/proposals/#implementing-a-proposal)
  specified in the MSC’s PR description?
- [ ] Are all MSCs that this MSC depends on already accepted?
- [ ] For each new endpoint that is introduced:
  - [ ] Have authentication requirements been specified?
  - [ ] Have rate-limiting requirements been specified?
  - [ ] Have guest access requirements been specified?
  - [ ] Are error responses specified?
    - [ ] Does each error case have a specified `errcode` (e.g. `M_FORBIDDEN`) and HTTP status code?
      - [ ] If a new `errcode` is introduced, is it clear that it is new?
- [ ] Will the MSC require a new room version, and if so, has that been made clear?
  - [ ] Is the reason for a new room version clearly stated? For example,
          modifying the set of redacted fields changes how event IDs are calculated,
          thus requiring a new room version.
- [ ] Are backwards-compatibility concerns appropriately addressed?
- [ ] Are the [endpoint conventions](https://spec.matrix.org/latest/appendices/#conventions-for-matrix-apis) honoured?
  - [ ] Do HTTP endpoints `use_underscores_like_this`?
  - [ ] Will the endpoint return unbounded data? If so, has pagination been considered?
  - [ ] If the endpoint utilises pagination, is it consistent with
    [the appendices](https://spec.matrix.org/v1.8/appendices/#pagination)?
- [ ] An introduction exists and clearly outlines the problem being solved.
      Ideally, the first paragraph should be understandable by a non-technical audience.
- [ ] All outstanding threads are resolved
  - [ ] All feedback is incorporated into the proposal text itself, either as a fix or noted as an alternative
- [ ] While the exact sections do not need to be present,
  the details implied by the proposal template are covered. Namely:
  - [ ] Introduction
  - [ ] Proposal text
  - [ ] Potential issues
  - [ ] Alternatives
  - [ ] Dependencies
- [ ] Stable identifiers are used throughout the proposal, except for the unstable prefix section
  - [ ] Unstable prefixes [consider](README.md#unstable-prefixes) the awkward accepted-but-not-merged state
  - [ ] Chosen unstable prefixes do not pollute any global namespace (use “org.matrix.mscXXXX”, not “org.matrix”).
- [ ] Changes have applicable [Sign Off](CONTRIBUTING.md#sign-off) from all authors/editors/contributors
- [ ] There is a dedicated "Security Considerations" section which detail
  any possible attacks/vulnerabilities this proposal may introduce, even if this is "None.".
  See [RFC3552](https://datatracker.ietf.org/doc/html/rfc3552) for things to think about,
  but in particular pay attention to the [OWASP Top Ten](https://owasp.org/www-project-top-ten/).

2025-07-08 15:33 UTC, turt2live reviewed
sorry for the massive review - this is editorial stuff that was picked up while reviewing the [checklist](https://github.com/matrix-org/matrix-spec-proposals/pull/4140#issuecomment-2806245590) for the MSC. Where possible, I've added suggestions to make resolution a bit easier/faster (hopefully). 

After the MSC is ready for re-review, let us know in the [SCT Office](https://matrix.to/#/#sct-office:matrix.org) and we'll get some technical content reviews going, including a push towards FCP.

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +  So the scheduled event might change it in an undesired way."}
```suggestion
{
  "outcome": "cancel",
  "reason": "error",
  "errorcode": "M_CANCELLED_BY_STATE_UPDATE",
  "error": "The delayed event did not get send because a different user updated the same state event. So the scheduled event might change it in an undesired way."
}
```

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +  }
```suggestion
{
  "errcode": "M_UNKNOWN",
  "org.matrix.msc4140.errcode": "M_CANCELLED_BY_STATE_UPDATE",
  "error": "The delayed event did not get send because a different user updated the same state event. So the scheduled event might change it in an undesired way."
}
```

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +  }
```suggestion
{
  "errcode": "M_CANCELLED_BY_STATE_UPDATE",
  "error": "The delayed event did not get send because a different user updated the same state event. So the scheduled event might change it in an undesired way."
}
```

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +the event is sent immediately as normal.
A later MSC may introduce an absolute timestamp, but I think for this proposal it's best to focus on just relative timestamps. Servers already internally do batching due to internal processing time, so the outbound transaction may still have more than one event. 

It's also possible that a homeserver could bucket delays so they all land in the same 100ms window, for example.

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +`delay_id` field (omitting the `event_id` as it is not available):
```suggestion
If a `delay` is provided, the homeserver schedules the event to be sent with the specified delay and responds with an
opaque `delay_id` field (omitting the `event_id` as it is not available):
```

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +and a body with a Matrix error code `M_MAX_DELAY_EXCEEDED` and the maximum allowed delay (`max_delay` in milliseconds).
```suggestion
and a body with a new Matrix error code `M_MAX_DELAY_EXCEEDED` and the maximum allowed delay (`max_delay` in milliseconds).
```

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +The homeserver **may** apply a limit on the maximum number of outstanding delayed events in which case the Matrix error code
```suggestion
The homeserver **may** apply a limit on the maximum number of outstanding delayed events in which case a new Matrix error code
```

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +  - `restart` - Restart the timeout of the delayed event.
```suggestion
  - `restart` - Reset the send time to be `now + original_delay`.
```

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +  - `send` - Send the delayed event immediately.
```suggestion
  - `send` - Send the delayed event immediately instead of waiting for the delay time to be reached.
```

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +to be managed.
From the checklist:

* What errors are returned if the client calls `action=send` twice?
* What if the client tries to `cancel` an already-sent event?
* Can this endpoint be rate limited? (how often can a caller `restart` the delay? or, how often can a client go through the delay->cancel loop?)
* Should there be a transaction ID on this endpoint? The case being a client tries to `send` the event, has a network issue which prevents them seeing a 200 OK, retries, gets error for "already sent". 
  * An alternative may be to have the endpoint return information about what happened instead of making it a transaction. For example, when `send` is called, return `200 OK` with the `event_id` *always*, even on subsequent calls. Similarly for `cancel`: just a 200 OK all the time. `restart` could return the new estimated send time so a client can inspect it to realize that the event would be sent too late and therefore needs to cancel and schedule a new event.
* Is this endpoint available to guest accounts?

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +all the delayed events owned by the requesting user that have been scheduled to send, have been sent, or failed to be sent.
From the checklist: 

* Can these endpoints be rate limited?
* Are these endpoints available to guest accounts?

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +      of the full event after sending.
this appears to describe that it returns "events", but it's actually returning metadata that has some specific event fields. It may be beneficial to either return real events (moving things like `delay_id` to `unsigned`) or rename `delayed_events` to something like `scheduled` for clarity to the caller.

Similar applies to the endpoint below.

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +#### On push
Discussed out of band: It may be beneficial to move this section out to a dedicated MSC when/if the functionality is needed rather than delay (hah) the MSC behind early proof of implementation here.

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +DAG. This implies a delayed event can fail if it violates power levels at the time the delay passes.
the client can't really do anything about it, so they should use this API with the expectation of failure I think. It might be enough to state that in the MSC/eventual spec so clients aren't surprised by it.

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +would be used.
it'd probably be scoped to being allowed to send certain event types without delay, so when the SFU determines the user has dropped, it can send the event itself at that time.

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +of an event including the `origin_server_timestamp` as defined in [this list](https://spec.matrix.org/v1.10/rooms/v11/#client-considerations)
```suggestion
of an event including the `origin_server_ts` as defined in [this list](https://spec.matrix.org/v1.10/rooms/v11/#client-considerations)
```

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +duration computation), the `event_id` cannot be computed when using the `send` endpoint before the delayed event has resolved.
```suggestion
Since the `origin_server_ts` may change due to re-scheduling the event's send time, the event ID cannot be relied upon as it would also change.
```

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +Servers **should** impose a maximum timeout value for delay timeouts of not more than a month.
Discussed out of band: It appears the implementation doesn't do this, which is fine, but adding rationale either here or to the Synapse docs as to why limiting to more than a month is a bad idea would be good (or, remove this line and leave it up to implementations to figure out).

2025-07-08 15:33 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +mitigate this risk.
```suggestion
This has the risk that this feature could be used by a malicious actor to circumvent existing rate limiting measures which
corresponds to the [High Volume of Messages](https://spec.matrix.org/v1.11/appendices/#threat-high-volume-of-messages)
threat. The homeserver **should** apply rate-limiting to both the scheduling of delayed events and the later sending to
mitigate this risk, as well as limiting the number of scheduled events a user can have at any one time.
```

2025-07-08 15:37 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +  So the scheduled event might change it in an undesired way."}
I'm also realizing that `error` being a nested object may be intentional here, so the fix to the diff highlighter may be:

```suggestion
{
  "outcome": "cancel", 
  "reason": "error", 
  "error": {
    "errorcode": "M_CANCELLED_BY_STATE_UPDATE",
    "error": "The delayed event did not get send because a different user updated the same state event. So the scheduled event might change it in an undesired way."
  }
}
```

2025-07-09 12:00 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +to be managed.
I will start with answering these here. Then think about how to incorporate this best in the MSC text:

> What errors are returned if the client calls action=send twice?

Not Found (once the delayed event is finalized, the delayd id will be removed from the pending list and anything related with that delayed event will result in not found)

> What if the client tries to cancel an already-sent event?

Not Found error response

>Can this endpoint be rate limited?

We considered a rate limit. But the operations are very lightweight:
 - restart -> bumps one timestamp to a new value
 - cancle -> deletes one delayId
 - send -> searches for one delayId in the delayed events table (sending is the normal send procedure that is already rate limited)
So they are almost comparable computation wise to the rate limit logic.

> how often can a caller restart the delay?

No limits. There is no concern about restarting. Its very light weight (bump one ts) and there is no additional power gained by postponing the event more. If a client is online to postpone an event they can do more "harmful" things with other endpoints.
Should there be a transaction ID on this endpoint? The case being a client tries to send the event, has a network issue which prevents them seeing a 200 OK, retries, gets error for "already sent".

>how often can a client go through the delay->cancel loop?

Also no limit. But this is a more interesting case. Each loop iteration will result in one db insert/deletion. I am not sure if this is comparable to the computation needed to check if a requst is rate limited (where we also need to save the last call). If this is significantly higher this needs a rate limit. The easist probably would be the schedule of delayed events.


> Is this endpoint available to guest accounts?

Yes it would be good if guest accounts could use delayed events. No description is required to what happens if an account gets deleted. The permission rules when the delayed event gets send will be evaluated on send so an event from a deleted guest account will never reach the dag. Homeservers can do this calculation on account creation to save db storage.


> Should there be a transaction ID on this endpoint? The case being a client tries to send the event, has a network issue which prevents them seeing a 200 OK, retries, gets error for "already sent".
> - An alternative may be to have the endpoint return information about what happened instead of making it a transaction. For example, when send is called, return 200 OK with the event_id always, even on subsequent calls. Similarly for cancel: just a 200 OK all the time. restart could return the new estimated send time so a client can inspect it to realize that the event would be sent too late and therefore needs to cancel and schedule a new event.

I do not understand the solution here. How can cahnging the response help in the case where a user does not see the response due to a network issue.

> a network issue which prevents them seeing a 200 OK, retries, gets error for "already sent".

This sounds okay to me.

2025-07-09 12:04 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +all the delayed events owned by the requesting user that have been scheduled to send, have been sent, or failed to be sent.
(Again) summarizing thoughts here first:

> Can these endpoints be rate limited?

Yes those should be rate limited. The response can be larger and I expect the server to not cache the json so a serialization step will happen with each request.

> Are these endpoints available to guest accounts?

Yes matrixRTC might be interesting to be available for guest accounts -> delayed events should also be

2025-07-09 12:34 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +      of the full event after sending.
I prefer renaming it to sth like scheduled that is what it is in the end. There is no event_id so it also is not really an event.

2025-07-09 13:51 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +DAG. This implies a delayed event can fail if it violates power levels at the time the delay passes.
> Would an event failure be something that a client needs to act upon? If so, the client would need to continuously poll this endpoint, which is starting to feel a lot like /sync...

A good client implementation would also know about its delayed events. If it is important to know the outcome they can anticipate the time when the finalized is available via the get endpoint and can get the data only if required for an immediate response.

2025-07-09 13:57 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +would be used.
Both work. The advantage here is that a scoped token to only manage already send and signed delayed events is "very" save.
If we allow the SFU to send staate events (even if scoped to one type and room) is already a bit much. The SFU also does not need to be a trusted instance (The MatrixRTC spec is designed so it would break but it would not be a vounerablility if the SFU is malicious. It cannot even inject abusive content into the call since the source of truth is the room state.)

Additionally state events should be signed (or even better encrypted) to really make MatrixRTC as secure as possible. Then the SFU could not send a signed leave event but the delayed delegation still would work.


Do we want this discussion to be evaluated in the MSC text?

2025-07-09 14:33 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +the event is sent immediately as normal.
I am resolving this issue since theis is not a fundamental issue with this MSC but a simplification for specific cases that deserves its own MSC with dedicated justifications why this is needed.

Feel free to repoen the discussion in case this does not sound appropriate.

2025-07-10 11:56 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +all the delayed events owned by the requesting user that have been scheduled to send, have been sent, or failed to be sent.
Fixed in: c25e5a3970f1b042246356f8939bbb2f46f05250

2025-07-10 11:58 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +to be managed.
solved in: 96f9063cf51598ad69e15cdecb7338d701eec1c3

2025-07-10 12:23 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +#### On push
moved out to https://github.com/matrix-org/matrix-spec-proposals/pull/4309 in commit: 99b79bab8c9f80c9e747b720350459e39ba61b68

2025-07-10 14:31 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +Servers **should** impose a maximum timeout value for delay timeouts of not more than a month.
This has been adressed in: bf5df9b002215cbcf8518a8c1f0afe0a66559066

2025-09-09 04:51 UTC, turt2live requested changes
Overall this is very close: largely just editorial things remain, to check boxes on the checklist.

I'm not quite comfortable putting this forward for FCP yet with MSC3757 possibly causing VoIP to steer down a non-event path - once (and if) that discussion settles in favour of event-based VoIP, I'll put this forward for FCP if it hasn't been done already.

2025-09-09 04:51 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +The ["reliability requirements for the room state"](https://github.com/matrix-org/matrix-spec-proposals/blob/toger5/matrixRTC/proposals/4143-matrix-rtc.md#reliability-requirements-for-the-room-state)
editorial: this link will break if MSC4143 gets accepted. Citing by section name, without link, and still continuing to link to the PR later in the sentence is recommended.

2025-09-09 04:51 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +the event is sent immediately as normal.
```suggestion
- `delay` - Optional number of positive non-zero milliseconds the homeserver should wait before sending the event. If no `delay` is provided,
the event is sent immediately as normal.
```

2025-09-09 04:51 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +the event is sent immediately as normal.
Servers should also be able to round the delay to buckets, as otherwise the server needs to run timers with millisecond accuracy, which isn't possible at scale. 

Language-wise such a limitation would be something like "The server MAY round the delay up to a maximum of 30 seconds away from the request".

2025-09-09 04:51 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +The server will return a `M_NOT_FOUND` error.
... in what circumstances?

2025-09-09 04:51 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +all the delayed events owned by the requesting user that have been scheduled to send, have been sent, or failed to be sent.
unresolving: guest access requirements aren't declared.

2025-09-09 04:51 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +to be managed.
> > Should there be a transaction ID on this endpoint? The case being a client tries to send the event, has a network issue which prevents them seeing a 200 OK, retries, gets error for "already sent".
> > 
> > * An alternative may be to have the endpoint return information about what happened instead of making it a transaction. For example, when send is called, return 200 OK with the event_id always, even on subsequent calls. Similarly for cancel: just a 200 OK all the time. restart could return the new estimated send time so a client can inspect it to realize that the event would be sent too late and therefore needs to cancel and schedule a new event.
> 
> I do not understand the solution here. How can cahnging the response help in the case where a user does not see the response due to a network issue.

Transaction IDs are used on `/send` to ensure the caller gets the same response for the same input, performing the action exactly once. Given this is a high traffic endpoint, potentially, it's similarly possible for a caller to get a *different* answer given the same input in a way where they might not know what went wrong. Usually in these cases, a transaction ID can help.

2025-09-09 04:51 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +to be managed.
Guest access requirements are not declared in the MSC.

2025-09-09 04:51 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +The rate limits will be applied when evets are send after the delay times out (or when the event is send by calling `send`).
It feels important to allow this endpoint to be rate limited. The MSC doesn't have to (and probably shouldn't) specify what that rate limit is, but having the ability to prevent DoS attacks is important to a server.

2025-09-09 04:51 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +expensive as sending a rate limit error response.
This may not be possible in some server implementations, so we cannot specify it as a requirement.

2025-09-09 04:51 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +(When the server returns the `M_MAX_DELAYED_EVENTS_EXCEEDED` and the `M_MAX_DELAY_EXCEEDED` error)
We generally shy away from mandating specific implementation like "config". Instead, we simply say that servers MUST impose maximum values - how they do that is their concern.

2025-09-10 18:23 UTC, turt2live commented
~~This MSC is blocked on conversations around possibly using non-state-events for VoIP becoming resolved.~~ It is required even if non-state-events are used.

2025-09-24 14:20 UTC, toger5 commented
> This MSC is blocked on conversations around possibly using non-state-events for VoIP becoming resolved.

We still need those regardless of swtiching to a non-state-events approach (sticky-events)

There is an implementation for voip + sticky-events: https://github.com/matrix-org/matrix-js-sdk/pull/5017
That requires delayed events.

2025-09-24 17:35 UTC, turt2live commented
This is unblocked: MSC3757's replacement won't end up impacting the 2.0 stream for this MSC.

2025-09-26 10:49 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +all the delayed events owned by the requesting user that have been scheduled to send, have been sent, or failed to be sent.
99b79bab8c9f80c9e747b720350459e39ba61b68 appears to have declared guest access already in July?

2025-09-26 10:51 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +to be managed.
Resolving this as a duplicate of the previous guest access thread https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r2331981720

2025-09-26 11:04 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +The server will return a `M_NOT_FOUND` error.
I assume it means when the delay ID is unknown, but not 100% certain

2025-09-26 11:05 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +expensive as sending a rate limit error response.
I'm not even sure what that sentence is trying to say, so I just removed it while rewording the whole paragraph to allow ratelimiting

2025-09-26 11:54 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +to be managed.
I think the always 200 method makes more sense than new transaction IDs. The return value doesn't seem to be defined at all right now 🤔

2025-09-26 12:05 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +to be managed.
`restart` probably already works fine, `cancel` can turn into a 404 which is also fine, so just `send` needs to be defined to not fail on resend

Looks like there's no return value currently. Would be nice if `send` returned the event id and `restart` the new time, but maybe those aren't absolutely necessary

2025-09-26 12:12 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +DAG. This implies a delayed event can fail if it violates power levels at the time the delay passes.
I've recorded `/sync`ing failed events as an alternative. It can be added in a later MSC if necessary, I don't think anyone wants to implement it right now

2025-09-26 12:16 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +would be used.
This is already an alternative rather than a part of the MSC, so we probably don't need to record alternatives for alternatives, especially since a token for sending without delay isn't related to delayed events at all. It can be discussed in more detail when someone actually proposed scoped tokens

2025-09-26 12:25 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +that happened while sending the event (e.g. `M_FORBIDDEN` if the user doesn't have permission to send the event).
This part probably hasn't been implemented because I made it up just now (the error part might have been implemented, but send 200 on retry probably hasn't)

2025-09-26 14:25 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +that happened while sending the event (e.g. `M_FORBIDDEN` if the user doesn't have permission to send the event).
Should `cancel` always return 200 on retry as well?
https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r2382210026
> `cancel` can turn into a 404 which is also fine

What makes it fine, while it was not fine for `send`?

2025-09-26 14:35 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +that happened while sending the event (e.g. `M_FORBIDDEN` if the user doesn't have permission to send the event).
Cancel means you want the scheduled event to not be sent, the `M_NOT_FOUND` code means it won't be sent

`send` can't return a generic error for already-sent events, because that could be confused with the send failing. It could also have a special error code that's only used to mean it was already sent successfully, but just returning 200 seems easier (especially if someone makes it return the event ID in the future).

2025-09-30 17:02 UTC, richvdh reviewed
sorry for the delay on these comments, I found them in github

2025-09-30 17:02 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +opaque `delay_id` field (omitting the `event_id` as it is not available):
we should specify a grammar for `delay_id`. What characters are allowed, what is its max length?

2025-09-30 17:02 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +The rate limits will be applied when evets are send after the delay times out (or when the event is send by calling `send`).
```suggestion
The rate limits will be applied when events are sent after the delay times out (or when the event is sent by calling `send`).
```

2025-09-30 17:02 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +because scheduling of the events itself is rate limited this is not causing issues.
I don't really understand what this sentence means

2025-09-30 17:02 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +The server will return a `M_NOT_FOUND` error.
this needs clarifying: presumably it only applies once the delayed event has been sent?

2025-09-30 17:02 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +The server will return a `M_NOT_FOUND` error.
Also: should it be a 404 HTTP error?

2025-09-30 17:02 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +    - `reason`: `"error"|"action"|"delay"`
these `reason`s could do with clarification. What do `action` and `delay` mean?

2025-09-30 17:02 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +    - `outcome`: `"send"|"cancel"`
what if there was an error when sending the event?

2025-09-30 17:02 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +New authenticated client-server API endpoints `GET /_matrix/client/v1/delayed_events/scheduled` and
There is a namespace clash here, between `/_matrix/client/v1/delayed_events/scheduled` and `/_matrix/client/v1/delayed_events/{delay_id}`.

I'd suggest combining the two pagination endpoints, as `GET /_matrix/client/v1/delayed_events`, and allow a `state=scheduled|finalised` query-parameter.

2025-09-30 17:02 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +New authenticated client-server API endpoints `GET /_matrix/client/v1/delayed_events/scheduled` and
I also think it might be worth having a `GET /_matrix/client/v1/delayed_events/{delay_id}` endpoint, though if there's no pressing need for this, it can always be added later.

2025-09-30 17:02 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +- _new state event_ followed by timeout for _delayed event_: the _new state event_ will cancel the outstanding _delayed event_.
this seems to forget that the two events can be sent "concurrently".

2025-09-30 17:02 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +They can just cancel and check the events manually using the `/delayed_events` and the `/delayed_events/scheduled` endpoint.
given that it could be a different device that scheduled the delayed event, this feels fragile. Maybe it should only cancel delayed events scheduled by the same device?

2025-09-30 17:02 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +- `last_restart` - but this feels less clear than `running_since` for a delayed event that hasn't been restarted
did you consider returning the scheduled send time, rather than the start time of the timer?

2025-09-30 18:10 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +that happened while sending the event (e.g. `M_FORBIDDEN` if the user doesn't have permission to send the event).
How about making a retried `send` return 200 only for as long as the specified delayed event is retained by [`GET /_matrix/client/v1/delayed_events/finalised`](https://github.com/matrix-org/matrix-spec-proposals/blob/toger5/expiring-events-keep-alive/proposals/4140-delayed-events-futures.md#getting-delayed-events), and 404 afterwards?  This would also address the question of how long after a successful `send` that the server should remember the sent delayed event, for considering whether another `send` on its ID is a retry vs a new action on an unknown ID.

This could also be done for a retried `cancel`, as the cancellation status of delayed events is also retained by `/finalised`.

This way, a 4xx response to either action would mean "the requested action could not be done" (i.e. couldn't be sent, or couldn't be cancelled).

Something else to consider is what the response should be when trying to `send` a cancelled event / `cancel` a sent event / `restart` a sent/cancelled event, or when trying to do anything with a delayed event that failed to be sent.  Perhaps 409 Conflict is appropriate.

To summarize, the responses I'm proposing are:
- 200 for any `action` on a scheduled delayed event
- 200 for an `action` on a finalised delayed event whose `outcome` == the requested `action`, and whose `reason` != `"error"`
- 409 for the above, when `outcome` != the requested `action`, or `reason` == `"error"`
- 404 for any `action` on a delayed event that is neither scheduled nor finalised (i.e. not found, or out of retention)

2025-10-01 00:55 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +opaque `delay_id` field (omitting the `event_id` as it is not available):
Given that `delay_id`s aren't federated & are generated by the server, there doesn't need to be much restriction on their grammar.  This should be satisfactory: ba78cde1

2025-10-01 00:55 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +The rate limits will be applied when evets are send after the delay times out (or when the event is send by calling `send`).
This section has since been replaced, and the typos have not reappeared.

2025-10-01 00:55 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +because scheduling of the events itself is rate limited this is not causing issues.
This has since been replaced by:

> The primary point of rate limiting is event sending when the delay times out or the event is sent using the `send` action. However, servers can choose to rate limit the the management endpoints themselves as well if necessary.

i.e. the old text said to not apply rate limiting on bulk cancellations, whereas the new text says that even cancelling may be rate limited at the server's discretion.

2025-10-01 00:55 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +The server will return a `M_NOT_FOUND` error.
Yes, it should be 404 + `M_NOT_FOUND`.  The latter is the more expressive error (according to [the CS-API](https://spec.matrix.org/latest/client-server-api/#standard-error-response)), but there's no good reason to not also specify the HTTP response here as well.  c2587feb

2025-10-01 00:55 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +The server will return a `M_NOT_FOUND` error.
This has since been clarified with:

> The server will return a `M_NOT_FOUND` error if the `delay_id` is not recognized or was already canceled.

2025-10-01 00:56 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +    - `reason`: `"error"|"action"|"delay"`
10361658 adds explanations for these, and for `outcome` as well.

2025-10-01 00:56 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +    - `outcome`: `"send"|"cancel"`
10361658 makes this use `"cancel"` for errors or intentional cancellations, with `reason` clarifying which of the two happened.

2025-10-01 01:13 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +New authenticated client-server API endpoints `GET /_matrix/client/v1/delayed_events/scheduled` and
Good idea.  Since "state" is already a meaningful term in the spec, how about naming the query parameter "status"? 2afcebba

2025-10-01 01:21 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- _new state event_ followed by timeout for _delayed event_: the _new state event_ will cancel the outstanding _delayed event_.
By this, do you mean two concurrently-sent state events that cause a fork in the DAG?  If so, would state resolution decide which of those events "wins"?

2025-10-01 01:34 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +They can just cancel and check the events manually using the `/delayed_events` and the `/delayed_events/scheduled` endpoint.
That would require the lookup endpoint to also return the device ID of the original request, which it doesn't currently.  Besides, for state events that are associated with sending device, the sending device ID would (or should) be part of the state key, which clients could use to decide to cancel scheduled state events for the same/different device ID.

2025-10-01 01:38 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- `last_restart` - but this feels less clear than `running_since` for a delayed event that hasn't been restarted
Surprised that it's is absent.  Here it is now: 8c5b612f

2025-10-01 08:59 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +The `delay_id` is generated by the server. It SHOULD contain only valid non-surrogate Unicode codepoints except `:` and `NUL`, and MUST NOT exceed 255 bytes.
why excluding :, ooi?

255 bytes rather than characters, so emojis count as multiple bytes?

Honestly I'd suggest just using the opaque identifier grammar for consistency and to save thinking about these things

2025-10-01 08:59 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +opaque `delay_id` field (omitting the `event_id` as it is not available):
The spec does have a standard opaque ID grammar too: https://spec.matrix.org/v1.16/appendices/#opaque-identifiers

2025-10-01 09:05 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +`GET /_matrix/client/v1/delayed_events?status=finalised` allows clients to get a list of
This wording suggests that the `status` query-parameter is mandatory. Could you clarify whether it is or is not?

(I don't see any reason to make it mandatory, but YMMV)

2025-10-01 09:09 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +- _new state event_ followed by timeout for _delayed event_: the _new state event_ will cancel the outstanding _delayed event_.
Yes. So the _delayed event_ could end up "winning". It's unclear whether or not that is a problem in practice, but basically your assertion that "there is no race condition here" seems incorrect.

2025-10-01 09:18 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +They can just cancel and check the events manually using the `/delayed_events` and the `/delayed_events/scheduled` endpoint.
> That would require the lookup endpoint to also return the device ID of the original request

Why so? Isn't it up to the server to decide whether or not to cancel the event, and it doesn't need to go through the lookup endpoint to do so.

> Besides, for state events that are associated with sending device, the sending device ID would (or should) be part of the state key, which clients could use to decide to cancel scheduled state events for the same/different device ID.

The concern is more about state events that are *not* associated with a specific device.

To be honest with you, this whole "Delayed state events are cancelled by a more recent state event" mechanism feels a bit like a solution looking for an application. It's not clear to me that we've given much thought to exactly what the semantics should be. I'd be in favour of removing this bit for now, until it's clearer what we want to happen.

2025-10-01 12:18 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +opaque `delay_id` field (omitting the `event_id` as it is not available):
Thanks, I somehow missed that. 6afd0f3a

2025-10-01 12:18 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +The `delay_id` is generated by the server. It SHOULD contain only valid non-surrogate Unicode codepoints except `:` and `NUL`, and MUST NOT exceed 255 bytes.
I just copied this part from the grammar for room aliases. The opaque identifier grammar is a much better fit, though. 6afd0f3a

2025-10-01 14:06 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +`GET /_matrix/client/v1/delayed_events?status=finalised` allows clients to get a list of
Good point.  The default can be to return both scheduled & finalised events, and setting `status` can filter on one or the other.  This is also a good spot to filter on the `delay_id` to query for just a single event.

2025-10-01 14:44 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +They can just cancel and check the events manually using the `/delayed_events` and the `/delayed_events/scheduled` endpoint.
> To be honest with you, this whole "Delayed state events are cancelled by a more recent state event" mechanism feels a bit like a solution looking for an application. It's not clear to me that we've given much thought to exactly what the semantics should be. I'd be in favour of removing this bit for now, until it's clearer what we want to happen.

Agreed -- now that MatrixRTC will be using [Sticky Events](https://github.com/matrix-org/matrix-spec-proposals/pull/4354) for call membership signaling, there is (to my knowledge) no other feature that depends on delayed state events, so there is no pressing need to special-case them now.

2025-10-01 15:34 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +`GET /_matrix/client/v1/delayed_events?status=finalised` allows clients to get a list of
1359f2b6 & 59392f28

2025-10-01 15:35 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +They can just cancel and check the events manually using the `/delayed_events` and the `/delayed_events/scheduled` endpoint.
3efecea1

2025-10-01 15:36 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- _new state event_ followed by timeout for _delayed event_: the _new state event_ will cancel the outstanding _delayed event_.
The special-casing of delayed state events is now in the alternatives section (3efecea1). See https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r2394874916

2025-10-09 16:45 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- `finalised` max cached events: 1000
IMO this limit should be applied per-user.  Otherwise, a malicious user could purge other users' finalised events by scheduling & canceling enough delayed events of their own to surpass the global retention limit.

2025-10-09 16:50 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- `finalised` batch size: 10
Non-finalised events need a batch size, too.

2025-10-10 07:41 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- `finalised` max cached events: 1000
9db80580

2025-10-10 07:42 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- `finalised` batch size: 10
c19a394d

2025-10-13 09:51 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +  "scheduled": [
Looks like this is still called `delayed_events` in the Synapse implementation: https://github.com/element-hq/synapse/blob/v1.140.0rc1/synapse/rest/client/delayed_events.py#L103, should mention that in the unstable prefix section. It was renamed in https://github.com/matrix-org/matrix-spec-proposals/commit/904e3d6b2a969efaf47842c2de9deaed0ab8b3c7

2025-10-19 16:03 UTC, Half-Shot commented on proposals/4140-delayed-events-futures.md
> +A new authenticated client-server API endpoint at `POST /_matrix/client/v1/delayed_events/{delay_id}` allows scheduled events
To throw this on its head a bit, could we make this *unauthenticated* and instead make the delay_id a more secure random string. I have a fairly strong use case:

If I am building a RTC application and I want a backend service to be in control of whether one of my events expires, then I can pass my delayed event to the server and it can control the disconnect event on my behalf. Because the `delay_id` is scoped to one event that the user has already consented to sending, the auth doesn't really add much if the delay_id isn't trivally guessable.

The alternative to this is the backend service would need to get either my full token or a scoped access token (via as an as-of-yet unspec'd MSC) which adds some overhead.

2025-10-20 12:43 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +  "scheduled": [
e2af939e

That deviation (among others) is being addressed by https://github.com/element-hq/synapse/pull/19038.

2025-10-21 12:09 UTC, benkuly commented on proposals/4140-delayed-events-futures.md
> +### Not reusing the `send`/`state` endpoint
I would highly prefer that.
1. An endpoint should not return two completely different response types depending on the query parameter.
2. Sending a delayed event is a different action than sending an event and should be more explicit.

2025-10-21 12:09 UTC, benkuly commented on proposals/4140-delayed-events-futures.md
> +### Self-destructing messages
This is a really good use case, but I see a fundamental problem in this MSC: Delayed events are not passed down the sync. So even if one device sends a self destruction, other devices of the same account would not be notified about it in the sync. Therefore other devices would always need to poll `delayed_events`, which breaks the concept of having the Matrix sync and would unnecessary flood the homeserver with requests.

2025-10-21 12:09 UTC, benkuly commented on proposals/4140-delayed-events-futures.md
> +### Getting delayed events
This is a poll mechanism. In my opinion, we would need a push (sync) mechanism to take really advantage of this MSC and be able to introduce a bunch of new Matrix features based on it.

2025-10-21 13:22 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +### Self-destructing messages
I don't think there's any need to know about delayed events in that context. The sender creates the delay, other devices don't care. Beeper already implements disappearing messages like that.

2025-10-21 13:46 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +### Not reusing the `send`/`state` endpoint
Its about the send body bein equivalent in both requests.
Sticky events also take the exact same appraoch.

I think the opinion on this very much depends on your mental model of delayed events
 - they are normal event sending actions but with a configurable increase in latency (it will take the hs a little bit to send the event anyways, you can just further delay this manually)
 - This endpoint schedules sth that is not a matrix event yet. Its a new entity that eveutally becomes a matrix event.
 
 I like the first view on it since it makes it easier to justify how this is compatible with matrix and why this probably wont change anything fundamental (matrix already needs to be capable dealing with differen network delays)

2025-10-21 13:51 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +### Self-destructing messages
If this is just about the user experience and communicating your intent to only let this message life for X minutes, that seems like an easy addition in a new MSC. A content fieled: `"scheduled_redaction_ms"` could be used to share when you plan to let this message disappear and clients can render some UI around that.

This is off topic, but if a burn on read semantic (in a DM) is desired. one could even go as far as sharing a link with a scoped token that sends the delayed redaction. So once received the receiver can than delete the message by sending the redaction scheduled by the sender of the message.

What I am trying to say, this MSC supports all the fundamentals for a really good self-destruction implementation. I am not sure it needs fundamental changes, but maybe some metadata on top is reaquired to check of UX features.
But this MSC proposes the general delayed event logic and is not specific to self-destructing messages.

2025-10-21 13:57 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +### Getting delayed events
Similar to the above.
There even is a follow up msc moving this into the sync block.
But your comments implicitly ask the question who should be able to access the list of scheduled delayed events: "The sender" vs "All room members". Right now the idea is that only the sender knows about their schedueld delayed events. (A dag like federated data exachange is required to sync inforamtion to all room members on other homeservers so sharing a schedueld delayed event is not as trivial, there is a reason matrix writes things into a room dag.)

The current MSC only ever exposes the scheduled delayed events to the sender.
This also has privacy/security advantages.
Whenever it is desired to share shedued data with the room metadata in the conetent of antoher room event should be used.

This might be worth explicitly mentioning in the MSC.

I hope this approach makes sense and coveres all of the usecases you have in mind?

2025-10-21 14:37 UTC, benkuly commented on proposals/4140-delayed-events-futures.md
> +### Getting delayed events
I don't expect to share `delayed_events` between users, but between devices of the same user (like account data). If we don't want that, which is totally okay, do we want an endpoint to get all `delayed_events` on an account base.

The other problem I see is, that the MSC suggest a new endpoint for getting `delayed_events`. It is poll based. As far as I know in Matrix there is no other data structure, that needs polling. What is the use case to poll `delayed_events` instead of syncing them? Why this "downgrade" regarding the Matrix push-first principle.

2025-10-21 14:41 UTC, benkuly commented on proposals/4140-delayed-events-futures.md
> +### Not reusing the `send`/`state` endpoint
As an SDK developer, I prefer a type safe API. It would've been helpful to have this natively in Matrix instead making a workaround at the SDK level to get type-safety. At the end, I will provide a type safe API to the user anyway.

2025-10-21 14:46 UTC, benkuly commented on proposals/4140-delayed-events-futures.md
> +### Self-destructing messages
> other devices don't care

If that is the case, do we need the polling api GET `delayed_events`? (we could close this thread, because the other is regarding the same topic)

2025-10-21 15:07 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +### Getting delayed events
There is a follow up MSC to include it in sync (sorry that i confused user vs room delayed events sharing)
The "all devices for one user" push/sync based system has been moved to that msc: 
https://github.com/matrix-org/matrix-spec-proposals/pull/4309

The reason was to make this msc simpler.

It does only include finalized delayed events. So your point of syncing schedules to all devices via a push semantic is very valid.

What do you think about moving/discussing this functionality to the other MSC?

(It sadly is still in draft)

2025-10-21 15:19 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +### Self-destructing messages
Querying delayed events is necessary for other things like scheduled messages even though it's not needed for disappearing messages. Scheduled messages don't need a push mechanism, it's enough to be able to view and manage scheduled events when the user navigates to a specific view inside a room.

> If this is just about the user experience and communicating your intent to only let this message life for X minutes, that seems like an easy addition in a new MSC. A content fieled: "scheduled_redaction_ms" could be used to share when you plan to let this message disappear and clients can render some UI around that.

This is indeed how Beeper works (using a `com.beeper.disappearing_timer` object) and that'll probably be MSC'd at some point

2025-10-27 16:28 UTC, Half-Shot commented on proposals/4140-delayed-events-futures.md
> +A new authenticated client-server API endpoint at `POST /_matrix/client/v1/delayed_events/{delay_id}` allows scheduled events
We discussed this out of band and decided it was a good idea, right @fkwp ?

2025-10-27 16:47 UTC, Half-Shot commented on proposals/4140-delayed-events-futures.md
> +These endpoints are unauthenticated so that control over a particular delayed event may be
Rough implementation at https://github.com/element-hq/synapse/compare/hs/delayed-event-anonymous?expand=1

2025-10-27 17:55 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +A new authenticated client-server API endpoint at `POST /_matrix/client/v1/delayed_events/{delay_id}` allows scheduled events
061dd56

2025-11-14 15:01 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +These endpoints are unauthenticated so that control over a particular delayed event may be
This is now merged: https://github.com/element-hq/synapse/pull/19152

2025-11-19 02:10 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +`GET /_matrix/client/v1/delayed_events?status=finalised` allows clients to get a list of
> The default can be to return both scheduled & finalised events

On second thought, this complicates pagination, as it makes the response have to paginate two different item categories.

A possible solution is to take advantage of the fact that all scheduled delayed events have send times in the future, while finalised ones have send times in the past.  The first "page" of the response would include both scheduled & finalised delayed events whose send times are within an interval around when the lookup request was made, and would also return both a `next_batch` and `prev_batch` token for retrieving further scheduled or finalised delayed events, respectively.  Any "next" page would include only scheduled delayed events (since they are "next" in time) while any "previous" page would include only finalised ones (since they are "previous" in time).

If that is too much complexity, then there could simply be dedicated endpoints for looking up either scheduled delayed events or finalised ones.  This has the added benefit of each endpoint being able to support unique query parameters that are relevant only for their respective delayed event status (like filtering finalised delayed events by the value of their `outcome` property).

> [The combined endpoint] is also a good spot to filter on the `delay_id` to query for just a single event.

I'll walk back on this too, and will opt for having the `delay_id` as a path parameter [as was originally proposed](https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r2315944196) instead of a query parameter, because:
1. There is precedent in the CS-API for using a path parameter for the ID of a singular resource to look up.
2. Having a `delay_id` query parameter would suggest being able to specify it multiple times to look up multiple items, but this should have safeguards on how many items to allow looking up, to avoid absurdly long URLs or the need to paginate.  Getting that right is not really worth the effort, especially since a viable alternative to a multi-item lookup is to just do multiple single-item lookups.
3. Giving the `delay_id`-based lookup its own endpoint leaves room for it to be unauthenticated, just like the management endpoints now are, for the purpose of delegating control over specific delayed events to an external service.  If it shared the same endpoint as the status-based lookups, this would not be possible.

The only caveat is that if the status-based lookups were to be split into one endpoint per status, we'd be back [in the situation of needing to avoid a namespace clash](https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r2315944196) with a `delay_id`-based lookup endpoint at `GET /delayed_events/{delayId}`.  So, their paths could be something like `GET /delayed_events/by-status/[scheduled|finalised]` to satisfy that.

2025-11-19 02:37 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +that happened while sending the event (e.g. `M_FORBIDDEN` if the user doesn't have permission to send the event).
Actually, to further emphasize that retries are safe, how about using `PUT` for the `/send` and `/cancel` endpoints, instead of `POST`?

`/restart` would still have to use `POST` since it is not idempotent (as repeated requests push the send time further into the future).

2025-11-19 03:06 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +### Not reusing the `send`/`state` endpoint
Another point against reusing the `/send` & `/state` endpoints is that having the delay as a query parameter conflicts with the convention of query parameters being filters, not action options.

It also interferes with the transaction identifier, for [which the spec says](https://spec.matrix.org/v1.16/client-server-api/#transaction-identifiers):
> The homeserver should identify a request as a retransmission if the transaction ID is the same as a previous request, and the path of the HTTP request is the same.

If I'm reading that rule correctly, it means that a request with the same transaction ID as an earlier request, but with a different query string, is still treated as a retransmission.  That would make a `/send` or `/state` request with a `?delay=` potentially be treated as a retransmission of an earlier such request without a `?delay=`.

Using a dedicated endpoint could avoid this by specifying the delay as a top-level field of the request body, with the content of the delayed event moved down one level into an object:

```
PUT /_matrix/client/v1/rooms/{roomId}/send_delayed_event/{eventType}/{txnId}
{
  "delay": <delay_ms>
  "content": {
    "body": "hello",
    "msgtype": "m.text"
  }
}
```

2025-11-20 08:57 UTC, Half-Shot requested changes

2025-11-20 08:57 UTC, Half-Shot commented on proposals/4140-delayed-events-futures.md
> +- `finalised` - Required if the request has no `status` parameter, or sets it to `"finalised"`.
I think we agreed oob to drop finalised from this endpoint, so it only returns events due to be sent now. Perhaps for future proofing we can have `GET /_matrix/client/v1/delayed_events/scheduled`.

2025-11-20 08:57 UTC, Half-Shot commented on proposals/4140-delayed-events-futures.md
> +The endpoint accepts a query parameter of `delay_id=<delay_id>` to filter the response on delayed events with a matching ID.
I think we also said this should just be a `GET /_matrix/client/v1/delayed_events/{delay_id}`.

This *could* return a finalised event, although I feel like homeservers should be able to clear up old delay_ids from the database so I wouldn't make this a hard requirement.

2025-11-20 08:57 UTC, Half-Shot commented on proposals/4140-delayed-events-futures.md
> +- batch size: 10
I don't really understand the rationale for retaining finalised events to be honest, what's the use case?

2025-11-20 08:57 UTC, Half-Shot commented on proposals/4140-delayed-events-futures.md
> +The `delay_id` is an [opaque identifier](https://spec.matrix.org/v1.16/appendices/#opaque-identifiers) generated by the server.
It would also be nice if the delay_id ended up in the unsigned content of the event down sync so your client could identify which event mapped to which delay. I don't know how important this is, but surely it would be the nice thing t odo.

2025-11-20 15:09 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- `finalised` - Required if the request has no `status` parameter, or sets it to `"finalised"`.
See https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r2540226430 for some brainstorming on this.

2025-11-20 15:09 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +The endpoint accepts a query parameter of `delay_id=<delay_id>` to filter the response on delayed events with a matching ID.
Yes, this endpoint is mentioned at the halfway mark of https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r2540226430

2025-11-20 15:16 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- batch size: 10
It's less about retaining them & more about purging them, i.e. about setting a limit on how many may be retained.  Server implementations will inevitably need some purging scheme lest they end up storing an unbounded number of finalised events, but the benefit of standardising purge rules (and configs for them) is to give server implementers a starting point / baseline of how it ought to be done, as opposed to each having to define its own scheme (which may very well converge to the rules proposed here).

2025-11-20 15:22 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +The `delay_id` is an [opaque identifier](https://spec.matrix.org/v1.16/appendices/#opaque-identifiers) generated by the server.
That's a good idea, and would help with at least one edge case in Synapse that I can think of :slightly_smiling_face:  What makes this possible is that the need to keep a `delay_id` secret (as it currently doubles as a token for having control over it) goes away once a delayed event is sent.

The only "information leak" is that others will be able to identify when an event was sent with a delay.  IMO that is not too bad (and maybe even useful) but perhaps some users would prefer not to expose that.

2025-11-25 18:30 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +that happened while sending the event (e.g. `M_FORBIDDEN` if the user doesn't have permission to send the event).
The conclusion of an OOB discussion about this was to keep these endpoints on `POST`, as the semantics of a `PUT` endpoint are more for updating a target resource with a particular representation, whereas `POST` is better suited for RPC-style calls, which these management actions are.

2025-12-16 17:44 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +### Not reusing the `send`/`state` endpoint
This also reveals another opportunity: sending delayed state shouldn't be idempotent per state key like sending non-delayed state is, because it's a _deferred request to set state_, as opposed to an immediate action of applying a desired state, meaning that repeated requests should each cause a new delayed event to be scheduled.  So, a `/send_delayed_state` endpoint should use `POST`, or `PUT` with a transaction ID, just like the `/send_delayed_event` endpoint would.

I also prefer names of `/delayed_send` and `/delayed_state` to shorten the paths a bit.

I'll write a proper commit for all that once I return from holidays.

2025-12-16 18:57 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +### Not reusing the `send`/`state` endpoint
> I also prefer names of /delayed_send and /delayed_state to shorten the paths a bit.

If the content is being wrapped anyway in the request body, it could be a single `PUT /delayed_event/{txnId}` endpoint for both with a body like this:

```json5
{
  "delay": 1234,
  "type": "m.example",
  "state_key": "", // omitted for non-state
  "content": {
    ...
  }
}

2025-12-17 05:49 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +### Not reusing the `send`/`state` endpoint
Oh, that is very nice.

2026-01-05 14:51 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +### Not reusing the `send`/`state` endpoint
1618990

2026-01-22 14:34 UTC, Half-Shot commented on proposals/4140-delayed-events-futures.md
> +The server MAY round the delay up to a maximum of 30 seconds away from the request.
I think this is saying that the server is allowed an accuracy of 30s?

This seems:

a) Difficult to enforce. What if the server is underpowered / unstable / has it's database fall out.
b) Probably next to useless if we're considering the RTC cases, as 30 seconds of delay is veeery slow for that kind of use case.

2026-01-22 14:37 UTC, Half-Shot commented on proposals/4140-delayed-events-futures.md
> +  "errcode": "M_RESOURCE_LIMIT_EXCEEDED",
This is not the correct use of this status code. This is for when the homeserver has limits placed upon *it*.

As per https://spec.matrix.org/latest/client-server-api/#common-error-codes:

>The request cannot be completed because the homeserver has reached a resource limit imposed on it. For example, a homeserver held in a shared hosting environment may reach a resource limit if it starts using too much memory or disk space

This is not the same as the homeserver limiting individual users.

Naively can we not use a `M_LIMIT_EXCEEDED` with the delay being the time until the next event is sent?

2026-01-22 14:39 UTC, Half-Shot commented on proposals/4140-delayed-events-futures.md
> +  "org.matrix.msc4140.errcode": "M_MAX_DELAY_EXCEEDED",
This is unusual? Can we not use an unstable string for `M_MAX_DELAY_EXCEEDED` and put it in `errcode`. 

https://spec.matrix.org/latest/client-server-api/#standard-error-response allows for bespoke error codes, and clients/servers should handle unknown `errcode`s.

2026-01-22 14:39 UTC, Half-Shot requested changes
I have some concerns about the wording and error codes.

2026-02-17 15:12 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +### Self-destructing messages
Closing this based on:
> we could close this thread, because the other is regarding the same topic

2026-02-17 15:12 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +### Getting delayed events
Closing this as there seem to be no objections to the follow up MSC approach.

2026-02-17 15:29 UTC, Half-Shot commented on proposals/4140-delayed-events-futures.md
> +- `finalised` - Required if the request has no `status` parameter, or sets it to `"finalised"`.
:brain:  = 🌪️ :heavy_check_mark:

2026-02-17 15:32 UTC, Half-Shot commented on proposals/4140-delayed-events-futures.md
> +- batch size: 10
Okay, I didn't see that this included failed events too. That makes sense, as otherwise how would you know that an event has failed.

2026-02-17 15:33 UTC, Half-Shot commented on proposals/4140-delayed-events-futures.md
> +The `delay_id` is an [opaque identifier](https://spec.matrix.org/v1.16/appendices/#opaque-identifiers) generated by the server.
I think we could make it so that it only appears down the sender's sync. Shall we do that?

2026-02-17 16:14 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +The `delay_id` is an [opaque identifier](https://spec.matrix.org/v1.16/appendices/#opaque-identifiers) generated by the server.
That would be ideal.  Is there a precedent of sender-exclusive fields in `unsigned`?

2026-02-17 16:23 UTC, Half-Shot commented on proposals/4140-delayed-events-futures.md
> +The `delay_id` is an [opaque identifier](https://spec.matrix.org/v1.16/appendices/#opaque-identifiers) generated by the server.
Yes, we do this for local echo https://spec.matrix.org/latest/client-server-api/#local-echo

2026-02-17 16:38 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +The `delay_id` is an [opaque identifier](https://spec.matrix.org/v1.16/appendices/#opaque-identifiers) generated by the server.
Resolved in: 49b200dcc11de286974925177b1e184cd905e6fa

2026-02-17 16:42 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +  "errcode": "M_RESOURCE_LIMIT_EXCEEDED",
Resolved with: 3ef314f861f3e54a9a474e624eba3684ee6ea978

2026-02-17 16:48 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +The server MAY round the delay up to a maximum of 30 seconds away from the request.
@tulir What is the rational behind this detailed latency?

I think it is really good to make 100% clear that a server can NEVER EVER send a delayed event before the delay timeout. This is the promise it has to give the users. But a later arriving delayed event is always the case (due to network latency, server load, restarts, implementation details (batching delayed event emissions))

I dont see why we mention a specific 30s is the spec. What is wrong with asking the server to send it as precise as possible? What benefit does loosening this constraint bring?

2026-02-17 16:56 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +  "errcode": "M_RESOURCE_LIMIT_EXCEEDED",
Another option is `M_USER_LIMIT_EXCEEDED` from MSC4335.

2026-02-17 16:56 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +  "org.matrix.msc4140.errcode": "M_MAX_DELAY_EXCEEDED",
resolved in: 95045cf00eeb2af0976b31d2262875ef7eefaeec

2026-02-17 16:58 UTC, toger5 commented
There have been changes to the MSC based on @Half-Shot s feedback:
3ef314f861f3e54a9a474e624eba3684ee6ea978
95045cf00eeb2af0976b31d2262875ef7eefaeec
49b200dcc11de286974925177b1e184cd905e6fa

Those three commits need updates to the implementations.

2026-02-17 17:07 UTC, Half-Shot commented on proposals/4140-delayed-events-futures.md
> +  "errcode": "M_RESOURCE_LIMIT_EXCEEDED",
Actually, great idea. It looks like this MSC is close to landing so we can probably rely on it.

2026-02-17 17:14 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +  "errcode": "M_RESOURCE_LIMIT_EXCEEDED",
fixed in: 642b09eaf238bc4f4fa97bee6615bb68481bae8d

2026-03-03 12:16 UTC, reivilibre commented on proposals/4140-delayed-events-futures.md
> +#### `delay_id` in `unsigned` sync field
This should have an unstable prefix whilst it's unstable

2026-03-03 14:18 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +The server MAY round the delay up to a maximum of 30 seconds away from the request.
Its based on this feedback: https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r2331979623

2026-03-03 14:29 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +The server MAY round the delay up to a maximum of 30 seconds away from the request.
I think more detailed requirements make it more clear what we are trying to say and what the implementation is allowed to.
I think we need to guarantee that events never get send before the scheduled time (later can always happen due to server or network load so we need to make clear that clients have to expect "after scheduled time emissions")

```suggestion
The server SHOULD send the delayed event as close to the scheduled time as possible.
The server MUST not send the event before the scheduled time.
The server MAY implement delayed event scheduling in a way, that results in sending the event at most 30 seconds later than the exact scheduled delay time. This might be required for performance optimisations (batching).
In practice, due to server load, network speed, larger send offsets can happen.
```

2026-03-03 14:33 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +The server MAY round the delay up to a maximum of 30 seconds away from the request.
@turt2live Does it make sense to you to extend you suggestion like that ^

2026-03-03 15:33 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +`M_USER_LIMIT_EXCEEDED` error code:
@turt2live mentioned that this in the end might not be the best option afterall.

`M_USER_LIMIT_EXCEEDED` is designed to be a "pay to get rid of the error" kind of problem. So we might have a "rate limit class"-error here.

If a homeserver would allow a paywall to send more delayed events they could return `M_USER_LIMIT_EXCEEDED`. But the default would be a rate limit error.

We want to return back to the prev (`M_LIMIT_EXCEEDED`) error code.

2026-03-03 15:38 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +The server MAY round the delay up to a maximum of 30 seconds away from the request.
```suggestion
The server MUST NOT send the event before the scheduled time.
To support batch sending, servers MAY add up to 30 seconds to the scheduled send time. 
Note: clients might find that their events are delayed further due to server load and similar conditions. 
```

2026-03-05 16:03 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +The homeserver MUST only include the `delay_id` unsigned key in the `/sync` response to the event `sender`.
May the `delay_id` be included with any event-returning request, not just `/sync`?

2026-03-05 16:22 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +#### `delay_id` in `unsigned` sync field
a790e5ad

2026-03-05 20:06 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +The homeserver MUST only include the `delay_id` unsigned key in the `/sync` response to the event `sender`.
08648699 tackles this by permitting, but not requiring, non-`/sync` requests to include the `delay_id`.  The point is to explicitly grant server implementations with more freedom for when to include the `delay_id` -- all that really matters is that it at least comes down `/sync` and isn't visible to non-`sender` users.

2026-03-06 06:37 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +`M_USER_LIMIT_EXCEEDED` error code:
bad34198

2026-03-09 11:09 UTC, robintown commented on proposals/4140-delayed-events-futures.md
> +The homeserver MUST only include the `delay_id` unsigned key in the `/sync` response to the event `sender`.
Hm, I worry that a client developer might erroneously infer from seeing `delay_id` in a non-`/sync` request that they can rely on it being there for one's own delayed events. Requiring it to be included or excluded would leave less room for mistakes that make a client reliant on a specific server implementation. Though are there other examples of unreliable attributes like this in `unsigned`?

2026-03-09 13:04 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +The homeserver MUST only include the `delay_id` unsigned key in the `/sync` response to the event `sender`.
Aha, it turns out it's not as I thought.  The unsigned `transaction_id` required by the [local echo feature](https://spec.matrix.org/v1.17/client-server-api/#local-echo) is described in such a way that mandates only for it to appear in `/sync` (i.e. "when it arrives through the event stream") but doesn't explicitly forbid it from appearing in other responses.  In practice, Synapse returns it in GET `/_matrix/client/v3/rooms/{roomId}/event/{eventId}`.

So, my main motivation was for `delay_id` to be work the same way: mandatory in `/sync`, but optional elsewhere.

...However, it turns out the unsigned `transaction_id` is also mentioned in [the room event format](https://spec.matrix.org/v1.17/client-server-api/#room-event-format), meaning it will be present in any rendering of an event.  Thus `delay_id` should be in all renderings too.

2026-03-09 13:16 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +The homeserver MUST only include the `delay_id` unsigned key in the `/sync` response to the event `sender`.
30426d68

2026-05-15 08:27 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +that happened while sending the event (e.g. `M_FORBIDDEN` if the user doesn't have permission to send the event).
This is now covered by 1e18fa2.

2026-05-15 08:33 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +`GET /_matrix/client/v1/delayed_events?status=finalised` allows clients to get a list of
cdc7a20 opts for having the multi-item lookup response put both scheduled & finalised events in the same array, which allows for straightforward pagination.

That commit also adds a single-item lookup, but doesn't make it unauthenticated as I had proposed in my last comment, as there is currently no use-case that requires external services to know the details (particularly the event content) of the delayed event(s) they are given control over the scheduling of.

2026-05-18 09:31 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +The homeserver MAY enforce a maximum allowed delay for delay events.
```suggestion
The homeserver MAY enforce a maximum allowed delay for delayed events.
```

2026-05-18 09:47 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_MAX_DELAY_EXCEEDED` and the maximum allowed delay in milliseconds in a `max_delay` field.
Instead of putting the maximum delay into the error response, maybe we could add a [capability](https://spec.matrix.org/v1.18/client-server-api/#capabilities-negotiation) or something akin to [` /_matrix/client/v1/media/config`](https://spec.matrix.org/v1.18/client-server-api/#get_matrixclientv1mediaconfig) (which coincidentally contains the maximum allowed upload size of media files)? This way clients would be able to discover the maximum delay (which might be zero if the server denies delayed events entirely) beforehand and adapt or disable certain parts of their UI.

The maximum allowed number of simultaneously scheduled events could possibly also go into such a capability / config.

2026-05-18 10:00 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +On success, the homeserver will respond with HTTP 200 and a JSON object containing the following fields:
I wonder if the status of the event could be too implicit here.

- To check for an error, you need to look at `error`.
- To check for a sent event, you probe `event_id`.
- A scheduled event is identified by the lack of both `error` and `event_id` and `running_since + delay` being in the future.
- A user-canceled event in turn can only be differentiated from a scheduled event once its trigger time has passed (so that `running_since + delay` is in the past).

Maybe this would become a bit easier to use if we added an explicit status property?

In fact, the listing endpoint introduced below has filter options for the status albeit in two separate parameters:

> - `status`: `"scheduled"|"finalised"` - Return only scheduled or finalised delayed events.
> [...]
> - `outcome`: `"send"|"cancel"|"error"` - Return only finalised delayed events that were either

How about we add a property à la `status = scheduled | sent | cancelled | failed`?

2026-05-18 10:01 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +- `origin_server_ts` - The timestamp (as Unix time in milliseconds) when the event was finalised;
Does this consciously include all finalization cases (sent, failed and cancelled)? I'm curious what the use case for the timestamp is when the event was _not_ sent.

It might be that my confusion just stems from the fact that `origin_server_ts` is only used for actually sent events in the current spec.

2026-05-18 11:40 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +Delayed events are returned in order of a time-based property which may specified by the `order_by` query parameter:
```suggestion
Delayed events are returned in order of a time-based property which may be specified by the `order_by` query parameter:
```

2026-05-18 12:30 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +#### Getting a list of delayed events
This API seems slightly more sophisticated than I expected. I'm sure there is thinking behind it but the proposal currently doesn't make the motivation very clear. Maybe we could add some examples of when and how a client would use this endpoint and its various query options?

2026-05-18 12:45 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +### Homeserver implementation details
The term "implementation details" might be slightly misleading here because it usually refers to something that is consciously left unspecified or something that is not relevant under the current scope. This section contains actual specification for the server though.

Maybe something like this would be clearer?

```suggestion
### Additional homeserver behaviour
```

2026-05-18 13:03 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +It can even be used to send temporal power levels/mutes or bans.
This and some of the content from the "Self-destructing messages" section might be good to have at the beginning of the proposal. The current introduction exclusively touches upon the VoIP use case. I think it would give use a much stronger case if we also covered the other foreseen usages there. This could also help motivate some of the details and design choices that follow afterwards in the proposal.

2026-05-18 14:01 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +[MSC4018](https://github.com/matrix-org/matrix-spec-proposals/pull/4018).
When using the sync loop as the heartbeat, this scheme seems like a generalization of the solution discussed and discarded in the "MSC4018 (use client sync loop)" section above. Maybe we could just combine the two sections?

2026-05-18 14:05 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +The existing `M_INVALID_PARAM` error code could be used instead of introducing a new error code `M_MAX_DELAY_EXCEEDED`.
I think we need to explain why we're discarding this alternative here. The only reason I can think of is that a separate error code lets the client know that it can look for the `max_delay` property? As discussed in https://github.com/matrix-org/matrix-spec-proposals/pull/4140/changes#r3257895622, however, we could possibly omit the `max_delay` property altogether.

2026-05-18 14:26 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +Some alternatives for the `running_since` field on the `GET` response are:
As another alternative, maybe we could pick something that ends with `..._ts`? The identifier `running_since` could erroneously be interpreted as a duration rather than a timestamp. This would be alleviated if we chose e.g. `scheduled_ts` or `created_ts`. This would also blend in slightly better with the other sorting options in GET /_matrix/client/v1/delayed_events: send_ts, origin_server_ts & ..._ts (rather than running_since)

In any case, if we list any alternatives, we need to motivate why we have discarded them.

2026-05-18 14:31 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +and thus no longer needs this rule.
This seems slightly complicated and if we cannot foresee a use case for it, maybe we don't even need to list it as an alternative?

2026-05-19 06:11 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +`delay_id` may securely grant control of it via [the management endpoints](#managing-delayed-events).
> [...] be as difficult to guess/craft as an access token [...]

I couldn't find any statements about the security of access tokens in the current spec. In fact, the spec seems to leave the format of access tokens [explicitly undefined](https://spec.matrix.org/v1.18/client-server-api/#client-authentication).

Maybe we could make this a little clearer by using the common term "cryptographically secure" rather than referring to "access tokens"?

```suggestion
It MUST be globally unique and SHOULD be cryptographically secure (in the sense that it is infeasible to predict).
This way, knowledge of the `delay_id` alone allows external services to control the delayed event through the
unauthenticated management endpoints introduced [below](#managing-delayed-events).
```

2026-05-19 06:47 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +  Absent if there are is no previous page of results.
I assume you can only paginate one way at a time?

```suggestion
- `next_batch` - A token that can be passed into a subsequent call to the endpoint to retrieve the next page of results.
  Absent if paginating backwards or when there is no next page of results.
- `prev_batch` - A token that can be passed into a subsequent call to the endpoint to retrieve the previous page of results.
  Absent if paginating forward or when there is no previous page of results.
```

2026-05-19 06:52 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +- `finalised` max cached events per user: 1000
The term "cached" threw me off here at first. I think this means the number of retained finalized events? So the retention is effectively up to 7 days or 1000 events, depending on which strikes first?

```suggestion
- `finalised` retention: up to 7 days or 1000 events per user, whichever occurs first
```

2026-05-19 07:02 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +against this attack.
This seems to be part of the proposal text further up now if I understood correctly.

> The homeserver SHOULD enforce a limit of how many delayed events a user may have scheduled at once [...]

```suggestion
```

2026-05-19 07:07 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +and the additional network/configuration overhead for external services to request access to this scope.
The OAuth APIs have officially been part of the spec for almost a year now. So the argument of having to support them should gradually get smaller and might not really be relevant here.

```suggestion
The downside of this approach is the additional network/configuration overhead for external services to
request access to this scope.
```

2026-05-19 07:19 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +resource limits.
This seems to contradict the design choice made in the proposal. We should either change this to motivate why we chose `M_LIMIT_EXCEEDED` or switch the proposal to use `M_MAX_DELAYED_EVENTS_EXCEEDED`.

Given that other resource limits are currently not differentiated via separate error codes in the API (see also https://github.com/matrix-org/matrix-spec-proposals/pull/4335), `M_LIMIT_EXCEEDED` seems like a reasonable choice to me.

```suggestion
A new error code `M_MAX_DELAYED_EVENTS_EXCEEDED` could be introduced instead of reusing the existing `M_LIMIT_EXCEEDED` error
code. This would allow clients to better distinguish delayed event scheduling limits from other resource limits.
Given that other resource limits are currently not differentiated via separate error codes in the API either,
reusing `M_LIMIT_EXCEEDED` seems reasonable though.
```

2026-05-19 07:24 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +- LastWill
It might be best to not open the naming can of worms ourselves. 🙈 😅

But if we really want to, I think we should add some reasoning for discarding the other terms. Here is what I can think of:

```suggestion
- Futures: Doesn't seem like a good match because the result of the API call cannot be "awaited" as you
  would normally `await` a future in various programming languages.
- Postponed Events: Similar to "delayed events" but longer.
- Last Will: Seems unfitting because the feature can be used regardless of whether the client goes offline
  or not. The term also feels somewhat dark.
```

2026-05-19 08:13 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +
I think this shouldn't be part of the proposal text but instead go into the PR description (or a separate comment similar to https://github.com/matrix-org/matrix-spec-proposals/pull/4473#discussion_r3253382151).

```suggestion
```

2026-05-19 08:16 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +opaque `delay_id` field (omitting the `event_id` as it is not available):
Given that the delay ID effectively acts as an access token for the management endpoints, we could consider changing the identifier to `delay_token`. This would more clearly call out to implementers that the ID / token is sensitive information. This will likely cause some compatibility hassle with the existing implementations, however.

2026-05-19 08:53 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_MAX_DELAY_EXCEEDED` and the maximum allowed delay in milliseconds in a `max_delay` field.
We need to consider if we want to ever allow a delay of 0.
It would break matrixRTC. (not entirely but the leave guarantee)
As this is like disabling the feature, we can either treat it as sliding sync (if a HS does not support it its incompatible) or like a "nice to have". If 0 is max allowed clients (and the jwt service) needs to work around it.

I am in favour of treating delayed events less as an optional "nice to have" but a necessity.
It should be the edgecase, that one exceeds the limit set by the HS. More like a rate limit than a file size limit.

But on the other hand an additional place to look up those configurations does not hurt in any way. Just not sure how important they are.

2026-05-19 08:56 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +On success, the homeserver will respond with HTTP 200 and a JSON object containing the following fields:
In an earlier iteration we had the status (quiet recent change actually)
The argumentation was along the lines of: redundancy, save bits on the wire.

@AndrewFerr I think that new eyes stumbled over this is a good insight?
How often will this endpoint realistically be used? How much do we gain by leaving this field?

2026-05-19 09:00 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +### Homeserver implementation details
needed to check the section again. Yes `Additional homeserver behaviour` fits much better.

2026-05-19 11:13 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +and thus no longer needs this rule.
I like the idea of dropping anything related to the autocancelling if a state event for the same key is sent.
At the end we do have power levels to figure out the a potential conflict. 
And matrix has this caveat (overwriting state) anyways. There is always delay in a federated world so app developers/spec designers should be expected to be aware of state having a risk to race and conflict and thing around this.

What about this:
We drop this as an alternative and make it a note along those lines:
The final spec text should mention, that a delayed event can overwrite changes that happened between sending the event and it getting finalised. (like with federation delay) Matrix based solutions that have to consider this and design around it. For example: pinned messages should have seperate keys or use relations instead of state events. State events that group independent information have to be challenged if they might be used with delayed events. If so one should consider splitting them into multiple events (or relation based solution where events represent a diff instead of a new state)

2026-05-19 11:15 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +`delay_id` may securely grant control of it via [the management endpoints](#managing-delayed-events).
I like this change. On top of this I would consider renaming `delay_id` -> `delay_token` as we have discussed briefly.

2026-05-19 11:23 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +and the additional network/configuration overhead for external services to request access to this scope.
I think the focus on this section is the required scoped token work (which I think it not yet there).
Maybe we can rephrase it so it becomes clear that this would then be blocked on figuring out the scoping implementation?

2026-05-19 11:25 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +- LastWill
Lets add this.

2026-05-19 11:25 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_MAX_DELAY_EXCEEDED` and the maximum allowed delay in milliseconds in a `max_delay` field.
It's probably not terribly important. I think the main reason to do it now rather than later is that we could avoid the `max_delay` property in the error response and use the existing `M_INVALID_PARAM` instead.

2026-05-19 11:27 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +
@AndrewFerr what is the current state of those anyways?

2026-05-19 11:32 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +opaque `delay_id` field (omitting the `event_id` as it is not available):
Can we evaluate in how many places this actually makes a difference (in the url for instance it does not make a difference since its not named there)

I think the main issue is the response to a `/send`/`/state`.
The default compatibility approach of sending both for some time seems very doable. The rust sdk and the js-sdk and synapse would be impacted but can be tackled one by one without coordination. (also LLM-able code imo. Should not introduce actual logic -> easy to review)

TLDR: The `cause some compatibility hassle` part seems to manageable and we can seriously consider this if we prefer it.

@AndrewFerr

2026-05-19 11:36 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +On success, the homeserver will respond with HTTP 200 and a JSON object containing the following fields:
Convenience aside, I think we'll need something to differentiate manually cancelled events. Currently they'll look like scheduled events until their trigger time has passed. This could also be solved by an `is_canceled` property. If we need a new property any way, a more general `status` property might be more useful though?

2026-05-19 11:42 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +and thus no longer needs this rule.
Yes, that sounds good. It could maybe go into the "Potential issues" section this way. 👍

2026-05-19 12:09 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +and the additional network/configuration overhead for external services to request access to this scope.
Oh, now I get it. How about something like this?

```suggestion
The downsides of this approach are the complexity of having  to implement scoped access tokens in homeservers
and the additional network/configuration overhead for external services to request access to this scope.
```

2026-05-19 19:40 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +- Creating self-destructing events (by sending a delayed redact).
Erasing events isn't currently possible, but we need to either fix that or the metadata issue.

(*resolving thread as it no longer applies to the current MSC*)

2026-05-19 21:07 UTC, turt2live requested changes
this is looking closer to being ready for FCP, thank you! I haven't done a detailed review because @Johennes has left a bunch of comments which should be addressed first. 

Removing the use cases section I think will also go a long way towards making this reviewable. The Alternatives section I think could also do with some shortening to reduce review load a lot.

2026-05-19 21:07 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +and a [standard error response](https://spec.matrix.org/latest/client-server-api/#standard-error-response)
`latest` can and does change, breaking historical links:
```suggestion
and a [standard error response](https://spec.matrix.org/v1.18/client-server-api/#standard-error-response)
```

2026-05-19 21:07 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +## Use case specific considerations
I'd suggest removing this section. It has a few examples which look too close to actual proposals, so it makes this proposal even harder to review. At best, this should say "These MSCs use this functionality: [list]" and "Future MSCs, like self-destructing messages, might find benefit from this proposal" - anything more starts to risk review delays.

2026-05-20 08:19 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +and thus no longer needs this rule.
Attempting to address this with https://github.com/matrix-org/matrix-spec-proposals/pull/4477.

2026-05-20 09:09 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +## Use case specific considerations
Attempting to address this with https://github.com/matrix-org/matrix-spec-proposals/pull/4478.

2026-05-20 09:09 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +It can even be used to send temporal power levels/mutes or bans.
Attempting to address this with https://github.com/matrix-org/matrix-spec-proposals/pull/4478.

2026-05-20 10:23 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +[MSC4018](https://github.com/matrix-org/matrix-spec-proposals/pull/4018).
Attempting to address this with https://github.com/matrix-org/matrix-spec-proposals/pull/4479.

2026-05-20 13:42 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +  Absent if there are is no previous page of results.
Good catch, both on the one-way pagination & the grammar :sweat_smile: 

Now that you mention it, I'm unaware of whether other bi-directional list lookups give only a single next/prev token for the 2nd page and onwards.  In any case, doing it like you mention here is reasonable.

2026-05-20 14:39 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_MAX_DELAY_EXCEEDED` and the maximum allowed delay in milliseconds in a `max_delay` field.
Using a capability is a good idea.  An advantage it has over adding a new /config endpoint is that there's nothing so unique about delayed event limits that warrants being expressed with an additional endpoint.

It could take the form of:
```
"capabilities": {
  "m.delayed_events": {
    "max_delay": 10000,
    "max_scheduled": 100
  }
}
```

2026-05-20 14:40 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +On success, the homeserver will respond with HTTP 200 and a JSON object containing the following fields:
Good catch on not being able to easily distinguish manually cancelled events vs scheduled ones.  Judging it by timestamps requires comparing client vs server times, which can get ugly.

Though I'm inclined against there being a `"status"` / `"outcome"` value for any status that can unambiguously determined by the presence of other fields on the response objects.  And as I see it, the only status that needs clarifying is a "cancelled" status, so a `"status"` enum field that has one of its possible values being `cancelled` really boils down to being a `"cancelled"` boolean field.

The reason why `status` and `outcome` remain as query parameters is because that felt like the best way to allow lookups to filter by the presence/absence of the fields they relate to, rather than by the values of those fields.

At the risk of being a tad esoteric, how about setting `"event_id"` to `null` for both cancelled & errored delayed events?  That is not ambiguous with an absent `"event_id"`, which would indicate a scheduled event.

2026-05-20 14:42 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- `origin_server_ts` - The timestamp (as Unix time in milliseconds) when the event was finalised;
> Does this consciously include all finalization cases (sent, failed and cancelled)?

Yes, as the server will be aware of all such cases.

> I'm curious what the use case for the timestamp is when the event was _not_ sent.

This is to allow checking the time of when a delayed event was cancelled.

Another possibility is that a server doesn't allow retrying `/send` on a delayed event if the first attempt failed with an error (since keeping the event scheduled after an error has been marked as a SHOULD condition, not a MUST), in which case this timestamp would tell you when the send was attempted.  But this isn't terribly important.

> It might be that my confusion just stems from the fact that `origin_server_ts` is only used for actually sent events in the current spec.

True.  Maybe the name of this field could be changed to something more illustrative.  A straightforward option is `finalised_ts`.

2026-05-20 14:43 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +The existing `M_INVALID_PARAM` error code could be used instead of introducing a new error code `M_MAX_DELAY_EXCEEDED`.
Yes, the point of a new error code was to be able to have the `max_delay` field in the error object.  But this can now all be removed in favour of expressing the max delay in `/capabilities`.

2026-05-20 14:43 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +Some alternatives for the `running_since` field on the `GET` response are:
Good idea.  IMO `scheduled_ts` is best because it reuses existing terminology introduced by this MSC.

2026-05-20 14:44 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +and the additional network/configuration overhead for external services to request access to this scope.
Instead of "complexity", maybe say "required work"; i.e. there is work to be done for servers to add more access scopes, but whether it's complex is a matter of debate (and suggesting that it is makes it seem more daunting than it might actually be)

2026-05-20 14:44 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +resource limits.
Good idea.  Adding the comment on how other resource limits don't get their own errcode justifies why this is alternative.

2026-05-20 14:45 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +
PRs for those points have been on hold but are still in progress.  I've posted them as an update to the top comment of this MSC instead of as a standalone comment.

2026-05-20 14:45 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +opaque `delay_id` field (omitting the `event_id` as it is not available):
I'm doubtful that the cost of changing the name across all clients/servers/SDKs is worth the effort, because:
- In the long run, access to delayed event endpoints / specific delayed events should be managed by OAuth 2.0 scopes, at which point a name of `delay_token` won't be as relevant
- Using `delay_id`s as an access token can't keep them as hidden as "real" access tokens (e.g. they appear in request URIs & `/sync` responses), so renaming them to `delay_token` suggests they adhere to a higher degree of security that they actually do

2026-05-22 11:38 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +On success, the homeserver will respond with HTTP 200 and a JSON object containing the following fields:
> At the risk of being a tad esoteric, how about setting `"event_id"` to `null` for both cancelled & errored delayed events? That is not ambiguous with an absent `"event_id"`, which would indicate a scheduled event.

Hm, I'm a bit divided as this might be slightly non-intuitive and possibly a bit unergonomic in languages that don't differentiate `null` and `undefined`. I cannot think of another way to infer cancelled events without adding a new property though and I get the rationale behind avoiding that.

If we document what properties to check for which status in the MSC / spec, this variant will probably be fine, I suppose. I'd give it 6 out 10 strength.

2026-05-22 11:41 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +and the additional network/configuration overhead for external services to request access to this scope.
Good idea. 👍 

```suggestion
The downsides of this approach are the required work of having to implement scoped access tokens in homeservers
and the additional network/configuration overhead for external services to request access to this scope.
```

2026-05-22 11:45 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +`delay_id` may securely grant control of it via [the management endpoints](#managing-delayed-events).
The suggestion has been applied separately and the potential renaming is being discussed in https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r3264704128.

2026-05-22 12:10 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +- `origin_server_ts` - The timestamp (as Unix time in milliseconds) when the event was finalised;
> Another possibility is that a server doesn't allow retrying `/send` on a delayed event if the first attempt failed with an error (since keeping the event scheduled after an error has been marked as a SHOULD condition, not a MUST), in which case this timestamp would tell you when the send was attempted. But this isn't terribly important.

Oh, interesting. I actually wouldn't have expected the timestamp to be set in this case. When the server leaves the event scheduled after the failed initial `/send`, it's not actually finalized as per the definition at the beginning of the proposal (not sent and not cancelled). Given that the client has issued the `/send` itself, maybe we could omit setting the timestamp in that case?

> > It might be that my confusion just stems from the fact that `origin_server_ts` is only used for actually sent events in the current spec.
> 
> True. Maybe the name of this field could be changed to something more illustrative. A straightforward option is `finalised_ts`.

I like `finalised_ts` better as it feels a bit clearer. I'm only 6 out of 10 strength on it though given that we could also document the meaning of `origin_server_ts` properly.

2026-05-24 14:09 UTC, new-years-eve commented on proposals/4140-delayed-events-futures.md
> +or as a special-case string of "end" to start from the latest possible results.
Shouldn't the option be "to start from the **earliest** possible results" ? If I understand correctly we're getting the events that come _after_ this timestamp.

It would also be good to clarify what timestamp is being looked to for the cutoff here. Is it the timestamp specified by the `order_by` parameter ?

2026-05-24 14:21 UTC, new-years-eve commented on proposals/4140-delayed-events-futures.md
> +On success, the homeserver will respond with HTTP 200 and a JSON object containing the following fields:
I'm currently implementing this MSC for Ruma and Continuwuity. I think I'd prefer a field that clearly tells us what became of the event, rather than a set of rules for determining it.

Maybe a compromise is to leave out the `status` : `"scheduled"|"finalized"` field, as that can be inferred easily from available information. But to include the `outcome` : `"send"|"cancel"|"error"` field for finalized events.

2026-05-25 12:59 UTC, new-years-eve commented on proposals/4140-delayed-events-futures.md
> +and to allow retries of the `send` action until then.
I don't think the behavior of the `/send` endpoint should be different from the behavior of the event reaching it's scheduled send time. In case of error, the event should be finalized with an `error` outcome. Nothing else about the delayed event feature suggests that they should ever be retried in case of failure.

Additionally, with the behavior specified here, the client cannot know if the event is still scheduled or not after receiving an error response to a `send` request. The same error response could mean that the event has failed to be sent by the request itself (and is still scheduled) or has failed to send after it's timeout was reached (and is no longer scheduled).

2026-05-26 05:34 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +and to allow retries of the `send` action until then.
Yeah, agreed. It would seem more consistent to me if we treated `/send` as an attempt to manually finalize the event – so that the event is either sent or cancelled afterwards.

2026-05-26 05:55 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +or as a special-case string of "end" to start from the latest possible results.
> Shouldn't the option be "to start from the **earliest** possible results" ? If I understand correctly we're getting the events that come _after_ this timestamp.

Hm, I think it depends on whether you use `dir=f` or `dir=b`?

IIUC:

- `dir=f` and `since_ts=X` returns results whose scheduled time is `>=X` ordered by increasing scheduled time
- `dir=b` and `since_ts=X` returns results whose scheduled time is `<=X` ordered by decreasing scheduled time

So `dir=f&since_ts=end` gives you only the result(s) with the most distant scheduled time as you cannot go forward from there. But `dir=b&since_ts=end` returns all results starting from the most distant scheduled time and then ordered by decreasing scheduled time.

> It would also be good to clarify what timestamp is being looked to for the cutoff here. Is it the timestamp specified by the `order_by` parameter ?

Yeah, given that the results are ordered by what's specified in `order_by`, that's the only option that makes sense, I'd say.

2026-05-26 07:29 UTC, new-years-eve commented on proposals/4140-delayed-events-futures.md
> +or as a special-case string of "end" to start from the latest possible results.
Oh I see. If that's the intended meaning, it could maybe be clarified? With the way it's worded, I wasn't sure if `since_ts` indicates the start of the event in time (always return events after the timestamp) or the start of events in the list ordering (events selected depend on the order).

2026-05-26 08:30 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +or as a special-case string of "end" to start from the latest possible results.
At least that's my interpretation of it. 🙈 But yeah, some clarification would help here.

On a tangential note, there's also maybe an [open question](https://github.com/matrix-org/matrix-spec-proposals/pull/4140/changes#r3258882699) whether we really need all these query options. It looks like Synapse [doesn't currently implement any of them](https://github.com/element-hq/synapse/blob/4655b435ee6e83518cd9ea6941d403be1cdf3a63/synapse/rest/client/delayed_events.py#L149).

2026-05-27 02:22 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +On success, the homeserver will respond with HTTP 200 and a JSON object containing the following fields:
Reducing the number of status-like fields from 2 to 1 is an improvement.  Still, it feels that even an `outcome` should be able to be inferred...

After thinking about it some more, there is indeed a "tell" for user-cancelled delayed events: the `origin_server_ts` / `finalised_ts` field.  If it is present and `event_id` & `error` are both absent, then the event was cancelled.

The full logic would then be:
- If `origin_server_ts` / `finalised_ts` is absent, then the delayed event is still scheduled.
- Otherwise, if `event_id` is present, then the delayed event has been sent (and was sent manually if `origin_server_ts`/`finalised_ts` < `running_since` + `delay`).
- Otherwise, if `error` is present, then the delayed event failed to be sent (and was descheduled) due to an error.
- Otherwise, the delayed event was cancelled.

This would also allow implementations to treat "falsey" values of any these fields (like the empty string or `undefined`/`null`/`nil`/etc) the same as the field being absent, since there would be no need to distinguish between the two.

Does that sound like it would be reasonable to implement?

2026-05-27 02:22 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- `origin_server_ts` - The timestamp (as Unix time in milliseconds) when the event was finalised;
> Oh, interesting. I actually wouldn't have expected the timestamp to be set in this case. When the server leaves the event scheduled after the failed initial `/send`, it's not actually finalized as per the definition at the beginning of the proposal (not sent and not cancelled). Given that the client has issued the `/send` itself, maybe we could omit setting the timestamp in that case?

To clarify, I didn't mean that a failed `/send` should set the `origin_server_ts` / `finalised_ts` timestamp even when the event remains scheduled; I meant that the server has the choice to deschedule an event if `/send` fails, _and only if it does so_ must the timestamp be set.  I.e. the timestamp must be set when & only when an event gets finalised/descheduled, and the server may choose to deschedule an event when `/send` fails.

> I like `finalised_ts` better as it feels a bit clearer. I'm only 6 out of 10 strength on it though given that we could also document the meaning of `origin_server_ts` properly.

Personally I've already confused myself with calling it `origin_server_ts`, as the field with the same name on sent events has different semantics.  So my vote is to rename it to make it clear that it has a distinct purpose.

2026-05-27 02:23 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +or as a special-case string of "end" to start from the latest possible results.
The interpretation in https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r3301523622 is correct.  I'll try to reword this section for clarity.

2026-05-27 02:23 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +and to allow retries of the `send` action until then.
The reason I added this section was to allow [external services](https://github.com/matrix-org/matrix-spec-proposals/blob/toger5/expiring-events-keep-alive/proposals/4140-delayed-events-futures.md#delegating-scheduled-delayed-events) to be able to retry `/send` attempts, especially for temporary errors like rate limits on messages sent into a room.

Otherwise, if the event that an external service tries to `/send` encounters an error, then the service can't simply retry sending/rescheduling that event, as the service won't have access to the event content to be re-sent (unless it was communicated with the service beforehand, or if `GET /delayed_events/{delay_id}` were to allow unauthed requests, which would sacrifice some privacy for convenience), and won't have permission to schedule/send a new event at all (unless it has an access token for doing so, in which case it would really just be a proper CS-API client and not an "external service" as this MSC defines it).

> Additionally, with the behavior specified here, the client cannot know if the event is still scheduled or not after receiving an error response to a `send` request. The same error response could mean that the event has failed to be sent by the request itself (and is still scheduled) or has failed to send after it's timeout was reached (and is no longer scheduled).

This is a good point.  A possible solution is to introduce a new error type for representing a `/send` request that was processed correctly by the server, but failed to send the event due to a CS-API error on the event itself; this error would wrap the standard error response of the underlying CS-API error in a dedicated field.  This would disambiguate from errors on the `/send` request itself, like a 404/409 for trying to send a delayed event that was not found / already cancelled / etc.

The error type would look something like this:
```json
{
  "errcode": "M_DELAYED_SEND_ERROR",
  "error": "Unable to send delayed event on-demand",
  "event_error": {
    "errcode": "M_LIMIT_EXCEEDED",
    "error": "Too many requests"
  } 
}
```

A limitation of this is that the wrapped error field can't wrap the HTTP status/headers of the CS-API error (such as [`Retry-After` for rate limits](https://spec.matrix.org/v1.18/client-server-api/#rate-limiting)), so I suppose the status/headers of `/send` would have to match those of the underlying CS-API error.

If all of this is too complicated, then an alternative is to propose that Matrix clients should have a communication channel with external services to be notified of when a service's `/send` attempt has failed & descheduled the target event, so it can possibly be retried.

2026-05-27 06:30 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +On success, the homeserver will respond with HTTP 200 and a JSON object containing the following fields:
I think I can live with that if we document it as explicitly as you did. 👍

2026-05-27 06:32 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +- `origin_server_ts` - The timestamp (as Unix time in milliseconds) when the event was finalised;
> To clarify, I didn't mean that a failed `/send` should set the `origin_server_ts` / `finalised_ts` timestamp even when the event remains scheduled; I meant that the server has the choice to deschedule an event if `/send` fails, _and only if it does so_ must the timestamp be set. I.e. the timestamp must be set when & only when an event gets finalised/descheduled, and the server may choose to deschedule an event when `/send` fails.

Ah sorry, got it now. Thanks for clarifying. 👍 

> Personally I've already confused myself with calling it `origin_server_ts`, as the field with the same name on sent events has different semantics. So my vote is to rename it to make it clear that it has a distinct purpose.

Ok, then I'd say let's just do it. It definitely feels more intuitive.

2026-05-27 08:06 UTC, new-years-eve commented on proposals/4140-delayed-events-futures.md
> +and to allow retries of the `send` action until then.
If failing due to a temporary error is a concern, then shouldn't we also worry about retrying events which have reached their scheduled send time ?

To consider the initial use case. I have a scheduled event for disconnecting from a VOIP call, and I want to trust that it will get sent eventually after I stop refreshing it. If there exists a possibility that the event will fail due to a temporary error that calls for a retry (a rate-limit, for example), then we would like the event to get retried in that case, regardless of whether it gets sent by the `/send` endpoint or by reaching it's scheduled time. Maybe the server should re-schedule the scheduled event when it fails due to an error that calls for a retry ?

Conversely, if we decide that re-scheduling failed events isn't necessary when they get sent by timeout, then I would say that having the ability to send them again through the `/send` endpoint isn't necessary either.

2026-05-28 05:41 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +and to allow retries of the `send` action until then.
> If failing due to a temporary error is a concern, then shouldn't we also worry about retrying events which have reached their scheduled send time ?

Yes, but the difference is that the scheduled send time of a delayed event is known (to a degree, considering restarts), but a `/send` request can be made at any time.

To check if a delayed event hit an error on its scheduled send time, a client can wait until that time and then call `GET /delayed_events/{delay_id}` to look for an `error` field on the response, and decide whether to retry sending/scheduling if there was an error.  In contrast, to check if a `/send` request descheduled its target event due to an error, a client must either proactively call the `GET` endpoint every so often, or instead wait until the event's original scheduled send time, at which point the event may have been cancelled for a long time already.

A way around that could be to notify clients (such as via a `/sync` payload) of failed `/send`s, so that they'll know right away when an event was unscheduled & can decide whether to retry sending it.  However, this would incur extra network traffic, and may not be available to "light" clients (like external services that only have access to `/send`, `/restart`, and `/cancel`, but not `/sync`, or even the ability to send/schedule a replacement event).

It also feels somewhat counter-intuitive for `/send` to behave like `/cancel` in the case of a temporary error.

> Maybe the server should re-schedule the scheduled event when it fails due to an error that calls for a retry ?

This could work, but I'd rather not offload more work to the server, especially for working around rate limits that are supposed to reduce server load.  I can also imagine situations where a retry isn't desired, so it makes more sense for clients to be in control of the decision to retry or not.

2026-05-28 07:18 UTC, new-years-eve commented on proposals/4140-delayed-events-futures.md
> +and to allow retries of the `send` action until then.
> To check if a delayed event hit an error on its scheduled send time, a client can wait until that time and then call GET /delayed_events/{delay_id} to look for an error field on the response, and decide whether to retry sending/scheduling if there was an error.

But isn't the use case for delayed events a situation where the client isn't available to send the event at the time ? Such as a client which has been disconnected and isn't there to hang-up a call. If we're counting on the client to be there after the event expired and check that it was sent successfully, then doesn't that defeat the whole purpose of a scheduled event in the first place ? If events that need to be retried are a concern, then we should also worry about the case of an event that needs to be retried after the client is no longer there to supervise it.

2026-05-28 08:18 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +
Capturing the finding from https://github.com/element-hq/element-call/issues/3985 as a potential issue.

```suggestion

### Rate-limiting for heartbeats

In office environments several clients might share the same public IP address. If the server
rate limits based on IP address and multiple clients use the heartbeat pattern (where a scheduled
delayed event is rescheduled recurringly), it is more likely for them to run into rate limit blocks.
This can result in their delayed event being triggered too early which can negatively affect application
logic. For instance, if the delayed event is a call disconnect event, triggering it too early will result
in unexpected disconnections from the call[^call-rate-limit].

[^call-rate-limit]: See also https://github.com/element-hq/element-call/issues/3985.

To mitigate this, the `/restart` endpoint SHOULD allow optional authentication so that the server
can rate limit per client when management of the delayed event is not delegated to an external service.

```

2026-05-28 14:28 UTC, toger5 commented on proposals/4140-delayed-events-futures.md
> +
I think this still collides with the delegation usecase. A JWT that handles 100dreds of calls will not use the authed endpoint and hence get rate limited easily.

I think the proper solution might be to rate limit per delay_token / delay_id. (looking at a delay_id like a scoped token, that fits the authed endpoint semantic where each token gets their own rate limit bucket.)
404 Not Found have to be a special case to mitigate denial of service attacks. If I send restarts for unknown delay events then we should fallback to IP based rate limiting. (In theory well behaving clients should never send restarts for unkown Id's)

2026-05-28 15:19 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +and to allow retries of the `send` action until then.
> But isn't the use case for delayed events a situation where the client isn't available to send the event at the time ? Such as a client which has been disconnected and isn't there to hang-up a call. If we're counting on the client to be there after the event expired and check that it was sent successfully, then doesn't that defeat the whole purpose of a scheduled event in the first place ?

This is a valid point.  The reality is that it is always possible for a scheduled event to become unsendable, even if the conditions at the time of its original scheduling would have allowed it to be sent.  This is what inspired the idea of finalised delayed events & allowing clients to check for failures after the fact; the only alternative is to let servers retry sending on failure.

> If events that need to be retried are a concern, then we should also worry about the case of an event that needs to be retried after the client is no longer there to supervise it.

My worry is that making the server retry failed scheduled events could be a futile effort, and may not be warranted depending on the kind of failure & the context in which it happened.  A valid case for retrying is rate limits, but a not-so-valid case is a permission issue, like the acting user no longer being in the room or having a power level that allows sending the event.  In those cases, automated retries would fail until the permission issue is resolved.

My view on this is, if a delayed event failed to be sent at its scheduled send time, nothing can fix how the event already missed its schedule, so clients can take their time (to a degree) to decide how to address the failure.  Meanwhile, if a `/send` hits a failure, that failure is known immediately & there is still time to address it before the event's scheduled send time, and should thus be as easy as possible to be addressed immediately.

The particular use-case I am considering is to allow Element Call to delegate management of delayed call-hangup events to the lk-jwt-service ([context](https://github.com/element-hq/lk-jwt-service/pull/171)).  When the service detects a dropped call, it may try `/send`ing the hangup event immediately instead of waiting for its scheduled send time ([context](https://github.com/element-hq/lk-jwt-service/pull/171/changes#diff-c48512963d0f5620e1d32f8c1e180dcc831e419f52ccea24a0d711130e65cc95R452-R455)).  What I want is for a failure on `/send` to not cancel the scheduled sending, because there could still be time for the scheduled send to succeed; and for the service to be able to retry the `/send` on failure, as the service has no other means of attempting a retry (as it can't query the homeserver for the event to be rescheduled/resent, nor can it hit any of the regular event-sending endpoints), and being able to retry is the easiest way for the service to send the hangup event as promptly as possible.  If all retried `/send`s fail & even the scheduled sending of the hangup event fails, then there is likely nothing that either the service or homeserver could do about it, and only then would a client have to clean up a lingering call state when it comes back online.

2026-05-28 16:14 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +
> I think the proper solution might be to rate limit per delay_token / delay_id. (looking at a delay_id like a scoped token, that fits the authed endpoint semantic where each token gets their own rate limit bucket.)

This does feel like the best compromise currently available.  (Note that once OAuth 2.0 scopes are used for the management endpoints, the rate-limits may be applied against the scope tokens.)

> 404 Not Found have to be a special case to mitigate denial of service attacks. If I send restarts for unknown delay events then we should fallback to IP based rate limiting.

I'm not sure how this rate-limit could be applied.  By the time the server has done the work to find that a requested `delay_id`/`delay_token` is invalid, there is no more work to be done that a rate limit would protect against, so it doesn't really matter whether the error response is 404 or 429.  So I think the correct way to describe this rate-limiting strategy is to apply a bucket on each valid `delay_id`/`delay_token`, and no limit on invalid ones.

Either way, this leaves open the attack vector of a malicious client making a high number of restart/send/cancel requests for bogus `delay_id`/`delay_token`s.  However, servers should ideally index delayed events by their ID/token, so perhaps it wouldn't be terribly costly to handle such bogus requests.

2026-05-28 17:12 UTC, new-years-eve commented on proposals/4140-delayed-events-futures.md
> +and to allow retries of the `send` action until then.
Okay I think I see the rationale. The event might be scheduled with a deliberately long timeout, counting on the external service to send it when it detects a hang-up. This gives the service plenty of time to retry it if needed.

Fair enough. It makes the API behavior a bit counterintuitive, but there's a good reason for it.

I still think that the need for retry when there isn't an external service to supervise the event is one worth worrying about. But I acknowledge that it doesn't necessarily have a good solution.

2026-05-29 05:46 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_MAX_DELAY_EXCEEDED` and the maximum allowed delay in milliseconds in a `max_delay` field.
Done by 8f9f4544

2026-05-29 05:47 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +The existing `M_INVALID_PARAM` error code could be used instead of introducing a new error code `M_MAX_DELAY_EXCEEDED`.
Removed by 8f9f4544.

2026-05-29 05:47 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- `origin_server_ts` - The timestamp (as Unix time in milliseconds) when the event was finalised;
Done by e557016e.

2026-05-29 19:43 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +On success, the homeserver will respond with HTTP 200 and a JSON object containing the following fields:
Done by 5977f94e.

2026-05-29 19:44 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +Some alternatives for the `running_since` field on the `GET` response are:
Done by 06ab77af.

2026-06-01 11:18 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +opaque `delay_id` field (omitting the `event_id` as it is not available):
This sounds reasonable. 👍 Let's leave it as it is then.

2026-06-01 11:23 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +    }
I _think_ the missing brace is what makes GitHub render the subsequent text all red.

```suggestion
    }
  }
```

2026-06-01 11:34 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +and to allow retries of the `send` action until then.
Resolving since – if I've followed correctly – it sounds like we acknowledged the current state of the proposal.

2026-06-01 11:40 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +#### Getting a list of delayed events
@AndrewFerr given that Synapse [doesn't seem to implement](https://github.com/element-hq/synapse/blob/4655b435ee6e83518cd9ea6941d403be1cdf3a63/synapse/rest/client/delayed_events.py#L149) any of the query parameters yet, what's your take on descoping them to a future proposal?

Unless we assume extensive usage of this feature, we may be ok without pagination for a start. If really needed, we could always add it later in a backwards-compatible way by introducing a `/v2` of the endpoint.

2026-06-01 11:50 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +or as a special-case string of "end" to start from the latest possible results.
Maybe this could work (contingent on https://github.com/matrix-org/matrix-spec-proposals/pull/4140/changes#r3333817315)?

```suggestion
or as a special-case string of "end" to start from the latest possible results. In other words:

- `dir=f&order_by=send_ts&since_ts=X` returns results whose scheduled time is `>= X` ordered by increasing scheduled time
- `dir=b&order_by=send_ts&since_ts=X` returns results whose scheduled time is `<= X` ordered by decreasing scheduled time

Thus, to paginate backwards from the latest available scheduled time, you would use `dir=b&order_by=send_ts&since_ts=end`.
```

2026-06-01 12:01 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +
How does this sound?

```suggestion

### Rate-limiting for heartbeats

In office environments several clients might share the same public IP address. If the server
rate limits based on IP address and multiple clients use the heartbeat pattern (where a scheduled
delayed event is rescheduled recurringly), it is more likely for them to run into rate limit blocks.
This can result in their delayed event being triggered too early which can negatively affect application
logic. For instance, if the delayed event is a call disconnect event, triggering it too early will result
in unexpected disconnections from the call[^call-rate-limit].

The same problem with rate limiting based on IP address also occurs when an external service
manages delayed events for a large number of users.

[^call-rate-limit]: See also https://github.com/element-hq/element-call/issues/3985.

To mitigate this, the server SHOULD rate limit the management endpoints based on the `delay_id`.
```

2026-06-01 14:12 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +#### Getting a list of delayed events
Andrew and I discussed this out of band and we think a pagination API will be helpful but we'll want to strip the parameters down a little.

2026-06-01 14:23 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +#### Getting a list of delayed events
I'm hesitant to add a bulk retrieval endpoint that doesn't support pagination, even as a temporary measure.

What can be dropped/descoped is the complexity of the filters.  I'll have something for that later today.

(EDIT: this was written before seeing the above comment)

2026-06-01 15:46 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +
This is an accurate & approachable description of the issue.  I also like the idea of recommending a mitigation strategy with SHOULD instead of enforcing one with MUST, as any single approach has drawbacks (as we've seen), so servers should be able to choose whatever approach that works best for its usecase.  Plus, being flexible about it now will reduce friction against introducing an OAuth 2.0 scope for these endpoints, as it would allow enforcing a ratelimit on the scope token without having to replace a previously-specced ratelimit.

2026-06-01 16:05 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +#### Getting a list of delayed events
Done by 88859bdc.

It makes the following simplifications:
- Drop the custom sort options, and instead always sort by the scheduled send time
- Allow restricting results to fall within a specified time range
  - This works together with `dir` to allow dropping the `since_ts` option for having results start from a certain point in time
- Have `status` be the only "property" filter

It also adds some examples to demonstrate the purpose of the filters.

2026-06-01 18:37 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +or as a special-case string of "end" to start from the latest possible results.
IMO 88859bd does now make this endpoint simple enough & gives enough examples to not need extra clarification.

But for completeness, the changes made would alter your explanation to be the following:
- `dir=f&from_ts=X` returns results whose scheduled send time is `>= X` ordered by increasing scheduled time
- `dir=b&to_ts=X` returns results whose scheduled send time is `<= X` ordered by decreasing scheduled time
- To paginate backwards from the latest available scheduled time, you would use `dir=b` without `to_ts`.

2026-06-02 07:13 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +- `status`: `"scheduled"|"send"|"cancel"|"error"` - Return only delayed events that are still scheduled to be sent, or
Cosmetic: One of the actions is a past participle, two are imperatives and the last is a noun. Would there be any point in harmonizing this? For instance, we could make all of them participles:

```suggestion
- `status`: `"scheduled"|"sent"|"cancelled"|"failed"` - Return only delayed events that are still scheduled to be sent, or
```

2026-06-02 07:15 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +or as a special-case string of "end" to start from the latest possible results.
Yes, agreed. This looks clear enough now to me. Thanks for the changes. 👍

2026-06-02 07:15 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +#### Getting a list of delayed events
Thanks, I think this looks great now. 👍

2026-06-02 11:35 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- `status`: `"scheduled"|"send"|"cancel"|"error"` - Return only delayed events that are still scheduled to be sent, or
The grammatical inconsistency was a means to reuse existing terms from elsewhere in the proposal, i.e. `"send"` & `"cancel"` matches `/send` and `/cancel`; and `"error"` matches the `"error"` field in the `GET` payloads.

But given your feedback, and at least one positive reaction from someone else, it looks like this wasn't worth the cost :sweat_smile:  I have no problems with going for the cosmetic route.

2026-06-02 12:05 UTC, benkuly requested changes

2026-06-02 12:05 UTC, benkuly commented on proposals/4140-delayed-events-futures.md
> +### Syncing failed delayed events
Sorry to bring that topic up again.

What exactly is "complicated" about this? From an SDK perspecive re-using the _long_ polling based sync loop instead of a _short_ polling delayed events loop sounds easier and more efficient to do. Usually a sync loop already has all the fail-safety mechanisms implemented, which needs to be re-implemented with the current approach in the MSC making the non-sync approach more complicated. Not having it in a sync also sort of breaks the current concept of the spec, that a sync usually contains everything needed.

Additionally, from a non-MatrixRTC perspecitve ("a wide range of possible
applications such as tea timers, reminders, self-destructing messages,...") getting all (not only failed) delayed events via sync loop has way better UX in most of these use cases with a multi-device setup.

2026-06-02 14:20 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +### Syncing failed delayed events
`/sync` would indeed be ideal, but the concern is that including it now would slow down the approval process & implementations of this MSC, especially since `/sync` support isn't strictly necessary for delayed events to be usable, and adding it later wouldn't conflict with any existing part of this MSC as currently written.  The intent is to eventually have a separate MSC for it.

I've put these thoughts in the MSC itself with e2a3dc34.

2026-06-03 10:32 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +
Looks like a link is missing here.

```suggestion

[MSC4143]: https://github.com/matrix-org/matrix-spec-proposals/pull/4143

```

2026-06-03 10:56 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +`GET /_matrix/client/v1/delayed_events(/{delay_id})?` response.
I think we should generalize this a little now that the listing API extensions live in https://github.com/matrix-org/matrix-spec-proposals/pull/4486.

```suggestion
There is no guarantee for a client that events will be available
if they exceed the limits of their homeserver.
Additionally, a homeserver MAY discard finalised delayed events that have been returned by a
`GET /_matrix/client/v1/delayed_events(/{delay_id})?` response.
```

2026-06-03 11:22 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +This proposal is a general behaviour valid for all event types.
Given the overall length of the proposal, this section still feels slightly too wordy to me. It also refers to widgets which are secondary to the MSC and, I think, should not be mentioned because they are themselves unspecced.

```suggestion
### Sync-loop based heartbeats

[MSC4018: Reliable call membership] was an earlier attempt at making call membership more reliable.
It used the client's sync loop as an indicator to determine if the call membership event is expired.
Conceptually, this is similar to [MQTT]'s "Will Message" that is published by the server when a client
disconnects.

[MSC4018: Reliable call membership]: https://github.com/matrix-org/matrix-spec-proposals/pull/4018
[MQTT]: https://mqtt.org/

The advantage of this approach is that it doesn't require a new system for emitting heartbeats. An API
for letting clients store the leave event to be sent would still be required due to encryption, however.

On the downside, the common timeouts for syncs are much larger than what would be desirable for
call membership (30s vs. 5s). Overall this alternative feels overly implicit and less flexible than the
solution proposed above.
```

2026-06-03 11:24 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +(sent down to clients) them at the appropriate time.
I think we can shorten the formulation here slightly.

```suggestion
Delayed events could be sent over federation immediately to then have the receiving homeservers send them down to clients at the appropriate time.
```

2026-06-03 11:26 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +  to be done.
I think there's a "be" missing here.

```suggestion
- restarts ("heartbeats") would need to be distributed via federation, meaning more traffic and processing
```

2026-06-03 11:28 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +  in the first place.
Nit: Let's make these proper sentences.

```suggestion
- Restarts ("heartbeats") would need to be distributed via federation, meaning more traffic and processing.
- If any homeservers missed the federated "heartbeat"/restart message, then they might decide that the event is visible
  to clients whereas other homeservers might have received it and come to a different conclusion.
  If the event was later cancelled, then resolving the inconsistency feels more complex than if the event was never sent
  in the first place.
```

2026-06-03 11:33 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +disconnect and the delayed message still will enter non-soft-failed state (will be sent).
I think we can shorten this slightly.

```suggestion
If modifying scheduled delayed events is not required, there is a benefit in federating them. It increases
resilience because the sender's homeserver can disconnect and the delayed event will still be delivered to receiving clients by their own homeservers.
```

2026-06-03 11:33 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +or though other means such as by (ab)using typing notification EDUs.
Small typo.

```suggestion
or through other means such as by (ab)using typing notification EDUs.
```

2026-06-09 09:43 UTC, new-years-eve commented on proposals/4140-delayed-events-futures.md
> +- batch size: 10
Batch size has been removed from this MSC.

2026-06-09 15:43 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- batch size: 10
Good catch, thanks.  Removed by 0ae35c4d

2026-06-13 16:46 UTC, new-years-eve commented on proposals/4140-delayed-events-futures.md
> +if, and only if, the client being given the event is authenticated as the event's sender.
Could you help me understand this, please ? The unsigned data is part of the PDU sent to the room, correct ? Its content does not depend on the client receiving it.

2026-06-15 13:40 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +if, and only if, the client being given the event is authenticated as the event's sender.
> The unsigned data is part of the PDU sent to the room, correct ? Its content does not depend on the client receiving it.

Not quite; servers can restrict which fields of a persisted event that a client may receive.  Prior art is how various CS-API endpoints withhold an event's transaction ID from all but the user who sent the event.  This is codified in the spec as responses that include a `transaction_id` field "if the client being given the event is the same one which sent it."

2026-06-16 08:30 UTC, new-years-eve commented on proposals/4140-delayed-events-futures.md
> +if, and only if, the client being given the event is authenticated as the event's sender.
I see. It would be helpful if the spec (and also this MSC) were a bit more clear on how this is done. As it's currently specified, this result could be achieved by putting the field in the PDU and then having the homeserver filter it out if needed when sending it to the client; or by *not* putting it in the PDU, and having the homeserver add it if needed when sending it to the client.

If I understand you correctly, it should be the first one ?

2026-06-16 13:59 UTC, HarHarLinks commented on proposals/4140-delayed-events-futures.md
> +### Additional homeserver behaviour
in my reading, it is implied that when a client sends a delayed event, the server should effectively persist it in some table of delayed events and eventually as the delay runs out persist it from there like a regular event "on the client's behalf". we don't usually have the following problem in matrix, but with this new mechanic it is possible that a server is offline at the time it should send the delayed event. perhaps this MSC should clarify explicitly how servers should handle this case. E.g. the temporary persistence while the event is still delayed should not be ephemeral storage such as RAM, but in a DB table proper. Upon startup a server should then check this table for "missed" delays and do something with the events contained.

2026-06-16 15:26 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +if, and only if, the client being given the event is authenticated as the event's sender.
If I'm not mistaken, PDUs are solely for server-server communication, and thus they don't need to carry `delay_id`s at all due to delayed events not being federated.

> As it's currently specified, this result could be achieved by putting the field in the PDU and then having the homeserver filter it out if needed when sending it to the client

This is pretty much how it's done in Synapse now, except the event is stored as ad-hoc internal representation instead of a "formal" PDU.  When formatting the event in responses, the server decides which fields to include depending on the user requesting it.

2026-06-16 15:31 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +### Additional homeserver behaviour
> it is possible that a server is offline at the time it should send the delayed event. perhaps this MSC should clarify explicitly how servers should handle this case.

Good idea.  The proposal shouldn't be too strict in saying how this should be done, but the bare minimum is for servers to not lose scheduled delayed events.

> Upon startup a server should then check this table for "missed" delays and do something with the events contained.

FTR this is precisely what Synapse does.

2026-06-16 19:59 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +### Additional homeserver behaviour
Added by fcffc2db

2026-06-18 20:19 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- `last_restart` - but this feels less clear than `running_since` for a delayed event that hasn't been restarted
There are no other specced fields ending with `_time`, but plenty with `_ts`.  8fee4cfe renames this to `send_ts`.

2026-06-18 20:28 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- `delay` - Required. A positive non-zero number of milliseconds the homeserver should wait before sending the event.
Is there any interest in renaming this to `delay_ms`, to make it crystal clear that the value is in milliseconds?

If this were to be renamed, then so too should the `delay` field in responses to the `GET` endpoints.

Additionally, the `max_delay` in the [new capability](https://github.com/matrix-org/matrix-spec-proposals/blob/toger5/expiring-events-keep-alive/proposals/4140-delayed-events-futures.md#delayed-event-limits-as-a-capability) would then benefit from being renamed to `max_delay_ms`.

For comparison, the names of most other specced millisecond-valued fields/parameters end with `_ms`, with the following exceptions:
- the `unsigned.age` field in events ([ref](https://spec.matrix.org/v1.18/client-server-api/#room-event-format))
- the `timeout` query parameter for `/sync` ([ref](https://spec.matrix.org/v1.18/client-server-api/#syncing))
  - Amusingly, there is also a parameter named `timeout_ms` used by the Content Repository module ([ref](https://spec.matrix.org/v1.18/client-server-api/#content-repo-client-behaviour))
- the `info.duration` field in `m.audio` & `m.video` events ([ref](https://spec.matrix.org/v1.18/client-server-api/#mroommessage-msgtypes))
- the `lifetime` field in `m.call.invite` and `m.call.negotiate` events ([ref](https://spec.matrix.org/v1.18/client-server-api/#events-4))
- the `timeout` body parameter in `/typing/{userId}` ([ref](https://spec.matrix.org/v1.18/client-server-api/#client-behaviour-4))
- The `last_active_ago` field in `m.presence` events ([ref](https://spec.matrix.org/v1.18/client-server-api/#events-9))

2026-06-18 20:29 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +Some alternatives for the `running_since` field on the `GET` response are:
At the risk of bikeshedding, how does `scheduled_at` sound?  Or at least something suffixed with `_at`, which the spec uses for a few other timestamp-valued fields.

I also feel that `scheduled_at` is less likely than `scheduled_ts` to be misinterpreted as the intended send time of the event, and thus is a good opportunity to put `scheduled` in the name, which is an existing keyword used elsewhere in this module, instead of having to introduce a new term (like "running" or "created").

2026-06-24 16:44 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- `delay` - Required. A positive non-zero number of milliseconds the homeserver should wait before sending the event.
Done by fd27ef00.

2026-06-24 16:44 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +Some alternatives for the `running_since` field on the `GET` response are:
Made the leap to prefer `scheduled_at` with f1845796.

2026-06-25 07:22 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +Some alternatives for the `running_since` field on the `GET` response are:
I've documented this in the known implementation differences in the PR description (and hopefully did so correctly).

2026-06-25 07:22 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +- `delay` - Required. A positive non-zero number of milliseconds the homeserver should wait before sending the event.
I've documented this in the known implementation differences in the PR description (and hopefully did so correctly).

2026-06-26 18:11 UTC, turt2live approved these changes
Overall this looks good to go for FCP - thank you! (and sorry for the review delay)

Before I send it into that stage though, I'd like to see the query string argument alternative explored a bit more. I'm hoping this is as easy as linking to a (rejected/reverted) PR which added such functionality, but it could also be notes from a team discussion which backs up the claim that it's difficult to do. If there's prior conversation on this MSC about it, linking to those threads would also be good. 

For a bit of process visibility: I'm going to ask the Security team to look at this MSC too. There are novel authentication mechanisms introduced here which need a more qualified opinion.

2026-06-26 18:11 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +and supports [timestamp massaging](https://spec.matrix.org/latest/application-service-api/#timestamp-massaging)
```suggestion
and supports [timestamp massaging](https://spec.matrix.org/v1.18/application-service-api/#timestamp-massaging)
```

"latest" can change without notice and break historical links - we prefer that MSCs use a tagged spec release instead.

2026-06-26 18:11 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +a [standard error response](https://spec.matrix.org/latest/client-server-api/#standard-error-response)
```suggestion
a [standard error response](https://spec.matrix.org/v1.18/client-server-api/#standard-error-response)
```

2026-06-26 18:11 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +to event scheduling requests with HTTP 400 and a standard error response with an `errcode` of `M_UNKNOWN`.
Shouldn't this be `M_FORBIDDEN` as the maximum delay condition is impossible to satisfy?

2026-06-26 18:11 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_INVALID_PARAM`.
```suggestion
The homeserver MAY enforce a maximum allowed delay for delayed events. This limit is
communicated to the client in a capability (described later in this proposal).
If a requested delay exceeds this maximum, the homeserver will respond with HTTP 400
and a [standard error response](https://spec.matrix.org/v1.18/client-server-api/#standard-error-response)
with an `errcode` of `M_INVALID_PARAM`.
```

to clarify that the MSC doesn't really suggest a limit, but the limit is known to clients so they aren't left completely in the dark about what is "acceptable".

2026-06-26 18:11 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +and a [standard error response](https://spec.matrix.org/latest/client-server-api/#standard-error-response)
```suggestion
and a [standard error response](https://spec.matrix.org/v1.18/client-server-api/#standard-error-response)
```

2026-06-26 18:11 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +and a [standard error response](https://spec.matrix.org/latest/client-server-api/#standard-error-response)
```suggestion
and a [standard error response](https://spec.matrix.org/v1.18/client-server-api/#standard-error-response)
```

2026-06-26 18:11 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +and a [standard error response](https://spec.matrix.org/latest/client-server-api/#standard-error-response)
```suggestion
and a [standard error response](https://spec.matrix.org/v1.18/client-server-api/#standard-error-response)
```

2026-06-26 18:11 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +and a [standard error response](https://spec.matrix.org/latest/client-server-api/#standard-error-response)
```suggestion
and a [standard error response](https://spec.matrix.org/v1.18/client-server-api/#standard-error-response)
```

2026-06-26 18:11 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +  Using [timestamp massaging](https://spec.matrix.org/latest/application-service-api/#timestamp-massaging)
```suggestion
  Using [timestamp massaging](https://spec.matrix.org/v1.18/application-service-api/#timestamp-massaging)
```

2026-06-26 18:11 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +it would make it transparent to clients, when an event was scheduled and when it was distributed over federation.
It's a little surprising to see this section here because the referenced MSC is a draft and in a much earlier stage of the process. Typically, this would mean it's MSC4080's problem to be compatible with this MSC rather than the other way around, though considerations in this MSC are certainly welcome where they make sense/are easy to do. I would suggest reducing the amount of page space we give to it however. 

```suggestion
### Compatibility with Cryptographic Identities

Proposals like [MSC4080](https://github.com/matrix-org/matrix-spec-proposals/pull/4080)
enable a client to verify that an event was *actually* sent by the sender's devices. This
proposal shouldn't affect how that verification works because those other proposals will
need to account for eventual consistency anyway, which may appear as a delayed event or
attached to a disjointed part of the DAG.
```

2026-06-26 18:11 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +which defies the usual semantics of a URI query.
We already use query strings for non-filtering purposes, so this doesn't hold up. If it's expected to stay in the proposal, a citation would be needed. (I'd suggest just removing the sentence.)

2026-06-26 18:11 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +However, this could be negated by the complexity of having to support multiple response body formats.
Do we have evidence of this being attempted? It seems like a great alternative (we aren't that worried about different response formats, generally speaking).

2026-06-26 18:11 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +[MQTT]: https://mqtt.org/
```suggestion
Conceptually, this is similar to [MQTT's "Will Message"] that is published by the server when a client
disconnects.

[MSC4018: Reliable call membership]: https://github.com/matrix-org/matrix-spec-proposals/pull/4018
[MQTT's "Will Message"]: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901040
```

Linking to spec is always better than not :)

2026-06-26 18:11 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +### Syncing failed delayed events
(+1 to pushing syncing failed delayed events out to its own MSC if/when needed rather than build it up front)

2026-06-29 07:12 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +It can even be used to send temporal power levels/mutes or bans.
This landed.

2026-06-29 07:13 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +## Use case specific considerations
This landed.

2026-06-29 07:28 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +However, this could be negated by the complexity of having to support multiple response body formats.
The currently merged implementations (https://github.com/element-hq/synapse/pull/17326 & https://github.com/matrix-org/matrix-js-sdk/pull/4294) use query strings. There are follow-up unmerged PRs that switch to dedicated endpoints (https://github.com/element-hq/synapse/pull/19354 & https://github.com/matrix-org/matrix-js-sdk/pull/5133).

2026-06-29 07:29 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +which defies the usual semantics of a URI query.
Addressing comment from https://github.com/matrix-org/matrix-spec-proposals/pull/4140/changes#r3483208622.

```suggestion
```

2026-06-29 17:29 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +However, this could be negated by the complexity of having to support multiple response body formats.
hmm, I'm worried that there's seemingly viable implementations for both the MSC and the alternative. Where was the motivation to switch to a dedicated endpoint discussed? (links please)

2026-06-30 14:13 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +However, this could be negated by the complexity of having to support multiple response body formats.
Mentioned on a call: there was a discussion thread a few months ago which requested the split. On the call, multiple teams nodded in approval to the sentiments of having a different endpoint.

The ask is to incorporate a link into the MSC for that discussion, and include context in case links break/change (again).

2026-06-30 14:21 UTC, turt2live commented
With the assumption that the alternative gets further information added into the MSC, this appears ready to go (though there's no comments on the [M_FORBIDDEN thread](https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r3483103991) 😇)

@mscbot fcp merge

2026-06-30 14:25 UTC, turt2live commented
MSCs proposed for Final Comment Period (FCP) should meet the requirements outlined in the [checklist](https://github.com/matrix-org/matrix-spec-proposals/blob/main/MSC_CHECKLIST.md) prior to being accepted into the spec. This checklist is a bit long, but aims to reduce the number of follow-on MSCs after a feature lands. 

SCT members: please check off things you check for, and raise a concern against FCP if the checklist is incomplete. If an item doesn't apply, prefer to check it rather than remove it. Unchecking items is encouraged where applicable.

MSC authors: feel free to ask *in a thread* on your MSC or in the[#matrix-spec:matrix.org](https://matrix.to/#/#matrix-spec:matrix.org) room for clarification of any of these points.

- [x] Are [appropriate implementation(s)](https://spec.matrix.org/proposals/#implementing-a-proposal) specified in the MSC’s PR description?
- [x] Are all MSCs that this MSC depends on already accepted?
- [x] For each new endpoint that is introduced:
  - [x] Have authentication requirements been specified?
  - [x] Have rate-limiting requirements been specified?
  - [x] Have guest access requirements been specified?
  - [x] Are error responses specified?
    - [x] Does each error case have a specified `errcode` (e.g. `M_FORBIDDEN`) and HTTP status code?
      - [x] If a new `errcode` is introduced, is it clear that it is new?
- [x] Will the MSC require a new room version, and if so, has that been made clear?
  - [x] Is the reason for a new room version clearly stated? For example, modifying the set of redacted fields changes how event IDs are calculated, thus requiring a new room version.
- [x] Are backwards-compatibility concerns appropriately addressed?
- [x] Are the [endpoint conventions](https://spec.matrix.org/latest/appendices/#conventions-for-matrix-apis) honoured?
  - [x] Do HTTP endpoints `use_underscores_like_this`?
  - [x] Will the endpoint return unbounded data? If so, has pagination been considered?
  - [x] If the endpoint utilises pagination, is it consistent with [the appendices](https://spec.matrix.org/latest/appendices/#pagination)?
- [x] An introduction exists and clearly outlines the problem being solved. Ideally, the first paragraph should be understandable by a non-technical audience.
- [x] All outstanding threads are resolved
  - [x] All feedback is incorporated into the proposal text itself, either as a fix or noted as an alternative
- [x] While the exact sections do not need to be present, the details implied by the proposal template are covered. Namely:
  - [x] Introduction
  - [x] Proposal text
  - [x] Potential issues
  - [x] Alternatives
  - [x] Dependencies
- [x] Stable identifiers are used throughout the proposal, except for the unstable prefix section
  - [x] Unstable prefixes [consider](https://github.com/matrix-org/matrix-spec-proposals/blob/main/README.md#unstable-prefixes) the awkward accepted-but-not-merged state
  - [x] Chosen unstable prefixes do not pollute any global namespace (use “org.matrix.mscXXXX”, not “org.matrix”).
- [x] Changes have applicable [Sign Off](https://github.com/matrix-org/matrix-spec-proposals/blob/main/CONTRIBUTING.md#sign-off) from all authors/editors/contributors
- [x] There is a dedicated "Security Considerations" section which detail any possible attacks/vulnerabilities this proposal may introduce, even if this is "None.". See [RFC3552](https://datatracker.ietf.org/doc/html/rfc3552) for things to think about, but in particular pay attention to the [OWASP Top Ten](https://owasp.org/www-project-top-ten/).

2026-06-30 15:38 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +However, this could be negated by the complexity of having to support multiple response body formats.
955ecf5d adds a link to the criticisms of the shared endpoint that motivated the move to a dedicated endpoint, and expands upon it lest the deep link gets lost & so that the MSC alone may be sufficient in communicating what the criticisms were.

2026-06-30 15:39 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +to event scheduling requests with HTTP 400 and a standard error response with an `errcode` of `M_UNKNOWN`.
Sure.  I was under the impression that `M_FORBIDDEN` was to be used only for insufficient permissions.

On that note, I thought the same was true for HTTP 403 as well, but it turns out that it can be used for "reasons unrelated to the credentials [of the request]" ([reference](https://www.rfc-editor.org/info/rfc9110/#status.403)).

So it may be most appropriate for this error response to use both `M_FORBIDDEN` and HTTP 403.  That change is made by d91a9321.

2026-06-30 15:47 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_INVALID_PARAM`.
To go even further with https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r3483103991, how about returning `M_FORBIDDEN` & HTTP 403 even for this case of requesting a delay longer than allowed?

This would prevent needing a special case error response for delayed events being entirely disallowed, as both that case & this one would then both give the same response.

It also looks like the spec uses `M_INVALID_PARAM` only for parameter values that are _always_ invalid (like a malformed room alias or MXID), as opposed to values that are disallowed by server config that may change later.

2026-06-30 15:56 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_INVALID_PARAM`.
Erm, actually, the special case would still be needed for when the maximum per-user amount of delayed events is 0, lest the response would be `M_LIMIT_EXCEEDED` & HTTP 429 for a limit that can never be satisfied.

But the point stands about `M_FORBIDDEN` & HTTP 403 potentially being more appropriate than `M_INVALID_PARAM` / HTTP 400.

2026-06-30 18:18 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_INVALID_PARAM`.
In the interest of progressing with the Synapse implementation of MSC4140 error codes ([PR](https://github.com/element-hq/synapse/pull/19539)), I've committed this change as 9447ee01.

I've also updated the PR description accordingly.

2026-07-01 05:37 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_INVALID_PARAM`.
> But the point stands about `M_FORBIDDEN` & HTTP 403 potentially being more appropriate than `M_INVALID_PARAM` / HTTP 400.

This sounds sensible to me.

2026-07-06 15:13 UTC, gewitternacht commented on proposals/4140-delayed-events-futures.md
> +It MUST be globally unique and SHOULD be cryptographically secure (in the sense that it is infeasible to predict).
There's a mismatch here with the wording in the `Security considerations – Authentication` section below, which says
> As such, generated `delay_id`s MUST be cryptographically random such that they are difficult to guess.

1. "cryptographically _random_" vs. "cryptographically _secure_" – I think a more accurate and unambiguous wording in both places would be something like
    > generated using a CSPRNG (Cryptographically Secure Pseudorandom Number Generator) and has sufficient entropy

2. MUST vs. SHOULD – I would change the SHOULD here to MUST, because that's what the authentication for these endpoints through knowledge of `delay_id` relies on.

2026-07-06 15:13 UTC, gewitternacht commented on proposals/4140-delayed-events-futures.md
> +It MUST be globally unique and SHOULD be cryptographically secure (in the sense that it is infeasible to predict).
What is "globally" here? Depending on the answer, I'm not sure how the homeserver is able to ensure this uniqueness?

2026-07-06 15:13 UTC, gewitternacht commented on proposals/4140-delayed-events-futures.md
> +with the cryptographic security of the `delay_id` preventing unapproved access to the delayed event.
> may be provided to approved external services

> preventing unapproved access

This does not make clear: un/approved by whom?

I guess the approval is supposed to be that of the user who sent the delayed event – but in practice, anyone that got hold of the `delay_id` once can forward it to others, including e.g. the homeserver. So I would argue that "approved external services" is a bit confusing, and "preventing unapproved access" overstates the security guarantees the `delay_id` can provide.

2026-07-06 15:13 UTC, gewitternacht commented on proposals/4140-delayed-events-futures.md
> +The client would share the `delay_id` and the required details, so that the SFU can call the
What are the "required details" other that the `delay_id`, purely from the perspective of being able to call the necessary endpoint?

If there indeed are such additional required details, it could be good to spell them out here; conversely, if these details are only technical, SFU-specific ones not really to do with the delayed event management itself, the "and the required details" part could probably be omitted to avoid confusion.

2026-07-06 15:13 UTC, gewitternacht commented on proposals/4140-delayed-events-futures.md
> +`POST /delayed_events/{delay_id}/refresh` endpoint while a user is connected
I suppose `/refresh` is from an older version of this MSC, and it should really be `/restart` here?

2026-07-06 15:13 UTC, gewitternacht commented on proposals/4140-delayed-events-futures.md
> +details on the delayed event with the specified `delay_id` owned by the requesting user.
There's a sort of duplicate authentication here: That of the requesting user via the standard authenticated endpoint mechanism, and through knowledge of the `delay_id` as explained in this MSC. While the management endpoints above only check for the latter, this `GET` endpoint should also check that the requesting, authenticated user owns the specified `delay_id`. This is somewhat suggested by the wording "the specified `delay_id` owned by the requesting user", but not entirely clear. I think it should be made explicit what happens if the given `delay_id` exists, but is not owned by the requesting user.

2026-07-06 15:13 UTC, gewitternacht commented on proposals/4140-delayed-events-futures.md
> +## Security considerations
An aspect I'm missing here is the fact that the `POST /delayed_events/{delay_id}/{action}` and `GET /_matrix/client/v1/delayed_events/{delay_id}` endpoints are including the `delay_id`, which is aptly described to "behave as a scoped access token". This risks a `delay_id`, i.e. an access token, getting leaked to various logs.

Can this risk be avoided / reduced by putting the `delay_id` in a header field or the request body instead? If there's technical reasons to not do that, this should at least be mentioned in the Security Considerations.

2026-07-06 15:13 UTC, gewitternacht commented on proposals/4140-delayed-events-futures.md
> +if, and only if, the client being given the event is authenticated as the event's sender.
I'm also quite confused by this paragraph. I might be missing some general background knowledge, but I think what might be missing is a mention of the context that "the client being given the event" happens in. It's also not made explicit that the homeserver (I guess?) is doing the "giving" here.

2026-07-07 05:44 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +It MUST be globally unique and SHOULD be cryptographically secure (in the sense that it is infeasible to predict).
Yeah, I can see how this might be slightly ambiguous. In my understanding, "globally" refers to the realm of the home server here. That is to say, when generating delay IDs, the server must take care to not produce collisions with other IDs for delayed events that it has currently stored. There is no requirement to keep delay IDs unique across home servers.

Does this make it more clear?

```suggestion
It MUST be unique with respect to the server's stored delayed events and SHOULD be cryptographically secure (in the sense that it is infeasible to predict).
```

2026-07-07 05:51 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +with the cryptographic security of the `delay_id` preventing unapproved access to the delayed event.
Yes, it's meant to be the client's choice what services it deems "approved" for delegating delayed event management to. Also agree on the potential overstating of the security guarantees.

Does this make it clearer?

```suggestion
This way, clients MAY share the `delay_id` with external services to allow delegated management of
their delayed events through the unauthenticated management endpoints introduced
[below](#managing-scheduled-delayed-events). The cryptographic security of the `delay_id` mitigates
unauthorized access to the delayed event.
```

2026-07-07 05:57 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +The client would share the `delay_id` and the required details, so that the SFU can call the
Depending on how the external service is set up, other required details could for instance be the server name of the client's homeserver. The service needs to know this in order to determine what server to call the endpoints on.

```suggestion
The client would share the `delay_id` and other possibly required details (such as its homeserver's server name), so that the SFU can call the
```

2026-07-07 05:59 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +`POST /delayed_events/{delay_id}/refresh` endpoint while a user is connected
Indeed. Good catch!

```suggestion
`POST /delayed_events/{delay_id}/restart` endpoint while a user is connected
```

2026-07-07 06:20 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +## Security considerations
I suspect the main reason is that in the path in makes for a very natural REST API shape.

I think putting it into the body would require changing `GET /_matrix/client/v1/delayed_events/{delay_id}` to POST. It's not as nice an API but would probably work.

As a header, we could leave the HTTP method unchanged. The API shape strikes me as equally odd but technically it should also be possible.

@AndrewFerr curious what you think? Have I missed any reasons why this needs to be in the path?

2026-07-07 06:26 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +if, and only if, the client being given the event is authenticated as the event's sender.
In my understanding, this only applies when a homeserver hands out the event to its local users, e.g. via `/sync` or `/messages`. Maybe it's sufficient to mention these endpoints as examples?

```suggestion
if, and only if, the client being given the event (e.g. over `/sync` or `/messages`) is authenticated as the event's sender.
```

2026-07-07 07:23 UTC, gewitternacht commented on proposals/4140-delayed-events-futures.md
> +It MUST be globally unique and SHOULD be cryptographically secure (in the sense that it is infeasible to predict).
This makes sense and makes it clearer :+1:

2026-07-07 07:32 UTC, gewitternacht commented on proposals/4140-delayed-events-futures.md
> +if, and only if, the client being given the event is authenticated as the event's sender.
yes that makes it clearer to me already 👍

2026-07-07 08:26 UTC, gewitternacht commented on proposals/4140-delayed-events-futures.md
> +with the cryptographic security of the `delay_id` preventing unapproved access to the delayed event.
Yes, this conveys better what's actually possible in my mind.

The only thing I'm not too sure about is the "The *cryptographic security* of the `delay_id`" part, it reads a bit weird (relating to [my comment](https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r3529519943) above). But this fits better into the other discussion, I'm adding a comment there.

2026-07-07 08:40 UTC, gewitternacht commented on proposals/4140-delayed-events-futures.md
> +It MUST be globally unique and SHOULD be cryptographically secure (in the sense that it is infeasible to predict).
A bit later, "the *cryptographic security* of the `delay_id`" is mentioned again, which reads a bit weird to me. Alternatives that would sound better to me are for example
- the CSPRNG-generated `delay_id`, or
- the cryptographic randomness of the `delay_id`, or
- the unpredictability of the `delay_id`.

2026-07-07 08:55 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +with the cryptographic security of the `delay_id` preventing unapproved access to the delayed event.
Good point. Out of the options in the other thread, "cryptographic randomness" sounds best to me here because it avoids us having to spell out the acronym again.

```suggestion
This way, clients MAY share the `delay_id` with external services to allow delegated management of
their delayed events through the unauthenticated management endpoints introduced
[below](#managing-scheduled-delayed-events). The cryptographic randomness of the `delay_id` mitigates
unauthorized access to the delayed event.
```

2026-07-07 08:56 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +It MUST be globally unique and SHOULD be cryptographically secure (in the sense that it is infeasible to predict).
> A bit later, "the _cryptographic security_ of the `delay_id`" is mentioned again, which reads a bit weird to me. Alternatives that would sound better to me are for example
> 
>     * the CSPRNG-generated `delay_id`, or
> 
>     * the cryptographic randomness of the `delay_id`, or
> 
>     * the unpredictability of the `delay_id`.

This part was resolved in https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/5dac49c7d5f4bb7de5f4dce8733c576e9f5df291. The original comment above is still open though.

2026-07-08 13:50 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +## Security considerations
Yes, the main reason is to be able to use the `delay_id` as a typical "identifier" token.

Besides, there's limited effectiveness in trying to hide a `delay_id` by moving it into request headers / body / elsewhere, because it will nevertheless appear in client logs via `/sync` responses once its associated event gets sent, as per [`delay_id` in `unsigned` event data](https://github.com/matrix-org/matrix-spec-proposals/blob/toger5/expiring-events-keep-alive/proposals/4140-delayed-events-futures.md#delay_id-in-unsigned-event-data).

2026-07-08 14:19 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +details on the delayed event with the specified `delay_id` owned by the requesting user.
The current wording does intend to convey that requests for a `delay_id` belonging to another user will respond with 404.

b75b9fc7 rewords this to try to make it more clear.

2026-07-08 14:30 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +if, and only if, the client being given the event is authenticated as the event's sender.
> Maybe it's sufficient to mention these endpoints as examples?

2f3b817c now includes those examples.

2026-07-09 07:57 UTC, gewitternacht commented on proposals/4140-delayed-events-futures.md
> +## Security considerations
> it will nevertheless appear in client logs via /sync responses once its associated event gets sent

But once the event gets sent, is there even a need to keep the `delay_id` secret any longer? Aren't all of the `delay_id`'s access token capabilities void once the respective event is finalised?

See this part of the MSC:
> If the target delayed event is already finalised with an outcome that conflicts with the action, i.e. if the action is send or restart and the delayed event has already been cancelled, or if the action is cancel and the delayed event has already been sent, the homeserver will respond with HTTP 409 and a [standard error response](https://spec.matrix.org/v1.18/client-server-api/#standard-error-response) with an errcode of M_UNKNOWN.

2026-07-10 17:38 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +## Security considerations
> But once the event gets sent, is there even a need to keep the delay_id secret any longer? Aren't all of the delay_id's access token capabilities void once the respective event is finalised?

Good point, that's correct.

In the interest of unblocking this, I'll split off the delegation feature into its own MSC. For now, I've moved it to an alternative: cd878d21

---

With that out of the way, I'll say that I'm still hesitant to protect `delay_id`s as much as access tokens, for a few reasons:
- It would preclude future endpoints from being able to use `delay_id`s in ways that would "leak" them by design.  A realistic possible addition is for `/sync` to include information about newly-scheduled delayed events (so that clients other than the one that scheduled an event would be notified of it, instead of having to manually hit the lookup endpoint to discover it).
- It may add friction against migrating to using OAuth 2.0 scopes for the management endpoints.

2026-07-13 09:18 UTC, gewitternacht commented on proposals/4140-delayed-events-futures.md
> +## Security considerations
With the delegation removed from this MSC, and the management endpoints being authenticated, I'm obviously fine with the security considerations in this MSC :+1: 

I'd be interested to see the additional delegation MSC when it's ready though – especially how it plans to deal with the authentication for the management endpoints prescribed in this MSC – and I think it would be good the mention the concerns form your comment about the handling of the `delay_id` there.

2026-07-21 05:17 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +It MUST be globally unique and SHOULD be cryptographically secure (in the sense that it is infeasible to predict).
This is obsolete now that delegation has been descoped from the MSC (https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/cd878d211fc855951e79cbb940bd68c304eecc87).

2026-07-22 20:09 UTC, turt2live commented
This looks ready for broader SCT review, even with designated review not being fully complete. SCT members are encouraged to review this MSC.

2026-07-24 10:45 UTC, tulir approved these changes

2026-07-24 10:45 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +`GET /_matrix/client/v1/delayed_events/{delay_id}` response.
This sounds kind of dangerous from a request retrying perspective since network errors can cause responses to be lost. I guess storing finalized events is best-effort anyway and clients shouldn't rely on any of them being stored?

2026-07-24 10:45 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_INVALID_PARAM`.
`M_FORBIDDEN` for a parameter exceeding a limit sounds weird, maybe it should just be a new dedicated error code instead?

2026-07-24 10:45 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +
The opening paragraph has multiple use cases, but there are also various limits that could interfere with clients actually using this for all those use cases. For example, if a server sets a low pending delayed event limit, then a client uses delayed events for self-destructing messages, would calls just fail because the user's limit is used up?

The 429 behavior is also mildly scary if clients aren't smart enough to ignore too long Retry-After fields (like if all the delayed events are for scheduled or self-destructing messages in 3 months, starting a call might just get stuck in a `sleep()`). That's mostly a client implementation concern though, the MSC is probably fine as is.

I'm not sure if it should be fixed in this MSC or just documented as a possible alternative/future MSC. The fix would probably be having the server tell the client what use case it's targeting so the server can have per-use-case limits

2026-07-27 14:57 UTC, dbkr commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_FORBIDDEN`.
Not critically important but 403 seems slightly odd in this case as implies the user might be able to do it if they had more rights, which probably isn't going to be the case.

2026-07-27 14:57 UTC, dbkr commented on proposals/4140-delayed-events-futures.md
> +To support batch sending, homeservers MAY add up to 30 seconds to the scheduled send time.
This doesn't really match up with the 'tea timer' use case suggested in the opening section. Probably the right fix here is to just accept that's not really a use case.

2026-07-27 14:57 UTC, dbkr commented on proposals/4140-delayed-events-futures.md
> +and send those delayed events as soon as possible, in chronological order of their scheduled send times.
These are implementation details for the homeserver ( and I don't think they're relevant for the spec. I think the spec should just say that HS's job is to deliver the events at the right time and it's the job of the HS implementer to make that happen. They can go in as additional / non-normative info if we think it's helpful.

2026-07-27 14:57 UTC, dbkr commented on proposals/4140-delayed-events-futures.md
> +the homeserver will instead respond with HTTP 403 and a standard error response with an `errcode` of `M_FORBIDDEN`.
Again, not sure 403 feels right here, and likewise 429, whilst technically correct since the client can wait until the next event is sent, feels a bit weird.

2026-07-27 14:57 UTC, dbkr commented on proposals/4140-delayed-events-futures.md
> +If the server doesn't enforce one of these limits, its representative field MUST be absent from the capability.
Seems odd that it only specifies this MUST one way around, ie. it must be absent if not enforced but implies that it may be enforced but not present, or is the capability intentionally optional?

2026-07-27 14:57 UTC, dbkr commented on proposals/4140-delayed-events-futures.md
> +- `restart` - Reset the delayed event's scheduled send time to be the current time + its original `delay_ms`.
This ties in with another thread but why not just have a way to update the delay on an event, then you could update it back to what it originally was (equivalent to restart) or update it to 0 (equivalent to send, except it wouldn't make sense to report sending errors back).

Also, there are idempotency issues here I think, either with updating the event's scheduled time or the plain 'restart': if a request is re-sent, does it restart the timer again or is it ignored for idempotency? This may need some kind of sequence number to differentiate separate requests from retries.

2026-07-27 14:57 UTC, dbkr commented on proposals/4140-delayed-events-futures.md
> +Note: clients might find that their events are delayed further due to server load and similar conditions.
Here might be a good place to also mention that the same rate limits will apply as if the client sent the events in the standard way at the time.

2026-07-27 14:57 UTC, dbkr commented on proposals/4140-delayed-events-futures.md
> +It then becomes the user's responsibility to fetch this error and retry sending the event as appropriate.
This seems odd? Why? I think I would expect it to be retried, otherwise this makes the mechanism a chunk less reliable if it might also fail permanently due to transient rate limiting.

2026-07-27 14:57 UTC, dbkr commented on proposals/4140-delayed-events-futures.md
> +doesn't allow querying finalised delayed events. This could be limiting in some cases. A future proposal
> It also doesn't allow querying finalised delayed events

Could you clarify this sentence - I'm not sure exactly what it's saying (unless it's fetching only finalised events, but isn't that the same as filtering?)

2026-07-27 14:57 UTC, dbkr commented on proposals/4140-delayed-events-futures.md
> +`POST /delayed_events/{delay_id}/send` requests when it detects a disconnecting client.
Honestly I suspect if we were to delegate this to the SFU, the sensible approach would to just let the SFU send the hangup sent in the normal way which would be much simpler: it ought to be reliable enough.

2026-07-27 14:57 UTC, dbkr commented on proposals/4140-delayed-events-futures.md
> +## Potential issues
A fairly significant potential issue in using this for VoIP hangups is that a client now needs to be able to make regular, timely HTTP requests to not get a call hung up. I frequently make calls in network conditions that are fine for getting UDP voice packets through but don't work for making a small HTTP request.

2026-07-27 15:52 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +`GET /_matrix/client/v1/delayed_events/{delay_id}` response.
> I guess storing finalized events is best-effort anyway and clients shouldn't rely on any of them being stored?

Correct.

Eventually, finalized delayed events should appear in `/sync` responses (and appservice transactions), which will reliably communicate them.

2026-07-27 15:52 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +
> For example, if a server sets a low pending delayed event limit, then a client uses delayed events for self-destructing messages, would calls just fail because the user's limit is used up?
>
> The 429 behavior is also mildly scary if clients aren't smart enough to ignore too long Retry-After fields (like if all the delayed events are for scheduled or self-destructing messages in 3 months, starting a call might just get stuck in a sleep()).

I suppose in cases like that, it's the client's responsibility to be proactive in checking server capabilities to verify that a desired usecase is feasible.  Then all that'd be required from this MSC is to ensure that enough capabilities are exposed for such checking, which IMO they already are.

2026-07-27 15:52 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_INVALID_PARAM`.
A dedicated error code was the original plan, but was decided against after opting to express the max-allowed delay in a capability: https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r3257895622, https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r3259516213.

There is also precedent of the spec using `M_FORBIDDEN` for disallowed parameter values, like an invalid password or login token for the [user-interactive login API](https://spec.matrix.org/latest/client-server-api/#user-interactive-api-in-the-rest-api), and an unsupported media type for [the media upload endpoint](https://spec.matrix.org/latest/client-server-api/#put_matrixmediav3uploadservernamemediaid).

2026-07-27 16:08 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_FORBIDDEN`.
I thought so too at first, but it turns out 403 can be used for more than auth errors / insufficient privileges: https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r3500003217

2026-07-27 16:09 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +To support batch sending, homeservers MAY add up to 30 seconds to the scheduled send time.
Sure.  The only way to properly support a "tea timer" would be to reduce the allowed delay of scheduled send times, but that would put extra load / obligations on servers that might not always be satisfiable in practice.  So it is safer to simply not suggest that scheduled sent times are accurate enough for timer usecases.

Removed by e5f656b3

2026-07-27 16:15 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +If the server doesn't enforce one of these limits, its representative field MUST be absent from the capability.
The intention is for the fields to be present if and only if their respective limit is enforced.

15770e69 tries to make that explicit.

2026-07-27 16:21 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_INVALID_PARAM`.
Personally I'd err towards adding new error codes even if they're not technically necessary, rather than reusing existing codes in a potentially confusing way. I don't feel too strongly about that though, so either way is fine

> an unsupported media type for [the media upload endpoint](https://spec.matrix.org/latest/client-server-api/#put_matrixmediav3uploadservernamemediaid)

not related to this MSC, but ???? HTTP 415 exists

2026-08-04 01:24 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +- `content` - Required. The content of the event to be sent.
Having a very different body than `/send` but the same path is very confusing.

It seems like it would be better to mirror the existing `/send` and `/state` endpoints (or not even bother with `/state` if it isn't needed yet).

2026-08-04 01:24 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +To support batch sending, homeservers MAY add up to 30 seconds to the scheduled send time.
Why does this need to batch sending? It seems very at odds with the feature.

2026-08-04 01:24 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +and send those delayed events as soon as possible, in chronological order of their scheduled send times.
Agreed, this section is very odd to include here.

2026-08-04 01:24 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_FORBIDDEN`.
This seems like both the wrong status code and wrong error code. I'd expect 400, unsure about the error code.

2026-08-04 01:24 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +rounded up to the nearest second.
`M_USER_LIMIT_EXCEEDED` seems to the the standard error code?

This should be a 400.

2026-08-04 01:24 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +the homeserver will instead respond with HTTP 403 and a standard error response with an `errcode` of `M_FORBIDDEN`.
Why special case this at all?

2026-08-04 01:24 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_NOT_FOUND`.
It is implied by other areas, but not explicit here that these are user scoped.

2026-08-04 01:24 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_FORBIDDEN` if the user doesn't have permission to send the event at the time of sending,
This doesn't match what the `/send` endpoint would do.

2026-08-04 01:24 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +both scheduled and finalised delayed events owned by the requesting user.
No rationale is provided for why you need finalized events from these APIs.

2026-08-04 01:24 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +  last restarted.
`scheduled_ts` would fit existing fields better.

2026-08-04 01:24 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +- `delay_ms` - Required. The delay in milliseconds after the point of scheduling that the event is/was to be sent at.
Is this useful or do clients actually want to know how many milliseconds until the event is sent? Time drift between servers and clients is a real thing.

2026-08-04 01:24 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +- Otherwise, the delayed event was cancelled by [the `/cancel` endpoint](#managing-scheduled-delayed-events).
This seems like a really hard response to fit into an OpenAPI definition. There's a lot of optional fields, etc.

2026-08-04 01:24 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +sending. If the power level situation has changed at the time the delay passes, the event can even reach the DAG.
Why? What's the use case for this?

2026-08-04 01:24 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +#### Power levels are evaluated at the point of sending
What about all the other ways events can fail validation?

2026-08-04 01:24 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +of delayed messages at the point that they are inserted into the DAG.
"further to" is confusing:

```suggestion
In addition to the rate limiting of the API endpoints, the homeserver SHOULD apply rate limiting to the sending
of delayed messages at the point that they are inserted into the DAG.
```

2026-08-04 01:24 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +### Conflicting delayed state events
Do we even need this feature for state events today? This seems like a big foot gun without a use case.

2026-08-04 01:24 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +### Inability to filter and paginate delayed events
Leaving pagination to a future proposal is not acceptable IMO.

@mscbot concern List endpoint is unbounded and needs pagination.

2026-08-04 01:24 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +of time.
Is this the only field stopping event ID calculation?

2026-08-04 08:30 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +- `content` - Required. The content of the event to be sent.
The MSC isn't using the same path? That was an older revision, but it was replaced with a dedicated /delayed_events path

2026-08-04 08:34 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +To support batch sending, homeservers MAY add up to 30 seconds to the scheduled send time.
If the user (or different users) schedule multiple events at timestamps close to each other, the homeserver may want to batch the sends together for efficiency reasons

2026-08-04 08:36 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +of time.
prev_events and auth_events are also not known ahead of time and we don't want to mess up the DAG

2026-08-04 12:32 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +- `content` - Required. The content of the event to be sent.
> The MSC isn't using the same path?

Yes, but it purposefully mirrors the path, I think it'll be quite confusing to have completely different API shapes.

2026-08-04 12:34 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +To support batch sending, homeservers MAY add up to 30 seconds to the scheduled send time.
OK, that seems like an implementation detail though. I think what this is trying to say is "don't expect your event to get send at _exactly_ the millisecond it is scheduled to, but I think that's kind of obvious?

> The homeserver MUST NOT send the event before the scheduled time, but
> MAY send it shortly after the scheduled send time.

2026-08-04 12:35 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +of time.
Right, those are much stronger rationale IMO. I could see it being reasonable to use the original schedule time as `origin_server_ts` or something like that if it was the only issue.

2026-08-04 12:58 UTC, dbkr commented
@mscbot concern open comment threads

2026-08-04 14:14 UTC, fkwp commented on proposals/4140-delayed-events-futures.md
> +## Potential issues
that's the reason why there is delegation of delayed events. In the VoIP example the media server is taking over control.

2026-08-04 14:17 UTC, fkwp commented on proposals/4140-delayed-events-futures.md
> +`POST /delayed_events/{delay_id}/send` requests when it detects a disconnecting client.
> Honestly I suspect if we were to delegate this to the SFU, the sensible approach would to just let the SFU send the hangup sent in the normal way which would be much simpler: it ought to be reliable enough.

wdym with in the normal way?

We are using encrypted sticky events for MatrixRTC membership. So a delayed event is the solution to sending the pre encrypted hangup event. The reason for the /reset is for a potentially long going MatrixRTC session a reset is required as the homeserver admin can restrict the max sticky event duration.

2026-08-04 14:34 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +rounded up to the nearest second.
`M_USER_LIMIT_EXCEEDED` was considered for this, but that is meant for quota limits that can be bypassed (such as with a "premium" subscription / payment-gated feature), whereas this is a server-imposed limit for the sake of appropriate resource allocation (akin to something like a maximum file upload size limit).

See: https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r2878970224

2026-08-04 14:40 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_FORBIDDEN` if the user doesn't have permission to send the event at the time of sending,
Really?  That's what Synapse does, at least.

The spec's only error response for `/send` is 400 with a standard error response.  This section could be changed to mimic that.

2026-08-04 14:46 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +  last restarted.
IMO the `_ts` suffix could make it seem like this field is for the scheduled send time instead of when the delayed event had been scheduled/restarted.  This is called out here: https://github.com/matrix-org/matrix-spec-proposals/blob/15770e6988f307499519b0cb294b95ed494171b6/proposals/4140-delayed-events-futures.md?plain=1#L564

2026-08-04 15:07 UTC, richvdh approved these changes
Looks great to me.

2026-08-04 15:07 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +- `content` - Required. The content of the event to be sent.
It's fine IMHO.

I guess if you wanted to mirror the existing endpoints, you'd have `PUT /_matrix/client/v3/rooms/{roomId}/delayed_send/{eventType}/{txnId}` and `PUT /_matrix/client/v3/rooms/{roomId}/delayed_state/{eventType}/{stateKey}`. I woudn't be dead against that, but I'm unconvinced it's worth changing.

2026-08-04 15:07 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +rounded up to the nearest second.
I think `M_USER_LIMIT_EXCEEDED` was introduced to deal with premium accounts; the general implication is that it's a quota you can pay to increase. Accordingly, `M_LIMIT_EXCEEDED` is probably appropriate here. And normally we would use a 429.

2026-08-04 15:07 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +the homeserver will instead respond with HTTP 403 and a standard error response with an `errcode` of `M_FORBIDDEN`.
> likewise 429, whilst technically correct since the client can wait until the next event is sent, feels a bit weird.

That's exactly what we do for `/send` and co: it seems fine to me?

2026-08-04 15:07 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +- `restart` - Reset the delayed event's scheduled send time to be the current time + its original `delay_ms`.
> if a request is re-sent, does it restart the timer again 

I think I can answer this from memory: the timer is restarted again. That is correct behaviour for the intended usecase of VoIP call keepalives: "I am still here, please don't auto-send the delayed hangup event yet".

I'm in favour of keeping it simple unless/until we have a different usecase that needs fancier semantics.

2026-08-04 15:07 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_UNKNOWN`.
I'm not a big fan of us deliberately specifying M_UNNOWN here. Maybe we can define an M_CONFLICT or something.

2026-08-04 15:07 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_FORBIDDEN` if the user doesn't have permission to send the event at the time of sending,
Doesn't it?

2026-08-04 15:07 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +- Otherwise, the delayed event was cancelled by [the `/cancel` endpoint](#managing-scheduled-delayed-events).
Optional fields are easy to represent in an OpenAPI definition.

We could bikeshed about more structured ways of representing this data (a `state` enum`, maybe?) but I'm not that bothered.

2026-08-04 15:07 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +### Inability to filter and paginate delayed events
The easiest solution to this may be to get rid of the list endpoint, if we don't have a usecase for it?

2026-08-04 15:07 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +### Inability to filter and paginate delayed events
In any case, I'm not sure I agree. This MSC is big enough as it is, and pagination was broken out to MSC4486 deliberately. Let's just land this MSC without adding more clutter.

2026-08-04 15:08 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +### Conflicting delayed state events
There is indeed no longer a planned usecase for delayed state events, or at least one that relies on any particular behaviour of them.  f0ad1898 removes this section.

2026-08-04 20:54 UTC, uhoreg commented on proposals/4140-delayed-events-futures.md
> +[Selective Forwarding Units (SFUs)]: https://trueconf.com/blog/wiki/sfu
nit: this link reference definition seems to be orphaned

2026-08-04 20:54 UTC, uhoreg commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_FORBIDDEN`.
Agreed.  I don't think any of the existing error codes quite match, so maybe a new one is needed for this.

2026-08-04 20:54 UTC, uhoreg commented on proposals/4140-delayed-events-futures.md
> +Delayed events are returned in chronological order of their intended send time, which is `scheduled_at` + `delay_ms`.
I assume ascending order?

2026-08-04 20:54 UTC, uhoreg commented on proposals/4140-delayed-events-futures.md
> +#### `delay_id` in `unsigned` event data
Does the server also include the `transaction_id` property in `unsigned`, like it does with events sent from the other event-sending endpoints?

2026-08-05 08:48 UTC, dbkr commented on proposals/4140-delayed-events-futures.md
> +`POST /delayed_events/{delay_id}/send` requests when it detects a disconnecting client.
Oh I see yes, the SFU can't just send the hangup event since it needs to be encrypted.

2026-08-05 08:52 UTC, dbkr commented on proposals/4140-delayed-events-futures.md
> +## Potential issues
Oh right, of course - I think I was generally failing to understand that this also acts as a way for a client to effectively hand the SFU a signed and sealed envelope with a hangup event that it can send (or trigger to be sent) later. Could add a thing to clarify this maybe.

2026-08-05 11:51 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +  last restarted.
That's exactly how I read 'scheduled_at` to mean! Maybe `created_ts`?

2026-08-05 11:52 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +- Otherwise, the delayed event was cancelled by [the `/cancel` endpoint](#managing-scheduled-delayed-events).
It isn't optional fields that are the issue, but sets of fields that are all optional or all must be included.

2026-08-05 11:54 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +### Inability to filter and paginate delayed events
Agreed this is lengthy.

Moving the entire list endpoint to a separate MSC that provides all the needed filtering/pagination probably makes the most sense.

But also if there's no use-case, why include it?

2026-08-06 13:57 UTC, robintown commented on proposals/4140-delayed-events-futures.md
> +the homeserver will instead respond with HTTP 403 and a standard error response with an `errcode` of `M_FORBIDDEN`.
Removed the special case in 6c3911d309c33cf573867cc1b08f86c49d5fea79. It looks like we don't have a better suggestion for the error code than 429, so we would like to stick with that. Prior art for using 429 as a response to the client having too many operations ongoing in parallel is given by the media creation endpoint, I believe: https://spec.matrix.org/unstable/client-server-api/#put_matrixclientv3roomsroomidsendeventtypetxnid

Please reopen the thread if anyone has a better suggestion for the error code.

2026-08-06 14:05 UTC, fkwp commented on proposals/4140-delayed-events-futures.md
> +- `restart` - Reset the delayed event's scheduled send time to be the current time + its original `delay_ms`.
VoIP team is also in favor of keeping it simple.

2026-08-06 14:06 UTC, robintown commented on proposals/4140-delayed-events-futures.md
> +and send those delayed events as soon as possible, in chronological order of their scheduled send times.
Removed in fc9077af5216f3d31c4a32b551716714a5180a6d

2026-08-06 14:17 UTC, fkwp commented on proposals/4140-delayed-events-futures.md
> +## Potential issues
However, as it was decided to move the LiveKit Auth service into the homeserver, the initial idea of "delegation of delayed events" was cut down to be  homeserver internal (e.g., app services). It's subject to a new MSC once there is demand to delegate to an external service.

2026-08-06 14:42 UTC, fkwp commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_FORBIDDEN`.
addressed by https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/0c7193aaa07c9a2634dccd7cf3bd83e2733a806e

2026-08-06 14:47 UTC, fkwp commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_NOT_FOUND`.
addressed by https://github.com/matrix-org/matrix-spec-proposals/pull/4140/commits/2d42dafcf8d6f50c965f84ba35ac4107b6e2267b

2026-08-06 14:49 UTC, robintown commented on proposals/4140-delayed-events-futures.md
> +both scheduled and finalised delayed events owned by the requesting user.
I can't recall immediately what the rationale is. (@AndrewFerr, your input please?) If there is none at this time, would you prefer that this behavior is removed from the MSC?

2026-08-06 14:51 UTC, fkwp commented on proposals/4140-delayed-events-futures.md
> +  last restarted.
I think created_ts would not be precise in case of a reset of a delayed event. So if we want to have the ts it should be scheduled_at_ts

@AndrewFerr wdyt?

2026-08-06 14:55 UTC, fkwp commented on proposals/4140-delayed-events-futures.md
> +- `delay_ms` - Required. The delay in milliseconds after the point of scheduling that the event is/was to be sent at.
This enables other devices in your account to gather all required data to tell the user when something will be sent.

2026-08-06 14:59 UTC, robintown commented on proposals/4140-delayed-events-futures.md
> +- Otherwise, the delayed event was cancelled by [the `/cancel` endpoint](#managing-scheduled-delayed-events).
Would you prefer that there were a single optional `finalised` object containing both the `event_id` and the `finalised_ts`?

2026-08-06 15:03 UTC, robintown commented on proposals/4140-delayed-events-futures.md
> +sending. If the power level situation has changed at the time the delay passes, the event can even reach the DAG.
It's just simpler to evaluate the power levels once at sending time. The alternative, automatically rejecting/canceling delayed events whenever the current room state looks unfavorable for them eventually getting sent, seems more complex.

2026-08-06 21:54 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +both scheduled and finalised delayed events owned by the requesting user.
I think it would heavily simplify the API and remove some ambiguous pieces (ie how long finalized operations are kept around).

I don't feel super strongly if there's a use case for it though.

2026-08-07 07:25 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +both scheduled and finalised delayed events owned by the requesting user.
The main purpose of finalized events is to make it possible to discover delayed events that failed to be sent due to an error.  Otherwise, failed delayed events would fail silently (at least until they're included in the `/sync` response).

2026-08-07 07:33 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +  last restarted.
`_at_ts` feels redundant.  For precedent, the spec uses either `_at` or `_ts` for timestamp values, but not both together.

It also looks like the choice of `_at` or `_ts` hasn't helped with the clarity of this field name.

How about `scheduled_since_ts`?
- `scheduled_since` makes it clear that the time is in the past, as opposed to the scheduled send time
- `_ts` makes it clear that it's a timestamp

2026-08-07 07:44 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- Otherwise, the delayed event was cancelled by [the `/cancel` endpoint](#managing-scheduled-delayed-events).
If a `finalised` field were to be introduced, what would end up changing is:
- `finalised` would be optional
- `finalised.finalised_ts` would be required
- `finalised.error` & `finalised.event_id` would be optional

That would guard against `error` and `event_id` from ever being set for non-finalised events.

2026-08-07 07:49 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +#### Power levels are evaluated at the point of sending
Yes, this part should call out how malformed events are handled.

Synapse validates the event at the time of scheduling, as opposed to at the scheduled send time, because unlike power levels, event validation rules are unlikely to change over time.  So IMO this section should at enforce at least a schedule-time validation check.

2026-08-07 07:53 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +### Inability to filter and paginate delayed events
The use-case is to give clients the ability to check if any delayed events failed to be sent.

Though admittedly, if a client really cares about the status of any particular delayed event, it would very likely have its `delay_id` on hand & use the single-item lookup to find it.

Still, it feels incomplete to not be able to simply list all available delayed events, especially now that it's contained in its own MSC.

2026-08-07 07:54 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +Delayed events are returned in chronological order of their intended send time, which is `scheduled_at` + `delay_ms`.
Yes; I thought "chronological" also implied ascending time.  If not, that can be clarified here.

2026-08-07 07:58 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +#### `delay_id` in `unsigned` event data
No, because the `transaction_id` only distinguishes requests, not the delayed events themselves.

2026-08-07 20:09 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- `content` - Required. The content of the event to be sent.
Another point against having split delayed send/state endpoints is that the semantics of sending a delayed event are the same for both message & state events, unlike for non-delayed events where `/send` uses a transaction ID to distinguish requests while `/state` uses the state key.

2026-08-17 18:31 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +the homeserver will instead respond with HTTP 403 and a standard error response with an `errcode` of `M_FORBIDDEN`.
The aim of the special case was to avoid returning a rate-limit response when the limit cannot be bypassed by waiting; i.e. when delayed events have been disabled by server config (by setting the allowed max to 0) and no amount of waiting will help.

That special case also helps if we don't want to return `M_DELAY_TOO_LARGE` for an impossible-to-satisfy max allowed delay of 0, as discussed here: https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r3483103991  Similar to 429 suggesting that waiting will help, I'd expect `M_DELAY_TOO_LARGE` to suggest that there exist delay values that are _not_ too large, which is not the case for a max of 0.  Plus, the special case would ensure that the same response would be given regardless of which config the server applied to disallow delayed events (either max delay of 0, or max number of allowed delayed events to 0).

With that said, does the special case feel okay to use here?

2026-08-17 18:31 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +Some alternatives for the `running_since` field on the `GET` response are:
There is still contention with `scheduled_at`, which is being discussed here: https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r3708744335

2026-08-17 18:45 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_FORBIDDEN`.
As long as we're adding a new error code for this, is there any interest in including the value of the max allowed delay in the error response body?

That is what used be done by `M_MAX_DELAY_EXCEEDED`, which was removed in favour of reusing existing error codes & expressing the limit in a capability instead: https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r3257895622

Admittedly, there has been enough discomfort around contorting existing error codes to fit this endpoint that it makes sense to reinstate a dedicated error code.

This isn't to suggest removing the max delay capability, but to save clients the effort of having to look up the capability to know the allowed max when they hit this error response.

2026-08-17 18:50 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_INVALID_PARAM`.
This has gone back to using a dedicated error code: 0c7193aa

2026-08-17 18:53 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +rounded up to the nearest second.
The discussion around using `M_LIMIT_EXCEEDED` / HTTP 429 here has settled in https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r3658009434 , so resolving this thread.

(Also, I hadn't seen Rich's comment on `M_USER_LIMIT_EXCEEDED` until after I had posted mine, hence the duplication 😅)

2026-08-17 19:13 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +  last restarted.
Last suggestion: `delayed_since_ts`, done by b9efebe2.  Reasoning is given in the reworked Alternatives section (which also removes names we've long since stopped considering).

2026-08-17 19:34 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +of time.
Resolving as the concern appears to be quelled.

2026-08-17 19:48 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +#### Power levels are evaluated at the point of sending
Done by ae669936

2026-08-17 19:48 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +of time.
Oh right, those other fields should be mentioned here.  Done by 1f7822f0

2026-08-17 19:48 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +[Selective Forwarding Units (SFUs)]: https://trueconf.com/blog/wiki/sfu
bee5de6f

2026-08-17 19:48 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +Delayed events are returned in chronological order of their intended send time, which is `scheduled_at` + `delay_ms`.
5a81974a

2026-08-17 19:49 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- Otherwise, the delayed event was cancelled by [the `/cancel` endpoint](#managing-scheduled-delayed-events).
0ffd6731 adds a `finalised` field as described above.  It also removes the normative section on what the different combinations of fields mean now that there are fewer such combinations.

2026-08-17 19:52 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +to event scheduling requests with HTTP 400 and a standard error response with an `errcode` of `M_UNKNOWN`.
Further discussion on this special case is here: https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r3729390953

Resolving this thread to avoid duplication.

2026-08-17 20:41 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +Note: clients might find that their events are delayed further due to server load and similar conditions.
ca9f55a5

2026-08-18 11:03 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +However, this could be negated by the complexity of having to support multiple response body formats.
Resolving as the request from https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r3499401628 appears to be addressed now.

2026-08-18 11:06 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +`GET /_matrix/client/v1/delayed_events/{delay_id}` response.
@tulir are you content with this or would you prefer some clarification in the proposal text?

2026-08-18 11:12 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +
Agreed. It feels like a client responsibility to verify that the server's published limits don't interfere with the features the client builds on top of them.

@tulir maybe it's sufficient if we just document this as a potential issue in implementations?

2026-08-18 11:30 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +the homeserver will instead respond with HTTP 403 and a standard error response with an `errcode` of `M_FORBIDDEN`.
I suppose it feels sensible. But also the client could always just verify whether delayed events are disabled entirely through the capability. So I think I'm leaning slightly more towards skipping the special case to keep things simpler.

2026-08-18 11:38 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +doesn't allow querying finalised delayed events. This could be limiting in some cases. A future proposal
Yes, you're right. I believe this was just trying to call out getting finalized events as a particular example. But we can just collapse it into general filtering. Have made this small change in e5bbe4167851a1820569f95fe3e540ab61db3b9e.

2026-08-18 11:49 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +## Potential issues
> Oh right, of course - I think I was generally failing to understand that this also acts as a way for a client to effectively hand the SFU a signed and sealed envelope with a hangup event that it can send (or trigger to be sent) later. Could add a thing to clarify this maybe.

We already seem to have this covered right below in the "Delegating scheduled delayed events" section. So I think this should be clear enough after reading further. Happy to take suggestions for improving the text of course.

> A fairly significant potential issue in using this for VoIP hangups is that a client now needs to be able to make regular, timely HTTP requests to not get a call hung up. I frequently make calls in network conditions that are fine for getting UDP voice packets through but don't work for making a small HTTP request.

I've captured this with a tiny change in the delegation alternative section (83d9e10f9aa6e7306843ea3260330fa938d51a8c).

2026-08-18 11:54 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +- `content` - Required. The content of the event to be sent.
@clokep are you alright with keeping the endpoint as is or would you like to keep this thread open for further discussion?

2026-08-18 11:57 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +To support batch sending, homeservers MAY add up to 30 seconds to the scheduled send time.
This suggestion seems reasonable to me. We don't need to prescribe any further details for how such efficiency delays are implemented. @AndrewFerr WDYT?

2026-08-18 12:00 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_FORBIDDEN`.
> As long as we're adding a new error code for this, is there any interest in including the value of the max allowed delay in the error response body?

I'm not opposed but given that we have (and probably want to keep) the capability anyway maybe that's sufficient and we don't need to bother with the extra complexity?

2026-08-18 12:05 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_FORBIDDEN` if the user doesn't have permission to send the event at the time of sending,
+1 for changing to 400 then for consistency.

2026-08-18 12:05 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +It then becomes the user's responsibility to fetch this error and retry sending the event as appropriate.
This has come up before: https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r3315572163

I stand by my comment from then:

> I'd rather not offload more work to the server, especially for working around rate limits that are supposed to reduce server load. I can also imagine situations where a retry isn't desired, so it makes more sense for clients to be in control of the decision to retry or not.

2026-08-18 12:44 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +To support batch sending, homeservers MAY add up to 30 seconds to the scheduled send time.
Sure; the fact that the allowed lag can be used to implement batch sending is very much an implementation detail.

Also, the "batch sending" here may also be confused with the kind of batch sending discussed in one of the Alternatives sections, i.e. sending related events together.

We should at least define an upper bound on the allowed lag here though, lest "shortly after" is too ambiguous.

All done by 062e6491.

2026-08-18 12:59 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_FORBIDDEN` if the user doesn't have permission to send the event at the time of sending,
57a24037 changes this error to HTTP 400, and uses `M_DUPLICATE_ANNOTATION` as the example error code to match the example given in [`/send`](https://spec.matrix.org/latest/client-server-api/#put_matrixclientv3roomsroomidsendeventtypetxnid)'s 400 response.

2026-08-18 14:23 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +  last restarted.
This seems fair to me. "since" makes it very clear that it refers to the start rather than the end of the interval. I'll consider this resolved.

2026-08-18 14:26 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +It then becomes the user's responsibility to fetch this error and retry sending the event as appropriate.
This sounds sensible to me. We should probably add that reasoning into the proposal text.

2026-08-18 14:34 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +- `delay_ms` - Required. The delay in milliseconds after the point of scheduling that the event is/was to be sent at.
Yeah, this feels like quite essential information to me if we want to enable management of delayed events. It's true that time drift will make this somewhat fuzzy. But then again, delayed events are not guaranteed to be sent at the exact instant specified anyway. So I think this is fine?

2026-08-18 14:35 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +sending. If the power level situation has changed at the time the delay passes, the event can even reach the DAG.
Considering this resolved given the thumbs up reaction.

2026-08-18 14:39 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_UNKNOWN`.
There is precedent in the spec for using `409` without a more specific errcode: [PUT /_matrix/client/v3/directory/room/{roomAlias}](https://spec.matrix.org/latest/client-server-api/#put_matrixclientv3directoryroomroomalias) uses it when trying to create a room alias with a name that already exists.

What else the spec does sometimes is not enforce any particular `errcode` in the error response for a given HTTP code (though example response bodies always include one, typically `M_UNKNOWN`).

So to keep things simple, how about we simply leave the errcode unsaid here?

2026-08-18 14:43 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +the homeserver will instead respond with HTTP 403 and a standard error response with an `errcode` of `M_FORBIDDEN`.
The situation I want to avoid is servers having to decide whether to return `M_DELAY_TOO_LARGE` or `M_LIMIT_EXCEEDED` whenever either (or both) of the server-side configs has effectively disabled delayed events.  So in a way, the special case provides simplicity through complexity :)

2026-08-18 14:45 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_FORBIDDEN`.
Alright, let's leave out the field then.  Besides, there's nothing stopping it from being added in a later MSC if it's really desired.

2026-08-18 14:57 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_UNKNOWN`.
[I'd still like to see this changed, ftr]

2026-08-18 15:36 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +### Inability to filter and paginate delayed events
To avoid leaving this endpoint partially defined, I've moved it out of this MSC entirely & put it into MSC4486.  No use case currently relies on bulk lookup, so there is no reason to rush it in now.

b1eb9b96 for the changes in this MSC.

2026-08-18 15:37 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +It then becomes the user's responsibility to fetch this error and retry sending the event as appropriate.
8de254bc

2026-08-18 15:51 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_UNKNOWN`.
e2636d62 just leaves the errcode unspecified.

IMO there is no value in defining a more specific errcode here since it wouldn't provide any extra information.  Only if there were multiple possible reasons for a 409 would it help.

But if you'd still rather have a new errcode, I will oblige.

2026-08-18 18:47 UTC, uhoreg commented on proposals/4140-delayed-events-futures.md
> +#### `delay_id` in `unsigned` event data
Can you add some words to the MSC to say this?

2026-08-18 19:11 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +#### `delay_id` in `unsigned` event data
Sure: fadd1f88

2026-08-19 06:39 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +#### `delay_id` in `unsigned` event data
(I think "MUST NOT" might be slightly too strong here. We need to explain why the MSC doesn't require it but there's no need to explicitly prohibit it? Maybe just replacing "MUST NOT" with "does not" would be sufficient?)

2026-08-19 06:43 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +It then becomes the user's responsibility to fetch this error and retry sending the event as appropriate.
@dbkr / @clokep are you content with the added motivation?

2026-08-19 06:46 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +both scheduled and finalised delayed events owned by the requesting user.
This paragraph has been eliminated since but maybe we could add a small explanation of why we retain finalized events under the "#### Retention of finalised delayed events" section?

2026-08-19 06:54 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +the homeserver will instead respond with HTTP 403 and a standard error response with an `errcode` of `M_FORBIDDEN`.
Ok, I see. @clokep what are your thoughts on reintroducing the special case to fix the error code?

2026-08-19 11:44 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +- `content` - Required. The content of the event to be sent.
I'm not sure. I'm a bit worried that supporting state at all will be a huge footgun down the road.

2026-08-19 11:47 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +the homeserver will instead respond with HTTP 403 and a standard error response with an `errcode` of `M_FORBIDDEN`.
It feels like setting the delay to 0 to disable the feature is the wrong thing to do. Maybe having a max allowed delayed events to 0 gives a more reasonable behavior?

2026-08-19 11:59 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +#### Event content is evaluated at the point of sending
I think this is a copy and paste error?

```suggestion
#### Event content is evaluated at the point of scheduling
```

2026-08-19 13:09 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +#### Event content is evaluated at the point of sending
Whoops, thanks.  f71394f1

2026-08-19 13:10 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +the homeserver will instead respond with HTTP 403 and a standard error response with an `errcode` of `M_FORBIDDEN`.
Even a max allowed delayed event limit of 0 would benefit from a special error response, because the usual response would be a `M_LIMIT_EXCEEDED` / 429 for a rate limit that can never be satisfied.  Using a different response would make it clear that a rate limit isn't the issue in that case.

2026-08-19 13:10 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- `content` - Required. The content of the event to be sent.
What about delayed state events in particular is problematic?

Some usecases I can think of are:
- kicking a set users in a room after a set time, to implement an "expiring room"
- changing the name/topic of a room after a set time, to indicate the room's age
- sending an event to prevent making voice/video calls after a certain point, to prevent open calls for too long
- scheduling a room upgrade to prevent a room from staying on an old version for too long (this is already possible to do with some finesse)

Also note that if the eventual sending of a state event fails, the account that scheduled it can learn about what went wrong by looking up the associated finalised delayed event.

2026-08-19 13:10 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +both scheduled and finalised delayed events owned by the requesting user.
Sure.  Added by 5d3a1ee2

2026-08-19 13:11 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +#### `delay_id` in `unsigned` event data
How about `SHOULD NOT`?  Reason being, there is no benefit for servers to include the transaction ID field, because it is redundant & therefore wasteful.

2026-08-19 13:12 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +#### `delay_id` in `unsigned` event data
Ok, yeah sounds fine.

2026-08-19 13:26 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +#### `delay_id` in `unsigned` event data
Done: 256957ad

2026-08-19 15:41 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +the homeserver will instead respond with HTTP 403 and a standard error response with an `errcode` of `M_FORBIDDEN`.
I think it's reasonable to define a specific error code to be returned to mean "this feature isn't supported on this server".

I think the problem here is couching it in terms of the limits set. What if my server impl considers any configured max delay below 10 to be effectively disabled? Or requires the admin to set some boolean? Or perform a little dance? These seem like valid implementation decisions.

In other words, remove the references to max delay and max events, and just something like:

```
If the feature is disabled on the server via configuration, the homeserver SHOULD instead respond with HTTP 403 and a standard error response with an `errcode` of `M_FORBIDDEN`.
```

That's all that a client or server implementer needs here.

2026-08-19 15:54 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_UNKNOWN`.
Oops, I missed your previous comment in this thread, sorry.

The spec is abitshit about defining error codes in general, so I wouldn't put too much store by what is already there. The 409 in /directory dates from prehistory: https://github.com/matrix-org/matrix-doc/pull/178.

I'd kinda prefer for there to be a defined Matrix error code, but I don't feel that strongly about it, and as you say the client gets enough info purely from the HTTP error code. I'm happy as it is.

2026-08-19 16:14 UTC, richvdh commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_DUPLICATE_ANNOTATION` if the event is an attempt to send a duplicate annotation,
I'm confused. Why is this about annotations now?

2026-08-19 17:38 UTC, richvdh reviewed
My current thoughts on this MSC (recorded as much as a memo to future-me as anyone else):

I think this is all basically fine, though there are still a few open threads from various reviewers. Thanks to those threads, there is still a fair amount of flux on the proposal. It therefore feels a little easy to add my approval for FCP.

2026-08-19 17:55 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_DUPLICATE_ANNOTATION` if the event is an attempt to send a duplicate annotation,
It's not; that's just an example of an errcode that could be responsible for the failed send.  I picked this because [the spec for non-delayed `/send`](https://spec.matrix.org/latest/client-server-api/#put_matrixclientv3roomsroomidsendeventtypetxnid) gives it as an example.  If it's distracting to have it here, though, I have no issues removing it.

2026-08-19 18:01 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +the homeserver will instead respond with HTTP 403 and a standard error response with an `errcode` of `M_FORBIDDEN`.
That's a great way to phrase it.  Added by ec7cbfd8

Leaving this thread unresolved in case there are any objections to it.

2026-08-19 18:02 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- `delay_ms` - Required. The delay in milliseconds after the point of scheduling that the event is/was to be sent at.
Resolving this on account of Patrick's 👍.

2026-08-19 20:08 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +the homeserver will instead respond with HTTP 403 and a standard error response with an `errcode` of `M_FORBIDDEN`.
Agreed that sounds better!

2026-08-19 20:12 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +It then becomes the user's responsibility to fetch this error and retry sending the event as appropriate.
Seems ok with me.

2026-08-19 20:14 UTC, clokep commented on proposals/4140-delayed-events-futures.md
> +- `content` - Required. The content of the event to be sent.
I guess those all sound reasonable, I didn't think we had any use cases for it though and I dislike adding features just because.

2026-08-19 20:15 UTC, clokep commented
@mscbot resolve List endpoint is unbounded and needs pagination.

2026-08-20 07:03 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +- `content` - Required. The content of the event to be sent.
Maybe we could list one or two of the examples above in the introductory section of the proposal to motivate why delayed state events are included.

2026-08-20 12:50 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +- `content` - Required. The content of the event to be sent.
Yes, may as well.  Done by 4d395ec9

(Not re-opening this thread because the contention re: delayed state is still resolved)

2026-08-21 02:52 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +the homeserver will instead respond with HTTP 403 and a standard error response with an `errcode` of `M_FORBIDDEN`.
Since there's been no further objections, I'll consider this settled.

2026-08-21 02:54 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_UNKNOWN`.
Thanks for the tolerance.  I will leave this as-is then.

2026-08-21 13:34 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +with an `errcode` of `M_DUPLICATE_ANNOTATION` if the event is an attempt to send a duplicate annotation,
I've gone ahead and reworded this with 05029e2b.  Instead of giving example responses, now it tries to more clearly say that the error response given is the same as for non-delayed event requests.  Let me know if this reads better.

2026-08-21 14:30 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +`GET /_matrix/client/v1/delayed_events/{delay_id}` response.
Actually, there's no pressing need to discard finalised events on retrieval.  The retention rules should be enough to protect against resource bloat of keeping too many finalised events.  Removed this with e18c6ab4

2026-08-21 14:55 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +
I've added something to the Potential Issues section to cover this.  @tulir Let me know if that's sufficient.  5398aa97

2026-08-21 15:08 UTC, tulir commented on proposals/4140-delayed-events-futures.md
> +
Yeah looks reasonable

2026-08-21 15:18 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +
Thanks. Marking this as resolved, then

2026-08-25 10:29 UTC, dbkr commented on proposals/4140-delayed-events-futures.md
> +It then becomes the user's responsibility to fetch this error and retry sending the event as appropriate.
Fair enough, as long as it's explained (plus, an HS being unable to send an event should be quite an extreme edge case).

2026-08-25 13:25 UTC, erikjohnston reviewed
Otherwise I'm happy

2026-08-25 13:25 UTC, erikjohnston commented on proposals/4140-delayed-events-futures.md
> +If the server doesn't enforce one of these limits, its representative field MUST be absent from the capability.
This framing does mean it's impossible for a server to say that delayed events are disabled. I'm not sure that is something we want to support, but equally feels odd. I'm not sure if it's worth doing anything about it though

2026-08-25 13:25 UTC, erikjohnston commented on proposals/4140-delayed-events-futures.md
> +sending. If the power level situation has changed at the time the delay passes, the event can even reach the DAG.
I think we should allow servers to reject scheduled events if the user doesn't have permission to send them at schedule time. It feels somewhat perverse to a) not error immediately, and b) allow stacking up delayed events in arbitrary rooms.

We shouldn't scope this to just power levels, it applies to all auth rules. We're basically saying "handle the event as if the client manually sent it at the scheduled time". This is important as servers could  construct and validate  the event when either a) it's scheduled, or b) it's sent. We want the latter.

I think it's fine to not handle the edge case where the room state changes between schedule and send, i.e. if it the event was allowed initially then it's fine not to check auth again until it comes to send time.

Maybe something like:

```suggestion
#### Auth rule evaluation

When a server comes to send a scheduled event it MUST construct the final event based on the state
of the room at the time of sending (NOT when it is scheduled), as if the client itself sent the
event. In particular, the server MUST check the event is authorized to be sent based on the state at
the time the server sends the event.

The server SHOULD also check the event could be sent when it is scheduled and reject the request if
not. In particular, servers SHOULD check the sender is in the room (or otherwise authorized to send
the event) to avoid storing events for rooms the user is not in.

> [!NOTE]
>
> Servers do not need to reevaluate the auth checks for delayed events in a room when the state
> changes, it can defer checks until the event comes to be sent.
```

2026-08-25 14:08 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +If the server doesn't enforce one of these limits, its representative field MUST be absent from the capability.
It can communicate disabled delayed events by responding with:
```json
{
  "capabilities": {
    "m.delayed_events": {
      "max_delay_ms": 0,
      "max_scheduled": 0
    }
  }
}
```
Even including only one of the `max_` fields would be sufficient, as it's enough for either one of them to be 0 to mean that delayed events are disabled.

Does that cover your concern?

2026-08-25 15:07 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +sending. If the power level situation has changed at the time the delay passes, the event can even reach the DAG.
> It feels somewhat perverse to ... allow stacking up delayed events in arbitrary rooms.

Good point; that is indeed something worth guarding against.

> We're basically saying "handle the event as if the client manually sent it at the scheduled time".

An exception should be made for rate-limiting rules, i.e. rate limits on event sending should apply on delayed events only on their send time, not on their schedule time.

Or, does that distinction not need to be made here, since rate limits are a different topic than auth rule evaluation?  (At least I don't see rate limits mentioned anywhere in (one version of) the spec for [auth rules](https://spec.matrix.org/v1.19/rooms/v12/#authorisation-rules).)

2026-08-25 15:24 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +sending. If the power level situation has changed at the time the delay passes, the event can even reach the DAG.
Actually, how to apply rate limiting is already made clear in the very next section ([Rate-limiting at the point of sending](https://github.com/matrix-org/matrix-spec-proposals/blob/toger5/expiring-events-keep-alive/proposals/4140-delayed-events-futures.md#rate-limiting-at-the-point-of-sending)).  So between that & auth rules not being about rate limits, let's call this resolved.

2026-08-25 15:42 UTC, erikjohnston commented on proposals/4140-delayed-events-futures.md
> +If the server doesn't enforce one of these limits, its representative field MUST be absent from the capability.
Mmm, true I suppose. Though if we want clients to consider `0` to mean disabled then that's something we should be specific. While technically a limit of 0 is the same, it needs to be handled specially by clients (i.e. this operation will never work no longer how long we wait). 

OTOH I'm not sure if we *want* to allow delayed events to be disabled by the server? I guess that is the fundamental question, and we should either explicitly allow or deny `0` as the limit.

(This is a very low severity thing)

2026-08-25 15:59 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +If the server doesn't enforce one of these limits, its representative field MUST be absent from the capability.
> While technically a limit of 0 is the same, it needs to be handled specially by clients (i.e. this operation will never work no longer how long we wait).

Aha, this is what that ["special case"](https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r3658009434) I was banging on about was for.  It landed as ec7cbfd.

> OTOH I'm not sure if we _want_ to allow delayed events to be disabled by the server?

IMO there's no harm to allow disabling it, especially if server configs already allow you to constrain it (why not allow constraining it all the way to 0?).

As another point, this section should also specify what clients should assume if the `m.delayed_events` capability is absent entirely (not just its fields).

af63014d does so, and also explicitly specifies what 0 limits mean.

2026-08-26 08:14 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +If the server doesn't enforce one of these limits, its representative field MUST be absent from the capability.
I suppose managing delayed events will cause some amount of load on the server. I suppose it's low but technically allowing an admin to disable it seems reasonable to me.

Even if we don't allow 0. A value of 1ms would still mean the feature is effectively disabled from a client's perspective.

2026-08-26 08:47 UTC, dbkr commented
@mscbot resolve open comment threads

2026-09-02 12:37 UTC, richvdh approved these changes

2026-09-02 17:21 UTC, ara4n commented
So I've gone through the whole thing (and a bunch of the old threads) and it makes sense - it's an alternative approach to my proposal at #3277 but there's a meaningful difference between asking your local HS to maybe send an event in future... versus asking your local HS to send an event right now, which servers should only reveal to their clients in future.

I've approved it for FCP, but with one minor proviso: i really tripped over the "Delegating scheduled delayed events" section in Alternatives... because it's listed as an alternative (having previously been part of the main proposal), and yet MatrixRTC explicitly depends on delegated delayed events to function sensibly, by letting SFUs explicitly trigger delayed leave events when users leave a call.

Now, it turns out that the way that works is that MSC4195 (LiveKit transport for MatrixRTC) specifies how a homeserver can cancel MSC4140 delayed events on behalf of the LiveKit SFU if the SFU knows that a user has dropped (the whole `/_matrix/client/v1/rtc/livekit/delegate_delayed_leave` mechanism).   But it'd be good to explicitly mention this to avoid others getting confused. Something like:

> Delegation of delayed events to other entities was originally part of this MSC, but descoped as an alternative given these complexities.  However, a simplified version of it is reintroduced in MSC4195 which allows a user's homeserver to act on behalf of the user in response to updates from a LiveKit SFU.

It also feels weird that the MatrixRTC delegation approach has ended up as livekit-specific in the LK transport MSC, when there's nothing livekit specific about it?  However, that's more a point for MSC4195.

2026-09-03 09:12 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +and the additional network/configuration overhead for external services to request access to this scope.
As per @ara4n's suggestion in https://github.com/matrix-org/matrix-spec-proposals/pull/4140#issuecomment-5513533076.

```suggestion
and the additional network/configuration overhead for external services to request access to this scope.

Delegation of delayed events to other entities was originally part of this MSC, but descoped as an
alternative given these complexities. However, a simplified version of it is reintroduced in
[MSC4195](https://github.com/matrix-org/matrix-spec-proposals/pull/4195) which allows a user's
homeserver to act on behalf of the user in response to updates from a LiveKit SFU.
```

2026-09-03 09:14 UTC, Johennes commented
> [...] But it'd be good to explicitly mention this to avoid others getting confused. Something like:
> 
> > Delegation of delayed events to other entities was originally part of this MSC, but descoped as an alternative given these complexities.  However, a simplified version of it is reintroduced in MSC4195 which allows a user's homeserver to act on behalf of the user in response to updates from a LiveKit SFU.

I have applied this in https://github.com/matrix-org/matrix-spec-proposals/pull/4140/changes#r3922947293.

2026-09-07 12:43 UTC, jevolk commented on proposals/4140-delayed-events-futures.md
> +If the action is `send` and the delayed event is unable to be sent due to an error,
This section requires some T&S carve-outs. Please adopt these clarifications:

> When sending a delayed event, the homeserver MUST apply the account-status restrictions that would apply to an equivalent non-delayed event from the same sender at that time, including any exceptions permitted by the ordinary sending rules.

This specifically allows leave membership events to be sent at their scheduled time when a user is suspended.

> Suspending an account MUST NOT, by itself, cancel its scheduled delayed events. Suspension which has ended before the send-time check does not affect that check.

Suspension and restitution prior to any scheduled send never affects that send.

> When an account is deactivated, the homeserver MUST cancel that account's delayed events which have not yet been added to a room's event DAG. These cancelled records MAY be removed immediately, including their stored event content, as an exception to the usual finalised-record retention policy.

Deactivation prior to any scheduled send always eliminates that send.

2026-09-07 18:21 UTC, richvdh commented
Slightly belatedly, I'm going to open a concern to track a resolution to @jevolk's comment.

(per the process: "a member of the Spec Core Team can raise a concern and block FCP from completing. This will not reset or pause the 5 day FCP timer, but FCP will not conclude until all concerns have been resolved")

We're all going to pretend that I did this an hour ago.

@mscbot concern comments from @jevolk regarding T&S

2026-09-07 19:04 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +If the action is `send` and the delayed event is unable to be sent due to an error,
The effects of account suspension and locking are left as implementation details - those two clarifications are not relevant in this MSC, though should be noted as things to consider at editorial time in the spec.

Deactivation would indeed imply inability to send events, but that wouldn't be something to list here. The wording suggestion is appropriate, but should probably be worked into the Potential Issues section rather than this specific line.

2026-09-07 21:12 UTC, jevolk commented on proposals/4140-delayed-events-futures.md
> +If the action is `send` and the delayed event is unable to be sent due to an error,
My position is that the latter two clarifications are easily deferred to implementations, certainly it's technically possible to do that. I just don't see why you would want to. The specification prerogative should promote uniformity and maintain least-surprise among implementations when all other things are equal.

My opinion is when a user sends a message from a server and then deactivates believing it won't be sent because that is what their last server did ... but it's sent anyway, and then the recipient tries to respond, but that gets bounced, which reads bizarrely to them too ... that mess can be avoided if you simply decide to avoid it. Nevertheless I don't see any truly objective case to make for specifying it.

The first clarification though resolves an intra-spec inconsistency, because it was a conscious choice to permit leaving a room while suspended. It's a technical quagmire to introduce separate rules for these two cases within one implementation. It's a subjective quagmire no different from above to have different behavior choices made by different implementations, and finally it's probably just a quagmire for reasons I'm not even aware of, such as when an Element Call gets stuck from suspending the user making it -- don't quote me on that -- but it's probably better to err on the side of consistency and comfortable expectation.

2026-09-08 00:05 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +If the action is `send` and the delayed event is unable to be sent due to an error,
Suspension and locking both could do with clearer expectations being set in the specification itself, but this won't be the MSC to do that. I'd still leave suspension/locking out of this proposal entirely, allowing the spec PR to make editorial choices as required.

Deactivation however does have more firm requirements in the spec, so it makes sense to clarify that deactivation also implies cancelling the delayed events. That's more of an edge case though, so belongs in the Potential Issues section.

2026-09-08 00:29 UTC, jevolk commented on proposals/4140-delayed-events-futures.md
> +If the action is `send` and the delayed event is unable to be sent due to an error,
Every implementation is forced to make this choice:

1. Cancel delayed events when a user is suspended.
2. Honor delayed events when a user is suspended.

Choosing 1 denies the ability for a suspended user to leave a room they otherwise have the spec-given ability to, merely on the account of an event being sent with some delay rather than not.

The counter-claim is that rejecting 2 isn't the wrong choice because implementations are granted discretionary power by this very MSC's refusal to compel it.

If the proper answer is 2, and I don't see how it couldn't be, the question becomes whether this edict is conveyed explicitly or implicitly. That's why I see every reason to include it as clearly and unambiguously as could be understood.

2026-09-08 00:50 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +If the action is `send` and the delayed event is unable to be sent due to an error,
I'm arguing the fact that *all* behaviour for suspension is currently an implementation detail. It doesn't make sense to apply any more strictness to delayed events than the other possible actions a user can/could take. See the spec for more information: https://spec.matrix.org/v1.19/client-server-api/#account-suspension

Further discussion is best placed on a dedicated MSC which clarifies suspension/locking mechanics, not here.

2026-09-08 00:59 UTC, jevolk commented on proposals/4140-delayed-events-futures.md
> +If the action is `send` and the delayed event is unable to be sent due to an error,
The clarifications never take a position against the spec's ambiguity. **They only tie this MSC to that ambiguity** rather than allowing a divergence from it.

> When sending a delayed event, the homeserver MUST apply the account-status restrictions that **WOULD** apply to an **EQUIVALENT** non-delayed event from the same sender at that time, including any exceptions permitted by the ordinary sending rules.

> status restrictions that _would_ apply to an _equivalent_ non-delayed event

2026-09-08 01:02 UTC, jevolk commented on proposals/4140-delayed-events-futures.md
> +If the action is `send` and the delayed event is unable to be sent due to an error,
> Suspending an account MUST NOT, _by itself_, cancel its scheduled delayed events. Suspension which has ended before the send-time check does not affect that check.

This doesn't change any behavior if your implementation **WOULD** blackhole an **EQUIVALENT** non-delayed event.

2026-09-08 01:04 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +If the action is `send` and the delayed event is unable to be sent due to an error,
> Further discussion is best placed on a dedicated MSC which clarifies suspension/locking mechanics, not here.

2026-09-08 06:07 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +If the action is `send` and the delayed event is unable to be sent due to an error,
Have captured the requirements for account deactivation and added a short note why nothing is prescribed for account suspension in 02a1abfbdf36d3452e2ee3f84ccd5b72ea3db67c.

2026-09-08 14:06 UTC, turt2live commented
Talked with @richvdh out of band:

@mscbot resolve comments from @jevolk regarding T&S

2026-09-08 14:07 UTC, merged

2026-09-12 15:21 UTC, jevolk commented on proposals/4140-delayed-events-futures.md
> +  This is the body of the original `PUT` request, not a preview of the full event after sending.
This seems to contradict https://github.com/matrix-org/matrix-spec-proposals/pull/4140/changes#diff-9b9804182bcf372862f2c7a98381b5ca28b064592fd7887aab7ea4386a81fc0aR63-R67

2026-09-14 06:38 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +  This is the body of the original `PUT` request, not a preview of the full event after sending.
I suppose what is meant here is the `content` object from the body of the original `PUT` request. Anything else would be fairly nonsensical.

```suggestion
  This is the `content` property from the body of the original `PUT` request, not a preview of the full event after sending.
```

2026-09-14 06:39 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +  This is the body of the original `PUT` request, not a preview of the full event after sending.
@turt2live can we still apply this clarification?

2026-09-15 00:35 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +  This is the body of the original `PUT` request, not a preview of the full event after sending.
Sure - a dedicated PR would be best.

2026-09-15 04:12 UTC, jevolk commented on proposals/4140-delayed-events-futures.md
> +If the capability is absent, clients SHOULD assume that delayed events are disabled / not supported by the server,
Line 132 lets a capable server that doesn't enforce limits omit the capability itself.

https://github.com/matrix-org/matrix-spec-proposals/blob/1363dd1352d98dff9eade4fb63d362daaa60e9d2/proposals/4140-delayed-events-futures.md#L132 

Line 147 tells the client that absence means disabled.

https://github.com/matrix-org/matrix-spec-proposals/blob/1363dd1352d98dff9eade4fb63d362daaa60e9d2/proposals/4140-delayed-events-futures.md#L147

The feature is not discovered.

2026-09-15 06:52 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +If the capability is absent, clients SHOULD assume that delayed events are disabled / not supported by the server,
Good spot. Fix in https://github.com/matrix-org/matrix-spec-proposals/pull/4542.

2026-09-15 06:52 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +  This is the body of the original `PUT` request, not a preview of the full event after sending.
This now lives in https://github.com/matrix-org/matrix-spec-proposals/pull/4542.

2026-09-15 07:32 UTC, jevolk commented on proposals/4140-delayed-events-futures.md
> +timeout duration of scheduled delayed events. The exact limits are left as an implementation detail.
> [!TIP]
> - MAY enforce a maximum delay.

https://github.com/matrix-org/matrix-spec-proposals/blob/1363dd1352d98dff9eade4fb63d362daaa60e9d2/proposals/4140-delayed-events-futures.md#L93

> [!WARNING]
> - SHOULD enforce a maximum scheduled count.

https://github.com/matrix-org/matrix-spec-proposals/blob/1363dd1352d98dff9eade4fb63d362daaa60e9d2/proposals/4140-delayed-events-futures.md#L99-L102

> [!CAUTION]
> - MUST enforce a maximum delay and maximum scheduled count !

https://github.com/matrix-org/matrix-spec-proposals/blob/1363dd1352d98dff9eade4fb63d362daaa60e9d2/proposals/4140-delayed-events-futures.md#L615-L616

> [!WARNING]
> - SHOULD enforce a maximum scheduled count.

https://github.com/matrix-org/matrix-spec-proposals/blob/1363dd1352d98dff9eade4fb63d362daaa60e9d2/proposals/4140-delayed-events-futures.md#L629-L630

2026-09-15 14:03 UTC, turt2live commented on proposals/4140-delayed-events-futures.md
> +timeout duration of scheduled delayed events. The exact limits are left as an implementation detail.
https://github.com/matrix-org/matrix-spec-proposals/pull/4542/commits/cff8f24e39377177cec1b498081e50e2e7ec5d3a

2026-09-16 07:09 UTC, jevolk commented on proposals/4140-delayed-events-futures.md
> +or if the `action` is `cancel` and the delayed event has already been sent,
```suggestion
or if the `action` is `cancel` or `restart` and the delayed event has already been sent,
```

The intent looks settled already: https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r2392441559 proposed 409 for `restart` on a sent or cancelled event, and 1e18fa2 ("Return 409 Conflict on any conflicting action") implemented it but listed only `cancel` for the sent case, so this reads as a transcription slip rather than a decision.

Line 204 gives `send` on a sent event a 200. Line 210 gives `cancel` on a sent event a 409. `restart` on a sent event is in neither list, and both lists are introduced with "i.e.", so it has no defined response.

https://github.com/matrix-org/matrix-spec-proposals/blob/1363dd1352d98dff9eade4fb63d362daaa60e9d2/proposals/4140-delayed-events-futures.md#L202-L211

A periodic `restart` that lands after the timer, or another client's `send`, has already sent the event. 404 does not fit, which leaves each server to pick between 200 and 409, and the client reacts differently to each. matrix-js-sdk's membership manager recovers from a failed `restart` only on `M_NOT_FOUND`; a 409 falls through to a throw, and a 200 tells it the timer was reset after its membership is already gone.

https://github.com/matrix-org/matrix-js-sdk/blob/15ed5fe089394f54e52eb6a0aa21e1ac791230af/src/matrixrtc/MembershipManager.ts#L631-L643

2026-09-16 08:14 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +or if the `action` is `cancel` and the delayed event has already been sent,
Have included this in https://github.com/matrix-org/matrix-spec-proposals/pull/4542.

2026-09-16 08:24 UTC, jevolk commented on proposals/4140-delayed-events-futures.md
> +MAY send it up to 30 seconds after the scheduled send time.
```suggestion
The homeserver MUST NOT send the event before the scheduled time, except in response to the
[`send` action](#managing-scheduled-delayed-events), and MAY send it up to 30 seconds after the scheduled send time.
```

Line 84 forbids sending before the scheduled time without exception. Line 173 defines `send` as sending the event "immediately instead of waiting for its scheduled send time", so a server cannot both keep the MUST NOT and support the action.

https://github.com/matrix-org/matrix-spec-proposals/blob/1363dd1352d98dff9eade4fb63d362daaa60e9d2/proposals/4140-delayed-events-futures.md#L84-L85

https://github.com/matrix-org/matrix-spec-proposals/blob/1363dd1352d98dff9eade4fb63d362daaa60e9d2/proposals/4140-delayed-events-futures.md#L173

The intent looks settled already: https://github.com/matrix-org/matrix-spec-proposals/pull/4140#discussion_r2818011461, a thread about how late the timer may fire, where the promise being made was that the server never fires early on its own, and was committed in 1e527c3d. The `send` action predates it by almost two years and keeps its own entry under Alternatives (line 551). Neither that thread nor the rewording in 062e6491 mentions the action, so this reads as a wording slip rather than a decision.

2026-09-17 05:51 UTC, Johennes commented on proposals/4140-delayed-events-futures.md
> +MAY send it up to 30 seconds after the scheduled send time.
Tracked in https://github.com/matrix-org/matrix-spec-proposals/pull/4542 as well.

2026-09-25 23:12 UTC, AndrewFerr commented on proposals/4140-delayed-events-futures.md
> +  This is the body of the original `PUT` request, not a preview of the full event after sending.
> This is the body of the original `PUT` request, not a preview of the full event after sending.

N.B. this line was an artifact of the original plan of using `PUT /send` & `PUT /state` with a `delay` parameter to schedule delayed events, in which case the request body would have indeed been the content of the event to be scheduled.

In any case, #4524 corrects this, so marking this thread as resolved.

2026-10-30 16:13 UTC, Johennes commented
Spec PR: https://github.com/matrix-org/matrix-spec/pull/2462

2026-11-13 16:46 UTC, turt2live commented
Merged 🎉