MSC4231: Backwards compatibility for media captions
matrix-org/matrix-spec-proposals pull request #4231
Opened 2024-11-22 00:19 UTC by ara4n

2024-11-22 01:32 UTC, turt2live commented on proposals/4231-media-caption-backwards-compatibility.md
Implementation requirements:
* [ ] Sending client (with fallback)
* [ ] Receiving client (strip fallback)
* [ ] Receiving client (requires fallback)

2024-11-22 01:36 UTC, turt2live requested changes

2024-11-22 01:36 UTC, turt2live commented on proposals/4231-media-caption-backwards-compatibility.md
> +[MSC2530](https://github.com/matrix-org/matrix-spec-proposals/pull/2530).
why not as replies? Semantically, a caption is referencing a piece of media, and when two events are involved it's possible for a third, unrelated, event to get in between them. 

Replies (or at least relationships) will also help clients parse the captions and hide the duplicate event.

2024-11-22 01:36 UTC, turt2live commented on proposals/4231-media-caption-backwards-compatibility.md
> +way worse to drop messages.
Clients which are "caption-aware" would hide these fallback events, meaning a client could have an entirely different conversation out of view of moderators on updated clients, for example. With replies, there's a relationship which can be validated - if the relationship is invalid (by whatever means), then the "caption-aware" client treats it as a regular message instead of a caption.

2024-11-22 09:40 UTC, ara4n commented on proposals/4231-media-caption-backwards-compatibility.md
> +[MSC2530](https://github.com/matrix-org/matrix-spec-proposals/pull/2530).
yup, agreed - replies are nicer

2024-11-22 10:26 UTC, tulir commented on proposals/4231-media-caption-backwards-compatibility.md
> +[MSC2530](https://github.com/matrix-org/matrix-spec-proposals/pull/2530).
It might be good to have some words about edits (I'd assume clients edit both messages? Does the fallback flag go in `m.new_content`, the top level, or both?)

2024-11-22 12:40 UTC, manuroe commented on proposals/4231-media-caption-backwards-compatibility.md
> +[MSC2530](https://github.com/matrix-org/matrix-spec-proposals/pull/2530).
Clients can also edit an image event to add or remove a caption

2024-11-22 12:42 UTC, manuroe commented on proposals/4231-media-caption-backwards-compatibility.md
> +[MSC2530](https://github.com/matrix-org/matrix-spec-proposals/pull/2530).
We should probably clarify what happens in case of the redaction of the media.

2024-11-22 13:09 UTC, tulir commented on proposals/4231-media-caption-backwards-compatibility.md
> +[MSC2530](https://github.com/matrix-org/matrix-spec-proposals/pull/2530).
Hmm yeah, adding a caption would be problematic, you can't insert a message after the image anymore. Simple edits and redactions are "easy", clients would just need to keep track of the fallback event associated with the media and edit/redact it at the same time

2024-11-22 15:39 UTC, clokep commented on proposals/4231-media-caption-backwards-compatibility.md
> +## Potential issues
If the caption message had a relation then it would probably be ok since you can't create a thread on an event that has a relation IIRC.

2024-11-22 19:42 UTC, spaetz commented
To be honest, this does feel just like building up technical debt and cruft with very little benefit. You expect clients to eventually support newer spec versions, why don't you expect them to eventually support captions? All those tricky edge cases mentioned above are a big can of worms that clients are never going to be supporting consistently.

2024-11-24 05:38 UTC, manuroe commented on proposals/4231-media-caption-backwards-compatibility.md
> +[MSC2530](https://github.com/matrix-org/matrix-spec-proposals/pull/2530).
Using a reply suggested MSC4231 may help but I am not sure it will give a great UX.

2024-11-24 05:44 UTC, manuroe commented on proposals/4231-media-caption-backwards-compatibility.md
> +## Potential issues
Do we create another backward compatibality issue?
Clients or bridges that are caption capable but not MSC4231 capable will display or transport the text content twice, displaying double content to the user.

2024-11-24 06:05 UTC, manuroe commented
I agree with @spaetz about the complexity this MSC is adding. Sending a fallback message, yes, it is easy. Keeping both the caption and the fallback consistent is another challenge.
Adopting the caption feature adoption was only a UX problem. It is going to be an implementation problem.

We are going to split a text content into 2 sources of truth. Clients will display and let users interact with one of them (or the 2 for caption capable but not MSC4231 aware clients or bridges). It creates bugs by design and can be only best effort.
If not making the implementation easier, using a reply creates a relationship that can cover some problems but not all. 

To avoid our users to suffer too much from the mitigation we are doing at the protocol level, can we define the solutions or mitigations in the MSC we will have for the following questions. Detailing them in the MSC will help to have a consistent behavior in the Matrix ecosystem.

- [ ] How to manage reactions made on the fallback? They will be hidden in MSC4231 clients
- [ ] How to manage edit/redaction made on the fallback?
- [ ] How to edit/redact the fallback? How can we know which event is the fallback?

More questions will probably come while implementing the MSC.

2024-11-24 20:22 UTC, ara4n commented on proposals/4231-media-caption-backwards-compatibility.md
> +# MSC4231: Backwards compatibility for media captions
This MSC has fallen apart a bit, on realising that to handle edits/redactions there's a real risk of the caption & caption fallback drifting out of sync - plus the caption fallback event has to have a relation to link it to the media event in order to try to keep the two in sync.  At which point it feels very close to MSC2529.

I think the three routes out of this mess are either:
 1. Switch to something like MSC2529, flagging media events which have a caption in them so that bridges know to look for the relation and aggregate it before they bridge the media event.  This means that we have a single source of captions, with fallback that works.
 2. Get our act together and say "to use captions, you have to use extensible events" and try to force that migration through - although it doesn't solve the immediate problem we have.
 3. Give up on the current lack of backwards compatibility, frantically encourage existing client implementors to implement MSC2530 on their existing clients, given it's easy to do, and fix it 'properly' in future with extensible events, which then gives us a mechanism to avoid future fallback problems.

Thoughts welcome on the right approach to take here.

2024-11-25 15:18 UTC, turt2live commented on proposals/4231-media-caption-backwards-compatibility.md
> +# MSC4231: Backwards compatibility for media captions
For the desync issue, does it help to reverse the relationship? Clients would send a caption event first, get the event ID, then send their media with `caption: "$whatever"`, potentially instead of using the `body` as a second source. A flag on the caption event may be required so clients (bridges) know to expect the other half eventually, with timeout. 

This takes us further away from extensible events, but reduces the amount of data that can be desynced.

2024-11-26 01:14 UTC, turt2live commented on proposals/4231-media-caption-backwards-compatibility.md
> +# MSC4231: Backwards compatibility for media captions
(I'm inclined to agree, though it's unfortunate that Extensible Events continues to fall behind 😢 )

2024-11-26 13:02 UTC, clokep commented on proposals/4231-media-caption-backwards-compatibility.md
> +# MSC4231: Backwards compatibility for media captions
I'm inclined to go with 3 as the only option that will realistically happen semi-quickly.

2024-11-26 14:20 UTC, anoadragon453 commented on proposals/4231-media-caption-backwards-compatibility.md
> +# MSC4231: Backwards compatibility for media captions
I agree that option 3 will save us a lot of headache.

2024-11-26 14:32 UTC, ara4n commented on proposals/4231-media-caption-backwards-compatibility.md
> +# MSC4231: Backwards compatibility for media captions
> Given the amount of time that reply fallbacks cost the ecosystem over the years, my preference would be for option 3.

To be clear, alt option 1 is *not* adding in fallbacks - it's switching from captions-as-body (MSC2530) to captions-as-relations (MSC2529), so that you get backwards compatibility (and meanwhile bridges would have to aggregate the relations when bridging from Matrix)

I am split between option 1 ("actually fixes the problem; only causes work for folks who have already implemented MSC2530") and option 3 ("doesn't fix the backwards compat problem so older/unmaintained clients will drop msgs sent as captions; causes work for everyone who's ever written a Matrix client, apart from those who have already implemented MSC2530").

2024-11-26 16:22 UTC, ara4n commented on proposals/4231-media-caption-backwards-compatibility.md
> +# MSC4231: Backwards compatibility for media captions
Having just spoken to the Element mobile team about this: the soonest they'd practically be able to work on the legacy Element mobile apps to make them talk MSC2530 would be early 2025 - and it was also pointed out it can take months particularly for Android users to update to newer apps, during which time messages sent in captions will be lost.

Meanwhile i've suggested that the MSC2529 support in Element X is put into labs while this backwards compatibility mess is sorted out.

So, i'm not sure it's true to say that Option 3 is going to happen quickly (or even semi-quickly).

I wonder if there is hybrid solution here where we switch to MSC2530 for authoring captions, but caption-aware clients can still display MSC2529 ones (for backwards compat).   So, to send a caption, you'd send:

```json5
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.image",
    "m.is_captioned": true
}
```

```json5
{
  "type": "m.room.message",
  "content": {
    "body": "Caption text",
    "msgtype": "m.text",
    "m.relates_to": {
        "event_id": "$media_event_id",
        "rel_type": "m.caption",
	"m.in_reply_to": {
	        "event_id": "$media_event_id"
	}
    }
}
```

and then the caption-aware displayer will spot `m.is_captioned: true` on the media event and on seeing the caption event will display it attached to the media event.  Bridges would have to do the same aggregation to group the two together.

Caption unaware displayers will meanwhile bridge it as two separate events; one for media and then a subsequent reply, which provides very reasonable backwards compatibility.

Finally, and this is the only bit of tech debt accrued: if a caption-aware client sees a media event with "body" set and no "m.is_captioned", then for backwards compatibility it'd treat it as an MSC2529 caption.

Having written it out, properly fixing the problem in this manner feels like a big improvement to me - and then once we eventually get extensible events, these captions-as-relations could be replaced by the fallback mechanisms provided by extensible events.

2024-11-26 17:34 UTC, ara4n commented
Given the number of unsolved [outstanding issues](https://github.com/matrix-org/matrix-spec-proposals/pull/4231/files#diff-4b4102b0dac5ab825374ab784bc4deafb189521341a9a0b52c3bd44c9a9d7224R61) caused by fallback caption events drifting out of sync with the media events, it feels like this attempt to add backwards compatibility to MSC2529 has failed, so i'm going to close it.

Meanwhile https://github.com/matrix-org/matrix-spec-proposals/pull/4231#pullrequestreview-2456786435 charts various possible ways forwards to fix the underlying problem of the lack of backwards compat in MSC2529 - I will open new MSCs as needed.

2024-11-26 17:34 UTC, closed without merging